#pragma once
#ifndef UE_CORE_INTELLISENSE_FIX
#define UE_CORE_INTELLISENSE_FIX
#include "BEHAVIOUR/BEHAVIOUR_INTERNAL.h" //Will be moved in next step to UPRISE_ENGINE_ECS
#include "COMPONENT/COMPONENT_INTERNAL.h" //Will be moved in next step to UPRISE_ENGINE_ECS
#include "CONCEPTS/ALIGN/CONCEPT_ALIGN_INTERNAL.h"
#include "CONCEPTS/SIZE/CONCEPT_SIZE_INTERNAL.h"
#include "CPUID/CPUID_INTERNAL.h"
#include "OBJECT/OBJECT_INTERNAL.h" // might be moved some day in the future to UPRISE_ENGINE_ECS. not sure tho
#include "REF_WRAPPERS/CONTROLL_BLOCKS/CONTROL_BASE/CONTROL_BASE_INTERNAL.h"
#include "REF_WRAPPERS/CONTROLL_BLOCKS/GC_CONTROLBLOCK/GC_CONTROLBLOCK_INTERNAL.h"
#include "REF_WRAPPERS/CONTROLL_BLOCKS/OWNED_CONTROLBLOCK/OWNED_CONTROLBLOCK_INTERNAL.h"
#include "REF_WRAPPERS/CONTROLL_BLOCKS/SHARED_CONTROL_BLOCK/SHARED_CONTROL_BLOCK_INTERNAL.h"
#include "REF_WRAPPERS/OWNED_REF/OWNED_REF_INTERNAL.h"
#include "REF_WRAPPERS/SHARED_REF/SHARED_REF_INTERNAL.h"
#include "REF_WRAPPERS/WEAK_REF/WEAK_REF_INTERNAL.h"
#include "REF_WRAPPERS/WRAPPER_BASE/WRAPPER_BASE_INTERNAL.h"
#include "SIMD_UTILLS/__M128/__M128_UTILLS_INTERNAL.h"
//#include "SIMD_UTILLS/__M256/__M256_UTILLS_INTERNAL.h" future proofing this file
//#include "SIMD_UTILLS/__M512/__M512_UTILLS_INTERNAL.h"  future proofing this file
//#include "THREADING/THREAD/" this will be added in the future
#include "ARRAY/ARRAY_INTERNAL.h"
#include "LAYER/LAYER_INTERNAL.h"
#include "MAT4/MAT4_INTERNAL.h"
#include "QUATERNION/QUATERNION_INTERNAL.h"
#include "STRING/STRING_INTERNAL.h"
//#include "STRING/UNICODE/" will be added in the future 
#include "TAG/TAG_INTERNAL.h"
#include "UUID/UUID_INTERNAL.h"
#include "VECTOR/VECTOR2/VECTOR2_INTERNAL.h"
#include "VECTOR/VECTOR3/VECTOR3_INTERNAL.h"
#include "VECTOR/VECTOR4/VECTOR4_INTERNAL.h"

#endif // !UE_CORE_INTELLISENSE_FIX
