<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <_PropertySheetDisplayName>props</_PropertySheetDisplayName>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_CORE\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_RENDER\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_PHYSICS\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_EE\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_ECS\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_DEBUG\HEADER;C:\Users\leo08\source\repos\UPRISE_ENGINE\SHARED_CODE\HEADER;C:\Users\leo08\source\repos\UPRISE_ENGINE\adhed;$(VULKAN_SDK)\Include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <AdditionalBMIDirectories>$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_CORE\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_RENDER\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_PHYSICS\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_EE\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_ECS\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_DEBUG\HEADER;C:\Users\leo08\source\repos\UPRISE_ENGINE\SHARED_CODE\HEADER;%(AdditionalIncludeDirectories)</AdditionalBMIDirectories>
      <Optimization>MaxSpeed</Optimization>
      <InlineFunctionExpansion>AnySuitable</InlineFunctionExpansion>
      <IntrinsicFunctions>true</IntrinsicFunctions>
      <FavorSizeOrSpeed>Speed</FavorSizeOrSpeed>
      <WholeProgramOptimization>true</WholeProgramOptimization>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
      <BasicRuntimeChecks>Default</BasicRuntimeChecks>
    </ClCompile>
    <Link>
      <LinkStatus>true</LinkStatus>
      <GenerateMapFile>true</GenerateMapFile>
      <OptimizeReferences>false</OptimizeReferences>
      <LinkTimeCodeGeneration>UseLinkTimeCodeGeneration</LinkTimeCodeGeneration>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>