<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup />
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_CORE\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_RENDER\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_PHYSICS\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_EE\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_ECS\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_DEBUG\HEADER;C:\Users\leo08\source\repos\UPRISE_ENGINE\SHARED_CODE\HEADER;C:\Users\leo08\source\repos\UPRISE_ENGINE\adhed;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <AdditionalBMIDirectories>$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_CORE\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_RENDER\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_PHYSICS\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_EE\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_ECS\HEADER;$(SolutionDir)UPRISE_ENGINE_MODULAR\UPRISE_ENGINE_DEBUG\HEADER;C:\Users\leo08\source\repos\UPRISE_ENGINE\SHARED_CODE\HEADER;%(AdditionalIncludeDirectories)</AdditionalBMIDirectories>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>