#pragma once
#ifndef GLADS_INTELLISENSE_FIX
#define GLADS_INTELLISENSE_FIX
#include "GLAD_CONSTANTS/CONSTANTS_PART_1/GLAD_CONSTANTS_PART_1_INTERNAL.h"
#include "GLAD_CONSTANTS/CONSTANTS_PART_2/CONSTANTS_PART_2_INTERNAL.h"
#include "GLAD_CONSTANTS/CONSTANTS_PART_3/GLAD_CONSTANTS_PART3_INTERNAL.h"
#include "GLAD_CONSTANTS/CONSTANTS_PART_4/GLAD_CONSTANTS_PART_4_INTERNAL.h"
#include "GLAD_CONSTANTS/CONSTANTS_PART_5/GLAD_CONSTANTS_PART_5_INTERNAL.h"
#include "GLAD_CONSTANTS/CONSTANTS_PART_6/GLAD_CONSTANTS_PART_6_INTERNAL.h"
#include "GLAD_CONSTANTS/CONSTANTS_PART_7/GLAD_CONSTANTS_PART_7.h"
#include "GLAD_GLOBALS/GLAD_GLOBALS_INTERNAL.h"
#include "OPENGL_VERSIONS/VERSION_ALL/OPENGL_VERSION_ALL_INTERNAL.h"
#include "STUPIDMACROS/GLAD_MACROS.h"
#endif // !GLADS_INTELLISENSE_FIX

