#pragma once
#ifndef UE_GLAD_CONSTANTS_PART_4_INTERNAL_
#define UE_GLAD_CONSTANTS_PART_4_INTERNAL_
#ifndef __INTELLISENSE__
#ifndef UE_OPENGL_BUILD_
#error "this file should not be directly included in user code. use import UPRISE_ENGINE_CORE instead"
#endif
#endif
#include "OPENGL/GLAD/STUPIDMACROS/GLAD_MACROS.h"
#ifdef __INTELLISENSE__
#ifndef DONT_INCLUDE_GLAD
#include <glad.h>
#endif
#endif // __INTELLISENSE__
namespace UPRISE_ENGINE {
    namespace RENDER {
        namespace GLAD {
            namespace CONSTANTS {
                constexpr int _GL_TEXTURE0 = 0x84C0;
                constexpr int _GL_TEXTURE1 = 0x84C1;
                constexpr int _GL_TEXTURE2 = 0x84C2;
                constexpr int _GL_TEXTURE3 = 0x84C3;
                constexpr int _GL_TEXTURE4 = 0x84C4;
                constexpr int _GL_TEXTURE5 = 0x84C5;
                constexpr int _GL_TEXTURE6 = 0x84C6;
                constexpr int _GL_TEXTURE7 = 0x84C7;
                constexpr int _GL_TEXTURE8 = 0x84C8;
                constexpr int _GL_TEXTURE9 = 0x84C9;
                constexpr int _GL_TEXTURE10 = 0x84CA;
                constexpr int _GL_TEXTURE11 = 0x84CB;
                constexpr int _GL_TEXTURE12 = 0x84CC;
                constexpr int _GL_TEXTURE13 = 0x84CD;
                constexpr int _GL_TEXTURE14 = 0x84CE;
                constexpr int _GL_TEXTURE15 = 0x84CF;
                constexpr int _GL_TEXTURE16 = 0x84D0;
                constexpr int _GL_TEXTURE17 = 0x84D1;
                constexpr int _GL_TEXTURE18 = 0x84D2;
                constexpr int _GL_TEXTURE19 = 0x84D3;
                constexpr int _GL_TEXTURE20 = 0x84D4;
                constexpr int _GL_TEXTURE21 = 0x84D5;
                constexpr int _GL_TEXTURE22 = 0x84D6;
                constexpr int _GL_TEXTURE23 = 0x84D7;
                constexpr int _GL_TEXTURE24 = 0x84D8;
                constexpr int _GL_TEXTURE25 = 0x84D9;
                constexpr int _GL_TEXTURE26 = 0x84DA;
                constexpr int _GL_TEXTURE27 = 0x84DB;
                constexpr int _GL_TEXTURE28 = 0x84DC;
                constexpr int _GL_TEXTURE29 = 0x84DD;
                constexpr int _GL_TEXTURE30 = 0x84DE;
                constexpr int _GL_TEXTURE31 = 0x84DF;
                constexpr int _GL_ACTIVE_TEXTURE = 0x84E0;
                constexpr int _GL_MULTISAMPLE = 0x809D;
                constexpr int _GL_SAMPLE_ALPHA_TO_COVERAGE = 0x809E;
                constexpr int _GL_SAMPLE_ALPHA_TO_ONE = 0x809F;
                constexpr int _GL_SAMPLE_COVERAGE = 0x80A0;
                constexpr int _GL_SAMPLE_BUFFERS = 0x80A8;
                constexpr int _GL_SAMPLES = 0x80A9;
                constexpr int _GL_SAMPLE_COVERAGE_VALUE = 0x80AA;
                constexpr int _GL_SAMPLE_COVERAGE_INVERT = 0x80AB;
                constexpr int _GL_TEXTURE_CUBE_MAP = 0x8513;
                constexpr int _GL_TEXTURE_BINDING_CUBE_MAP = 0x8514;
                constexpr int _GL_TEXTURE_CUBE_MAP_POSITIVE_X = 0x8515;
                constexpr int _GL_TEXTURE_CUBE_MAP_NEGATIVE_X = 0x8516;
                constexpr int _GL_TEXTURE_CUBE_MAP_POSITIVE_Y = 0x8517;
                constexpr int _GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = 0x8518;
                constexpr int _GL_TEXTURE_CUBE_MAP_POSITIVE_Z = 0x8519;
                constexpr int _GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = 0x851A;
                constexpr int _GL_PROXY_TEXTURE_CUBE_MAP = 0x851B;
                constexpr int _GL_MAX_CUBE_MAP_TEXTURE_SIZE = 0x851C;
                constexpr int _GL_COMPRESSED_RGB = 0x84ED;
                constexpr int _GL_COMPRESSED_RGBA = 0x84EE;
                constexpr int _GL_TEXTURE_COMPRESSION_HINT = 0x84EF;
                constexpr int _GL_TEXTURE_COMPRESSED_IMAGE_SIZE = 0x86A0;
                constexpr int _GL_TEXTURE_COMPRESSED = 0x86A1;
                constexpr int _GL_NUM_COMPRESSED_TEXTURE_FORMATS = 0x86A2;
                constexpr int _GL_COMPRESSED_TEXTURE_FORMATS = 0x86A3;
                constexpr int _GL_CLAMP_TO_BORDER = 0x812D;
                constexpr int _GL_BLEND_DST_RGB = 0x80C8;
                constexpr int _GL_BLEND_SRC_RGB = 0x80C9;
                constexpr int _GL_BLEND_DST_ALPHA = 0x80CA;
                constexpr int _GL_BLEND_SRC_ALPHA = 0x80CB;
                constexpr int _GL_POINT_FADE_THRESHOLD_SIZE = 0x8128;
                constexpr int _GL_DEPTH_COMPONENT16 = 0x81A5;
                constexpr int _GL_DEPTH_COMPONENT24 = 0x81A6;
                constexpr int _GL_DEPTH_COMPONENT32 = 0x81A7;
                constexpr int _GL_MIRRORED_REPEAT = 0x8370;
                constexpr int _GL_MAX_TEXTURE_LOD_BIAS = 0x84FD;
                constexpr int _GL_TEXTURE_LOD_BIAS = 0x8501;
                constexpr int _GL_INCR_WRAP = 0x8507;
                constexpr int _GL_DECR_WRAP = 0x8508;
                constexpr int _GL_TEXTURE_DEPTH_SIZE = 0x884A;
                constexpr int _GL_TEXTURE_COMPARE_MODE = 0x884C;
                constexpr int _GL_TEXTURE_COMPARE_FUNC = 0x884D;
                constexpr int _GL_BLEND_COLOR = 0x8005;
                constexpr int _GL_BLEND_EQUATION = 0x8009;
                constexpr int _GL_CONSTANT_COLOR = 0x8001;
                constexpr int _GL_ONE_MINUS_CONSTANT_COLOR = 0x8002;
                constexpr int _GL_CONSTANT_ALPHA = 0x8003;
                constexpr int _GL_ONE_MINUS_CONSTANT_ALPHA = 0x8004;
                constexpr int _GL_FUNC_ADD = 0x8006;
                constexpr int _GL_FUNC_REVERSE_SUBTRACT = 0x800B;
                constexpr int _GL_FUNC_SUBTRACT = 0x800A;
                constexpr int _GL_MIN = 0x8007;
                constexpr int _GL_MAX = 0x8008;
                constexpr int _GL_BUFFER_SIZE = 0x8764;
                constexpr int _GL_BUFFER_USAGE = 0x8765;
                constexpr int _GL_QUERY_COUNTER_BITS = 0x8864;
                constexpr int _GL_CURRENT_QUERY = 0x8865;
                constexpr int _GL_QUERY_RESULT = 0x8866;
                constexpr int _GL_QUERY_RESULT_AVAILABLE = 0x8867;
                constexpr int _GL_ARRAY_BUFFER = 0x8892;
                constexpr int _GL_ELEMENT_ARRAY_BUFFER = 0x8893;
                constexpr int _GL_ARRAY_BUFFER_BINDING = 0x8894;
                constexpr int _GL_ELEMENT_ARRAY_BUFFER_BINDING = 0x8895;
                constexpr int _GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 0x889F;
                constexpr int _GL_READ_ONLY = 0x88B8;
                constexpr int _GL_WRITE_ONLY = 0x88B9;
                constexpr int _GL_READ_WRITE = 0x88BA;
                constexpr int _GL_BUFFER_ACCESS = 0x88BB;
                constexpr int _GL_BUFFER_MAPPED = 0x88BC;
                constexpr int _GL_BUFFER_MAP_POINTER = 0x88BD;
                constexpr int _GL_STREAM_DRAW = 0x88E0;
                constexpr int _GL_STREAM_READ = 0x88E1;
                constexpr int _GL_STREAM_COPY = 0x88E2;
                constexpr int _GL_STATIC_DRAW = 0x88E4;
                constexpr int _GL_STATIC_READ = 0x88E5;
                constexpr int _GL_STATIC_COPY = 0x88E6;
                constexpr int _GL_DYNAMIC_DRAW = 0x88E8;
                constexpr int _GL_DYNAMIC_READ = 0x88E9;
                constexpr int _GL_DYNAMIC_COPY = 0x88EA;
                constexpr int _GL_SAMPLES_PASSED = 0x8914;
                constexpr int _GL_SRC1_ALPHA = 0x8589;
                constexpr int _GL_BLEND_EQUATION_RGB = 0x8009;
                constexpr int _GL_VERTEX_ATTRIB_ARRAY_ENABLED = 0x8622;
                constexpr int _GL_VERTEX_ATTRIB_ARRAY_SIZE = 0x8623;
                constexpr int _GL_VERTEX_ATTRIB_ARRAY_STRIDE = 0x8624;
                constexpr int _GL_VERTEX_ATTRIB_ARRAY_TYPE = 0x8625;
                constexpr int _GL_CURRENT_VERTEX_ATTRIB = 0x8626;
                constexpr int _GL_VERTEX_PROGRAM_POINT_SIZE = 0x8642;
                constexpr int _GL_VERTEX_ATTRIB_ARRAY_POINTER = 0x8645;
                constexpr int _GL_STENCIL_BACK_FUNC = 0x8800;
                constexpr int _GL_STENCIL_BACK_FAIL = 0x8801;
                constexpr int _GL_STENCIL_BACK_PASS_DEPTH_FAIL = 0x8802;
                constexpr int _GL_STENCIL_BACK_PASS_DEPTH_PASS = 0x8803;
                constexpr int _GL_MAX_DRAW_BUFFERS = 0x8824;
                constexpr int _GL_DRAW_BUFFER0 = 0x8825;
                constexpr int _GL_DRAW_BUFFER1 = 0x8826;
                constexpr int _GL_DRAW_BUFFER2 = 0x8827;
                constexpr int _GL_DRAW_BUFFER3 = 0x8828;
                constexpr int _GL_DRAW_BUFFER4 = 0x8829;
                constexpr int _GL_DRAW_BUFFER5 = 0x882A;
                constexpr int _GL_DRAW_BUFFER6 = 0x882B;
                constexpr int _GL_DRAW_BUFFER7 = 0x882C;
                constexpr int _GL_DRAW_BUFFER8 = 0x882D;
                constexpr int _GL_DRAW_BUFFER9 = 0x882E;
                constexpr int _GL_DRAW_BUFFER10 = 0x882F;
                constexpr int _GL_DRAW_BUFFER11 = 0x8830;
                constexpr int _GL_DRAW_BUFFER12 = 0x8831;
                constexpr int _GL_DRAW_BUFFER13 = 0x8832;
                constexpr int _GL_DRAW_BUFFER14 = 0x8833;
                constexpr int _GL_DRAW_BUFFER15 = 0x8834;
                constexpr int _GL_BLEND_EQUATION_ALPHA = 0x883D;
                constexpr int _GL_MAX_VERTEX_ATTRIBS = 0x8869;
                constexpr int _GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = 0x886A;
                constexpr int _GL_MAX_TEXTURE_IMAGE_UNITS = 0x8872;
                constexpr int _GL_FRAGMENT_SHADER = 0x8B30;
                constexpr int _GL_VERTEX_SHADER = 0x8B31;
                constexpr int _GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 0x8B49;
                constexpr int _GL_MAX_VERTEX_UNIFORM_COMPONENTS = 0x8B4A;
                constexpr int _GL_MAX_VARYING_FLOATS = 0x8B4B;
                constexpr int _GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 0x8B4C;
                constexpr int _GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 0x8B4D;
                constexpr int _GL_SHADER_TYPE = 0x8B4F;
#ifndef DONT_INCLUDE_GLAD
                consteval void CheckConstantsPart4() {
                    static_assert(_GL_TEXTURE0 == GL_TEXTURE0, "_GL_TEXTURE0 is not equal to GL_TEXTURE0");
                    static_assert(_GL_TEXTURE1 == GL_TEXTURE1, "_GL_TEXTURE1 is not equal to GL_TEXTURE1");
                    static_assert(_GL_TEXTURE2 == GL_TEXTURE2, "_GL_TEXTURE2 is not equal to GL_TEXTURE2");
                    static_assert(_GL_TEXTURE3 == GL_TEXTURE3, "_GL_TEXTURE3 is not equal to GL_TEXTURE3");
                    static_assert(_GL_TEXTURE4 == GL_TEXTURE4, "_GL_TEXTURE4 is not equal to GL_TEXTURE4");
                    static_assert(_GL_TEXTURE5 == GL_TEXTURE5, "_GL_TEXTURE5 is not equal to GL_TEXTURE5");
                    static_assert(_GL_TEXTURE6 == GL_TEXTURE6, "_GL_TEXTURE6 is not equal to GL_TEXTURE6");
                    static_assert(_GL_TEXTURE7 == GL_TEXTURE7, "_GL_TEXTURE7 is not equal to GL_TEXTURE7");
                    static_assert(_GL_TEXTURE8 == GL_TEXTURE8, "_GL_TEXTURE8 is not equal to GL_TEXTURE8");
                    static_assert(_GL_TEXTURE9 == GL_TEXTURE9, "_GL_TEXTURE9 is not equal to GL_TEXTURE9");
                    static_assert(_GL_TEXTURE10 == GL_TEXTURE10, "_GL_TEXTURE10 is not equal to GL_TEXTURE10");
                    static_assert(_GL_TEXTURE11 == GL_TEXTURE11, "_GL_TEXTURE11 is not equal to GL_TEXTURE11");
                    static_assert(_GL_TEXTURE12 == GL_TEXTURE12, "_GL_TEXTURE12 is not equal to GL_TEXTURE12");
                    static_assert(_GL_TEXTURE13 == GL_TEXTURE13, "_GL_TEXTURE13 is not equal to GL_TEXTURE13");
                    static_assert(_GL_TEXTURE14 == GL_TEXTURE14, "_GL_TEXTURE14 is not equal to GL_TEXTURE14");
                    static_assert(_GL_TEXTURE15 == GL_TEXTURE15, "_GL_TEXTURE15 is not equal to GL_TEXTURE15");
                    static_assert(_GL_TEXTURE16 == GL_TEXTURE16, "_GL_TEXTURE16 is not equal to GL_TEXTURE16");
                    static_assert(_GL_TEXTURE17 == GL_TEXTURE17, "_GL_TEXTURE17 is not equal to GL_TEXTURE17");
                    static_assert(_GL_TEXTURE18 == GL_TEXTURE18, "_GL_TEXTURE18 is not equal to GL_TEXTURE18");
                    static_assert(_GL_TEXTURE19 == GL_TEXTURE19, "_GL_TEXTURE19 is not equal to GL_TEXTURE19");
                    static_assert(_GL_TEXTURE20 == GL_TEXTURE20, "_GL_TEXTURE20 is not equal to GL_TEXTURE20");
                    static_assert(_GL_TEXTURE21 == GL_TEXTURE21, "_GL_TEXTURE21 is not equal to GL_TEXTURE21");
                    static_assert(_GL_TEXTURE22 == GL_TEXTURE22, "_GL_TEXTURE22 is not equal to GL_TEXTURE22");
                    static_assert(_GL_TEXTURE23 == GL_TEXTURE23, "_GL_TEXTURE23 is not equal to GL_TEXTURE23");
                    static_assert(_GL_TEXTURE24 == GL_TEXTURE24, "_GL_TEXTURE24 is not equal to GL_TEXTURE24");
                    static_assert(_GL_TEXTURE25 == GL_TEXTURE25, "_GL_TEXTURE25 is not equal to GL_TEXTURE25");
                    static_assert(_GL_TEXTURE26 == GL_TEXTURE26, "_GL_TEXTURE26 is not equal to GL_TEXTURE26");
                    static_assert(_GL_TEXTURE27 == GL_TEXTURE27, "_GL_TEXTURE27 is not equal to GL_TEXTURE27");
                    static_assert(_GL_TEXTURE28 == GL_TEXTURE28, "_GL_TEXTURE28 is not equal to GL_TEXTURE28");
                    static_assert(_GL_TEXTURE29 == GL_TEXTURE29, "_GL_TEXTURE29 is not equal to GL_TEXTURE29");
                    static_assert(_GL_TEXTURE30 == GL_TEXTURE30, "_GL_TEXTURE30 is not equal to GL_TEXTURE30");
                    static_assert(_GL_TEXTURE31 == GL_TEXTURE31, "_GL_TEXTURE31 is not equal to GL_TEXTURE31");
                    static_assert(_GL_ACTIVE_TEXTURE == GL_ACTIVE_TEXTURE, "_GL_ACTIVE_TEXTURE is not equal to GL_ACTIVE_TEXTURE");
                    static_assert(_GL_MULTISAMPLE == GL_MULTISAMPLE, "_GL_MULTISAMPLE is not equal to GL_MULTISAMPLE");
                    static_assert(_GL_SAMPLE_ALPHA_TO_COVERAGE == GL_SAMPLE_ALPHA_TO_COVERAGE, "_GL_SAMPLE_ALPHA_TO_COVERAGE is not equal to GL_SAMPLE_ALPHA_TO_COVERAGE");
                    static_assert(_GL_SAMPLE_ALPHA_TO_ONE == GL_SAMPLE_ALPHA_TO_ONE, "_GL_SAMPLE_ALPHA_TO_ONE is not equal to GL_SAMPLE_ALPHA_TO_ONE");
                    static_assert(_GL_SAMPLE_COVERAGE == GL_SAMPLE_COVERAGE, "_GL_SAMPLE_COVERAGE is not equal to GL_SAMPLE_COVERAGE");
                    static_assert(_GL_SAMPLE_BUFFERS == GL_SAMPLE_BUFFERS, "_GL_SAMPLE_BUFFERS is not equal to GL_SAMPLE_BUFFERS");
                    static_assert(_GL_SAMPLES == GL_SAMPLES, "_GL_SAMPLES is not equal to GL_SAMPLES");
                    static_assert(_GL_SAMPLE_COVERAGE_VALUE == GL_SAMPLE_COVERAGE_VALUE, "_GL_SAMPLE_COVERAGE_VALUE is not equal to GL_SAMPLE_COVERAGE_VALUE");
                    static_assert(_GL_SAMPLE_COVERAGE_INVERT == GL_SAMPLE_COVERAGE_INVERT, "_GL_SAMPLE_COVERAGE_INVERT is not equal to GL_SAMPLE_COVERAGE_INVERT");
                    static_assert(_GL_TEXTURE_CUBE_MAP == GL_TEXTURE_CUBE_MAP, "_GL_TEXTURE_CUBE_MAP is not equal to GL_TEXTURE_CUBE_MAP");
                    static_assert(_GL_TEXTURE_BINDING_CUBE_MAP == GL_TEXTURE_BINDING_CUBE_MAP, "_GL_TEXTURE_BINDING_CUBE_MAP is not equal to GL_TEXTURE_BINDING_CUBE_MAP");
                    static_assert(_GL_TEXTURE_CUBE_MAP_POSITIVE_X == GL_TEXTURE_CUBE_MAP_POSITIVE_X, "_GL_TEXTURE_CUBE_MAP_POSITIVE_X is not equal to GL_TEXTURE_CUBE_MAP_POSITIVE_X");
                    static_assert(_GL_TEXTURE_CUBE_MAP_NEGATIVE_X == GL_TEXTURE_CUBE_MAP_NEGATIVE_X, "_GL_TEXTURE_CUBE_MAP_NEGATIVE_X is not equal to GL_TEXTURE_CUBE_MAP_NEGATIVE_X");
                    static_assert(_GL_TEXTURE_CUBE_MAP_POSITIVE_Y == GL_TEXTURE_CUBE_MAP_POSITIVE_Y, "_GL_TEXTURE_CUBE_MAP_POSITIVE_Y is not equal to GL_TEXTURE_CUBE_MAP_POSITIVE_Y");
                    static_assert(_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y == GL_TEXTURE_CUBE_MAP_NEGATIVE_Y, "_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y is not equal to GL_TEXTURE_CUBE_MAP_NEGATIVE_Y");
                    static_assert(_GL_TEXTURE_CUBE_MAP_POSITIVE_Z == GL_TEXTURE_CUBE_MAP_POSITIVE_Z, "_GL_TEXTURE_CUBE_MAP_POSITIVE_Z is not equal to GL_TEXTURE_CUBE_MAP_POSITIVE_Z");
                    static_assert(_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z == GL_TEXTURE_CUBE_MAP_NEGATIVE_Z, "_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z is not equal to GL_TEXTURE_CUBE_MAP_NEGATIVE_Z");
                    static_assert(_GL_PROXY_TEXTURE_CUBE_MAP == GL_PROXY_TEXTURE_CUBE_MAP, "_GL_PROXY_TEXTURE_CUBE_MAP is not equal to GL_PROXY_TEXTURE_CUBE_MAP");
                    static_assert(_GL_MAX_CUBE_MAP_TEXTURE_SIZE == GL_MAX_CUBE_MAP_TEXTURE_SIZE, "_GL_MAX_CUBE_MAP_TEXTURE_SIZE is not equal to GL_MAX_CUBE_MAP_TEXTURE_SIZE");
                    static_assert(_GL_COMPRESSED_RGB == GL_COMPRESSED_RGB, "_GL_COMPRESSED_RGB is not equal to GL_COMPRESSED_RGB");
                    static_assert(_GL_COMPRESSED_RGBA == GL_COMPRESSED_RGBA, "_GL_COMPRESSED_RGBA is not equal to GL_COMPRESSED_RGBA");
                    static_assert(_GL_TEXTURE_COMPRESSION_HINT == GL_TEXTURE_COMPRESSION_HINT, "_GL_TEXTURE_COMPRESSION_HINT is not equal to GL_TEXTURE_COMPRESSION_HINT");
                    static_assert(_GL_TEXTURE_COMPRESSED_IMAGE_SIZE == GL_TEXTURE_COMPRESSED_IMAGE_SIZE, "_GL_TEXTURE_COMPRESSED_IMAGE_SIZE is not equal to GL_TEXTURE_COMPRESSED_IMAGE_SIZE");
                    static_assert(_GL_TEXTURE_COMPRESSED == GL_TEXTURE_COMPRESSED, "_GL_TEXTURE_COMPRESSED is not equal to GL_TEXTURE_COMPRESSED");
                    static_assert(_GL_NUM_COMPRESSED_TEXTURE_FORMATS == GL_NUM_COMPRESSED_TEXTURE_FORMATS, "_GL_NUM_COMPRESSED_TEXTURE_FORMATS is not equal to GL_NUM_COMPRESSED_TEXTURE_FORMATS");
                    static_assert(_GL_COMPRESSED_TEXTURE_FORMATS == GL_COMPRESSED_TEXTURE_FORMATS, "_GL_COMPRESSED_TEXTURE_FORMATS is not equal to GL_COMPRESSED_TEXTURE_FORMATS");
                    static_assert(_GL_CLAMP_TO_BORDER == GL_CLAMP_TO_BORDER, "_GL_CLAMP_TO_BORDER is not equal to GL_CLAMP_TO_BORDER");
                    static_assert(_GL_BLEND_DST_RGB == GL_BLEND_DST_RGB, "_GL_BLEND_DST_RGB is not equal to GL_BLEND_DST_RGB");
                    static_assert(_GL_BLEND_SRC_RGB == GL_BLEND_SRC_RGB, "_GL_BLEND_SRC_RGB is not equal to GL_BLEND_SRC_RGB");
                    static_assert(_GL_BLEND_DST_ALPHA == GL_BLEND_DST_ALPHA, "_GL_BLEND_DST_ALPHA is not equal to GL_BLEND_DST_ALPHA");
                    static_assert(_GL_BLEND_SRC_ALPHA == GL_BLEND_SRC_ALPHA, "_GL_BLEND_SRC_ALPHA is not equal to GL_BLEND_SRC_ALPHA");
                    static_assert(_GL_POINT_FADE_THRESHOLD_SIZE == GL_POINT_FADE_THRESHOLD_SIZE, "_GL_POINT_FADE_THRESHOLD_SIZE is not equal to GL_POINT_FADE_THRESHOLD_SIZE");
                    static_assert(_GL_DEPTH_COMPONENT16 == GL_DEPTH_COMPONENT16, "_GL_DEPTH_COMPONENT16 is not equal to GL_DEPTH_COMPONENT16");
                    static_assert(_GL_DEPTH_COMPONENT24 == GL_DEPTH_COMPONENT24, "_GL_DEPTH_COMPONENT24 is not equal to GL_DEPTH_COMPONENT24");
                    static_assert(_GL_DEPTH_COMPONENT32 == GL_DEPTH_COMPONENT32, "_GL_DEPTH_COMPONENT32 is not equal to GL_DEPTH_COMPONENT32");
                    static_assert(_GL_MIRRORED_REPEAT == GL_MIRRORED_REPEAT, "_GL_MIRRORED_REPEAT is not equal to GL_MIRRORED_REPEAT");
                    static_assert(_GL_MAX_TEXTURE_LOD_BIAS == GL_MAX_TEXTURE_LOD_BIAS, "_GL_MAX_TEXTURE_LOD_BIAS is not equal to GL_MAX_TEXTURE_LOD_BIAS");
                    static_assert(_GL_TEXTURE_LOD_BIAS == GL_TEXTURE_LOD_BIAS, "_GL_TEXTURE_LOD_BIAS is not equal to GL_TEXTURE_LOD_BIAS");
                    static_assert(_GL_INCR_WRAP == GL_INCR_WRAP, "_GL_INCR_WRAP is not equal to GL_INCR_WRAP");
                    static_assert(_GL_DECR_WRAP == GL_DECR_WRAP, "_GL_DECR_WRAP is not equal to GL_DECR_WRAP");
                    static_assert(_GL_TEXTURE_DEPTH_SIZE == GL_TEXTURE_DEPTH_SIZE, "_GL_TEXTURE_DEPTH_SIZE is not equal to GL_TEXTURE_DEPTH_SIZE");
                    static_assert(_GL_TEXTURE_COMPARE_MODE == GL_TEXTURE_COMPARE_MODE, "_GL_TEXTURE_COMPARE_MODE is not equal to GL_TEXTURE_COMPARE_MODE");
                    static_assert(_GL_TEXTURE_COMPARE_FUNC == GL_TEXTURE_COMPARE_FUNC, "_GL_TEXTURE_COMPARE_FUNC is not equal to GL_TEXTURE_COMPARE_FUNC");
                    static_assert(_GL_BLEND_COLOR == GL_BLEND_COLOR, "_GL_BLEND_COLOR is not equal to GL_BLEND_COLOR");
                    static_assert(_GL_BLEND_EQUATION == GL_BLEND_EQUATION, "_GL_BLEND_EQUATION is not equal to GL_BLEND_EQUATION");
                    static_assert(_GL_CONSTANT_COLOR == GL_CONSTANT_COLOR, "_GL_CONSTANT_COLOR is not equal to GL_CONSTANT_COLOR");
                    static_assert(_GL_ONE_MINUS_CONSTANT_COLOR == GL_ONE_MINUS_CONSTANT_COLOR, "_GL_ONE_MINUS_CONSTANT_COLOR is not equal to GL_ONE_MINUS_CONSTANT_COLOR");
                    static_assert(_GL_CONSTANT_ALPHA == GL_CONSTANT_ALPHA, "_GL_CONSTANT_ALPHA is not equal to GL_CONSTANT_ALPHA");
                    static_assert(_GL_ONE_MINUS_CONSTANT_ALPHA == GL_ONE_MINUS_CONSTANT_ALPHA, "_GL_ONE_MINUS_CONSTANT_ALPHA is not equal to GL_ONE_MINUS_CONSTANT_ALPHA");
                    static_assert(_GL_FUNC_ADD == GL_FUNC_ADD, "_GL_FUNC_ADD is not equal to GL_FUNC_ADD");
                    static_assert(_GL_FUNC_REVERSE_SUBTRACT == GL_FUNC_REVERSE_SUBTRACT, "_GL_FUNC_REVERSE_SUBTRACT is not equal to GL_FUNC_REVERSE_SUBTRACT");
                    static_assert(_GL_FUNC_SUBTRACT == GL_FUNC_SUBTRACT, "_GL_FUNC_SUBTRACT is not equal to GL_FUNC_SUBTRACT");
                    static_assert(_GL_MIN == GL_MIN, "_GL_MIN is not equal to GL_MIN");
                    static_assert(_GL_MAX == GL_MAX, "_GL_MAX is not equal to GL_MAX");
                    static_assert(_GL_BUFFER_SIZE == GL_BUFFER_SIZE, "_GL_BUFFER_SIZE is not equal to GL_BUFFER_SIZE");
                    static_assert(_GL_BUFFER_USAGE == GL_BUFFER_USAGE, "_GL_BUFFER_USAGE is not equal to GL_BUFFER_USAGE");
                    static_assert(_GL_QUERY_COUNTER_BITS == GL_QUERY_COUNTER_BITS, "_GL_QUERY_COUNTER_BITS is not equal to GL_QUERY_COUNTER_BITS");
                    static_assert(_GL_CURRENT_QUERY == GL_CURRENT_QUERY, "_GL_CURRENT_QUERY is not equal to GL_CURRENT_QUERY");
                    static_assert(_GL_QUERY_RESULT == GL_QUERY_RESULT, "_GL_QUERY_RESULT is not equal to GL_QUERY_RESULT");
                    static_assert(_GL_QUERY_RESULT_AVAILABLE == GL_QUERY_RESULT_AVAILABLE, "_GL_QUERY_RESULT_AVAILABLE is not equal to GL_QUERY_RESULT_AVAILABLE");
                    static_assert(_GL_ARRAY_BUFFER == GL_ARRAY_BUFFER, "_GL_ARRAY_BUFFER is not equal to GL_ARRAY_BUFFER");
                    static_assert(_GL_ELEMENT_ARRAY_BUFFER == GL_ELEMENT_ARRAY_BUFFER, "_GL_ELEMENT_ARRAY_BUFFER is not equal to GL_ELEMENT_ARRAY_BUFFER");
                    static_assert(_GL_ARRAY_BUFFER_BINDING == GL_ARRAY_BUFFER_BINDING, "_GL_ARRAY_BUFFER_BINDING is not equal to GL_ARRAY_BUFFER_BINDING");
                    static_assert(_GL_ELEMENT_ARRAY_BUFFER_BINDING == GL_ELEMENT_ARRAY_BUFFER_BINDING, "_GL_ELEMENT_ARRAY_BUFFER_BINDING is not equal to GL_ELEMENT_ARRAY_BUFFER_BINDING");
                    static_assert(_GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING == GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING, "_GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING is not equal to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING");
                    static_assert(_GL_READ_ONLY == GL_READ_ONLY, "_GL_READ_ONLY is not equal to GL_READ_ONLY");
                    static_assert(_GL_WRITE_ONLY == GL_WRITE_ONLY, "_GL_WRITE_ONLY is not equal to GL_WRITE_ONLY");
                    static_assert(_GL_READ_WRITE == GL_READ_WRITE, "_GL_READ_WRITE is not equal to GL_READ_WRITE");
                    static_assert(_GL_BUFFER_ACCESS == GL_BUFFER_ACCESS, "_GL_BUFFER_ACCESS is not equal to GL_BUFFER_ACCESS");
                    static_assert(_GL_BUFFER_MAPPED == GL_BUFFER_MAPPED, "_GL_BUFFER_MAPPED is not equal to GL_BUFFER_MAPPED");
                    static_assert(_GL_BUFFER_MAP_POINTER == GL_BUFFER_MAP_POINTER, "_GL_BUFFER_MAP_POINTER is not equal to GL_BUFFER_MAP_POINTER");
                    static_assert(_GL_STREAM_DRAW == GL_STREAM_DRAW, "_GL_STREAM_DRAW is not equal to GL_STREAM_DRAW");
                    static_assert(_GL_STREAM_READ == GL_STREAM_READ, "_GL_STREAM_READ is not equal to GL_STREAM_READ");
                    static_assert(_GL_STREAM_COPY == GL_STREAM_COPY, "_GL_STREAM_COPY is not equal to GL_STREAM_COPY");
                    static_assert(_GL_STATIC_DRAW == GL_STATIC_DRAW, "_GL_STATIC_DRAW is not equal to GL_STATIC_DRAW");
                    static_assert(_GL_STATIC_READ == GL_STATIC_READ, "_GL_STATIC_READ is not equal to GL_STATIC_READ");
                    static_assert(_GL_STATIC_COPY == GL_STATIC_COPY, "_GL_STATIC_COPY is not equal to GL_STATIC_COPY");
                    static_assert(_GL_DYNAMIC_DRAW == GL_DYNAMIC_DRAW, "_GL_DYNAMIC_DRAW is not equal to GL_DYNAMIC_DRAW");
                    static_assert(_GL_DYNAMIC_READ == GL_DYNAMIC_READ, "_GL_DYNAMIC_READ is not equal to GL_DYNAMIC_READ");
                    static_assert(_GL_DYNAMIC_COPY == GL_DYNAMIC_COPY, "_GL_DYNAMIC_COPY is not equal to GL_DYNAMIC_COPY");
                    static_assert(_GL_SAMPLES_PASSED == GL_SAMPLES_PASSED, "_GL_SAMPLES_PASSED is not equal to GL_SAMPLES_PASSED");
                    static_assert(_GL_SRC1_ALPHA == GL_SRC1_ALPHA, "_GL_SRC1_ALPHA is not equal to GL_SRC1_ALPHA");
                    static_assert(_GL_BLEND_EQUATION_RGB == GL_BLEND_EQUATION_RGB, "_GL_BLEND_EQUATION_RGB is not equal to GL_BLEND_EQUATION_RGB");
                    static_assert(_GL_VERTEX_ATTRIB_ARRAY_ENABLED == GL_VERTEX_ATTRIB_ARRAY_ENABLED, "_GL_VERTEX_ATTRIB_ARRAY_ENABLED is not equal to GL_VERTEX_ATTRIB_ARRAY_ENABLED");
                    static_assert(_GL_VERTEX_ATTRIB_ARRAY_SIZE == GL_VERTEX_ATTRIB_ARRAY_SIZE, "_GL_VERTEX_ATTRIB_ARRAY_SIZE is not equal to GL_VERTEX_ATTRIB_ARRAY_SIZE");
                    static_assert(_GL_VERTEX_ATTRIB_ARRAY_STRIDE == GL_VERTEX_ATTRIB_ARRAY_STRIDE, "_GL_VERTEX_ATTRIB_ARRAY_STRIDE is not equal to GL_VERTEX_ATTRIB_ARRAY_STRIDE");
                    static_assert(_GL_VERTEX_ATTRIB_ARRAY_TYPE == GL_VERTEX_ATTRIB_ARRAY_TYPE, "_GL_VERTEX_ATTRIB_ARRAY_TYPE is not equal to GL_VERTEX_ATTRIB_ARRAY_TYPE");
                    static_assert(_GL_CURRENT_VERTEX_ATTRIB == GL_CURRENT_VERTEX_ATTRIB, "_GL_CURRENT_VERTEX_ATTRIB is not equal to GL_CURRENT_VERTEX_ATTRIB");
                    static_assert(_GL_VERTEX_PROGRAM_POINT_SIZE == GL_VERTEX_PROGRAM_POINT_SIZE, "_GL_VERTEX_PROGRAM_POINT_SIZE is not equal to GL_VERTEX_PROGRAM_POINT_SIZE");
                    static_assert(_GL_VERTEX_ATTRIB_ARRAY_POINTER == GL_VERTEX_ATTRIB_ARRAY_POINTER, "_GL_VERTEX_ATTRIB_ARRAY_POINTER is not equal to GL_VERTEX_ATTRIB_ARRAY_POINTER");
                    static_assert(_GL_STENCIL_BACK_FUNC == GL_STENCIL_BACK_FUNC, "_GL_STENCIL_BACK_FUNC is not equal to GL_STENCIL_BACK_FUNC");
                    static_assert(_GL_STENCIL_BACK_FAIL == GL_STENCIL_BACK_FAIL, "_GL_STENCIL_BACK_FAIL is not equal to GL_STENCIL_BACK_FAIL");
                    static_assert(_GL_STENCIL_BACK_PASS_DEPTH_FAIL == GL_STENCIL_BACK_PASS_DEPTH_FAIL, "_GL_STENCIL_BACK_PASS_DEPTH_FAIL is not equal to GL_STENCIL_BACK_PASS_DEPTH_FAIL");
                    static_assert(_GL_STENCIL_BACK_PASS_DEPTH_PASS == GL_STENCIL_BACK_PASS_DEPTH_PASS, "_GL_STENCIL_BACK_PASS_DEPTH_PASS is not equal to GL_STENCIL_BACK_PASS_DEPTH_PASS");
                    static_assert(_GL_MAX_DRAW_BUFFERS == GL_MAX_DRAW_BUFFERS, "_GL_MAX_DRAW_BUFFERS is not equal to GL_MAX_DRAW_BUFFERS");
                    static_assert(_GL_DRAW_BUFFER0 == GL_DRAW_BUFFER0, "_GL_DRAW_BUFFER0 is not equal to GL_DRAW_BUFFER0");
                    static_assert(_GL_DRAW_BUFFER1 == GL_DRAW_BUFFER1, "_GL_DRAW_BUFFER1 is not equal to GL_DRAW_BUFFER1");
                    static_assert(_GL_DRAW_BUFFER2 == GL_DRAW_BUFFER2, "_GL_DRAW_BUFFER2 is not equal to GL_DRAW_BUFFER2");
                    static_assert(_GL_DRAW_BUFFER3 == GL_DRAW_BUFFER3, "_GL_DRAW_BUFFER3 is not equal to GL_DRAW_BUFFER3");
                    static_assert(_GL_DRAW_BUFFER4 == GL_DRAW_BUFFER4, "_GL_DRAW_BUFFER4 is not equal to GL_DRAW_BUFFER4");
                    static_assert(_GL_DRAW_BUFFER5 == GL_DRAW_BUFFER5, "_GL_DRAW_BUFFER5 is not equal to GL_DRAW_BUFFER5");
                    static_assert(_GL_DRAW_BUFFER6 == GL_DRAW_BUFFER6, "_GL_DRAW_BUFFER6 is not equal to GL_DRAW_BUFFER6");
                    static_assert(_GL_DRAW_BUFFER7 == GL_DRAW_BUFFER7, "_GL_DRAW_BUFFER7 is not equal to GL_DRAW_BUFFER7");
                    static_assert(_GL_DRAW_BUFFER8 == GL_DRAW_BUFFER8, "_GL_DRAW_BUFFER8 is not equal to GL_DRAW_BUFFER8");
                    static_assert(_GL_DRAW_BUFFER9 == GL_DRAW_BUFFER9, "_GL_DRAW_BUFFER9 is not equal to GL_DRAW_BUFFER9");
                    static_assert(_GL_DRAW_BUFFER10 == GL_DRAW_BUFFER10, "_GL_DRAW_BUFFER10 is not equal to GL_DRAW_BUFFER10");
                    static_assert(_GL_DRAW_BUFFER11 == GL_DRAW_BUFFER11, "_GL_DRAW_BUFFER11 is not equal to GL_DRAW_BUFFER11");
                    static_assert(_GL_DRAW_BUFFER12 == GL_DRAW_BUFFER12, "_GL_DRAW_BUFFER12 is not equal to GL_DRAW_BUFFER12");
                    static_assert(_GL_DRAW_BUFFER13 == GL_DRAW_BUFFER13, "_GL_DRAW_BUFFER13 is not equal to GL_DRAW_BUFFER13");
                    static_assert(_GL_DRAW_BUFFER14 == GL_DRAW_BUFFER14, "_GL_DRAW_BUFFER14 is not equal to GL_DRAW_BUFFER14");
                    static_assert(_GL_DRAW_BUFFER15 == GL_DRAW_BUFFER15, "_GL_DRAW_BUFFER15 is not equal to GL_DRAW_BUFFER15");
                    static_assert(_GL_BLEND_EQUATION_ALPHA == GL_BLEND_EQUATION_ALPHA, "_GL_BLEND_EQUATION_ALPHA is not equal to GL_BLEND_EQUATION_ALPHA");
                    static_assert(_GL_MAX_VERTEX_ATTRIBS == GL_MAX_VERTEX_ATTRIBS, "_GL_MAX_VERTEX_ATTRIBS is not equal to GL_MAX_VERTEX_ATTRIBS");
                    static_assert(_GL_VERTEX_ATTRIB_ARRAY_NORMALIZED == GL_VERTEX_ATTRIB_ARRAY_NORMALIZED, "_GL_VERTEX_ATTRIB_ARRAY_NORMALIZED is not equal to GL_VERTEX_ATTRIB_ARRAY_NORMALIZED");
                    static_assert(_GL_MAX_TEXTURE_IMAGE_UNITS == GL_MAX_TEXTURE_IMAGE_UNITS, "_GL_MAX_TEXTURE_IMAGE_UNITS is not equal to GL_MAX_TEXTURE_IMAGE_UNITS");
                    static_assert(_GL_FRAGMENT_SHADER == GL_FRAGMENT_SHADER, "_GL_FRAGMENT_SHADER is not equal to GL_FRAGMENT_SHADER");
                    static_assert(_GL_VERTEX_SHADER == GL_VERTEX_SHADER, "_GL_VERTEX_SHADER is not equal to GL_VERTEX_SHADER");
                    static_assert(_GL_MAX_FRAGMENT_UNIFORM_COMPONENTS == GL_MAX_FRAGMENT_UNIFORM_COMPONENTS, "_GL_MAX_FRAGMENT_UNIFORM_COMPONENTS is not equal to GL_MAX_FRAGMENT_UNIFORM_COMPONENTS");
                    static_assert(_GL_MAX_VERTEX_UNIFORM_COMPONENTS == GL_MAX_VERTEX_UNIFORM_COMPONENTS, "_GL_MAX_VERTEX_UNIFORM_COMPONENTS is not equal to GL_MAX_VERTEX_UNIFORM_COMPONENTS");
                    static_assert(_GL_MAX_VARYING_FLOATS == GL_MAX_VARYING_FLOATS, "_GL_MAX_VARYING_FLOATS is not equal to GL_MAX_VARYING_FLOATS");
                    static_assert(_GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS == GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS, "_GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS is not equal to GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS");
                    static_assert(_GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS == GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS, "_GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS is not equal to GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS");
                    static_assert(_GL_SHADER_TYPE == GL_SHADER_TYPE, "_GL_SHADER_TYPE is not equal to GL_SHADER_TYPE");
                }
#endif
            }
        }
    }
}
#endif
