export module UPRISE_ENGINE_OPEN_GL_RENDER:OPENGL_SHADER;
export import UPRISE_ENGINE_CORE;
import UPRISE_ENGINE_COMMON_RENDER_COMPONETS;
export {
#define UE_OPENGL_BUILD_
#include "OPENGL_SHADER_INTERNAL.h"
}