.TH "_D3D12_SHADER_VARIABLE_DESC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_D3D12_SHADER_VARIABLE_DESC
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3d12shader\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LPCSTR \fBName\fP"
.br
.ti -1c
.RI "UINT \fBStartOffset\fP"
.br
.ti -1c
.RI "UINT \fBSize\fP"
.br
.ti -1c
.RI "UINT \fBuFlags\fP"
.br
.ti -1c
.RI "LPVOID \fBDefaultValue\fP"
.br
.ti -1c
.RI "UINT \fBStartTexture\fP"
.br
.ti -1c
.RI "UINT \fBTextureSize\fP"
.br
.ti -1c
.RI "UINT \fBStartSampler\fP"
.br
.ti -1c
.RI "UINT \fBSamplerSize\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "LPVOID _D3D12_SHADER_VARIABLE_DESC::DefaultValue"

.SS "LPCSTR _D3D12_SHADER_VARIABLE_DESC::Name"

.SS "UINT _D3D12_SHADER_VARIABLE_DESC::SamplerSize"

.SS "UINT _D3D12_SHADER_VARIABLE_DESC::Size"

.SS "UINT _D3D12_SHADER_VARIABLE_DESC::StartOffset"

.SS "UINT _D3D12_SHADER_VARIABLE_DESC::StartSampler"

.SS "UINT _D3D12_SHADER_VARIABLE_DESC::StartTexture"

.SS "UINT _D3D12_SHADER_VARIABLE_DESC::TextureSize"

.SS "UINT _D3D12_SHADER_VARIABLE_DESC::uFlags"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
