.TH "_D3D12_SIGNATURE_PARAMETER_DESC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_D3D12_SIGNATURE_PARAMETER_DESC
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3d12shader\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LPCSTR \fBSemanticName\fP"
.br
.ti -1c
.RI "UINT \fBSemanticIndex\fP"
.br
.ti -1c
.RI "UINT \fBRegister\fP"
.br
.ti -1c
.RI "\fBD3D_NAME\fP \fBSystemValueType\fP"
.br
.ti -1c
.RI "\fBD3D_REGISTER_COMPONENT_TYPE\fP \fBComponentType\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBMask\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBReadWriteMask\fP"
.br
.ti -1c
.RI "UINT \fBStream\fP"
.br
.ti -1c
.RI "\fBD3D_MIN_PRECISION\fP \fBMinPrecision\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBD3D_REGISTER_COMPONENT_TYPE\fP _D3D12_SIGNATURE_PARAMETER_DESC::ComponentType"

.SS "\fBBYTE\fP _D3D12_SIGNATURE_PARAMETER_DESC::Mask"

.SS "\fBD3D_MIN_PRECISION\fP _D3D12_SIGNATURE_PARAMETER_DESC::MinPrecision"

.SS "\fBBYTE\fP _D3D12_SIGNATURE_PARAMETER_DESC::ReadWriteMask"

.SS "UINT _D3D12_SIGNATURE_PARAMETER_DESC::Register"

.SS "UINT _D3D12_SIGNATURE_PARAMETER_DESC::SemanticIndex"

.SS "LPCSTR _D3D12_SIGNATURE_PARAMETER_DESC::SemanticName"

.SS "UINT _D3D12_SIGNATURE_PARAMETER_DESC::Stream"

.SS "\fBD3D_NAME\fP _D3D12_SIGNATURE_PARAMETER_DESC::SystemValueType"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
