.TH "_D3D_SHADER_MACRO" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_D3D_SHADER_MACRO
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3dcommon\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LPCSTR \fBName\fP"
.br
.ti -1c
.RI "LPCSTR \fBDefinition\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "LPCSTR _D3D_SHADER_MACRO::Definition"

.SS "LPCSTR _D3D_SHADER_MACRO::Name"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
