.TH "_D3D12_PARAMETER_DESC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_D3D12_PARAMETER_DESC
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3d12shader\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LPCSTR \fBName\fP"
.br
.ti -1c
.RI "LPCSTR \fBSemanticName\fP"
.br
.ti -1c
.RI "\fBD3D_SHADER_VARIABLE_TYPE\fP \fBType\fP"
.br
.ti -1c
.RI "\fBD3D_SHADER_VARIABLE_CLASS\fP \fBClass\fP"
.br
.ti -1c
.RI "UINT \fBRows\fP"
.br
.ti -1c
.RI "UINT \fBColumns\fP"
.br
.ti -1c
.RI "\fBD3D_INTERPOLATION_MODE\fP \fBInterpolationMode\fP"
.br
.ti -1c
.RI "\fBD3D_PARAMETER_FLAGS\fP \fBFlags\fP"
.br
.ti -1c
.RI "UINT \fBFirstInRegister\fP"
.br
.ti -1c
.RI "UINT \fBFirstInComponent\fP"
.br
.ti -1c
.RI "UINT \fBFirstOutRegister\fP"
.br
.ti -1c
.RI "UINT \fBFirstOutComponent\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBD3D_SHADER_VARIABLE_CLASS\fP _D3D12_PARAMETER_DESC::Class"

.SS "UINT _D3D12_PARAMETER_DESC::Columns"

.SS "UINT _D3D12_PARAMETER_DESC::FirstInComponent"

.SS "UINT _D3D12_PARAMETER_DESC::FirstInRegister"

.SS "UINT _D3D12_PARAMETER_DESC::FirstOutComponent"

.SS "UINT _D3D12_PARAMETER_DESC::FirstOutRegister"

.SS "\fBD3D_PARAMETER_FLAGS\fP _D3D12_PARAMETER_DESC::Flags"

.SS "\fBD3D_INTERPOLATION_MODE\fP _D3D12_PARAMETER_DESC::InterpolationMode"

.SS "LPCSTR _D3D12_PARAMETER_DESC::Name"

.SS "UINT _D3D12_PARAMETER_DESC::Rows"

.SS "LPCSTR _D3D12_PARAMETER_DESC::SemanticName"

.SS "\fBD3D_SHADER_VARIABLE_TYPE\fP _D3D12_PARAMETER_DESC::Type"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
