.TH "_D3D12_LIBRARY_DESC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_D3D12_LIBRARY_DESC
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3d12shader\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LPCSTR \fBCreator\fP"
.br
.ti -1c
.RI "UINT \fBFlags\fP"
.br
.ti -1c
.RI "UINT \fBFunctionCount\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "LPCSTR _D3D12_LIBRARY_DESC::Creator"

.SS "UINT _D3D12_LIBRARY_DESC::Flags"

.SS "UINT _D3D12_LIBRARY_DESC::FunctionCount"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
