.TH "_D3D12_SHADER_DESC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_D3D12_SHADER_DESC
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3d12shader\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBVersion\fP"
.br
.ti -1c
.RI "LPCSTR \fBCreator\fP"
.br
.ti -1c
.RI "UINT \fBFlags\fP"
.br
.ti -1c
.RI "UINT \fBConstantBuffers\fP"
.br
.ti -1c
.RI "UINT \fBBoundResources\fP"
.br
.ti -1c
.RI "UINT \fBInputParameters\fP"
.br
.ti -1c
.RI "UINT \fBOutputParameters\fP"
.br
.ti -1c
.RI "UINT \fBInstructionCount\fP"
.br
.ti -1c
.RI "UINT \fBTempRegisterCount\fP"
.br
.ti -1c
.RI "UINT \fBTempArrayCount\fP"
.br
.ti -1c
.RI "UINT \fBDefCount\fP"
.br
.ti -1c
.RI "UINT \fBDclCount\fP"
.br
.ti -1c
.RI "UINT \fBTextureNormalInstructions\fP"
.br
.ti -1c
.RI "UINT \fBTextureLoadInstructions\fP"
.br
.ti -1c
.RI "UINT \fBTextureCompInstructions\fP"
.br
.ti -1c
.RI "UINT \fBTextureBiasInstructions\fP"
.br
.ti -1c
.RI "UINT \fBTextureGradientInstructions\fP"
.br
.ti -1c
.RI "UINT \fBFloatInstructionCount\fP"
.br
.ti -1c
.RI "UINT \fBIntInstructionCount\fP"
.br
.ti -1c
.RI "UINT \fBUintInstructionCount\fP"
.br
.ti -1c
.RI "UINT \fBStaticFlowControlCount\fP"
.br
.ti -1c
.RI "UINT \fBDynamicFlowControlCount\fP"
.br
.ti -1c
.RI "UINT \fBMacroInstructionCount\fP"
.br
.ti -1c
.RI "UINT \fBArrayInstructionCount\fP"
.br
.ti -1c
.RI "UINT \fBCutInstructionCount\fP"
.br
.ti -1c
.RI "UINT \fBEmitInstructionCount\fP"
.br
.ti -1c
.RI "\fBD3D_PRIMITIVE_TOPOLOGY\fP \fBGSOutputTopology\fP"
.br
.ti -1c
.RI "UINT \fBGSMaxOutputVertexCount\fP"
.br
.ti -1c
.RI "\fBD3D_PRIMITIVE\fP \fBInputPrimitive\fP"
.br
.ti -1c
.RI "UINT \fBPatchConstantParameters\fP"
.br
.ti -1c
.RI "UINT \fBcGSInstanceCount\fP"
.br
.ti -1c
.RI "UINT \fBcControlPoints\fP"
.br
.ti -1c
.RI "\fBD3D_TESSELLATOR_OUTPUT_PRIMITIVE\fP \fBHSOutputPrimitive\fP"
.br
.ti -1c
.RI "\fBD3D_TESSELLATOR_PARTITIONING\fP \fBHSPartitioning\fP"
.br
.ti -1c
.RI "\fBD3D_TESSELLATOR_DOMAIN\fP \fBTessellatorDomain\fP"
.br
.ti -1c
.RI "UINT \fBcBarrierInstructions\fP"
.br
.ti -1c
.RI "UINT \fBcInterlockedInstructions\fP"
.br
.ti -1c
.RI "UINT \fBcTextureStoreInstructions\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT _D3D12_SHADER_DESC::ArrayInstructionCount"

.SS "UINT _D3D12_SHADER_DESC::BoundResources"

.SS "UINT _D3D12_SHADER_DESC::cBarrierInstructions"

.SS "UINT _D3D12_SHADER_DESC::cControlPoints"

.SS "UINT _D3D12_SHADER_DESC::cGSInstanceCount"

.SS "UINT _D3D12_SHADER_DESC::cInterlockedInstructions"

.SS "UINT _D3D12_SHADER_DESC::ConstantBuffers"

.SS "LPCSTR _D3D12_SHADER_DESC::Creator"

.SS "UINT _D3D12_SHADER_DESC::cTextureStoreInstructions"

.SS "UINT _D3D12_SHADER_DESC::CutInstructionCount"

.SS "UINT _D3D12_SHADER_DESC::DclCount"

.SS "UINT _D3D12_SHADER_DESC::DefCount"

.SS "UINT _D3D12_SHADER_DESC::DynamicFlowControlCount"

.SS "UINT _D3D12_SHADER_DESC::EmitInstructionCount"

.SS "UINT _D3D12_SHADER_DESC::Flags"

.SS "UINT _D3D12_SHADER_DESC::FloatInstructionCount"

.SS "UINT _D3D12_SHADER_DESC::GSMaxOutputVertexCount"

.SS "\fBD3D_PRIMITIVE_TOPOLOGY\fP _D3D12_SHADER_DESC::GSOutputTopology"

.SS "\fBD3D_TESSELLATOR_OUTPUT_PRIMITIVE\fP _D3D12_SHADER_DESC::HSOutputPrimitive"

.SS "\fBD3D_TESSELLATOR_PARTITIONING\fP _D3D12_SHADER_DESC::HSPartitioning"

.SS "UINT _D3D12_SHADER_DESC::InputParameters"

.SS "\fBD3D_PRIMITIVE\fP _D3D12_SHADER_DESC::InputPrimitive"

.SS "UINT _D3D12_SHADER_DESC::InstructionCount"

.SS "UINT _D3D12_SHADER_DESC::IntInstructionCount"

.SS "UINT _D3D12_SHADER_DESC::MacroInstructionCount"

.SS "UINT _D3D12_SHADER_DESC::OutputParameters"

.SS "UINT _D3D12_SHADER_DESC::PatchConstantParameters"

.SS "UINT _D3D12_SHADER_DESC::StaticFlowControlCount"

.SS "UINT _D3D12_SHADER_DESC::TempArrayCount"

.SS "UINT _D3D12_SHADER_DESC::TempRegisterCount"

.SS "\fBD3D_TESSELLATOR_DOMAIN\fP _D3D12_SHADER_DESC::TessellatorDomain"

.SS "UINT _D3D12_SHADER_DESC::TextureBiasInstructions"

.SS "UINT _D3D12_SHADER_DESC::TextureCompInstructions"

.SS "UINT _D3D12_SHADER_DESC::TextureGradientInstructions"

.SS "UINT _D3D12_SHADER_DESC::TextureLoadInstructions"

.SS "UINT _D3D12_SHADER_DESC::TextureNormalInstructions"

.SS "UINT _D3D12_SHADER_DESC::UintInstructionCount"

.SS "UINT _D3D12_SHADER_DESC::Version"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
