.TH "_D3D12_FUNCTION_DESC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_D3D12_FUNCTION_DESC
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3d12shader\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBVersion\fP"
.br
.ti -1c
.RI "LPCSTR \fBCreator\fP"
.br
.ti -1c
.RI "UINT \fBFlags\fP"
.br
.ti -1c
.RI "UINT \fBConstantBuffers\fP"
.br
.ti -1c
.RI "UINT \fBBoundResources\fP"
.br
.ti -1c
.RI "UINT \fBInstructionCount\fP"
.br
.ti -1c
.RI "UINT \fBTempRegisterCount\fP"
.br
.ti -1c
.RI "UINT \fBTempArrayCount\fP"
.br
.ti -1c
.RI "UINT \fBDefCount\fP"
.br
.ti -1c
.RI "UINT \fBDclCount\fP"
.br
.ti -1c
.RI "UINT \fBTextureNormalInstructions\fP"
.br
.ti -1c
.RI "UINT \fBTextureLoadInstructions\fP"
.br
.ti -1c
.RI "UINT \fBTextureCompInstructions\fP"
.br
.ti -1c
.RI "UINT \fBTextureBiasInstructions\fP"
.br
.ti -1c
.RI "UINT \fBTextureGradientInstructions\fP"
.br
.ti -1c
.RI "UINT \fBFloatInstructionCount\fP"
.br
.ti -1c
.RI "UINT \fBIntInstructionCount\fP"
.br
.ti -1c
.RI "UINT \fBUintInstructionCount\fP"
.br
.ti -1c
.RI "UINT \fBStaticFlowControlCount\fP"
.br
.ti -1c
.RI "UINT \fBDynamicFlowControlCount\fP"
.br
.ti -1c
.RI "UINT \fBMacroInstructionCount\fP"
.br
.ti -1c
.RI "UINT \fBArrayInstructionCount\fP"
.br
.ti -1c
.RI "UINT \fBMovInstructionCount\fP"
.br
.ti -1c
.RI "UINT \fBMovcInstructionCount\fP"
.br
.ti -1c
.RI "UINT \fBConversionInstructionCount\fP"
.br
.ti -1c
.RI "UINT \fBBitwiseInstructionCount\fP"
.br
.ti -1c
.RI "\fBD3D_FEATURE_LEVEL\fP \fBMinFeatureLevel\fP"
.br
.ti -1c
.RI "UINT64 \fBRequiredFeatureFlags\fP"
.br
.ti -1c
.RI "LPCSTR \fBName\fP"
.br
.ti -1c
.RI "INT \fBFunctionParameterCount\fP"
.br
.ti -1c
.RI "BOOL \fBHasReturn\fP"
.br
.ti -1c
.RI "BOOL \fBHas10Level9VertexShader\fP"
.br
.ti -1c
.RI "BOOL \fBHas10Level9PixelShader\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT _D3D12_FUNCTION_DESC::ArrayInstructionCount"

.SS "UINT _D3D12_FUNCTION_DESC::BitwiseInstructionCount"

.SS "UINT _D3D12_FUNCTION_DESC::BoundResources"

.SS "UINT _D3D12_FUNCTION_DESC::ConstantBuffers"

.SS "UINT _D3D12_FUNCTION_DESC::ConversionInstructionCount"

.SS "LPCSTR _D3D12_FUNCTION_DESC::Creator"

.SS "UINT _D3D12_FUNCTION_DESC::DclCount"

.SS "UINT _D3D12_FUNCTION_DESC::DefCount"

.SS "UINT _D3D12_FUNCTION_DESC::DynamicFlowControlCount"

.SS "UINT _D3D12_FUNCTION_DESC::Flags"

.SS "UINT _D3D12_FUNCTION_DESC::FloatInstructionCount"

.SS "INT _D3D12_FUNCTION_DESC::FunctionParameterCount"

.SS "BOOL _D3D12_FUNCTION_DESC::Has10Level9PixelShader"

.SS "BOOL _D3D12_FUNCTION_DESC::Has10Level9VertexShader"

.SS "BOOL _D3D12_FUNCTION_DESC::HasReturn"

.SS "UINT _D3D12_FUNCTION_DESC::InstructionCount"

.SS "UINT _D3D12_FUNCTION_DESC::IntInstructionCount"

.SS "UINT _D3D12_FUNCTION_DESC::MacroInstructionCount"

.SS "\fBD3D_FEATURE_LEVEL\fP _D3D12_FUNCTION_DESC::MinFeatureLevel"

.SS "UINT _D3D12_FUNCTION_DESC::MovcInstructionCount"

.SS "UINT _D3D12_FUNCTION_DESC::MovInstructionCount"

.SS "LPCSTR _D3D12_FUNCTION_DESC::Name"

.SS "UINT64 _D3D12_FUNCTION_DESC::RequiredFeatureFlags"

.SS "UINT _D3D12_FUNCTION_DESC::StaticFlowControlCount"

.SS "UINT _D3D12_FUNCTION_DESC::TempArrayCount"

.SS "UINT _D3D12_FUNCTION_DESC::TempRegisterCount"

.SS "UINT _D3D12_FUNCTION_DESC::TextureBiasInstructions"

.SS "UINT _D3D12_FUNCTION_DESC::TextureCompInstructions"

.SS "UINT _D3D12_FUNCTION_DESC::TextureGradientInstructions"

.SS "UINT _D3D12_FUNCTION_DESC::TextureLoadInstructions"

.SS "UINT _D3D12_FUNCTION_DESC::TextureNormalInstructions"

.SS "UINT _D3D12_FUNCTION_DESC::UintInstructionCount"

.SS "UINT _D3D12_FUNCTION_DESC::Version"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
