.TH "_D3D12_SHADER_TYPE_DESC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_D3D12_SHADER_TYPE_DESC
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3d12shader\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBD3D_SHADER_VARIABLE_CLASS\fP \fBClass\fP"
.br
.ti -1c
.RI "\fBD3D_SHADER_VARIABLE_TYPE\fP \fBType\fP"
.br
.ti -1c
.RI "UINT \fBRows\fP"
.br
.ti -1c
.RI "UINT \fBColumns\fP"
.br
.ti -1c
.RI "UINT \fBElements\fP"
.br
.ti -1c
.RI "UINT \fBMembers\fP"
.br
.ti -1c
.RI "UINT \fBOffset\fP"
.br
.ti -1c
.RI "LPCSTR \fBName\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBD3D_SHADER_VARIABLE_CLASS\fP _D3D12_SHADER_TYPE_DESC::Class"

.SS "UINT _D3D12_SHADER_TYPE_DESC::Columns"

.SS "UINT _D3D12_SHADER_TYPE_DESC::Elements"

.SS "UINT _D3D12_SHADER_TYPE_DESC::Members"

.SS "LPCSTR _D3D12_SHADER_TYPE_DESC::Name"

.SS "UINT _D3D12_SHADER_TYPE_DESC::Offset"

.SS "UINT _D3D12_SHADER_TYPE_DESC::Rows"

.SS "\fBD3D_SHADER_VARIABLE_TYPE\fP _D3D12_SHADER_TYPE_DESC::Type"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
