.TH "_IEEEDouble" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_IEEEDouble
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <qnan\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBDouble\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint64_t \fBFrac\fP: 52"
.br
.ti -1c
.RI "   uint64_t \fBExp\fP: 11"
.br
.ti -1c
.RI "   uint64_t \fBSign\fP: 1"
.br
.ti -1c
.RI "} \fBIEEE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data structure to represent the bit pattern of a 64 Bit IEEE 754 floating-point number\&. 
.SH "Member Data Documentation"
.PP 
.SS "double _IEEEDouble::Double"

.SS "uint64_t _IEEEDouble::Exp"

.SS "uint64_t _IEEEDouble::Frac"

.SS "struct  { \&.\&.\&. }  _IEEEDouble::IEEE"

.SS "uint64_t _IEEEDouble::Sign"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
