.TH "_IEEESingle" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_IEEESingle
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <qnan\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBFloat\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBFrac\fP: 23"
.br
.ti -1c
.RI "   uint32_t \fBExp\fP: 8"
.br
.ti -1c
.RI "   uint32_t \fBSign\fP: 1"
.br
.ti -1c
.RI "} \fBIEEE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data structure to represent the bit pattern of a 32 Bit IEEE 754 floating-point number\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint32_t _IEEESingle::Exp"

.SS "float _IEEESingle::Float"

.SS "uint32_t _IEEESingle::Frac"

.SS "struct  { \&.\&.\&. }  _IEEESingle::IEEE"

.SS "uint32_t _IEEESingle::Sign"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
