.TH "UPRISE_ENGINE/_MESH.h" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/_MESH.h
.SH SYNOPSIS
.br
.PP
\fR#include 'pch\&.h'\fP
.br
\fR#include 'TS_P_VECTOR3\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDATATYPES::Mesh\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDATATYPES\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__MESH_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __MESH_"

.PP
Definition at line \fB4\fP of file \fB_MESH\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
