.TH "UPRISE_ENGINE/_PHYSICSOBJEC.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/_PHYSICSOBJEC.h
.SH SYNOPSIS
.br
.PP
\fR#include 'HeaderE/CORE/C_BEHAVIOUR\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_PhysicsObject\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
