.TH "adhed/glm/detail/_swizzle_func.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/detail/_swizzle_func.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC2_ENTRY\fP(\fBT\fP,  \fBP\fP,  CONST,  \fBA\fP,  \fBB\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC3_ENTRY\fP(\fBT\fP,  \fBP\fP,  CONST,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC4_ENTRY\fP(\fBT\fP,  \fBP\fP,  CONST,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC2_ENTRY_DEF\fP(\fBT\fP,  \fBP\fP,  \fBL\fP,  CONST,  \fBA\fP,  \fBB\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC3_ENTRY_DEF\fP(\fBT\fP,  \fBP\fP,  \fBL\fP,  CONST,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC4_ENTRY_DEF\fP(\fBT\fP,  \fBP\fP,  \fBL\fP,  CONST,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
.br
.ti -1c
.RI "#define \fBGLM_MUTABLE\fP"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_REF_FROM_VEC2\fP(\fBT\fP,  \fBP\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_REF2_FROM_VEC3_SWIZZLE\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_REF3_FROM_VEC3_SWIZZLE\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_REF_FROM_VEC3_COMP\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_REF_FROM_VEC3\fP(\fBT\fP,  \fBP\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_REF2_FROM_VEC4_SWIZZLE\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_REF3_FROM_VEC4_SWIZZLE\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_REF4_FROM_VEC4_SWIZZLE\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_REF_FROM_VEC4_COMP\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_REF_FROM_VEC4\fP(\fBT\fP,  \fBP\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC2_FROM_VEC2_SWIZZLE\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC3_FROM_VEC2_SWIZZLE\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC4_FROM_VEC2_SWIZZLE\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC_FROM_VEC2_COMP\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC_FROM_VEC2\fP(\fBT\fP,  \fBP\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC2_FROM_VEC3_SWIZZLE\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC3_FROM_VEC3_SWIZZLE\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC4_FROM_VEC3_SWIZZLE\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC_FROM_VEC3_COMP\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC_FROM_VEC3\fP(\fBT\fP,  \fBP\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC2_FROM_VEC4_SWIZZLE\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC3_FROM_VEC4_SWIZZLE\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC4_FROM_VEC4_SWIZZLE\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC_FROM_VEC4_COMP\fP(\fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
.br
.ti -1c
.RI "#define \fBGLM_SWIZZLE_GEN_VEC_FROM_VEC4\fP(\fBT\fP,  \fBP\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GLM_MUTABLE"

.SS "#define GLM_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, 2, GLM_MUTABLE, A, B) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, 2, GLM_MUTABLE, B, A)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_REF2_FROM_VEC3_SWIZZLE( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, A, B) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, A, C) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, B, A) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, B, C) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, C, A) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, C, B)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_REF2_FROM_VEC4_SWIZZLE( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, A, B) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, A, C) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, A, D) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, B, A) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, B, C) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, B, D) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, C, A) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, C, B) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, C, D) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, D, A) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, D, B) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, GLM_MUTABLE, D, C)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_REF3_FROM_VEC3_SWIZZLE( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, GLM_MUTABLE, A, B, C) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, GLM_MUTABLE, A, C, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, GLM_MUTABLE, B, A, C) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, GLM_MUTABLE, B, C, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, GLM_MUTABLE, C, A, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, GLM_MUTABLE, C, B, A)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_REF3_FROM_VEC4_SWIZZLE( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , A, B, C) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , A, B, D) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , A, C, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , A, C, D) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , A, D, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , A, D, C) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , B, A, C) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , B, A, D) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , B, C, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , B, C, D) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , B, D, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , B, D, C) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , C, A, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , C, A, D) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , C, B, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , C, B, D) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , C, D, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , C, D, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , D, A, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , D, A, C) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , D, B, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , D, B, C) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , D, C, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, , D, C, B)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_REF4_FROM_VEC4_SWIZZLE( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, C, B, D) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, C, D, B) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, D, B, C) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, D, C, B) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, B, D, C) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , A, B, C, D) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, C, A, D) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, C, D, A) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, D, A, C) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, D, C, A) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, A, D, C) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , B, A, C, D) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, B, A, D) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, B, D, A) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, D, A, B) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, D, B, A) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, A, D, B) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , C, A, B, D) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, C, B, A) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, C, A, B) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, A, B, C) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, A, C, B) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, B, A, C) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, , D, B, C, A)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_REF_FROM_VEC2( \fBT\fP,  \fBP\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, x, y) \\
    GLM_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, r, g) \\
    GLM_SWIZZLE_GEN_REF2_FROM_VEC2_SWIZZLE(T, P, s, t)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_REF_FROM_VEC3( \fBT\fP,  \fBP\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_REF_FROM_VEC3_COMP(T, P, x, y, z) \\
    GLM_SWIZZLE_GEN_REF_FROM_VEC3_COMP(T, P, r, g, b) \\
    GLM_SWIZZLE_GEN_REF_FROM_VEC3_COMP(T, P, s, t, p)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_REF_FROM_VEC3_COMP( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_REF3_FROM_VEC3_SWIZZLE(T, P, A, B, C) \\
    GLM_SWIZZLE_GEN_REF2_FROM_VEC3_SWIZZLE(T, P, A, B, C)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_REF_FROM_VEC4( \fBT\fP,  \fBP\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_REF_FROM_VEC4_COMP(T, P, x, y, z, w) \\
    GLM_SWIZZLE_GEN_REF_FROM_VEC4_COMP(T, P, r, g, b, a) \\
    GLM_SWIZZLE_GEN_REF_FROM_VEC4_COMP(T, P, s, t, p, q)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_REF_FROM_VEC4_COMP( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_REF2_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \\
    GLM_SWIZZLE_GEN_REF3_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \\
    GLM_SWIZZLE_GEN_REF4_FROM_VEC4_SWIZZLE(T, P, A, B, C, D)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC2_ENTRY( \fBT\fP,  \fBP\fP,  CONST,  \fBA\fP,  \fBB\fP)"
\fBValue:\fP
.nf
    GLM_FUNC_QUALIFIER vec<2, T, Q> A ## B() CONST                          \\
    {                                                   \\
        return vec<2, T, Q>(this\->A, this\->B);            \\
    }
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC2_ENTRY_DEF( \fBT\fP,  \fBP\fP,  \fBL\fP,  CONST,  \fBA\fP,  \fBB\fP)"
\fBValue:\fP
.nf
    template<typename T>                                        \\
    GLM_FUNC_QUALIFIER vec<L, T, Q> vec<L, T, Q>::A ## B() CONST                    \\
    {                                                           \\
        return vec<2, T, Q>(this\->A, this\->B);                    \\
    }
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC2_FROM_VEC2_SWIZZLE( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, A) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, B) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, A) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, B)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC2_FROM_VEC3_SWIZZLE( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, A) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, B) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, C) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, A) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, B) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, C) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, C, A) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, C, B) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, C, C)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC2_FROM_VEC4_SWIZZLE( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, A) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, B) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, C) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, A, D) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, A) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, B) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, C) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, B, D) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, C, A) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, C, B) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, C, C) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, C, D) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, D, A) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, D, B) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, D, C) \\
    GLM_SWIZZLE_GEN_VEC2_ENTRY(T, P, const, D, D)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC3_ENTRY( \fBT\fP,  \fBP\fP,  CONST,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
\fBValue:\fP
.nf
    GLM_FUNC_QUALIFIER vec<3, T, Q> A ## B ## C() CONST                         \\
    {                                                           \\
        return vec<3, T, Q>(this\->A, this\->B, this\->C);            \\
    }
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC3_ENTRY_DEF( \fBT\fP,  \fBP\fP,  \fBL\fP,  CONST,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
\fBValue:\fP
.nf
    template<typename T>                                            \\
    GLM_FUNC_QUALIFIER vec<3, T, Q> vec<L, T, Q>::A ## B ## C() CONST                   \\
    {                                                               \\
        return vec<3, T, Q>(this\->A, this\->B, this\->C);                \\
    }
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC3_FROM_VEC2_SWIZZLE( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, A, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, A, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, B, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, B, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, A, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, A, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, B, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, B, B)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC3_FROM_VEC3_SWIZZLE( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, A, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, A, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, A, C) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, B, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, B, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, B, C) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, C, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, C, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, A, C, C) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, A, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, A, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, A, C) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, B, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, B, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, B, C) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, C, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, C, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, B, C, C) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, A, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, A, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, A, C) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, B, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, B, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, B, C) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, C, A) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, C, B) \\
    GLM_SWIZZLE_GEN_VEC3_ENTRY(T, P, const, C, C, C)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC3_FROM_VEC4_SWIZZLE( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"

.SS "#define GLM_SWIZZLE_GEN_VEC4_ENTRY( \fBT\fP,  \fBP\fP,  CONST,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
\fBValue:\fP
.nf
    GLM_FUNC_QUALIFIER vec<4, T, Q> A ## B ## C ## D() CONST                                    \\
    {                                                                       \\
        return vec<4, T, Q>(this\->A, this\->B, this\->C, this\->D);            \\
    }
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC4_ENTRY_DEF( \fBT\fP,  \fBP\fP,  \fBL\fP,  CONST,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
\fBValue:\fP
.nf
    template<typename T>                                                \\
    GLM_FUNC_QUALIFIER vec<4, T, Q> vec<L, T, Q>::A ## B ## C ## D() CONST                  \\
    {                                                                   \\
        return vec<4, T, Q>(this\->A, this\->B, this\->C, this\->D);        \\
    }
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC4_FROM_VEC2_SWIZZLE( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, A, A) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, A, B) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, B, A) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, A, B, B) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, A, A) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, A, B) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, B, A) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, A, B, B, B) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, A, A) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, A, B) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, B, A) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, A, B, B) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, A, A) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, A, B) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, B, A) \\
    GLM_SWIZZLE_GEN_VEC4_ENTRY(T, P, const, B, B, B, B)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC4_FROM_VEC3_SWIZZLE( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP)"

.SS "#define GLM_SWIZZLE_GEN_VEC4_FROM_VEC4_SWIZZLE( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"

.SS "#define GLM_SWIZZLE_GEN_VEC_FROM_VEC2( \fBT\fP,  \fBP\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC_FROM_VEC2_COMP(T, P, x, y)  \\
    GLM_SWIZZLE_GEN_VEC_FROM_VEC2_COMP(T, P, r, g)  \\
    GLM_SWIZZLE_GEN_VEC_FROM_VEC2_COMP(T, P, s, t)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC_FROM_VEC2_COMP( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC2_FROM_VEC2_SWIZZLE(T, P, A, B) \\
    GLM_SWIZZLE_GEN_VEC3_FROM_VEC2_SWIZZLE(T, P, A, B) \\
    GLM_SWIZZLE_GEN_VEC4_FROM_VEC2_SWIZZLE(T, P, A, B)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC_FROM_VEC3( \fBT\fP,  \fBP\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC_FROM_VEC3_COMP(T, P, x, y, z) \\
    GLM_SWIZZLE_GEN_VEC_FROM_VEC3_COMP(T, P, r, g, b) \\
    GLM_SWIZZLE_GEN_VEC_FROM_VEC3_COMP(T, P, s, t, p)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC_FROM_VEC3_COMP( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC2_FROM_VEC3_SWIZZLE(T, P, A, B, C) \\
    GLM_SWIZZLE_GEN_VEC3_FROM_VEC3_SWIZZLE(T, P, A, B, C) \\
    GLM_SWIZZLE_GEN_VEC4_FROM_VEC3_SWIZZLE(T, P, A, B, C)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC_FROM_VEC4( \fBT\fP,  \fBP\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC_FROM_VEC4_COMP(T, P, x, y, z, w) \\
    GLM_SWIZZLE_GEN_VEC_FROM_VEC4_COMP(T, P, r, g, b, a) \\
    GLM_SWIZZLE_GEN_VEC_FROM_VEC4_COMP(T, P, s, t, p, q)
.PP
.fi

.SS "#define GLM_SWIZZLE_GEN_VEC_FROM_VEC4_COMP( \fBT\fP,  \fBP\fP,  \fBA\fP,  \fBB\fP,  \fBC\fP,  \fBD\fP)"
\fBValue:\fP
.nf
    GLM_SWIZZLE_GEN_VEC2_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \\
    GLM_SWIZZLE_GEN_VEC3_FROM_VEC4_SWIZZLE(T, P, A, B, C, D) \\
    GLM_SWIZZLE_GEN_VEC4_FROM_VEC4_SWIZZLE(T, P, A, B, C, D)
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
