.TH "adhed/assimp/ai_assert.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/assimp/ai_assert.h \- Declares the assimp-specific assertion handler\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <assimp/defs\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAI_ASSERT_H_INC\fP"
.br
.ti -1c
.RI "#define \fBai_assert\fP(expression)"
.br
.ti -1c
.RI "#define \fBai_assert_entry\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Declares the assimp-specific assertion handler\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define ai_assert( expression)"

.SS "#define ai_assert_entry()"

.SS "#define AI_ASSERT_H_INC"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
