.TH "aiAnimMesh" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiAnimMesh \- An AnimMesh is an attachment to an \fBaiMesh\fP stores per-vertex animations for a particular frame\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mesh\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiString\fP \fBmName\fP"
.br
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiVector3D\fP * \fBmVertices\fP"
.br
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiVector3D\fP * \fBmNormals\fP"
.br
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiVector3D\fP * \fBmTangents\fP"
.br
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiVector3D\fP * \fBmBitangents\fP"
.br
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiColor4D\fP * \fBmColors\fP [\fBAI_MAX_NUMBER_OF_COLOR_SETS\fP]"
.br
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiVector3D\fP * \fBmTextureCoords\fP [\fBAI_MAX_NUMBER_OF_TEXTURECOORDS\fP]"
.br
.ti -1c
.RI "unsigned int \fBmNumVertices\fP"
.br
.ti -1c
.RI "float \fBmWeight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An AnimMesh is an attachment to an \fBaiMesh\fP stores per-vertex animations for a particular frame\&. 

You may think of an \fBaiAnimMesh\fP as a \fRpatch\fP for the host mesh, which replaces only certain vertex data streams at a particular time\&. Each mesh stores n attached attached meshes (\fBaiMesh::mAnimMeshes\fP)\&. The actual relationship between the time line and anim meshes is established by \fBaiMeshAnim\fP, which references singular mesh attachments by their ID and binds them to a time offset\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBC_STRUCT\fP \fBaiVector3D\fP* aiAnimMesh::mBitangents"
Replacement for \fBaiMesh::mBitangents\fP\&. 
.SS "\fBC_STRUCT\fP \fBaiColor4D\fP* aiAnimMesh::mColors[\fBAI_MAX_NUMBER_OF_COLOR_SETS\fP]"
Replacement for \fBaiMesh::mColors\fP 
.SS "\fBC_STRUCT\fP \fBaiString\fP aiAnimMesh::mName"
Anim Mesh name 
.SS "\fBC_STRUCT\fP \fBaiVector3D\fP* aiAnimMesh::mNormals"
Replacement for \fBaiMesh::mNormals\fP\&. 
.br
 
.SS "unsigned int aiAnimMesh::mNumVertices"
The number of vertices in the \fBaiAnimMesh\fP, and thus the length of all the member arrays\&.
.PP
This has always the same value as the mNumVertices property in the corresponding \fBaiMesh\fP\&. It is duplicated here merely to make the length of the member arrays accessible even if the \fBaiMesh\fP is not known, e\&.g\&. from language bindings\&. 
.SS "\fBC_STRUCT\fP \fBaiVector3D\fP* aiAnimMesh::mTangents"
Replacement for \fBaiMesh::mTangents\fP\&. 
.SS "\fBC_STRUCT\fP \fBaiVector3D\fP* aiAnimMesh::mTextureCoords[\fBAI_MAX_NUMBER_OF_TEXTURECOORDS\fP]"
Replacement for \fBaiMesh::mTextureCoords\fP 
.SS "\fBC_STRUCT\fP \fBaiVector3D\fP* aiAnimMesh::mVertices"
Replacement for \fBaiMesh::mVertices\fP\&. If this array is non-nullptr, it \fImust\fP contain mNumVertices entries\&. The corresponding array in the host mesh must be non-nullptr as well - animation meshes may neither add or nor remove vertex components (if a replacement array is nullptr and the corresponding source array is not, the source data is taken instead) 
.SS "float aiAnimMesh::mWeight"
Weight of the AnimMesh\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
