.TH "aiColor3D" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiColor3D
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBai_real\fP \fBr\fP"
.br
.RI "Red, green and blue color values\&. "
.ti -1c
.RI "\fBai_real\fP \fBg\fP"
.br
.ti -1c
.RI "\fBai_real\fP \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a color in Red-Green-Blue space\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBai_real\fP aiColor3D::b"

.SS "\fBai_real\fP aiColor3D::g"

.SS "\fBai_real\fP aiColor3D::r"

.PP
Red, green and blue color values\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
