.TH "aiExportFormatDesc" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiExportFormatDesc \- Describes an file format which \fBAssimp\fP can export to\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <cexport\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBid\fP"
.br
.ti -1c
.RI "const char * \fBdescription\fP"
.br
.ti -1c
.RI "const char * \fBfileExtension\fP"
.br
.RI "Recommended file extension for the exported file in lower case\&. "
.in -1c
.SH "Detailed Description"
.PP 
Describes an file format which \fBAssimp\fP can export to\&. 

Use \fBaiGetExportFormatCount()\fP to learn how many export-formats are supported by the current Assimp-build and \fBaiGetExportFormatDescription()\fP to retrieve the description of the export format option\&. 
.SH "Member Data Documentation"
.PP 
.SS "const char* aiExportFormatDesc::description"
A short description of the file format to present to users\&. Useful if you want to allow the user to select an export format\&. 
.SS "const char* aiExportFormatDesc::fileExtension"

.PP
Recommended file extension for the exported file in lower case\&. 
.SS "const char* aiExportFormatDesc::id"
a short string ID to uniquely identify the export format\&. Use this ID string to specify which file format you want to export to when calling \fBaiExportScene()\fP\&. Example: 'dae' or 'obj' 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
