.TH "aiFace" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiFace \- A single face in a mesh, referring to multiple vertices\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mesh\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBmNumIndices\fP"
.br
.ti -1c
.RI "unsigned int * \fBmIndices\fP"
.br
.RI "Pointer to the indices array\&. Size of the array is given in numIndices\&. "
.in -1c
.SH "Detailed Description"
.PP 
A single face in a mesh, referring to multiple vertices\&. 

If mNumIndices is 3, we call the face 'triangle', for mNumIndices > 3 it's called 'polygon' (hey, that's just a definition!)\&. 
.br
 \fBaiMesh::mPrimitiveTypes\fP can be queried to quickly examine which types of primitive are actually present in a mesh\&. The \fBaiProcess_SortByPType\fP flag executes a special post-processing algorithm which splits meshes with \fIdifferent\fP primitive types mixed up (e\&.g\&. lines and triangles) in several 'clean' sub-meshes\&. Furthermore there is a configuration option ( \fBAI_CONFIG_PP_SBP_REMOVE\fP) to force \fBaiProcess_SortByPType\fP to remove specific kinds of primitives from the imported scene, completely and forever\&. In many cases you'll probably want to set this setting to 
.PP
.nf
aiPrimitiveType_LINE|aiPrimitiveType_POINT

.fi
.PP
 Together with the \fBaiProcess_Triangulate\fP flag you can then be sure that \fBaiFace::mNumIndices\fP is always 3\&. 
.PP
\fBNote\fP
.RS 4
Take a look at the \fBData Structures page \fP for more information on the layout and winding order of a face\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "unsigned int* aiFace::mIndices"

.PP
Pointer to the indices array\&. Size of the array is given in numIndices\&. 
.SS "unsigned int aiFace::mNumIndices"
Number of indices defining this face\&. The maximum value for this member is \fBAI_MAX_FACE_INDICES\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
