.TH "aiLogStream" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiLogStream
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <cimport\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaiLogStreamCallback\fP \fBcallback\fP"
.br
.ti -1c
.RI "char * \fBuser\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
C-API: Represents a log stream\&. A log stream receives all log messages and streams them \fIsomewhere\fP\&. 
.PP
\fBSee also\fP
.RS 4
\fBaiGetPredefinedLogStream\fP 
.PP
\fBaiAttachLogStream\fP 
.PP
\fBaiDetachLogStream\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBaiLogStreamCallback\fP aiLogStream::callback"
callback to be called 
.SS "char* aiLogStream::user"
user data to be passed to the callback 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
