.TH "aiMemoryInfo" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiMemoryInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <types\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaiMemoryInfo\fP () \fBAI_NO_EXCEPT\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBtextures\fP"
.br
.ti -1c
.RI "unsigned int \fBmaterials\fP"
.br
.ti -1c
.RI "unsigned int \fBmeshes\fP"
.br
.ti -1c
.RI "unsigned int \fBnodes\fP"
.br
.ti -1c
.RI "unsigned int \fBanimations\fP"
.br
.ti -1c
.RI "unsigned int \fBcameras\fP"
.br
.ti -1c
.RI "unsigned int \fBlights\fP"
.br
.ti -1c
.RI "unsigned int \fBtotal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stores the memory requirements for different components (e\&.g\&. meshes, materials, animations) of an import\&. All sizes are in bytes\&. 
.PP
\fBSee also\fP
.RS 4
Importer::GetMemoryRequirements() 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "aiMemoryInfo::aiMemoryInfo ()\fR [inline]\fP"
Default constructor 
.SH "Member Data Documentation"
.PP 
.SS "unsigned int aiMemoryInfo::animations"
Storage allocated for animation data 
.SS "unsigned int aiMemoryInfo::cameras"
Storage allocated for camera data 
.SS "unsigned int aiMemoryInfo::lights"
Storage allocated for light data 
.SS "unsigned int aiMemoryInfo::materials"
Storage allocated for material data 
.br
 
.SS "unsigned int aiMemoryInfo::meshes"
Storage allocated for mesh data 
.SS "unsigned int aiMemoryInfo::nodes"
Storage allocated for node data 
.SS "unsigned int aiMemoryInfo::textures"
Storage allocated for texture data 
.SS "unsigned int aiMemoryInfo::total"
Total storage allocated for the full import\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
