.TH "aiMeshKey" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiMeshKey
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <anim\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef unsigned int \fBelem_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaiMeshKey\fP () \fBAI_NO_EXCEPT\fP"
.br
.ti -1c
.RI "\fBaiMeshKey\fP (double time, const unsigned int \fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBaiMeshKey\fP &o) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBaiMeshKey\fP &o) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBaiMeshKey\fP &o) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBaiMeshKey\fP &o) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBmTime\fP"
.br
.ti -1c
.RI "unsigned int \fBmValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Binds a anim-mesh to a specific point in time\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "typedef unsigned int \fBaiMeshKey::elem_type\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "aiMeshKey::aiMeshKey ()\fR [inline]\fP"

.SS "aiMeshKey::aiMeshKey (double time, const unsigned int value)\fR [inline]\fP"
Construction from a given time and key value 
.SH "Member Function Documentation"
.PP 
.SS "bool aiMeshKey::operator!= (const \fBaiMeshKey\fP & o) const\fR [inline]\fP"

.SS "bool aiMeshKey::operator< (const \fBaiMeshKey\fP & o) const\fR [inline]\fP"

.SS "bool aiMeshKey::operator== (const \fBaiMeshKey\fP & o) const\fR [inline]\fP"

.SS "bool aiMeshKey::operator> (const \fBaiMeshKey\fP & o) const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double aiMeshKey::mTime"
The time of this key 
.SS "unsigned int aiMeshKey::mValue"
Index into the \fBaiMesh::mAnimMeshes\fP array of the mesh corresponding to the \fBaiMeshAnim\fP hosting this key frame\&. The referenced anim mesh is evaluated according to the rules defined in the docs for \fBaiAnimMesh\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
