.TH "aiNodeAnim" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiNodeAnim
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <anim\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaiNodeAnim\fP () \fBAI_NO_EXCEPT\fP"
.br
.ti -1c
.RI "\fB~aiNodeAnim\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiString\fP \fBmNodeName\fP"
.br
.ti -1c
.RI "unsigned int \fBmNumPositionKeys\fP"
.br
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiVectorKey\fP * \fBmPositionKeys\fP"
.br
.ti -1c
.RI "unsigned int \fBmNumRotationKeys\fP"
.br
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiQuatKey\fP * \fBmRotationKeys\fP"
.br
.ti -1c
.RI "unsigned int \fBmNumScalingKeys\fP"
.br
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiVectorKey\fP * \fBmScalingKeys\fP"
.br
.ti -1c
.RI "\fBC_ENUM\fP \fBaiAnimBehaviour\fP \fBmPreState\fP"
.br
.ti -1c
.RI "\fBC_ENUM\fP \fBaiAnimBehaviour\fP \fBmPostState\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Describes the animation of a single node\&. The name specifies the bone/node which is affected by this animation channel\&. The keyframes are given in three separate series of values, one each for position, rotation and scaling\&. The transformation matrix computed from these values replaces the node's original transformation matrix at a specific time\&. This means all keys are absolute and not relative to the bone default pose\&. The order in which the transformations are applied is
.IP "\(bu" 2
as usual - scaling, rotation, translation\&.
.PP
.PP
\fBNote\fP
.RS 4
All keys are returned in their correct, chronological order\&. Duplicate keys don't pass the validation step\&. Most likely there will be no negative time values, but they are not forbidden also ( so implementations need to cope with them! ) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "aiNodeAnim::aiNodeAnim ()\fR [inline]\fP"

.SS "aiNodeAnim::~aiNodeAnim ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBC_STRUCT\fP \fBaiString\fP aiNodeAnim::mNodeName"
The name of the node affected by this animation\&. The node must exist and it must be unique\&. 
.SS "unsigned int aiNodeAnim::mNumPositionKeys"
The number of position keys 
.SS "unsigned int aiNodeAnim::mNumRotationKeys"
The number of rotation keys 
.SS "unsigned int aiNodeAnim::mNumScalingKeys"
The number of scaling keys 
.SS "\fBC_STRUCT\fP \fBaiVectorKey\fP* aiNodeAnim::mPositionKeys"
The position keys of this animation channel\&. Positions are specified as 3D vector\&. The array is mNumPositionKeys in size\&.
.PP
If there are position keys, there will also be at least one scaling and one rotation key\&. 
.SS "\fBC_ENUM\fP \fBaiAnimBehaviour\fP aiNodeAnim::mPostState"
Defines how the animation behaves after the last key was processed\&.
.PP
The default value is aiAnimBehaviour_DEFAULT (the original transformation matrix of the affected node is taken)\&. 
.SS "\fBC_ENUM\fP \fBaiAnimBehaviour\fP aiNodeAnim::mPreState"
Defines how the animation behaves before the first key is encountered\&.
.PP
The default value is aiAnimBehaviour_DEFAULT (the original transformation matrix of the affected node is used)\&. 
.SS "\fBC_STRUCT\fP \fBaiQuatKey\fP* aiNodeAnim::mRotationKeys"
The rotation keys of this animation channel\&. Rotations are given as quaternions, which are 4D vectors\&. The array is mNumRotationKeys in size\&.
.PP
If there are rotation keys, there will also be at least one scaling and one position key\&. 
.SS "\fBC_STRUCT\fP \fBaiVectorKey\fP* aiNodeAnim::mScalingKeys"
The scaling keys of this animation channel\&. Scalings are specified as 3D vector\&. The array is mNumScalingKeys in size\&.
.PP
If there are scaling keys, there will also be at least one position and one rotation key\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
