.TH "aiPropertyStore" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiPropertyStore
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <cimport\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBsentinel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
C-API: Represents an opaque set of settings to be used during importing\&. 
.PP
\fBSee also\fP
.RS 4
\fBaiCreatePropertyStore\fP 
.PP
\fBaiReleasePropertyStore\fP 
.PP
\fBaiImportFileExWithProperties\fP 
.PP
aiSetPropertyInteger 
.PP
aiSetPropertyFloat 
.PP
aiSetPropertyString 
.PP
aiSetPropertyMatrix 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "char aiPropertyStore::sentinel"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
