.TH "aiQuaternion" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiQuaternion
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <quaternion\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBai_real\fP \fBw\fP"
.br
.ti -1c
.RI "\fBai_real\fP \fBx\fP"
.br
.ti -1c
.RI "\fBai_real\fP \fBy\fP"
.br
.ti -1c
.RI "\fBai_real\fP \fBz\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBai_real\fP aiQuaternion::w"

.SS "\fBai_real\fP aiQuaternion::x"

.SS "\fBai_real\fP aiQuaternion::y"

.SS "\fBai_real\fP aiQuaternion::z"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
