.TH "aiQuatKey" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiQuatKey
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <anim\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBaiQuaternion\fP \fBelem_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaiQuatKey\fP () \fBAI_NO_EXCEPT\fP"
.br
.ti -1c
.RI "\fBaiQuatKey\fP (double time, const \fBaiQuaternion\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBaiQuatKey\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBaiQuatKey\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBaiQuatKey\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBaiQuatKey\fP &rhs) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBmTime\fP"
.br
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiQuaternion\fP \fBmValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A time-value pair specifying a rotation for the given time\&. Rotations are expressed with quaternions\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "typedef \fBaiQuaternion\fP \fBaiQuatKey::elem_type\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "aiQuatKey::aiQuatKey ()\fR [inline]\fP"

.SS "aiQuatKey::aiQuatKey (double time, const \fBaiQuaternion\fP & value)\fR [inline]\fP"
Construction from a given time and key value 
.SH "Member Function Documentation"
.PP 
.SS "bool aiQuatKey::operator!= (const \fBaiQuatKey\fP & rhs) const\fR [inline]\fP"

.SS "bool aiQuatKey::operator< (const \fBaiQuatKey\fP & rhs) const\fR [inline]\fP"

.SS "bool aiQuatKey::operator== (const \fBaiQuatKey\fP & rhs) const\fR [inline]\fP"

.SS "bool aiQuatKey::operator> (const \fBaiQuatKey\fP & rhs) const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double aiQuatKey::mTime"
The time of this key 
.SS "\fBC_STRUCT\fP \fBaiQuaternion\fP aiQuatKey::mValue"
The value of this key 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
