.TH "aiSkeletonBone" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiSkeletonBone
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mesh\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmParent\fP"
.br
.RI "The parent bone index, is -1 one if this bone represents the root bone\&. "
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiNode\fP * \fBmArmature\fP"
.br
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiNode\fP * \fBmNode\fP"
.br
.ti -1c
.RI "unsigned int \fBmNumnWeights\fP"
.br
.RI "The number of weights\&. "
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiMesh\fP * \fBmMeshId\fP"
.br
.RI "The mesh index, which will get influenced by the weight\&. "
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiVertexWeight\fP * \fBmWeights\fP"
.br
.RI "The influence weights of this bone, by vertex index\&. "
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiMatrix4x4\fP \fBmOffsetMatrix\fP"
.br
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiMatrix4x4\fP \fBmLocalMatrix\fP"
.br
.RI "Matrix that transforms the locale bone in bind pose\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBC_STRUCT\fP \fBaiNode\fP* aiSkeletonBone::mArmature"
The bone armature node - used for skeleton conversion you must enable aiProcess_PopulateArmatureData to populate this 
.SS "\fBC_STRUCT\fP \fBaiMatrix4x4\fP aiSkeletonBone::mLocalMatrix"

.PP
Matrix that transforms the locale bone in bind pose\&. 
.SS "\fBC_STRUCT\fP \fBaiMesh\fP* aiSkeletonBone::mMeshId"

.PP
The mesh index, which will get influenced by the weight\&. 
.SS "\fBC_STRUCT\fP \fBaiNode\fP* aiSkeletonBone::mNode"
The bone node in the scene - used for skeleton conversion you must enable aiProcess_PopulateArmatureData to populate this 
.SS "unsigned int aiSkeletonBone::mNumnWeights"

.PP
The number of weights\&. 
.SS "\fBC_STRUCT\fP \fBaiMatrix4x4\fP aiSkeletonBone::mOffsetMatrix"
Matrix that transforms from bone space to mesh space in bind pose\&.
.PP
This matrix describes the position of the mesh in the local space of this bone when the skeleton was bound\&. Thus it can be used directly to determine a desired vertex position, given the world-space transform of the bone when animated, and the position of the vertex in mesh space\&.
.PP
It is sometimes called an inverse-bind matrix, or inverse bind pose matrix\&. 
.SS "int aiSkeletonBone::mParent"

.PP
The parent bone index, is -1 one if this bone represents the root bone\&. 
.SS "\fBC_STRUCT\fP \fBaiVertexWeight\fP* aiSkeletonBone::mWeights"

.PP
The influence weights of this bone, by vertex index\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
