.TH "aiSkeleton" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiSkeleton \- 
.br
  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mesh\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiString\fP \fBmName\fP"
.br
.ti -1c
.RI "unsigned int \fBmNumBones\fP"
.br
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiSkeletonBone\fP ** \fBmBones\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.br
 
.SH "Member Data Documentation"
.PP 
.SS "\fBC_STRUCT\fP \fBaiSkeletonBone\fP** aiSkeleton::mBones"

.SS "\fBC_STRUCT\fP \fBaiString\fP aiSkeleton::mName"

.SS "unsigned int aiSkeleton::mNumBones"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
