.TH "aiString" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiString
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBai_uint32\fP \fBlength\fP"
.br
.ti -1c
.RI "char \fBdata\fP [\fBMAXLEN\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents an UTF-8 string, zero byte terminated\&.
.PP
The character set of an \fBaiString\fP is explicitly defined to be UTF-8\&. This Unicode transformation was chosen in the belief that most strings in 3d files are limited to ASCII, thus the character set needed to be strictly ASCII compatible\&.
.PP
Most text file loaders provide proper Unicode input file handling, special unicode characters are correctly transcoded to UTF8 and are kept throughout the libraries' import pipeline\&.
.PP
For most applications, it will be absolutely sufficient to interpret the \fBaiString\fP as ASCII data and work with it as one would work with a plain char*\&. Windows users in need of proper support for i\&.e asian characters can use the MultiByteToWideChar(), WideCharToMultiByte() WinAPI functionality to convert the UTF-8 strings to their working character set (i\&.e\&. MBCS, WideChar)\&.
.PP
We use this representation instead of std::string to be C-compatible\&. The (binary) length of such a string is limited to MAXLEN characters (including the the terminating zero)\&. 
.SH "Member Data Documentation"
.PP 
.SS "char aiString::data[\fBMAXLEN\fP]"
String buffer\&. Size limit is MAXLEN 
.SS "\fBai_uint32\fP aiString::length"
Binary length of the string excluding the terminal 0\&. This is NOT the logical length of strings containing UTF-8 multi-byte sequences! It's the number of bytes from the beginning of the string to its end\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
