.TH "aiVectorKey" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiVectorKey
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <anim\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBaiVector3D\fP \fBelem_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaiVectorKey\fP () \fBAI_NO_EXCEPT\fP"
.br
.RI "The default constructor\&. "
.ti -1c
.RI "\fBaiVectorKey\fP (double time, const \fBaiVector3D\fP &\fBvalue\fP)"
.br
.RI "Construction from a given time and key value\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBaiVectorKey\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBaiVectorKey\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBaiVectorKey\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBaiVectorKey\fP &rhs) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBmTime\fP"
.br
.ti -1c
.RI "\fBC_STRUCT\fP \fBaiVector3D\fP \fBmValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A time-value pair specifying a certain 3D vector for the given time\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "typedef \fBaiVector3D\fP \fBaiVectorKey::elem_type\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "aiVectorKey::aiVectorKey ()\fR [inline]\fP"

.PP
The default constructor\&. 
.SS "aiVectorKey::aiVectorKey (double time, const \fBaiVector3D\fP & value)\fR [inline]\fP"

.PP
Construction from a given time and key value\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool aiVectorKey::operator!= (const \fBaiVectorKey\fP & rhs) const\fR [inline]\fP"

.SS "bool aiVectorKey::operator< (const \fBaiVectorKey\fP & rhs) const\fR [inline]\fP"

.SS "bool aiVectorKey::operator== (const \fBaiVectorKey\fP & rhs) const\fR [inline]\fP"

.SS "bool aiVectorKey::operator> (const \fBaiVectorKey\fP & rhs) const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double aiVectorKey::mTime"
The time of this key 
.SS "\fBC_STRUCT\fP \fBaiVector3D\fP aiVectorKey::mValue"
The value of this key 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
