.TH "aiVertexWeight" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiVertexWeight \- A single influence of a bone on a vertex\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mesh\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBmVertexId\fP"
.br
.RI "Index of the vertex which is influenced by the bone\&. "
.ti -1c
.RI "\fBai_real\fP \fBmWeight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A single influence of a bone on a vertex\&. 
.SH "Member Data Documentation"
.PP 
.SS "unsigned int aiVertexWeight::mVertexId"

.PP
Index of the vertex which is influenced by the bone\&. 
.SS "\fBai_real\fP aiVertexWeight::mWeight"
The strength of the influence in the range (0\&.\&.\&.1)\&. The influence from all bones at one vertex amounts to 1\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
