.TH "adhed/libbacktrace/alloc.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/libbacktrace/alloc.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include <errno\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <sys/types\&.h>\fP
.br
\fR#include 'backtrace\&.hpp'\fP
.br
\fR#include 'internal\&.hpp'\fP
.br
\fR#include '\&.\&./common/TracyAlloc\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBtracy::backtrace_alloc\fP (\fBstruct\fP \fBbacktrace_state\fP *state \fBATTRIBUTE_UNUSED\fP, size_t \fBsize\fP, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtracy::backtrace_free\fP (\fBstruct\fP \fBbacktrace_state\fP *state \fBATTRIBUTE_UNUSED\fP, \fBvoid\fP *p, size_t \fBsize\fP \fBATTRIBUTE_UNUSED\fP, \fBbacktrace_error_callback\fP error_callback \fBATTRIBUTE_UNUSED\fP, \fBvoid\fP *\fBdata\fP \fBATTRIBUTE_UNUSED\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBtracy::backtrace_vector_grow\fP (\fBstruct\fP \fBbacktrace_state\fP *state \fBATTRIBUTE_UNUSED\fP, size_t \fBsize\fP, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP, \fBstruct\fP \fBbacktrace_vector\fP *vec)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBtracy::backtrace_vector_finish\fP (\fBstruct\fP \fBbacktrace_state\fP *state, \fBstruct\fP \fBbacktrace_vector\fP *vec, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP)"
.br
.ti -1c
.RI "int \fBtracy::backtrace_vector_release\fP (\fBstruct\fP \fBbacktrace_state\fP *state \fBATTRIBUTE_UNUSED\fP, \fBstruct\fP \fBbacktrace_vector\fP *vec, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
