.TH "Assimp::SceneHelper" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::SceneHelper \- Utility for \fBSceneCombiner\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SceneCombiner\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSceneHelper\fP ()"
.br
.ti -1c
.RI "\fBSceneHelper\fP (\fBaiScene\fP *_scene)"
.br
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP \fBaiScene\fP * \fBoperator\->\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaiScene\fP * \fBscene\fP"
.br
.ti -1c
.RI "char \fBid\fP [32]"
.br
.ti -1c
.RI "unsigned int \fBidlen\fP"
.br
.ti -1c
.RI "std::set< unsigned int > \fBhashes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Utility for \fBSceneCombiner\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Assimp::SceneHelper::SceneHelper ()\fR [inline]\fP"

.SS "Assimp::SceneHelper::SceneHelper (\fBaiScene\fP * _scene)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBAI_FORCE_INLINE\fP \fBaiScene\fP * Assimp::SceneHelper::operator\-> () const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::set<unsigned int> Assimp::SceneHelper::hashes"

.SS "char Assimp::SceneHelper::id[32]"

.SS "unsigned int Assimp::SceneHelper::idlen"

.SS "\fBaiScene\fP* Assimp::SceneHelper::scene"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
