.TH "Assimp::SGSpatialSort::Entry" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::SGSpatialSort::Entry
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SGSpatialSort\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntry\fP () \fBAI_NO_EXCEPT\fP"
.br
.ti -1c
.RI "\fBEntry\fP (unsigned int pIndex, const \fBaiVector3D\fP &pPosition, float pDistance, uint32_t pSG)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBEntry\fP &\fBe\fP) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBmIndex\fP"
.br
.RI "The vertex referred by this entry\&. "
.ti -1c
.RI "\fBaiVector3D\fP \fBmPosition\fP"
.br
.RI "Position\&. "
.ti -1c
.RI "uint32_t \fBmSmoothGroups\fP"
.br
.ti -1c
.RI "float \fBmDistance\fP"
.br
.RI "Distance of this vertex to the sorting plane\&. "
.in -1c
.SH "Detailed Description"
.PP 
An entry in a spatially sorted position array\&. Consists of a vertex index, its position and its pre-calculated distance from the reference plane 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Assimp::SGSpatialSort::Entry::Entry ()\fR [inline]\fP"

.SS "Assimp::SGSpatialSort::Entry::Entry (unsigned int pIndex, const \fBaiVector3D\fP & pPosition, float pDistance, uint32_t pSG)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool Assimp::SGSpatialSort::Entry::operator< (const \fBEntry\fP & e) const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float Assimp::SGSpatialSort::Entry::mDistance"

.PP
Distance of this vertex to the sorting plane\&. 
.SS "unsigned int Assimp::SGSpatialSort::Entry::mIndex"

.PP
The vertex referred by this entry\&. 
.SS "\fBaiVector3D\fP Assimp::SGSpatialSort::Entry::mPosition"

.PP
Position\&. 
.SS "uint32_t Assimp::SGSpatialSort::Entry::mSmoothGroups"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
