.TH "Assimp::TXmlParser< TNodeType >" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::TXmlParser< TNodeType > \- The Xml-Parser class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <XmlParser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTXmlParser\fP ()"
.br
.RI "The default class constructor\&. "
.ti -1c
.RI "\fB~TXmlParser\fP ()"
.br
.RI "The class destructor\&. "
.ti -1c
.RI "\fBvoid\fP \fBclear\fP ()"
.br
.RI "Will clear the parsed xml-file\&. "
.ti -1c
.RI "TNodeType * \fBfindNode\fP (const std::string &\fBname\fP)"
.br
.RI "Will search for a child-node by its name\&. "
.ti -1c
.RI "bool \fBhasNode\fP (const std::string &\fBname\fP)"
.br
.RI "Will return true, if the node is a child-node\&. "
.ti -1c
.RI "bool \fBparse\fP (\fBIOStream\fP *\fBstream\fP)"
.br
.RI "Will parse an xml-file from a given stream\&. "
.ti -1c
.RI "bool \fBhasRoot\fP () const"
.br
.RI "Will return true if a root node is there\&. "
.ti -1c
.RI "pugi::xml_document * \fBgetDocument\fP () const"
.br
.RI "Will return the document pointer, is nullptr if no xml-file was parsed\&. "
.ti -1c
.RI "const TNodeType \fBgetRootNode\fP () const"
.br
.RI "Will return the root node, const version\&. "
.ti -1c
.RI "TNodeType \fBgetRootNode\fP ()"
.br
.RI "Will return the root node, non-const version\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBhasNode\fP (\fBXmlNode\fP &node, const char *\fBname\fP)"
.br
.RI "Will check if a node with the given name is in\&. "
.ti -1c
.RI "static bool \fBhasAttribute\fP (\fBXmlNode\fP &xmlNode, const char *\fBname\fP)"
.br
.RI "Will check if an attribute is part of the XmlNode\&. "
.ti -1c
.RI "static bool \fBgetUIntAttribute\fP (\fBXmlNode\fP &xmlNode, const char *\fBname\fP, unsigned int &\fBval\fP)"
.br
.RI "Will try to get an unsigned int attribute value\&. "
.ti -1c
.RI "static bool \fBgetIntAttribute\fP (\fBXmlNode\fP &xmlNode, const char *\fBname\fP, int &\fBval\fP)"
.br
.RI "Will try to get an int attribute value\&. "
.ti -1c
.RI "static bool \fBgetRealAttribute\fP (\fBXmlNode\fP &xmlNode, const char *\fBname\fP, \fBai_real\fP &\fBval\fP)"
.br
.RI "Will try to get a real attribute value\&. "
.ti -1c
.RI "static bool \fBgetFloatAttribute\fP (\fBXmlNode\fP &xmlNode, const char *\fBname\fP, float &\fBval\fP)"
.br
.RI "Will try to get a float attribute value\&. "
.ti -1c
.RI "static bool \fBgetDoubleAttribute\fP (\fBXmlNode\fP &xmlNode, const char *\fBname\fP, double &\fBval\fP)"
.br
.RI "Will try to get a double attribute value\&. "
.ti -1c
.RI "static bool \fBgetStdStrAttribute\fP (\fBXmlNode\fP &xmlNode, const char *\fBname\fP, std::string &\fBval\fP)"
.br
.RI "Will try to get a std::string attribute value\&. "
.ti -1c
.RI "static bool \fBgetBoolAttribute\fP (\fBXmlNode\fP &xmlNode, const char *\fBname\fP, bool &\fBval\fP)"
.br
.RI "Will try to get a bool attribute value\&. "
.ti -1c
.RI "static bool \fBgetValueAsString\fP (\fBXmlNode\fP &node, std::string &text)"
.br
.RI "Will try to get the value of the node as a string\&. "
.ti -1c
.RI "static bool \fBgetValueAsFloat\fP (\fBXmlNode\fP &node, \fBai_real\fP &\fBv\fP)"
.br
.RI "Will try to get the value of the node as a float\&. "
.ti -1c
.RI "static bool \fBgetValueAsInt\fP (\fBXmlNode\fP &node, int &\fBv\fP)"
.br
.RI "Will try to get the value of the node as an integer\&. "
.ti -1c
.RI "static bool \fBgetValueAsBool\fP (\fBXmlNode\fP &node, bool &\fBv\fP)"
.br
.RI "Will try to get the value of the node as an bool\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class TNodeType>
.br
class Assimp::TXmlParser< TNodeType >"The Xml-Parser class\&. 

Use this parser if you have to import any kind of xml-format\&.
.PP
An example: 
.PP
.nf
TXmlParser<XmlNode> theParser;
if (theParser\&.parse(fileStream)) {
    auto node = theParser\&.getRootNode();
    for ( auto currentNode : node\&.children()) {
        // Will loop over all children
    }
}

.fi
.PP
 
.PP
\fBTemplate Parameters\fP
.RS 4
\fITNodeType\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class TNodeType > \fBAssimp::TXmlParser\fP< TNodeType >::TXmlParser ()\fR [inline]\fP"

.PP
The default class constructor\&. 
.SS "template<class TNodeType > \fBAssimp::TXmlParser\fP< TNodeType >::~\fBTXmlParser\fP ()\fR [inline]\fP"

.PP
The class destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<class TNodeType > \fBvoid\fP \fBAssimp::TXmlParser\fP< TNodeType >::clear ()\fR [inline]\fP"

.PP
Will clear the parsed xml-file\&. 
.SS "template<class TNodeType > TNodeType * \fBAssimp::TXmlParser\fP< TNodeType >::findNode (const std::string & name)\fR [inline]\fP"

.PP
Will search for a child-node by its name\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP [in] The name of the child-node\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The node instance or nullptr, if nothing was found\&. 
.RE
.PP

.SS "template<class TNodeType > bool \fBAssimp::TXmlParser\fP< TNodeType >::getBoolAttribute (\fBXmlNode\fP & xmlNode, const char * name, bool & val)\fR [inline]\fP, \fR [static]\fP"

.PP
Will try to get a bool attribute value\&. 
.PP
\fBParameters\fP
.RS 4
\fIxmlNode\fP [in] The node to search in\&. 
.br
\fIname\fP [in] The attribute name to look for\&. 
.br
\fIval\fP [out] The bool value from the attribute\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true, if the node contains an attribute with the given name and if the value is a bool\&. 
.RE
.PP

.SS "template<class TNodeType > pugi::xml_document * \fBAssimp::TXmlParser\fP< TNodeType >::getDocument () const"

.PP
Will return the document pointer, is nullptr if no xml-file was parsed\&. 
.PP
\fBReturns\fP
.RS 4
The pointer showing to the document\&. 
.RE
.PP

.SS "template<class TNodeType > bool \fBAssimp::TXmlParser\fP< TNodeType >::getDoubleAttribute (\fBXmlNode\fP & xmlNode, const char * name, double & val)\fR [inline]\fP, \fR [static]\fP"

.PP
Will try to get a double attribute value\&. 
.PP
\fBParameters\fP
.RS 4
\fIxmlNode\fP [in] The node to search in\&. 
.br
\fIname\fP [in] The attribute name to look for\&. 
.br
\fIval\fP [out] The double value from the attribute\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true, if the node contains an attribute with the given name and if the value is a double\&. 
.RE
.PP

.SS "template<class TNodeType > bool \fBAssimp::TXmlParser\fP< TNodeType >::getFloatAttribute (\fBXmlNode\fP & xmlNode, const char * name, float & val)\fR [inline]\fP, \fR [static]\fP"

.PP
Will try to get a float attribute value\&. 
.PP
\fBParameters\fP
.RS 4
\fIxmlNode\fP [in] The node to search in\&. 
.br
\fIname\fP [in] The attribute name to look for\&. 
.br
\fIval\fP [out] The float value from the attribute\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true, if the node contains an attribute with the given name and if the value is a float\&. 
.RE
.PP

.SS "template<class TNodeType > bool \fBAssimp::TXmlParser\fP< TNodeType >::getIntAttribute (\fBXmlNode\fP & xmlNode, const char * name, int & val)\fR [inline]\fP, \fR [static]\fP"

.PP
Will try to get an int attribute value\&. 
.PP
\fBParameters\fP
.RS 4
\fIxmlNode\fP [in] The node to search in\&. 
.br
\fIname\fP [in] The attribute name to look for\&. 
.br
\fIval\fP [out] The int value from the attribute\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true, if the node contains an attribute with the given name and if the value is an int\&. 
.RE
.PP

.SS "template<class TNodeType > bool \fBAssimp::TXmlParser\fP< TNodeType >::getRealAttribute (\fBXmlNode\fP & xmlNode, const char * name, \fBai_real\fP & val)\fR [inline]\fP, \fR [static]\fP"

.PP
Will try to get a real attribute value\&. 
.PP
\fBParameters\fP
.RS 4
\fIxmlNode\fP [in] The node to search in\&. 
.br
\fIname\fP [in] The attribute name to look for\&. 
.br
\fIval\fP [out] The real value from the attribute\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true, if the node contains an attribute with the given name and if the value is a real\&. 
.RE
.PP

.SS "template<class TNodeType > TNodeType \fBAssimp::TXmlParser\fP< TNodeType >::getRootNode ()"

.PP
Will return the root node, non-const version\&. 
.PP
\fBReturns\fP
.RS 4
The root node\&. 
.RE
.PP

.SS "template<class TNodeType > const TNodeType \fBAssimp::TXmlParser\fP< TNodeType >::getRootNode () const"

.PP
Will return the root node, const version\&. 
.PP
\fBReturns\fP
.RS 4
The root node\&. 
.RE
.PP

.SS "template<class TNodeType > bool \fBAssimp::TXmlParser\fP< TNodeType >::getStdStrAttribute (\fBXmlNode\fP & xmlNode, const char * name, std::string & val)\fR [inline]\fP, \fR [static]\fP"

.PP
Will try to get a std::string attribute value\&. 
.PP
\fBParameters\fP
.RS 4
\fIxmlNode\fP [in] The node to search in\&. 
.br
\fIname\fP [in] The attribute name to look for\&. 
.br
\fIval\fP [out] The std::string value from the attribute\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true, if the node contains an attribute with the given name and if the value is a std::string\&. 
.RE
.PP

.SS "template<class TNodeType > bool \fBAssimp::TXmlParser\fP< TNodeType >::getUIntAttribute (\fBXmlNode\fP & xmlNode, const char * name, unsigned int & val)\fR [inline]\fP, \fR [static]\fP"

.PP
Will try to get an unsigned int attribute value\&. 
.PP
\fBParameters\fP
.RS 4
\fIxmlNode\fP [in] The node to search in\&. 
.br
\fIname\fP [in] The attribute name to look for\&. 
.br
\fIval\fP [out] The unsigned int value from the attribute\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true, if the node contains an attribute with the given name and if the value is an unsigned int\&. 
.RE
.PP

.SS "template<class TNodeType > bool \fBAssimp::TXmlParser\fP< TNodeType >::getValueAsBool (\fBXmlNode\fP & node, bool & v)\fR [inline]\fP, \fR [static]\fP"

.PP
Will try to get the value of the node as an bool\&. 
.PP
\fBParameters\fP
.RS 4
\fInode\fP [in] The node to search in\&. 
.br
\fItext\fP [out] The value as a bool\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true, if the value can be read out\&. 
.RE
.PP

.SS "template<class TNodeType > bool \fBAssimp::TXmlParser\fP< TNodeType >::getValueAsFloat (\fBXmlNode\fP & node, \fBai_real\fP & v)\fR [inline]\fP, \fR [static]\fP"

.PP
Will try to get the value of the node as a float\&. 
.PP
\fBParameters\fP
.RS 4
\fInode\fP [in] The node to search in\&. 
.br
\fItext\fP [out] The value as a float\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true, if the value can be read out\&. 
.RE
.PP

.SS "template<class TNodeType > bool \fBAssimp::TXmlParser\fP< TNodeType >::getValueAsInt (\fBXmlNode\fP & node, int & v)\fR [inline]\fP, \fR [static]\fP"

.PP
Will try to get the value of the node as an integer\&. 
.PP
\fBParameters\fP
.RS 4
\fInode\fP [in] The node to search in\&. 
.br
\fItext\fP [out] The value as a int\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true, if the value can be read out\&. 
.RE
.PP

.SS "template<class TNodeType > bool \fBAssimp::TXmlParser\fP< TNodeType >::getValueAsString (\fBXmlNode\fP & node, std::string & text)\fR [inline]\fP, \fR [static]\fP"

.PP
Will try to get the value of the node as a string\&. 
.PP
\fBParameters\fP
.RS 4
\fInode\fP [in] The node to search in\&. 
.br
\fItext\fP [out] The value as a text\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true, if the value can be read out\&. 
.RE
.PP

.SS "template<class TNodeType > bool \fBAssimp::TXmlParser\fP< TNodeType >::hasAttribute (\fBXmlNode\fP & xmlNode, const char * name)\fR [inline]\fP, \fR [static]\fP"

.PP
Will check if an attribute is part of the XmlNode\&. 
.PP
\fBParameters\fP
.RS 4
\fIxmlNode\fP [in] The node to search in\&. 
.br
\fIname\fP [in} The attribute name to look for\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true, if the was found, false if not\&. 
.RE
.PP

.SS "template<class TNodeType > bool \fBAssimp::TXmlParser\fP< TNodeType >::hasNode (const std::string & name)"

.PP
Will return true, if the node is a child-node\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP [in] The name of the child node to look for\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true, if the node is a child-node or false if not\&. 
.RE
.PP

.SS "template<class TNodeType > bool \fBAssimp::TXmlParser\fP< TNodeType >::hasNode (\fBXmlNode\fP & node, const char * name)\fR [inline]\fP, \fR [static]\fP"

.PP
Will check if a node with the given name is in\&. 
.PP
\fBParameters\fP
.RS 4
\fInode\fP [in] The node to look in\&. 
.br
\fIname\fP [in] The name of the child-node\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true, if node was found, false if not\&. 
.RE
.PP

.SS "template<class TNodeType > bool \fBAssimp::TXmlParser\fP< TNodeType >::hasRoot () const"

.PP
Will return true if a root node is there\&. 
.PP
\fBReturns\fP
.RS 4
true in case of an existing root\&. 
.RE
.PP

.SS "template<class TNodeType > bool \fBAssimp::TXmlParser\fP< TNodeType >::parse (\fBIOStream\fP * stream)"

.PP
Will parse an xml-file from a given stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIstream\fP The input stream\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true, if the parsing was successful, false if not\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
