.TH "Assimp::Logger" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::Logger \- CPP-API: Abstract interface for logger implementations\&. \fBAssimp\fP provides a default implementation and uses it for almost all logging stuff ('\fBDefaultLogger\fP')\&. This class defines just basic logging behavior and is not of interest for you\&. Instead, take a look at #DefaultLogger\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Logger\&.hpp>\fP
.PP
Inherits Intern::AllocateFromAssimpHeap\&.
.PP
Inherited by \fBAssimp::DefaultLogger\fP, and \fBAssimp::NullLogger\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBLogSeverity\fP { \fBNORMAL\fP, \fBDEBUGGING\fP, \fBVERBOSE\fP }"
.br
.RI "Log severity to describe the granularity of logging\&. "
.ti -1c
.RI "enum \fBErrorSeverity\fP { \fBDebugging\fP = 1, \fBInfo\fP = 2, \fBWarn\fP = 4, \fBErr\fP = 8 }"
.br
.RI "Description for severity of a log message\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Logger\fP ()"
.br
.RI "Virtual destructor\&. "
.ti -1c
.RI "\fBvoid\fP \fBdebug\fP (const char *message)"
.br
.RI "Writes a debug message\&. "
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBvoid\fP \fBdebug\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBvoid\fP \fBverboseDebug\fP (const char *message)"
.br
.RI "Writes a debug message\&. "
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBvoid\fP \fBverboseDebug\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBvoid\fP \fBinfo\fP (const char *message)"
.br
.RI "Writes a info message\&. "
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBvoid\fP \fBinfo\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBvoid\fP \fBwarn\fP (const char *message)"
.br
.RI "Writes a warning message\&. "
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBvoid\fP \fBwarn\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBvoid\fP \fBerror\fP (const char *message)"
.br
.RI "Writes an error message\&. "
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBvoid\fP \fBerror\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetLogSeverity\fP (\fBLogSeverity\fP log_severity)"
.br
.RI "Set a new log severity\&. "
.ti -1c
.RI "\fBLogSeverity\fP \fBgetLogSeverity\fP () const"
.br
.RI "Get the current log severity\&. "
.ti -1c
.RI "virtual bool \fBattachStream\fP (\fBLogStream\fP *pStream, unsigned int severity=\fBDebugging\fP|\fBErr\fP|\fBWarn\fP|\fBInfo\fP)=0"
.br
.RI "Attach a new log-stream\&. "
.ti -1c
.RI "virtual bool \fBdetachStream\fP (\fBLogStream\fP *pStream, unsigned int severity=\fBDebugging\fP|\fBErr\fP|\fBWarn\fP|\fBInfo\fP)=0"
.br
.RI "Detach a still attached stream from the logger (or modify the filter flags bits) "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBLogger\fP () \fBAI_NO_EXCEPT\fP"
.br
.ti -1c
.RI "\fBLogger\fP (\fBLogSeverity\fP severity)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBOnDebug\fP (const char *message)=0"
.br
.RI "Called as a request to write a specific debug message\&. "
.ti -1c
.RI "virtual \fBvoid\fP \fBOnVerboseDebug\fP (const char *message)=0"
.br
.RI "Called as a request to write a specific verbose debug message\&. "
.ti -1c
.RI "virtual \fBvoid\fP \fBOnInfo\fP (const char *message)=0"
.br
.RI "Called as a request to write a specific info message\&. "
.ti -1c
.RI "virtual \fBvoid\fP \fBOnWarn\fP (const char *essage)=0"
.br
.RI "Called as a request to write a specific warn message\&. "
.ti -1c
.RI "virtual \fBvoid\fP \fBOnError\fP (const char *message)=0"
.br
.RI "Called as a request to write a specific error message\&. "
.ti -1c
.RI "std::string \fBformatMessage\fP (\fBAssimp::Formatter::format\fP \fBf\fP)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T, typename \fBU\fP > std::string \fBformatMessage\fP (\fBAssimp::Formatter::format\fP \fBf\fP, \fBU\fP &&u, \fBT\fP &&\&.\&.\&. args)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBLogSeverity\fP \fBm_Severity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CPP-API: Abstract interface for logger implementations\&. \fBAssimp\fP provides a default implementation and uses it for almost all logging stuff ('\fBDefaultLogger\fP')\&. This class defines just basic logging behavior and is not of interest for you\&. Instead, take a look at #DefaultLogger\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "\fBenum\fP \fBAssimp::Logger::ErrorSeverity\fP"

.PP
Description for severity of a log message\&. Every \fBLogStream\fP has a bitwise combination of these flags\&. A \fBLogStream\fP doesn't receive any messages of a specific type if it doesn't specify the corresponding ErrorSeverity flag\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDebugging \fP\fP
\fBDebug\fP log message\&. 
.TP
\fB\fIInfo \fP\fP
Info log message\&. 
.TP
\fB\fIWarn \fP\fP
Warn log message\&. 
.TP
\fB\fIErr \fP\fP
Error log message\&. 
.SS "\fBenum\fP \fBAssimp::Logger::LogSeverity\fP"

.PP
Log severity to describe the granularity of logging\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINORMAL \fP\fP
Normal granularity of logging\&. 
.TP
\fB\fIDEBUGGING \fP\fP
\fBDebug\fP messages will be logged, but not verbose debug messages\&. 
.TP
\fB\fIVERBOSE \fP\fP
All messages will be logged\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Assimp::Logger::~Logger ()\fR [inline]\fP, \fR [virtual]\fP, \fR [default]\fP"

.PP
Virtual destructor\&. 
.SS "Assimp::Logger::Logger ()\fR [inline]\fP, \fR [protected]\fP"
Default constructor 
.SS "Assimp::Logger::Logger (\fBLogSeverity\fP severity)\fR [inline]\fP, \fR [explicit]\fP, \fR [protected]\fP"
Construction with a given log severity 
.SH "Member Function Documentation"
.PP 
.SS "virtual bool Assimp::Logger::attachStream (\fBLogStream\fP * pStream, unsigned int severity = \fR\fBDebugging\fP|\fBErr\fP|\fBWarn\fP|\fBInfo\fP\fP)\fR [pure virtual]\fP"

.PP
Attach a new log-stream\&. The logger takes ownership of the stream and is responsible for its destruction (which is done using delete when the logger itself is destroyed)\&. Call detachStream to detach a stream and to gain ownership of it again\&. 
.PP
\fBParameters\fP
.RS 4
\fIpStream\fP Log-stream to attach 
.br
\fIseverity\fP Message filter, specified which types of log messages are dispatched to the stream\&. Provide a bitwise combination of the ErrorSeverity flags\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true if the stream has been attached, false otherwise\&. 
.RE
.PP

.PP
Implemented in \fBAssimp::DefaultLogger\fP, and \fBAssimp::NullLogger\fP\&.
.SS "\fBvoid\fP Assimp::Logger::debug (const char * message)"

.PP
Writes a debug message\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP \fBDebug\fP message 
.RE
.PP

.SS "template<typename\&.\&.\&. T> \fBvoid\fP Assimp::Logger::debug (\fBT\fP &&\&.\&.\&. args)\fR [inline]\fP"

.SS "virtual bool Assimp::Logger::detachStream (\fBLogStream\fP * pStream, unsigned int severity = \fR\fBDebugging\fP|\fBErr\fP|\fBWarn\fP|\fBInfo\fP\fP)\fR [pure virtual]\fP"

.PP
Detach a still attached stream from the logger (or modify the filter flags bits) 
.PP
\fBParameters\fP
.RS 4
\fIpStream\fP Log-stream instance for detaching 
.br
\fIseverity\fP Provide a bitwise combination of the ErrorSeverity flags\&. This value is &~ed with the current flags of the stream, if the result is 0 the stream is detached from the \fBLogger\fP and the caller retakes the possession of the stream\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true if the stream has been detached, false otherwise\&. 
.RE
.PP

.PP
Implemented in \fBAssimp::DefaultLogger\fP, and \fBAssimp::NullLogger\fP\&.
.SS "\fBvoid\fP Assimp::Logger::error (const char * message)"

.PP
Writes an error message\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Error message 
.RE
.PP

.SS "template<typename\&.\&.\&. T> \fBvoid\fP Assimp::Logger::error (\fBT\fP &&\&.\&.\&. args)\fR [inline]\fP"

.SS "std::string Assimp::Logger::formatMessage (\fBAssimp::Formatter::format\fP f)\fR [inline]\fP, \fR [protected]\fP"

.SS "template<typename\&.\&.\&. T, typename \fBU\fP > std::string Assimp::Logger::formatMessage (\fBAssimp::Formatter::format\fP f, \fBU\fP && u, \fBT\fP &&\&.\&.\&. args)\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBLogger::LogSeverity\fP Assimp::Logger::getLogSeverity () const\fR [inline]\fP"

.PP
Get the current log severity\&. 
.SS "\fBvoid\fP Assimp::Logger::info (const char * message)"

.PP
Writes a info message\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Info message 
.RE
.PP

.SS "template<typename\&.\&.\&. T> \fBvoid\fP Assimp::Logger::info (\fBT\fP &&\&.\&.\&. args)\fR [inline]\fP"

.SS "virtual \fBvoid\fP Assimp::Logger::OnDebug (const char * message)\fR [protected]\fP, \fR [pure virtual]\fP"

.PP
Called as a request to write a specific debug message\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP \fBDebug\fP message\&. Never longer than MAX_LOG_MESSAGE_LENGTH characters (excluding the '0')\&. 
.RE
.PP
\fBNote\fP
.RS 4
The message string is only valid until the scope of the function is left\&. 
.RE
.PP

.PP
Implemented in \fBAssimp::NullLogger\fP\&.
.SS "virtual \fBvoid\fP Assimp::Logger::OnError (const char * message)\fR [protected]\fP, \fR [pure virtual]\fP"

.PP
Called as a request to write a specific error message\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Error message\&. Never longer than MAX_LOG_MESSAGE_LENGTH characters (exluding the '0')\&. 
.RE
.PP
\fBNote\fP
.RS 4
The message string is only valid until the scope of the function is left\&. 
.RE
.PP

.PP
Implemented in \fBAssimp::NullLogger\fP\&.
.SS "virtual \fBvoid\fP Assimp::Logger::OnInfo (const char * message)\fR [protected]\fP, \fR [pure virtual]\fP"

.PP
Called as a request to write a specific info message\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Info message\&. Never longer than MAX_LOG_MESSAGE_LENGTH characters (ecxluding the '0')\&. 
.RE
.PP
\fBNote\fP
.RS 4
The message string is only valid until the scope of the function is left\&. 
.RE
.PP

.PP
Implemented in \fBAssimp::NullLogger\fP\&.
.SS "virtual \fBvoid\fP Assimp::Logger::OnVerboseDebug (const char * message)\fR [protected]\fP, \fR [pure virtual]\fP"

.PP
Called as a request to write a specific verbose debug message\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP \fBDebug\fP message\&. Never longer than MAX_LOG_MESSAGE_LENGTH characters (excluding the '0')\&. 
.RE
.PP
\fBNote\fP
.RS 4
The message string is only valid until the scope of the function is left\&. 
.RE
.PP

.PP
Implemented in \fBAssimp::NullLogger\fP\&.
.SS "virtual \fBvoid\fP Assimp::Logger::OnWarn (const char * essage)\fR [protected]\fP, \fR [pure virtual]\fP"

.PP
Called as a request to write a specific warn message\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Warn message\&. Never longer than MAX_LOG_MESSAGE_LENGTH characters (exluding the '0')\&. 
.RE
.PP
\fBNote\fP
.RS 4
The message string is only valid until the scope of the function is left\&. 
.RE
.PP

.PP
Implemented in \fBAssimp::NullLogger\fP\&.
.SS "\fBvoid\fP Assimp::Logger::setLogSeverity (\fBLogSeverity\fP log_severity)\fR [inline]\fP"

.PP
Set a new log severity\&. 
.PP
\fBParameters\fP
.RS 4
\fIlog_severity\fP New severity for logging 
.RE
.PP

.SS "\fBvoid\fP Assimp::Logger::verboseDebug (const char * message)"

.PP
Writes a debug message\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP \fBDebug\fP message 
.RE
.PP

.SS "template<typename\&.\&.\&. T> \fBvoid\fP Assimp::Logger::verboseDebug (\fBT\fP &&\&.\&.\&. args)\fR [inline]\fP"

.SS "\fBvoid\fP Assimp::Logger::warn (const char * message)"

.PP
Writes a warning message\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Warn message 
.RE
.PP

.SS "template<typename\&.\&.\&. T> \fBvoid\fP Assimp::Logger::warn (\fBT\fP &&\&.\&.\&. args)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBLogSeverity\fP Assimp::Logger::m_Severity\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
