.TH "Assimp::Intern::Getter< SwapEndianess, T, RuntimeSwitch >" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::Intern::Getter< SwapEndianess, T, RuntimeSwitch >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ByteSwapper\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBoperator()\fP (\fBT\fP *inout, bool le)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<bool SwapEndianess, typename \fBT\fP , bool RuntimeSwitch> \fBvoid\fP \fBAssimp::Intern::Getter\fP< SwapEndianess, \fBT\fP, RuntimeSwitch >::operator() (\fBT\fP * inout, bool le)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
