.TH "Assimp::Subdivider" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::Subdivider
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Subdivision\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBAlgorithm\fP { \fBCATMULL_CLARKE\fP = 0x1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Subdivider\fP ()"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBSubdivide\fP (\fBaiMesh\fP *mesh, \fBaiMesh\fP *&out, unsigned int num, bool discard_input=false)=0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBSubdivide\fP (\fBaiMesh\fP **smesh, size_t nmesh, \fBaiMesh\fP **out, unsigned int num, bool discard_input=false)=0"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSubdivider\fP * \fBCreate\fP (\fBAlgorithm\fP algo)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helper class to evaluate subdivision surfaces\&. Different algorithms are provided for choice\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "\fBenum\fP \fBAssimp::Subdivider::Algorithm\fP"
Enumerates all supported subvidision algorithms 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICATMULL_CLARKE \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Assimp::Subdivider::~Subdivider ()\fR [inline]\fP, \fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static \fBSubdivider\fP * Assimp::Subdivider::Create (\fBAlgorithm\fP algo)\fR [static]\fP"
Create a subdivider of a specific type
.PP
\fBParameters\fP
.RS 4
\fIalgo\fP Algorithm to be used for subdivision 
.RE
.PP
\fBReturns\fP
.RS 4
\fBSubdivider\fP instance\&. 
.RE
.PP

.SS "virtual \fBvoid\fP Assimp::Subdivider::Subdivide (\fBaiMesh\fP ** smesh, size_t nmesh, \fBaiMesh\fP ** out, unsigned int num, bool discard_input = \fRfalse\fP)\fR [pure virtual]\fP"
Subdivide multiple meshes using the selected algorithm\&. This avoids erroneous smoothing on objects consisting of multiple per-material meshes\&. Usually, most 3d modellers smooth on a per-object base, regardless the materials assigned to the meshes\&.
.PP
\fBParameters\fP
.RS 4
\fIsmesh\fP Array of meshes to be subdivided\&. Must be in verbose format\&. 
.br
\fInmesh\fP Number of meshes in smesh\&. 
.br
\fIout\fP Receives the output meshes\&. The array must be sufficiently large (at least \fRnmesh\fP elements) and may not overlap the input array\&. Output meshes map one-to-one to their corresponding input meshes\&. The meshes are allocated by the function\&. 
.br
\fIdiscard_input\fP If true is passed, input meshes are deleted after the subdivision is complete\&. This can improve performance because it allows the optimization of reusing existing meshes for intermediate results\&. 
.br
\fInum\fP Number of subdivisions to perform\&. 
.RE
.PP
\fBPrecondition\fP
.RS 4
nmesh != 0, smesh and out may not overlap 
.RE
.PP

.SS "virtual \fBvoid\fP Assimp::Subdivider::Subdivide (\fBaiMesh\fP * mesh, \fBaiMesh\fP *& out, unsigned int num, bool discard_input = \fRfalse\fP)\fR [pure virtual]\fP"
Subdivide a mesh using the selected algorithm
.PP
\fBParameters\fP
.RS 4
\fImesh\fP First mesh to be subdivided\&. Must be in verbose format\&. 
.br
\fIout\fP Receives the output mesh, allocated by me\&. 
.br
\fInum\fP Number of subdivisions to perform\&. 
.br
\fIdiscard_input\fP If true is passed, the input mesh is deleted after the subdivision is complete\&. This can improve performance because it allows the optimization to reuse the existing mesh for intermediate results\&. 
.RE
.PP
\fBPrecondition\fP
.RS 4
out!=mesh 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
