.TH "Assimp::LogStream" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::LogStream \- CPP-API: Abstract interface for log stream implementations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <LogStream\&.hpp>\fP
.PP
Inherits Intern::AllocateFromAssimpHeap\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~LogStream\fP ()"
.br
.RI "Virtual destructor 
.br
 "
.ti -1c
.RI "virtual \fBvoid\fP \fBwrite\fP (const char *message)=0"
.br
.RI "Overwrite this for your own output methods\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLogStream\fP * \fBcreateDefaultStream\fP (\fBaiDefaultLogStream\fP \fBstream\fP, const char *\fBname\fP='AssimpLog\&.txt', \fBIOSystem\fP *io=nullptr)"
.br
.RI "Creates a default log stream\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBLogStream\fP () \fBAI_NO_EXCEPT\fP"
.br
.RI "Default constructor\&. "
.in -1c
.SH "Detailed Description"
.PP 
CPP-API: Abstract interface for log stream implementations\&. 

Several default implementations are provided, see \fBaiDefaultLogStream\fP for more details\&. Writing your own implementation of \fBLogStream\fP is just necessary if these are not enough for your purpose\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Assimp::LogStream::LogStream ()\fR [inline]\fP, \fR [protected]\fP, \fR [default]\fP"

.PP
Default constructor\&. 
.SS "Assimp::LogStream::~LogStream ()\fR [inline]\fP, \fR [virtual]\fP, \fR [default]\fP"

.PP
Virtual destructor 
.br
 
.SH "Member Function Documentation"
.PP 
.SS "static \fBLogStream\fP * Assimp::LogStream::createDefaultStream (\fBaiDefaultLogStream\fP stream, const char * name = \fR'AssimpLog\&.txt'\fP, \fBIOSystem\fP * io = \fRnullptr\fP)\fR [static]\fP"

.PP
Creates a default log stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIstreams\fP Type of the default stream 
.br
\fIname\fP For aiDefaultLogStream_FILE: name of the output file 
.br
\fIio\fP For aiDefaultLogStream_FILE: \fBIOSystem\fP to be used to open the output file\&. Pass nullptr for the default implementation\&. 
.RE
.PP
\fBReturns\fP
.RS 4
New \fBLogStream\fP instance\&. 
.br
 
.RE
.PP

.SS "virtual \fBvoid\fP Assimp::LogStream::write (const char * message)\fR [pure virtual]\fP"

.PP
Overwrite this for your own output methods\&. Log messages \fImay\fP consist of multiple lines and you shouldn't expect a consistent formatting\&. If you want custom formatting (e\&.g\&. generate HTML), supply a custom instance of \fBLogger\fP to #DefaultLogger:set()\&. Usually you can \fIexpect\fP that a log message is exactly one line and terminated with a single 
.br
 character\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP Message to be written 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
