.TH "Assimp::Exporter::ExportFormatEntry" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::Exporter::ExportFormatEntry
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Exporter\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExportFormatEntry\fP (const char *pId, const char *pDesc, const char *pExtension, \fBfpExportFunc\fP pFunction, unsigned int pEnforcePP=0u)"
.br
.ti -1c
.RI "\fBExportFormatEntry\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaiExportFormatDesc\fP \fBmDescription\fP"
.br
.RI "Public description structure to be returned by \fBaiGetExportFormatDescription()\fP "
.ti -1c
.RI "\fBfpExportFunc\fP \fBmExportFunction\fP"
.br
.ti -1c
.RI "unsigned int \fBmEnforcePP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal description of an \fBAssimp\fP export format option 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Assimp::Exporter::ExportFormatEntry::ExportFormatEntry (const char * pId, const char * pDesc, const char * pExtension, \fBfpExportFunc\fP pFunction, unsigned int pEnforcePP = \fR0u\fP)\fR [inline]\fP"

.SS "Assimp::Exporter::ExportFormatEntry::ExportFormatEntry ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBaiExportFormatDesc\fP Assimp::Exporter::ExportFormatEntry::mDescription"

.PP
Public description structure to be returned by \fBaiGetExportFormatDescription()\fP 
.SS "unsigned int Assimp::Exporter::ExportFormatEntry::mEnforcePP"

.SS "\fBfpExportFunc\fP Assimp::Exporter::ExportFormatEntry::mExportFunction"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
