.TH "Assimp::ExportProperties" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::ExportProperties
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Exporter\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef unsigned int \fBKeyType\fP"
.br
.ti -1c
.RI "typedef std::map< \fBKeyType\fP, int > \fBIntPropertyMap\fP"
.br
.ti -1c
.RI "typedef std::map< \fBKeyType\fP, \fBai_real\fP > \fBFloatPropertyMap\fP"
.br
.ti -1c
.RI "typedef std::map< \fBKeyType\fP, std::string > \fBStringPropertyMap\fP"
.br
.ti -1c
.RI "typedef std::map< \fBKeyType\fP, \fBaiMatrix4x4\fP > \fBMatrixPropertyMap\fP"
.br
.ti -1c
.RI "typedef std::map< \fBKeyType\fP, std::function< \fBvoid\fP *(\fBvoid\fP *)> > \fBCallbackPropertyMap\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExportProperties\fP ()"
.br
.ti -1c
.RI "\fBExportProperties\fP (const \fBExportProperties\fP &other)"
.br
.ti -1c
.RI "bool \fBSetPropertyInteger\fP (const char *szName, int iValue)"
.br
.ti -1c
.RI "bool \fBSetPropertyBool\fP (const char *szName, bool \fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBSetPropertyFloat\fP (const char *szName, \fBai_real\fP fValue)"
.br
.ti -1c
.RI "bool \fBSetPropertyString\fP (const char *szName, const std::string &sValue)"
.br
.ti -1c
.RI "bool \fBSetPropertyMatrix\fP (const char *szName, const \fBaiMatrix4x4\fP &sValue)"
.br
.ti -1c
.RI "bool \fBSetPropertyCallback\fP (const char *szName, const std::function< \fBvoid\fP *(\fBvoid\fP *)> &\fBf\fP)"
.br
.ti -1c
.RI "int \fBGetPropertyInteger\fP (const char *szName, int iErrorReturn=0xffffffff) const"
.br
.ti -1c
.RI "bool \fBGetPropertyBool\fP (const char *szName, bool bErrorReturn=false) const"
.br
.ti -1c
.RI "\fBai_real\fP \fBGetPropertyFloat\fP (const char *szName, \fBai_real\fP fErrorReturn=10e10f) const"
.br
.ti -1c
.RI "const std::string \fBGetPropertyString\fP (const char *szName, const std::string &sErrorReturn='') const"
.br
.ti -1c
.RI "const \fBaiMatrix4x4\fP \fBGetPropertyMatrix\fP (const char *szName, const \fBaiMatrix4x4\fP &sErrorReturn=\fBaiMatrix4x4\fP()) const"
.br
.ti -1c
.RI "std::function< \fBvoid\fP *(\fBvoid\fP *)> \fBGetPropertyCallback\fP (const char *szName) const"
.br
.ti -1c
.RI "bool \fBHasPropertyInteger\fP (const char *szName) const"
.br
.ti -1c
.RI "bool \fBHasPropertyBool\fP (const char *szName) const"
.br
.ti -1c
.RI "bool \fBHasPropertyFloat\fP (const char *szName) const"
.br
.ti -1c
.RI "bool \fBHasPropertyString\fP (const char *szName) const"
.br
.ti -1c
.RI "bool \fBHasPropertyMatrix\fP (const char *szName) const"
.br
.ti -1c
.RI "bool \fBHasPropertyCallback\fP (const char *szName) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBIntPropertyMap\fP \fBmIntProperties\fP"
.br
.ti -1c
.RI "\fBFloatPropertyMap\fP \fBmFloatProperties\fP"
.br
.ti -1c
.RI "\fBStringPropertyMap\fP \fBmStringProperties\fP"
.br
.ti -1c
.RI "\fBMatrixPropertyMap\fP \fBmMatrixProperties\fP"
.br
.ti -1c
.RI "\fBCallbackPropertyMap\fP \fBmCallbackProperties\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef std::map<\fBKeyType\fP, std::function<\fBvoid\fP *(\fBvoid\fP *)> > \fBAssimp::ExportProperties::CallbackPropertyMap\fP"

.SS "typedef std::map<\fBKeyType\fP, \fBai_real\fP> \fBAssimp::ExportProperties::FloatPropertyMap\fP"

.SS "typedef std::map<\fBKeyType\fP, int> \fBAssimp::ExportProperties::IntPropertyMap\fP"

.SS "typedef unsigned int \fBAssimp::ExportProperties::KeyType\fP"

.SS "typedef std::map<\fBKeyType\fP, \fBaiMatrix4x4\fP> \fBAssimp::ExportProperties::MatrixPropertyMap\fP"

.SS "typedef std::map<\fBKeyType\fP, std::string> \fBAssimp::ExportProperties::StringPropertyMap\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Assimp::ExportProperties::ExportProperties ()"
Standard constructor 
.PP
\fBSee also\fP
.RS 4
\fBExportProperties()\fP 
.RE
.PP

.SS "Assimp::ExportProperties::ExportProperties (const \fBExportProperties\fP & other)"
Copy constructor\&.
.PP
This copies the configuration properties of another \fBExportProperties\fP\&. 
.PP
\fBSee also\fP
.RS 4
\fBExportProperties(const ExportProperties& other)\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool Assimp::ExportProperties::GetPropertyBool (const char * szName, bool bErrorReturn = \fRfalse\fP) const\fR [inline]\fP"
Get a boolean configuration property\&. Boolean properties are stored on the integer stack internally so it's possible to set them via \fBSetPropertyBool\fP and query them with \fBGetPropertyBool\fP and vice versa\&. 
.PP
\fBSee also\fP
.RS 4
\fBGetPropertyInteger()\fP 
.RE
.PP

.SS "std::function< \fBvoid\fP *(\fBvoid\fP *)> Assimp::ExportProperties::GetPropertyCallback (const char * szName) const"

.SS "\fBai_real\fP Assimp::ExportProperties::GetPropertyFloat (const char * szName, \fBai_real\fP fErrorReturn = \fR10e10f\fP) const"
Get a floating-point configuration property 
.PP
\fBSee also\fP
.RS 4
\fBGetPropertyInteger()\fP 
.RE
.PP

.SS "int Assimp::ExportProperties::GetPropertyInteger (const char * szName, int iErrorReturn = \fR0xffffffff\fP) const"
Get a configuration property\&. 
.PP
\fBParameters\fP
.RS 4
\fIszName\fP Name of the property\&. All supported properties are defined in the aiConfig\&.g header (all constants share the prefix AI_CONFIG_XXX)\&. 
.br
\fIiErrorReturn\fP Value that is returned if the property is not found\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Current value of the property 
.RE
.PP
\fBNote\fP
.RS 4
Property of different types (float, int, string \&.\&.) are kept on different lists, so calling \fBSetPropertyInteger()\fP for a floating-point property has no effect - the loader will call \fBGetPropertyFloat()\fP to read the property, but it won't be there\&. 
.RE
.PP

.SS "const \fBaiMatrix4x4\fP Assimp::ExportProperties::GetPropertyMatrix (const char * szName, const \fBaiMatrix4x4\fP & sErrorReturn = \fR\fBaiMatrix4x4\fP()\fP) const"
Get a matrix configuration property
.PP
The return value remains valid until the property is modified\&. 
.PP
\fBSee also\fP
.RS 4
\fBGetPropertyInteger()\fP 
.RE
.PP

.SS "const std::string Assimp::ExportProperties::GetPropertyString (const char * szName, const std::string & sErrorReturn = \fR''\fP) const"
Get a string configuration property
.PP
The return value remains valid until the property is modified\&. 
.PP
\fBSee also\fP
.RS 4
\fBGetPropertyInteger()\fP 
.RE
.PP

.SS "bool Assimp::ExportProperties::HasPropertyBool (const char * szName) const"
Determine a boolean configuration property has been set\&. 
.PP
\fBSee also\fP
.RS 4
\fBHasPropertyBool()\fP 
.RE
.PP

.SS "bool Assimp::ExportProperties::HasPropertyCallback (const char * szName) const"

.SS "bool Assimp::ExportProperties::HasPropertyFloat (const char * szName) const"
Determine a boolean configuration property has been set\&. 
.PP
\fBSee also\fP
.RS 4
\fBHasPropertyFloat()\fP 
.RE
.PP

.SS "bool Assimp::ExportProperties::HasPropertyInteger (const char * szName) const"
Determine a integer configuration property has been set\&. 
.PP
\fBSee also\fP
.RS 4
\fBHasPropertyInteger()\fP 
.RE
.PP

.SS "bool Assimp::ExportProperties::HasPropertyMatrix (const char * szName) const"
Determine a Matrix configuration property has been set\&. 
.PP
\fBSee also\fP
.RS 4
\fBHasPropertyMatrix()\fP 
.RE
.PP

.SS "bool Assimp::ExportProperties::HasPropertyString (const char * szName) const"
Determine a String configuration property has been set\&. 
.PP
\fBSee also\fP
.RS 4
\fBHasPropertyString()\fP 
.RE
.PP

.SS "bool Assimp::ExportProperties::SetPropertyBool (const char * szName, bool value)\fR [inline]\fP"
Set a boolean configuration property\&. Boolean properties are stored on the integer stack internally so it's possible to set them via \fBSetPropertyBool\fP and query them with \fBGetPropertyBool\fP and vice versa\&. 
.PP
\fBSee also\fP
.RS 4
\fBSetPropertyInteger()\fP 
.RE
.PP

.SS "bool Assimp::ExportProperties::SetPropertyCallback (const char * szName, const std::function< \fBvoid\fP *(\fBvoid\fP *)> & f)"

.SS "bool Assimp::ExportProperties::SetPropertyFloat (const char * szName, \fBai_real\fP fValue)"
Set a floating-point configuration property\&. 
.PP
\fBSee also\fP
.RS 4
\fBSetPropertyInteger()\fP 
.RE
.PP

.SS "bool Assimp::ExportProperties::SetPropertyInteger (const char * szName, int iValue)"
Set an integer configuration property\&. 
.PP
\fBParameters\fP
.RS 4
\fIszName\fP Name of the property\&. All supported properties are defined in the aiConfig\&.g header (all constants share the prefix AI_CONFIG_XXX and are simple strings)\&. 
.br
\fIiValue\fP New value of the property 
.RE
.PP
\fBReturns\fP
.RS 4
true if the property was set before\&. The new value replaces the previous value in this case\&. 
.RE
.PP
\fBNote\fP
.RS 4
Property of different types (float, int, string \&.\&.) are kept on different stacks, so calling \fBSetPropertyInteger()\fP for a floating-point property has no effect - the loader will call \fBGetPropertyFloat()\fP to read the property, but it won't be there\&. 
.RE
.PP

.SS "bool Assimp::ExportProperties::SetPropertyMatrix (const char * szName, const \fBaiMatrix4x4\fP & sValue)"
Set a matrix configuration property\&. 
.PP
\fBSee also\fP
.RS 4
\fBSetPropertyInteger()\fP 
.RE
.PP

.SS "bool Assimp::ExportProperties::SetPropertyString (const char * szName, const std::string & sValue)"
Set a string configuration property\&. 
.PP
\fBSee also\fP
.RS 4
\fBSetPropertyInteger()\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBCallbackPropertyMap\fP Assimp::ExportProperties::mCallbackProperties"

.SS "\fBFloatPropertyMap\fP Assimp::ExportProperties::mFloatProperties"
List of floating-point properties 
.SS "\fBIntPropertyMap\fP Assimp::ExportProperties::mIntProperties"
List of integer properties 
.SS "\fBMatrixPropertyMap\fP Assimp::ExportProperties::mMatrixProperties"
List of Matrix properties 
.SS "\fBStringPropertyMap\fP Assimp::ExportProperties::mStringProperties"
List of string properties 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
