.TH "Assimp::CommentRemover" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::CommentRemover \- Helper class to remove single and multi line comments from a file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RemoveComments\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBvoid\fP \fBRemoveLineComments\fP (const char *szComment, char *szBuffer, char chReplacement=' ')"
.br
.ti -1c
.RI "static \fBvoid\fP \fBRemoveMultiLineComments\fP (const char *szCommentStart, const char *szCommentEnd, char *szBuffer, char chReplacement=' ')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helper class to remove single and multi line comments from a file\&. 

Some mesh formats like MD5 have comments that are quite similar to those in C or C++ so this code has been moved to a separate module\&. 
.SH "Member Function Documentation"
.PP 
.SS "static \fBvoid\fP Assimp::CommentRemover::RemoveLineComments (const char * szComment, char * szBuffer, char chReplacement = \fR' '\fP)\fR [static]\fP"
Remove single-line comments\&. The end of a line is expected to be either NL or CR or NLCR\&. 
.PP
\fBParameters\fP
.RS 4
\fIszComment\fP The start sequence of the comment, e\&.g\&. '//' 
.br
\fIszBuffer\fP Buffer to work with 
.br
\fIchReplacement\fP Character to be used as replacement for commented lines\&. By default this is ' ' 
.RE
.PP

.SS "static \fBvoid\fP Assimp::CommentRemover::RemoveMultiLineComments (const char * szCommentStart, const char * szCommentEnd, char * szBuffer, char chReplacement = \fR' '\fP)\fR [static]\fP"
Remove multi-line comments\&. The end of a line is expected to be either NL or CR or NLCR\&. Multi-line comments may not be nested (as in C)\&. 
.PP
\fBParameters\fP
.RS 4
\fIszCommentStart\fP The start sequence of the comment, e\&.g\&. '/*' 
.br
\fIszCommentEnd\fP The end sequence of the comment, e\&.g\&. '*&zwj;/' 
.br
\fIszBuffer\fP Buffer to work with 
.br
\fIchReplacement\fP Character to be used as replacement for commented lines\&. By default this is ' ' 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
