.TH "Assimp::NodeConverter< TNodeType >" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::NodeConverter< TNodeType > \- Will convert an attribute to its int value\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <XmlParser\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBto_int\fP (TNodeType &node, const char *attribName)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class TNodeType>
.br
struct Assimp::NodeConverter< TNodeType >"Will convert an attribute to its int value\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fITNodeType\fP The node type\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<class TNodeType > static int \fBAssimp::NodeConverter\fP< TNodeType >::to_int (TNodeType & node, const char * attribName)\fR [inline]\fP, \fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
