.TH "Assimp::StreamWriter< SwapEndianess, RuntimeSwitch >" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::StreamWriter< SwapEndianess, RuntimeSwitch >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <StreamWriter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStreamWriter\fP (std::shared_ptr< \fBIOStream\fP > \fBstream\fP, bool le=false)"
.br
.ti -1c
.RI "\fBStreamWriter\fP (\fBIOStream\fP *\fBstream\fP, bool le=false)"
.br
.ti -1c
.RI "\fB~StreamWriter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBFlush\fP ()"
.br
.ti -1c
.RI "\fBaiReturn\fP \fBSeek\fP (size_t pOffset, \fBaiOrigin\fP pOrigin=\fBaiOrigin_SET\fP)"
.br
.ti -1c
.RI "size_t \fBTell\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBPutF4\fP (float \fBf\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPutF8\fP (double d)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPutI2\fP (int16_t n)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPutI1\fP (int8_t n)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPutI4\fP (int32_t n)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPutI8\fP (int64_t n)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPutU2\fP (uint16_t n)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPutU1\fP (uint8_t n)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPutU4\fP (uint32_t n)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPutU8\fP (uint64_t n)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPutChar\fP (char c)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPutString\fP (const \fBaiString\fP &s)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPutString\fP (const std::string &s)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBStreamWriter\fP & \fBoperator<<\fP (\fBT\fP \fBf\fP)"
.br
.ti -1c
.RI "std::size_t \fBGetCurrentPos\fP () const"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCurrentPos\fP (std::size_t new_cursor)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBvoid\fP \fBPut\fP (\fBT\fP \fBf\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false>
.br
class Assimp::StreamWriter< SwapEndianess, RuntimeSwitch >"Wrapper class around \fBIOStream\fP to allow for consistent writing of binary data in both little and big endian format\&. Don't attempt to instance the template directly\&. Use StreamWriterLE to write to a little-endian stream and StreamWriterBE to write to a BE stream\&. Alternatively, there is StreamWriterAny if the endianness of the output stream is to be determined at runtime\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::StreamWriter (std::shared_ptr< \fBIOStream\fP > stream, bool le = \fRfalse\fP)\fR [inline]\fP"
Construction from a given stream with a well-defined endianness\&.
.PP
The \fBStreamReader\fP holds a permanent strong reference to the stream, which is released upon destruction\&. 
.PP
\fBParameters\fP
.RS 4
\fIstream\fP Input stream\&. The stream is not re-seeked and writing continues at the current position of the stream cursor\&. 
.br
\fIle\fP If \fRRuntimeSwitch\fP is true: specifies whether the stream is in little endian byte order\&. Otherwise the endianness information is defined by the \fRSwapEndianess\fP template parameter and this parameter is meaningless\&. 
.br
 
.RE
.PP

.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::StreamWriter (\fBIOStream\fP * stream, bool le = \fRfalse\fP)\fR [inline]\fP"

.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::~\fBStreamWriter\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBvoid\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::Flush ()\fR [inline]\fP"
Flush the contents of the internal buffer, and the output \fBIOStream\fP 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> std::size_t \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::GetCurrentPos () const\fR [inline]\fP"

.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> template<typename \fBT\fP > \fBStreamWriter\fP & \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::operator<< (\fBT\fP f)\fR [inline]\fP"
overload operator<< and allow chaining of MM ops\&. 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> template<typename \fBT\fP > \fBvoid\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::Put (\fBT\fP f)\fR [inline]\fP"
Generic write method\&. ByteSwap::Swap(T*) \fImust\fP be defined 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBvoid\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::PutChar (char c)\fR [inline]\fP"
Write a single character to the stream 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBvoid\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::PutF4 (float f)\fR [inline]\fP"
Write a float to the stream 
.br
 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBvoid\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::PutF8 (double d)\fR [inline]\fP"
Write a double to the stream 
.br
 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBvoid\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::PutI1 (int8_t n)\fR [inline]\fP"
Write a signed 8 bit integer to the stream 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBvoid\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::PutI2 (int16_t n)\fR [inline]\fP"
Write a signed 16 bit integer to the stream 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBvoid\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::PutI4 (int32_t n)\fR [inline]\fP"
Write an signed 32 bit integer to the stream 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBvoid\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::PutI8 (int64_t n)\fR [inline]\fP"
Write a signed 64 bit integer to the stream 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBvoid\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::PutString (const \fBaiString\fP & s)\fR [inline]\fP"
Write an \fBaiString\fP to the stream 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBvoid\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::PutString (const std::string & s)\fR [inline]\fP"
Write a std::string to the stream 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBvoid\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::PutU1 (uint8_t n)\fR [inline]\fP"
Write a unsigned 8 bit integer to the stream 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBvoid\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::PutU2 (uint16_t n)\fR [inline]\fP"
Write a unsigned 16 bit integer to the stream 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBvoid\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::PutU4 (uint32_t n)\fR [inline]\fP"
Write an unsigned 32 bit integer to the stream 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBvoid\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::PutU8 (uint64_t n)\fR [inline]\fP"
Write a unsigned 64 bit integer to the stream 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBaiReturn\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::Seek (size_t pOffset, \fBaiOrigin\fP pOrigin = \fR\fBaiOrigin_SET\fP\fP)\fR [inline]\fP"
Seek to the given offset / origin in the output \fBIOStream\fP\&.
.PP
Flushes the internal buffer and the output \fBIOStream\fP prior to seeking\&. 
.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> \fBvoid\fP \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::SetCurrentPos (std::size_t new_cursor)\fR [inline]\fP"

.SS "template<bool SwapEndianess = false, bool RuntimeSwitch = false> size_t \fBAssimp::StreamWriter\fP< SwapEndianess, RuntimeSwitch >::Tell ()\fR [inline]\fP"
Tell the current position in the output \fBIOStream\fP\&.
.PP
First flushes the internal buffer and the output \fBIOStream\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
