.TH "Assimp::Bitmap::Header" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::Bitmap::Header
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Bitmap\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBtype\fP"
.br
.ti -1c
.RI "uint32_t \fBsize\fP"
.br
.ti -1c
.RI "uint16_t \fBreserved1\fP"
.br
.ti -1c
.RI "uint16_t \fBreserved2\fP"
.br
.ti -1c
.RI "uint32_t \fBoffset\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr std::size_t \fBheader_size\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::size_t Assimp::Bitmap::Header::header_size\fR [static]\fP, \fR [constexpr]\fP"
\fBInitial value:\fP
.nf
=
            sizeof(uint16_t) +
            sizeof(uint32_t) +
            sizeof(uint16_t) +
            sizeof(uint16_t) +
            sizeof(uint32_t)
.PP
.fi

.SS "uint32_t Assimp::Bitmap::Header::offset"

.SS "uint16_t Assimp::Bitmap::Header::reserved1"

.SS "uint16_t Assimp::Bitmap::Header::reserved2"

.SS "uint32_t Assimp::Bitmap::Header::size"

.SS "uint16_t Assimp::Bitmap::Header::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
