.TH "Assimp::find_node_by_name_predicate" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::find_node_by_name_predicate \- Will find a node by its name\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <XmlParser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfind_node_by_name_predicate\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (pugi::xml_node node) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBmName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Will find a node by its name\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Assimp::find_node_by_name_predicate::find_node_by_name_predicate (const std::string & name)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool Assimp::find_node_by_name_predicate::operator() (pugi::xml_node node) const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string Assimp::find_node_by_name_predicate::mName"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
