.TH "Assimp::NodeAttachmentInfo" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::NodeAttachmentInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SceneCombiner\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeAttachmentInfo\fP ()"
.br
.ti -1c
.RI "\fBNodeAttachmentInfo\fP (\fBaiNode\fP *_scene, \fBaiNode\fP *_attachToNode, size_t idx)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaiNode\fP * \fBnode\fP"
.br
.ti -1c
.RI "\fBaiNode\fP * \fBattachToNode\fP"
.br
.ti -1c
.RI "bool \fBresolved\fP"
.br
.ti -1c
.RI "size_t \fBsrc_idx\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Assimp::NodeAttachmentInfo::NodeAttachmentInfo ()\fR [inline]\fP"

.SS "Assimp::NodeAttachmentInfo::NodeAttachmentInfo (\fBaiNode\fP * _scene, \fBaiNode\fP * _attachToNode, size_t idx)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBaiNode\fP* Assimp::NodeAttachmentInfo::attachToNode"

.SS "\fBaiNode\fP* Assimp::NodeAttachmentInfo::node"

.SS "bool Assimp::NodeAttachmentInfo::resolved"

.SS "size_t Assimp::NodeAttachmentInfo::src_idx"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
