.TH "Assimp::LogFunctions< TDeriving >" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::LogFunctions< TDeriving > \- \fBLogger\fP class, which will extend the class by log-functions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <LogAux\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. T> static \fBvoid\fP \fBThrowException\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T> static \fBvoid\fP \fBLogWarn\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T> static \fBvoid\fP \fBLogError\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T> static \fBvoid\fP \fBLogInfo\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T> static \fBvoid\fP \fBLogDebug\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T> static \fBvoid\fP \fBLogVerboseDebug\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class TDeriving>
.br
class Assimp::LogFunctions< TDeriving >"\fBLogger\fP class, which will extend the class by log-functions\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fITDeriving\fP 
.br
 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<class TDeriving > template<typename\&.\&.\&. T> static \fBvoid\fP \fBAssimp::LogFunctions\fP< TDeriving >::LogDebug (\fBT\fP &&\&.\&.\&. args)\fR [inline]\fP, \fR [static]\fP"

.SS "template<class TDeriving > template<typename\&.\&.\&. T> static \fBvoid\fP \fBAssimp::LogFunctions\fP< TDeriving >::LogError (\fBT\fP &&\&.\&.\&. args)\fR [inline]\fP, \fR [static]\fP"

.SS "template<class TDeriving > template<typename\&.\&.\&. T> static \fBvoid\fP \fBAssimp::LogFunctions\fP< TDeriving >::LogInfo (\fBT\fP &&\&.\&.\&. args)\fR [inline]\fP, \fR [static]\fP"

.SS "template<class TDeriving > template<typename\&.\&.\&. T> static \fBvoid\fP \fBAssimp::LogFunctions\fP< TDeriving >::LogVerboseDebug (\fBT\fP &&\&.\&.\&. args)\fR [inline]\fP, \fR [static]\fP"

.SS "template<class TDeriving > template<typename\&.\&.\&. T> static \fBvoid\fP \fBAssimp::LogFunctions\fP< TDeriving >::LogWarn (\fBT\fP &&\&.\&.\&. args)\fR [inline]\fP, \fR [static]\fP"

.SS "template<class TDeriving > template<typename\&.\&.\&. T> static \fBvoid\fP \fBAssimp::LogFunctions\fP< TDeriving >::ThrowException (\fBT\fP &&\&.\&.\&. args)\fR [inline]\fP, \fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
