.TH "Assimp::DefaultLogger" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::DefaultLogger \- CPP-API: Primary logging facility of \fBAssimp\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DefaultLogger\&.hpp>\fP
.PP
Inherits \fBAssimp::Logger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBattachStream\fP (\fBLogStream\fP *pStream, unsigned int severity) override"
.br
.RI "Attach a new log-stream\&.    "
.ti -1c
.RI "bool \fBdetachStream\fP (\fBLogStream\fP *pStream, unsigned int severity) override"
.br
.RI "Detach a still attached stream from the logger (or modify the filter flags bits)    "
.in -1c

Public Member Functions inherited from \fBAssimp::Logger\fP
.in +1c
.ti -1c
.RI "virtual \fB~Logger\fP ()"
.br
.RI "Virtual destructor\&. "
.ti -1c
.RI "\fBvoid\fP \fBdebug\fP (const char *message)"
.br
.RI "Writes a debug message\&. "
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBvoid\fP \fBdebug\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBvoid\fP \fBverboseDebug\fP (const char *message)"
.br
.RI "Writes a debug message\&. "
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBvoid\fP \fBverboseDebug\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBvoid\fP \fBinfo\fP (const char *message)"
.br
.RI "Writes a info message\&. "
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBvoid\fP \fBinfo\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBvoid\fP \fBwarn\fP (const char *message)"
.br
.RI "Writes a warning message\&. "
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBvoid\fP \fBwarn\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBvoid\fP \fBerror\fP (const char *message)"
.br
.RI "Writes an error message\&. "
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBvoid\fP \fBerror\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetLogSeverity\fP (\fBLogSeverity\fP log_severity)"
.br
.RI "Set a new log severity\&. "
.ti -1c
.RI "\fBLogSeverity\fP \fBgetLogSeverity\fP () const"
.br
.RI "Get the current log severity\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLogger\fP * \fBcreate\fP (const char *\fBname\fP=\fBASSIMP_DEFAULT_LOG_NAME\fP, \fBLogSeverity\fP severity=\fBNORMAL\fP, unsigned int defStreams=\fBaiDefaultLogStream_DEBUGGER\fP|\fBaiDefaultLogStream_FILE\fP, \fBIOSystem\fP *io=nullptr)"
.br
.RI "Creates a logging instance\&. "
.ti -1c
.RI "static \fBvoid\fP \fBset\fP (\fBLogger\fP *logger)"
.br
.RI "Setup a custom \fBLogger\fP implementation\&. "
.ti -1c
.RI "static \fBLogger\fP * \fBget\fP ()"
.br
.RI "Getter for singleton instance\&. "
.ti -1c
.RI "static bool \fBisNullLogger\fP ()"
.br
.RI "Return whether a #NullLogger is currently active\&. "
.ti -1c
.RI "static \fBvoid\fP \fBkill\fP ()"
.br
.RI "Kills the current singleton logger and replaces it with a #NullLogger instance\&. "
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBAssimp::Logger\fP
.in +1c
.ti -1c
.RI "enum \fBLogSeverity\fP { \fBNORMAL\fP, \fBDEBUGGING\fP, \fBVERBOSE\fP }"
.br
.RI "Log severity to describe the granularity of logging\&. "
.ti -1c
.RI "enum \fBErrorSeverity\fP { \fBDebugging\fP = 1, \fBInfo\fP = 2, \fBWarn\fP = 4, \fBErr\fP = 8 }"
.br
.RI "Description for severity of a log message\&. "
.in -1c

Protected Member Functions inherited from \fBAssimp::Logger\fP
.in +1c
.ti -1c
.RI "\fBLogger\fP () \fBAI_NO_EXCEPT\fP"
.br
.ti -1c
.RI "\fBLogger\fP (\fBLogSeverity\fP severity)"
.br
.ti -1c
.RI "std::string \fBformatMessage\fP (\fBAssimp::Formatter::format\fP \fBf\fP)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T, typename \fBU\fP > std::string \fBformatMessage\fP (\fBAssimp::Formatter::format\fP \fBf\fP, \fBU\fP &&u, \fBT\fP &&\&.\&.\&. args)"
.br
.in -1c

Protected Attributes inherited from \fBAssimp::Logger\fP
.in +1c
.ti -1c
.RI "\fBLogSeverity\fP \fBm_Severity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CPP-API: Primary logging facility of \fBAssimp\fP\&. 

The library stores its primary \fBLogger\fP as a static member of this class\&. \fBget()\fP returns this primary logger\&. By default the underlying implementation is just a #NullLogger which rejects all log messages\&. By calling \fBcreate()\fP, logging is turned on\&. To capture the log output multiple log streams (#LogStream) can be attach to the logger\&. Some default streams for common streaming locations (such as a file, std::cout, OutputDebugString()) are also provided\&.
.PP
If you wish to customize the logging at an even deeper level supply your own implementation of \fBLogger\fP to \fBset()\fP\&. 
.PP
\fBNote\fP
.RS 4
The whole logging stuff causes a small extra overhead for all imports\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool Assimp::DefaultLogger::attachStream (\fBLogStream\fP * pStream, unsigned int severity)\fR [override]\fP, \fR [virtual]\fP"

.PP
Attach a new log-stream\&.    The logger takes ownership of the stream and is responsible for its destruction (which is done using delete when the logger itself is destroyed)\&. Call detachStream to detach a stream and to gain ownership of it again\&. 
.PP
\fBParameters\fP
.RS 4
\fIpStream\fP Log-stream to attach 
.br
\fIseverity\fP Message filter, specified which types of log messages are dispatched to the stream\&. Provide a bitwise combination of the ErrorSeverity flags\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true if the stream has been attached, false otherwise\&.    
.br
 
.RE
.PP

.PP
Implements \fBAssimp::Logger\fP\&.
.SS "static \fBLogger\fP * Assimp::DefaultLogger::create (const char * name = \fR\fBASSIMP_DEFAULT_LOG_NAME\fP\fP, \fBLogSeverity\fP severity = \fR\fBNORMAL\fP\fP, unsigned int defStreams = \fR\fBaiDefaultLogStream_DEBUGGER\fP|\fBaiDefaultLogStream_FILE\fP\fP, \fBIOSystem\fP * io = \fRnullptr\fP)\fR [static]\fP"

.PP
Creates a logging instance\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP Name for log file\&. Only valid in combination with the aiDefaultLogStream_FILE flag\&. 
.br
\fIseverity\fP Log severity, DEBUG turns on debug messages and VERBOSE turns on all messages\&. 
.br
\fIdefStreams\fP Default log streams to be attached\&. Any bitwise combination of the aiDefaultLogStream enumerated values\&. If \fBaiDefaultLogStream_FILE\fP is specified but an empty string is passed for 'name', no log file is created at all\&. 
.br
\fIio\fP \fBIOSystem\fP to be used to open external files (such as the log file)\&. Pass nullptr to rely on the default implementation\&. This replaces the default #NullLogger with a DefaultLogger instance\&. 
.RE
.PP

.SS "bool Assimp::DefaultLogger::detachStream (\fBLogStream\fP * pStream, unsigned int severity)\fR [override]\fP, \fR [virtual]\fP"

.PP
Detach a still attached stream from the logger (or modify the filter flags bits)    
.PP
\fBParameters\fP
.RS 4
\fIpStream\fP Log-stream instance for detaching 
.br
\fIseverity\fP Provide a bitwise combination of the ErrorSeverity flags\&. This value is &~ed with the current flags of the stream, if the result is 0 the stream is detached from the \fBLogger\fP and the caller retakes the possession of the stream\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true if the stream has been detached, false otherwise\&.    
.RE
.PP

.PP
Implements \fBAssimp::Logger\fP\&.
.SS "static \fBLogger\fP * Assimp::DefaultLogger::get ()\fR [static]\fP"

.PP
Getter for singleton instance\&. 
.PP
\fBReturns\fP
.RS 4
Only instance\&. This is never null, but it could be a \fBNullLogger\fP\&. Use isNullLogger to check this\&. 
.RE
.PP

.SS "static bool Assimp::DefaultLogger::isNullLogger ()\fR [static]\fP"

.PP
Return whether a #NullLogger is currently active\&. 
.PP
\fBReturns\fP
.RS 4
true if the current logger is a #NullLogger\&. Use \fBcreate()\fP or \fBset()\fP to setup a logger that does actually do something else than just rejecting all log messages\&. 
.RE
.PP

.SS "static \fBvoid\fP Assimp::DefaultLogger::kill ()\fR [static]\fP"

.PP
Kills the current singleton logger and replaces it with a #NullLogger instance\&. 
.SS "static \fBvoid\fP Assimp::DefaultLogger::set (\fBLogger\fP * logger)\fR [static]\fP"

.PP
Setup a custom \fBLogger\fP implementation\&. Use this if the provided DefaultLogger class doesn't fit into your needs\&. If the provided message formatting is OK for you, it's much easier to use \fBcreate()\fP and to attach your own custom output streams to it\&. 
.PP
\fBParameters\fP
.RS 4
\fIlogger\fP Pass NULL to setup a default \fBNullLogger\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
