.TH "Assimp::Math" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::Math
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename IntegerType > IntegerType \fBgcd\fP (IntegerType \fBa\fP, IntegerType \fBb\fP)"
.br
.RI "Will return the greatest common divisor\&. "
.ti -1c
.RI "template<typename IntegerType > IntegerType \fBlcm\fP (IntegerType \fBa\fP, IntegerType \fBb\fP)"
.br
.RI "Will return the greatest common divisor\&. "
.ti -1c
.RI "template<class \fBT\fP > \fBT\fP \fBgetEpsilon\fP ()"
.br
.RI "Will return the smallest epsilon-value for the requested type\&. "
.ti -1c
.RI "template<class \fBT\fP > \fBT\fP \fBaiPi\fP ()"
.br
.RI "Will return the constant PI for the requested type\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<class \fBT\fP > \fBT\fP Assimp::Math::aiPi ()\fR [inline]\fP"

.PP
Will return the constant PI for the requested type\&. 
.PP
\fBReturns\fP
.RS 4
Pi 
.RE
.PP

.SS "template<typename IntegerType > IntegerType Assimp::Math::gcd (IntegerType a, IntegerType b)\fR [inline]\fP"

.PP
Will return the greatest common divisor\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP [in] Value a\&. 
.br
\fIb\fP [in] Value b\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The greatest common divisor\&. 
.RE
.PP

.SS "template<class \fBT\fP > \fBT\fP Assimp::Math::getEpsilon ()\fR [inline]\fP"

.PP
Will return the smallest epsilon-value for the requested type\&. 
.PP
\fBReturns\fP
.RS 4
The numercical limit epsilon depending on its type\&. 
.RE
.PP

.SS "template<typename IntegerType > IntegerType Assimp::Math::lcm (IntegerType a, IntegerType b)\fR [inline]\fP"

.PP
Will return the greatest common divisor\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP [in] Value a\&. 
.br
\fIb\fP [in] Value b\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The greatest common divisor\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
