.TH "Assimp::StandardShapes" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::StandardShapes \- Helper class to generate vertex buffers for standard geometric shapes, such as cylinders, cones, boxes, spheres, elipsoids \&.\&.\&. \&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <StandardShapes\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBaiMesh\fP * \fBMakeMesh\fP (const std::vector< \fBaiVector3D\fP > &positions, unsigned int numIndices)"
.br
.ti -1c
.RI "static \fBaiMesh\fP * \fBMakeMesh\fP (unsigned int(*GenerateFunc)(std::vector< \fBaiVector3D\fP > &))"
.br
.ti -1c
.RI "static \fBaiMesh\fP * \fBMakeMesh\fP (unsigned int(*GenerateFunc)(std::vector< \fBaiVector3D\fP > &, bool))"
.br
.ti -1c
.RI "static \fBaiMesh\fP * \fBMakeMesh\fP (unsigned int n, \fBvoid\fP(*GenerateFunc)(unsigned int, std::vector< \fBaiVector3D\fP > &))"
.br
.ti -1c
.RI "static unsigned int \fBMakeHexahedron\fP (std::vector< \fBaiVector3D\fP > &positions, bool polygons=false)"
.br
.RI "Generates a hexahedron (cube) "
.ti -1c
.RI "static unsigned int \fBMakeIcosahedron\fP (std::vector< \fBaiVector3D\fP > &positions)"
.br
.RI "Generates an icosahedron\&. "
.ti -1c
.RI "static unsigned int \fBMakeDodecahedron\fP (std::vector< \fBaiVector3D\fP > &positions, bool polygons=false)"
.br
.RI "Generates a dodecahedron\&. "
.ti -1c
.RI "static unsigned int \fBMakeOctahedron\fP (std::vector< \fBaiVector3D\fP > &positions)"
.br
.RI "Generates an octahedron\&. "
.ti -1c
.RI "static unsigned int \fBMakeTetrahedron\fP (std::vector< \fBaiVector3D\fP > &positions)"
.br
.RI "Generates a tetrahedron\&. "
.ti -1c
.RI "static \fBvoid\fP \fBMakeSphere\fP (unsigned int tess, std::vector< \fBaiVector3D\fP > &positions)"
.br
.RI "Generates a sphere\&. "
.ti -1c
.RI "static \fBvoid\fP \fBMakeCone\fP (\fBai_real\fP \fBheight\fP, \fBai_real\fP radius1, \fBai_real\fP radius2, unsigned int tess, std::vector< \fBaiVector3D\fP > &positions, bool bOpen=false)"
.br
.RI "Generates a cone or a cylinder, either open or closed\&. "
.ti -1c
.RI "static \fBvoid\fP \fBMakeCircle\fP (\fBai_real\fP radius, unsigned int tess, std::vector< \fBaiVector3D\fP > &positions)"
.br
.RI "Generates a flat circle\&. "
.in -1c
.SH "Detailed Description"
.PP 
Helper class to generate vertex buffers for standard geometric shapes, such as cylinders, cones, boxes, spheres, elipsoids \&.\&.\&. \&. 
.SH "Member Function Documentation"
.PP 
.SS "static \fBvoid\fP Assimp::StandardShapes::MakeCircle (\fBai_real\fP radius, unsigned int tess, std::vector< \fBaiVector3D\fP > & positions)\fR [static]\fP"

.PP
Generates a flat circle\&. The circle is constructed in the planned formed by the x,z axes of the cartesian coordinate system\&.
.PP
\fBParameters\fP
.RS 4
\fIradius\fP Radius of the circle 
.br
\fItess\fP Number of segments\&. 
.br
\fIpositions\fP Receives output triangles\&. 
.RE
.PP

.SS "static \fBvoid\fP Assimp::StandardShapes::MakeCone (\fBai_real\fP height, \fBai_real\fP radius1, \fBai_real\fP radius2, unsigned int tess, std::vector< \fBaiVector3D\fP > & positions, bool bOpen = \fRfalse\fP)\fR [static]\fP"

.PP
Generates a cone or a cylinder, either open or closed\&. 
.PP
.nf
    |\-\-\-\-\-|       <\- radius 1

     __x__        <\- ]               ^
    /     \\          | height        |
   /       \\         |               Y
  /         \\        |
 /           \\       |
/______x______\\   <\- ] <\- end cap

|\-\-\-\-\-\-\-\-\-\-\-\-\-|   <\- radius 2

.fi
.PP
.PP
\fBParameters\fP
.RS 4
\fIheight\fP Height of the cone 
.br
\fIradius1\fP First radius 
.br
\fIradius2\fP Second radius 
.br
\fItess\fP Number of triangles\&. 
.br
\fIbOpened\fP true for an open cone/cylinder\&. An open shape has no 'end caps' 
.br
\fIpositions\fP Receives output triangles 
.RE
.PP

.SS "static unsigned int Assimp::StandardShapes::MakeDodecahedron (std::vector< \fBaiVector3D\fP > & positions, bool polygons = \fRfalse\fP)\fR [static]\fP"

.PP
Generates a dodecahedron\&. 
.PP
\fBParameters\fP
.RS 4
\fIpositions\fP Receives output triangles 
.br
\fIpolygons\fP If you pass true here pentagons will be returned 
.RE
.PP
\fBReturns\fP
.RS 4
Number of vertices per face 
.RE
.PP

.SS "static unsigned int Assimp::StandardShapes::MakeHexahedron (std::vector< \fBaiVector3D\fP > & positions, bool polygons = \fRfalse\fP)\fR [static]\fP"

.PP
Generates a hexahedron (cube) Hexahedrons can be scaled on all axes\&. 
.PP
\fBParameters\fP
.RS 4
\fIpositions\fP Receives output triangles\&. 
.br
\fIpolygons\fP If you pass true here quads will be returned 
.RE
.PP
\fBReturns\fP
.RS 4
Number of vertices per face 
.RE
.PP

.SS "static unsigned int Assimp::StandardShapes::MakeIcosahedron (std::vector< \fBaiVector3D\fP > & positions)\fR [static]\fP"

.PP
Generates an icosahedron\&. 
.PP
\fBParameters\fP
.RS 4
\fIpositions\fP Receives output triangles\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Number of vertices per face 
.RE
.PP

.SS "static \fBaiMesh\fP * Assimp::StandardShapes::MakeMesh (const std::vector< \fBaiVector3D\fP > & positions, unsigned int numIndices)\fR [static]\fP"
Generates a mesh from an array of vertex positions\&.
.PP
\fBParameters\fP
.RS 4
\fIpositions\fP List of vertex positions 
.br
\fInumIndices\fP Number of indices per primitive 
.RE
.PP
\fBReturns\fP
.RS 4
Output mesh 
.RE
.PP

.SS "static \fBaiMesh\fP * Assimp::StandardShapes::MakeMesh (unsigned int n, \fBvoid\fP(* GenerateFunc )(unsigned int, std::vector< \fBaiVector3D\fP > &))\fR [static]\fP"

.SS "static \fBaiMesh\fP * Assimp::StandardShapes::MakeMesh (unsigned int(* GenerateFunc )(std::vector< \fBaiVector3D\fP > &))\fR [static]\fP"

.SS "static \fBaiMesh\fP * Assimp::StandardShapes::MakeMesh (unsigned int(* GenerateFunc )(std::vector< \fBaiVector3D\fP > &, bool))\fR [static]\fP"

.SS "static unsigned int Assimp::StandardShapes::MakeOctahedron (std::vector< \fBaiVector3D\fP > & positions)\fR [static]\fP"

.PP
Generates an octahedron\&. 
.PP
\fBParameters\fP
.RS 4
\fIpositions\fP Receives output triangles\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Number of vertices per face 
.RE
.PP

.SS "static \fBvoid\fP Assimp::StandardShapes::MakeSphere (unsigned int tess, std::vector< \fBaiVector3D\fP > & positions)\fR [static]\fP"

.PP
Generates a sphere\&. 
.PP
\fBParameters\fP
.RS 4
\fItess\fP Number of subdivions - 0 generates a octahedron 
.br
\fIpositions\fP Receives output triangles\&. 
.RE
.PP

.SS "static unsigned int Assimp::StandardShapes::MakeTetrahedron (std::vector< \fBaiVector3D\fP > & positions)\fR [static]\fP"

.PP
Generates a tetrahedron\&. 
.PP
\fBParameters\fP
.RS 4
\fIpositions\fP Receives output triangles\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Number of vertices per face 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
