.TH "Assimp::ProgressHandler" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::ProgressHandler \- CPP-API: Abstract interface for custom progress report receivers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ProgressHandler\&.hpp>\fP
.PP
Inherits Intern::AllocateFromAssimpHeap\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ProgressHandler\fP ()"
.br
.RI "Virtual destructor\&. "
.ti -1c
.RI "virtual bool \fBUpdate\fP (float percentage=\-1\&.\fBf\fP)=0"
.br
.RI "Progress callback\&. "
.ti -1c
.RI "virtual \fBvoid\fP \fBUpdateFileRead\fP (int currentStep, int numberOfSteps)"
.br
.RI "Progress callback for file loading steps\&. "
.ti -1c
.RI "virtual \fBvoid\fP \fBUpdatePostProcess\fP (int currentStep, int numberOfSteps)"
.br
.RI "Progress callback for post-processing steps\&. "
.ti -1c
.RI "virtual \fBvoid\fP \fBUpdateFileWrite\fP (int currentStep, int numberOfSteps)"
.br
.RI "Progress callback for export steps\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBProgressHandler\fP () \fBAI_NO_EXCEPT\fP"
.br
.RI "Default constructor\&. "
.in -1c
.SH "Detailed Description"
.PP 
CPP-API: Abstract interface for custom progress report receivers\&. 

Each #Importer instance maintains its own \fBProgressHandler\fP\&. The default implementation provided by \fBAssimp\fP doesn't do anything at all\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Assimp::ProgressHandler::ProgressHandler ()\fR [inline]\fP, \fR [protected]\fP"

.PP
Default constructor\&. 
.SS "virtual Assimp::ProgressHandler::~ProgressHandler ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Virtual destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual bool Assimp::ProgressHandler::Update (float percentage = \fR\-1\&.\fBf\fP\fP)\fR [pure virtual]\fP"

.PP
Progress callback\&. 
.PP
\fBParameters\fP
.RS 4
\fIpercentage\fP An estimate of the current loading progress, in percent\&. Or -1\&.f if such an estimate is not available\&.
.RE
.PP
There are restriction on what you may do from within your implementation of this method: no exceptions may be thrown and no non-const #Importer methods may be called\&. It is not generally possible to predict the number of callbacks fired during a single import\&.
.PP
\fBReturns\fP
.RS 4
Return false to abort loading at the next possible occasion (loaders and \fBAssimp\fP are generally allowed to perform all needed cleanup tasks prior to returning control to the caller)\&. If the loading is aborted, \fBImporter::ReadFile()\fP returns always nullptr\&. 
.RE
.PP

.SS "virtual \fBvoid\fP Assimp::ProgressHandler::UpdateFileRead (int currentStep, int numberOfSteps)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Progress callback for file loading steps\&. 
.PP
\fBParameters\fP
.RS 4
\fInumberOfSteps\fP The number of total post-processing steps 
.br
\fIcurrentStep\fP The index of the current post-processing step that will run, or equal to numberOfSteps if all of them has finished\&. This number is always strictly monotone increasing, although not necessarily linearly\&.
.RE
.PP
\fBNote\fP
.RS 4
This is currently only used at the start and the end of the file parsing\&. 
.RE
.PP

.SS "virtual \fBvoid\fP Assimp::ProgressHandler::UpdateFileWrite (int currentStep, int numberOfSteps)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Progress callback for export steps\&. 
.PP
\fBParameters\fP
.RS 4
\fInumberOfSteps\fP The number of total processing steps 
.br
\fIcurrentStep\fP The index of the current post-processing step that will run, or equal to numberOfSteps if all of them has finished\&. This number is always strictly monotone increasing, although not necessarily linearly\&. 
.RE
.PP

.SS "virtual \fBvoid\fP Assimp::ProgressHandler::UpdatePostProcess (int currentStep, int numberOfSteps)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Progress callback for post-processing steps\&. 
.PP
\fBParameters\fP
.RS 4
\fInumberOfSteps\fP The number of total post-processing steps 
.br
\fIcurrentStep\fP The index of the current post-processing step that will run, or equal to numberOfSteps if all of them has finished\&. This number is always strictly monotone increasing, although not necessarily linearly\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
