.TH "Assimp::AttachmentInfo" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::AttachmentInfo \- Helper data structure for \fBSceneCombiner\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SceneCombiner\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAttachmentInfo\fP ()"
.br
.ti -1c
.RI "\fBAttachmentInfo\fP (\fBaiScene\fP *_scene, \fBaiNode\fP *_attachToNode)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaiScene\fP * \fBscene\fP"
.br
.ti -1c
.RI "\fBaiNode\fP * \fBattachToNode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helper data structure for \fBSceneCombiner\fP\&. 

Describes to which node a scene must be attached to\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Assimp::AttachmentInfo::AttachmentInfo ()\fR [inline]\fP"

.SS "Assimp::AttachmentInfo::AttachmentInfo (\fBaiScene\fP * _scene, \fBaiNode\fP * _attachToNode)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBaiNode\fP* Assimp::AttachmentInfo::attachToNode"

.SS "\fBaiScene\fP* Assimp::AttachmentInfo::scene"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
