.TH "Assimp::ZipArchiveIOSystem" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assimp::ZipArchiveIOSystem
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ZipArchiveIOSystem\&.h>\fP
.PP
Inherits \fBAssimp::IOSystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZipArchiveIOSystem\fP (\fBIOSystem\fP *pIOHandler, const char *pFilename, const char *pMode='r')"
.br
.RI "Open a Zip using the proffered \fBIOSystem\fP\&. "
.ti -1c
.RI "\fBZipArchiveIOSystem\fP (\fBIOSystem\fP *pIOHandler, const std::string &rFilename, const char *pMode='r')"
.br
.ti -1c
.RI "virtual \fB~ZipArchiveIOSystem\fP ()"
.br
.ti -1c
.RI "bool \fBExists\fP (const char *pFilename) const override"
.br
.RI "Tests for the existence of a file at the given path\&. "
.ti -1c
.RI "char \fBgetOsSeparator\fP () const override"
.br
.RI "Returns the system specific directory separator\&. "
.ti -1c
.RI "\fBIOStream\fP * \fBOpen\fP (const char *pFilename, const char *pMode='rb') override"
.br
.RI "Open a new file with a given path\&. "
.ti -1c
.RI "\fBvoid\fP \fBClose\fP (\fBIOStream\fP *pFile) override"
.br
.RI "Closes the given file and releases all resources associated with it\&. "
.ti -1c
.RI "bool \fBisOpen\fP () const"
.br
.RI "The file was opened and is a ZIP\&. "
.ti -1c
.RI "\fBvoid\fP \fBgetFileList\fP (std::vector< std::string > &rFileList) const"
.br
.ti -1c
.RI "\fBvoid\fP \fBgetFileListExtension\fP (std::vector< std::string > &rFileList, const std::string &extension) const"
.br
.in -1c

Public Member Functions inherited from \fBAssimp::IOSystem\fP
.in +1c
.ti -1c
.RI "\fBIOSystem\fP () \fBAI_NO_EXCEPT\fP"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "virtual \fB~IOSystem\fP ()"
.br
.RI "Virtual destructor\&. "
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP bool \fBExists\fP (const std::string &pFile) const"
.br
.RI "For backward compatibility\&. "
.ti -1c
.RI "\fBIOStream\fP * \fBOpen\fP (const std::string &pFile, const std::string &pMode=std::string('rb'))"
.br
.RI "For backward compatibility\&. "
.ti -1c
.RI "virtual bool \fBComparePaths\fP (const char *\fBone\fP, const char *second) const"
.br
.RI "Compares two paths and check whether the point to identical files\&. "
.ti -1c
.RI "bool \fBComparePaths\fP (const std::string &\fBone\fP, const std::string &second) const"
.br
.RI "For backward compatibility\&. "
.ti -1c
.RI "virtual bool \fBPushDirectory\fP (const std::string &path)"
.br
.RI "Pushes a new directory onto the directory stack\&. "
.ti -1c
.RI "virtual const std::string & \fBCurrentDirectory\fP () const"
.br
.RI "Returns the top directory from the stack\&. "
.ti -1c
.RI "virtual size_t \fBStackSize\fP () const"
.br
.RI "Returns the number of directories stored on the stack\&. "
.ti -1c
.RI "virtual bool \fBPopDirectory\fP ()"
.br
.RI "Pops the top directory from the stack\&. "
.ti -1c
.RI "virtual bool \fBCreateDirectory\fP (const std::string &path)"
.br
.RI "CReates an new directory at the given path\&. "
.ti -1c
.RI "virtual bool \fBChangeDirectory\fP (const std::string &path)"
.br
.RI "Will change the current directory to the given path\&. "
.ti -1c
.RI "virtual bool \fBDeleteFile\fP (const std::string &file)"
.br
.RI "Will delete the given file\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBisZipArchive\fP (\fBIOSystem\fP *pIOHandler, const char *pFilename)"
.br
.ti -1c
.RI "static bool \fBisZipArchive\fP (\fBIOSystem\fP *pIOHandler, const std::string &rFilename)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Assimp::ZipArchiveIOSystem::ZipArchiveIOSystem (\fBIOSystem\fP * pIOHandler, const char * pFilename, const char * pMode = \fR'r'\fP)"

.PP
Open a Zip using the proffered \fBIOSystem\fP\&. 
.SS "Assimp::ZipArchiveIOSystem::ZipArchiveIOSystem (\fBIOSystem\fP * pIOHandler, const std::string & rFilename, const char * pMode = \fR'r'\fP)"

.SS "virtual Assimp::ZipArchiveIOSystem::~ZipArchiveIOSystem ()\fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP Assimp::ZipArchiveIOSystem::Close (\fBIOStream\fP * pFile)\fR [override]\fP, \fR [virtual]\fP"

.PP
Closes the given file and releases all resources associated with it\&. 
.PP
\fBParameters\fP
.RS 4
\fIpFile\fP The file instance previously created by \fBOpen()\fP\&. 
.RE
.PP

.PP
Implements \fBAssimp::IOSystem\fP\&.
.SS "bool Assimp::ZipArchiveIOSystem::Exists (const char * pFile) const\fR [override]\fP, \fR [virtual]\fP"

.PP
Tests for the existence of a file at the given path\&. 
.PP
\fBParameters\fP
.RS 4
\fIpFile\fP Path to the file 
.RE
.PP
\fBReturns\fP
.RS 4
true if there is a file with this path, else false\&. 
.RE
.PP

.PP
Implements \fBAssimp::IOSystem\fP\&.
.SS "\fBvoid\fP Assimp::ZipArchiveIOSystem::getFileList (std::vector< std::string > & rFileList) const"
Get the list of all files with their simplified paths Intended for use within \fBAssimp\fP library boundaries 
.SS "\fBvoid\fP Assimp::ZipArchiveIOSystem::getFileListExtension (std::vector< std::string > & rFileList, const std::string & extension) const"
Get the list of all files with extension (must be lowercase) Intended for use within \fBAssimp\fP library boundaries 
.SS "char Assimp::ZipArchiveIOSystem::getOsSeparator () const\fR [override]\fP, \fR [virtual]\fP"

.PP
Returns the system specific directory separator\&. 
.PP
\fBReturns\fP
.RS 4
System specific directory separator 
.RE
.PP

.PP
Implements \fBAssimp::IOSystem\fP\&.
.SS "bool Assimp::ZipArchiveIOSystem::isOpen () const"

.PP
The file was opened and is a ZIP\&. 
.SS "static bool Assimp::ZipArchiveIOSystem::isZipArchive (\fBIOSystem\fP * pIOHandler, const char * pFilename)\fR [static]\fP"

.SS "static bool Assimp::ZipArchiveIOSystem::isZipArchive (\fBIOSystem\fP * pIOHandler, const std::string & rFilename)\fR [static]\fP"

.SS "\fBIOStream\fP * Assimp::ZipArchiveIOSystem::Open (const char * pFile, const char * pMode = \fR'rb'\fP)\fR [override]\fP, \fR [virtual]\fP"

.PP
Open a new file with a given path\&. When the access to the file is finished, call \fBClose()\fP to release all associated resources (or the virtual dtor of the \fBIOStream\fP)\&.
.PP
\fBParameters\fP
.RS 4
\fIpFile\fP Path to the file 
.br
\fIpMode\fP Desired file I/O mode\&. Required are: 'wb', 'w', 'wt', 'rb', 'r', 'rt'\&.
.RE
.PP
\fBReturns\fP
.RS 4
New \fBIOStream\fP interface allowing the lib to access the underlying file\&. 
.RE
.PP
\fBNote\fP
.RS 4
When implementing this class to provide custom IO handling, you probably have to supply an own implementation of \fBIOStream\fP as well\&. 
.RE
.PP

.PP
Implements \fBAssimp::IOSystem\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
