.TH "adhed/glm/gtx/associated_min_max.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/associated_min_max.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./glm\&.hpp'\fP
.br
\fR#include 'associated_min_max\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP \fBglm::associatedMin\fP (\fBT\fP \fBx\fP, \fBU\fP \fBa\fP, \fBT\fP \fBy\fP, \fBU\fP \fBb\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMin\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMin\fP (\fBT\fP \fBx\fP, const \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > &\fBa\fP, \fBT\fP \fBy\fP, const \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > &\fBb\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMin\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBU\fP \fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBU\fP \fBb\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP \fBglm::associatedMin\fP (\fBT\fP \fBx\fP, \fBU\fP \fBa\fP, \fBT\fP \fBy\fP, \fBU\fP \fBb\fP, \fBT\fP \fBz\fP, \fBU\fP c)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMin\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBz\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &c)"
.br
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP \fBglm::associatedMin\fP (\fBT\fP \fBx\fP, \fBU\fP \fBa\fP, \fBT\fP \fBy\fP, \fBU\fP \fBb\fP, \fBT\fP \fBz\fP, \fBU\fP c, \fBT\fP \fBw\fP, \fBU\fP d)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMin\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBz\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &c, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBw\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &d)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMin\fP (\fBT\fP \fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBT\fP \fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP, \fBT\fP \fBz\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &c, \fBT\fP \fBw\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &d)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMin\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBU\fP \fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBU\fP \fBb\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBz\fP, \fBU\fP c, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBw\fP, \fBU\fP d)"
.br
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP \fBglm::associatedMax\fP (\fBT\fP \fBx\fP, \fBU\fP \fBa\fP, \fBT\fP \fBy\fP, \fBU\fP \fBb\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBT\fP \fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBT\fP \fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBU\fP \fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBU\fP \fBb\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP \fBglm::associatedMax\fP (\fBT\fP \fBx\fP, \fBU\fP \fBa\fP, \fBT\fP \fBy\fP, \fBU\fP \fBb\fP, \fBT\fP \fBz\fP, \fBU\fP c)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBz\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &c)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBT\fP \fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBT\fP \fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP, \fBT\fP \fBz\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &c)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBU\fP \fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBU\fP \fBb\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBz\fP, \fBU\fP c)"
.br
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP \fBglm::associatedMax\fP (\fBT\fP \fBx\fP, \fBU\fP \fBa\fP, \fBT\fP \fBy\fP, \fBU\fP \fBb\fP, \fBT\fP \fBz\fP, \fBU\fP c, \fBT\fP \fBw\fP, \fBU\fP d)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBz\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &c, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBw\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &d)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBT\fP \fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBT\fP \fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP, \fBT\fP \fBz\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &c, \fBT\fP \fBw\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &d)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBU\fP \fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBU\fP \fBb\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBz\fP, \fBU\fP c, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBw\fP, \fBU\fP d)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_associated_min_max\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
gtx_extented_min_max (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
