.TH "adhed/glm/gtc/bitfield.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtc/bitfield.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./detail/setup\&.hpp'\fP
.br
\fR#include '\&.\&./ext/scalar_int_sized\&.hpp'\fP
.br
\fR#include '\&.\&./ext/scalar_uint_sized\&.hpp'\fP
.br
\fR#include '\&.\&./detail/qualifier\&.hpp'\fP
.br
\fR#include '\&.\&./detail/_vectorize\&.hpp'\fP
.br
\fR#include 'type_precision\&.hpp'\fP
.br
\fR#include <limits>\fP
.br
\fR#include 'bitfield\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType \fBglm::mask\fP (genIUType Bits)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::mask\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType \fBglm::bitfieldRotateRight\fP (genIUType In, int Shift)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::bitfieldRotateRight\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &In, int Shift)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType \fBglm::bitfieldRotateLeft\fP (genIUType In, int Shift)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::bitfieldRotateLeft\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &In, int Shift)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType \fBglm::bitfieldFillOne\fP (genIUType \fBValue\fP, int FirstBit, int BitCount)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::bitfieldFillOne\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBValue\fP, int FirstBit, int BitCount)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType \fBglm::bitfieldFillZero\fP (genIUType \fBValue\fP, int FirstBit, int BitCount)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::bitfieldFillZero\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBValue\fP, int FirstBit, int BitCount)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBint16\fP \fBglm::bitfieldInterleave\fP (\fBint8\fP \fBx\fP, \fBint8\fP \fBy\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBuint16\fP \fBglm::bitfieldInterleave\fP (\fBuint8\fP \fBx\fP, \fBuint8\fP \fBy\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBuint16\fP \fBglm::bitfieldInterleave\fP (\fBu8vec2\fP const &\fBv\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBglm::u8vec2\fP \fBglm::bitfieldDeinterleave\fP (\fBglm::uint16\fP \fBx\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBint32\fP \fBglm::bitfieldInterleave\fP (\fBint16\fP \fBx\fP, \fBint16\fP \fBy\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBuint32\fP \fBglm::bitfieldInterleave\fP (\fBuint16\fP \fBx\fP, \fBuint16\fP \fBy\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBuint32\fP \fBglm::bitfieldInterleave\fP (\fBu16vec2\fP const &\fBv\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBglm::u16vec2\fP \fBglm::bitfieldDeinterleave\fP (\fBglm::uint32\fP \fBx\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBint64\fP \fBglm::bitfieldInterleave\fP (\fBint32\fP \fBx\fP, \fBint32\fP \fBy\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBuint64\fP \fBglm::bitfieldInterleave\fP (\fBuint32\fP \fBx\fP, \fBuint32\fP \fBy\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBuint64\fP \fBglm::bitfieldInterleave\fP (\fBu32vec2\fP const &\fBv\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBglm::u32vec2\fP \fBglm::bitfieldDeinterleave\fP (\fBglm::uint64\fP \fBx\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBint32\fP \fBglm::bitfieldInterleave\fP (\fBint8\fP \fBx\fP, \fBint8\fP \fBy\fP, \fBint8\fP \fBz\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBuint32\fP \fBglm::bitfieldInterleave\fP (\fBuint8\fP \fBx\fP, \fBuint8\fP \fBy\fP, \fBuint8\fP \fBz\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBint64\fP \fBglm::bitfieldInterleave\fP (\fBint16\fP \fBx\fP, \fBint16\fP \fBy\fP, \fBint16\fP \fBz\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBuint64\fP \fBglm::bitfieldInterleave\fP (\fBuint16\fP \fBx\fP, \fBuint16\fP \fBy\fP, \fBuint16\fP \fBz\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBint64\fP \fBglm::bitfieldInterleave\fP (\fBint32\fP \fBx\fP, \fBint32\fP \fBy\fP, \fBint32\fP \fBz\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBuint64\fP \fBglm::bitfieldInterleave\fP (\fBuint32\fP \fBx\fP, \fBuint32\fP \fBy\fP, \fBuint32\fP \fBz\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBint32\fP \fBglm::bitfieldInterleave\fP (\fBint8\fP \fBx\fP, \fBint8\fP \fBy\fP, \fBint8\fP \fBz\fP, \fBint8\fP \fBw\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBuint32\fP \fBglm::bitfieldInterleave\fP (\fBuint8\fP \fBx\fP, \fBuint8\fP \fBy\fP, \fBuint8\fP \fBz\fP, \fBuint8\fP \fBw\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBint64\fP \fBglm::bitfieldInterleave\fP (\fBint16\fP \fBx\fP, \fBint16\fP \fBy\fP, \fBint16\fP \fBz\fP, \fBint16\fP \fBw\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBuint64\fP \fBglm::bitfieldInterleave\fP (\fBuint16\fP \fBx\fP, \fBuint16\fP \fBy\fP, \fBuint16\fP \fBz\fP, \fBuint16\fP \fBw\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTC_bitfield\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTC_bitfield\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
