.TH "blink::application" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blink::application
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <blink\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBapplication\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBrun\fP (\fBvoid\fP *const blink_handle, const wchar_t *\fBblink_environment\fP=nullptr, const wchar_t *\fBblink_working_directory\fP=nullptr, bool \fBcompile_source\fP=true)"
.br
.ti -1c
.RI "bool \fBlink\fP (const std::filesystem::path &object_file)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBT\fP \fBread_symbol\fP (const std::string &\fBname\fP) const"
.br
.ti -1c
.RI "template<typename \fBT\fP  = void, typename\&.\&.\&. Args> \fBT\fP \fBcall_symbol\fP (const std::string &\fBname\fP, Args\&.\&.\&. args) const"
.br
.ti -1c
.RI "template<typename SYMBOL_TYPE , typename HEADER_TYPE > bool \fBlink\fP (HANDLE file, const HEADER_TYPE &header)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "blink::application::application ()"

.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBT\fP  = void, typename\&.\&.\&. Args> \fBT\fP blink::application::call_symbol (const std::string & name, Args\&.\&.\&. args) const\fR [inline]\fP"

.SS "bool blink::application::link (const std::filesystem::path & object_file)"

.SS "template<typename SYMBOL_TYPE , typename HEADER_TYPE > bool blink::application::link (HANDLE file, const HEADER_TYPE & header)"

.SS "template<typename \fBT\fP > \fBT\fP blink::application::read_symbol (const std::string & name) const\fR [inline]\fP"

.SS "\fBvoid\fP blink::application::run (\fBvoid\fP *const blink_handle, const wchar_t * blink_environment = \fRnullptr\fP, const wchar_t * blink_working_directory = \fRnullptr\fP, bool compile_source = \fRtrue\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
