.TH "blink::path_comp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blink::path_comp
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pdb_reader\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const std::filesystem::path &lhs, const std::filesystem::path &rhs) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool blink::path_comp::operator() (const std::filesystem::path & lhs, const std::filesystem::path & rhs) const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
