.TH "blink::guid" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blink::guid \- A global unique identifier (GUID)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pdb_reader\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBguid\fP &other)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBguid\fP &other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBdata1\fP"
.br
.ti -1c
.RI "uint32_t \fBdata2\fP"
.br
.ti -1c
.RI "uint32_t \fBdata3\fP"
.br
.ti -1c
.RI "uint32_t \fBdata4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A global unique identifier (GUID)\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool blink::guid::operator!= (const \fBguid\fP & other)\fR [inline]\fP"

.SS "bool blink::guid::operator== (const \fBguid\fP & other)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "uint32_t blink::guid::data1"

.SS "uint32_t blink::guid::data2"

.SS "uint32_t blink::guid::data3"

.SS "uint32_t blink::guid::data4"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
