.TH "BLINK/source/blink.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLINK/source/blink.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'blink\&.hpp'\fP
.br
\fR#include 'coff_reader\&.hpp'\fP
.br
\fR#include <algorithm>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
