.TH "blink::msf_reader" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blink::msf_reader \- Class which splits a multi-stream file into its content streams\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <msf_reader\&.hpp>\fP
.PP
Inherited by \fBblink::pdb_reader\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBcontent_stream\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmsf_reader\fP (const std::string &path)"
.br
.RI "Opens a multi-stream file\&. "
.ti -1c
.RI "bool \fBis_valid\fP () const"
.br
.RI "Returns whether this multi-stream file exists and is of a valid format\&. "
.ti -1c
.RI "size_t \fBstream_count\fP () const"
.br
.RI "Returns the number of content streams in this file\&. "
.ti -1c
.RI "std::vector< char > \fBstream\fP (size_t \fBindex\fP)"
.br
.RI "Gets a content stream\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fB_is_valid\fP = false"
.br
.ti -1c
.RI "std::vector< \fBcontent_stream\fP > \fB_streams\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class which splits a multi-stream file into its content streams\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "blink::msf_reader::msf_reader (const std::string & path)\fR [explicit]\fP"

.PP
Opens a multi-stream file\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP The file system path the multi-stream file is located at\&.
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool blink::msf_reader::is_valid () const\fR [inline]\fP"

.PP
Returns whether this multi-stream file exists and is of a valid format\&. 
.SS "std::vector< char > blink::msf_reader::stream (size_t index)"

.PP
Gets a content stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIindex\fP The index the stream is located at\&.
.RE
.PP

.SS "size_t blink::msf_reader::stream_count () const\fR [inline]\fP"

.PP
Returns the number of content streams in this file\&. 
.SH "Member Data Documentation"
.PP 
.SS "bool blink::msf_reader::_is_valid = false\fR [protected]\fP"

.SS "std::vector<\fBcontent_stream\fP> blink::msf_reader::_streams\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
