.TH "blink" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blink
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBapplication\fP"
.br
.ti -1c
.RI "struct \fBguid\fP"
.br
.RI "A global unique identifier (GUID)\&. "
.ti -1c
.RI "class \fBmsf_reader\fP"
.br
.RI "Class which splits a multi-stream file into its content streams\&. "
.ti -1c
.RI "struct \fBpath_comp\fP"
.br
.ti -1c
.RI "struct \fBpath_hash\fP"
.br
.ti -1c
.RI "class \fBpdb_reader\fP"
.br
.RI "Class which reads a program debug database\&. "
.ti -1c
.RI "struct \fBsource_file_indices\fP"
.br
.ti -1c
.RI "class \fBstream_reader\fP"
.br
.RI "Class which provides cached reading access to the content streams of a multi-stream file\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::unordered_map< std::filesystem::path, \fBsource_file_indices\fP, \fBpath_hash\fP, \fBpath_comp\fP > \fBsource_file_map\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBL\fP > \fBvoid\fP \fBparse_code_view_records\fP (\fBstream_reader\fP &\fBstream\fP, size_t \fBlength\fP, \fBL\fP callback, size_t alignment=1)"
.br
.RI "Helper function that parses a CodeView stream and calls a callback function for every record in it\&. "
.in -1c
.SH "Detailed Description"
.PP 
Copyright (C) 2016 Patrick Mours\&. All rights reserved\&. License: https://github.com/crosire/blink#license 
.SH "Typedef Documentation"
.PP 
.SS "typedef std::unordered_map<std::filesystem::path, \fBsource_file_indices\fP, \fBpath_hash\fP, \fBpath_comp\fP> \fBblink::source_file_map\fP"

.SH "Function Documentation"
.PP 
.SS "template<typename \fBL\fP > \fBvoid\fP blink::parse_code_view_records (\fBstream_reader\fP & stream, size_t length, \fBL\fP callback, size_t alignment = \fR1\fP)"

.PP
Helper function that parses a CodeView stream and calls a callback function for every record in it\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
