.TH "Buidling::Slot" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Buidling::Slot
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <D_CONFIGFILE\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBRessource\fP > \fBResource\fP"
.br
.ti -1c
.RI "int \fBamount\fP"
.br
.ti -1c
.RI "\fBSlotType\fP \fBslotType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB109\fP of file \fBD_CONFIGFILE\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Buidling::Slot::amount"

.PP
Definition at line \fB112\fP of file \fBD_CONFIGFILE\&.h\fP\&.
.SS "std::shared_ptr<\fBRessource\fP> Buidling::Slot::Resource"

.PP
Definition at line \fB111\fP of file \fBD_CONFIGFILE\&.h\fP\&.
.SS "\fBSlotType\fP Buidling::Slot::slotType"

.PP
Definition at line \fB113\fP of file \fBD_CONFIGFILE\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
