.TH "UPRISE_ENGINE/HeaderE/CORE/C_BEHAVIOUR.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/HeaderE/CORE/C_BEHAVIOUR.h
.SH SYNOPSIS
.br
.PP
\fR#include 'pch\&.h'\fP
.br
\fR#include <windows\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCORE::Behaviour\fP"
.br
.ti -1c
.RI "class \fBRegister< _T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDATATYPES\fP"
.br
.ti -1c
.RI "namespace \fBCOMPONENTS\fP"
.br
.ti -1c
.RI "namespace \fBCORE\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOPY\fP(x,  Member_Copy)   std::shared_ptr<\fBCORE::Behaviour\fP> Copy() override{auto a = std::make_shared<x>();Member_Copy;std::shared_ptr<\fBCORE::Behaviour\fP> ret=a;return ret;};"
.br
.ti -1c
.RI "#define \fBDEEP_COPY\fP(x,  Member_Copy,  y)   std::shared_ptr<\fBCORE::Behaviour\fP> DeepCopy() override{auto a = std::make_shared<x>();Member_Copy;std::shared_ptr<\fBCORE::Behaviour\fP> ret=a;return ret;};"
.br
.ti -1c
.RI "#define \fBI_WINDOW_E\fP()   void EditorWindow() override{};"
.br
.ti -1c
.RI "#define \fBI_WINDOW\fP(x)   void EditorWindow() override{x};"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COPY( x,  Member_Copy)   std::shared_ptr<\fBCORE::Behaviour\fP> Copy() override{auto a = std::make_shared<x>();Member_Copy;std::shared_ptr<\fBCORE::Behaviour\fP> ret=a;return ret;};"

.PP
Definition at line \fB81\fP of file \fBC_BEHAVIOUR\&.h\fP\&.
.SS "#define DEEP_COPY( x,  Member_Copy,  y)   std::shared_ptr<\fBCORE::Behaviour\fP> DeepCopy() override{auto a = std::make_shared<x>();Member_Copy;std::shared_ptr<\fBCORE::Behaviour\fP> ret=a;return ret;};"

.PP
Definition at line \fB82\fP of file \fBC_BEHAVIOUR\&.h\fP\&.
.SS "#define I_WINDOW( x)   void EditorWindow() override{x};"

.PP
Definition at line \fB84\fP of file \fBC_BEHAVIOUR\&.h\fP\&.
.SS "#define I_WINDOW_E()   void EditorWindow() override{};"

.PP
Definition at line \fB83\fP of file \fBC_BEHAVIOUR\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
