.TH "UPRISE_ENGINE/HeaderE/CORE/C_INPUT.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/HeaderE/CORE/C_INPUT.h
.SH SYNOPSIS
.br
.PP
\fR#include 'GLINCLUDES\&.h'\fP
.br
\fR#include 'HeaderE/DATATYPES/D_TS_P_VECOTR2\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCORE::Input\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCORE\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBA\fP   GLFW_KEY_A"
.br
.ti -1c
.RI "#define \fBB\fP   GLFW_KEY_B"
.br
.ti -1c
.RI "#define \fBC\fP   GLFW_KEY_C"
.br
.ti -1c
.RI "#define \fBD\fP   GLFW_KEY_D"
.br
.ti -1c
.RI "#define \fBE\fP   GLFW_KEY_E"
.br
.ti -1c
.RI "#define \fBF\fP   GLFW_KEY_F"
.br
.ti -1c
.RI "#define \fBG\fP   GLFW_KEY_G"
.br
.ti -1c
.RI "#define \fBH\fP   GLFW_KEY_H"
.br
.ti -1c
.RI "#define \fBI\fP   GLFW_KEY_I"
.br
.ti -1c
.RI "#define \fBJ\fP   GLFW_KEY_J"
.br
.ti -1c
.RI "#define \fBK\fP   GLFW_KEY_K"
.br
.ti -1c
.RI "#define \fBL\fP   GLFW_KEY_L"
.br
.ti -1c
.RI "#define \fBM\fP   GLFW_KEY_M"
.br
.ti -1c
.RI "#define \fBN\fP   GLFW_KEY_N"
.br
.ti -1c
.RI "#define \fBO\fP   GLFW_KEY_O"
.br
.ti -1c
.RI "#define \fBP\fP   GLFW_KEY_P"
.br
.ti -1c
.RI "#define \fBQ\fP   GLFW_KEY_Q"
.br
.ti -1c
.RI "#define \fBR\fP   GLFW_KEY_R"
.br
.ti -1c
.RI "#define \fBS\fP   GLFW_KEY_S"
.br
.ti -1c
.RI "#define \fBT\fP   GLFW_KEY_T"
.br
.ti -1c
.RI "#define \fBU\fP   GLFW_KEY_U"
.br
.ti -1c
.RI "#define \fBV\fP   GLFW_KEY_V"
.br
.ti -1c
.RI "#define \fBW\fP   GLFW_KEY_W"
.br
.ti -1c
.RI "#define \fBX\fP   GLFW_KEY_X"
.br
.ti -1c
.RI "#define \fBY\fP   GLFW_KEY_Y"
.br
.ti -1c
.RI "#define \fBZ\fP   GLFW_KEY_Z"
.br
.ti -1c
.RI "#define \fBone\fP   GLFW_KEY_1"
.br
.ti -1c
.RI "#define \fBtwo\fP   GLFW_KEY_2"
.br
.ti -1c
.RI "#define \fBthree\fP   GLFW_KEY_3"
.br
.ti -1c
.RI "#define \fBfour\fP   GLFW_KEY_4"
.br
.ti -1c
.RI "#define \fBfive\fP   GLFW_KEY_5"
.br
.ti -1c
.RI "#define \fBsix\fP   GLFW_KEY_6"
.br
.ti -1c
.RI "#define \fBseven\fP   GLFW_KEY_7"
.br
.ti -1c
.RI "#define \fBnine\fP   GLFW_KEY_9"
.br
.ti -1c
.RI "#define \fBeight\fP   GLFW_KEY_8"
.br
.ti -1c
.RI "#define \fBzero\fP   GLFW_KEY_0"
.br
.ti -1c
.RI "#define \fBLcrt\fP   GLFW_KEY_LEFT_CONTROL"
.br
.ti -1c
.RI "#define \fBLalt\fP   GLFW_KEY_LEFT_ALT"
.br
.ti -1c
.RI "#define \fBLshift\fP   GLFW_KEY_LEFT_SHIFT"
.br
.ti -1c
.RI "#define \fBSpace\fP   GLFW_KEY_SPACE"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define A   GLFW_KEY_A"

.PP
Definition at line \fB6\fP of file \fBC_INPUT\&.h\fP\&.
.PP
Referenced by \fBprocessInput()\fP, and \fBTest::Update()\fP\&.
.SS "#define B   GLFW_KEY_B"

.PP
Definition at line \fB7\fP of file \fBC_INPUT\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "#define C   GLFW_KEY_C"

.PP
Definition at line \fB8\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define D   GLFW_KEY_D"

.PP
Definition at line \fB9\fP of file \fBC_INPUT\&.h\fP\&.
.PP
Referenced by \fBTest::Update()\fP\&.
.SS "#define E   GLFW_KEY_E"

.PP
Definition at line \fB10\fP of file \fBC_INPUT\&.h\fP\&.
.PP
Referenced by \fBTest::Update()\fP\&.
.SS "#define eight   GLFW_KEY_8"

.PP
Definition at line \fB40\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define F   GLFW_KEY_F"

.PP
Definition at line \fB11\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define five   GLFW_KEY_5"

.PP
Definition at line \fB36\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define four   GLFW_KEY_4"

.PP
Definition at line \fB35\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define G   GLFW_KEY_G"

.PP
Definition at line \fB12\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define H   GLFW_KEY_H"

.PP
Definition at line \fB13\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define I   GLFW_KEY_I"

.PP
Definition at line \fB14\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define J   GLFW_KEY_J"

.PP
Definition at line \fB15\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define K   GLFW_KEY_K"

.PP
Definition at line \fB16\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define L   GLFW_KEY_L"

.PP
Definition at line \fB17\fP of file \fBC_INPUT\&.h\fP\&.
.PP
Referenced by \fBCallCSharpFunction()\fP, and \fBTerrain_Data::LoadHeightmap()\fP\&.
.SS "#define Lalt   GLFW_KEY_LEFT_ALT"

.PP
Definition at line \fB43\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define Lcrt   GLFW_KEY_LEFT_CONTROL"

.PP
Definition at line \fB42\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define Lshift   GLFW_KEY_LEFT_SHIFT"

.PP
Definition at line \fB44\fP of file \fBC_INPUT\&.h\fP\&.
.PP
Referenced by \fBTest::Update()\fP\&.
.SS "#define M   GLFW_KEY_M"

.PP
Definition at line \fB18\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define N   GLFW_KEY_N"

.PP
Definition at line \fB19\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define nine   GLFW_KEY_9"

.PP
Definition at line \fB39\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define O   GLFW_KEY_O"

.PP
Definition at line \fB20\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define one   GLFW_KEY_1"

.PP
Definition at line \fB32\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define P   GLFW_KEY_P"

.PP
Definition at line \fB21\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define Q   GLFW_KEY_Q"

.PP
Definition at line \fB22\fP of file \fBC_INPUT\&.h\fP\&.
.PP
Referenced by \fBTest::Update()\fP\&.
.SS "#define R   GLFW_KEY_R"

.PP
Definition at line \fB23\fP of file \fBC_INPUT\&.h\fP\&.
.PP
Referenced by \fBTest::Update()\fP\&.
.SS "#define S   GLFW_KEY_S"

.PP
Definition at line \fB24\fP of file \fBC_INPUT\&.h\fP\&.
.PP
Referenced by \fBTest::Update()\fP\&.
.SS "#define seven   GLFW_KEY_7"

.PP
Definition at line \fB38\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define six   GLFW_KEY_6"

.PP
Definition at line \fB37\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define Space   GLFW_KEY_SPACE"

.PP
Definition at line \fB45\fP of file \fBC_INPUT\&.h\fP\&.
.PP
Referenced by \fBTest::Update()\fP\&.
.SS "#define T   GLFW_KEY_T"

.PP
Definition at line \fB25\fP of file \fBC_INPUT\&.h\fP\&.
.PP
Referenced by \fBTest::Update()\fP\&.
.SS "#define three   GLFW_KEY_3"

.PP
Definition at line \fB34\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define two   GLFW_KEY_2"

.PP
Definition at line \fB33\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define U   GLFW_KEY_U"

.PP
Definition at line \fB26\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define V   GLFW_KEY_V"

.PP
Definition at line \fB27\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define W   GLFW_KEY_W"

.PP
Definition at line \fB28\fP of file \fBC_INPUT\&.h\fP\&.
.PP
Referenced by \fBTest::Update()\fP\&.
.SS "#define X   GLFW_KEY_X"

.PP
Definition at line \fB29\fP of file \fBC_INPUT\&.h\fP\&.
.PP
Referenced by \fBTeleport::Update()\fP\&.
.SS "#define Y   GLFW_KEY_Y"

.PP
Definition at line \fB30\fP of file \fBC_INPUT\&.h\fP\&.
.PP
Referenced by \fBTeleport::Update()\fP\&.
.SS "#define Z   GLFW_KEY_Z"

.PP
Definition at line \fB31\fP of file \fBC_INPUT\&.h\fP\&.
.SS "#define zero   GLFW_KEY_0"

.PP
Definition at line \fB41\fP of file \fBC_INPUT\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
