.TH "UPRISE_ENGINE/C_SMART_POINTER.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/C_SMART_POINTER.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUTILLS::PTR_base< _Ty >\fP"
.br
.ti -1c
.RI "class \fBUTILLS::REF_block\fP"
.br
.ti -1c
.RI "class \fBUTILLS::Shared_ptr< _Ty >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUTILLS\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_SMART_POINTER_\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class _Ty , class\&.\&.\&. Args> \fBShared_ptr\fP< _Ty > \fBUTILLS::Make_Shared\fP (Args &&\&.\&.\&. args)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _SMART_POINTER_"

.PP
Definition at line \fB3\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
