.TH "UPRISE_ENGINE/src/CORE/C_STARTUP.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/src/CORE/C_STARTUP.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'HeaderE/CORE/C_STARTUP\&.h'\fP
.br
\fR#include 'HeaderE/DATATYPES/D_DATATYPES\&.h'\fP
.br
\fR#include 'MESSAGES\&.h'\fP
.br
\fR#include 'pch\&.h'\fP
.br
\fR#include 'PHYSICS\&.h'\fP
.br
\fR#include 'HeaderE/CORE/C_CPUFEATURES\&.h'\fP
.br
\fR#include 'RENDERSETUP\&.h'\fP
.br
\fR#include 'DEBUG_LOGGER\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
