.TH "Camera" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Camera
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CAMERA\&.h>\fP
.PP
Inherits \fBCORE::Behaviour\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBI_WINDOW\fP (ImGui::SliderFloat('FOV Direct', &camera\&.FOV, 0, 90);) \fBCOPY\fP(\fBCamera\fP"
.br
.in -1c

Public Member Functions inherited from \fBCORE::Behaviour\fP
.in +1c
.ti -1c
.RI "\fBBehaviour\fP ()"
.br
.ti -1c
.RI "\fBBehaviour\fP (\fBGameObject\fP *oobj, std::shared_ptr< \fBCORE::Behaviour\fP > trans)"
.br
.ti -1c
.RI "virtual std::shared_ptr< \fBCORE::Behaviour\fP > \fBCopy\fP ()=0"
.br
.ti -1c
.RI "virtual std::shared_ptr< \fBCORE::Behaviour\fP > \fBDeepCopy\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBEditorWindow\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBAwake\fP ()"
.br
.ti -1c
.RI "virtual void \fBStart\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBCORE::Behaviour\fP
.in +1c
.ti -1c
.RI "static void \fBupdateAll\fP ()"
.br
.ti -1c
.RI "static void \fBupdateAllAWAKE\fP ()"
.br
.ti -1c
.RI "static void \fBupdateAllSTART\fP ()"
.br
.ti -1c
.RI "static void \fBupdateallParallel\fP ()"
.br
.in -1c

Public Attributes inherited from \fBCORE::Behaviour\fP
.in +1c
.ti -1c
.RI "\fBGameObject\fP * \fBgameobject\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBTransform\fP > \fBTRANSFORM\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBCORE::Behaviour\fP > \fBtransf\fP"
.br
.ti -1c
.RI "std::string \fBcompname\fP"
.br
.ti -1c
.RI "UUID \fBuuID\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.in -1c

Static Public Attributes inherited from \fBCORE::Behaviour\fP
.in +1c
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBCORE::Behaviour\fP > > \fBobjectss\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBBehaviour\fP > > \fBbehaviours\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBBehaviour\fP > > \fBAWAKES\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBBehaviour\fP > > \fBStarts\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBBehaviour\fP > > \fBParallel_Updates\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBCAMERA\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Camera::I_WINDOW (ImGui::SliderFloat('FOV Direct', &camera\&.FOV, 0, 90); )"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
