.TH "CD3DX12_STATIC_SAMPLER_DESC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CD3DX12_STATIC_SAMPLER_DESC
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3dx12_root_signature\&.h>\fP
.PP
Inherits \fBD3D12_STATIC_SAMPLER_DESC\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCD3DX12_STATIC_SAMPLER_DESC\fP ()=default"
.br
.ti -1c
.RI "\fBCD3DX12_STATIC_SAMPLER_DESC\fP (const \fBD3D12_STATIC_SAMPLER_DESC\fP &o) noexcept"
.br
.ti -1c
.RI "\fBCD3DX12_STATIC_SAMPLER_DESC\fP (UINT shaderRegister, \fBD3D12_FILTER\fP \fBfilter\fP=\fBD3D12_FILTER_ANISOTROPIC\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressU=\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressV=\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressW=\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP, FLOAT mipLODBias=0, UINT maxAnisotropy=16, \fBD3D12_COMPARISON_FUNC\fP comparisonFunc=\fBD3D12_COMPARISON_FUNC_LESS_EQUAL\fP, \fBD3D12_STATIC_BORDER_COLOR\fP borderColor=D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE, FLOAT minLOD=0\&.\fBf\fP, FLOAT maxLOD=D3D12_FLOAT32_MAX, \fBD3D12_SHADER_VISIBILITY\fP shaderVisibility=\fBD3D12_SHADER_VISIBILITY_ALL\fP, UINT registerSpace=0) noexcept"
.br
.ti -1c
.RI "\fBvoid\fP \fBInit\fP (UINT shaderRegister, \fBD3D12_FILTER\fP \fBfilter\fP=\fBD3D12_FILTER_ANISOTROPIC\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressU=\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressV=\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressW=\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP, FLOAT mipLODBias=0, UINT maxAnisotropy=16, \fBD3D12_COMPARISON_FUNC\fP comparisonFunc=\fBD3D12_COMPARISON_FUNC_LESS_EQUAL\fP, \fBD3D12_STATIC_BORDER_COLOR\fP borderColor=D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE, FLOAT minLOD=0\&.\fBf\fP, FLOAT maxLOD=D3D12_FLOAT32_MAX, \fBD3D12_SHADER_VISIBILITY\fP shaderVisibility=\fBD3D12_SHADER_VISIBILITY_ALL\fP, UINT registerSpace=0) noexcept"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBvoid\fP \fBInit\fP (_Out_ \fBD3D12_STATIC_SAMPLER_DESC\fP &samplerDesc, UINT shaderRegister, \fBD3D12_FILTER\fP \fBfilter\fP=\fBD3D12_FILTER_ANISOTROPIC\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressU=\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressV=\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressW=\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP, FLOAT mipLODBias=0, UINT maxAnisotropy=16, \fBD3D12_COMPARISON_FUNC\fP comparisonFunc=\fBD3D12_COMPARISON_FUNC_LESS_EQUAL\fP, \fBD3D12_STATIC_BORDER_COLOR\fP borderColor=D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE, FLOAT minLOD=0\&.\fBf\fP, FLOAT maxLOD=D3D12_FLOAT32_MAX, \fBD3D12_SHADER_VISIBILITY\fP shaderVisibility=\fBD3D12_SHADER_VISIBILITY_ALL\fP, UINT registerSpace=0) noexcept"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBD3D12_STATIC_SAMPLER_DESC\fP
.in +1c
.ti -1c
.RI "\fBD3D12_FILTER\fP \fBFilter\fP"
.br
.ti -1c
.RI "\fBD3D12_TEXTURE_ADDRESS_MODE\fP \fBAddressU\fP"
.br
.ti -1c
.RI "\fBD3D12_TEXTURE_ADDRESS_MODE\fP \fBAddressV\fP"
.br
.ti -1c
.RI "\fBD3D12_TEXTURE_ADDRESS_MODE\fP \fBAddressW\fP"
.br
.ti -1c
.RI "FLOAT \fBMipLODBias\fP"
.br
.ti -1c
.RI "UINT \fBMaxAnisotropy\fP"
.br
.ti -1c
.RI "\fBD3D12_COMPARISON_FUNC\fP \fBComparisonFunc\fP"
.br
.ti -1c
.RI "\fBD3D12_STATIC_BORDER_COLOR\fP \fBBorderColor\fP"
.br
.ti -1c
.RI "FLOAT \fBMinLOD\fP"
.br
.ti -1c
.RI "FLOAT \fBMaxLOD\fP"
.br
.ti -1c
.RI "UINT \fBShaderRegister\fP"
.br
.ti -1c
.RI "UINT \fBRegisterSpace\fP"
.br
.ti -1c
.RI "\fBD3D12_SHADER_VISIBILITY\fP \fBShaderVisibility\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CD3DX12_STATIC_SAMPLER_DESC::CD3DX12_STATIC_SAMPLER_DESC ()\fR [default]\fP"

.SS "CD3DX12_STATIC_SAMPLER_DESC::CD3DX12_STATIC_SAMPLER_DESC (const \fBD3D12_STATIC_SAMPLER_DESC\fP & o)\fR [inline]\fP, \fR [explicit]\fP, \fR [noexcept]\fP"

.SS "CD3DX12_STATIC_SAMPLER_DESC::CD3DX12_STATIC_SAMPLER_DESC (UINT shaderRegister, \fBD3D12_FILTER\fP filter = \fR\fBD3D12_FILTER_ANISOTROPIC\fP\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressU = \fR\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressV = \fR\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressW = \fR\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP\fP, FLOAT mipLODBias = \fR0\fP, UINT maxAnisotropy = \fR16\fP, \fBD3D12_COMPARISON_FUNC\fP comparisonFunc = \fR\fBD3D12_COMPARISON_FUNC_LESS_EQUAL\fP\fP, \fBD3D12_STATIC_BORDER_COLOR\fP borderColor = \fRD3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE\fP, FLOAT minLOD = \fR0\&.\fBf\fP\fP, FLOAT maxLOD = \fRD3D12_FLOAT32_MAX\fP, \fBD3D12_SHADER_VISIBILITY\fP shaderVisibility = \fR\fBD3D12_SHADER_VISIBILITY_ALL\fP\fP, UINT registerSpace = \fR0\fP)\fR [inline]\fP, \fR [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static \fBvoid\fP CD3DX12_STATIC_SAMPLER_DESC::Init (_Out_ \fBD3D12_STATIC_SAMPLER_DESC\fP & samplerDesc, UINT shaderRegister, \fBD3D12_FILTER\fP filter = \fR\fBD3D12_FILTER_ANISOTROPIC\fP\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressU = \fR\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressV = \fR\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressW = \fR\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP\fP, FLOAT mipLODBias = \fR0\fP, UINT maxAnisotropy = \fR16\fP, \fBD3D12_COMPARISON_FUNC\fP comparisonFunc = \fR\fBD3D12_COMPARISON_FUNC_LESS_EQUAL\fP\fP, \fBD3D12_STATIC_BORDER_COLOR\fP borderColor = \fRD3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE\fP, FLOAT minLOD = \fR0\&.\fBf\fP\fP, FLOAT maxLOD = \fRD3D12_FLOAT32_MAX\fP, \fBD3D12_SHADER_VISIBILITY\fP shaderVisibility = \fR\fBD3D12_SHADER_VISIBILITY_ALL\fP\fP, UINT registerSpace = \fR0\fP)\fR [inline]\fP, \fR [static]\fP, \fR [noexcept]\fP"

.SS "\fBvoid\fP CD3DX12_STATIC_SAMPLER_DESC::Init (UINT shaderRegister, \fBD3D12_FILTER\fP filter = \fR\fBD3D12_FILTER_ANISOTROPIC\fP\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressU = \fR\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressV = \fR\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP\fP, \fBD3D12_TEXTURE_ADDRESS_MODE\fP addressW = \fR\fBD3D12_TEXTURE_ADDRESS_MODE_WRAP\fP\fP, FLOAT mipLODBias = \fR0\fP, UINT maxAnisotropy = \fR16\fP, \fBD3D12_COMPARISON_FUNC\fP comparisonFunc = \fR\fBD3D12_COMPARISON_FUNC_LESS_EQUAL\fP\fP, \fBD3D12_STATIC_BORDER_COLOR\fP borderColor = \fRD3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE\fP, FLOAT minLOD = \fR0\&.\fBf\fP\fP, FLOAT maxLOD = \fRD3D12_FLOAT32_MAX\fP, \fBD3D12_SHADER_VISIBILITY\fP shaderVisibility = \fR\fBD3D12_SHADER_VISIBILITY_ALL\fP\fP, UINT registerSpace = \fR0\fP)\fR [inline]\fP, \fR [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
