.TH "CD3DX12_PIPELINE_STATE_STREAM" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CD3DX12_PIPELINE_STATE_STREAM
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3dx12_pipeline_state_stream\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM\fP ()=default"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM\fP (const \fBD3D12_GRAPHICS_PIPELINE_STATE_DESC\fP &Desc) noexcept"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM\fP (const \fBD3D12_COMPUTE_PIPELINE_STATE_DESC\fP &Desc) noexcept"
.br
.ti -1c
.RI "\fBD3D12_GRAPHICS_PIPELINE_STATE_DESC\fP \fBGraphicsDescV0\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_COMPUTE_PIPELINE_STATE_DESC\fP \fBComputeDescV0\fP () const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_FLAGS\fP \fBFlags\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_NODE_MASK\fP \fBNodeMask\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_ROOT_SIGNATURE\fP \fBpRootSignature\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_INPUT_LAYOUT\fP \fBInputLayout\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_IB_STRIP_CUT_VALUE\fP \fBIBStripCutValue\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_PRIMITIVE_TOPOLOGY\fP \fBPrimitiveTopologyType\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_VS\fP \fBVS\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_GS\fP \fBGS\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_STREAM_OUTPUT\fP \fBStreamOutput\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_HS\fP \fBHS\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_DS\fP \fBDS\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_PS\fP \fBPS\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_CS\fP \fBCS\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_BLEND_DESC\fP \fBBlendState\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_DEPTH_STENCIL1\fP \fBDepthStencilState\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_DEPTH_STENCIL_FORMAT\fP \fBDSVFormat\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_RASTERIZER\fP \fBRasterizerState\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_RENDER_TARGET_FORMATS\fP \fBRTVFormats\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_SAMPLE_DESC\fP \fBSampleDesc\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_SAMPLE_MASK\fP \fBSampleMask\fP"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_CACHED_PSO\fP \fBCachedPSO\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CD3DX12_PIPELINE_STATE_STREAM::CD3DX12_PIPELINE_STATE_STREAM ()\fR [default]\fP"

.SS "CD3DX12_PIPELINE_STATE_STREAM::CD3DX12_PIPELINE_STATE_STREAM (const \fBD3D12_GRAPHICS_PIPELINE_STATE_DESC\fP & Desc)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "CD3DX12_PIPELINE_STATE_STREAM::CD3DX12_PIPELINE_STATE_STREAM (const \fBD3D12_COMPUTE_PIPELINE_STATE_DESC\fP & Desc)\fR [inline]\fP, \fR [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBD3D12_COMPUTE_PIPELINE_STATE_DESC\fP CD3DX12_PIPELINE_STATE_STREAM::ComputeDescV0 () const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "\fBD3D12_GRAPHICS_PIPELINE_STATE_DESC\fP CD3DX12_PIPELINE_STATE_STREAM::GraphicsDescV0 () const\fR [inline]\fP, \fR [noexcept]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_BLEND_DESC\fP CD3DX12_PIPELINE_STATE_STREAM::BlendState"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_CACHED_PSO\fP CD3DX12_PIPELINE_STATE_STREAM::CachedPSO"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_CS\fP CD3DX12_PIPELINE_STATE_STREAM::CS"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_DEPTH_STENCIL1\fP CD3DX12_PIPELINE_STATE_STREAM::DepthStencilState"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_DS\fP CD3DX12_PIPELINE_STATE_STREAM::DS"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_DEPTH_STENCIL_FORMAT\fP CD3DX12_PIPELINE_STATE_STREAM::DSVFormat"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_FLAGS\fP CD3DX12_PIPELINE_STATE_STREAM::Flags"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_GS\fP CD3DX12_PIPELINE_STATE_STREAM::GS"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_HS\fP CD3DX12_PIPELINE_STATE_STREAM::HS"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_IB_STRIP_CUT_VALUE\fP CD3DX12_PIPELINE_STATE_STREAM::IBStripCutValue"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_INPUT_LAYOUT\fP CD3DX12_PIPELINE_STATE_STREAM::InputLayout"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_NODE_MASK\fP CD3DX12_PIPELINE_STATE_STREAM::NodeMask"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_PRIMITIVE_TOPOLOGY\fP CD3DX12_PIPELINE_STATE_STREAM::PrimitiveTopologyType"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_ROOT_SIGNATURE\fP CD3DX12_PIPELINE_STATE_STREAM::pRootSignature"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_PS\fP CD3DX12_PIPELINE_STATE_STREAM::PS"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_RASTERIZER\fP CD3DX12_PIPELINE_STATE_STREAM::RasterizerState"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_RENDER_TARGET_FORMATS\fP CD3DX12_PIPELINE_STATE_STREAM::RTVFormats"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_SAMPLE_DESC\fP CD3DX12_PIPELINE_STATE_STREAM::SampleDesc"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_SAMPLE_MASK\fP CD3DX12_PIPELINE_STATE_STREAM::SampleMask"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_STREAM_OUTPUT\fP CD3DX12_PIPELINE_STATE_STREAM::StreamOutput"

.SS "\fBCD3DX12_PIPELINE_STATE_STREAM_VS\fP CD3DX12_PIPELINE_STATE_STREAM::VS"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
