.TH "CD3DX12_RESOURCE_DESC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CD3DX12_RESOURCE_DESC
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3dx12_core\&.h>\fP
.PP
Inherits \fBD3D12_RESOURCE_DESC\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCD3DX12_RESOURCE_DESC\fP ()=default"
.br
.ti -1c
.RI "\fBCD3DX12_RESOURCE_DESC\fP (const \fBD3D12_RESOURCE_DESC\fP &o) noexcept"
.br
.ti -1c
.RI "\fBCD3DX12_RESOURCE_DESC\fP (\fBD3D12_RESOURCE_DIMENSION\fP dimension, UINT64 alignment, UINT64 \fBwidth\fP, UINT \fBheight\fP, UINT16 depthOrArraySize, UINT16 mipLevels, \fBDXGI_FORMAT\fP \fBformat\fP, UINT sampleCount, UINT sampleQuality, \fBD3D12_TEXTURE_LAYOUT\fP layout, \fBD3D12_RESOURCE_FLAGS\fP \fBflags\fP) noexcept"
.br
.ti -1c
.RI "UINT16 \fBDepth\fP () const noexcept"
.br
.ti -1c
.RI "UINT16 \fBArraySize\fP () const noexcept"
.br
.ti -1c
.RI "UINT8 \fBPlaneCount\fP (_In_ \fBID3D12Device\fP *pDevice) const noexcept"
.br
.ti -1c
.RI "UINT \fBSubresources\fP (_In_ \fBID3D12Device\fP *pDevice) const noexcept"
.br
.ti -1c
.RI "UINT \fBCalcSubresource\fP (UINT MipSlice, UINT ArraySlice, UINT PlaneSlice) noexcept"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCD3DX12_RESOURCE_DESC\fP \fBBuffer\fP (const \fBD3D12_RESOURCE_ALLOCATION_INFO\fP &resAllocInfo, \fBD3D12_RESOURCE_FLAGS\fP \fBflags\fP=\fBD3D12_RESOURCE_FLAG_NONE\fP) noexcept"
.br
.ti -1c
.RI "static \fBCD3DX12_RESOURCE_DESC\fP \fBBuffer\fP (UINT64 \fBwidth\fP, \fBD3D12_RESOURCE_FLAGS\fP \fBflags\fP=\fBD3D12_RESOURCE_FLAG_NONE\fP, UINT64 alignment=0) noexcept"
.br
.ti -1c
.RI "static \fBCD3DX12_RESOURCE_DESC\fP \fBTex1D\fP (\fBDXGI_FORMAT\fP \fBformat\fP, UINT64 \fBwidth\fP, UINT16 arraySize=1, UINT16 mipLevels=0, \fBD3D12_RESOURCE_FLAGS\fP \fBflags\fP=\fBD3D12_RESOURCE_FLAG_NONE\fP, \fBD3D12_TEXTURE_LAYOUT\fP layout=\fBD3D12_TEXTURE_LAYOUT_UNKNOWN\fP, UINT64 alignment=0) noexcept"
.br
.ti -1c
.RI "static \fBCD3DX12_RESOURCE_DESC\fP \fBTex2D\fP (\fBDXGI_FORMAT\fP \fBformat\fP, UINT64 \fBwidth\fP, UINT \fBheight\fP, UINT16 arraySize=1, UINT16 mipLevels=0, UINT sampleCount=1, UINT sampleQuality=0, \fBD3D12_RESOURCE_FLAGS\fP \fBflags\fP=\fBD3D12_RESOURCE_FLAG_NONE\fP, \fBD3D12_TEXTURE_LAYOUT\fP layout=\fBD3D12_TEXTURE_LAYOUT_UNKNOWN\fP, UINT64 alignment=0) noexcept"
.br
.ti -1c
.RI "static \fBCD3DX12_RESOURCE_DESC\fP \fBTex3D\fP (\fBDXGI_FORMAT\fP \fBformat\fP, UINT64 \fBwidth\fP, UINT \fBheight\fP, UINT16 \fBdepth\fP, UINT16 mipLevels=0, \fBD3D12_RESOURCE_FLAGS\fP \fBflags\fP=\fBD3D12_RESOURCE_FLAG_NONE\fP, \fBD3D12_TEXTURE_LAYOUT\fP layout=\fBD3D12_TEXTURE_LAYOUT_UNKNOWN\fP, UINT64 alignment=0) noexcept"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBD3D12_RESOURCE_DESC\fP
.in +1c
.ti -1c
.RI "\fBD3D12_RESOURCE_DIMENSION\fP \fBDimension\fP"
.br
.ti -1c
.RI "UINT64 \fBAlignment\fP"
.br
.ti -1c
.RI "UINT64 \fBWidth\fP"
.br
.ti -1c
.RI "UINT \fBHeight\fP"
.br
.ti -1c
.RI "UINT16 \fBDepthOrArraySize\fP"
.br
.ti -1c
.RI "UINT16 \fBMipLevels\fP"
.br
.ti -1c
.RI "\fBDXGI_FORMAT\fP \fBFormat\fP"
.br
.ti -1c
.RI "\fBDXGI_SAMPLE_DESC\fP \fBSampleDesc\fP"
.br
.ti -1c
.RI "\fBD3D12_TEXTURE_LAYOUT\fP \fBLayout\fP"
.br
.ti -1c
.RI "\fBD3D12_RESOURCE_FLAGS\fP \fBFlags\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CD3DX12_RESOURCE_DESC::CD3DX12_RESOURCE_DESC ()\fR [default]\fP"

.SS "CD3DX12_RESOURCE_DESC::CD3DX12_RESOURCE_DESC (const \fBD3D12_RESOURCE_DESC\fP & o)\fR [inline]\fP, \fR [explicit]\fP, \fR [noexcept]\fP"

.SS "CD3DX12_RESOURCE_DESC::CD3DX12_RESOURCE_DESC (\fBD3D12_RESOURCE_DIMENSION\fP dimension, UINT64 alignment, UINT64 width, UINT height, UINT16 depthOrArraySize, UINT16 mipLevels, \fBDXGI_FORMAT\fP format, UINT sampleCount, UINT sampleQuality, \fBD3D12_TEXTURE_LAYOUT\fP layout, \fBD3D12_RESOURCE_FLAGS\fP flags)\fR [inline]\fP, \fR [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "UINT16 CD3DX12_RESOURCE_DESC::ArraySize () const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "static \fBCD3DX12_RESOURCE_DESC\fP CD3DX12_RESOURCE_DESC::Buffer (const \fBD3D12_RESOURCE_ALLOCATION_INFO\fP & resAllocInfo, \fBD3D12_RESOURCE_FLAGS\fP flags = \fR\fBD3D12_RESOURCE_FLAG_NONE\fP\fP)\fR [inline]\fP, \fR [static]\fP, \fR [noexcept]\fP"

.SS "static \fBCD3DX12_RESOURCE_DESC\fP CD3DX12_RESOURCE_DESC::Buffer (UINT64 width, \fBD3D12_RESOURCE_FLAGS\fP flags = \fR\fBD3D12_RESOURCE_FLAG_NONE\fP\fP, UINT64 alignment = \fR0\fP)\fR [inline]\fP, \fR [static]\fP, \fR [noexcept]\fP"

.SS "UINT CD3DX12_RESOURCE_DESC::CalcSubresource (UINT MipSlice, UINT ArraySlice, UINT PlaneSlice)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "UINT16 CD3DX12_RESOURCE_DESC::Depth () const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "UINT8 CD3DX12_RESOURCE_DESC::PlaneCount (_In_ \fBID3D12Device\fP * pDevice) const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "UINT CD3DX12_RESOURCE_DESC::Subresources (_In_ \fBID3D12Device\fP * pDevice) const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "static \fBCD3DX12_RESOURCE_DESC\fP CD3DX12_RESOURCE_DESC::Tex1D (\fBDXGI_FORMAT\fP format, UINT64 width, UINT16 arraySize = \fR1\fP, UINT16 mipLevels = \fR0\fP, \fBD3D12_RESOURCE_FLAGS\fP flags = \fR\fBD3D12_RESOURCE_FLAG_NONE\fP\fP, \fBD3D12_TEXTURE_LAYOUT\fP layout = \fR\fBD3D12_TEXTURE_LAYOUT_UNKNOWN\fP\fP, UINT64 alignment = \fR0\fP)\fR [inline]\fP, \fR [static]\fP, \fR [noexcept]\fP"

.SS "static \fBCD3DX12_RESOURCE_DESC\fP CD3DX12_RESOURCE_DESC::Tex2D (\fBDXGI_FORMAT\fP format, UINT64 width, UINT height, UINT16 arraySize = \fR1\fP, UINT16 mipLevels = \fR0\fP, UINT sampleCount = \fR1\fP, UINT sampleQuality = \fR0\fP, \fBD3D12_RESOURCE_FLAGS\fP flags = \fR\fBD3D12_RESOURCE_FLAG_NONE\fP\fP, \fBD3D12_TEXTURE_LAYOUT\fP layout = \fR\fBD3D12_TEXTURE_LAYOUT_UNKNOWN\fP\fP, UINT64 alignment = \fR0\fP)\fR [inline]\fP, \fR [static]\fP, \fR [noexcept]\fP"

.SS "static \fBCD3DX12_RESOURCE_DESC\fP CD3DX12_RESOURCE_DESC::Tex3D (\fBDXGI_FORMAT\fP format, UINT64 width, UINT height, UINT16 depth, UINT16 mipLevels = \fR0\fP, \fBD3D12_RESOURCE_FLAGS\fP flags = \fR\fBD3D12_RESOURCE_FLAG_NONE\fP\fP, \fBD3D12_TEXTURE_LAYOUT\fP layout = \fR\fBD3D12_TEXTURE_LAYOUT_UNKNOWN\fP\fP, UINT64 alignment = \fR0\fP)\fR [inline]\fP, \fR [static]\fP, \fR [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
