.TH "CD3DX12FeatureSupport" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CD3DX12FeatureSupport
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3dx12_check_feature_support\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCD3DX12FeatureSupport\fP () noexcept"
.br
.ti -1c
.RI "HRESULT \fBInit\fP (\fBID3D12Device\fP *pDevice)"
.br
.ti -1c
.RI "HRESULT \fBGetStatus\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBDoublePrecisionFloatShaderOps\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBOutputMergerLogicOp\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_SHADER_MIN_PRECISION_SUPPORT\fP \fBMinPrecisionSupport\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_TILED_RESOURCES_TIER\fP \fBTiledResourcesTier\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_RESOURCE_BINDING_TIER\fP \fBResourceBindingTier\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBPSSpecifiedStencilRefSupported\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBTypedUAVLoadAdditionalFormats\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBROVsSupported\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_CONSERVATIVE_RASTERIZATION_TIER\fP \fBConservativeRasterizationTier\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBStandardSwizzle64KBSupported\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBCrossAdapterRowMajorTextureSupported\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBVPAndRTArrayIndexFromAnyShaderFeedingRasterizerSupportedWithoutGSEmulation\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_RESOURCE_HEAP_TIER\fP \fBResourceHeapTier\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_CROSS_NODE_SHARING_TIER\fP \fBCrossNodeSharingTier\fP () const noexcept"
.br
.ti -1c
.RI "UINT \fBMaxGPUVirtualAddressBitsPerResource\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D_FEATURE_LEVEL\fP \fBMaxSupportedFeatureLevel\fP () const noexcept"
.br
.ti -1c
.RI "HRESULT \fBFormatSupport\fP (\fBDXGI_FORMAT\fP Format, \fBD3D12_FORMAT_SUPPORT1\fP &Support1, \fBD3D12_FORMAT_SUPPORT2\fP &Support2) const"
.br
.ti -1c
.RI "HRESULT \fBMultisampleQualityLevels\fP (\fBDXGI_FORMAT\fP Format, UINT SampleCount, \fBD3D12_MULTISAMPLE_QUALITY_LEVEL_FLAGS\fP \fBFlags\fP, UINT &NumQualityLevels) const"
.br
.ti -1c
.RI "HRESULT \fBFormatInfo\fP (\fBDXGI_FORMAT\fP Format, UINT8 &PlaneCount) const"
.br
.ti -1c
.RI "UINT \fBMaxGPUVirtualAddressBitsPerProcess\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D_SHADER_MODEL\fP \fBHighestShaderModel\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBWaveOps\fP () const noexcept"
.br
.ti -1c
.RI "UINT \fBWaveLaneCountMin\fP () const noexcept"
.br
.ti -1c
.RI "UINT \fBWaveLaneCountMax\fP () const noexcept"
.br
.ti -1c
.RI "UINT \fBTotalLaneCount\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBExpandedComputeResourceStates\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBInt64ShaderOps\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_PROTECTED_RESOURCE_SESSION_SUPPORT_FLAGS\fP \fBProtectedResourceSessionSupport\fP (UINT NodeIndex=0) const"
.br
.ti -1c
.RI "\fBD3D_ROOT_SIGNATURE_VERSION\fP \fBHighestRootSignatureVersion\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBTileBasedRenderer\fP (UINT NodeIndex=0) const"
.br
.ti -1c
.RI "BOOL \fBUMA\fP (UINT NodeIndex=0) const"
.br
.ti -1c
.RI "BOOL \fBCacheCoherentUMA\fP (UINT NodeIndex=0) const"
.br
.ti -1c
.RI "BOOL \fBIsolatedMMU\fP (UINT NodeIndex=0) const"
.br
.ti -1c
.RI "BOOL \fBDepthBoundsTestSupported\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_PROGRAMMABLE_SAMPLE_POSITIONS_TIER\fP \fBProgrammableSamplePositionsTier\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_SHADER_CACHE_SUPPORT_FLAGS\fP \fBShaderCacheSupportFlags\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBCommandQueuePrioritySupported\fP (\fBD3D12_COMMAND_LIST_TYPE\fP CommandListType, UINT Priority)"
.br
.ti -1c
.RI "BOOL \fBCopyQueueTimestampQueriesSupported\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBCastingFullyTypedFormatSupported\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_COMMAND_LIST_SUPPORT_FLAGS\fP \fBWriteBufferImmediateSupportFlags\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_VIEW_INSTANCING_TIER\fP \fBViewInstancingTier\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBBarycentricsSupported\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBExistingHeapsSupported\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBMSAA64KBAlignedTextureSupported\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_SHARED_RESOURCE_COMPATIBILITY_TIER\fP \fBSharedResourceCompatibilityTier\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBNative16BitShaderOpsSupported\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_HEAP_SERIALIZATION_TIER\fP \fBHeapSerializationTier\fP (UINT NodeIndex=0) const"
.br
.ti -1c
.RI "BOOL \fBCrossNodeAtomicShaderInstructions\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBSRVOnlyTiledResourceTier3\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_RENDER_PASS_TIER\fP \fBRenderPassesTier\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_RAYTRACING_TIER\fP \fBRaytracingTier\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBAdditionalShadingRatesSupported\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBPerPrimitiveShadingRateSupportedWithViewportIndexing\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_VARIABLE_SHADING_RATE_TIER\fP \fBVariableShadingRateTier\fP () const noexcept"
.br
.ti -1c
.RI "UINT \fBShadingRateImageTileSize\fP () const noexcept"
.br
.ti -1c
.RI "BOOL \fBBackgroundProcessingSupported\fP () const noexcept"
.br
.ti -1c
.RI "HRESULT \fBQueryMetaCommand\fP (\fBD3D12_FEATURE_DATA_QUERY_META_COMMAND\fP &dQueryMetaCommand) const"
.br
.ti -1c
.RI "\fBD3D12_MESH_SHADER_TIER\fP \fBMeshShaderTier\fP () const noexcept"
.br
.ti -1c
.RI "\fBD3D12_SAMPLER_FEEDBACK_TIER\fP \fBSamplerFeedbackTier\fP () const noexcept"
.br
.ti -1c
.RI "UINT \fBProtectedResourceSessionTypeCount\fP (UINT NodeIndex=0) const"
.br
.ti -1c
.RI "std::vector< GUID > \fBProtectedResourceSessionTypes\fP (UINT NodeIndex=0) const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CD3DX12FeatureSupport::CD3DX12FeatureSupport ()\fR [inline]\fP, \fR [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "BOOL CD3DX12FeatureSupport::AdditionalShadingRatesSupported () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::BackgroundProcessingSupported () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::BarycentricsSupported () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::CacheCoherentUMA (UINT NodeIndex = \fR0\fP) const"

.SS "BOOL CD3DX12FeatureSupport::CastingFullyTypedFormatSupported () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::CommandQueuePrioritySupported (\fBD3D12_COMMAND_LIST_TYPE\fP CommandListType, UINT Priority)\fR [inline]\fP"

.SS "\fBD3D12_CONSERVATIVE_RASTERIZATION_TIER\fP CD3DX12FeatureSupport::ConservativeRasterizationTier () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::CopyQueueTimestampQueriesSupported () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::CrossAdapterRowMajorTextureSupported () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::CrossNodeAtomicShaderInstructions () const\fR [noexcept]\fP"

.SS "\fBD3D12_CROSS_NODE_SHARING_TIER\fP CD3DX12FeatureSupport::CrossNodeSharingTier () const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::DepthBoundsTestSupported () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::DoublePrecisionFloatShaderOps () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::ExistingHeapsSupported () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::ExpandedComputeResourceStates () const\fR [noexcept]\fP"

.SS "HRESULT CD3DX12FeatureSupport::FormatInfo (\fBDXGI_FORMAT\fP Format, UINT8 & PlaneCount) const\fR [inline]\fP"

.SS "HRESULT CD3DX12FeatureSupport::FormatSupport (\fBDXGI_FORMAT\fP Format, \fBD3D12_FORMAT_SUPPORT1\fP & Support1, \fBD3D12_FORMAT_SUPPORT2\fP & Support2) const\fR [inline]\fP"

.SS "HRESULT CD3DX12FeatureSupport::GetStatus () const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "\fBD3D12_HEAP_SERIALIZATION_TIER\fP CD3DX12FeatureSupport::HeapSerializationTier (UINT NodeIndex = \fR0\fP) const"

.SS "\fBD3D_ROOT_SIGNATURE_VERSION\fP CD3DX12FeatureSupport::HighestRootSignatureVersion () const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "\fBD3D_SHADER_MODEL\fP CD3DX12FeatureSupport::HighestShaderModel () const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "HRESULT CD3DX12FeatureSupport::Init (\fBID3D12Device\fP * pDevice)\fR [inline]\fP"

.SS "BOOL CD3DX12FeatureSupport::Int64ShaderOps () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::IsolatedMMU (UINT NodeIndex = \fR0\fP) const"

.SS "UINT CD3DX12FeatureSupport::MaxGPUVirtualAddressBitsPerProcess () const\fR [noexcept]\fP"

.SS "UINT CD3DX12FeatureSupport::MaxGPUVirtualAddressBitsPerResource () const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "\fBD3D_FEATURE_LEVEL\fP CD3DX12FeatureSupport::MaxSupportedFeatureLevel () const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "\fBD3D12_MESH_SHADER_TIER\fP CD3DX12FeatureSupport::MeshShaderTier () const\fR [noexcept]\fP"

.SS "\fBD3D12_SHADER_MIN_PRECISION_SUPPORT\fP CD3DX12FeatureSupport::MinPrecisionSupport () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::MSAA64KBAlignedTextureSupported () const\fR [noexcept]\fP"

.SS "HRESULT CD3DX12FeatureSupport::MultisampleQualityLevels (\fBDXGI_FORMAT\fP Format, UINT SampleCount, \fBD3D12_MULTISAMPLE_QUALITY_LEVEL_FLAGS\fP Flags, UINT & NumQualityLevels) const\fR [inline]\fP"

.SS "BOOL CD3DX12FeatureSupport::Native16BitShaderOpsSupported () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::OutputMergerLogicOp () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::PerPrimitiveShadingRateSupportedWithViewportIndexing () const\fR [noexcept]\fP"

.SS "\fBD3D12_PROGRAMMABLE_SAMPLE_POSITIONS_TIER\fP CD3DX12FeatureSupport::ProgrammableSamplePositionsTier () const\fR [noexcept]\fP"

.SS "\fBD3D12_PROTECTED_RESOURCE_SESSION_SUPPORT_FLAGS\fP CD3DX12FeatureSupport::ProtectedResourceSessionSupport (UINT NodeIndex = \fR0\fP) const\fR [inline]\fP"

.SS "UINT CD3DX12FeatureSupport::ProtectedResourceSessionTypeCount (UINT NodeIndex = \fR0\fP) const"

.SS "std::vector< GUID > CD3DX12FeatureSupport::ProtectedResourceSessionTypes (UINT NodeIndex = \fR0\fP) const"

.SS "BOOL CD3DX12FeatureSupport::PSSpecifiedStencilRefSupported () const\fR [noexcept]\fP"

.SS "HRESULT CD3DX12FeatureSupport::QueryMetaCommand (\fBD3D12_FEATURE_DATA_QUERY_META_COMMAND\fP & dQueryMetaCommand) const\fR [inline]\fP"

.SS "\fBD3D12_RAYTRACING_TIER\fP CD3DX12FeatureSupport::RaytracingTier () const\fR [noexcept]\fP"

.SS "\fBD3D12_RENDER_PASS_TIER\fP CD3DX12FeatureSupport::RenderPassesTier () const\fR [noexcept]\fP"

.SS "\fBD3D12_RESOURCE_BINDING_TIER\fP CD3DX12FeatureSupport::ResourceBindingTier () const\fR [noexcept]\fP"

.SS "\fBD3D12_RESOURCE_HEAP_TIER\fP CD3DX12FeatureSupport::ResourceHeapTier () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::ROVsSupported () const\fR [noexcept]\fP"

.SS "\fBD3D12_SAMPLER_FEEDBACK_TIER\fP CD3DX12FeatureSupport::SamplerFeedbackTier () const\fR [noexcept]\fP"

.SS "\fBD3D12_SHADER_CACHE_SUPPORT_FLAGS\fP CD3DX12FeatureSupport::ShaderCacheSupportFlags () const\fR [noexcept]\fP"

.SS "UINT CD3DX12FeatureSupport::ShadingRateImageTileSize () const\fR [noexcept]\fP"

.SS "\fBD3D12_SHARED_RESOURCE_COMPATIBILITY_TIER\fP CD3DX12FeatureSupport::SharedResourceCompatibilityTier () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::SRVOnlyTiledResourceTier3 () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::StandardSwizzle64KBSupported () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::TileBasedRenderer (UINT NodeIndex = \fR0\fP) const"

.SS "\fBD3D12_TILED_RESOURCES_TIER\fP CD3DX12FeatureSupport::TiledResourcesTier () const\fR [noexcept]\fP"

.SS "UINT CD3DX12FeatureSupport::TotalLaneCount () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::TypedUAVLoadAdditionalFormats () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::UMA (UINT NodeIndex = \fR0\fP) const"

.SS "\fBD3D12_VARIABLE_SHADING_RATE_TIER\fP CD3DX12FeatureSupport::VariableShadingRateTier () const\fR [noexcept]\fP"

.SS "\fBD3D12_VIEW_INSTANCING_TIER\fP CD3DX12FeatureSupport::ViewInstancingTier () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::VPAndRTArrayIndexFromAnyShaderFeedingRasterizerSupportedWithoutGSEmulation () const\fR [noexcept]\fP"

.SS "UINT CD3DX12FeatureSupport::WaveLaneCountMax () const\fR [noexcept]\fP"

.SS "UINT CD3DX12FeatureSupport::WaveLaneCountMin () const\fR [noexcept]\fP"

.SS "BOOL CD3DX12FeatureSupport::WaveOps () const\fR [noexcept]\fP"

.SS "\fBD3D12_COMMAND_LIST_SUPPORT_FLAGS\fP CD3DX12FeatureSupport::WriteBufferImmediateSupportFlags () const\fR [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
