.TH "CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3dx12_pipeline_state_stream\&.h>\fP
.PP
Inherits \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP () noexcept"
.br
.ti -1c
.RI "\fBvoid\fP \fBFlagsCb\fP (\fBD3D12_PIPELINE_STATE_FLAGS\fP \fBFlags\fP) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBNodeMaskCb\fP (UINT NodeMask) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBRootSignatureCb\fP (\fBID3D12RootSignature\fP *pRootSignature) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBInputLayoutCb\fP (const \fBD3D12_INPUT_LAYOUT_DESC\fP &InputLayout) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBIBStripCutValueCb\fP (\fBD3D12_INDEX_BUFFER_STRIP_CUT_VALUE\fP IBStripCutValue) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBPrimitiveTopologyTypeCb\fP (\fBD3D12_PRIMITIVE_TOPOLOGY_TYPE\fP PrimitiveTopologyType) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBVSCb\fP (const \fBD3D12_SHADER_BYTECODE\fP &VS) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBGSCb\fP (const \fBD3D12_SHADER_BYTECODE\fP &GS) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBStreamOutputCb\fP (const \fBD3D12_STREAM_OUTPUT_DESC\fP &StreamOutput) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBHSCb\fP (const \fBD3D12_SHADER_BYTECODE\fP &HS) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBDSCb\fP (const \fBD3D12_SHADER_BYTECODE\fP &DS) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBPSCb\fP (const \fBD3D12_SHADER_BYTECODE\fP &PS) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBCSCb\fP (const \fBD3D12_SHADER_BYTECODE\fP &CS) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBASCb\fP (const \fBD3D12_SHADER_BYTECODE\fP &AS) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBMSCb\fP (const \fBD3D12_SHADER_BYTECODE\fP &MS) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBBlendStateCb\fP (const \fBD3D12_BLEND_DESC\fP &BlendState) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBDepthStencilStateCb\fP (const \fBD3D12_DEPTH_STENCIL_DESC\fP &DepthStencilState) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBDepthStencilState1Cb\fP (const \fBD3D12_DEPTH_STENCIL_DESC1\fP &DepthStencilState) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBDSVFormatCb\fP (\fBDXGI_FORMAT\fP DSVFormat) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBRasterizerStateCb\fP (const \fBD3D12_RASTERIZER_DESC\fP &RasterizerState) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBRTVFormatsCb\fP (const \fBD3D12_RT_FORMAT_ARRAY\fP &RTVFormats) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBSampleDescCb\fP (const \fBDXGI_SAMPLE_DESC\fP &SampleDesc) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBSampleMaskCb\fP (UINT SampleMask) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBViewInstancingCb\fP (const \fBD3D12_VIEW_INSTANCING_DESC\fP &ViewInstancingDesc) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBCachedPSOCb\fP (const \fBD3D12_CACHED_PIPELINE_STATE\fP &CachedPSO) override"
.br
.in -1c

Public Member Functions inherited from \fBID3DX12PipelineParserCallbacks\fP
.in +1c
.ti -1c
.RI "virtual \fBvoid\fP \fBErrorBadInputParameter\fP (UINT)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBErrorDuplicateSubobject\fP (\fBD3D12_PIPELINE_STATE_SUBOBJECT_TYPE\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBErrorUnknownSubobject\fP (UINT)"
.br
.ti -1c
.RI "virtual \fB~ID3DX12PipelineParserCallbacks\fP ()=default"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM2\fP \fBPipelineStream\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER ()\fR [inline]\fP, \fR [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::ASCb (const \fBD3D12_SHADER_BYTECODE\fP & AS)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::BlendStateCb (const \fBD3D12_BLEND_DESC\fP & BlendState)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::CachedPSOCb (const \fBD3D12_CACHED_PIPELINE_STATE\fP & CachedPSO)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::CSCb (const \fBD3D12_SHADER_BYTECODE\fP & CS)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::DepthStencilState1Cb (const \fBD3D12_DEPTH_STENCIL_DESC1\fP & DepthStencilState)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::DepthStencilStateCb (const \fBD3D12_DEPTH_STENCIL_DESC\fP & DepthStencilState)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::DSCb (const \fBD3D12_SHADER_BYTECODE\fP & DS)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::DSVFormatCb (\fBDXGI_FORMAT\fP DSVFormat)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::FlagsCb (\fBD3D12_PIPELINE_STATE_FLAGS\fP Flags)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::GSCb (const \fBD3D12_SHADER_BYTECODE\fP & GS)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::HSCb (const \fBD3D12_SHADER_BYTECODE\fP & HS)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::IBStripCutValueCb (\fBD3D12_INDEX_BUFFER_STRIP_CUT_VALUE\fP IBStripCutValue)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::InputLayoutCb (const \fBD3D12_INPUT_LAYOUT_DESC\fP & InputLayout)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::MSCb (const \fBD3D12_SHADER_BYTECODE\fP & MS)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::NodeMaskCb (UINT NodeMask)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::PrimitiveTopologyTypeCb (\fBD3D12_PRIMITIVE_TOPOLOGY_TYPE\fP PrimitiveTopologyType)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::PSCb (const \fBD3D12_SHADER_BYTECODE\fP & PS)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::RasterizerStateCb (const \fBD3D12_RASTERIZER_DESC\fP & RasterizerState)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::RootSignatureCb (\fBID3D12RootSignature\fP * pRootSignature)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::RTVFormatsCb (const \fBD3D12_RT_FORMAT_ARRAY\fP & RTVFormats)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::SampleDescCb (const \fBDXGI_SAMPLE_DESC\fP & SampleDesc)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::SampleMaskCb (UINT SampleMask)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::StreamOutputCb (const \fBD3D12_STREAM_OUTPUT_DESC\fP & StreamOutput)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::ViewInstancingCb (const \fBD3D12_VIEW_INSTANCING_DESC\fP & ViewInstancingDesc)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SS "\fBvoid\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::VSCb (const \fBD3D12_SHADER_BYTECODE\fP & VS)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBID3DX12PipelineParserCallbacks\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCD3DX12_PIPELINE_STATE_STREAM2\fP CD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER::PipelineStream"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
