.TH "CD3DX12_EXISTING_COLLECTION_SUBOBJECT" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CD3DX12_EXISTING_COLLECTION_SUBOBJECT
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3dx12_state_object\&.h>\fP
.PP
Inherits \fBCD3DX12_STATE_OBJECT_DESC::SUBOBJECT_HELPER_BASE\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP () noexcept"
.br
.ti -1c
.RI "\fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP (\fBCD3DX12_STATE_OBJECT_DESC\fP &ContainingStateObject)"
.br
.ti -1c
.RI "\fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP (const \fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP &other)=delete"
.br
.ti -1c
.RI "\fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP & \fBoperator=\fP (const \fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP &other)=delete"
.br
.ti -1c
.RI "\fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP (\fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP &&other)=default"
.br
.ti -1c
.RI "\fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP & \fBoperator=\fP (\fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP &&other)=default"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetExistingCollection\fP (\fBID3D12StateObject\fP *pExistingCollection) noexcept"
.br
.ti -1c
.RI "\fBvoid\fP \fBDefineExport\fP (LPCWSTR Name, LPCWSTR ExportToRename=nullptr, \fBD3D12_EXPORT_FLAGS\fP \fBFlags\fP=\fBD3D12_EXPORT_FLAG_NONE\fP)"
.br
.ti -1c
.RI "template<size_t N> \fBvoid\fP \fBDefineExports\fP (LPCWSTR(&Exports)[\fBN\fP])"
.br
.ti -1c
.RI "\fBvoid\fP \fBDefineExports\fP (const LPCWSTR *Exports, UINT \fBN\fP)"
.br
.ti -1c
.RI "\fBD3D12_STATE_SUBOBJECT_TYPE\fP \fBType\fP () const noexcept override"
.br
.ti -1c
.RI "\fBoperator const D3D12_EXISTING_COLLECTION_DESC &\fP () const noexcept"
.br
.in -1c

Public Member Functions inherited from \fBCD3DX12_STATE_OBJECT_DESC::SUBOBJECT_HELPER_BASE\fP
.in +1c
.ti -1c
.RI "\fBSUBOBJECT_HELPER_BASE\fP () noexcept"
.br
.ti -1c
.RI "virtual \fB~SUBOBJECT_HELPER_BASE\fP ()=default"
.br
.ti -1c
.RI "\fBSUBOBJECT_HELPER_BASE\fP (const \fBSUBOBJECT_HELPER_BASE\fP &other)=delete"
.br
.ti -1c
.RI "\fBSUBOBJECT_HELPER_BASE\fP & \fBoperator=\fP (const \fBSUBOBJECT_HELPER_BASE\fP &other)=delete"
.br
.ti -1c
.RI "\fBSUBOBJECT_HELPER_BASE\fP (\fBSUBOBJECT_HELPER_BASE\fP &&other)=default"
.br
.ti -1c
.RI "\fBSUBOBJECT_HELPER_BASE\fP & \fBoperator=\fP (\fBSUBOBJECT_HELPER_BASE\fP &&other)=default"
.br
.ti -1c
.RI "\fBvoid\fP \fBAddToStateObject\fP (\fBCD3DX12_STATE_OBJECT_DESC\fP &ContainingStateObject)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBFinalize\fP ()"
.br
.ti -1c
.RI "\fBoperator const D3D12_STATE_SUBOBJECT &\fP () const noexcept"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBCD3DX12_STATE_OBJECT_DESC::SUBOBJECT_HELPER_BASE\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP \fBInit\fP () noexcept"
.br
.in -1c

Protected Attributes inherited from \fBCD3DX12_STATE_OBJECT_DESC::SUBOBJECT_HELPER_BASE\fP
.in +1c
.ti -1c
.RI "\fBD3D12_STATE_SUBOBJECT\fP * \fBm_pSubobject\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CD3DX12_EXISTING_COLLECTION_SUBOBJECT::CD3DX12_EXISTING_COLLECTION_SUBOBJECT ()\fR [inline]\fP, \fR [noexcept]\fP"

.SS "CD3DX12_EXISTING_COLLECTION_SUBOBJECT::CD3DX12_EXISTING_COLLECTION_SUBOBJECT (\fBCD3DX12_STATE_OBJECT_DESC\fP & ContainingStateObject)\fR [inline]\fP"

.SS "CD3DX12_EXISTING_COLLECTION_SUBOBJECT::CD3DX12_EXISTING_COLLECTION_SUBOBJECT (const \fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP & other)\fR [delete]\fP"

.SS "CD3DX12_EXISTING_COLLECTION_SUBOBJECT::CD3DX12_EXISTING_COLLECTION_SUBOBJECT (\fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP && other)\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP CD3DX12_EXISTING_COLLECTION_SUBOBJECT::DefineExport (LPCWSTR Name, LPCWSTR ExportToRename = \fRnullptr\fP, \fBD3D12_EXPORT_FLAGS\fP Flags = \fR\fBD3D12_EXPORT_FLAG_NONE\fP\fP)\fR [inline]\fP"

.SS "\fBvoid\fP CD3DX12_EXISTING_COLLECTION_SUBOBJECT::DefineExports (const LPCWSTR * Exports, UINT N)\fR [inline]\fP"

.SS "template<size_t N> \fBvoid\fP CD3DX12_EXISTING_COLLECTION_SUBOBJECT::DefineExports (LPCWSTR(&) Exports[N])\fR [inline]\fP"

.SS "CD3DX12_EXISTING_COLLECTION_SUBOBJECT::operator const \fBD3D12_EXISTING_COLLECTION_DESC\fP & () const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "\fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP & CD3DX12_EXISTING_COLLECTION_SUBOBJECT::operator= (\fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP && other)\fR [default]\fP"

.SS "\fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP & CD3DX12_EXISTING_COLLECTION_SUBOBJECT::operator= (const \fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP & other)\fR [delete]\fP"

.SS "\fBvoid\fP CD3DX12_EXISTING_COLLECTION_SUBOBJECT::SetExistingCollection (\fBID3D12StateObject\fP * pExistingCollection)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "\fBD3D12_STATE_SUBOBJECT_TYPE\fP CD3DX12_EXISTING_COLLECTION_SUBOBJECT::Type () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP, \fR [noexcept]\fP"

.PP
Implements \fBCD3DX12_STATE_OBJECT_DESC::SUBOBJECT_HELPER_BASE\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
