.TH "CD3DX12_RT_FORMAT_ARRAY" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CD3DX12_RT_FORMAT_ARRAY
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3dx12_core\&.h>\fP
.PP
Inherits \fBD3D12_RT_FORMAT_ARRAY\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCD3DX12_RT_FORMAT_ARRAY\fP ()=default"
.br
.ti -1c
.RI "\fBCD3DX12_RT_FORMAT_ARRAY\fP (const \fBD3D12_RT_FORMAT_ARRAY\fP &o) noexcept"
.br
.ti -1c
.RI "\fBCD3DX12_RT_FORMAT_ARRAY\fP (_In_reads_(NumFormats) const \fBDXGI_FORMAT\fP *pFormats, UINT NumFormats) noexcept"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBD3D12_RT_FORMAT_ARRAY\fP
.in +1c
.ti -1c
.RI "\fBDXGI_FORMAT\fP \fBRTFormats\fP [\fBD3D12_SIMULTANEOUS_RENDER_TARGET_COUNT\fP]"
.br
.ti -1c
.RI "UINT \fBNumRenderTargets\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CD3DX12_RT_FORMAT_ARRAY::CD3DX12_RT_FORMAT_ARRAY ()\fR [default]\fP"

.SS "CD3DX12_RT_FORMAT_ARRAY::CD3DX12_RT_FORMAT_ARRAY (const \fBD3D12_RT_FORMAT_ARRAY\fP & o)\fR [inline]\fP, \fR [explicit]\fP, \fR [noexcept]\fP"

.SS "CD3DX12_RT_FORMAT_ARRAY::CD3DX12_RT_FORMAT_ARRAY (_In_reads_(NumFormats) const \fBDXGI_FORMAT\fP * pFormats, UINT NumFormats)\fR [inline]\fP, \fR [explicit]\fP, \fR [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
