.TH "CD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT< InnerStructType, Type, DefaultArg >" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT< InnerStructType, Type, DefaultArg >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3dx12_pipeline_state_stream\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT\fP () noexcept"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT\fP (InnerStructType const &\fBi\fP) noexcept"
.br
.ti -1c
.RI "\fBCD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT\fP & \fBoperator=\fP (InnerStructType const &\fBi\fP) noexcept"
.br
.ti -1c
.RI "\fBoperator InnerStructType const &\fP () const noexcept"
.br
.ti -1c
.RI "\fBoperator InnerStructType &\fP () noexcept"
.br
.ti -1c
.RI "InnerStructType * \fBoperator&\fP () noexcept"
.br
.ti -1c
.RI "InnerStructType const * \fBoperator&\fP () const noexcept"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename InnerStructType , \fBD3D12_PIPELINE_STATE_SUBOBJECT_TYPE\fP Type, typename DefaultArg  = InnerStructType> \fBCD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT\fP< InnerStructType, Type, DefaultArg >\fB::CD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT\fP ()\fR [inline]\fP, \fR [noexcept]\fP"

.SS "template<typename InnerStructType , \fBD3D12_PIPELINE_STATE_SUBOBJECT_TYPE\fP Type, typename DefaultArg  = InnerStructType> \fBCD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT\fP< InnerStructType, Type, DefaultArg >\fB::CD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT\fP (InnerStructType const & i)\fR [inline]\fP, \fR [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename InnerStructType , \fBD3D12_PIPELINE_STATE_SUBOBJECT_TYPE\fP Type, typename DefaultArg  = InnerStructType> \fBCD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT\fP< InnerStructType, Type, DefaultArg >::operator InnerStructType & ()\fR [inline]\fP, \fR [noexcept]\fP"

.SS "template<typename InnerStructType , \fBD3D12_PIPELINE_STATE_SUBOBJECT_TYPE\fP Type, typename DefaultArg  = InnerStructType> \fBCD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT\fP< InnerStructType, Type, DefaultArg >::operator InnerStructType const & () const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "template<typename InnerStructType , \fBD3D12_PIPELINE_STATE_SUBOBJECT_TYPE\fP Type, typename DefaultArg  = InnerStructType> InnerStructType const  * \fBCD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT\fP< InnerStructType, Type, DefaultArg >::operator& () const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "template<typename InnerStructType , \fBD3D12_PIPELINE_STATE_SUBOBJECT_TYPE\fP Type, typename DefaultArg  = InnerStructType> InnerStructType * \fBCD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT\fP< InnerStructType, Type, DefaultArg >::operator& ()\fR [inline]\fP, \fR [noexcept]\fP"

.SS "template<typename InnerStructType , \fBD3D12_PIPELINE_STATE_SUBOBJECT_TYPE\fP Type, typename DefaultArg  = InnerStructType> \fBCD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT\fP & \fBCD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT\fP< InnerStructType, Type, DefaultArg >::operator= (InnerStructType const & i)\fR [inline]\fP, \fR [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
