.TH "CD3DX12_HEAP_PROPERTIES" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CD3DX12_HEAP_PROPERTIES
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3dx12_core\&.h>\fP
.PP
Inherits \fBD3D12_HEAP_PROPERTIES\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCD3DX12_HEAP_PROPERTIES\fP ()=default"
.br
.ti -1c
.RI "\fBCD3DX12_HEAP_PROPERTIES\fP (const \fBD3D12_HEAP_PROPERTIES\fP &o) noexcept"
.br
.ti -1c
.RI "\fBCD3DX12_HEAP_PROPERTIES\fP (\fBD3D12_CPU_PAGE_PROPERTY\fP cpuPageProperty, \fBD3D12_MEMORY_POOL\fP memoryPoolPreference, UINT creationNodeMask=1, UINT nodeMask=1) noexcept"
.br
.ti -1c
.RI "\fBCD3DX12_HEAP_PROPERTIES\fP (\fBD3D12_HEAP_TYPE\fP \fBtype\fP, UINT creationNodeMask=1, UINT nodeMask=1) noexcept"
.br
.ti -1c
.RI "bool \fBIsCPUAccessible\fP () const noexcept"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBD3D12_HEAP_PROPERTIES\fP
.in +1c
.ti -1c
.RI "\fBD3D12_HEAP_TYPE\fP \fBType\fP"
.br
.ti -1c
.RI "\fBD3D12_CPU_PAGE_PROPERTY\fP \fBCPUPageProperty\fP"
.br
.ti -1c
.RI "\fBD3D12_MEMORY_POOL\fP \fBMemoryPoolPreference\fP"
.br
.ti -1c
.RI "UINT \fBCreationNodeMask\fP"
.br
.ti -1c
.RI "UINT \fBVisibleNodeMask\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CD3DX12_HEAP_PROPERTIES::CD3DX12_HEAP_PROPERTIES ()\fR [default]\fP"

.SS "CD3DX12_HEAP_PROPERTIES::CD3DX12_HEAP_PROPERTIES (const \fBD3D12_HEAP_PROPERTIES\fP & o)\fR [inline]\fP, \fR [explicit]\fP, \fR [noexcept]\fP"

.SS "CD3DX12_HEAP_PROPERTIES::CD3DX12_HEAP_PROPERTIES (\fBD3D12_CPU_PAGE_PROPERTY\fP cpuPageProperty, \fBD3D12_MEMORY_POOL\fP memoryPoolPreference, UINT creationNodeMask = \fR1\fP, UINT nodeMask = \fR1\fP)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "CD3DX12_HEAP_PROPERTIES::CD3DX12_HEAP_PROPERTIES (\fBD3D12_HEAP_TYPE\fP type, UINT creationNodeMask = \fR1\fP, UINT nodeMask = \fR1\fP)\fR [inline]\fP, \fR [explicit]\fP, \fR [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool CD3DX12_HEAP_PROPERTIES::IsCPUAccessible () const\fR [inline]\fP, \fR [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
