.TH "CD3DX12_RESOURCE_ALLOCATION_INFO" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CD3DX12_RESOURCE_ALLOCATION_INFO
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3dx12_core\&.h>\fP
.PP
Inherits \fBD3D12_RESOURCE_ALLOCATION_INFO\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCD3DX12_RESOURCE_ALLOCATION_INFO\fP ()=default"
.br
.ti -1c
.RI "\fBCD3DX12_RESOURCE_ALLOCATION_INFO\fP (const \fBD3D12_RESOURCE_ALLOCATION_INFO\fP &o) noexcept"
.br
.ti -1c
.RI "\fBCD3DX12_RESOURCE_ALLOCATION_INFO\fP (UINT64 \fBsize\fP, UINT64 alignment) noexcept"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBD3D12_RESOURCE_ALLOCATION_INFO\fP
.in +1c
.ti -1c
.RI "UINT64 \fBSizeInBytes\fP"
.br
.ti -1c
.RI "UINT64 \fBAlignment\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CD3DX12_RESOURCE_ALLOCATION_INFO::CD3DX12_RESOURCE_ALLOCATION_INFO ()\fR [default]\fP"

.SS "CD3DX12_RESOURCE_ALLOCATION_INFO::CD3DX12_RESOURCE_ALLOCATION_INFO (const \fBD3D12_RESOURCE_ALLOCATION_INFO\fP & o)\fR [inline]\fP, \fR [explicit]\fP, \fR [noexcept]\fP"

.SS "CD3DX12_RESOURCE_ALLOCATION_INFO::CD3DX12_RESOURCE_ALLOCATION_INFO (UINT64 size, UINT64 alignment)\fR [inline]\fP, \fR [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
