.TH "BLINK/source/coff_reader.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLINK/source/coff_reader.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'blink\&.hpp'\fP
.br
\fR#include 'coff_reader\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscoped_handle\fP \fBopen_coff_file\fP (const std::filesystem::path &path, \fBCOFF_HEADER\fP &header)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBscoped_handle\fP open_coff_file (const std::filesystem::path & path, \fBCOFF_HEADER\fP & header)"
Copyright (C) 2019 Patrick Mours\&. All rights reserved\&. License: https://github.com/crosire/blink#license 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
