.TH "adhed/glm/gtx/color_space_YCoCg.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/color_space_YCoCg.inl
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBglm::compute_YCoCgR< T, Q, isInteger >\fP"
.br
.ti -1c
.RI "class \fBglm::compute_YCoCgR< T, Q, true >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::rgb2YCoCg\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBrgbColor\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::YCoCg2rgb\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &YCoCgColor)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::rgb2YCoCgR\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBrgbColor\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::YCoCgR2rgb\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &YCoCgRColor)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
