.TH "adhed/glm/gtx/color_space_YCoCg.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/color_space_YCoCg.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./glm\&.hpp'\fP
.br
\fR#include 'color_space_YCoCg\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::rgb2YCoCg\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBrgbColor\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::YCoCg2rgb\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &YCoCgColor)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::rgb2YCoCgR\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBrgbColor\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::YCoCgR2rgb\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &YCoCgColor)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_color_space_YCoCg\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
