.TH "adhed/glm/gtx/color_space.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/color_space.inl
.SH SYNOPSIS
.br
.PP
\fR#include <glm/ext/scalar_relational\&.hpp>\fP
.br
\fR#include <glm/ext/scalar_constants\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::rgbColor\fP (const \fBvec\fP< 3, \fBT\fP, \fBQ\fP > &\fBhsvColor\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::hsvColor\fP (const \fBvec\fP< 3, \fBT\fP, \fBQ\fP > &\fBrgbColor\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::saturation\fP (\fBT\fP const s)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::saturation\fP (const \fBT\fP s, const \fBvec\fP< 3, \fBT\fP, \fBQ\fP > &\fBcolor\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::saturation\fP (const \fBT\fP s, const \fBvec\fP< 4, \fBT\fP, \fBQ\fP > &\fBcolor\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::luminosity\fP (const \fBvec\fP< 3, \fBT\fP, \fBQ\fP > &\fBcolor\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
