.TH "adhed/glm/gtx/color_encoding.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/color_encoding.inl
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::convertLinearSRGBToD65XYZ\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &ColorLinearSRGB)"
.br
.RI "Convert a linear sRGB color to D65 YUV\&. "
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::convertLinearSRGBToD50XYZ\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &ColorLinearSRGB)"
.br
.RI "Convert a linear sRGB color to D50 YUV\&. "
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::convertD65XYZToLinearSRGB\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &ColorD65XYZ)"
.br
.RI "Convert a D65 YUV color to linear sRGB\&. "
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::convertD65XYZToD50XYZ\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &ColorD65XYZ)"
.br
.RI "Convert a D65 YUV color to D50 YUV\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
