.TH "adhed/assimp/commonMetaData.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/assimp/commonMetaData.h \- Defines a set of common scene metadata keys\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAI_COMMONMETADATA_H_INC\fP"
.br
.ti -1c
.RI "#define \fBAI_METADATA_SOURCE_FORMAT\fP   'SourceAsset_Format'"
.br
.ti -1c
.RI "#define \fBAI_METADATA_SOURCE_FORMAT_VERSION\fP   'SourceAsset_FormatVersion'"
.br
.ti -1c
.RI "#define \fBAI_METADATA_SOURCE_GENERATOR\fP   'SourceAsset_Generator'"
.br
.ti -1c
.RI "#define \fBAI_METADATA_SOURCE_COPYRIGHT\fP   'SourceAsset_Copyright'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines a set of common scene metadata keys\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AI_COMMONMETADATA_H_INC"

.SS "#define AI_METADATA_SOURCE_COPYRIGHT   'SourceAsset_Copyright'"
Scene metadata holding the source asset copyright statement, if available\&. Not all formats add this metadata\&. 
.SS "#define AI_METADATA_SOURCE_FORMAT   'SourceAsset_Format'"
Scene metadata holding the name of the importer which loaded the source asset\&. This is always present if the scene was created from an imported asset\&. 
.SS "#define AI_METADATA_SOURCE_FORMAT_VERSION   'SourceAsset_FormatVersion'"
Scene metadata holding the version of the source asset as a string, if available\&. Not all formats add this metadata\&. 
.SS "#define AI_METADATA_SOURCE_GENERATOR   'SourceAsset_Generator'"
Scene metadata holding the name of the software which generated the source asset, if available\&. Not all formats add this metadata\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
