.TH "COMPONENTS::_Mesh" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
COMPONENTS::_Mesh
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MESH\&.h>\fP
.PP
Inherits \fBCORE::Behaviour\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_Mesh\fP ()"
.br
.ti -1c
.RI "\fB_Mesh\fP (const char *pth)"
.br
.ti -1c
.RI "\fB_Mesh\fP (std::shared_ptr< \fBPAIN::Model\fP > model)"
.br
.ti -1c
.RI "void \fBSetModel\fP (std::shared_ptr< \fBPAIN::Model\fP > m)"
.br
.ti -1c
.RI "void \fBUpdate\fP () override"
.br
.ti -1c
.RI "void \fBAwake\fP () override"
.br
.ti -1c
.RI "void \fBStart\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBCORE::Behaviour\fP
.in +1c
.ti -1c
.RI "\fBBehaviour\fP ()"
.br
.ti -1c
.RI "\fBBehaviour\fP (\fBGameObject\fP *oobj, std::shared_ptr< \fBCORE::Behaviour\fP > trans)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGameObject\fP * \fBoobj\fP = nullptr"
.br
.ti -1c
.RI "std::shared_ptr< \fBPAIN::Model\fP > \fBModel\fP"
.br
.in -1c

Public Attributes inherited from \fBCORE::Behaviour\fP
.in +1c
.ti -1c
.RI "\fBGameObject\fP * \fBgameobject\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBTransform\fP > \fBTRANSFORM\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBCORE::Behaviour\fP > \fBtransf\fP"
.br
.ti -1c
.RI "UUID \fBuuID\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static UUID \fBUUID\fP = GUID_NULL"
.br
.in -1c

Static Public Attributes inherited from \fBCORE::Behaviour\fP
.in +1c
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBCORE::Behaviour\fP > > \fBobjectss\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBBehaviour\fP > > \fBbehaviours\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBBehaviour\fP > > \fBAWAKES\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBBehaviour\fP > > \fBStarts\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBBehaviour\fP > > \fBParallel_Updates\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBCORE::Behaviour\fP
.in +1c
.ti -1c
.RI "static void \fBupdateAll\fP ()"
.br
.ti -1c
.RI "static void \fBupdateAllAWAKE\fP ()"
.br
.ti -1c
.RI "static void \fBupdateAllSTART\fP ()"
.br
.ti -1c
.RI "static void \fBupdateallParallel\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBMESH\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "COMPONENTS::_Mesh::_Mesh ()"

.PP
Definition at line \fB3\fP of file \fBMESH\&.cpp\fP\&.
.SS "COMPONENTS::_Mesh::_Mesh (const char * pth)"

.PP
Definition at line \fB5\fP of file \fBMESH\&.cpp\fP\&.
.SS "COMPONENTS::_Mesh::_Mesh (std::shared_ptr< \fBPAIN::Model\fP > model)"

.PP
Definition at line \fB12\fP of file \fBMESH\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void COMPONENTS::_Mesh::Awake ()\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBCORE::Behaviour\fP\&.
.PP
Definition at line \fB22\fP of file \fBMESH\&.cpp\fP\&.
.SS "void COMPONENTS::_Mesh::SetModel (std::shared_ptr< \fBPAIN::Model\fP > m)"

.PP
Definition at line \fB16\fP of file \fBMESH\&.cpp\fP\&.
.SS "void COMPONENTS::_Mesh::Start ()\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBCORE::Behaviour\fP\&.
.PP
Definition at line \fB24\fP of file \fBMESH\&.cpp\fP\&.
.SS "void COMPONENTS::_Mesh::Update ()\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBCORE::Behaviour\fP\&.
.PP
Definition at line \fB20\fP of file \fBMESH\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::shared_ptr<\fBPAIN::Model\fP> COMPONENTS::_Mesh::Model"

.PP
Definition at line \fB16\fP of file \fBMESH\&.h\fP\&.
.SS "\fBGameObject\fP* COMPONENTS::_Mesh::oobj = nullptr"

.PP
Definition at line \fB15\fP of file \fBMESH\&.h\fP\&.
.SS "GUID COMPONENTS::_Mesh::UUID = GUID_NULL\fR [static]\fP"

.PP
Definition at line \fB14\fP of file \fBMESH\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
