.TH "adhed/glm/detail/compute_vector_decl.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/detail/compute_vector_decl.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <functional>\fP
.br
\fR#include '_vectorize\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBglm::detail::compute_vec_add< L, T, Q, UseSimd >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_sub< L, T, Q, UseSimd >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_mul< L, T, Q, UseSimd >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_div< L, T, Q, UseSimd >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_mod< L, T, Q, UseSimd >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_splat< L, T, Q, UseSimd >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_and< L, T, Q, IsInt, Size, UseSimd >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_or< L, T, Q, IsInt, Size, UseSimd >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_xor< L, T, Q, IsInt, Size, UseSimd >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_shift_left< L, T, Q, IsInt, Size, UseSimd >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_shift_right< L, T, Q, IsInt, Size, UseSimd >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_equal< L, T, Q, IsInt, Size, UseSimd >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_nequal< L, T, Q, IsInt, Size, UseSimd >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_bitwise_not< L, T, Q, IsInt, Size, UseSimd >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_add< L, T, Q, false >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_sub< L, T, Q, false >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_mul< L, T, Q, false >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_div< L, T, Q, false >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_mod< L, T, Q, false >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_and< L, T, Q, IsInt, Size, false >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_or< L, T, Q, IsInt, Size, false >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_xor< L, T, Q, IsInt, Size, false >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_shift_left< L, T, Q, IsInt, Size, false >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_shift_right< L, T, Q, IsInt, Size, false >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_equal< L, T, Q, IsInt, Size, false >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_nequal< L, T, Q, IsInt, Size, false >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec_bitwise_not< L, T, Q, IsInt, Size, false >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.ti -1c
.RI "namespace \fBglm::detail\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
