.TH "adhed/glm/gtx/component_wise.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/component_wise.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./detail/setup\&.hpp'\fP
.br
\fR#include '\&.\&./detail/qualifier\&.hpp'\fP
.br
\fR#include 'component_wise\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename floatType , \fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, floatType, \fBQ\fP > \fBglm::compNormalize\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename floatType , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::compScale\fP (\fBvec\fP< \fBL\fP, floatType, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType::value_type \fBglm::compAdd\fP (genType const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType::value_type \fBglm::compMul\fP (genType const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType::value_type \fBglm::compMin\fP (genType const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType::value_type \fBglm::compMax\fP (genType const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType::value_type \fBglm::fcompMin\fP (genType const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType::value_type \fBglm::fcompMax\fP (genType const &\fBv\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_component_wise\fP
.PP
\fBDate\fP
.RS 4
2007-05-21 / 2011-06-07 
.RE
.PP
\fBAuthor\fP
.RS 4
Christophe Riccio
.RE
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
