.TH "adhed/glm/detail/compute_common.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/detail/compute_common.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'setup\&.hpp'\fP
.br
\fR#include <limits>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBglm::detail::compute_abs< genFIType, bool >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_abs< genFIType, true >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_abs< genFIType, false >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.ti -1c
.RI "namespace \fBglm::detail\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
