.TH "adhed/libbacktrace/config.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/libbacktrace/config.h
.SH SYNOPSIS
.br
.PP
\fR#include <limits\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBACKTRACE_ELF_SIZE\fP   32"
.br
.ti -1c
.RI "#define \fBHAVE_DLFCN_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FCNTL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_INTTYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LSTAT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_READLINK\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_DL_ITERATE_PHDR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATOMIC_FUNCTIONS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_DECL_STRNLEN\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BACKTRACE_ELF_SIZE   32"

.SS "#define HAVE_ATOMIC_FUNCTIONS   1"

.SS "#define HAVE_DECL_STRNLEN   1"

.SS "#define HAVE_DL_ITERATE_PHDR   1"

.SS "#define HAVE_DLFCN_H   1"

.SS "#define HAVE_FCNTL   1"

.SS "#define HAVE_INTTYPES_H   1"

.SS "#define HAVE_LSTAT   1"

.SS "#define HAVE_READLINK   1"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
