.TH "CORE::InstructionSet" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORE::InstructionSet \- contains cpu secs  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <C_CPUFEATURES\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInstructionSet_Internal\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBVendor\fP (void)"
.br
.ti -1c
.RI "static std::string \fBBrand\fP (void)"
.br
.ti -1c
.RI "static bool \fBSSE3\fP (void)"
.br
.ti -1c
.RI "static bool \fBPCLMULQDQ\fP (void)"
.br
.ti -1c
.RI "static bool \fBMONITOR\fP (void)"
.br
.ti -1c
.RI "static bool \fBSSSE3\fP (void)"
.br
.ti -1c
.RI "static bool \fBFMA\fP (void)"
.br
.ti -1c
.RI "static bool \fBCMPXCHG16B\fP (void)"
.br
.ti -1c
.RI "static bool \fBSSE41\fP (void)"
.br
.ti -1c
.RI "static bool \fBSSE42\fP (void)"
.br
.ti -1c
.RI "static bool \fBMOVBE\fP (void)"
.br
.ti -1c
.RI "static bool \fBPOPCNT\fP (void)"
.br
.ti -1c
.RI "static bool \fBAES\fP (void)"
.br
.ti -1c
.RI "static bool \fBXSAVE\fP (void)"
.br
.ti -1c
.RI "static bool \fBOSXSAVE\fP (void)"
.br
.ti -1c
.RI "static bool \fBAVX\fP (void)"
.br
.ti -1c
.RI "static bool \fBF16C\fP (void)"
.br
.ti -1c
.RI "static bool \fBRDRAND\fP (void)"
.br
.ti -1c
.RI "static bool \fBMSR\fP (void)"
.br
.ti -1c
.RI "static bool \fBCX8\fP (void)"
.br
.ti -1c
.RI "static bool \fBSEP\fP (void)"
.br
.ti -1c
.RI "static bool \fBCMOV\fP (void)"
.br
.ti -1c
.RI "static bool \fBCLFSH\fP (void)"
.br
.ti -1c
.RI "static bool \fBMMX\fP (void)"
.br
.ti -1c
.RI "static bool \fBFXSR\fP (void)"
.br
.ti -1c
.RI "static bool \fBSSE\fP (void)"
.br
.ti -1c
.RI "static bool \fBSSE2\fP (void)"
.br
.ti -1c
.RI "static bool \fBFSGSBASE\fP (void)"
.br
.ti -1c
.RI "static bool \fBBMI1\fP (void)"
.br
.ti -1c
.RI "static bool \fBHLE\fP (void)"
.br
.ti -1c
.RI "static bool \fBAVX2\fP (void)"
.br
.ti -1c
.RI "static bool \fBBMI2\fP (void)"
.br
.ti -1c
.RI "static bool \fBERMS\fP (void)"
.br
.ti -1c
.RI "static bool \fBINVPCID\fP (void)"
.br
.ti -1c
.RI "static bool \fBRTM\fP (void)"
.br
.ti -1c
.RI "static bool \fBAVX512F\fP (void)"
.br
.ti -1c
.RI "static bool \fBRDSEED\fP (void)"
.br
.ti -1c
.RI "static bool \fBADX\fP (void)"
.br
.ti -1c
.RI "static bool \fBAVX512PF\fP (void)"
.br
.ti -1c
.RI "static bool \fBAVX512ER\fP (void)"
.br
.ti -1c
.RI "static bool \fBAVX512CD\fP (void)"
.br
.ti -1c
.RI "static bool \fBSHA\fP (void)"
.br
.ti -1c
.RI "static bool \fBPREFETCHWT1\fP (void)"
.br
.ti -1c
.RI "static bool \fBLAHF\fP (void)"
.br
.ti -1c
.RI "static bool \fBLZCNT\fP (void)"
.br
.ti -1c
.RI "static bool \fBABM\fP (void)"
.br
.ti -1c
.RI "static bool \fBSSE4a\fP (void)"
.br
.ti -1c
.RI "static bool \fBXOP\fP (void)"
.br
.ti -1c
.RI "static bool \fBTBM\fP (void)"
.br
.ti -1c
.RI "static bool \fBSYSCALL\fP (void)"
.br
.ti -1c
.RI "static bool \fBMMXEXT\fP (void)"
.br
.ti -1c
.RI "static bool \fBRDTSCP\fP (void)"
.br
.ti -1c
.RI "static bool \fB_3DNOWEXT\fP (void)"
.br
.ti -1c
.RI "static bool \fB_3DNOW\fP (void)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBInstructionSet_Internal\fP \fBCPU_Rep\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains cpu secs 
.PP
Definition at line \fB9\fP of file \fBC_CPUFEATURES\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CORE::InstructionSet::_3DNOW (void )\fR [static]\fP"

.PP
Definition at line \fB111\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
111 { return CPU_Rep\&.isAMD_ && CPU_Rep\&.f_81_EDX_[31]; }
.PP
.fi

.SS "bool CORE::InstructionSet::_3DNOWEXT (void )\fR [static]\fP"

.PP
Definition at line \fB109\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
109 { return CPU_Rep\&.isAMD_ && CPU_Rep\&.f_81_EDX_[30]; }
.PP
.fi

.SS "bool CORE::InstructionSet::ABM (void )\fR [static]\fP"

.PP
Definition at line \fB95\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
95 { return CPU_Rep\&.isAMD_ && CPU_Rep\&.f_81_ECX_[5]; }
.PP
.fi

.SS "bool CORE::InstructionSet::ADX (void )\fR [static]\fP"

.PP
Definition at line \fB79\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
79 { return CPU_Rep\&.f_7_EBX_[19]; }
.PP
.fi

.SS "bool CORE::InstructionSet::AES (void )\fR [static]\fP"

.PP
Definition at line \fB29\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
29 { return CPU_Rep\&.f_1_ECX_[25]; }
.PP
.fi

.SS "bool CORE::InstructionSet::AVX (void )\fR [static]\fP"

.PP
Definition at line \fB35\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
35 { return CPU_Rep\&.f_1_ECX_[28]; }
.PP
.fi

.PP
Referenced by \fBCORE::Startup::Configure_Startup()\fP\&.
.SS "bool CORE::InstructionSet::AVX2 (void )\fR [static]\fP"

.PP
Definition at line \fB65\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
65 { return CPU_Rep\&.f_7_EBX_[5]; }
.PP
.fi

.PP
Referenced by \fBCORE::Startup::Configure_Startup()\fP\&.
.SS "bool CORE::InstructionSet::AVX512CD (void )\fR [static]\fP"

.PP
Definition at line \fB85\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
85 { return CPU_Rep\&.f_7_EBX_[28]; }
.PP
.fi

.SS "bool CORE::InstructionSet::AVX512ER (void )\fR [static]\fP"

.PP
Definition at line \fB83\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
83 { return CPU_Rep\&.f_7_EBX_[27]; }
.PP
.fi

.SS "bool CORE::InstructionSet::AVX512F (void )\fR [static]\fP"

.PP
Definition at line \fB75\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
75 { return CPU_Rep\&.f_7_EBX_[16]; }
.PP
.fi

.SS "bool CORE::InstructionSet::AVX512PF (void )\fR [static]\fP"

.PP
Definition at line \fB81\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
81 { return CPU_Rep\&.f_7_EBX_[26]; }
.PP
.fi

.SS "bool CORE::InstructionSet::BMI1 (void )\fR [static]\fP"

.PP
Definition at line \fB61\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
61 { return CPU_Rep\&.f_7_EBX_[3]; }
.PP
.fi

.SS "bool CORE::InstructionSet::BMI2 (void )\fR [static]\fP"

.PP
Definition at line \fB67\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
67 { return CPU_Rep\&.f_7_EBX_[8]; }
.PP
.fi

.SS "std::string CORE::InstructionSet::Brand (void )\fR [static]\fP"

.PP
Definition at line \fB9\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
9 { return CPU_Rep\&.brand_; }
.PP
.fi

.SS "bool CORE::InstructionSet::CLFSH (void )\fR [static]\fP"

.PP
Definition at line \fB49\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
49 { return CPU_Rep\&.f_1_EDX_[19]; }
.PP
.fi

.SS "bool CORE::InstructionSet::CMOV (void )\fR [static]\fP"

.PP
Definition at line \fB47\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
47 { return CPU_Rep\&.f_1_EDX_[15]; }
.PP
.fi

.SS "bool CORE::InstructionSet::CMPXCHG16B (void )\fR [static]\fP"

.PP
Definition at line \fB19\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
19 { return CPU_Rep\&.f_1_ECX_[13]; }
.PP
.fi

.SS "bool CORE::InstructionSet::CX8 (void )\fR [static]\fP"

.PP
Definition at line \fB43\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
43 { return CPU_Rep\&.f_1_EDX_[8]; }
.PP
.fi

.SS "bool CORE::InstructionSet::ERMS (void )\fR [static]\fP"

.PP
Definition at line \fB69\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
69 { return CPU_Rep\&.f_7_EBX_[9]; }
.PP
.fi

.SS "bool CORE::InstructionSet::F16C (void )\fR [static]\fP"

.PP
Definition at line \fB37\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
37 { return CPU_Rep\&.f_1_ECX_[29]; }
.PP
.fi

.SS "bool CORE::InstructionSet::FMA (void )\fR [static]\fP"

.PP
Definition at line \fB17\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
17 { return CPU_Rep\&.f_1_ECX_[12]; }
.PP
.fi

.SS "bool CORE::InstructionSet::FSGSBASE (void )\fR [static]\fP"

.PP
Definition at line \fB59\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
59 { return CPU_Rep\&.f_7_EBX_[0]; }
.PP
.fi

.SS "bool CORE::InstructionSet::FXSR (void )\fR [static]\fP"

.PP
Definition at line \fB53\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
53 { return CPU_Rep\&.f_1_EDX_[24]; }
.PP
.fi

.SS "bool CORE::InstructionSet::HLE (void )\fR [static]\fP"

.PP
Definition at line \fB63\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
63 { return CPU_Rep\&.isIntel_ && CPU_Rep\&.f_7_EBX_[4]; }
.PP
.fi

.SS "bool CORE::InstructionSet::INVPCID (void )\fR [static]\fP"

.PP
Definition at line \fB71\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
71 { return CPU_Rep\&.f_7_EBX_[10]; }
.PP
.fi

.SS "bool CORE::InstructionSet::LAHF (void )\fR [static]\fP"

.PP
Definition at line \fB91\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
91 { return CPU_Rep\&.f_81_ECX_[0]; }
.PP
.fi

.SS "bool CORE::InstructionSet::LZCNT (void )\fR [static]\fP"

.PP
Definition at line \fB93\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
93 { return CPU_Rep\&.isIntel_ && CPU_Rep\&.f_81_ECX_[5]; }
.PP
.fi

.SS "bool CORE::InstructionSet::MMX (void )\fR [static]\fP"

.PP
Definition at line \fB51\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
51 { return CPU_Rep\&.f_1_EDX_[23]; }
.PP
.fi

.SS "bool CORE::InstructionSet::MMXEXT (void )\fR [static]\fP"

.PP
Definition at line \fB105\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
105 { return CPU_Rep\&.isAMD_ && CPU_Rep\&.f_81_EDX_[22]; }
.PP
.fi

.SS "bool CORE::InstructionSet::MONITOR (void )\fR [static]\fP"

.PP
Definition at line \fB13\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
13 { return CPU_Rep\&.f_1_ECX_[3]; }
.PP
.fi

.SS "bool CORE::InstructionSet::MOVBE (void )\fR [static]\fP"

.PP
Definition at line \fB25\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
25 { return CPU_Rep\&.f_1_ECX_[22]; }
.PP
.fi

.SS "bool CORE::InstructionSet::MSR (void )\fR [static]\fP"

.PP
Definition at line \fB41\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
41 { return CPU_Rep\&.f_1_EDX_[5]; }
.PP
.fi

.SS "bool CORE::InstructionSet::OSXSAVE (void )\fR [static]\fP"

.PP
Definition at line \fB33\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
33 { return CPU_Rep\&.f_1_ECX_[27]; }
.PP
.fi

.SS "bool CORE::InstructionSet::PCLMULQDQ (void )\fR [static]\fP"

.PP
Definition at line \fB11\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
11 { return CPU_Rep\&.f_1_ECX_[1]; }
.PP
.fi

.SS "bool CORE::InstructionSet::POPCNT (void )\fR [static]\fP"

.PP
Definition at line \fB27\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
27 { return CPU_Rep\&.f_1_ECX_[23]; }
.PP
.fi

.SS "bool CORE::InstructionSet::PREFETCHWT1 (void )\fR [static]\fP"

.PP
Definition at line \fB89\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
89 { return CPU_Rep\&.f_7_ECX_[0]; }
.PP
.fi

.SS "bool CORE::InstructionSet::RDRAND (void )\fR [static]\fP"

.PP
Definition at line \fB39\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
39 { return CPU_Rep\&.f_1_ECX_[30]; }
.PP
.fi

.SS "bool CORE::InstructionSet::RDSEED (void )\fR [static]\fP"

.PP
Definition at line \fB77\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
77 { return CPU_Rep\&.f_7_EBX_[18]; }
.PP
.fi

.SS "bool CORE::InstructionSet::RDTSCP (void )\fR [static]\fP"

.PP
Definition at line \fB107\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
107 { return CPU_Rep\&.isIntel_ && CPU_Rep\&.f_81_EDX_[27]; }
.PP
.fi

.SS "bool CORE::InstructionSet::RTM (void )\fR [static]\fP"

.PP
Definition at line \fB73\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
73 { return CPU_Rep\&.isIntel_ && CPU_Rep\&.f_7_EBX_[11]; }
.PP
.fi

.SS "bool CORE::InstructionSet::SEP (void )\fR [static]\fP"

.PP
Definition at line \fB45\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
45 { return CPU_Rep\&.f_1_EDX_[11]; }
.PP
.fi

.SS "bool CORE::InstructionSet::SHA (void )\fR [static]\fP"

.PP
Definition at line \fB87\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
87 { return CPU_Rep\&.f_7_EBX_[29]; }
.PP
.fi

.SS "bool CORE::InstructionSet::SSE (void )\fR [static]\fP"

.PP
Definition at line \fB55\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
55 { return CPU_Rep\&.f_1_EDX_[25]; }
.PP
.fi

.SS "bool CORE::InstructionSet::SSE2 (void )\fR [static]\fP"

.PP
Definition at line \fB57\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
57 { return CPU_Rep\&.f_1_EDX_[26]; }
.PP
.fi

.SS "static bool CORE::InstructionSet::SSE3 (void )\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB19\fP of file \fBC_CPUFEATURES\&.h\fP\&.
.nf
19 { return CPU_Rep\&.f_1_ECX_[0]; }
.PP
.fi

.PP
References \fBCPU_Rep\fP, and \fBCORE::InstructionSet::InstructionSet_Internal::f_1_ECX_\fP\&.
.SS "bool CORE::InstructionSet::SSE41 (void )\fR [static]\fP"

.PP
Definition at line \fB21\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
21 { return CPU_Rep\&.f_1_ECX_[19]; }
.PP
.fi

.SS "bool CORE::InstructionSet::SSE42 (void )\fR [static]\fP"

.PP
Definition at line \fB23\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
23 { return CPU_Rep\&.f_1_ECX_[20]; }
.PP
.fi

.SS "bool CORE::InstructionSet::SSE4a (void )\fR [static]\fP"

.PP
Definition at line \fB97\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
97 { return CPU_Rep\&.isAMD_ && CPU_Rep\&.f_81_ECX_[6]; }
.PP
.fi

.SS "bool CORE::InstructionSet::SSSE3 (void )\fR [static]\fP"

.PP
Definition at line \fB15\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
15 { return CPU_Rep\&.f_1_ECX_[9]; }
.PP
.fi

.SS "bool CORE::InstructionSet::SYSCALL (void )\fR [static]\fP"

.PP
Definition at line \fB103\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
103 { return CPU_Rep\&.isIntel_ && CPU_Rep\&.f_81_EDX_[11]; }
.PP
.fi

.SS "bool CORE::InstructionSet::TBM (void )\fR [static]\fP"

.PP
Definition at line \fB101\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
101 { return CPU_Rep\&.isAMD_ && CPU_Rep\&.f_81_ECX_[21]; }
.PP
.fi

.SS "std::string CORE::InstructionSet::Vendor (void )\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
7 { return CPU_Rep\&.vendor_; }
.PP
.fi

.PP
References \fBCPU_Rep\fP, and \fBCORE::InstructionSet::InstructionSet_Internal::vendor_\fP\&.
.SS "bool CORE::InstructionSet::XOP (void )\fR [static]\fP"

.PP
Definition at line \fB99\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
99 { return CPU_Rep\&.isAMD_ && CPU_Rep\&.f_81_ECX_[11]; }
.PP
.fi

.SS "bool CORE::InstructionSet::XSAVE (void )\fR [static]\fP"

.PP
Definition at line \fB31\fP of file \fBC_CPUFEATURES\&.cpp\fP\&.
.nf
31 { return CPU_Rep\&.f_1_ECX_[26]; }
.PP
.fi

.SH "Member Data Documentation"
.PP 
.SS "const \fBCORE::InstructionSet::InstructionSet_Internal\fP CORE::InstructionSet::CPU_Rep\fR [static]\fP"

.PP
Definition at line \fB77\fP of file \fBC_CPUFEATURES\&.h\fP\&.
.PP
Referenced by \fBSSE3()\fP, and \fBVendor()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
