.TH "CORE::SYSTEMS" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORE::SYSTEMS
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <STARTUP\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMESSAGES::Message_Bus\fP * \fBBus\fP"
.br
.ti -1c
.RI "bool \fBRender\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static GLFWwindow * \fBwindw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBSTARTUP\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBMESSAGES::Message_Bus\fP* CORE::SYSTEMS::Bus"

.PP
Definition at line \fB18\fP of file \fBSTARTUP\&.h\fP\&.
.SS "bool CORE::SYSTEMS::Render"

.PP
Definition at line \fB19\fP of file \fBSTARTUP\&.h\fP\&.
.SS "GLFWwindow * CORE::SYSTEMS::windw\fR [static]\fP"

.PP
Definition at line \fB17\fP of file \fBSTARTUP\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
