.TH "core_func_matrix" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core_func_matrix \- Matrix functions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBlength_t\fP C, \fBlength_t\fP R, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > \fBglm::inverse\fP (\fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &m)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides GLSL matrix functions\&.
.PP
Include <\fBglm/matrix\&.hpp\fP> to use these core features\&.
.SH "Function Documentation"
.PP 
.SS "template<\fBlength_t\fP C, \fBlength_t\fP R, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > glm::inverse (\fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const & m)"
Return the inverse of a squared matrix\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIC\fP Integer between 1 and 4 included that qualify the number a column 
.br
\fIR\fP Integer between 1 and 4 included that qualify the number a row 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL inverse man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.6 Matrix Functions\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
