.TH "CORE::InstructionSet" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORE::InstructionSet
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CPUFEATURES\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInstructionSet_Internal\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBVendor\fP (void)"
.br
.ti -1c
.RI "static std::string \fBBrand\fP (void)"
.br
.ti -1c
.RI "static bool \fBSSE3\fP (void)"
.br
.ti -1c
.RI "static bool \fBPCLMULQDQ\fP (void)"
.br
.ti -1c
.RI "static bool \fBMONITOR\fP (void)"
.br
.ti -1c
.RI "static bool \fBSSSE3\fP (void)"
.br
.ti -1c
.RI "static bool \fBFMA\fP (void)"
.br
.ti -1c
.RI "static bool \fBCMPXCHG16B\fP (void)"
.br
.ti -1c
.RI "static bool \fBSSE41\fP (void)"
.br
.ti -1c
.RI "static bool \fBSSE42\fP (void)"
.br
.ti -1c
.RI "static bool \fBMOVBE\fP (void)"
.br
.ti -1c
.RI "static bool \fBPOPCNT\fP (void)"
.br
.ti -1c
.RI "static bool \fBAES\fP (void)"
.br
.ti -1c
.RI "static bool \fBXSAVE\fP (void)"
.br
.ti -1c
.RI "static bool \fBOSXSAVE\fP (void)"
.br
.ti -1c
.RI "static bool \fBAVX\fP (void)"
.br
.ti -1c
.RI "static bool \fBF16C\fP (void)"
.br
.ti -1c
.RI "static bool \fBRDRAND\fP (void)"
.br
.ti -1c
.RI "static bool \fBMSR\fP (void)"
.br
.ti -1c
.RI "static bool \fBCX8\fP (void)"
.br
.ti -1c
.RI "static bool \fBSEP\fP (void)"
.br
.ti -1c
.RI "static bool \fBCMOV\fP (void)"
.br
.ti -1c
.RI "static bool \fBCLFSH\fP (void)"
.br
.ti -1c
.RI "static bool \fBMMX\fP (void)"
.br
.ti -1c
.RI "static bool \fBFXSR\fP (void)"
.br
.ti -1c
.RI "static bool \fBSSE\fP (void)"
.br
.ti -1c
.RI "static bool \fBSSE2\fP (void)"
.br
.ti -1c
.RI "static bool \fBFSGSBASE\fP (void)"
.br
.ti -1c
.RI "static bool \fBBMI1\fP (void)"
.br
.ti -1c
.RI "static bool \fBHLE\fP (void)"
.br
.ti -1c
.RI "static bool \fBAVX2\fP (void)"
.br
.ti -1c
.RI "static bool \fBBMI2\fP (void)"
.br
.ti -1c
.RI "static bool \fBERMS\fP (void)"
.br
.ti -1c
.RI "static bool \fBINVPCID\fP (void)"
.br
.ti -1c
.RI "static bool \fBRTM\fP (void)"
.br
.ti -1c
.RI "static bool \fBAVX512F\fP (void)"
.br
.ti -1c
.RI "static bool \fBRDSEED\fP (void)"
.br
.ti -1c
.RI "static bool \fBADX\fP (void)"
.br
.ti -1c
.RI "static bool \fBAVX512PF\fP (void)"
.br
.ti -1c
.RI "static bool \fBAVX512ER\fP (void)"
.br
.ti -1c
.RI "static bool \fBAVX512CD\fP (void)"
.br
.ti -1c
.RI "static bool \fBSHA\fP (void)"
.br
.ti -1c
.RI "static bool \fBPREFETCHWT1\fP (void)"
.br
.ti -1c
.RI "static bool \fBLAHF\fP (void)"
.br
.ti -1c
.RI "static bool \fBLZCNT\fP (void)"
.br
.ti -1c
.RI "static bool \fBABM\fP (void)"
.br
.ti -1c
.RI "static bool \fBSSE4a\fP (void)"
.br
.ti -1c
.RI "static bool \fBXOP\fP (void)"
.br
.ti -1c
.RI "static bool \fBTBM\fP (void)"
.br
.ti -1c
.RI "static bool \fBSYSCALL\fP (void)"
.br
.ti -1c
.RI "static bool \fBMMXEXT\fP (void)"
.br
.ti -1c
.RI "static bool \fBRDTSCP\fP (void)"
.br
.ti -1c
.RI "static bool \fB_3DNOWEXT\fP (void)"
.br
.ti -1c
.RI "static bool \fB_3DNOW\fP (void)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBInstructionSet_Internal\fP \fBCPU_Rep\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBCPUFEATURES\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CORE::InstructionSet::_3DNOW (void )\fR [static]\fP"

.PP
Definition at line \fB110\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::_3DNOWEXT (void )\fR [static]\fP"

.PP
Definition at line \fB108\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::ABM (void )\fR [static]\fP"

.PP
Definition at line \fB94\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::ADX (void )\fR [static]\fP"

.PP
Definition at line \fB78\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::AES (void )\fR [static]\fP"

.PP
Definition at line \fB28\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::AVX (void )\fR [static]\fP"

.PP
Definition at line \fB34\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::AVX2 (void )\fR [static]\fP"

.PP
Definition at line \fB64\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::AVX512CD (void )\fR [static]\fP"

.PP
Definition at line \fB84\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::AVX512ER (void )\fR [static]\fP"

.PP
Definition at line \fB82\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::AVX512F (void )\fR [static]\fP"

.PP
Definition at line \fB74\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::AVX512PF (void )\fR [static]\fP"

.PP
Definition at line \fB80\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::BMI1 (void )\fR [static]\fP"

.PP
Definition at line \fB60\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::BMI2 (void )\fR [static]\fP"

.PP
Definition at line \fB66\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "std::string CORE::InstructionSet::Brand (void )\fR [static]\fP"

.PP
Definition at line \fB8\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::CLFSH (void )\fR [static]\fP"

.PP
Definition at line \fB48\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::CMOV (void )\fR [static]\fP"

.PP
Definition at line \fB46\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::CMPXCHG16B (void )\fR [static]\fP"

.PP
Definition at line \fB18\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::CX8 (void )\fR [static]\fP"

.PP
Definition at line \fB42\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::ERMS (void )\fR [static]\fP"

.PP
Definition at line \fB68\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::F16C (void )\fR [static]\fP"

.PP
Definition at line \fB36\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::FMA (void )\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::FSGSBASE (void )\fR [static]\fP"

.PP
Definition at line \fB58\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::FXSR (void )\fR [static]\fP"

.PP
Definition at line \fB52\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::HLE (void )\fR [static]\fP"

.PP
Definition at line \fB62\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::INVPCID (void )\fR [static]\fP"

.PP
Definition at line \fB70\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::LAHF (void )\fR [static]\fP"

.PP
Definition at line \fB90\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::LZCNT (void )\fR [static]\fP"

.PP
Definition at line \fB92\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::MMX (void )\fR [static]\fP"

.PP
Definition at line \fB50\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::MMXEXT (void )\fR [static]\fP"

.PP
Definition at line \fB104\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::MONITOR (void )\fR [static]\fP"

.PP
Definition at line \fB12\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::MOVBE (void )\fR [static]\fP"

.PP
Definition at line \fB24\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::MSR (void )\fR [static]\fP"

.PP
Definition at line \fB40\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::OSXSAVE (void )\fR [static]\fP"

.PP
Definition at line \fB32\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::PCLMULQDQ (void )\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::POPCNT (void )\fR [static]\fP"

.PP
Definition at line \fB26\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::PREFETCHWT1 (void )\fR [static]\fP"

.PP
Definition at line \fB88\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::RDRAND (void )\fR [static]\fP"

.PP
Definition at line \fB38\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::RDSEED (void )\fR [static]\fP"

.PP
Definition at line \fB76\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::RDTSCP (void )\fR [static]\fP"

.PP
Definition at line \fB106\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::RTM (void )\fR [static]\fP"

.PP
Definition at line \fB72\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::SEP (void )\fR [static]\fP"

.PP
Definition at line \fB44\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::SHA (void )\fR [static]\fP"

.PP
Definition at line \fB86\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::SSE (void )\fR [static]\fP"

.PP
Definition at line \fB54\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::SSE2 (void )\fR [static]\fP"

.PP
Definition at line \fB56\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "static bool CORE::InstructionSet::SSE3 (void )\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB17\fP of file \fBCPUFEATURES\&.h\fP\&.
.SS "bool CORE::InstructionSet::SSE41 (void )\fR [static]\fP"

.PP
Definition at line \fB20\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::SSE42 (void )\fR [static]\fP"

.PP
Definition at line \fB22\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::SSE4a (void )\fR [static]\fP"

.PP
Definition at line \fB96\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::SSSE3 (void )\fR [static]\fP"

.PP
Definition at line \fB14\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::SYSCALL (void )\fR [static]\fP"

.PP
Definition at line \fB102\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::TBM (void )\fR [static]\fP"

.PP
Definition at line \fB100\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "std::string CORE::InstructionSet::Vendor (void )\fR [static]\fP"

.PP
Definition at line \fB6\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::XOP (void )\fR [static]\fP"

.PP
Definition at line \fB98\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SS "bool CORE::InstructionSet::XSAVE (void )\fR [static]\fP"

.PP
Definition at line \fB30\fP of file \fBCPUFEATURES\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const \fBCORE::InstructionSet::InstructionSet_Internal\fP CORE::InstructionSet::CPU_Rep\fR [static]\fP"

.PP
Definition at line \fB75\fP of file \fBCPUFEATURES\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
