.TH "core_func_trigonometric" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core_func_trigonometric \- Angle and Trigonometry Functions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::radians\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &degrees)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::degrees\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &radians)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::sin\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBangle\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::cos\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBangle\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::tan\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBangle\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::asin\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::acos\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::atan\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::atan\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &y_over_x)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::sinh\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBangle\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::cosh\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBangle\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::tanh\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBangle\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::asinh\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::acosh\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::atanh\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Function parameters specified as angle are assumed to be in units of radians\&. In no case will any of these functions result in a divide by zero error\&. If the divisor of a ratio is 0, then results will be undefined\&.
.PP
These all operate component-wise\&. The description is per component\&.
.PP
Include <\fBglm/trigonometric\&.hpp\fP> to use these core features\&.
.PP
\fBSee also\fP
.RS 4
ext_vector_trigonometric
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::acos (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Arc cosine\&. Returns an angle whose cosine is x\&. The range of values returned by this function is [0, PI]\&. Results are undefined if |x| > 1\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL acos man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.1 Angle and Trigonometry Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::acosh (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Arc hyperbolic cosine; returns the non-negative inverse of cosh\&. Results are undefined if x < 1\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL acosh man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.1 Angle and Trigonometry Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::asin (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Arc sine\&. Returns an angle whose sine is x\&. The range of values returned by this function is [-PI/2, PI/2]\&. Results are undefined if |x| > 1\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL asin man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.1 Angle and Trigonometry Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::asinh (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Arc hyperbolic sine; returns the inverse of sinh\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL asinh man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.1 Angle and Trigonometry Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::atan (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Arc tangent\&. Returns an angle whose tangent is y/x\&. The signs of x and y are used to determine what quadrant the angle is in\&. The range of values returned by this function is [-PI, PI]\&. Results are undefined if x and y are both 0\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL atan man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.1 Angle and Trigonometry Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::atan (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y_over_x)"
Arc tangent\&. Returns an angle whose tangent is y_over_x\&. The range of values returned by this function is [-PI/2, PI/2]\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL atan man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.1 Angle and Trigonometry Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::atanh (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Arc hyperbolic tangent; returns the inverse of tanh\&. Results are undefined if abs(x) >= 1\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL atanh man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.1 Angle and Trigonometry Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::cos (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & angle)"
The standard trigonometric cosine function\&. The values returned by this function will range from [-1, 1]\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL cos man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.1 Angle and Trigonometry Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::cosh (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & angle)"
Returns the hyperbolic cosine function, (exp(x) + exp(-x)) / 2
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL cosh man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.1 Angle and Trigonometry Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::degrees (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & radians)"
Converts radians to degrees and returns the result\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL degrees man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.1 Angle and Trigonometry Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::radians (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & degrees)"
Converts degrees to radians and returns the result\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL radians man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.1 Angle and Trigonometry Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::sin (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & angle)"
The standard trigonometric sine function\&. The values returned by this function will range from [-1, 1]\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL sin man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.1 Angle and Trigonometry Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::sinh (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & angle)"
Returns the hyperbolic sine function, (exp(x) - exp(-x)) / 2
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL sinh man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.1 Angle and Trigonometry Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::tan (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & angle)"
The standard trigonometric tangent function\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL tan man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.1 Angle and Trigonometry Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::tanh (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & angle)"
Returns the hyperbolic tangent function, sinh(angle) / cosh(angle)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL tanh man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.1 Angle and Trigonometry Functions\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
