.TH "CORE::Directory" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORE::Directory
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FILELOADER\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDirectory\fP (const char *Paht)"
.br
.ti -1c
.RI "std::vector< \fBFolder\fP > \fBGetFolder\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBPath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBFILELOADER\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CORE::Directory::Directory (const char * Paht)"

.PP
Definition at line \fB18\fP of file \fBFILELOADER\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "std::vector< \fBCORE::Folder\fP > CORE::Directory::GetFolder ()"

.PP
Definition at line \fB23\fP of file \fBFILELOADER\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const char* CORE::Directory::Path"

.PP
Definition at line \fB22\fP of file \fBFILELOADER\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
