.TH "core_func_common" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core_func_common \- Common functions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP genType \fBglm::abs\fP (genType \fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::abs\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::sign\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::floor\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::trunc\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::round\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::roundEven\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::ceil\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::fract\fP (genType \fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::fract\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::mod\fP (genType \fBx\fP, genType \fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::mod\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBT\fP \fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::mod\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::modf\fP (genType \fBx\fP, genType &\fBi\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP genType \fBglm::min\fP (genType \fBx\fP, genType \fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::min\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBT\fP \fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::min\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP genType \fBglm::max\fP (genType \fBx\fP, genType \fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::max\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBT\fP \fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::max\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP genType \fBglm::clamp\fP (genType \fBx\fP, genType minVal, genType maxVal)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::clamp\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBT\fP minVal, \fBT\fP maxVal)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::clamp\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &minVal, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &maxVal)"
.br
.ti -1c
.RI "template<typename genTypeT , typename genTypeU > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP genTypeT \fBglm::mix\fP (genTypeT \fBx\fP, genTypeT \fBy\fP, genTypeU \fBa\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::mix\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::mix\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBU\fP \fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::step\fP (genType edge, genType \fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::step\fP (\fBT\fP edge, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::step\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &edge, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::smoothstep\fP (genType edge0, genType edge1, genType \fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::smoothstep\fP (\fBT\fP edge0, \fBT\fP edge1, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::smoothstep\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &edge0, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &edge1, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, bool, \fBQ\fP > \fBglm::isnan\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, bool, \fBQ\fP > \fBglm::isinf\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP int \fBglm::floatBitsToInt\fP (float \fBv\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, int, \fBQ\fP > \fBglm::floatBitsToInt\fP (\fBvec\fP< \fBL\fP, float, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBuint\fP \fBglm::floatBitsToUint\fP (float \fBv\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBuint\fP, \fBQ\fP > \fBglm::floatBitsToUint\fP (\fBvec\fP< \fBL\fP, float, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP float \fBglm::intBitsToFloat\fP (int \fBv\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, float, \fBQ\fP > \fBglm::intBitsToFloat\fP (\fBvec\fP< \fBL\fP, int, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP float \fBglm::uintBitsToFloat\fP (\fBuint\fP \fBv\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, float, \fBQ\fP > \fBglm::uintBitsToFloat\fP (\fBvec\fP< \fBL\fP, \fBuint\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::fma\fP (genType const &\fBa\fP, genType const &\fBb\fP, genType const &c)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::frexp\fP (genType \fBx\fP, int &exp)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::frexp\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBvec\fP< \fBL\fP, int, \fBQ\fP > &exp)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::ldexp\fP (genType const &\fBx\fP, int const &exp)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::ldexp\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBvec\fP< \fBL\fP, int, \fBQ\fP > const &exp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides GLSL common functions
.PP
These all operate component-wise\&. The description is per component\&.
.PP
Include <\fBglm/common\&.hpp\fP> to use these core features\&.
.SH "Function Documentation"
.PP 
.SS "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP genType glm::abs (genType x)"
Returns x if x >= 0; otherwise, it returns -x\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP floating-point or signed integer; scalar or vector types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL abs man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::abs (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Returns x if x >= 0; otherwise, it returns -x\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point or signed integer scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL abs man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::ceil (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Returns a value equal to the nearest integer that is greater than or equal to x\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL ceil man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP genType glm::clamp (genType x, genType minVal, genType maxVal)"
Returns min(max(x, minVal), maxVal) for each component in x using the floating-point values minVal and maxVal\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP Floating-point or integer; scalar or vector types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL clamp man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::clamp (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBT\fP minVal, \fBT\fP maxVal)"
Returns min(max(x, minVal), maxVal) for each component in x using the floating-point values minVal and maxVal\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point or integer scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL clamp man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::clamp (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & minVal, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & maxVal)"
Returns min(max(x, minVal), maxVal) for each component in x using the floating-point values minVal and maxVal\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point or integer scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL clamp man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "\fBGLM_FUNC_QUALIFIER\fP int glm::floatBitsToInt (float v)"
Returns a signed integer value representing the encoding of a floating-point value\&. The floating-point value's bit-level representation is preserved\&.
.PP
\fBSee also\fP
.RS 4
\fRGLSL floatBitsToInt man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, int, \fBQ\fP > glm::floatBitsToInt (\fBvec\fP< \fBL\fP, float, \fBQ\fP > const & v)"
Returns a signed integer value representing the encoding of a floating-point value\&. The floatingpoint value's bit-level representation is preserved\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL floatBitsToInt man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "\fBGLM_FUNC_QUALIFIER\fP \fBuint\fP glm::floatBitsToUint (float v)"
Returns a unsigned integer value representing the encoding of a floating-point value\&. The floatingpoint value's bit-level representation is preserved\&.
.PP
\fBSee also\fP
.RS 4
\fRGLSL floatBitsToUint man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBuint\fP, \fBQ\fP > glm::floatBitsToUint (\fBvec\fP< \fBL\fP, float, \fBQ\fP > const & v)"
Returns a unsigned integer value representing the encoding of a floating-point value\&. The floatingpoint value's bit-level representation is preserved\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL floatBitsToUint man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::floor (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Returns a value equal to the nearest integer that is less then or equal to x\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL floor man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::fma (genType const & a, genType const & b, genType const & c)"
Computes and returns a * b + c\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL fma man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::fract (genType x)"
Return x - floor(x)\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL fract man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::fract (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Return x - floor(x)\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL fract man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::frexp (genType x, int & exp)"
Splits x into a floating-point significand in the range [0\&.5, 1\&.0) and an integral exponent of two, such that: x = significand * exp(2, exponent)
.PP
The significand is returned by the function and the exponent is returned in the parameter exp\&. For a floating-point value of zero, the significant and exponent are both zero\&. For a floating-point value that is an infinity or is not a number, the results are undefined\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL frexp man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::frexp (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & v, \fBvec\fP< \fBL\fP, int, \fBQ\fP > & exp)"

.SS "\fBGLM_FUNC_QUALIFIER\fP float glm::intBitsToFloat (int v)"
Returns a floating-point value corresponding to a signed integer encoding of a floating-point value\&. If an inf or NaN is passed in, it will not signal, and the resulting floating point value is unspecified\&. Otherwise, the bit-level representation is preserved\&.
.PP
\fBSee also\fP
.RS 4
\fRGLSL intBitsToFloat man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, float, \fBQ\fP > glm::intBitsToFloat (\fBvec\fP< \fBL\fP, int, \fBQ\fP > const & v)"
Returns a floating-point value corresponding to a signed integer encoding of a floating-point value\&. If an inf or NaN is passed in, it will not signal, and the resulting floating point value is unspecified\&. Otherwise, the bit-level representation is preserved\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL intBitsToFloat man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, bool, \fBQ\fP > glm::isinf (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Returns true if x holds a positive infinity or negative infinity representation in the underlying implementation's set of floating point representations\&. Returns false otherwise, including for implementations with no infinity representations\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL isinf man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, bool, \fBQ\fP > glm::isnan (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Returns true if x holds a NaN (not a number) representation in the underlying implementation's set of floating point representations\&. Returns false otherwise, including for implementations with no NaN representations\&.
.PP
/!\\ When using compiler fast math, this function may fail\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL isnan man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::ldexp (genType const & x, int const & exp)"
Builds a floating-point number from x and the corresponding integral exponent of two in exp, returning: significand * exp(2, exponent)
.PP
If this product is too large to be represented in the floating-point type, the result is undefined\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL ldexp man page\fP; 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::ldexp (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & v, \fBvec\fP< \fBL\fP, int, \fBQ\fP > const & exp)"

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP genType glm::max (genType x, genType y)"
Returns y if x < y; otherwise, it returns x\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP Floating-point or integer; scalar or vector types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL max man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::max (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBT\fP y)"
Returns y if x < y; otherwise, it returns x\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point or integer scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL max man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::max (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y)"
Returns y if x < y; otherwise, it returns x\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point or integer scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL max man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP genType glm::min (genType x, genType y)"
Returns y if y < x; otherwise, it returns x\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP Floating-point or integer; scalar or vector types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL min man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::min (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBT\fP y)"
Returns y if y < x; otherwise, it returns x\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point or integer scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL min man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::min (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y)"
Returns y if y < x; otherwise, it returns x\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point or integer scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL min man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<typename genTypeT , typename genTypeU > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP genTypeT glm::mix (genTypeT x, genTypeT y, genTypeU a)"
If genTypeU is a floating scalar or vector: Returns x * (1\&.0 - a) + y * a, i\&.e\&., the linear blend of x and y using the floating-point value a\&. The value for a is not restricted to the range [0, 1]\&.
.PP
If genTypeU is a boolean scalar or vector: Selects which vector each returned component comes from\&. For a component of 'a' that is false, the corresponding component of 'x' is returned\&. For a component of 'a' that is true, the corresponding component of 'y' is returned\&. Components of 'x' and 'y' that are not selected are allowed to be invalid floating point values and will have no effect on the results\&. Thus, this provides different functionality than genType mix(genType x, genType y, genType(a)) where a is a Boolean vector\&.
.PP
\fBSee also\fP
.RS 4
\fRGLSL mix man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP
.RE
.PP
\fBParameters\fP
.RS 4
\fIx\fP Value to interpolate\&. 
.br
\fIy\fP Value to interpolate\&. 
.br
\fIa\fP Interpolant\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenTypeT\fP Floating point scalar or vector\&. 
.br
\fIgenTypeU\fP Floating point or boolean scalar or vector\&. It can't be a vector if it is the length of genTypeT\&.
.RE
.PP
.PP
.nf
#include <glm/glm\&.hpp>
\&.\&.\&.
float a;
bool b;
glm::dvec3 e;
glm::dvec3 f;
glm::vec4 g;
glm::vec4 h;
\&.\&.\&.
glm::vec4 r = glm::mix(g, h, a); // Interpolate with a floating\-point scalar two vectors\&.
glm::vec4 s = glm::mix(g, h, b); // Returns g or h;
glm::dvec3 t = glm::mix(e, f, a); // Types of the third parameter is not required to match with the first and the second\&.
glm::vec4 u = glm::mix(g, h, r); // Interpolations can be perform per component with a vector for the last parameter\&.
.fi
.PP
 
.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::mix (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y, \fBU\fP a)"

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::mix (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & a)"

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::mod (genType x, genType y)"

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::mod (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBT\fP y)"

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::mod (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y)"
Modulus\&. Returns x - y * floor(x / y) for each component in x using the floating point value y\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types, include glm/gtc/integer for integer scalar types support 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL mod man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::modf (genType x, genType & i)"
Returns the fractional part of x and sets i to the integer part (as a whole number floating point value)\&. Both the return value and the output parameter will have the same sign as x\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL modf man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::round (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Returns a value equal to the nearest integer to x\&. The fraction 0\&.5 will round in a direction chosen by the implementation, presumably the direction that is fastest\&. This includes the possibility that round(x) returns the same value as roundEven(x) for all values of x\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL round man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::roundEven (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Returns a value equal to the nearest integer to x\&. A fractional part of 0\&.5 will round toward the nearest even integer\&. (Both 3\&.5 and 4\&.5 for x will return 4\&.0\&.)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL roundEven man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.PP
\fRNew round to even technique\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::sign (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Returns 1\&.0 if x > 0, 0\&.0 if x == 0, or -1\&.0 if x < 0\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL sign man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::smoothstep (genType edge0, genType edge1, genType x)"
Returns 0\&.0 if x <= edge0 and 1\&.0 if x >= edge1 and performs smooth Hermite interpolation between 0 and 1 when edge0 < x < edge1\&. This is useful in cases where you would want a threshold function with a smooth transition\&. This is equivalent to: genType t; t = clamp ((x - edge0) / (edge1 - edge0), 0, 1); return t * t * (3 - 2 * t); Results are undefined if edge0 >= edge1\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL smoothstep man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::smoothstep (\fBT\fP edge0, \fBT\fP edge1, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::smoothstep (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & edge0, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & edge1, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::step (genType edge, genType x)"
Returns 0\&.0 if x < edge, otherwise it returns 1\&.0 for each component of a genType\&.
.PP
\fBSee also\fP
.RS 4
\fRGLSL step man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::step (\fBT\fP edge, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Returns 0\&.0 if x < edge, otherwise it returns 1\&.0\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL step man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::step (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & edge, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Returns 0\&.0 if x < edge, otherwise it returns 1\&.0\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL step man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::trunc (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Returns a value equal to the nearest integer to x whose absolute value is not larger than the absolute value of x\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL trunc man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "\fBGLM_FUNC_QUALIFIER\fP float glm::uintBitsToFloat (\fBuint\fP v)"
Returns a floating-point value corresponding to a unsigned integer encoding of a floating-point value\&. If an inf or NaN is passed in, it will not signal, and the resulting floating point value is unspecified\&. Otherwise, the bit-level representation is preserved\&.
.PP
\fBSee also\fP
.RS 4
\fRGLSL uintBitsToFloat man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, float, \fBQ\fP > glm::uintBitsToFloat (\fBvec\fP< \fBL\fP, \fBuint\fP, \fBQ\fP > const & v)"
Returns a floating-point value corresponding to a unsigned integer encoding of a floating-point value\&. If an inf or NaN is passed in, it will not signal, and the resulting floating point value is unspecified\&. Otherwise, the bit-level representation is preserved\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRGLSL uintBitsToFloat man page\fP 
.PP
\fRGLSL 4\&.20\&.8 specification, section 8\&.3 Common Functions\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
