.TH "CORE::Object" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORE::Object
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <C_OBJECT\&.h>\fP
.PP
Inherited by \fBGameObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObject\fP ()"
.br
.ti -1c
.RI "virtual \fB~Object\fP ()"
.br
.ti -1c
.RI "void \fBDestroyObj\fP (\fBObject\fP *obj)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UUID \fBuuid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBC_OBJECT\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CORE::Object::Object ()"

.PP
Definition at line \fB14\fP of file \fBC_OBJECT\&.cpp\fP\&.
.nf
14 {}
.PP
.fi

.SS "CORE::Object::~Object ()\fR [virtual]\fP"

.PP
Definition at line \fB16\fP of file \fBC_OBJECT\&.cpp\fP\&.
.nf
16                      {
17 
18     }
.PP
.fi

.SH "Member Function Documentation"
.PP 
.SS "void CORE::Object::DestroyObj (\fBObject\fP * obj)"

.PP
Definition at line \fB20\fP of file \fBC_OBJECT\&.cpp\fP\&.
.nf
20                                         {
21         free(obj);
22     }
.PP
.fi

.SH "Member Data Documentation"
.PP 
.SS "UUID CORE::Object::uuid"

.PP
Definition at line \fB14\fP of file \fBC_OBJECT\&.h\fP\&.
.PP
Referenced by \fBGameObject::AddComponent()\fP, \fBGameObject::AddComponent()\fP, \fBGameObject::AddComponent()\fP, \fBGameObject::Create()\fP, \fBGameObject::Create()\fP, \fBGameObject::CreateCamera()\fP, and \fBGameObject::CreateEmpty()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
