.TH "CORE::Thread" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORE::Thread
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <C_THREADING\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThread\fP (std::function< void()> f)"
.br
.ti -1c
.RI "template<class _Fn , class \&.\&.\&. _Args> \fBThread\fP (_Fn &&_Fx, _Args &&\&.\&.\&. _Ax)"
.br
.ti -1c
.RI "void \fBSchedule\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB25\fP of file \fBC_THREADING\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CORE::Thread::Thread (std::function< void()> f)\fR [inline]\fP"

.PP
Definition at line \fB32\fP of file \fBC_THREADING\&.h\fP\&.
.nf
32 : func(f) {};
.PP
.fi

.SS "template<class _Fn , class \&.\&.\&. _Args> CORE::Thread::Thread (_Fn && _Fx, _Args &&\&.\&.\&. _Ax)\fR [inline]\fP"

.PP
Definition at line \fB35\fP of file \fBC_THREADING\&.h\fP\&.
.nf
35                                           {
36             func = std::bind(std::forward<_Fn>(_Fx), std::forward<_Args>(_Ax)\&.\&.\&.);
37             Thread_Manager::Threads\&.push_back(this);
38         }
.PP
.fi

.PP
References \fBCORE::Thread_Manager::Threads\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void CORE::Thread::Schedule ()\fR [inline]\fP"

.PP
Definition at line \fB47\fP of file \fBC_THREADING\&.h\fP\&.
.nf
47                         {
48 
49             this\->thread = std::thread(func);
50 
51         }
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
