.TH "CORE::Startup" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORE::Startup
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <STARTUP\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDATATYPES::Startup_Config\fP \fBConfigure_Startup\fP ()"
.br
.ti -1c
.RI "static void \fBInit_Startup\fP (\fBDATATYPES::Startup_Config\fP config)"
.br
.ti -1c
.RI "static \fBSYSTEMS\fP \fBStart_Systems\fP ()"
.br
.ti -1c
.RI "static void \fBStart_Game\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBDATATYPES::Startup_Config\fP \fBSTARTUP_CONFIG\fP"
.br
.ti -1c
.RI "static bool \fBStartupComplete\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBSTARTUP\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDATATYPES::Startup_Config\fP CORE::Startup::Configure_Startup ()\fR [static]\fP"

.PP
Definition at line \fB14\fP of file \fBSTARTUP\&.cpp\fP\&.
.SS "void CORE::Startup::Init_Startup (\fBDATATYPES::Startup_Config\fP config)\fR [static]\fP"

.PP
Definition at line \fB44\fP of file \fBSTARTUP\&.cpp\fP\&.
.SS "static void CORE::Startup::Start_Game ()\fR [static]\fP"

.SS "\fBCORE::SYSTEMS\fP CORE::Startup::Start_Systems ()\fR [static]\fP"

.PP
Definition at line \fB48\fP of file \fBSTARTUP\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDATATYPES::Startup_Config\fP CORE::Startup::STARTUP_CONFIG\fR [static]\fP"

.PP
Definition at line \fB30\fP of file \fBSTARTUP\&.h\fP\&.
.SS "bool CORE::Startup::StartupComplete\fR [static]\fP"

.PP
Definition at line \fB31\fP of file \fBSTARTUP\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
