.TH "CORE::Filehandler" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORE::Filehandler
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CORE\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBApplicationPath\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB31\fP of file \fBCORE\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string CORE::Filehandler::ApplicationPath ()\fR [static]\fP"

.PP
Definition at line \fB5\fP of file \fBCORE\&.cpp\fP\&.
.nf
5                                             {
6     TrPr(ctx, __func__)
7     if (yes == false) {
8         yes = true;
9 
10         //Application_Path = GetModuleFileNameA();
11         char buffer[MAX_PATH];
12         DWORD length = GetModuleFileNameA(NULL, buffer, MAX_PATH);
13         Application_Path = std::string(buffer, length\-18);
14     }
15     TrPrE(ctx);
16     return Application_Path;
17 }
.PP
.fi

.PP
References \fBTrPr\fP, and \fBTrPrE\fP\&.
.PP
Referenced by \fBEDITOR::Editor::DrawEditor()\fP, and \fBmain()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
