.TH "CORE::FileLoader" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORE::FileLoader
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FILELOADER\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileLoader\fP (\fBDirectory\fP *\fBdirectory\fP)"
.br
.ti -1c
.RI "\fBFile\fP \fBLoadFile\fP (const char *path)"
.br
.ti -1c
.RI "\fBFile\fP \fBLoadFilesWithExtension\fP (const char *path, const char *extension)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDirectory\fP * \fBdirectory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB29\fP of file \fBFILELOADER\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CORE::FileLoader::FileLoader (\fBDirectory\fP * directory)"

.PP
Definition at line \fB3\fP of file \fBFILELOADER\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCORE::File\fP CORE::FileLoader::LoadFile (const char * path)"

.PP
Definition at line \fB8\fP of file \fBFILELOADER\&.cpp\fP\&.
.SS "\fBCORE::File\fP CORE::FileLoader::LoadFilesWithExtension (const char * path, const char * extension)"

.PP
Definition at line \fB13\fP of file \fBFILELOADER\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDirectory\fP* CORE::FileLoader::directory"

.PP
Definition at line \fB32\fP of file \fBFILELOADER\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
