.TH "CORE::FileLoader" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORE::FileLoader
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <C_FILELOADER\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileLoader\fP (\fBDirectory\fP *\fBdirectory\fP)"
.br
.ti -1c
.RI "\fBFile\fP \fBLoadFile\fP (const char *path)"
.br
.ti -1c
.RI "\fBFile\fP \fBLoadFilesWithExtension\fP (const char *path, const char *extension)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDirectory\fP * \fBdirectory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB29\fP of file \fBC_FILELOADER\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CORE::FileLoader::FileLoader (\fBDirectory\fP * directory)"

.PP
Definition at line \fB5\fP of file \fBC_FILELOADER\&.cpp\fP\&.
.nf
6 {
7     this\->directory = directory;
8 }
.PP
.fi

.PP
References \fBdirectory\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCORE::File\fP CORE::FileLoader::LoadFile (const char * path)"

.PP
Definition at line \fB10\fP of file \fBC_FILELOADER\&.cpp\fP\&.
.nf
11 {
12     return File();
13 }
.PP
.fi

.SS "\fBCORE::File\fP CORE::FileLoader::LoadFilesWithExtension (const char * path, const char * extension)"

.PP
Definition at line \fB15\fP of file \fBC_FILELOADER\&.cpp\fP\&.
.nf
16 {
17     return File();
18 }
.PP
.fi

.SH "Member Data Documentation"
.PP 
.SS "\fBDirectory\fP* CORE::FileLoader::directory"

.PP
Definition at line \fB32\fP of file \fBC_FILELOADER\&.h\fP\&.
.PP
Referenced by \fBFileLoader()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
