.TH "CORE::Input" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORE::Input
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <INPUT\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMouseMode\fP { \fBMouseLocked\fP, \fBMouseFree\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInput\fP ()"
.br
.ti -1c
.RI "\fBInput\fP (GLFWwindow *Window)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBGetKey\fP (int key)"
.br
.ti -1c
.RI "static \fBMouseMode\fP \fBSetMouseMode\fP (\fBMouseMode\fP mode)"
.br
.ti -1c
.RI "static void \fBmouse_callback\fP (GLFWwindow *window, double xpos, double ypos)"
.br
.ti -1c
.RI "static void \fBInit\fP (GLFWwindow *Window)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static GLFWwindow * \fBwinow\fP"
.br
.ti -1c
.RI "static \fBTS_P_Vector2\fP \fBMousePosition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB49\fP of file \fBINPUT\&.h\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBCORE::Input::MouseMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMouseLocked \fP\fP
.TP
\fB\fIMouseFree \fP\fP
.PP
Definition at line \fB56\fP of file \fBINPUT\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CORE::Input::Input ()"

.PP
Definition at line \fB5\fP of file \fBINPUT\&.cpp\fP\&.
.SS "CORE::Input::Input (GLFWwindow * Window)"

.PP
Definition at line \fB6\fP of file \fBINPUT\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int CORE::Input::GetKey (int key)\fR [static]\fP"

.PP
Definition at line \fB9\fP of file \fBINPUT\&.cpp\fP\&.
.SS "void CORE::Input::Init (GLFWwindow * Window)\fR [static]\fP"

.PP
Definition at line \fB39\fP of file \fBINPUT\&.cpp\fP\&.
.SS "void CORE::Input::mouse_callback (GLFWwindow * window, double xpos, double ypos)\fR [static]\fP"

.PP
Definition at line \fB31\fP of file \fBINPUT\&.cpp\fP\&.
.SS "\fBCORE::Input::MouseMode\fP CORE::Input::SetMouseMode (\fBMouseMode\fP mode)\fR [static]\fP"

.PP
Definition at line \fB14\fP of file \fBINPUT\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTS_P_Vector2\fP CORE::Input::MousePosition\fR [static]\fP"

.PP
Definition at line \fB65\fP of file \fBINPUT\&.h\fP\&.
.SS "GLFWwindow * CORE::Input::winow\fR [static]\fP"

.PP
Definition at line \fB60\fP of file \fBINPUT\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
