.TH "CORE::ConfigLoader" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORE::ConfigLoader
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CONFIGLOADER\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSettingsFile\fP \fBLoadSettingsFile\fP (const char *path)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBConfigFile\fP \fBLoadCOnfigFile\fP (const char *path)"
.br
.ti -1c
.RI "static void \fBLoadModels\fP (const std::filesystem::path path)"
.br
.ti -1c
.RI "static void \fBLoadTerrains\fP ()"
.br
.ti -1c
.RI "template<class _Ty , class _Arg > static _Ty \fBGameobjectFromCFGFile\fP (std::shared_ptr< \fBConfigFile\fP > CFG)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBsafemode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBCONFIGLOADER\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class _Ty , class _Arg > _Ty CORE::ConfigLoader::GameobjectFromCFGFile (std::shared_ptr< \fBConfigFile\fP > CFG)\fR [static]\fP"

.PP
Definition at line \fB66\fP of file \fBCONFIGLOADER\&.cpp\fP\&.
.SS "\fBConfigFile\fP CORE::ConfigLoader::LoadCOnfigFile (const char * path)\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBCONFIGLOADER\&.cpp\fP\&.
.SS "void CORE::ConfigLoader::LoadModels (const std::filesystem::path path)\fR [static]\fP"

.PP
Definition at line \fB37\fP of file \fBCONFIGLOADER\&.cpp\fP\&.
.SS "\fBSettingsFile\fP CORE::ConfigLoader::LoadSettingsFile (const char * path)"

.PP
Definition at line \fB5\fP of file \fBCONFIGLOADER\&.cpp\fP\&.
.SS "void CORE::ConfigLoader::LoadTerrains ()\fR [static]\fP"

.PP
Definition at line \fB62\fP of file \fBCONFIGLOADER\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CORE::ConfigLoader::safemode"

.PP
Definition at line \fB12\fP of file \fBCONFIGLOADER\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
