.TH "CORE::Object" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORE::Object
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <OBJECT\&.h>\fP
.PP
Inherited by \fBGameObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObject\fP ()"
.br
.ti -1c
.RI "virtual \fB~Object\fP ()"
.br
.ti -1c
.RI "void \fBDestroyObj\fP (\fBObject\fP *obj)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UUID \fBuuid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBOBJECT\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CORE::Object::Object ()"

.PP
Definition at line \fB14\fP of file \fBOBJECT\&.cpp\fP\&.
.SS "CORE::Object::~Object ()\fR [virtual]\fP"

.PP
Definition at line \fB16\fP of file \fBOBJECT\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void CORE::Object::DestroyObj (\fBObject\fP * obj)"

.PP
Definition at line \fB20\fP of file \fBOBJECT\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UUID CORE::Object::uuid"

.PP
Definition at line \fB14\fP of file \fBOBJECT\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
