.TH "CORE::Behaviour" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORE::Behaviour
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <BEHAVIOUR\&.h>\fP
.PP
Inherited by \fBCOMPONENTS::_Mesh\fP, \fBCamera\fP, \fBEmpty\fP, \fBParallel_Update\fP, \fBTerrain\fP, \fBTest\fP, and \fBTransform\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBehaviour\fP ()"
.br
.ti -1c
.RI "\fBBehaviour\fP (\fBGameObject\fP *oobj, std::shared_ptr< \fBCORE::Behaviour\fP > trans)"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBAwake\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBStart\fP ()=0"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBupdateAll\fP ()"
.br
.ti -1c
.RI "static void \fBupdateAllAWAKE\fP ()"
.br
.ti -1c
.RI "static void \fBupdateAllSTART\fP ()"
.br
.ti -1c
.RI "static void \fBupdateallParallel\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGameObject\fP * \fBgameobject\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBTransform\fP > \fBTRANSFORM\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBCORE::Behaviour\fP > \fBtransf\fP"
.br
.ti -1c
.RI "UUID \fBuuID\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBCORE::Behaviour\fP > > \fBobjectss\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBBehaviour\fP > > \fBbehaviours\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBBehaviour\fP > > \fBAWAKES\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBBehaviour\fP > > \fBStarts\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBBehaviour\fP > > \fBParallel_Updates\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBBEHAVIOUR\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CORE::Behaviour::Behaviour ()"

.PP
Definition at line \fB12\fP of file \fBBehaviour\&.cpp\fP\&.
.SS "CORE::Behaviour::Behaviour (\fBGameObject\fP * oobj, std::shared_ptr< \fBCORE::Behaviour\fP > trans)"

.PP
Definition at line \fB14\fP of file \fBBehaviour\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void CORE::Behaviour::Awake ()\fR [pure virtual]\fP"

.PP
Implemented in \fBCamera\fP, \fBCOMPONENTS::_Mesh\fP, \fBEmpty\fP, \fBParallel_Update\fP, \fBTerrain\fP, \fBTest\fP, and \fBTransform\fP\&.
.SS "virtual void CORE::Behaviour::Start ()\fR [pure virtual]\fP"

.PP
Implemented in \fBCamera\fP, \fBCOMPONENTS::_Mesh\fP, \fBEmpty\fP, \fBParallel_Update\fP, \fBTerrain\fP, \fBTest\fP, and \fBTransform\fP\&.
.SS "virtual void CORE::Behaviour::Update ()\fR [pure virtual]\fP"

.PP
Implemented in \fBCamera\fP, \fBCOMPONENTS::_Mesh\fP, \fBEmpty\fP, \fBParallel_Update\fP, \fBTerrain\fP, \fBTest\fP, and \fBTransform\fP\&.
.SS "void CORE::Behaviour::updateAll ()\fR [static]\fP"

.PP
Definition at line \fB20\fP of file \fBBehaviour\&.cpp\fP\&.
.SS "void CORE::Behaviour::updateAllAWAKE ()\fR [static]\fP"

.PP
Definition at line \fB29\fP of file \fBBehaviour\&.cpp\fP\&.
.SS "static void CORE::Behaviour::updateallParallel ()\fR [static]\fP"

.SS "void CORE::Behaviour::updateAllSTART ()\fR [static]\fP"

.PP
Definition at line \fB40\fP of file \fBBehaviour\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector< std::shared_ptr< \fBCORE::Behaviour\fP > > CORE::Behaviour::AWAKES\fR [static]\fP"

.PP
Definition at line \fB32\fP of file \fBBEHAVIOUR\&.h\fP\&.
.SS "std::vector< std::shared_ptr< \fBCORE::Behaviour\fP > > CORE::Behaviour::behaviours\fR [static]\fP"

.PP
Definition at line \fB31\fP of file \fBBEHAVIOUR\&.h\fP\&.
.SS "\fBGameObject\fP* CORE::Behaviour::gameobject"

.PP
Definition at line \fB26\fP of file \fBBEHAVIOUR\&.h\fP\&.
.SS "int CORE::Behaviour::id"

.PP
Definition at line \fB36\fP of file \fBBEHAVIOUR\&.h\fP\&.
.SS "std::vector<std::shared_ptr<\fBCORE::Behaviour\fP> > CORE::Behaviour::objectss\fR [static]\fP"

.PP
Definition at line \fB30\fP of file \fBBEHAVIOUR\&.h\fP\&.
.SS "std::vector<std::shared_ptr<\fBBehaviour\fP> > CORE::Behaviour::Parallel_Updates\fR [static]\fP"

.PP
Definition at line \fB34\fP of file \fBBEHAVIOUR\&.h\fP\&.
.SS "std::vector< std::shared_ptr< \fBCORE::Behaviour\fP > > CORE::Behaviour::Starts\fR [static]\fP"

.PP
Definition at line \fB33\fP of file \fBBEHAVIOUR\&.h\fP\&.
.SS "std::shared_ptr<\fBCORE::Behaviour\fP> CORE::Behaviour::transf"

.PP
Definition at line \fB28\fP of file \fBBEHAVIOUR\&.h\fP\&.
.SS "std::shared_ptr<\fBTransform\fP> CORE::Behaviour::TRANSFORM"

.PP
Definition at line \fB27\fP of file \fBBEHAVIOUR\&.h\fP\&.
.SS "UUID CORE::Behaviour::uuID"

.PP
Definition at line \fB35\fP of file \fBBEHAVIOUR\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
