.TH "CORE::Scene" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORE::Scene
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SCENE\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScene\fP ()"
.br
.ti -1c
.RI "virtual \fB~Scene\fP ()"
.br
.ti -1c
.RI "\fBGameObject\fP * \fBFindObjectByName\fP (const char *name)"
.br
.ti -1c
.RI "\fBGameObject\fP * \fBFindObjectByUUID\fP (UUID uuid)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBScene\fP \fBCreate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::shared_ptr< \fBGameObject\fP > > \fBObjectsInScene\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBScene\fP \fBactiveScene\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBSCENE\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CORE::Scene::Scene ()"

.PP
Definition at line \fB3\fP of file \fBSCENE\&.cpp\fP\&.
.SS "CORE::Scene::~Scene ()\fR [virtual]\fP"

.PP
Definition at line \fB7\fP of file \fBSCENE\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCORE::Scene\fP CORE::Scene::Create ()\fR [static]\fP"

.PP
Definition at line \fB33\fP of file \fBSCENE\&.cpp\fP\&.
.SS "\fBGameObject\fP * CORE::Scene::FindObjectByName (const char * name)"

.PP
Definition at line \fB11\fP of file \fBSCENE\&.cpp\fP\&.
.SS "\fBGameObject\fP * CORE::Scene::FindObjectByUUID (UUID uuid)"

.PP
Definition at line \fB22\fP of file \fBSCENE\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCORE::Scene\fP CORE::Scene::activeScene\fR [static]\fP"

.PP
Definition at line \fB17\fP of file \fBSCENE\&.h\fP\&.
.SS "std::vector<std::shared_ptr<\fBGameObject\fP> > CORE::Scene::ObjectsInScene"

.PP
Definition at line \fB16\fP of file \fBSCENE\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
