.TH "D3D12_QUERY_DATA_PIPELINE_STATISTICS" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_QUERY_DATA_PIPELINE_STATISTICS
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT64 \fBIAVertices\fP"
.br
.ti -1c
.RI "UINT64 \fBIAPrimitives\fP"
.br
.ti -1c
.RI "UINT64 \fBVSInvocations\fP"
.br
.ti -1c
.RI "UINT64 \fBGSInvocations\fP"
.br
.ti -1c
.RI "UINT64 \fBGSPrimitives\fP"
.br
.ti -1c
.RI "UINT64 \fBCInvocations\fP"
.br
.ti -1c
.RI "UINT64 \fBCPrimitives\fP"
.br
.ti -1c
.RI "UINT64 \fBPSInvocations\fP"
.br
.ti -1c
.RI "UINT64 \fBHSInvocations\fP"
.br
.ti -1c
.RI "UINT64 \fBDSInvocations\fP"
.br
.ti -1c
.RI "UINT64 \fBCSInvocations\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS::CInvocations"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS::CPrimitives"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS::CSInvocations"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS::DSInvocations"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS::GSInvocations"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS::GSPrimitives"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS::HSInvocations"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS::IAPrimitives"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS::IAVertices"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS::PSInvocations"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS::VSInvocations"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
