.TH "D3D12_TILE_SHAPE" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_TILE_SHAPE
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.PP
Inherited by \fBCD3DX12_TILE_SHAPE\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBWidthInTexels\fP"
.br
.ti -1c
.RI "UINT \fBHeightInTexels\fP"
.br
.ti -1c
.RI "UINT \fBDepthInTexels\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT D3D12_TILE_SHAPE::DepthInTexels"

.SS "UINT D3D12_TILE_SHAPE::HeightInTexels"

.SS "UINT D3D12_TILE_SHAPE::WidthInTexels"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
