.TH "D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT64 \fBCompoundPredictionType\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_CONFIG\fP \fBLoopFilter\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_DELTA_CONFIG\fP \fBLoopFilterDelta\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_CONFIG\fP \fBQuantization\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_DELTA_CONFIG\fP \fBQuantizationDelta\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_AV1_CDEF_CONFIG\fP \fBCDEF\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_AV1_SEGMENTATION_CONFIG\fP \fBSegmentationConfig\fP"
.br
.ti -1c
.RI "UINT64 \fBPrimaryRefFrame\fP"
.br
.ti -1c
.RI "UINT64 \fBReferenceIndices\fP [7]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBD3D12_VIDEO_ENCODER_AV1_CDEF_CONFIG\fP D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES::CDEF"

.SS "UINT64 D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES::CompoundPredictionType"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_CONFIG\fP D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES::LoopFilter"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_DELTA_CONFIG\fP D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES::LoopFilterDelta"

.SS "UINT64 D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES::PrimaryRefFrame"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_CONFIG\fP D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES::Quantization"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_DELTA_CONFIG\fP D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES::QuantizationDelta"

.SS "UINT64 D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES::ReferenceIndices[7]"

.SS "\fBD3D12_VIDEO_ENCODER_AV1_SEGMENTATION_CONFIG\fP D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES::SegmentationConfig"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
