.TH "D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBDataSize\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBD3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_H264\fP * \fBpH264PicData\fP"
.br
.ti -1c
.RI "   \fBD3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC\fP * \fBpHEVCPicData\fP"
.br
.ti -1c
.RI "   \fBD3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC1\fP * \fBpHEVCPicData1\fP"
.br
.ti -1c
.RI "   \fBD3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA\fP * \fBpAV1PicData\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "union  { \&.\&.\&. }  \fBD3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA\fP"

.SS "UINT D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA::DataSize"

.SS "\fBD3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA\fP* D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA::pAV1PicData"

.SS "\fBD3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_H264\fP* D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA::pH264PicData"

.SS "\fBD3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC\fP* D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA::pHEVCPicData"

.SS "\fBD3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC1\fP* D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA::pHEVCPicData1"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
