.TH "D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3dx12_property_format_table\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDXGI_FORMAT\fP \fBDXGIFormat\fP"
.br
.ti -1c
.RI "\fBDXGI_FORMAT\fP \fBParentFormat\fP"
.br
.ti -1c
.RI "const \fBDXGI_FORMAT\fP * \fBpDefaultFormatCastSet\fP"
.br
.ti -1c
.RI "UINT8 \fBBitsPerComponent\fP [4]"
.br
.ti -1c
.RI "UINT8 \fBBitsPerUnit\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBSRGBFormat\fP: 1"
.br
.ti -1c
.RI "UINT \fBWidthAlignment\fP: 4"
.br
.ti -1c
.RI "UINT \fBHeightAlignment\fP: 4"
.br
.ti -1c
.RI "UINT \fBDepthAlignment\fP: 1"
.br
.ti -1c
.RI "\fBD3D_FORMAT_LAYOUT\fP \fBLayout\fP: 1"
.br
.ti -1c
.RI "\fBD3D_FORMAT_TYPE_LEVEL\fP \fBTypeLevel\fP: 2"
.br
.ti -1c
.RI "\fBD3D_FORMAT_COMPONENT_NAME\fP \fBComponentName0\fP: 3"
.br
.ti -1c
.RI "\fBD3D_FORMAT_COMPONENT_NAME\fP \fBComponentName1\fP: 3"
.br
.ti -1c
.RI "\fBD3D_FORMAT_COMPONENT_NAME\fP \fBComponentName2\fP: 3"
.br
.ti -1c
.RI "\fBD3D_FORMAT_COMPONENT_NAME\fP \fBComponentName3\fP: 3"
.br
.ti -1c
.RI "\fBD3D_FORMAT_COMPONENT_INTERPRETATION\fP \fBComponentInterpretation0\fP: 3"
.br
.ti -1c
.RI "\fBD3D_FORMAT_COMPONENT_INTERPRETATION\fP \fBComponentInterpretation1\fP: 3"
.br
.ti -1c
.RI "\fBD3D_FORMAT_COMPONENT_INTERPRETATION\fP \fBComponentInterpretation2\fP: 3"
.br
.ti -1c
.RI "\fBD3D_FORMAT_COMPONENT_INTERPRETATION\fP \fBComponentInterpretation3\fP: 3"
.br
.ti -1c
.RI "bool \fBbDX9VertexOrIndexFormat\fP: 1"
.br
.ti -1c
.RI "bool \fBbDX9TextureFormat\fP: 1"
.br
.ti -1c
.RI "bool \fBbFloatNormFormat\fP: 1"
.br
.ti -1c
.RI "bool \fBbPlanar\fP: 1"
.br
.ti -1c
.RI "bool \fBbYUV\fP: 1"
.br
.ti -1c
.RI "bool \fBbDependantFormatCastSet\fP: 1"
.br
.ti -1c
.RI "bool \fBbInternal\fP: 1"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::bDependantFormatCastSet"

.SS "bool D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::bDX9TextureFormat"

.SS "bool D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::bDX9VertexOrIndexFormat"

.SS "bool D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::bFloatNormFormat"

.SS "bool D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::bInternal"

.SS "UINT8 D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::BitsPerComponent[4]"

.SS "UINT8 D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::BitsPerUnit"

.SS "bool D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::bPlanar"

.SS "bool D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::bYUV"

.SS "\fBD3D_FORMAT_COMPONENT_INTERPRETATION\fP D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::ComponentInterpretation0"

.SS "\fBD3D_FORMAT_COMPONENT_INTERPRETATION\fP D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::ComponentInterpretation1"

.SS "\fBD3D_FORMAT_COMPONENT_INTERPRETATION\fP D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::ComponentInterpretation2"

.SS "\fBD3D_FORMAT_COMPONENT_INTERPRETATION\fP D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::ComponentInterpretation3"

.SS "\fBD3D_FORMAT_COMPONENT_NAME\fP D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::ComponentName0"

.SS "\fBD3D_FORMAT_COMPONENT_NAME\fP D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::ComponentName1"

.SS "\fBD3D_FORMAT_COMPONENT_NAME\fP D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::ComponentName2"

.SS "\fBD3D_FORMAT_COMPONENT_NAME\fP D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::ComponentName3"

.SS "UINT D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::DepthAlignment"

.SS "\fBDXGI_FORMAT\fP D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::DXGIFormat"

.SS "UINT D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::HeightAlignment"

.SS "\fBD3D_FORMAT_LAYOUT\fP D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::Layout"

.SS "\fBDXGI_FORMAT\fP D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::ParentFormat"

.SS "const \fBDXGI_FORMAT\fP* D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::pDefaultFormatCastSet"

.SS "\fBBYTE\fP D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::SRGBFormat"

.SS "\fBD3D_FORMAT_TYPE_LEVEL\fP D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::TypeLevel"

.SS "UINT D3D12_PROPERTY_LAYOUT_FORMAT_TABLE::FORMAT_DETAIL::WidthAlignment"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
