.TH "D3D12_SAMPLER_DESC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_SAMPLER_DESC
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBD3D12_FILTER\fP \fBFilter\fP"
.br
.ti -1c
.RI "\fBD3D12_TEXTURE_ADDRESS_MODE\fP \fBAddressU\fP"
.br
.ti -1c
.RI "\fBD3D12_TEXTURE_ADDRESS_MODE\fP \fBAddressV\fP"
.br
.ti -1c
.RI "\fBD3D12_TEXTURE_ADDRESS_MODE\fP \fBAddressW\fP"
.br
.ti -1c
.RI "FLOAT \fBMipLODBias\fP"
.br
.ti -1c
.RI "UINT \fBMaxAnisotropy\fP"
.br
.ti -1c
.RI "\fBD3D12_COMPARISON_FUNC\fP \fBComparisonFunc\fP"
.br
.ti -1c
.RI "FLOAT \fBBorderColor\fP [4]"
.br
.ti -1c
.RI "FLOAT \fBMinLOD\fP"
.br
.ti -1c
.RI "FLOAT \fBMaxLOD\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBD3D12_TEXTURE_ADDRESS_MODE\fP D3D12_SAMPLER_DESC::AddressU"

.SS "\fBD3D12_TEXTURE_ADDRESS_MODE\fP D3D12_SAMPLER_DESC::AddressV"

.SS "\fBD3D12_TEXTURE_ADDRESS_MODE\fP D3D12_SAMPLER_DESC::AddressW"

.SS "FLOAT D3D12_SAMPLER_DESC::BorderColor[4]"

.SS "\fBD3D12_COMPARISON_FUNC\fP D3D12_SAMPLER_DESC::ComparisonFunc"

.SS "\fBD3D12_FILTER\fP D3D12_SAMPLER_DESC::Filter"

.SS "UINT D3D12_SAMPLER_DESC::MaxAnisotropy"

.SS "FLOAT D3D12_SAMPLER_DESC::MaxLOD"

.SS "FLOAT D3D12_SAMPLER_DESC::MinLOD"

.SS "FLOAT D3D12_SAMPLER_DESC::MipLODBias"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
