.TH "D3D12_SUBRESOURCE_FOOTPRINT" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_SUBRESOURCE_FOOTPRINT
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.PP
Inherited by \fBCD3DX12_SUBRESOURCE_FOOTPRINT\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDXGI_FORMAT\fP \fBFormat\fP"
.br
.ti -1c
.RI "UINT \fBWidth\fP"
.br
.ti -1c
.RI "UINT \fBHeight\fP"
.br
.ti -1c
.RI "UINT \fBDepth\fP"
.br
.ti -1c
.RI "UINT \fBRowPitch\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT D3D12_SUBRESOURCE_FOOTPRINT::Depth"

.SS "\fBDXGI_FORMAT\fP D3D12_SUBRESOURCE_FOOTPRINT::Format"

.SS "UINT D3D12_SUBRESOURCE_FOOTPRINT::Height"

.SS "UINT D3D12_SUBRESOURCE_FOOTPRINT::RowPitch"

.SS "UINT D3D12_SUBRESOURCE_FOOTPRINT::Width"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
