.TH "D3D12_SUBRESOURCE_INFO" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_SUBRESOURCE_INFO
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT64 \fBOffset\fP"
.br
.ti -1c
.RI "UINT \fBRowPitch\fP"
.br
.ti -1c
.RI "UINT \fBDepthPitch\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT D3D12_SUBRESOURCE_INFO::DepthPitch"

.SS "UINT64 D3D12_SUBRESOURCE_INFO::Offset"

.SS "UINT D3D12_SUBRESOURCE_INFO::RowPitch"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
