.TH "D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBNodeIndex\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC\fP \fBCodec\fP"
.br
.ti -1c
.RI "\fBDXGI_FORMAT\fP \fBInputFormat\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION\fP \fBCodecConfiguration\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE\fP \fBCodecGopSequence\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_RATE_CONTROL\fP \fBRateControl\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_INTRA_REFRESH_MODE\fP \fBIntraRefresh\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_FRAME_SUBREGION_LAYOUT_MODE\fP \fBSubregionFrameEncoding\fP"
.br
.ti -1c
.RI "UINT \fBResolutionsListCount\fP"
.br
.ti -1c
.RI "const \fBD3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_DESC\fP * \fBpResolutionList\fP"
.br
.ti -1c
.RI "UINT \fBMaxReferenceFramesInDPB\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_VALIDATION_FLAGS\fP \fBValidationFlags\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_SUPPORT_FLAGS\fP \fBSupportFlags\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_PROFILE_DESC\fP \fBSuggestedProfile\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_LEVEL_SETTING\fP \fBSuggestedLevel\fP"
.br
.ti -1c
.RI "\fBD3D12_FEATURE_DATA_VIDEO_ENCODER_RESOLUTION_SUPPORT_LIMITS\fP * \fBpResolutionDependentSupport\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBD3D12_VIDEO_ENCODER_CODEC\fP D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT::Codec"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION\fP D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT::CodecConfiguration"

.SS "\fBD3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE\fP D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT::CodecGopSequence"

.SS "\fBDXGI_FORMAT\fP D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT::InputFormat"

.SS "\fBD3D12_VIDEO_ENCODER_INTRA_REFRESH_MODE\fP D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT::IntraRefresh"

.SS "UINT D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT::MaxReferenceFramesInDPB"

.SS "UINT D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT::NodeIndex"

.SS "\fBD3D12_FEATURE_DATA_VIDEO_ENCODER_RESOLUTION_SUPPORT_LIMITS\fP* D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT::pResolutionDependentSupport"

.SS "const \fBD3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_DESC\fP* D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT::pResolutionList"

.SS "\fBD3D12_VIDEO_ENCODER_RATE_CONTROL\fP D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT::RateControl"

.SS "UINT D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT::ResolutionsListCount"

.SS "\fBD3D12_VIDEO_ENCODER_FRAME_SUBREGION_LAYOUT_MODE\fP D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT::SubregionFrameEncoding"

.SS "\fBD3D12_VIDEO_ENCODER_LEVEL_SETTING\fP D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT::SuggestedLevel"

.SS "\fBD3D12_VIDEO_ENCODER_PROFILE_DESC\fP D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT::SuggestedProfile"

.SS "\fBD3D12_VIDEO_ENCODER_SUPPORT_FLAGS\fP D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT::SupportFlags"

.SS "\fBD3D12_VIDEO_ENCODER_VALIDATION_FLAGS\fP D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT::ValidationFlags"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
