.TH "D3D12_FEATURE_DATA_D3D12_OPTIONS19" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_FEATURE_DATA_D3D12_OPTIONS19
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BOOL \fBMismatchingOutputDimensionsSupported\fP"
.br
.ti -1c
.RI "UINT \fBSupportedSampleCountsWithNoOutputs\fP"
.br
.ti -1c
.RI "BOOL \fBPointSamplingAddressesNeverRoundUp\fP"
.br
.ti -1c
.RI "BOOL \fBRasterizerDesc2Supported\fP"
.br
.ti -1c
.RI "BOOL \fBNarrowQuadrilateralLinesSupported\fP"
.br
.ti -1c
.RI "BOOL \fBAnisoFilterWithPointMipSupported\fP"
.br
.ti -1c
.RI "UINT \fBMaxSamplerDescriptorHeapSize\fP"
.br
.ti -1c
.RI "UINT \fBMaxSamplerDescriptorHeapSizeWithStaticSamplers\fP"
.br
.ti -1c
.RI "UINT \fBMaxViewDescriptorHeapSize\fP"
.br
.ti -1c
.RI "BOOL \fBComputeOnlyCustomHeapSupported\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "BOOL D3D12_FEATURE_DATA_D3D12_OPTIONS19::AnisoFilterWithPointMipSupported"

.SS "BOOL D3D12_FEATURE_DATA_D3D12_OPTIONS19::ComputeOnlyCustomHeapSupported"

.SS "UINT D3D12_FEATURE_DATA_D3D12_OPTIONS19::MaxSamplerDescriptorHeapSize"

.SS "UINT D3D12_FEATURE_DATA_D3D12_OPTIONS19::MaxSamplerDescriptorHeapSizeWithStaticSamplers"

.SS "UINT D3D12_FEATURE_DATA_D3D12_OPTIONS19::MaxViewDescriptorHeapSize"

.SS "BOOL D3D12_FEATURE_DATA_D3D12_OPTIONS19::MismatchingOutputDimensionsSupported"

.SS "BOOL D3D12_FEATURE_DATA_D3D12_OPTIONS19::NarrowQuadrilateralLinesSupported"

.SS "BOOL D3D12_FEATURE_DATA_D3D12_OPTIONS19::PointSamplingAddressesNeverRoundUp"

.SS "BOOL D3D12_FEATURE_DATA_D3D12_OPTIONS19::RasterizerDesc2Supported"

.SS "UINT D3D12_FEATURE_DATA_D3D12_OPTIONS19::SupportedSampleCountsWithNoOutputs"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
