.TH "D3D12_FEATURE_DATA_D3D12_OPTIONS11" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_FEATURE_DATA_D3D12_OPTIONS11
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BOOL \fBAtomicInt64OnDescriptorHeapResourceSupported\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "BOOL D3D12_FEATURE_DATA_D3D12_OPTIONS11::AtomicInt64OnDescriptorHeapResourceSupported"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
