.TH "D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_RATIO_DESC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_RATIO_DESC
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBWidthRatio\fP"
.br
.ti -1c
.RI "UINT \fBHeightRatio\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_RATIO_DESC::HeightRatio"

.SS "UINT D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_RATIO_DESC::WidthRatio"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
