.TH "D3D12_QUERY_DATA_SO_STATISTICS" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_QUERY_DATA_SO_STATISTICS
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT64 \fBNumPrimitivesWritten\fP"
.br
.ti -1c
.RI "UINT64 \fBPrimitivesStorageNeeded\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT64 D3D12_QUERY_DATA_SO_STATISTICS::NumPrimitivesWritten"

.SS "UINT64 D3D12_QUERY_DATA_SO_STATISTICS::PrimitivesStorageNeeded"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
