.TH "D3D12_TEX2D_ARRAY_UAV" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_TEX2D_ARRAY_UAV
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBMipSlice\fP"
.br
.ti -1c
.RI "UINT \fBFirstArraySlice\fP"
.br
.ti -1c
.RI "UINT \fBArraySize\fP"
.br
.ti -1c
.RI "UINT \fBPlaneSlice\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT D3D12_TEX2D_ARRAY_UAV::ArraySize"

.SS "UINT D3D12_TEX2D_ARRAY_UAV::FirstArraySlice"

.SS "UINT D3D12_TEX2D_ARRAY_UAV::MipSlice"

.SS "UINT D3D12_TEX2D_ARRAY_UAV::PlaneSlice"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
