.TH "D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_SUPPORT_HEVC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_SUPPORT_HEVC
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_SUPPORT_HEVC_FLAGS\fP \fBSupportFlags\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_CUSIZE\fP \fBMinLumaCodingUnitSize\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_CUSIZE\fP \fBMaxLumaCodingUnitSize\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_TUSIZE\fP \fBMinLumaTransformUnitSize\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_TUSIZE\fP \fBMaxLumaTransformUnitSize\fP"
.br
.ti -1c
.RI "UCHAR \fBmax_transform_hierarchy_depth_inter\fP"
.br
.ti -1c
.RI "UCHAR \fBmax_transform_hierarchy_depth_intra\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UCHAR D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_SUPPORT_HEVC::max_transform_hierarchy_depth_inter"

.SS "UCHAR D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_SUPPORT_HEVC::max_transform_hierarchy_depth_intra"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_CUSIZE\fP D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_SUPPORT_HEVC::MaxLumaCodingUnitSize"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_TUSIZE\fP D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_SUPPORT_HEVC::MaxLumaTransformUnitSize"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_CUSIZE\fP D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_SUPPORT_HEVC::MinLumaCodingUnitSize"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_TUSIZE\fP D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_SUPPORT_HEVC::MinLumaTransformUnitSize"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_SUPPORT_HEVC_FLAGS\fP D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_SUPPORT_HEVC::SupportFlags"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
