.TH "D3D12_NODE_GPU_INPUT" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_NODE_GPU_INPUT
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBEntrypointIndex\fP"
.br
.ti -1c
.RI "UINT \fBNumRecords\fP"
.br
.ti -1c
.RI "\fBD3D12_GPU_VIRTUAL_ADDRESS_AND_STRIDE\fP \fBRecords\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT D3D12_NODE_GPU_INPUT::EntrypointIndex"

.SS "UINT D3D12_NODE_GPU_INPUT::NumRecords"

.SS "\fBD3D12_GPU_VIRTUAL_ADDRESS_AND_STRIDE\fP D3D12_NODE_GPU_INPUT::Records"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
