.TH "D3D12_FEATURE_DATA_D3D12_OPTIONS" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_FEATURE_DATA_D3D12_OPTIONS
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BOOL \fBDoublePrecisionFloatShaderOps\fP"
.br
.ti -1c
.RI "BOOL \fBOutputMergerLogicOp\fP"
.br
.ti -1c
.RI "\fBD3D12_SHADER_MIN_PRECISION_SUPPORT\fP \fBMinPrecisionSupport\fP"
.br
.ti -1c
.RI "\fBD3D12_TILED_RESOURCES_TIER\fP \fBTiledResourcesTier\fP"
.br
.ti -1c
.RI "\fBD3D12_RESOURCE_BINDING_TIER\fP \fBResourceBindingTier\fP"
.br
.ti -1c
.RI "BOOL \fBPSSpecifiedStencilRefSupported\fP"
.br
.ti -1c
.RI "BOOL \fBTypedUAVLoadAdditionalFormats\fP"
.br
.ti -1c
.RI "BOOL \fBROVsSupported\fP"
.br
.ti -1c
.RI "\fBD3D12_CONSERVATIVE_RASTERIZATION_TIER\fP \fBConservativeRasterizationTier\fP"
.br
.ti -1c
.RI "UINT \fBMaxGPUVirtualAddressBitsPerResource\fP"
.br
.ti -1c
.RI "BOOL \fBStandardSwizzle64KBSupported\fP"
.br
.ti -1c
.RI "\fBD3D12_CROSS_NODE_SHARING_TIER\fP \fBCrossNodeSharingTier\fP"
.br
.ti -1c
.RI "BOOL \fBCrossAdapterRowMajorTextureSupported\fP"
.br
.ti -1c
.RI "BOOL \fBVPAndRTArrayIndexFromAnyShaderFeedingRasterizerSupportedWithoutGSEmulation\fP"
.br
.ti -1c
.RI "\fBD3D12_RESOURCE_HEAP_TIER\fP \fBResourceHeapTier\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBD3D12_CONSERVATIVE_RASTERIZATION_TIER\fP D3D12_FEATURE_DATA_D3D12_OPTIONS::ConservativeRasterizationTier"

.SS "BOOL D3D12_FEATURE_DATA_D3D12_OPTIONS::CrossAdapterRowMajorTextureSupported"

.SS "\fBD3D12_CROSS_NODE_SHARING_TIER\fP D3D12_FEATURE_DATA_D3D12_OPTIONS::CrossNodeSharingTier"

.SS "BOOL D3D12_FEATURE_DATA_D3D12_OPTIONS::DoublePrecisionFloatShaderOps"

.SS "UINT D3D12_FEATURE_DATA_D3D12_OPTIONS::MaxGPUVirtualAddressBitsPerResource"

.SS "\fBD3D12_SHADER_MIN_PRECISION_SUPPORT\fP D3D12_FEATURE_DATA_D3D12_OPTIONS::MinPrecisionSupport"

.SS "BOOL D3D12_FEATURE_DATA_D3D12_OPTIONS::OutputMergerLogicOp"

.SS "BOOL D3D12_FEATURE_DATA_D3D12_OPTIONS::PSSpecifiedStencilRefSupported"

.SS "\fBD3D12_RESOURCE_BINDING_TIER\fP D3D12_FEATURE_DATA_D3D12_OPTIONS::ResourceBindingTier"

.SS "\fBD3D12_RESOURCE_HEAP_TIER\fP D3D12_FEATURE_DATA_D3D12_OPTIONS::ResourceHeapTier"

.SS "BOOL D3D12_FEATURE_DATA_D3D12_OPTIONS::ROVsSupported"

.SS "BOOL D3D12_FEATURE_DATA_D3D12_OPTIONS::StandardSwizzle64KBSupported"

.SS "\fBD3D12_TILED_RESOURCES_TIER\fP D3D12_FEATURE_DATA_D3D12_OPTIONS::TiledResourcesTier"

.SS "BOOL D3D12_FEATURE_DATA_D3D12_OPTIONS::TypedUAVLoadAdditionalFormats"

.SS "BOOL D3D12_FEATURE_DATA_D3D12_OPTIONS::VPAndRTArrayIndexFromAnyShaderFeedingRasterizerSupportedWithoutGSEmulation"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
