.TH "D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS\fP \fBFlags\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_AV1_FRAME_TYPE\fP \fBFrameType\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_AV1_COMP_PREDICTION_TYPE\fP \fBCompoundPredictionType\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS\fP \fBInterpolationFilter\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_AV1_RESTORATION_CONFIG\fP \fBFrameRestorationConfig\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_AV1_TX_MODE\fP \fBTxMode\fP"
.br
.ti -1c
.RI "UINT \fBSuperResDenominator\fP"
.br
.ti -1c
.RI "UINT \fBOrderHint\fP"
.br
.ti -1c
.RI "UINT \fBPictureIndex\fP"
.br
.ti -1c
.RI "UINT \fBTemporalLayerIndexPlus1\fP"
.br
.ti -1c
.RI "UINT \fBSpatialLayerIndexPlus1\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_AV1_REFERENCE_PICTURE_DESCRIPTOR\fP \fBReferenceFramesReconPictureDescriptors\fP [8]"
.br
.ti -1c
.RI "UINT \fBReferenceIndices\fP [7]"
.br
.ti -1c
.RI "UINT \fBPrimaryRefFrame\fP"
.br
.ti -1c
.RI "UINT \fBRefreshFrameFlags\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_CONFIG\fP \fBLoopFilter\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_DELTA_CONFIG\fP \fBLoopFilterDelta\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_CONFIG\fP \fBQuantization\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_DELTA_CONFIG\fP \fBQuantizationDelta\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_AV1_CDEF_CONFIG\fP \fBCDEF\fP"
.br
.ti -1c
.RI "UINT \fBQPMapValuesCount\fP"
.br
.ti -1c
.RI "INT16 * \fBpRateControlQPMap\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_AV1_SEGMENTATION_CONFIG\fP \fBCustomSegmentation\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MAP\fP \fBCustomSegmentsMap\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBD3D12_VIDEO_ENCODER_AV1_CDEF_CONFIG\fP D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::CDEF"

.SS "\fBD3D12_VIDEO_ENCODER_AV1_COMP_PREDICTION_TYPE\fP D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::CompoundPredictionType"

.SS "\fBD3D12_VIDEO_ENCODER_AV1_SEGMENTATION_CONFIG\fP D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::CustomSegmentation"

.SS "\fBD3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MAP\fP D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::CustomSegmentsMap"

.SS "\fBD3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS\fP D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::Flags"

.SS "\fBD3D12_VIDEO_ENCODER_AV1_RESTORATION_CONFIG\fP D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::FrameRestorationConfig"

.SS "\fBD3D12_VIDEO_ENCODER_AV1_FRAME_TYPE\fP D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::FrameType"

.SS "\fBD3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS\fP D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::InterpolationFilter"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_CONFIG\fP D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::LoopFilter"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_DELTA_CONFIG\fP D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::LoopFilterDelta"

.SS "UINT D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::OrderHint"

.SS "UINT D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::PictureIndex"

.SS "INT16* D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::pRateControlQPMap"

.SS "UINT D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::PrimaryRefFrame"

.SS "UINT D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::QPMapValuesCount"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_CONFIG\fP D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::Quantization"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_DELTA_CONFIG\fP D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::QuantizationDelta"

.SS "\fBD3D12_VIDEO_ENCODER_AV1_REFERENCE_PICTURE_DESCRIPTOR\fP D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::ReferenceFramesReconPictureDescriptors[8]"

.SS "UINT D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::ReferenceIndices[7]"

.SS "UINT D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::RefreshFrameFlags"

.SS "UINT D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::SpatialLayerIndexPlus1"

.SS "UINT D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::SuperResDenominator"

.SS "UINT D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::TemporalLayerIndexPlus1"

.SS "\fBD3D12_VIDEO_ENCODER_AV1_TX_MODE\fP D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA::TxMode"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
