.TH "D3D12_VIDEO_PROCESS_INPUT_STREAM_RATE" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_VIDEO_PROCESS_INPUT_STREAM_RATE
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBOutputIndex\fP"
.br
.ti -1c
.RI "UINT \fBInputFrameOrField\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT D3D12_VIDEO_PROCESS_INPUT_STREAM_RATE::InputFrameOrField"

.SS "UINT D3D12_VIDEO_PROCESS_INPUT_STREAM_RATE::OutputIndex"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
