.TH "D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_HEVC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_HEVC
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBGOPLength\fP"
.br
.ti -1c
.RI "UINT \fBPPicturePeriod\fP"
.br
.ti -1c
.RI "UCHAR \fBlog2_max_pic_order_cnt_lsb_minus4\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_HEVC::GOPLength"

.SS "UCHAR D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_HEVC::log2_max_pic_order_cnt_lsb_minus4"

.SS "UINT D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_HEVC::PPicturePeriod"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
