.TH "D3D12_VIDEO_DECODER_HEAP_DESC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_VIDEO_DECODER_HEAP_DESC
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBNodeMask\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_DECODE_CONFIGURATION\fP \fBConfiguration\fP"
.br
.ti -1c
.RI "UINT \fBDecodeWidth\fP"
.br
.ti -1c
.RI "UINT \fBDecodeHeight\fP"
.br
.ti -1c
.RI "\fBDXGI_FORMAT\fP \fBFormat\fP"
.br
.ti -1c
.RI "\fBDXGI_RATIONAL\fP \fBFrameRate\fP"
.br
.ti -1c
.RI "UINT \fBBitRate\fP"
.br
.ti -1c
.RI "UINT \fBMaxDecodePictureBufferCount\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT D3D12_VIDEO_DECODER_HEAP_DESC::BitRate"

.SS "\fBD3D12_VIDEO_DECODE_CONFIGURATION\fP D3D12_VIDEO_DECODER_HEAP_DESC::Configuration"

.SS "UINT D3D12_VIDEO_DECODER_HEAP_DESC::DecodeHeight"

.SS "UINT D3D12_VIDEO_DECODER_HEAP_DESC::DecodeWidth"

.SS "\fBDXGI_FORMAT\fP D3D12_VIDEO_DECODER_HEAP_DESC::Format"

.SS "\fBDXGI_RATIONAL\fP D3D12_VIDEO_DECODER_HEAP_DESC::FrameRate"

.SS "UINT D3D12_VIDEO_DECODER_HEAP_DESC::MaxDecodePictureBufferCount"

.SS "UINT D3D12_VIDEO_DECODER_HEAP_DESC::NodeMask"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
