.TH "D3D12_RESOLVE_VIDEO_MOTION_VECTOR_HEAP_INPUT" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_RESOLVE_VIDEO_MOTION_VECTOR_HEAP_INPUT
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBID3D12VideoMotionVectorHeap\fP * \fBpMotionVectorHeap\fP"
.br
.ti -1c
.RI "UINT \fBPixelWidth\fP"
.br
.ti -1c
.RI "UINT \fBPixelHeight\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT D3D12_RESOLVE_VIDEO_MOTION_VECTOR_HEAP_INPUT::PixelHeight"

.SS "UINT D3D12_RESOLVE_VIDEO_MOTION_VECTOR_HEAP_INPUT::PixelWidth"

.SS "\fBID3D12VideoMotionVectorHeap\fP* D3D12_RESOLVE_VIDEO_MOTION_VECTOR_HEAP_INPUT::pMotionVectorHeap"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
