.TH "D3D12_AUTO_BREADCRUMB_NODE" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_AUTO_BREADCRUMB_NODE
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBpCommandListDebugNameA\fP"
.br
.ti -1c
.RI "const wchar_t * \fBpCommandListDebugNameW\fP"
.br
.ti -1c
.RI "const char * \fBpCommandQueueDebugNameA\fP"
.br
.ti -1c
.RI "const wchar_t * \fBpCommandQueueDebugNameW\fP"
.br
.ti -1c
.RI "\fBID3D12GraphicsCommandList\fP * \fBpCommandList\fP"
.br
.ti -1c
.RI "\fBID3D12CommandQueue\fP * \fBpCommandQueue\fP"
.br
.ti -1c
.RI "UINT32 \fBBreadcrumbCount\fP"
.br
.ti -1c
.RI "const UINT32 * \fBpLastBreadcrumbValue\fP"
.br
.ti -1c
.RI "const \fBD3D12_AUTO_BREADCRUMB_OP\fP * \fBpCommandHistory\fP"
.br
.ti -1c
.RI "const \fBstruct\fP \fBD3D12_AUTO_BREADCRUMB_NODE\fP * \fBpNext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT32 D3D12_AUTO_BREADCRUMB_NODE::BreadcrumbCount"

.SS "const \fBD3D12_AUTO_BREADCRUMB_OP\fP* D3D12_AUTO_BREADCRUMB_NODE::pCommandHistory"

.SS "\fBID3D12GraphicsCommandList\fP* D3D12_AUTO_BREADCRUMB_NODE::pCommandList"

.SS "const char* D3D12_AUTO_BREADCRUMB_NODE::pCommandListDebugNameA"

.SS "const wchar_t* D3D12_AUTO_BREADCRUMB_NODE::pCommandListDebugNameW"

.SS "\fBID3D12CommandQueue\fP* D3D12_AUTO_BREADCRUMB_NODE::pCommandQueue"

.SS "const char* D3D12_AUTO_BREADCRUMB_NODE::pCommandQueueDebugNameA"

.SS "const wchar_t* D3D12_AUTO_BREADCRUMB_NODE::pCommandQueueDebugNameW"

.SS "const UINT32* D3D12_AUTO_BREADCRUMB_NODE::pLastBreadcrumbValue"

.SS "const \fBstruct\fP \fBD3D12_AUTO_BREADCRUMB_NODE\fP* D3D12_AUTO_BREADCRUMB_NODE::pNext"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
