.TH "D3D12_RESOURCE_ALIASING_BARRIER" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_RESOURCE_ALIASING_BARRIER
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBID3D12Resource\fP * \fBpResourceBefore\fP"
.br
.ti -1c
.RI "\fBID3D12Resource\fP * \fBpResourceAfter\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBID3D12Resource\fP* D3D12_RESOURCE_ALIASING_BARRIER::pResourceAfter"

.SS "\fBID3D12Resource\fP* D3D12_RESOURCE_ALIASING_BARRIER::pResourceBefore"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
