.TH "D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDXGI_FORMAT\fP \fBFormat\fP"
.br
.ti -1c
.RI "\fBDXGI_COLOR_SPACE_TYPE\fP \fBColorSpace\fP"
.br
.ti -1c
.RI "\fBDXGI_RATIONAL\fP \fBSourceAspectRatio\fP"
.br
.ti -1c
.RI "\fBDXGI_RATIONAL\fP \fBDestinationAspectRatio\fP"
.br
.ti -1c
.RI "\fBDXGI_RATIONAL\fP \fBFrameRate\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_SIZE_RANGE\fP \fBSourceSizeRange\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_SIZE_RANGE\fP \fBDestinationSizeRange\fP"
.br
.ti -1c
.RI "BOOL \fBEnableOrientation\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_PROCESS_FILTER_FLAGS\fP \fBFilterFlags\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_FRAME_STEREO_FORMAT\fP \fBStereoFormat\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_FIELD_TYPE\fP \fBFieldType\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_PROCESS_DEINTERLACE_FLAGS\fP \fBDeinterlaceMode\fP"
.br
.ti -1c
.RI "BOOL \fBEnableAlphaBlending\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_PROCESS_LUMA_KEY\fP \fBLumaKey\fP"
.br
.ti -1c
.RI "UINT \fBNumPastFrames\fP"
.br
.ti -1c
.RI "UINT \fBNumFutureFrames\fP"
.br
.ti -1c
.RI "BOOL \fBEnableAutoProcessing\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBDXGI_COLOR_SPACE_TYPE\fP D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::ColorSpace"

.SS "\fBD3D12_VIDEO_PROCESS_DEINTERLACE_FLAGS\fP D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::DeinterlaceMode"

.SS "\fBDXGI_RATIONAL\fP D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::DestinationAspectRatio"

.SS "\fBD3D12_VIDEO_SIZE_RANGE\fP D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::DestinationSizeRange"

.SS "BOOL D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::EnableAlphaBlending"

.SS "BOOL D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::EnableAutoProcessing"

.SS "BOOL D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::EnableOrientation"

.SS "\fBD3D12_VIDEO_FIELD_TYPE\fP D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::FieldType"

.SS "\fBD3D12_VIDEO_PROCESS_FILTER_FLAGS\fP D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::FilterFlags"

.SS "\fBDXGI_FORMAT\fP D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::Format"

.SS "\fBDXGI_RATIONAL\fP D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::FrameRate"

.SS "\fBD3D12_VIDEO_PROCESS_LUMA_KEY\fP D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::LumaKey"

.SS "UINT D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::NumFutureFrames"

.SS "UINT D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::NumPastFrames"

.SS "\fBDXGI_RATIONAL\fP D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::SourceAspectRatio"

.SS "\fBD3D12_VIDEO_SIZE_RANGE\fP D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::SourceSizeRange"

.SS "\fBD3D12_VIDEO_FRAME_STEREO_FORMAT\fP D3D12_VIDEO_PROCESS_INPUT_STREAM_DESC::StereoFormat"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
