.TH "D3D12_RESOURCE_ALLOCATION_INFO1" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_RESOURCE_ALLOCATION_INFO1
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT64 \fBOffset\fP"
.br
.ti -1c
.RI "UINT64 \fBAlignment\fP"
.br
.ti -1c
.RI "UINT64 \fBSizeInBytes\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT64 D3D12_RESOURCE_ALLOCATION_INFO1::Alignment"

.SS "UINT64 D3D12_RESOURCE_ALLOCATION_INFO1::Offset"

.SS "UINT64 D3D12_RESOURCE_ALLOCATION_INFO1::SizeInBytes"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
