.TH "D3D12_QUERY_DATA_PIPELINE_STATISTICS1" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_QUERY_DATA_PIPELINE_STATISTICS1
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT64 \fBIAVertices\fP"
.br
.ti -1c
.RI "UINT64 \fBIAPrimitives\fP"
.br
.ti -1c
.RI "UINT64 \fBVSInvocations\fP"
.br
.ti -1c
.RI "UINT64 \fBGSInvocations\fP"
.br
.ti -1c
.RI "UINT64 \fBGSPrimitives\fP"
.br
.ti -1c
.RI "UINT64 \fBCInvocations\fP"
.br
.ti -1c
.RI "UINT64 \fBCPrimitives\fP"
.br
.ti -1c
.RI "UINT64 \fBPSInvocations\fP"
.br
.ti -1c
.RI "UINT64 \fBHSInvocations\fP"
.br
.ti -1c
.RI "UINT64 \fBDSInvocations\fP"
.br
.ti -1c
.RI "UINT64 \fBCSInvocations\fP"
.br
.ti -1c
.RI "UINT64 \fBASInvocations\fP"
.br
.ti -1c
.RI "UINT64 \fBMSInvocations\fP"
.br
.ti -1c
.RI "UINT64 \fBMSPrimitives\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS1::ASInvocations"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS1::CInvocations"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS1::CPrimitives"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS1::CSInvocations"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS1::DSInvocations"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS1::GSInvocations"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS1::GSPrimitives"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS1::HSInvocations"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS1::IAPrimitives"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS1::IAVertices"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS1::MSInvocations"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS1::MSPrimitives"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS1::PSInvocations"

.SS "UINT64 D3D12_QUERY_DATA_PIPELINE_STATISTICS1::VSInvocations"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
