.TH "D3D12_TEXCUBE_ARRAY_SRV" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_TEXCUBE_ARRAY_SRV
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBMostDetailedMip\fP"
.br
.ti -1c
.RI "UINT \fBMipLevels\fP"
.br
.ti -1c
.RI "UINT \fBFirst2DArrayFace\fP"
.br
.ti -1c
.RI "UINT \fBNumCubes\fP"
.br
.ti -1c
.RI "FLOAT \fBResourceMinLODClamp\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT D3D12_TEXCUBE_ARRAY_SRV::First2DArrayFace"

.SS "UINT D3D12_TEXCUBE_ARRAY_SRV::MipLevels"

.SS "UINT D3D12_TEXCUBE_ARRAY_SRV::MostDetailedMip"

.SS "UINT D3D12_TEXCUBE_ARRAY_SRV::NumCubes"

.SS "FLOAT D3D12_TEXCUBE_ARRAY_SRV::ResourceMinLODClamp"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
