.TH "D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264_FLAGS\fP \fBConfigurationFlags\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264_DIRECT_MODES\fP \fBDirectModeConfig\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264_SLICES_DEBLOCKING_MODES\fP \fBDisableDeblockingFilterConfig\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264_FLAGS\fP D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264::ConfigurationFlags"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264_DIRECT_MODES\fP D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264::DirectModeConfig"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264_SLICES_DEBLOCKING_MODES\fP D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264::DisableDeblockingFilterConfig"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
