.TH "D3D12_FEATURE_DATA_VIDEO_EXTENSION_COMMAND_SIZE" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_FEATURE_DATA_VIDEO_EXTENSION_COMMAND_SIZE
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBNodeIndex\fP"
.br
.ti -1c
.RI "GUID \fBCommandId\fP"
.br
.ti -1c
.RI "const \fBvoid\fP * \fBpCreationParameters\fP"
.br
.ti -1c
.RI "SIZE_T \fBCreationParametersSizeInBytes\fP"
.br
.ti -1c
.RI "UINT64 \fBMemoryPoolL0Size\fP"
.br
.ti -1c
.RI "UINT64 \fBMemoryPoolL1Size\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "GUID D3D12_FEATURE_DATA_VIDEO_EXTENSION_COMMAND_SIZE::CommandId"

.SS "SIZE_T D3D12_FEATURE_DATA_VIDEO_EXTENSION_COMMAND_SIZE::CreationParametersSizeInBytes"

.SS "UINT64 D3D12_FEATURE_DATA_VIDEO_EXTENSION_COMMAND_SIZE::MemoryPoolL0Size"

.SS "UINT64 D3D12_FEATURE_DATA_VIDEO_EXTENSION_COMMAND_SIZE::MemoryPoolL1Size"

.SS "UINT D3D12_FEATURE_DATA_VIDEO_EXTENSION_COMMAND_SIZE::NodeIndex"

.SS "const \fBvoid\fP* D3D12_FEATURE_DATA_VIDEO_EXTENSION_COMMAND_SIZE::pCreationParameters"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
