.TH "D3D12_FEATURE_DATA_FEATURE_LEVELS" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_FEATURE_DATA_FEATURE_LEVELS
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBNumFeatureLevels\fP"
.br
.ti -1c
.RI "const \fBD3D_FEATURE_LEVEL\fP * \fBpFeatureLevelsRequested\fP"
.br
.ti -1c
.RI "\fBD3D_FEATURE_LEVEL\fP \fBMaxSupportedFeatureLevel\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBD3D_FEATURE_LEVEL\fP D3D12_FEATURE_DATA_FEATURE_LEVELS::MaxSupportedFeatureLevel"

.SS "UINT D3D12_FEATURE_DATA_FEATURE_LEVELS::NumFeatureLevels"

.SS "const \fBD3D_FEATURE_LEVEL\fP* D3D12_FEATURE_DATA_FEATURE_LEVELS::pFeatureLevelsRequested"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
