.TH "D3D12_DEVICE_REMOVED_EXTENDED_DATA1" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_DEVICE_REMOVED_EXTENDED_DATA1
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "HRESULT \fBDeviceRemovedReason\fP"
.br
.ti -1c
.RI "\fBD3D12_DRED_AUTO_BREADCRUMBS_OUTPUT\fP \fBAutoBreadcrumbsOutput\fP"
.br
.ti -1c
.RI "\fBD3D12_DRED_PAGE_FAULT_OUTPUT\fP \fBPageFaultOutput\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBD3D12_DRED_AUTO_BREADCRUMBS_OUTPUT\fP D3D12_DEVICE_REMOVED_EXTENDED_DATA1::AutoBreadcrumbsOutput"

.SS "HRESULT D3D12_DEVICE_REMOVED_EXTENDED_DATA1::DeviceRemovedReason"

.SS "\fBD3D12_DRED_PAGE_FAULT_OUTPUT\fP D3D12_DEVICE_REMOVED_EXTENDED_DATA1::PageFaultOutput"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
