.TH "D3D12_RENDER_TARGET_BLEND_DESC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_RENDER_TARGET_BLEND_DESC
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BOOL \fBBlendEnable\fP"
.br
.ti -1c
.RI "BOOL \fBLogicOpEnable\fP"
.br
.ti -1c
.RI "\fBD3D12_BLEND\fP \fBSrcBlend\fP"
.br
.ti -1c
.RI "\fBD3D12_BLEND\fP \fBDestBlend\fP"
.br
.ti -1c
.RI "\fBD3D12_BLEND_OP\fP \fBBlendOp\fP"
.br
.ti -1c
.RI "\fBD3D12_BLEND\fP \fBSrcBlendAlpha\fP"
.br
.ti -1c
.RI "\fBD3D12_BLEND\fP \fBDestBlendAlpha\fP"
.br
.ti -1c
.RI "\fBD3D12_BLEND_OP\fP \fBBlendOpAlpha\fP"
.br
.ti -1c
.RI "\fBD3D12_LOGIC_OP\fP \fBLogicOp\fP"
.br
.ti -1c
.RI "UINT8 \fBRenderTargetWriteMask\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "BOOL D3D12_RENDER_TARGET_BLEND_DESC::BlendEnable"

.SS "\fBD3D12_BLEND_OP\fP D3D12_RENDER_TARGET_BLEND_DESC::BlendOp"

.SS "\fBD3D12_BLEND_OP\fP D3D12_RENDER_TARGET_BLEND_DESC::BlendOpAlpha"

.SS "\fBD3D12_BLEND\fP D3D12_RENDER_TARGET_BLEND_DESC::DestBlend"

.SS "\fBD3D12_BLEND\fP D3D12_RENDER_TARGET_BLEND_DESC::DestBlendAlpha"

.SS "\fBD3D12_LOGIC_OP\fP D3D12_RENDER_TARGET_BLEND_DESC::LogicOp"

.SS "BOOL D3D12_RENDER_TARGET_BLEND_DESC::LogicOpEnable"

.SS "UINT8 D3D12_RENDER_TARGET_BLEND_DESC::RenderTargetWriteMask"

.SS "\fBD3D12_BLEND\fP D3D12_RENDER_TARGET_BLEND_DESC::SrcBlend"

.SS "\fBD3D12_BLEND\fP D3D12_RENDER_TARGET_BLEND_DESC::SrcBlendAlpha"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
