.TH "adhed/d3d12compatibility.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/d3d12compatibility.h
.SH SYNOPSIS
.br
.PP
\fR#include 'rpc\&.h'\fP
.br
\fR#include 'rpcndr\&.h'\fP
.br
\fR#include 'windows\&.h'\fP
.br
\fR#include 'ole2\&.h'\fP
.br
\fR#include 'oaidl\&.h'\fP
.br
\fR#include 'ocidl\&.h'\fP
.br
\fR#include 'd3d11on12\&.h'\fP
.br
\fR#include <winapifamily\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__REQUIRED_RPCNDR_H_VERSION__\fP   500"
.br
.ti -1c
.RI "#define \fB__REQUIRED_RPCSAL_H_VERSION__\fP   100"
.br
.ti -1c
.RI "#define \fBDECLSPEC_XFGVIRT\fP(base,  \fBfunc\fP)"
.br
.ti -1c
.RI "#define \fB__ID3D12CompatibilityDevice_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__D3D11On12CreatorID_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__D3D9On12CreatorID_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__OpenGLOn12CreatorID_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__OpenCLOn12CreatorID_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__VulkanOn12CreatorID_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__DirectMLTensorFlowCreatorID_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__DirectMLPyTorchCreatorID_FWD_DEFINED__\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef interface ID3D12CompatibilityDevice \fBID3D12CompatibilityDevice\fP"
.br
.ti -1c
.RI "typedef interface D3D11On12CreatorID \fBD3D11On12CreatorID\fP"
.br
.ti -1c
.RI "typedef interface D3D9On12CreatorID \fBD3D9On12CreatorID\fP"
.br
.ti -1c
.RI "typedef interface OpenGLOn12CreatorID \fBOpenGLOn12CreatorID\fP"
.br
.ti -1c
.RI "typedef interface OpenCLOn12CreatorID \fBOpenCLOn12CreatorID\fP"
.br
.ti -1c
.RI "typedef interface VulkanOn12CreatorID \fBVulkanOn12CreatorID\fP"
.br
.ti -1c
.RI "typedef interface DirectMLTensorFlowCreatorID \fBDirectMLTensorFlowCreatorID\fP"
.br
.ti -1c
.RI "typedef interface DirectMLPyTorchCreatorID \fBDirectMLPyTorchCreatorID\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12CompatibilityDevice, 0x8f1c0e3c, 0xfae3, 0x4a82, 0xb0, 0x98, 0xbf, 0xe1, 0x70, 0x82, 0x07, 0xff)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_D3D11On12CreatorID, 0xedbf5678, 0x2960, 0x4e81, 0x84, 0x29, 0x99, 0xd4, 0xb2, 0x63, 0x0c, 0x4e)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_D3D9On12CreatorID, 0xfffcbb7f, 0x15d3, 0x42a2, 0x84, 0x1e, 0x9d, 0x8d, 0x32, 0xf3, 0x7d, 0xdd)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_OpenGLOn12CreatorID, 0x6bb3cd34, 0x0d19, 0x45ab, 0x97, 0xed, 0xd7, 0x20, 0xba, 0x3d, 0xfc, 0x80)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_OpenCLOn12CreatorID, 0x3f76bb74, 0x91b5, 0x4a88, 0xb1, 0x26, 0x20, 0xca, 0x03, 0x31, 0xcd, 0x60)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_VulkanOn12CreatorID, 0xbc806e01, 0x3052, 0x406c, 0xa3, 0xe8, 0x9f, 0xc0, 0x7f, 0x04, 0x8f, 0x98)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_DirectMLTensorFlowCreatorID, 0xcb7490ac, 0x8a0f, 0x44ec, 0x9b, 0x7b, 0x6f, 0x4c, 0xaf, 0xe8, 0xe9, 0xab)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_DirectMLPyTorchCreatorID, 0xaf029192, 0xfba1, 0x4b05, 0x91, 0x16, 0x23, 0x5e, 0x06, 0x56, 0x03, 0x54)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "RPC_IF_HANDLE \fB__MIDL_itf_d3d12compatibility_0000_0008_v0_0_c_ifspec\fP"
.br
.ti -1c
.RI "RPC_IF_HANDLE \fB__MIDL_itf_d3d12compatibility_0000_0008_v0_0_s_ifspec\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __D3D11On12CreatorID_FWD_DEFINED__"

.SS "#define __D3D9On12CreatorID_FWD_DEFINED__"

.SS "#define __DirectMLPyTorchCreatorID_FWD_DEFINED__"

.SS "#define __DirectMLTensorFlowCreatorID_FWD_DEFINED__"

.SS "#define __ID3D12CompatibilityDevice_FWD_DEFINED__"

.SS "#define __OpenCLOn12CreatorID_FWD_DEFINED__"

.SS "#define __OpenGLOn12CreatorID_FWD_DEFINED__"

.SS "#define __REQUIRED_RPCNDR_H_VERSION__   500"

.SS "#define __REQUIRED_RPCSAL_H_VERSION__   100"

.SS "#define __VulkanOn12CreatorID_FWD_DEFINED__"

.SS "#define DECLSPEC_XFGVIRT( base,  \fBfunc\fP)"

.SH "Typedef Documentation"
.PP 
.SS "typedef interface D3D11On12CreatorID D3D11On12CreatorID"

.SS "typedef interface D3D9On12CreatorID D3D9On12CreatorID"

.SS "typedef interface DirectMLPyTorchCreatorID DirectMLPyTorchCreatorID"

.SS "typedef interface DirectMLTensorFlowCreatorID DirectMLTensorFlowCreatorID"

.SS "typedef interface ID3D12CompatibilityDevice ID3D12CompatibilityDevice"

.SS "typedef interface OpenCLOn12CreatorID OpenCLOn12CreatorID"

.SS "typedef interface OpenGLOn12CreatorID OpenGLOn12CreatorID"

.SS "typedef interface VulkanOn12CreatorID VulkanOn12CreatorID"

.SH "Function Documentation"
.PP 
.SS "DEFINE_GUID (IID_D3D11On12CreatorID , 0xedbf5678 , 0x2960 , 0x4e81 , 0x84 , 0x29 , 0x99 , 0xd4 , 0xb2 , 0x63 , 0x0c , 0x4e )"

.SS "DEFINE_GUID (IID_D3D9On12CreatorID , 0xfffcbb7f , 0x15d3 , 0x42a2 , 0x84 , 0x1e , 0x9d , 0x8d , 0x32 , 0xf3 , 0x7d , 0xdd )"

.SS "DEFINE_GUID (IID_DirectMLPyTorchCreatorID , 0xaf029192 , 0xfba1 , 0x4b05 , 0x91 , 0x16 , 0x23 , 0x5e , 0x06 , 0x56 , 0x03 , 0x54 )"

.SS "DEFINE_GUID (IID_DirectMLTensorFlowCreatorID , 0xcb7490ac , 0x8a0f , 0x44ec , 0x9b , 0x7b , 0x6f , 0x4c , 0xaf , 0xe8 , 0xe9 , 0xab )"

.SS "DEFINE_GUID (IID_ID3D12CompatibilityDevice , 0x8f1c0e3c , 0xfae3 , 0x4a82 , 0xb0 , 0x98 , 0xbf , 0xe1 , 0x70 , 0x82 , 0x07 , 0xff )"

.SS "DEFINE_GUID (IID_OpenCLOn12CreatorID , 0x3f76bb74 , 0x91b5 , 0x4a88 , 0xb1 , 0x26 , 0x20 , 0xca , 0x03 , 0x31 , 0xcd , 0x60 )"

.SS "DEFINE_GUID (IID_OpenGLOn12CreatorID , 0x6bb3cd34 , 0x0d19 , 0x45ab , 0x97 , 0xed , 0xd7 , 0x20 , 0xba , 0x3d , 0xfc , 0x80 )"

.SS "DEFINE_GUID (IID_VulkanOn12CreatorID , 0xbc806e01 , 0x3052 , 0x406c , 0xa3 , 0xe8 , 0x9f , 0xc0 , 0x7f , 0x04 , 0x8f , 0x98 )"

.SH "Variable Documentation"
.PP 
.SS "RPC_IF_HANDLE __MIDL_itf_d3d12compatibility_0000_0008_v0_0_c_ifspec\fR [extern]\fP"

.SS "RPC_IF_HANDLE __MIDL_itf_d3d12compatibility_0000_0008_v0_0_s_ifspec\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
