.TH "D3D12_SUBRESOURCE_TILING" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_SUBRESOURCE_TILING
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.PP
Inherited by \fBCD3DX12_SUBRESOURCE_TILING\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBWidthInTiles\fP"
.br
.ti -1c
.RI "UINT16 \fBHeightInTiles\fP"
.br
.ti -1c
.RI "UINT16 \fBDepthInTiles\fP"
.br
.ti -1c
.RI "UINT \fBStartTileIndexInOverallResource\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT16 D3D12_SUBRESOURCE_TILING::DepthInTiles"

.SS "UINT16 D3D12_SUBRESOURCE_TILING::HeightInTiles"

.SS "UINT D3D12_SUBRESOURCE_TILING::StartTileIndexInOverallResource"

.SS "UINT D3D12_SUBRESOURCE_TILING::WidthInTiles"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
