.TH "D3D12_VIDEO_ENCODER_AV1_SEGMENT_DATA" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_VIDEO_ENCODER_AV1_SEGMENT_DATA
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT64 \fBEnabledFeatures\fP"
.br
.ti -1c
.RI "INT64 \fBFeatureValue\fP [8]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT64 D3D12_VIDEO_ENCODER_AV1_SEGMENT_DATA::EnabledFeatures"

.SS "INT64 D3D12_VIDEO_ENCODER_AV1_SEGMENT_DATA::FeatureValue[8]"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
