.TH "D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT64 \fBMinSizeInBytes\fP"
.br
.ti -1c
.RI "UINT64 \fBMaxSizeInBytes\fP"
.br
.ti -1c
.RI "UINT \fBSizeGranularityInBytes\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT64 D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS::MaxSizeInBytes"

.SS "UINT64 D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS::MinSizeInBytes"

.SS "UINT D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS::SizeGranularityInBytes"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
