.TH "D3D12_VIDEO_ENCODER_AV1_SEQUENCE_STRUCTURE" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_VIDEO_ENCODER_AV1_SEQUENCE_STRUCTURE
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBIntraDistance\fP"
.br
.ti -1c
.RI "UINT \fBInterFramePeriod\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT D3D12_VIDEO_ENCODER_AV1_SEQUENCE_STRUCTURE::InterFramePeriod"

.SS "UINT D3D12_VIDEO_ENCODER_AV1_SEQUENCE_STRUCTURE::IntraDistance"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
