.TH "D3D12_VIEWPORT" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_VIEWPORT
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.PP
Inherited by \fBCD3DX12_VIEWPORT\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FLOAT \fBTopLeftX\fP"
.br
.ti -1c
.RI "FLOAT \fBTopLeftY\fP"
.br
.ti -1c
.RI "FLOAT \fBWidth\fP"
.br
.ti -1c
.RI "FLOAT \fBHeight\fP"
.br
.ti -1c
.RI "FLOAT \fBMinDepth\fP"
.br
.ti -1c
.RI "FLOAT \fBMaxDepth\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "FLOAT D3D12_VIEWPORT::Height"

.SS "FLOAT D3D12_VIEWPORT::MaxDepth"

.SS "FLOAT D3D12_VIEWPORT::MinDepth"

.SS "FLOAT D3D12_VIEWPORT::TopLeftX"

.SS "FLOAT D3D12_VIEWPORT::TopLeftY"

.SS "FLOAT D3D12_VIEWPORT::Width"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
