.TH "D3D12_THREAD_LAUNCH_OVERRIDES" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_THREAD_LAUNCH_OVERRIDES
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const UINT * \fBpLocalRootArgumentsTableIndex\fP"
.br
.ti -1c
.RI "const BOOL * \fBpProgramEntry\fP"
.br
.ti -1c
.RI "const \fBD3D12_NODE_ID\fP * \fBpNewName\fP"
.br
.ti -1c
.RI "const \fBD3D12_NODE_ID\fP * \fBpShareInputOf\fP"
.br
.ti -1c
.RI "UINT \fBNumOutputOverrides\fP"
.br
.ti -1c
.RI "const \fBD3D12_NODE_OUTPUT_OVERRIDES\fP * \fBpOutputOverrides\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT D3D12_THREAD_LAUNCH_OVERRIDES::NumOutputOverrides"

.SS "const UINT* D3D12_THREAD_LAUNCH_OVERRIDES::pLocalRootArgumentsTableIndex"

.SS "const \fBD3D12_NODE_ID\fP* D3D12_THREAD_LAUNCH_OVERRIDES::pNewName"

.SS "const \fBD3D12_NODE_OUTPUT_OVERRIDES\fP* D3D12_THREAD_LAUNCH_OVERRIDES::pOutputOverrides"

.SS "const BOOL* D3D12_THREAD_LAUNCH_OVERRIDES::pProgramEntry"

.SS "const \fBD3D12_NODE_ID\fP* D3D12_THREAD_LAUNCH_OVERRIDES::pShareInputOf"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
