.TH "D3D12_GPU_DESCRIPTOR_HANDLE" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_GPU_DESCRIPTOR_HANDLE
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.PP
Inherited by \fBCD3DX12_GPU_DESCRIPTOR_HANDLE\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT64 \fBptr\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT64 D3D12_GPU_DESCRIPTOR_HANDLE::ptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
