.TH "D3D12_DRED_BREADCRUMB_CONTEXT" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_DRED_BREADCRUMB_CONTEXT
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBBreadcrumbIndex\fP"
.br
.ti -1c
.RI "const wchar_t * \fBpContextString\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT D3D12_DRED_BREADCRUMB_CONTEXT::BreadcrumbIndex"

.SS "const wchar_t* D3D12_DRED_BREADCRUMB_CONTEXT::pContextString"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
