.TH "adhed/d3d12sdklayers.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/d3d12sdklayers.h
.SH SYNOPSIS
.br
.PP
\fR#include 'rpc\&.h'\fP
.br
\fR#include 'rpcndr\&.h'\fP
.br
\fR#include 'windows\&.h'\fP
.br
\fR#include 'ole2\&.h'\fP
.br
\fR#include 'oaidl\&.h'\fP
.br
\fR#include 'ocidl\&.h'\fP
.br
\fR#include 'd3d12\&.h'\fP
.br
\fR#include <winapifamily\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__REQUIRED_RPCNDR_H_VERSION__\fP   500"
.br
.ti -1c
.RI "#define \fB__REQUIRED_RPCSAL_H_VERSION__\fP   100"
.br
.ti -1c
.RI "#define \fBDECLSPEC_XFGVIRT\fP(base,  \fBfunc\fP)"
.br
.ti -1c
.RI "#define \fB__ID3D12Debug_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12Debug1_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12Debug2_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12Debug3_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12Debug4_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12Debug5_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12Debug6_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12DebugDevice1_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12DebugDevice_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12DebugDevice2_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12DebugCommandQueue_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12DebugCommandQueue1_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12DebugCommandList1_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12DebugCommandList_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12DebugCommandList2_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12DebugCommandList3_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12SharingContract_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12ManualWriteTrackingResource_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12InfoQueue_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__ID3D12InfoQueue1_FWD_DEFINED__\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef interface \fBID3D12Debug\fP \fBID3D12Debug\fP"
.br
.ti -1c
.RI "typedef interface \fBID3D12Debug1\fP \fBID3D12Debug1\fP"
.br
.ti -1c
.RI "typedef interface \fBID3D12Debug2\fP \fBID3D12Debug2\fP"
.br
.ti -1c
.RI "typedef interface \fBID3D12Debug3\fP \fBID3D12Debug3\fP"
.br
.ti -1c
.RI "typedef interface \fBID3D12Debug4\fP \fBID3D12Debug4\fP"
.br
.ti -1c
.RI "typedef interface \fBID3D12Debug5\fP \fBID3D12Debug5\fP"
.br
.ti -1c
.RI "typedef interface \fBID3D12Debug6\fP \fBID3D12Debug6\fP"
.br
.ti -1c
.RI "typedef interface ID3D12DebugDevice1 \fBID3D12DebugDevice1\fP"
.br
.ti -1c
.RI "typedef interface ID3D12DebugDevice \fBID3D12DebugDevice\fP"
.br
.ti -1c
.RI "typedef interface ID3D12DebugDevice2 \fBID3D12DebugDevice2\fP"
.br
.ti -1c
.RI "typedef interface ID3D12DebugCommandQueue \fBID3D12DebugCommandQueue\fP"
.br
.ti -1c
.RI "typedef interface ID3D12DebugCommandQueue1 \fBID3D12DebugCommandQueue1\fP"
.br
.ti -1c
.RI "typedef interface ID3D12DebugCommandList1 \fBID3D12DebugCommandList1\fP"
.br
.ti -1c
.RI "typedef interface ID3D12DebugCommandList \fBID3D12DebugCommandList\fP"
.br
.ti -1c
.RI "typedef interface ID3D12DebugCommandList2 \fBID3D12DebugCommandList2\fP"
.br
.ti -1c
.RI "typedef interface ID3D12DebugCommandList3 \fBID3D12DebugCommandList3\fP"
.br
.ti -1c
.RI "typedef interface ID3D12SharingContract \fBID3D12SharingContract\fP"
.br
.ti -1c
.RI "typedef interface ID3D12ManualWriteTrackingResource \fBID3D12ManualWriteTrackingResource\fP"
.br
.ti -1c
.RI "typedef interface ID3D12InfoQueue \fBID3D12InfoQueue\fP"
.br
.ti -1c
.RI "typedef interface ID3D12InfoQueue1 \fBID3D12InfoQueue1\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12Debug, 0x344488b7, 0x6846, 0x474b, 0xb9, 0x89, 0xf0, 0x27, 0x44, 0x82, 0x45, 0xe0)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12Debug1, 0xaffaa4ca, 0x63fe, 0x4d8e, 0xb8, 0xad, 0x15, 0x90, 0x00, 0xaf, 0x43, 0x04)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12Debug2, 0x93a665c4, 0xa3b2, 0x4e5d, 0xb6, 0x92, 0xa2, 0x6a, 0xe1, 0x4e, 0x33, 0x74)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12Debug3, 0x5cf4e58f, 0xf671, 0x4ff1, 0xa5, 0x42, 0x36, 0x86, 0xe3, 0xd1, 0x53, 0xd1)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12Debug4, 0x014b816e, 0x9ec5, 0x4a2f, 0xa8, 0x45, 0xff, 0xbe, 0x44, 0x1c, 0xe1, 0x3a)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12Debug5, 0x548d6b12, 0x09fa, 0x40e0, 0x90, 0x69, 0x5d, 0xcd, 0x58, 0x9a, 0x52, 0xc9)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12Debug6, 0x82a816d6, 0x5d01, 0x4157, 0x97, 0xd0, 0x49, 0x75, 0x46, 0x3f, 0xd1, 0xed)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12DebugDevice1, 0xa9b71770, 0xd099, 0x4a65, 0xa6, 0x98, 0x3d, 0xee, 0x10, 0x02, 0x0f, 0x88)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12DebugDevice, 0x3febd6dd, 0x4973, 0x4787, 0x81, 0x94, 0xe4, 0x5f, 0x9e, 0x28, 0x92, 0x3e)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12DebugDevice2, 0x60eccbc1, 0x378d, 0x4df1, 0x89, 0x4c, 0xf8, 0xac, 0x5c, 0xe4, 0xd7, 0xdd)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12DebugCommandQueue, 0x09e0bf36, 0x54ac, 0x484f, 0x88, 0x47, 0x4b, 0xae, 0xea, 0xb6, 0x05, 0x3a)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12DebugCommandQueue1, 0x16be35a2, 0xbfd6, 0x49f2, 0xbc, 0xae, 0xea, 0xae, 0x4a, 0xff, 0x86, 0x2d)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12DebugCommandList1, 0x102ca951, 0x311b, 0x4b01, 0xb1, 0x1f, 0xec, 0xb8, 0x3e, 0x06, 0x1b, 0x37)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12DebugCommandList, 0x09e0bf36, 0x54ac, 0x484f, 0x88, 0x47, 0x4b, 0xae, 0xea, 0xb6, 0x05, 0x3f)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12DebugCommandList2, 0xaeb575cf, 0x4e06, 0x48be, 0xba, 0x3b, 0xc4, 0x50, 0xfc, 0x96, 0x65, 0x2e)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12DebugCommandList3, 0x197d5e15, 0x4d37, 0x4d34, 0xaf, 0x78, 0x72, 0x4c, 0xd7, 0x0f, 0xdb, 0x1f)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12SharingContract, 0x0adf7d52, 0x929c, 0x4e61, 0xad, 0xdb, 0xff, 0xed, 0x30, 0xde, 0x66, 0xef)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12ManualWriteTrackingResource, 0x86ca3b85, 0x49ad, 0x4b6e, 0xae, 0xd5, 0xed, 0xdb, 0x18, 0x54, 0x0f, 0x41)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12InfoQueue, 0x0742a90b, 0xc387, 0x483f, 0xb9, 0x46, 0x30, 0xa7, 0xe4, 0xe6, 0x14, 0x58)"
.br
.ti -1c
.RI "\fBDEFINE_GUID\fP (IID_ID3D12InfoQueue1, 0x2852dd88, 0xb484, 0x4c0c, 0xb6, 0xb1, 0x67, 0x16, 0x85, 0x00, 0xe6, 0x00)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "RPC_IF_HANDLE \fB__MIDL_itf_d3d12sdklayers_0000_0020_v0_0_c_ifspec\fP"
.br
.ti -1c
.RI "RPC_IF_HANDLE \fB__MIDL_itf_d3d12sdklayers_0000_0020_v0_0_s_ifspec\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __ID3D12Debug1_FWD_DEFINED__"

.SS "#define __ID3D12Debug2_FWD_DEFINED__"

.SS "#define __ID3D12Debug3_FWD_DEFINED__"

.SS "#define __ID3D12Debug4_FWD_DEFINED__"

.SS "#define __ID3D12Debug5_FWD_DEFINED__"

.SS "#define __ID3D12Debug6_FWD_DEFINED__"

.SS "#define __ID3D12Debug_FWD_DEFINED__"

.SS "#define __ID3D12DebugCommandList1_FWD_DEFINED__"

.SS "#define __ID3D12DebugCommandList2_FWD_DEFINED__"

.SS "#define __ID3D12DebugCommandList3_FWD_DEFINED__"

.SS "#define __ID3D12DebugCommandList_FWD_DEFINED__"

.SS "#define __ID3D12DebugCommandQueue1_FWD_DEFINED__"

.SS "#define __ID3D12DebugCommandQueue_FWD_DEFINED__"

.SS "#define __ID3D12DebugDevice1_FWD_DEFINED__"

.SS "#define __ID3D12DebugDevice2_FWD_DEFINED__"

.SS "#define __ID3D12DebugDevice_FWD_DEFINED__"

.SS "#define __ID3D12InfoQueue1_FWD_DEFINED__"

.SS "#define __ID3D12InfoQueue_FWD_DEFINED__"

.SS "#define __ID3D12ManualWriteTrackingResource_FWD_DEFINED__"

.SS "#define __ID3D12SharingContract_FWD_DEFINED__"

.SS "#define __REQUIRED_RPCNDR_H_VERSION__   500"

.SS "#define __REQUIRED_RPCSAL_H_VERSION__   100"

.SS "#define DECLSPEC_XFGVIRT( base,  \fBfunc\fP)"

.SH "Typedef Documentation"
.PP 
.SS "typedef interface \fBID3D12Debug\fP \fBID3D12Debug\fP"

.SS "typedef interface \fBID3D12Debug1\fP \fBID3D12Debug1\fP"

.SS "typedef interface \fBID3D12Debug2\fP \fBID3D12Debug2\fP"

.SS "typedef interface \fBID3D12Debug3\fP \fBID3D12Debug3\fP"

.SS "typedef interface \fBID3D12Debug4\fP \fBID3D12Debug4\fP"

.SS "typedef interface \fBID3D12Debug5\fP \fBID3D12Debug5\fP"

.SS "typedef interface \fBID3D12Debug6\fP \fBID3D12Debug6\fP"

.SS "typedef interface ID3D12DebugCommandList ID3D12DebugCommandList"

.SS "typedef interface ID3D12DebugCommandList1 ID3D12DebugCommandList1"

.SS "typedef interface ID3D12DebugCommandList2 ID3D12DebugCommandList2"

.SS "typedef interface ID3D12DebugCommandList3 ID3D12DebugCommandList3"

.SS "typedef interface ID3D12DebugCommandQueue ID3D12DebugCommandQueue"

.SS "typedef interface ID3D12DebugCommandQueue1 ID3D12DebugCommandQueue1"

.SS "typedef interface ID3D12DebugDevice ID3D12DebugDevice"

.SS "typedef interface ID3D12DebugDevice1 ID3D12DebugDevice1"

.SS "typedef interface ID3D12DebugDevice2 ID3D12DebugDevice2"

.SS "typedef interface ID3D12InfoQueue ID3D12InfoQueue"

.SS "typedef interface ID3D12InfoQueue1 ID3D12InfoQueue1"

.SS "typedef interface ID3D12ManualWriteTrackingResource ID3D12ManualWriteTrackingResource"

.SS "typedef interface ID3D12SharingContract ID3D12SharingContract"

.SH "Function Documentation"
.PP 
.SS "DEFINE_GUID (IID_ID3D12Debug , 0x344488b7 , 0x6846 , 0x474b , 0xb9 , 0x89 , 0xf0 , 0x27 , 0x44 , 0x82 , 0x45 , 0xe0 )"

.SS "DEFINE_GUID (IID_ID3D12Debug1 , 0xaffaa4ca , 0x63fe , 0x4d8e , 0xb8 , 0xad , 0x15 , 0x90 , 0x00 , 0xaf , 0x43 , 0x04 )"

.SS "DEFINE_GUID (IID_ID3D12Debug2 , 0x93a665c4 , 0xa3b2 , 0x4e5d , 0xb6 , 0x92 , 0xa2 , 0x6a , 0xe1 , 0x4e , 0x33 , 0x74 )"

.SS "DEFINE_GUID (IID_ID3D12Debug3 , 0x5cf4e58f , 0xf671 , 0x4ff1 , 0xa5 , 0x42 , 0x36 , 0x86 , 0xe3 , 0xd1 , 0x53 , 0xd1 )"

.SS "DEFINE_GUID (IID_ID3D12Debug4 , 0x014b816e , 0x9ec5 , 0x4a2f , 0xa8 , 0x45 , 0xff , 0xbe , 0x44 , 0x1c , 0xe1 , 0x3a )"

.SS "DEFINE_GUID (IID_ID3D12Debug5 , 0x548d6b12 , 0x09fa , 0x40e0 , 0x90 , 0x69 , 0x5d , 0xcd , 0x58 , 0x9a , 0x52 , 0xc9 )"

.SS "DEFINE_GUID (IID_ID3D12Debug6 , 0x82a816d6 , 0x5d01 , 0x4157 , 0x97 , 0xd0 , 0x49 , 0x75 , 0x46 , 0x3f , 0xd1 , 0xed )"

.SS "DEFINE_GUID (IID_ID3D12DebugCommandList , 0x09e0bf36 , 0x54ac , 0x484f , 0x88 , 0x47 , 0x4b , 0xae , 0xea , 0xb6 , 0x05 , 0x3f )"

.SS "DEFINE_GUID (IID_ID3D12DebugCommandList1 , 0x102ca951 , 0x311b , 0x4b01 , 0xb1 , 0x1f , 0xec , 0xb8 , 0x3e , 0x06 , 0x1b , 0x37 )"

.SS "DEFINE_GUID (IID_ID3D12DebugCommandList2 , 0xaeb575cf , 0x4e06 , 0x48be , 0xba , 0x3b , 0xc4 , 0x50 , 0xfc , 0x96 , 0x65 , 0x2e )"

.SS "DEFINE_GUID (IID_ID3D12DebugCommandList3 , 0x197d5e15 , 0x4d37 , 0x4d34 , 0xaf , 0x78 , 0x72 , 0x4c , 0xd7 , 0x0f , 0xdb , 0x1f )"

.SS "DEFINE_GUID (IID_ID3D12DebugCommandQueue , 0x09e0bf36 , 0x54ac , 0x484f , 0x88 , 0x47 , 0x4b , 0xae , 0xea , 0xb6 , 0x05 , 0x3a )"

.SS "DEFINE_GUID (IID_ID3D12DebugCommandQueue1 , 0x16be35a2 , 0xbfd6 , 0x49f2 , 0xbc , 0xae , 0xea , 0xae , 0x4a , 0xff , 0x86 , 0x2d )"

.SS "DEFINE_GUID (IID_ID3D12DebugDevice , 0x3febd6dd , 0x4973 , 0x4787 , 0x81 , 0x94 , 0xe4 , 0x5f , 0x9e , 0x28 , 0x92 , 0x3e )"

.SS "DEFINE_GUID (IID_ID3D12DebugDevice1 , 0xa9b71770 , 0xd099 , 0x4a65 , 0xa6 , 0x98 , 0x3d , 0xee , 0x10 , 0x02 , 0x0f , 0x88 )"

.SS "DEFINE_GUID (IID_ID3D12DebugDevice2 , 0x60eccbc1 , 0x378d , 0x4df1 , 0x89 , 0x4c , 0xf8 , 0xac , 0x5c , 0xe4 , 0xd7 , 0xdd )"

.SS "DEFINE_GUID (IID_ID3D12InfoQueue , 0x0742a90b , 0xc387 , 0x483f , 0xb9 , 0x46 , 0x30 , 0xa7 , 0xe4 , 0xe6 , 0x14 , 0x58 )"

.SS "DEFINE_GUID (IID_ID3D12InfoQueue1 , 0x2852dd88 , 0xb484 , 0x4c0c , 0xb6 , 0xb1 , 0x67 , 0x16 , 0x85 , 0x00 , 0xe6 , 0x00 )"

.SS "DEFINE_GUID (IID_ID3D12ManualWriteTrackingResource , 0x86ca3b85 , 0x49ad , 0x4b6e , 0xae , 0xd5 , 0xed , 0xdb , 0x18 , 0x54 , 0x0f , 0x41 )"

.SS "DEFINE_GUID (IID_ID3D12SharingContract , 0x0adf7d52 , 0x929c , 0x4e61 , 0xad , 0xdb , 0xff , 0xed , 0x30 , 0xde , 0x66 , 0xef )"

.SH "Variable Documentation"
.PP 
.SS "RPC_IF_HANDLE __MIDL_itf_d3d12sdklayers_0000_0020_v0_0_c_ifspec\fR [extern]\fP"

.SS "RPC_IF_HANDLE __MIDL_itf_d3d12sdklayers_0000_0020_v0_0_s_ifspec\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
