.TH "D3D12_VIDEO_ENCODER_REFERENCE_PICTURE_DESCRIPTOR_H264" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_VIDEO_ENCODER_REFERENCE_PICTURE_DESCRIPTOR_H264
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBReconstructedPictureResourceIndex\fP"
.br
.ti -1c
.RI "BOOL \fBIsLongTermReference\fP"
.br
.ti -1c
.RI "UINT \fBLongTermPictureIdx\fP"
.br
.ti -1c
.RI "UINT \fBPictureOrderCountNumber\fP"
.br
.ti -1c
.RI "UINT \fBFrameDecodingOrderNumber\fP"
.br
.ti -1c
.RI "UINT \fBTemporalLayerIndex\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT D3D12_VIDEO_ENCODER_REFERENCE_PICTURE_DESCRIPTOR_H264::FrameDecodingOrderNumber"

.SS "BOOL D3D12_VIDEO_ENCODER_REFERENCE_PICTURE_DESCRIPTOR_H264::IsLongTermReference"

.SS "UINT D3D12_VIDEO_ENCODER_REFERENCE_PICTURE_DESCRIPTOR_H264::LongTermPictureIdx"

.SS "UINT D3D12_VIDEO_ENCODER_REFERENCE_PICTURE_DESCRIPTOR_H264::PictureOrderCountNumber"

.SS "UINT D3D12_VIDEO_ENCODER_REFERENCE_PICTURE_DESCRIPTOR_H264::ReconstructedPictureResourceIndex"

.SS "UINT D3D12_VIDEO_ENCODER_REFERENCE_PICTURE_DESCRIPTOR_H264::TemporalLayerIndex"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
