.TH "D3D12_FEATURE_DATA_VIDEO_ENCODER_CODEC_PICTURE_CONTROL_SUPPORT" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D3D12_FEATURE_DATA_VIDEO_ENCODER_CODEC_PICTURE_CONTROL_SUPPORT
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBNodeIndex\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC\fP \fBCodec\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_PROFILE_DESC\fP \fBProfile\fP"
.br
.ti -1c
.RI "BOOL \fBIsSupported\fP"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_ENCODER_CODEC_PICTURE_CONTROL_SUPPORT\fP \fBPictureSupport\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBD3D12_VIDEO_ENCODER_CODEC\fP D3D12_FEATURE_DATA_VIDEO_ENCODER_CODEC_PICTURE_CONTROL_SUPPORT::Codec"

.SS "BOOL D3D12_FEATURE_DATA_VIDEO_ENCODER_CODEC_PICTURE_CONTROL_SUPPORT::IsSupported"

.SS "UINT D3D12_FEATURE_DATA_VIDEO_ENCODER_CODEC_PICTURE_CONTROL_SUPPORT::NodeIndex"

.SS "\fBD3D12_VIDEO_ENCODER_CODEC_PICTURE_CONTROL_SUPPORT\fP D3D12_FEATURE_DATA_VIDEO_ENCODER_CODEC_PICTURE_CONTROL_SUPPORT::PictureSupport"

.SS "\fBD3D12_VIDEO_ENCODER_PROFILE_DESC\fP D3D12_FEATURE_DATA_VIDEO_ENCODER_CODEC_PICTURE_CONTROL_SUPPORT::Profile"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
