.TH "adhed/d3dx12_core.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/d3dx12_core.h
.SH SYNOPSIS
.br
.PP
\fR#include <string\&.h>\fP
.br
\fR#include 'd3d12\&.h'\fP
.br
\fR#include 'd3dx12_default\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCD3DX12_RECT\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_VIEWPORT\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_BOX\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_DEPTH_STENCIL_DESC\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_DEPTH_STENCIL_DESC1\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_BLEND_DESC\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_RASTERIZER_DESC\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_RESOURCE_ALLOCATION_INFO\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_HEAP_PROPERTIES\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_HEAP_DESC\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_CLEAR_VALUE\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_RANGE\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_RANGE_UINT64\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_SUBRESOURCE_RANGE_UINT64\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_SHADER_BYTECODE\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_TILED_RESOURCE_COORDINATE\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_TILE_REGION_SIZE\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_SUBRESOURCE_TILING\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_TILE_SHAPE\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_PACKED_MIP_INFO\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_SUBRESOURCE_FOOTPRINT\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_TEXTURE_COPY_LOCATION\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_RESOURCE_DESC\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_RESOURCE_DESC1\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_VIEW_INSTANCING_DESC\fP"
.br
.ti -1c
.RI "struct \fBCD3DX12_RT_FORMAT_ARRAY\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBD3DX12_ASSERT\fP(\fBx\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename t_CommandListType > \fBID3D12CommandList\fP *const * \fBCommandListCast\fP (t_CommandListType *const *pp) noexcept"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBD3D12_VIEWPORT\fP &l, const \fBD3D12_VIEWPORT\fP &\fBr\fP) noexcept"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBD3D12_VIEWPORT\fP &l, const \fBD3D12_VIEWPORT\fP &\fBr\fP) noexcept"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBD3D12_BOX\fP &l, const \fBD3D12_BOX\fP &\fBr\fP) noexcept"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBD3D12_BOX\fP &l, const \fBD3D12_BOX\fP &\fBr\fP) noexcept"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBD3D12_HEAP_PROPERTIES\fP &l, const \fBD3D12_HEAP_PROPERTIES\fP &\fBr\fP) noexcept"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBD3D12_HEAP_PROPERTIES\fP &l, const \fBD3D12_HEAP_PROPERTIES\fP &\fBr\fP) noexcept"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBD3D12_HEAP_DESC\fP &l, const \fBD3D12_HEAP_DESC\fP &\fBr\fP) noexcept"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBD3D12_HEAP_DESC\fP &l, const \fBD3D12_HEAP_DESC\fP &\fBr\fP) noexcept"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBD3D12_CLEAR_VALUE\fP &\fBa\fP, const \fBD3D12_CLEAR_VALUE\fP &\fBb\fP) noexcept"
.br
.ti -1c
.RI "constexpr UINT \fBD3D12CalcSubresource\fP (UINT MipSlice, UINT ArraySlice, UINT PlaneSlice, UINT MipLevels, UINT ArraySize) noexcept"
.br
.ti -1c
.RI "UINT8 \fBD3D12GetFormatPlaneCount\fP (_In_ \fBID3D12Device\fP *pDevice, \fBDXGI_FORMAT\fP Format) noexcept"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBD3D12_RESOURCE_DESC\fP &l, const \fBD3D12_RESOURCE_DESC\fP &\fBr\fP) noexcept"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBD3D12_RESOURCE_DESC\fP &l, const \fBD3D12_RESOURCE_DESC\fP &\fBr\fP) noexcept"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBD3D12_RESOURCE_DESC1\fP &l, const \fBD3D12_RESOURCE_DESC1\fP &\fBr\fP) noexcept"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBD3D12_RESOURCE_DESC1\fP &l, const \fBD3D12_RESOURCE_DESC1\fP &\fBr\fP) noexcept"
.br
.ti -1c
.RI "const \fBCD3DX12_RESOURCE_DESC1\fP * \fBD3DX12ConditionallyExpandAPIDesc\fP (\fBCD3DX12_RESOURCE_DESC1\fP &LclDesc, const \fBCD3DX12_RESOURCE_DESC1\fP *pDesc)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define D3DX12_ASSERT( \fBx\fP)"

.SH "Function Documentation"
.PP 
.SS "template<typename t_CommandListType > \fBID3D12CommandList\fP *const  * CommandListCast (t_CommandListType *const * pp)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "UINT D3D12CalcSubresource (UINT MipSlice, UINT ArraySlice, UINT PlaneSlice, UINT MipLevels, UINT ArraySize)\fR [constexpr]\fP, \fR [noexcept]\fP"

.SS "UINT8 D3D12GetFormatPlaneCount (_In_ \fBID3D12Device\fP * pDevice, \fBDXGI_FORMAT\fP Format)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "const \fBCD3DX12_RESOURCE_DESC1\fP * D3DX12ConditionallyExpandAPIDesc (\fBCD3DX12_RESOURCE_DESC1\fP & LclDesc, const \fBCD3DX12_RESOURCE_DESC1\fP * pDesc)\fR [inline]\fP"

.SS "bool operator!= (const \fBD3D12_BOX\fP & l, const \fBD3D12_BOX\fP & r)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "bool operator!= (const \fBD3D12_HEAP_DESC\fP & l, const \fBD3D12_HEAP_DESC\fP & r)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "bool operator!= (const \fBD3D12_HEAP_PROPERTIES\fP & l, const \fBD3D12_HEAP_PROPERTIES\fP & r)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "bool operator!= (const \fBD3D12_RESOURCE_DESC\fP & l, const \fBD3D12_RESOURCE_DESC\fP & r)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "bool operator!= (const \fBD3D12_RESOURCE_DESC1\fP & l, const \fBD3D12_RESOURCE_DESC1\fP & r)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "bool operator!= (const \fBD3D12_VIEWPORT\fP & l, const \fBD3D12_VIEWPORT\fP & r)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "bool operator== (const \fBD3D12_BOX\fP & l, const \fBD3D12_BOX\fP & r)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "bool operator== (const \fBD3D12_CLEAR_VALUE\fP & a, const \fBD3D12_CLEAR_VALUE\fP & b)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "bool operator== (const \fBD3D12_HEAP_DESC\fP & l, const \fBD3D12_HEAP_DESC\fP & r)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "bool operator== (const \fBD3D12_HEAP_PROPERTIES\fP & l, const \fBD3D12_HEAP_PROPERTIES\fP & r)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "bool operator== (const \fBD3D12_RESOURCE_DESC\fP & l, const \fBD3D12_RESOURCE_DESC\fP & r)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "bool operator== (const \fBD3D12_RESOURCE_DESC1\fP & l, const \fBD3D12_RESOURCE_DESC1\fP & r)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "bool operator== (const \fBD3D12_VIEWPORT\fP & l, const \fBD3D12_VIEWPORT\fP & r)\fR [inline]\fP, \fR [noexcept]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
