.TH "adhed/d3dx12_state_object.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/d3dx12_state_object.h
.SH SYNOPSIS
.br
.PP
\fR#include 'd3dx12_default\&.h'\fP
.br
\fR#include 'd3d12\&.h'\fP
.br
\fR#include 'd3dx12_core\&.h'\fP
.br
\fR#include <list>\fP
.br
\fR#include <forward_list>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <string>\fP
.br
\fR#include <wrl/client\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCD3DX12_STATE_OBJECT_DESC\fP"
.br
.ti -1c
.RI "class \fBCD3DX12_STATE_OBJECT_DESC::SUBOBJECT_HELPER_BASE\fP"
.br
.ti -1c
.RI "class \fBCD3DX12_DXIL_LIBRARY_SUBOBJECT\fP"
.br
.ti -1c
.RI "class \fBCD3DX12_EXISTING_COLLECTION_SUBOBJECT\fP"
.br
.ti -1c
.RI "class \fBCD3DX12_SUBOBJECT_TO_EXPORTS_ASSOCIATION_SUBOBJECT\fP"
.br
.ti -1c
.RI "class \fBCD3DX12_DXIL_SUBOBJECT_TO_EXPORTS_ASSOCIATION\fP"
.br
.ti -1c
.RI "class \fBCD3DX12_HIT_GROUP_SUBOBJECT\fP"
.br
.ti -1c
.RI "class \fBCD3DX12_RAYTRACING_SHADER_CONFIG_SUBOBJECT\fP"
.br
.ti -1c
.RI "class \fBCD3DX12_RAYTRACING_PIPELINE_CONFIG_SUBOBJECT\fP"
.br
.ti -1c
.RI "class \fBCD3DX12_RAYTRACING_PIPELINE_CONFIG1_SUBOBJECT\fP"
.br
.ti -1c
.RI "class \fBCD3DX12_GLOBAL_ROOT_SIGNATURE_SUBOBJECT\fP"
.br
.ti -1c
.RI "class \fBCD3DX12_LOCAL_ROOT_SIGNATURE_SUBOBJECT\fP"
.br
.ti -1c
.RI "class \fBCD3DX12_STATE_OBJECT_CONFIG_SUBOBJECT\fP"
.br
.ti -1c
.RI "class \fBCD3DX12_NODE_MASK_SUBOBJECT\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBD3DX12_COM_PTR\fP   Microsoft::WRL::ComPtr"
.br
.ti -1c
.RI "#define \fBD3DX12_COM_PTR_GET\fP(\fBx\fP)   \fBx\&.Get\fP()"
.br
.ti -1c
.RI "#define \fBD3DX12_COM_PTR_ADDRESSOF\fP(\fBx\fP)   x\&.GetAddressOf()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define D3DX12_COM_PTR   Microsoft::WRL::ComPtr"

.SS "#define D3DX12_COM_PTR_ADDRESSOF( \fBx\fP)   x\&.GetAddressOf()"

.SS "#define D3DX12_COM_PTR_GET( \fBx\fP)   \fBx\&.Get\fP()"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
