.TH "UPRISE_ENGINE/src/DATATYPES/D_TERRAIN_DATA.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/src/DATATYPES/D_TERRAIN_DATA.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'pch\&.h'\fP
.br
\fR#include 'HeaderE/DATATYPES/D_TERRAIN_DATA\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBssharp_methcall\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ssharp_methcall ()"

.PP
Definition at line \fB9\fP of file \fBD_TERRAIN_DATA\&.cpp\fP\&.
.nf
9                        {
10 
11     HRESULT hr = CoInitialize(NULL);
12     if (FAILED(hr)) {
13         std::cerr << "Failed to initialize COM library" << std::endl;
14         
15 
16     }
17    // ManagedUtills::IHeightmapProccesorPtr pHeightmapProc;
18     //hr = pHeightmapProc\&.CreateInstance(__uuidof(ManagedUtills::IHeightmapProccesor));
19     //if (FAILED(hr)) {
20      //   std::cerr << "Failed to create instance of HeightmapProccesor: 0x" << std::hex << hr << std::endl;
21         
22     //}
23 
24 
25 
26 
27 }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
