.TH "UPRISE_ENGINE/DATATYPES.h" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/DATATYPES.h
.SH SYNOPSIS
.br
.PP
\fR#include 'TS_P_VECTOR3\&.h'\fP
.br
\fR#include 'MSG_MESSAGE\&.h'\fP
.br
\fR#include '_MESH\&.h'\fP
.br
\fR#include 'STARTUP_CONFIG\&.h'\fP
.br
\fR#include 'TS_P_QUATERION\&.h'\fP
.br
\fR#include 'TS_P_VECOTR2\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDATATYpeS\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_DATATYPES_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _DATATYPES_"

.PP
Definition at line \fB3\fP of file \fBDATATYPES\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
