.TH "DATALINK" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DATALINK
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DLL\-ENGINE\-LINK\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBCreatorFunc\fP = std::function<std::shared_ptr<\fBCORE::Behaviour\fP>()>"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVEC\fP (std::shared_ptr< \fBCORE::Behaviour\fP >) *inst_LINK"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBCORE::Scene\fP > \fBACTIVE_SCENE\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBCORE::Scene\fP > \fBBackups_SCENE\fP"
.br
.ti -1c
.RI "\fBPAIN::Shader\fP *(* \fBCreateSHADER\fP )(const char *vertexPath, const char *fragmentPath)"
.br
.ti -1c
.RI "void(* \fBAddTORender\fP )(std::shared_ptr< \fBPAIN::MiniModel\fP > mm, int id)"
.br
.ti -1c
.RI "bool(* \fBRemoveFromRender\fP )(std::shared_ptr< \fBPAIN::MiniModel\fP > &mm, int Material_ID)"
.br
.ti -1c
.RI "bool(* \fBCreateMaterial\fP )(\fBPAIN::Shader\fP *Shader)"
.br
.ti -1c
.RI "GLFWwindow * \fBwindow\fP"
.br
.ti -1c
.RI "std::unordered_map< std::string, int > * \fBM_ID_LINK\fP"
.br
.ti -1c
.RI "unsigned int \fBM_ID_LINK_LENGTH\fP"
.br
.ti -1c
.RI "std::unordered_map< std::string, std::shared_ptr< \fBPAIN::Model\fP > > * \fBM_DICT_LINK\fP"
.br
.ti -1c
.RI "unsigned int \fBM_DICT_LINK_LENGTH\fP"
.br
.ti -1c
.RI "std::shared_ptr< std::vector< \fBPAIN::Material\fP > > \fBMATS_LINK\fP"
.br
.ti -1c
.RI "unsigned int \fBMATS_LINK_LENGTH\fP"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBPAIN::TerrainModel\fP > > * \fBTERRAIN_LINK\fP"
.br
.ti -1c
.RI "unsigned int \fBTERRAIN_LINK_LENGTH\fP"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBGameObject\fP > > * \fBOBJECT_LINK\fP"
.br
.ti -1c
.RI "unsigned int \fBOBJECT_LINK_LENGTH\fP"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBCORE::Object\fP > > * \fBPTR_OBJECTS_LINK\fP"
.br
.ti -1c
.RI "unsigned int \fBPTR_OBJECTS_LINK_LENGTH\fP"
.br
.ti -1c
.RI "std::vector< void * > * \fBVOID_OBJECTS_LINK\fP"
.br
.ti -1c
.RI "unsigned int \fBVOID_OBJECTS_LINK_LENGTH\fP"
.br
.ti -1c
.RI "\fBPAIN::Render_Camera\fP * \fBRenderCam\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBCamera\fP > \fBCAM\fP"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBCORE::Behaviour\fP > > \fBobjectss_LINK\fP"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBCORE::Behaviour\fP > > \fBbehaviours_LINK\fP"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBCORE::Behaviour\fP > > \fBAWAKES_LINK\fP"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBCORE::Behaviour\fP > > \fBStarts_LINK\fP"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBCORE::Behaviour\fP > > \fBParallel_Updates_LINK\fP"
.br
.ti -1c
.RI "std::shared_ptr< std::unordered_map< \fBConfigFile::ConfigType\fP, std::unordered_map< std::string, std::shared_ptr< \fBConfigFile\fP > > > > \fBConfigDatabase_LINK\fP"
.br
.ti -1c
.RI "std::shared_ptr< std::map< std::string, \fBCreatorFunc\fP > > \fBcreators_LINK\fP"
.br
.ti -1c
.RI "int * \fBIII\fP"
.br
.ti -1c
.RI "int(* \fBGetKey\fP )(int key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB21\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBDATALINK::CreatorFunc\fP = std::function<std::shared_ptr<\fBCORE::Behaviour\fP>()>"

.PP
Definition at line \fB67\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "DATALINK::VEC (std::shared_ptr< \fBCORE::Behaviour\fP > )"

.SH "Member Data Documentation"
.PP 
.SS "std::shared_ptr<\fBCORE::Scene\fP> DATALINK::ACTIVE_SCENE"

.PP
Definition at line \fB25\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "void(* DATALINK::AddTORender) (std::shared_ptr< \fBPAIN::MiniModel\fP > mm, int id)"

.PP
Definition at line \fB30\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "std::vector<std::shared_ptr<\fBCORE::Behaviour\fP> > DATALINK::AWAKES_LINK"

.PP
Definition at line \fB57\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SS "std::shared_ptr<\fBCORE::Scene\fP> DATALINK::Backups_SCENE"

.PP
Definition at line \fB26\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "std::vector<std::shared_ptr<\fBCORE::Behaviour\fP> > DATALINK::behaviours_LINK"

.PP
Definition at line \fB56\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SS "std::shared_ptr<\fBCamera\fP> DATALINK::CAM"

.PP
Definition at line \fB51\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "std::shared_ptr<std::unordered_map<\fBConfigFile::ConfigType\fP, std::unordered_map <std::string, std::shared_ptr<\fBConfigFile\fP> > > > DATALINK::ConfigDatabase_LINK"

.PP
Definition at line \fB63\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "bool(* DATALINK::CreateMaterial) (\fBPAIN::Shader\fP *Shader)"

.PP
Definition at line \fB32\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "\fBPAIN::Shader\fP *(* DATALINK::CreateSHADER) (const char *vertexPath, const char *fragmentPath)"

.PP
Definition at line \fB29\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "std::shared_ptr<std::map<std::string, \fBCreatorFunc\fP> > DATALINK::creators_LINK"

.PP
Definition at line \fB69\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "int(* DATALINK::GetKey) (int key)"

.PP
Definition at line \fB76\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "int* DATALINK::III"

.PP
Definition at line \fB71\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "std::unordered_map<std::string, std::shared_ptr<\fBPAIN::Model\fP> >* DATALINK::M_DICT_LINK"

.PP
Definition at line \fB37\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "unsigned int DATALINK::M_DICT_LINK_LENGTH"

.PP
Definition at line \fB38\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SS "std::unordered_map<std::string, int>* DATALINK::M_ID_LINK"

.PP
Definition at line \fB35\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "unsigned int DATALINK::M_ID_LINK_LENGTH"

.PP
Definition at line \fB36\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SS "std::shared_ptr<std::vector<\fBPAIN::Material\fP> > DATALINK::MATS_LINK"

.PP
Definition at line \fB39\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "unsigned int DATALINK::MATS_LINK_LENGTH"

.PP
Definition at line \fB40\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SS "std::vector< std::shared_ptr<\fBGameObject\fP> >* DATALINK::OBJECT_LINK"

.PP
Definition at line \fB43\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SS "unsigned int DATALINK::OBJECT_LINK_LENGTH"

.PP
Definition at line \fB44\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SS "std::vector<std::shared_ptr<\fBCORE::Behaviour\fP> > DATALINK::objectss_LINK"

.PP
Definition at line \fB55\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SS "std::vector<std::shared_ptr<\fBCORE::Behaviour\fP> > DATALINK::Parallel_Updates_LINK"

.PP
Definition at line \fB59\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SS "std::vector< std::shared_ptr<\fBCORE::Object\fP> >* DATALINK::PTR_OBJECTS_LINK"

.PP
Definition at line \fB46\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SS "unsigned int DATALINK::PTR_OBJECTS_LINK_LENGTH"

.PP
Definition at line \fB47\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SS "bool(* DATALINK::RemoveFromRender) (std::shared_ptr< \fBPAIN::MiniModel\fP > &mm, int Material_ID)"

.PP
Definition at line \fB31\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "\fBPAIN::Render_Camera\fP* DATALINK::RenderCam"

.PP
Definition at line \fB50\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "std::vector<std::shared_ptr<\fBCORE::Behaviour\fP> > DATALINK::Starts_LINK"

.PP
Definition at line \fB58\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SS "std::vector<std::shared_ptr<\fBPAIN::TerrainModel\fP> >* DATALINK::TERRAIN_LINK"

.PP
Definition at line \fB41\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "unsigned int DATALINK::TERRAIN_LINK_LENGTH"

.PP
Definition at line \fB42\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SS "std::vector< void* >* DATALINK::VOID_OBJECTS_LINK"

.PP
Definition at line \fB48\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SS "unsigned int DATALINK::VOID_OBJECTS_LINK_LENGTH"

.PP
Definition at line \fB49\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.SS "GLFWwindow* DATALINK::window"

.PP
Definition at line \fB34\fP of file \fBDLL\-ENGINE\-LINK\&.h\fP\&.
.PP
Referenced by \fBmain()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
