.TH "DATATYPES::Startup_Config" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DATATYPES::Startup_Config
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <D_STARTUP_CONFIG\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStartup_Config\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long long \fBRAMbytes\fP"
.br
.ti -1c
.RI "bool \fBSupports_AVX2\fP"
.br
.ti -1c
.RI "bool \fBSupports_AVX\fP"
.br
.ti -1c
.RI "bool \fBIs_IGPU\fP"
.br
.ti -1c
.RI "unsigned short \fBCPU_Cores\fP"
.br
.ti -1c
.RI "unsigned short \fBGPU_Cores\fP"
.br
.ti -1c
.RI "unsigned short \fBRenderMode\fP"
.br
.RI "accepts 0 opengl,1vulkan,2 dx11 and 2 dx12 "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBD_STARTUP_CONFIG\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DATATYPES::Startup_Config::Startup_Config ()"

.PP
Definition at line \fB4\fP of file \fBSTARTUP_CONFIG\&.cpp\fP\&.
.nf
5 {
6 }
.PP
.fi

.SH "Member Data Documentation"
.PP 
.SS "unsigned short DATATYPES::Startup_Config::CPU_Cores"

.PP
Definition at line \fB15\fP of file \fBD_STARTUP_CONFIG\&.h\fP\&.
.PP
Referenced by \fBCORE::Startup::Configure_Startup()\fP\&.
.SS "unsigned short DATATYPES::Startup_Config::GPU_Cores"

.PP
Definition at line \fB16\fP of file \fBD_STARTUP_CONFIG\&.h\fP\&.
.SS "bool DATATYPES::Startup_Config::Is_IGPU"

.PP
Definition at line \fB14\fP of file \fBD_STARTUP_CONFIG\&.h\fP\&.
.SS "unsigned long long DATATYPES::Startup_Config::RAMbytes"

.PP
Definition at line \fB11\fP of file \fBD_STARTUP_CONFIG\&.h\fP\&.
.PP
Referenced by \fBCORE::Startup::Configure_Startup()\fP\&.
.SS "unsigned short DATATYPES::Startup_Config::RenderMode"

.PP
accepts 0 opengl,1vulkan,2 dx11 and 2 dx12 
.PP
Definition at line \fB20\fP of file \fBD_STARTUP_CONFIG\&.h\fP\&.
.PP
Referenced by \fBCORE::Startup::Configure_Startup()\fP\&.
.SS "bool DATATYPES::Startup_Config::Supports_AVX"

.PP
Definition at line \fB13\fP of file \fBD_STARTUP_CONFIG\&.h\fP\&.
.PP
Referenced by \fBCORE::Startup::Configure_Startup()\fP\&.
.SS "bool DATATYPES::Startup_Config::Supports_AVX2"

.PP
Definition at line \fB12\fP of file \fBD_STARTUP_CONFIG\&.h\fP\&.
.PP
Referenced by \fBCORE::Startup::Configure_Startup()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
