.TH "DATATYPES::Quaternion" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DATATYPES::Quaternion
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <TS_P_QUATERION\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuaternion\fP ()"
.br
.ti -1c
.RI "\fBQuaternion\fP (float \fBw\fP, float \fBx\fP, float \fBy\fP, float \fBz\fP)"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBoperator*\fP (const \fBQuaternion\fP &other) const"
.br
.ti -1c
.RI "\fBDATATYPES::TS_P_Vector3\fP \fBToRotationVector\fP () const"
.br
.ti -1c
.RI "\fBTS_P_Vector3\fP \fBoperator*\fP (\fBDATATYPES::TS_P_Vector3\fP vec)"
.br
.ti -1c
.RI "\fBDATATYPES::TS_P_Vector3\fP \fBRotate\fP (const \fBDATATYPES::TS_P_Vector3\fP &v) const"
.br
.ti -1c
.RI "glm::mat4 \fBToMat4\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBQuaternion\fP \fBFromEulerAngles\fP (\fBDATATYPES::TS_P_Vector3\fP vec)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.ti -1c
.RI "float \fBw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBTS_P_QUATERION\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DATATYPES::Quaternion::Quaternion ()\fR [inline]\fP"

.PP
Definition at line \fB11\fP of file \fBTS_P_QUATERION\&.h\fP\&.
.SS "DATATYPES::Quaternion::Quaternion (float w, float x, float y, float z)\fR [inline]\fP"

.PP
Definition at line \fB12\fP of file \fBTS_P_QUATERION\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDATATYPES::Quaternion\fP DATATYPES::Quaternion::FromEulerAngles (\fBDATATYPES::TS_P_Vector3\fP vec)\fR [static]\fP"

.PP
Definition at line \fB3\fP of file \fBTS_P_QUATERION\&.cpp\fP\&.
.SS "\fBDATATYPES::Quaternion\fP DATATYPES::Quaternion::operator* (const \fBQuaternion\fP & other) const"

.PP
Definition at line \fB25\fP of file \fBTS_P_QUATERION\&.cpp\fP\&.
.SS "\fBDATATYPES::TS_P_Vector3\fP DATATYPES::Quaternion::operator* (\fBDATATYPES::TS_P_Vector3\fP vec)"

.PP
Definition at line \fB56\fP of file \fBTS_P_QUATERION\&.cpp\fP\&.
.SS "\fBDATATYPES::TS_P_Vector3\fP DATATYPES::Quaternion::Rotate (const \fBDATATYPES::TS_P_Vector3\fP & v) const\fR [inline]\fP"

.PP
Definition at line \fB24\fP of file \fBTS_P_QUATERION\&.h\fP\&.
.SS "glm::mat4 DATATYPES::Quaternion::ToMat4 () const\fR [inline]\fP"

.PP
Definition at line \fB31\fP of file \fBTS_P_QUATERION\&.h\fP\&.
.SS "\fBDATATYPES::TS_P_Vector3\fP DATATYPES::Quaternion::ToRotationVector () const"

.PP
Definition at line \fB35\fP of file \fBTS_P_QUATERION\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float DATATYPES::Quaternion::w"

.PP
Definition at line \fB10\fP of file \fBTS_P_QUATERION\&.h\fP\&.
.SS "float DATATYPES::Quaternion::x"

.PP
Definition at line \fB10\fP of file \fBTS_P_QUATERION\&.h\fP\&.
.SS "float DATATYPES::Quaternion::y"

.PP
Definition at line \fB10\fP of file \fBTS_P_QUATERION\&.h\fP\&.
.SS "float DATATYPES::Quaternion::z"

.PP
Definition at line \fB10\fP of file \fBTS_P_QUATERION\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
