.TH "DATATYPES::Quaternion" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DATATYPES::Quaternion
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <D_TS_P_QUATERION\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuaternion\fP ()"
.br
.ti -1c
.RI "\fBQuaternion\fP (float \fBw\fP, float \fBx\fP, float \fBy\fP, float \fBz\fP)"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBoperator*\fP (const \fBQuaternion\fP &other) const"
.br
.ti -1c
.RI "\fBDATATYPES::TS_P_Vector3\fP \fBToRotationVector\fP () const"
.br
.ti -1c
.RI "\fBTS_P_Vector3\fP \fBoperator*\fP (\fBDATATYPES::TS_P_Vector3\fP vec)"
.br
.ti -1c
.RI "\fBDATATYPES::TS_P_Vector3\fP \fBRotate\fP (const \fBDATATYPES::TS_P_Vector3\fP &v) const"
.br
.ti -1c
.RI "glm::mat4 \fBToMat4\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBQuaternion\fP \fBFromEulerAngles\fP (\fBDATATYPES::TS_P_Vector3\fP vec)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.ti -1c
.RI "float \fBw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBD_TS_P_QUATERION\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DATATYPES::Quaternion::Quaternion ()\fR [inline]\fP"

.PP
Definition at line \fB11\fP of file \fBD_TS_P_QUATERION\&.h\fP\&.
.nf
11 : w(1), x(0), y(0), z(0) {}
.PP
.fi

.PP
Referenced by \fBFromEulerAngles()\fP\&.
.SS "DATATYPES::Quaternion::Quaternion (float w, float x, float y, float z)\fR [inline]\fP"

.PP
Definition at line \fB12\fP of file \fBD_TS_P_QUATERION\&.h\fP\&.
.nf
12 : w(w), x(x), y(y), z(z) {}
.PP
.fi

.SH "Member Function Documentation"
.PP 
.SS "\fBDATATYPES::Quaternion\fP DATATYPES::Quaternion::FromEulerAngles (\fBDATATYPES::TS_P_Vector3\fP vec)\fR [static]\fP"

.PP
Definition at line \fB6\fP of file \fBD_TS_P_QUATERION\&.cpp\fP\&.
.nf
6                                                                                    {
7      float cy = std::cos(vec\&.y * 0\&.5);
8      float sy = std::sin(vec\&.y * 0\&.5);
9      float cp = std::cos(vec\&.z* 0\&.5);
10      float sp = std::sin(vec\&.z * 0\&.5);
11      float cr = std::cos(vec\&.x * 0\&.5);
12      float sr = std::sin(vec\&.x * 0\&.5);
13      return Quaternion(
14          cr * cp * cy + sr * sp * sy,
15          sr * cp * cy \- cr * sp * sy,
16          cr * sp * cy + sr * cp * sy,
17          cr * cp * sy \- sr * sp * cy
18 
19         //  cr * cp * cy + sr * sp * sy,
20      //sr * cp * cy \- cr * sp * sy,
21      // cr * sp * cy + sr * cp * sy,
22      //cr * cp * sy \- sr * sp * cy
23      );
24 }
.PP
.fi

.PP
References \fBQuaternion()\fP, \fBDATATYPES::TS_P_Vector3::x\fP, \fBDATATYPES::TS_P_Vector3::y\fP, and \fBDATATYPES::TS_P_Vector3::z\fP\&.
.SS "\fBDATATYPES::Quaternion\fP DATATYPES::Quaternion::operator* (const \fBQuaternion\fP & other) const"

.PP
Definition at line \fB27\fP of file \fBD_TS_P_QUATERION\&.cpp\fP\&.
.nf
28  {
29     return Quaternion(
30         w * other\&.w \- x * other\&.x \- y * other\&.y \- z * other\&.z,
31         w * other\&.x + x * other\&.w + y * other\&.z \- z * other\&.y,
32         w * other\&.y \- x * other\&.z + y * other\&.w + z * other\&.x,
33         w * other\&.z + x * other\&.y \- y * other\&.x + z * other\&.w
34     );
35  }
.PP
.fi

.PP
References \fBw\fP, \fBx\fP, \fBy\fP, and \fBz\fP\&.
.SS "\fBDATATYPES::TS_P_Vector3\fP DATATYPES::Quaternion::operator* (\fBDATATYPES::TS_P_Vector3\fP vec)"

.PP
Definition at line \fB76\fP of file \fBD_TS_P_QUATERION\&.cpp\fP\&.
.nf
77  {
78      float num = x * 2;
79      float num2 = y * 2;
80      float num3 = z * 2;
81      float num4 = x * num;
82      float num5 = y * num2;
83      float num6 = z * num3;
84      float num7 = x * num2;
85      float num8 = x * num3;
86      float num9 = y * num3;
87      float num10 = w * num;
88      float num11 = w * num2;
89      float num12 = w * num3;
90      DATATYPES::TS_P_Vector3 result;
91      result\&.x = (1 \- (num5 + num6)) * vec\&.x + (num7 \- num12) * vec\&.y + (num8 + num11) * vec\&.z;
92      result\&.y = (num7 + num12) * vec\&.x + (1 \- (num4 + num6)) * vec\&.y + (num9 \- num10) * vec\&.z;
93      result\&.z = (num8 \- num11) * vec\&.x + (num9 + num10) * vec\&.y + (1 \- (num4 + num5)) * vec\&.z;
94      return result;
95  }
.PP
.fi

.PP
References \fBDATATYPES::TS_P_Vector3::x\fP, \fBDATATYPES::TS_P_Vector3::y\fP, and \fBDATATYPES::TS_P_Vector3::z\fP\&.
.SS "\fBDATATYPES::TS_P_Vector3\fP DATATYPES::Quaternion::Rotate (const \fBDATATYPES::TS_P_Vector3\fP & v) const\fR [inline]\fP"

.PP
Definition at line \fB24\fP of file \fBD_TS_P_QUATERION\&.h\fP\&.
.nf
24                                                                            {
25             Quaternion qv(0, v\&.x, v\&.y, v\&.z);
26             Quaternion qconj(w, \-x, \-y, \-z);
27             Quaternion result = (*this) * qv * qconj;
28             auto a = DATATYPES::TS_P_Vector3(result\&.x, result\&.y, result\&.z);
29             return a;
30         }
.PP
.fi

.PP
References \fBw\fP, \fBx\fP, \fBDATATYPES::TS_P_Vector3::x\fP, \fBy\fP, \fBDATATYPES::TS_P_Vector3::y\fP, \fBz\fP, and \fBDATATYPES::TS_P_Vector3::z\fP\&.
.SS "glm::mat4 DATATYPES::Quaternion::ToMat4 () const\fR [inline]\fP"

.PP
Definition at line \fB31\fP of file \fBD_TS_P_QUATERION\&.h\fP\&.
.nf
31                                {
32             return glm::mat4_cast(glm::quat(w, x, y, z));
33         }
.PP
.fi

.PP
References \fBw\fP, \fBx\fP, \fBy\fP, and \fBz\fP\&.
.SS "\fBDATATYPES::TS_P_Vector3\fP DATATYPES::Quaternion::ToRotationVector () const"

.PP
Definition at line \fB37\fP of file \fBD_TS_P_QUATERION\&.cpp\fP\&.
.nf
37                                                                    {
38      //DATATYPES::TS_P_Vector3 ot;
39      //double sinr_cosp = 2 * (w * x + y * z);
40      //double cosr_cosp = 1 \- 2 * (x * x + y * y);
41      //ot\&.x = std::atan2(sinr_cosp, cosr_cosp);
42 
44      //double sinp = std::sqrt(1 + 2 * (w * y \- x * z));
45      //double cosp = std::sqrt(1 \- 2 * (w * y \- x * z));
46      //ot\&.z = 2 * std::atan2(sinp, cosp) \- M_PI / 2;
47 
49      //double siny_cosp = 2 * (w *z + x * y);
50      //double cosy_cosp = 1 \- 2 * (y * y + z * z);
51      //ot\&.z = std::atan2(siny_cosp, cosy_cosp);
52      //return ot;
53      
54      // Normalize the quaternion
55 
56 
57      float length = std::sqrt(w * w + x * x + y * y + z * z);
58      float nw = w / length;
59      float nx = x / length;
60      float ny = y / length;
61      float nz = z / length;
62 
63      // Compute the angle
64      float angle = 2\&.0f * std::acos(nw);
65 
66      // Compute the axis
67      float s = std::sqrt(1\&.0f \- nw * nw);
68      if (s < 0\&.0001f) {
69          // If s is close to zero, return the axis as (1, 0, 0)
70          return DATATYPES::TS_P_Vector3(1, 0, 0) * angle;
71      }
72      else {
73          return DATATYPES::TS_P_Vector3(nx / s, ny / s, nz / s) * angle;
74      }
75  }
.PP
.fi

.SH "Member Data Documentation"
.PP 
.SS "float DATATYPES::Quaternion::w"

.PP
Definition at line \fB10\fP of file \fBD_TS_P_QUATERION\&.h\fP\&.
.PP
Referenced by \fBoperator*()\fP, \fBRotate()\fP, and \fBToMat4()\fP\&.
.SS "float DATATYPES::Quaternion::x"

.PP
Definition at line \fB10\fP of file \fBD_TS_P_QUATERION\&.h\fP\&.
.PP
Referenced by \fBoperator*()\fP, \fBRotate()\fP, and \fBToMat4()\fP\&.
.SS "float DATATYPES::Quaternion::y"

.PP
Definition at line \fB10\fP of file \fBD_TS_P_QUATERION\&.h\fP\&.
.PP
Referenced by \fBoperator*()\fP, \fBRotate()\fP, and \fBToMat4()\fP\&.
.SS "float DATATYPES::Quaternion::z"

.PP
Definition at line \fB10\fP of file \fBD_TS_P_QUATERION\&.h\fP\&.
.PP
Referenced by \fBoperator*()\fP, \fBRotate()\fP, and \fBToMat4()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
