.TH "DeadlyImportError" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeadlyImportError
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Exceptional\&.h>\fP
.PP
Inherits \fBDeadlyErrorBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeadlyImportError\fP (const char *message)"
.br
.RI "The class constructor with the message\&. "
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBDeadlyImportError\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.RI "The class constructor with the parameter ellipse\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBDeadlyErrorBase\fP
.in +1c
.ti -1c
.RI "\fBDeadlyErrorBase\fP (\fBAssimp::Formatter::format\fP \fBf\fP)"
.br
.RI "The class constructor with the formatter\&. "
.ti -1c
.RI "template<typename\&.\&.\&. T, typename \fBU\fP > \fBDeadlyErrorBase\fP (\fBAssimp::Formatter::format\fP \fBf\fP, \fBU\fP &&u, \fBT\fP &&\&.\&.\&. args)"
.br
.RI "The class constructor with the parameter ellipse\&. "
.in -1c
.SH "Detailed Description"
.PP 
FOR IMPORTER PLUGINS ONLY: Simple exception class to be thrown if an unrecoverable error occurs while importing\&. Loading APIs return nullptr instead of a valid \fBaiScene\fP then\&. 
.br
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DeadlyImportError::DeadlyImportError (const char * message)\fR [inline]\fP"

.PP
The class constructor with the message\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP The message 
.RE
.PP

.SS "template<typename\&.\&.\&. T> DeadlyImportError::DeadlyImportError (\fBT\fP &&\&.\&.\&. args)\fR [inline]\fP, \fR [explicit]\fP"

.PP
The class constructor with the parameter ellipse\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fI\&.\&.\&.T\fP The type for the ellipse 
.RE
.PP
\fBParameters\fP
.RS 4
\fI\&.\&.\&.args\fP The args 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
