.TH "DeadlyExportError" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeadlyExportError
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Exceptional\&.h>\fP
.PP
Inherits \fBDeadlyErrorBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBDeadlyExportError\fP (\fBT\fP &&\&.\&.\&. args)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBDeadlyErrorBase\fP
.in +1c
.ti -1c
.RI "\fBDeadlyErrorBase\fP (\fBAssimp::Formatter::format\fP \fBf\fP)"
.br
.RI "The class constructor with the formatter\&. "
.ti -1c
.RI "template<typename\&.\&.\&. T, typename \fBU\fP > \fBDeadlyErrorBase\fP (\fBAssimp::Formatter::format\fP \fBf\fP, \fBU\fP &&u, \fBT\fP &&\&.\&.\&. args)"
.br
.RI "The class constructor with the parameter ellipse\&. "
.in -1c
.SH "Detailed Description"
.PP 
FOR EXPORTER PLUGINS ONLY: Simple exception class to be thrown if an unrecoverable error occurs while exporting\&. Exporting APIs return nullptr instead of a valid \fBaiScene\fP then\&. 
.br
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename\&.\&.\&. T> DeadlyExportError::DeadlyExportError (\fBT\fP &&\&.\&.\&. args)\fR [inline]\fP, \fR [explicit]\fP"
Constructor with arguments 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
