.TH "DeadlyErrorBase" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeadlyErrorBase
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Exceptional\&.h>\fP
.PP
Inherits runtime_error\&.
.PP
Inherited by \fBDeadlyExportError\fP, and \fBDeadlyImportError\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBDeadlyErrorBase\fP (\fBAssimp::Formatter::format\fP \fBf\fP)"
.br
.RI "The class constructor with the formatter\&. "
.ti -1c
.RI "template<typename\&.\&.\&. T, typename \fBU\fP > \fBDeadlyErrorBase\fP (\fBAssimp::Formatter::format\fP \fBf\fP, \fBU\fP &&u, \fBT\fP &&\&.\&.\&. args)"
.br
.RI "The class constructor with the parameter ellipse\&. "
.in -1c
.SH "Detailed Description"
.PP 
The base-class for all other exceptions 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DeadlyErrorBase::DeadlyErrorBase (\fBAssimp::Formatter::format\fP f)\fR [protected]\fP"

.PP
The class constructor with the formatter\&. 
.PP
\fBParameters\fP
.RS 4
\fIf\fP The formatter\&. 
.RE
.PP

.SS "template<typename\&.\&.\&. T, typename \fBU\fP > DeadlyErrorBase::DeadlyErrorBase (\fBAssimp::Formatter::format\fP f, \fBU\fP && u, \fBT\fP &&\&.\&.\&. args)\fR [inline]\fP, \fR [protected]\fP"

.PP
The class constructor with the parameter ellipse\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fI\&.\&.\&.T\fP The type for the ellipse 
.br
\fIU\fP The other type 
.RE
.PP
\fBParameters\fP
.RS 4
\fIf\fP The formatter 
.br
\fIu\fP One parameter 
.br
\fI\&.\&.\&.args\fP The rest 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
