.TH "Debug::LogStream" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Debug::LogStream
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DEBUG_LOGGER\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogStream\fP ()"
.br
.ti -1c
.RI "\fB~LogStream\fP ()"
.br
.ti -1c
.RI "template<typename \fBt\fP > \fBLogStream\fP & \fBoperator<<\fP (const \fBt\fP &value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB40\fP of file \fBDEBUG_LOGGER\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Debug::LogStream::LogStream ()\fR [inline]\fP"

.PP
Definition at line \fB42\fP of file \fBDEBUG_LOGGER\&.h\fP\&.
.nf
42 : stream() {}
.PP
.fi

.SS "Debug::LogStream::~LogStream ()\fR [inline]\fP"

.PP
Definition at line \fB43\fP of file \fBDEBUG_LOGGER\&.h\fP\&.
.nf
43                      {
44             Logger::log(stream\&.str());
45         }
.PP
.fi

.PP
References \fBDebug::Logger::log()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBt\fP > \fBLogStream\fP & Debug::LogStream::operator<< (const \fBt\fP & value)\fR [inline]\fP"

.PP
Definition at line \fB48\fP of file \fBDEBUG_LOGGER\&.h\fP\&.
.nf
48                                               {
49             stream << value;
50             return *this;
51         }
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
