.TH "UPRISE_ENGINE/DEBUG_LOGGER.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/DEBUG_LOGGER.h
.SH SYNOPSIS
.br
.PP
\fR#include 'pch\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDebug::Error\fP"
.br
.ti -1c
.RI "class \fBDebug::Logger\fP"
.br
.ti -1c
.RI "class \fBDebug::LogStream\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDebug\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_DEBUG_LOGGER_\fP"
.br
.ti -1c
.RI "#define \fBERROR\fP   \fBError\fP"
.br
.ti -1c
.RI "#define \fBWhite\fP   system('COLOR 0F');"
.br
.ti -1c
.RI "#define \fBRed\fP   system('COLOR 0C');"
.br
.ti -1c
.RI "#define \fBYellow\fP   system('COLOR 06');"
.br
.ti -1c
.RI "#define \fBRedException\fP   system('COLOR 04');"
.br
.ti -1c
.RI "#define \fBLog\fP   \fBDebug::LogStream\fP()"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBErrorCode\fP { \fBLowMemory\fP, \fBNoMatchinngComponentFoud\fP }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _DEBUG_LOGGER_"

.PP
Definition at line \fB3\fP of file \fBDEBUG_LOGGER\&.h\fP\&.
.SS "#define ERROR   \fBError\fP"

.PP
Definition at line \fB6\fP of file \fBDEBUG_LOGGER\&.h\fP\&.
.SS "#define Log   \fBDebug::LogStream\fP()"

.PP
Definition at line \fB58\fP of file \fBDEBUG_LOGGER\&.h\fP\&.
.PP
Referenced by \fBCORE::Startup::Configure_Startup()\fP, \fBCORE::ConfigLoader::GameobjectFromCFGFile()\fP, \fBCORE::Startup::Init_Startup()\fP, \fBCORE::ConfigLoader::LoadConfigFiles()\fP, \fBmain()\fP, \fBPAIN::RenderStup::Setup()\fP, \fBCORE::Startup::Start_Systems()\fP, and \fBPAIN::RenderStup::Window()\fP\&.
.SS "#define Red   system('COLOR 0C');"

.PP
Definition at line \fB8\fP of file \fBDEBUG_LOGGER\&.h\fP\&.
.SS "#define RedException   system('COLOR 04');"

.PP
Definition at line \fB10\fP of file \fBDEBUG_LOGGER\&.h\fP\&.
.SS "#define White   system('COLOR 0F');"

.PP
Definition at line \fB7\fP of file \fBDEBUG_LOGGER\&.h\fP\&.
.SS "#define Yellow   system('COLOR 06');"

.PP
Definition at line \fB9\fP of file \fBDEBUG_LOGGER\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBErrorCode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILowMemory \fP\fP
.TP
\fB\fINoMatchinngComponentFoud \fP\fP
.PP
Definition at line \fB12\fP of file \fBDEBUG_LOGGER\&.h\fP\&.
.nf
12                {
13     LowMemory,
14     NoMatchinngComponentFoud,
15 
16 
17 };
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
