.TH "Debug::Error" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Debug::Error
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DEBUG_LOGGER\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBError\fP (\fBErrorCode\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBDEBUG_LOGGER\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Debug::Error::Error (\fBErrorCode\fP )"

.PP
Definition at line \fB3\fP of file \fBDEBUG_LOGGER\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
