.TH "adhed/assimp/DefaultLogger.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/assimp/DefaultLogger.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'LogStream\&.hpp'\fP
.br
\fR#include 'Logger\&.hpp'\fP
.br
\fR#include 'NullLogger\&.hpp'\fP
.br
\fR#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAssimp::DefaultLogger\fP"
.br
.RI "CPP-API: Primary logging facility of \fBAssimp\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAssimp\fP"
.br
.RI "Some C++ utilities for inter- and extrapolation\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINCLUDED_AI_DEFAULTLOGGER\fP"
.br
.ti -1c
.RI "#define \fBASSIMP_DEFAULT_LOG_NAME\fP   'AssimpLog\&.txt'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ASSIMP_DEFAULT_LOG_NAME   'AssimpLog\&.txt'"
default name of log-file 
.SS "#define INCLUDED_AI_DEFAULTLOGGER"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
