.TH "DefaultSampleDesc" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DefaultSampleDesc
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3dx12_pipeline_state_stream\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoperator DXGI_SAMPLE_DESC\fP () noexcept"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "DefaultSampleDesc::operator \fBDXGI_SAMPLE_DESC\fP ()\fR [inline]\fP, \fR [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
