.TH "deprecated" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 
.PP

.IP "\fBMember \fBaiProcess_ConvertToLeftHanded\fP \fP" 1c
  
.IP "\fBMember \fBbasic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::iterator_wrapper\fP (reference ref) noexcept\fP" 1c
This function is deprecated since 3\&.1\&.0 and will be removed in version 4\&.0\&.0 of the library\&. Please use \fBitems()\fP instead; that is, replace \fRjson::iterator_wrapper(j)\fP with \fRj\&.items()\fP\&.  
.IP "\fBMember \fBbasic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::iterator_wrapper\fP (const_reference ref) noexcept\fP" 1c
This function is deprecated since 3\&.1\&.0 and will be removed in version 4\&.0\&.0 of the library\&. Please use \fBitems()\fP instead; that is, replace \fRjson::iterator_wrapper(j)\fP with \fRj\&.items()\fP\&.  
.IP "\fBMember \fBbasic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::operator<<\fP (\fBbasic_json\fP &j, std::istream &i)\fP" 1c
This stream operator is deprecated since 3\&.0\&.0 and will be removed in version 4\&.0\&.0 of the library\&. Please use \fBoperator>>(std::istream&, basic_json&)\fP instead; that is, replace calls like \fRj << i;\fP with \fRi >> j;\fP\&.  
.IP "\fBMember \fBbasic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::sax_parse\fP (\fBdetail::span_input_adapter\fP &&i, SAX *sax, input_format_t format=input_format_t::json, const bool strict=true, const bool ignore_comments=false)\fP" 1c
This function is deprecated since 3\&.8\&.0 and will be removed in version 4\&.0\&.0 of the library\&. Please use sax_parse(ptr, ptr + len) instead\&.  
.IP "\fBMember \fBGLFWcharmodsfun\fP )(GLFWwindow *window, unsigned int codepoint, int mods)\fP" 1c
Scheduled for removal in version 4\&.0\&. 
.IP "\fBMember \fBglfwSetCharModsCallback\fP (GLFWwindow *window, GLFWcharmodsfun callback)\fP" 1c
Scheduled for removal in version 4\&.0\&.
.PP

