.TH "packages/directxtk12_uwp.2024.6.5.1/include/DescriptorHeap.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/directxtk12_uwp.2024.6.5.1/include/DescriptorHeap.h
.SH SYNOPSIS
.br
.PP
\fR#include <d3d12\&.h>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <wrl/client\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDirectX::DescriptorHeap\fP"
.br
.ti -1c
.RI "class \fBDirectX::DescriptorPile\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDirectX\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
