.TH "detail::invalid_iterator" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail::invalid_iterator \- exception indicating errors with iterators  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <json\&.hpp>\fP
.PP
Inherits \fBdetail::exception\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename BasicJsonContext , \fBenable_if_t\fP< \fBis_basic_json_context\fP< BasicJsonContext >\fB::value\fP, int >  = 0> static \fBinvalid_iterator\fP \fBcreate\fP (int id_, const std::string &what_arg, BasicJsonContext context)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBdetail::exception\fP
.in +1c
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.RI "returns the explanatory string "
.in -1c

Public Attributes inherited from \fBdetail::exception\fP
.in +1c
.ti -1c
.RI "const int \fBid\fP"
.br
.RI "the id of the exception "
.in -1c

Protected Member Functions inherited from \fBdetail::exception\fP
.in +1c
.ti -1c
.RI "\fBexception\fP (int id_, const char *what_arg)"
.br
.in -1c

Static Protected Member Functions inherited from \fBdetail::exception\fP
.in +1c
.ti -1c
.RI "static std::string \fBname\fP (const std::string &ename, int id_)"
.br
.ti -1c
.RI "static std::string \fBdiagnostics\fP (std::nullptr_t)"
.br
.ti -1c
.RI "template<typename BasicJsonType > static std::string \fBdiagnostics\fP (const BasicJsonType *leaf_element)"
.br
.in -1c
.SH "Detailed Description"
.PP 
exception indicating errors with iterators 


.PP
\fBSee also\fP
.RS 4
https://json.nlohmann.me/api/basic_json/invalid_iterator/ 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<typename BasicJsonContext , \fBenable_if_t\fP< \fBis_basic_json_context\fP< BasicJsonContext >\fB::value\fP, int >  = 0> static \fBinvalid_iterator\fP detail::invalid_iterator::create (int id_, const std::string & what_arg, BasicJsonContext context)\fR [inline]\fP, \fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
