.TH "detail::file_input_adapter" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail::file_input_adapter
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <json\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBchar_type\fP = char"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfile_input_adapter\fP (std::FILE *\fBf\fP) noexcept"
.br
.ti -1c
.RI "\fBfile_input_adapter\fP (const \fBfile_input_adapter\fP &)=delete"
.br
.ti -1c
.RI "\fBfile_input_adapter\fP (\fBfile_input_adapter\fP &&) noexcept=default"
.br
.ti -1c
.RI "\fBfile_input_adapter\fP & \fBoperator=\fP (const \fBfile_input_adapter\fP &)=delete"
.br
.ti -1c
.RI "\fBfile_input_adapter\fP & \fBoperator=\fP (\fBfile_input_adapter\fP &&)=delete"
.br
.ti -1c
.RI "\fB~file_input_adapter\fP ()=default"
.br
.ti -1c
.RI "std::char_traits< char >::int_type \fBget_character\fP () noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
Input adapter for stdio file access\&. This adapter read only 1 byte and do not use any buffer\&. This adapter is a very low level adapter\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBdetail::file_input_adapter::char_type\fP = char"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "detail::file_input_adapter::file_input_adapter (std::FILE * f)\fR [inline]\fP, \fR [explicit]\fP, \fR [noexcept]\fP"

.SS "detail::file_input_adapter::file_input_adapter (const \fBfile_input_adapter\fP & )\fR [delete]\fP"

.SS "detail::file_input_adapter::file_input_adapter (\fBfile_input_adapter\fP && )\fR [default]\fP, \fR [noexcept]\fP"

.SS "detail::file_input_adapter::~file_input_adapter ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::char_traits< char >::int_type detail::file_input_adapter::get_character ()\fR [inline]\fP, \fR [noexcept]\fP"

.SS "\fBfile_input_adapter\fP & detail::file_input_adapter::operator= (const \fBfile_input_adapter\fP & )\fR [delete]\fP"

.SS "\fBfile_input_adapter\fP & detail::file_input_adapter::operator= (\fBfile_input_adapter\fP && )\fR [delete]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
