.TH "detail::detector< Default, void_t< Op< Args... > >, Op, Args... >" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail::detector< Default, void_t< Op< Args... > >, Op, Args... >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <json\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBvalue_t\fP = std::true_type"
.br
.ti -1c
.RI "using \fBtype\fP = Op<Args\&.\&.\&.>"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<class Default , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBdetail::detector\fP< Default, \fBvoid_t\fP< Op< Args\&.\&.\&. > >, Op, Args\&.\&.\&. >\fB::type\fP = Op<Args\&.\&.\&.>"

.SS "template<class Default , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBdetail::detector\fP< Default, \fBvoid_t\fP< Op< Args\&.\&.\&. > >, Op, Args\&.\&.\&. >::value_t = std::true_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
