.TH "detail::from_json_fn" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail::from_json_fn
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <json\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename BasicJsonType , typename \fBT\fP > auto \fBoperator()\fP (const BasicJsonType &j, \fBT\fP &&\fBval\fP) const noexcept(noexcept(\fBfrom_json\fP(j, std::forward< \fBT\fP >(\fBval\fP)))) \-> decltype(\fBfrom_json\fP(j, std::forward< \fBT\fP >(\fBval\fP)))"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename BasicJsonType , typename \fBT\fP > auto detail::from_json_fn::operator() (const BasicJsonType & j, \fBT\fP && val) const \-> decltype(\fBfrom_json\fP(j, std::forward<\fBT\fP>(\fBval\fP)))
    \fR [inline]\fP, \fR [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
