.TH "detail::is_basic_json_context< BasicJsonContext >" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail::is_basic_json_context< BasicJsonContext >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <json\&.hpp>\fP
.PP
Inherits std::integral_constant< bool, is_basic_json< std::remove_cv< std::remove_pointer< BasicJsonContext >::type >::type >::value||std::is_same< BasicJsonContext, std::nullptr_t >::value >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
