.TH "detail::conjunction< B, Bn... >" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail::conjunction< B, Bn... >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <json\&.hpp>\fP
.PP
Inherits std::conditional::type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
