.TH "detail::has_to_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail::has_to_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <json\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBserializer\fP = typename BasicJsonType::template json_serializer<\fBT\fP, \fBvoid\fP>"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr bool \fBvalue\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename BasicJsonType , typename \fBT\fP > using \fBdetail::has_to_json\fP< BasicJsonType, \fBT\fP, \fBenable_if_t\fP< !\fBis_basic_json\fP< \fBT\fP >\fB::value\fP > >::serializer = typename BasicJsonType::template json_serializer<\fBT\fP, \fBvoid\fP>"

.SH "Member Data Documentation"
.PP 
.SS "template<typename BasicJsonType , typename \fBT\fP > bool \fBdetail::has_to_json\fP< BasicJsonType, \fBT\fP, \fBenable_if_t\fP< !\fBis_basic_json\fP< \fBT\fP >\fB::value\fP > >\fB::value\fP\fR [static]\fP, \fR [constexpr]\fP"
\fBInitial value:\fP
.nf
=
        is_detected_exact<void, to_json_function, serializer, BasicJsonType&,
        T>::value
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
