.TH "detail::binary_writer< BasicJsonType, CharType >" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail::binary_writer< BasicJsonType, CharType > \- serialization to CBOR and MessagePack values  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <json\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbinary_writer\fP (\fBoutput_adapter_t\fP< CharType > adapter)"
.br
.RI "create a binary writer "
.ti -1c
.RI "\fBvoid\fP \fBwrite_bson\fP (const BasicJsonType &j)"
.br
.ti -1c
.RI "\fBvoid\fP \fBwrite_cbor\fP (const BasicJsonType &j)"
.br
.ti -1c
.RI "\fBvoid\fP \fBwrite_msgpack\fP (const BasicJsonType &j)"
.br
.ti -1c
.RI "\fBvoid\fP \fBwrite_ubjson\fP (const BasicJsonType &j, const bool use_count, const bool use_type, const bool add_prefix=true, const bool use_bjdata=false)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename \fBC\fP  = CharType, \fBenable_if_t\fP< std::is_signed< \fBC\fP >\fB::value\fP &&std::is_signed< char >\fB::value\fP > *  = nullptr> static constexpr CharType \fBto_char_type\fP (std::uint8_t \fBx\fP) noexcept"
.br
.ti -1c
.RI "template<typename \fBC\fP  = CharType, \fBenable_if_t\fP< std::is_signed< \fBC\fP >\fB::value\fP &&std::is_unsigned< char >\fB::value\fP > *  = nullptr> static CharType \fBto_char_type\fP (std::uint8_t \fBx\fP) noexcept"
.br
.ti -1c
.RI "template<typename \fBC\fP  = CharType, \fBenable_if_t\fP< std::is_unsigned< \fBC\fP >\fB::value\fP > *  = nullptr> static constexpr CharType \fBto_char_type\fP (std::uint8_t \fBx\fP) noexcept"
.br
.ti -1c
.RI "template<typename InputCharType , typename \fBC\fP  = CharType, \fBenable_if_t\fP< std::is_signed< \fBC\fP >\fB::value\fP &&std::is_signed< char >\fB::value\fP &&std::is_same< char, typename std::remove_cv< InputCharType >\fB::type\fP >\fB::value\fP > *  = nullptr> static constexpr CharType \fBto_char_type\fP (InputCharType \fBx\fP) noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename BasicJsonType, typename CharType>
.br
class detail::binary_writer< BasicJsonType, CharType >"serialization to CBOR and MessagePack values 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename BasicJsonType , typename CharType > \fBdetail::binary_writer\fP< BasicJsonType, CharType >::binary_writer (\fBoutput_adapter_t\fP< CharType > adapter)\fR [inline]\fP, \fR [explicit]\fP"

.PP
create a binary writer 
.PP
\fBParameters\fP
.RS 4
\fIadapter\fP output adapter to write to 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<typename BasicJsonType , typename CharType > template<typename InputCharType , typename \fBC\fP  = CharType, \fBenable_if_t\fP< std::is_signed< \fBC\fP >\fB::value\fP &&std::is_signed< char >\fB::value\fP &&std::is_same< char, typename std::remove_cv< InputCharType >\fB::type\fP >\fB::value\fP > *  = nullptr> static constexpr CharType \fBdetail::binary_writer\fP< BasicJsonType, CharType >::to_char_type (InputCharType x)\fR [inline]\fP, \fR [static]\fP, \fR [constexpr]\fP, \fR [noexcept]\fP"

.SS "template<typename BasicJsonType , typename CharType > template<typename \fBC\fP  = CharType, \fBenable_if_t\fP< std::is_signed< \fBC\fP >\fB::value\fP &&std::is_signed< char >\fB::value\fP > *  = nullptr> static constexpr CharType \fBdetail::binary_writer\fP< BasicJsonType, CharType >::to_char_type (std::uint8_t x)\fR [inline]\fP, \fR [static]\fP, \fR [constexpr]\fP, \fR [noexcept]\fP"

.SS "template<typename BasicJsonType , typename CharType > template<typename \fBC\fP  = CharType, \fBenable_if_t\fP< std::is_signed< \fBC\fP >\fB::value\fP &&std::is_unsigned< char >\fB::value\fP > *  = nullptr> static CharType \fBdetail::binary_writer\fP< BasicJsonType, CharType >::to_char_type (std::uint8_t x)\fR [inline]\fP, \fR [static]\fP, \fR [noexcept]\fP"

.SS "template<typename BasicJsonType , typename CharType > template<typename \fBC\fP  = CharType, \fBenable_if_t\fP< std::is_unsigned< \fBC\fP >\fB::value\fP > *  = nullptr> static constexpr CharType \fBdetail::binary_writer\fP< BasicJsonType, CharType >::to_char_type (std::uint8_t x)\fR [inline]\fP, \fR [static]\fP, \fR [constexpr]\fP, \fR [noexcept]\fP"

.SS "template<typename BasicJsonType , typename CharType > \fBvoid\fP \fBdetail::binary_writer\fP< BasicJsonType, CharType >::write_bson (const BasicJsonType & j)\fR [inline]\fP"

.PP
\fBParameters\fP
.RS 4
\fIj\fP JSON value to serialize 
.RE
.PP
\fBPrecondition\fP
.RS 4
j\&.type() == \fBvalue_t::object\fP 
.RE
.PP

.SS "template<typename BasicJsonType , typename CharType > \fBvoid\fP \fBdetail::binary_writer\fP< BasicJsonType, CharType >::write_cbor (const BasicJsonType & j)\fR [inline]\fP"

.PP
\fBParameters\fP
.RS 4
\fIj\fP JSON value to serialize 
.RE
.PP

.SS "template<typename BasicJsonType , typename CharType > \fBvoid\fP \fBdetail::binary_writer\fP< BasicJsonType, CharType >::write_msgpack (const BasicJsonType & j)\fR [inline]\fP"

.PP
\fBParameters\fP
.RS 4
\fIj\fP JSON value to serialize 
.RE
.PP

.SS "template<typename BasicJsonType , typename CharType > \fBvoid\fP \fBdetail::binary_writer\fP< BasicJsonType, CharType >::write_ubjson (const BasicJsonType & j, const bool use_count, const bool use_type, const bool add_prefix = \fRtrue\fP, const bool use_bjdata = \fRfalse\fP)\fR [inline]\fP"

.PP
\fBParameters\fP
.RS 4
\fIj\fP JSON value to serialize 
.br
\fIuse_count\fP whether to use '#' prefixes (optimized format) 
.br
\fIuse_type\fP whether to use '$' prefixes (optimized format) 
.br
\fIadd_prefix\fP whether prefixes need to be used for this value 
.br
\fIuse_bjdata\fP whether write in BJData format, default is false 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
