.TH "DirectMLPyTorchCreatorID" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectMLPyTorchCreatorID
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12compatibility\&.idl;\fP
.PP
Inherits IUnknown\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
