.TH "UPRISE_PROFILER/dllmain.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_PROFILER/dllmain.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'pch\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "BOOL \fBAPIENTRY\fP \fBDllMain\fP (HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOL \fBAPIENTRY\fP DllMain (HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
