.TH "adhed/glm/gtx/dual_quaternion.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/dual_quaternion.inl
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./geometric\&.hpp'\fP
.br
\fR#include <limits>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBtdualquat\fP< \fBT\fP, \fBQ\fP > \fBglm::operator+\fP (\fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &q)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBtdualquat\fP< \fBT\fP, \fBQ\fP > \fBglm::operator\-\fP (\fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &q)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBtdualquat\fP< \fBT\fP, \fBQ\fP > \fBglm::operator+\fP (\fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &q, \fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &p)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBtdualquat\fP< \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &p, \fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &o)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &q, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &q)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &q, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &q)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBtdualquat\fP< \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &q, \fBT\fP const &s)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBtdualquat\fP< \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBT\fP const &s, \fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &q)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBtdualquat\fP< \fBT\fP, \fBQ\fP > \fBglm::operator/\fP (\fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &q, \fBT\fP const &s)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP bool \fBglm::operator==\fP (\fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &q1, \fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &q2)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP bool \fBglm::operator!=\fP (\fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &q1, \fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &q2)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBtdualquat\fP< \fBT\fP, \fBQ\fP > \fBglm::dual_quat_identity\fP ()"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBtdualquat\fP< \fBT\fP, \fBQ\fP > \fBglm::normalize\fP (\fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &q)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBtdualquat\fP< \fBT\fP, \fBQ\fP > \fBglm::lerp\fP (\fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBT\fP const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBtdualquat\fP< \fBT\fP, \fBQ\fP > \fBglm::inverse\fP (\fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &q)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 2, 4, \fBT\fP, \fBQ\fP > \fBglm::mat2x4_cast\fP (\fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 3, 4, \fBT\fP, \fBQ\fP > \fBglm::mat3x4_cast\fP (\fBtdualquat\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBtdualquat\fP< \fBT\fP, \fBQ\fP > \fBglm::dualquat_cast\fP (\fBmat\fP< 2, 4, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBtdualquat\fP< \fBT\fP, \fBQ\fP > \fBglm::dualquat_cast\fP (\fBmat\fP< 3, 4, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
