.TH "DXGI_SAMPLE_DESC" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DXGI_SAMPLE_DESC
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <dxgicommon\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBCount\fP"
.br
.ti -1c
.RI "UINT \fBQuality\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UINT DXGI_SAMPLE_DESC::Count"

.SS "UINT DXGI_SAMPLE_DESC::Quality"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
