.TH "adhed/glm/gtx/easing.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/easing.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./glm\&.hpp'\fP
.br
\fR#include '\&.\&./gtc/constants\&.hpp'\fP
.br
\fR#include '\&.\&./detail/qualifier\&.hpp'\fP
.br
\fR#include 'easing\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::linearInterpolation\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quadraticEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quadraticEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quadraticEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::cubicEaseIn\fP (genType const &\fBa\fP)"
.br
.RI "Modelled after the cubic y = x^3\&. "
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::cubicEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::cubicEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quarticEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quarticEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quarticEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quinticEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quinticEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quinticEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::sineEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::sineEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::sineEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::circularEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::circularEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::circularEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::exponentialEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::exponentialEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::exponentialEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::elasticEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::elasticEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::elasticEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::backEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::backEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::backEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::backEaseIn\fP (genType const &\fBa\fP, genType const &o)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::backEaseOut\fP (genType const &\fBa\fP, genType const &o)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::backEaseInOut\fP (genType const &\fBa\fP, genType const &o)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::bounceEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::bounceEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::bounceEaseInOut\fP (genType const &\fBa\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_easing\fP
.PP
\fBAuthor\fP
.RS 4
Robert Chisholm
.RE
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
