.TH "EDITOR::Editor" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EDITOR::Editor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <EDITOR\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBStartEditor\fP ()"
.br
.ti -1c
.RI "static void \fBDrawEditor\fP ()"
.br
.ti -1c
.RI "static void \fBCompileCode\fP ()"
.br
.ti -1c
.RI "static void \fBBuild\fP ()"
.br
.ti -1c
.RI "static void \fBReload\fP ()"
.br
.ti -1c
.RI "static void \fBSetApplicationMode\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBEDITOR\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void EDITOR::Editor::Build ()\fR [static]\fP"

.PP
Definition at line \fB35\fP of file \fBEDITOR\&.cpp\fP\&.
.nf
36 {
37 }
.PP
.fi

.SS "void EDITOR::Editor::CompileCode ()\fR [static]\fP"

.PP
Definition at line \fB31\fP of file \fBEDITOR\&.cpp\fP\&.
.nf
32 {
33 }
.PP
.fi

.SS "void EDITOR::Editor::DrawEditor ()\fR [static]\fP"

.PP
Definition at line \fB21\fP of file \fBEDITOR\&.cpp\fP\&.
.nf
22 {
23     {
24         BEGIN("ASSETS");
25         auto assetfolder = CORE::Filehandler::ApplicationPath();
26         SearchFolderRecrusively(assetfolder);
27         END;
28     }
29 }
.PP
.fi

.PP
References \fBCORE::Filehandler::ApplicationPath()\fP, \fBBEGIN\fP, and \fBEND\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "void EDITOR::Editor::Reload ()\fR [static]\fP"

.PP
Definition at line \fB39\fP of file \fBEDITOR\&.cpp\fP\&.
.nf
40 {
41 }
.PP
.fi

.SS "void EDITOR::Editor::SetApplicationMode ()\fR [static]\fP"

.PP
Definition at line \fB43\fP of file \fBEDITOR\&.cpp\fP\&.
.nf
44 {
45 }
.PP
.fi

.SS "int EDITOR::Editor::StartEditor ()\fR [static]\fP"

.PP
Definition at line \fB6\fP of file \fBEDITOR\&.cpp\fP\&.
.nf
7 {
8     return 0;
9 }
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
