.TH "UPRISE_ENGINE/EDITOR.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/EDITOR.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'pch\&.h'\fP
.br
\fR#include 'EDITOR\&.h'\fP
.br
\fR#include 'HeaderE/CORE/CORE\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBEGIN\fP(x)   ImGui::Begin(x);"
.br
.ti -1c
.RI "#define \fBEND\fP   ImGui::End();"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BEGIN( x)   ImGui::Begin(x);"

.PP
Definition at line \fB4\fP of file \fBEDITOR\&.cpp\fP\&.
.PP
Referenced by \fBEDITOR::Editor::DrawEditor()\fP\&.
.SS "#define END   ImGui::End();"

.PP
Definition at line \fB5\fP of file \fBEDITOR\&.cpp\fP\&.
.PP
Referenced by \fBEDITOR::Editor::DrawEditor()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
