.TH "adhed/glm/gtc/epsilon.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtc/epsilon.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./detail/setup\&.hpp'\fP
.br
\fR#include '\&.\&./detail/qualifier\&.hpp'\fP
.br
\fR#include 'epsilon\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, bool, \fBQ\fP > \fBglm::epsilonEqual\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBT\fP const &\fBepsilon\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP bool \fBglm::epsilonEqual\fP (genType const &\fBx\fP, genType const &\fBy\fP, genType const &\fBepsilon\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, bool, \fBQ\fP > \fBglm::epsilonNotEqual\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBT\fP const &\fBepsilon\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP bool \fBglm::epsilonNotEqual\fP (genType const &\fBx\fP, genType const &\fBy\fP, genType const &\fBepsilon\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTC_epsilon\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTC_quaternion\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
