.TH "EqualTo" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EqualTo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Helpers\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (\fBTypeInfoRef\fP lhs, \fBTypeInfoRef\fP rhs) const"
.br
.ti -1c
.RI "bool \fBoperator()\fP (\fBTypeInfoRef\fP lhs, \fBTypeInfoRef\fP rhs) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB37\fP of file \fBHelpers\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool EqualTo::operator() (\fBTypeInfoRef\fP lhs, \fBTypeInfoRef\fP rhs) const\fR [inline]\fP"

.PP
Definition at line \fB39\fP of file \fBHelpers\&.h\fP\&.
.nf
40     {
41         return lhs\&.get() == rhs\&.get();
42     }
.PP
.fi

.SS "bool EqualTo::operator() (\fBTypeInfoRef\fP lhs, \fBTypeInfoRef\fP rhs) const\fR [inline]\fP"

.PP
Definition at line \fB118\fP of file \fBpch\&.h\fP\&.
.nf
119     {
120         return lhs\&.get() == rhs\&.get();
121     }
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
