.TH "Event" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Event
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <D_EVENT\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEvent\fP ()=default"
.br
.ti -1c
.RI "template<class _Func , class\&.\&.\&. _Arg> \fBEvent\fP (std::shared_ptr< \fBGameObject\fP > TergetObj, _Func &&TergetFunc, _Arg &&\&.\&.\&. args)"
.br
.ti -1c
.RI "void \fBInvoke\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBD_EVENT\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Event::Event ()\fR [default]\fP"

.SS "template<class _Func , class\&.\&.\&. _Arg> Event::Event (std::shared_ptr< \fBGameObject\fP > TergetObj, _Func && TergetFunc, _Arg &&\&.\&.\&. args)\fR [inline]\fP"

.PP
Definition at line \fB13\fP of file \fBD_EVENT\&.h\fP\&.
.nf
13 :targetObject(targetObject), func(std::bind(std::forward<Func>(targetFunc), std::forward<Args>(args)\&.\&.\&.)) {}
.PP
.fi

.SH "Member Function Documentation"
.PP 
.SS "void Event::Invoke () const\fR [inline]\fP"

.PP
Definition at line \fB14\fP of file \fBD_EVENT\&.h\fP\&.
.nf
14                        {
15         func();
16     }
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
