.TH "ExampleDualListBox" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleDualListBox
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBMoveAll\fP (int src, int dst)"
.br
.ti -1c
.RI "void \fBMoveSelected\fP (int src, int dst)"
.br
.ti -1c
.RI "void \fBApplySelectionRequests\fP (ImGuiMultiSelectIO *ms_io, int side)"
.br
.ti -1c
.RI "void \fBSortItems\fP (int n)"
.br
.ti -1c
.RI "void \fBShow\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBIMGUI_CDECL\fP \fBCompareItemsByValue\fP (const void *lhs, const void *rhs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImVector< ImGuiID > \fBItems\fP [2]"
.br
.ti -1c
.RI "ImGuiSelectionBasicStorage \fBSelections\fP [2]"
.br
.ti -1c
.RI "bool \fBOptKeepSorted\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3020\fP of file \fBimgui_demo\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ExampleDualListBox::ApplySelectionRequests (ImGuiMultiSelectIO * ms_io, int side)\fR [inline]\fP"

.PP
Definition at line \fB3052\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
3053     {
3054         // In this example we store item id in selection (instead of item index)
3055         Selections[side]\&.UserData = Items[side]\&.Data;
3056         Selections[side]\&.AdapterIndexToStorageId = [](ImGuiSelectionBasicStorage* self, int idx) { ImGuiID* items = (ImGuiID*)self\->UserData; return items[idx]; };
3057         Selections[side]\&.ApplyRequests(ms_io);
3058     }
.PP
.fi

.PP
References \fBItems\fP, and \fBSelections\fP\&.
.PP
Referenced by \fBShow()\fP\&.
.SS "static int \fBIMGUI_CDECL\fP ExampleDualListBox::CompareItemsByValue (const void * lhs, const void * rhs)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB3059\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
3060     {
3061         const int* a = (const int*)lhs;
3062         const int* b = (const int*)rhs;
3063         return (*a \- *b) > 0 ? +1 : \-1;
3064     }
.PP
.fi

.PP
Referenced by \fBSortItems()\fP\&.
.SS "void ExampleDualListBox::MoveAll (int src, int dst)\fR [inline]\fP"

.PP
Definition at line \fB3026\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
3027     {
3028         IM_ASSERT((src == 0 && dst == 1) || (src == 1 && dst == 0));
3029         for (ImGuiID item_id : Items[src])
3030             Items[dst]\&.push_back(item_id);
3031         Items[src]\&.clear();
3032         SortItems(dst);
3033         Selections[src]\&.Swap(Selections[dst]);
3034         Selections[src]\&.Clear();
3035     }
.PP
.fi

.PP
References \fBItems\fP, \fBSelections\fP, and \fBSortItems()\fP\&.
.PP
Referenced by \fBShow()\fP\&.
.SS "void ExampleDualListBox::MoveSelected (int src, int dst)\fR [inline]\fP"

.PP
Definition at line \fB3036\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
3037     {
3038         for (int src_n = 0; src_n < Items[src]\&.Size; src_n++)
3039         {
3040             ImGuiID item_id = Items[src][src_n];
3041             if (!Selections[src]\&.Contains(item_id))
3042                 continue;
3043             Items[src]\&.erase(&Items[src][src_n]); // FIXME\-OPT: Could be implemented more optimally (rebuild src items and swap)
3044             Items[dst]\&.push_back(item_id);
3045             src_n\-\-;
3046         }
3047         if (OptKeepSorted)
3048             SortItems(dst);
3049         Selections[src]\&.Swap(Selections[dst]);
3050         Selections[src]\&.Clear();
3051     }
.PP
.fi

.PP
References \fBItems\fP, \fBOptKeepSorted\fP, \fBSelections\fP, and \fBSortItems()\fP\&.
.PP
Referenced by \fBShow()\fP\&.
.SS "void ExampleDualListBox::Show ()\fR [inline]\fP"

.PP
Definition at line \fB3069\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
3070     {
3071         //ImGui::Checkbox("Sorted", &OptKeepSorted);
3072         if (ImGui::BeginTable("split", 3, ImGuiTableFlags_None))
3073         {
3074             ImGui::TableSetupColumn("", ImGuiTableColumnFlags_WidthStretch);    // Left side
3075             ImGui::TableSetupColumn("", ImGuiTableColumnFlags_WidthFixed);      // Buttons
3076             ImGui::TableSetupColumn("", ImGuiTableColumnFlags_WidthStretch);    // Right side
3077             ImGui::TableNextRow();
3078 
3079             int request_move_selected = \-1;
3080             int request_move_all = \-1;
3081             float child_height_0 = 0\&.0f;
3082             for (int side = 0; side < 2; side++)
3083             {
3084                 // FIXME\-MULTISELECT: Dual List Box: Add context menus
3085                 // FIXME\-NAV: Using ImGuiWindowFlags_NavFlattened exhibit many issues\&.
3086                 ImVector<ImGuiID>& items = Items[side];
3087                 ImGuiSelectionBasicStorage& selection = Selections[side];
3088 
3089                 ImGui::TableSetColumnIndex((side == 0) ? 0 : 2);
3090                 ImGui::Text("%s (%d)", (side == 0) ? "Available" : "Basket", items\&.Size);
3091 
3092                 // Submit scrolling range to avoid glitches on moving/deletion
3093                 const float items_height = ImGui::GetTextLineHeightWithSpacing();
3094                 ImGui::SetNextWindowContentSize(ImVec2(0\&.0f, items\&.Size * items_height));
3095 
3096                 bool child_visible;
3097                 if (side == 0)
3098                 {
3099                     // Left child is resizable
3100                     ImGui::SetNextWindowSizeConstraints(ImVec2(0\&.0f, ImGui::GetFrameHeightWithSpacing() * 4), ImVec2(FLT_MAX, FLT_MAX));
3101                     child_visible = ImGui::BeginChild("0", ImVec2(\-FLT_MIN, ImGui::GetFontSize() * 20), ImGuiChildFlags_FrameStyle | ImGuiChildFlags_ResizeY);
3102                     child_height_0 = ImGui::GetWindowSize()\&.y;
3103                 }
3104                 else
3105                 {
3106                     // Right child use same height as left one
3107                     child_visible = ImGui::BeginChild("1", ImVec2(\-FLT_MIN, child_height_0), ImGuiChildFlags_FrameStyle);
3108                 }
3109                 if (child_visible)
3110                 {
3111                     ImGuiMultiSelectFlags flags = ImGuiMultiSelectFlags_None;
3112                     ImGuiMultiSelectIO* ms_io = ImGui::BeginMultiSelect(flags, selection\&.Size, items\&.Size);
3113                     ApplySelectionRequests(ms_io, side);
3114 
3115                     for (int item_n = 0; item_n < items\&.Size; item_n++)
3116                     {
3117                         ImGuiID item_id = items[item_n];
3118                         bool item_is_selected = selection\&.Contains(item_id);
3119                         ImGui::SetNextItemSelectionUserData(item_n);
3120                         ImGui::Selectable(ExampleNames[item_id], item_is_selected, ImGuiSelectableFlags_AllowDoubleClick);
3121                         if (ImGui::IsItemFocused())
3122                         {
3123                             // FIXME\-MULTISELECT: Dual List Box: Transfer focus
3124                             if (ImGui::IsKeyPressed(ImGuiKey_Enter) || ImGui::IsKeyPressed(ImGuiKey_KeypadEnter))
3125                                 request_move_selected = side;
3126                             if (ImGui::IsMouseDoubleClicked(0)) // FIXME\-MULTISELECT: Double\-click on multi\-selection?
3127                                 request_move_selected = side;
3128                         }
3129                     }
3130 
3131                     ms_io = ImGui::EndMultiSelect();
3132                     ApplySelectionRequests(ms_io, side);
3133                 }
3134                 ImGui::EndChild();
3135             }
3136 
3137             // Buttons columns
3138             ImGui::TableSetColumnIndex(1);
3139             ImGui::NewLine();
3140             //ImVec2 button_sz = { ImGui::CalcTextSize(">>")\&.x + ImGui::GetStyle()\&.FramePadding\&.x * 2\&.0f, ImGui::GetFrameHeight() + padding\&.y * 2\&.0f };
3141             ImVec2 button_sz = { ImGui::GetFrameHeight(), ImGui::GetFrameHeight() };
3142 
3143             // (Using BeginDisabled()/EndDisabled() works but feels distracting given how it is currently visualized)
3144             if (ImGui::Button(">>", button_sz))
3145                 request_move_all = 0;
3146             if (ImGui::Button(">", button_sz))
3147                 request_move_selected = 0;
3148             if (ImGui::Button("<", button_sz))
3149                 request_move_selected = 1;
3150             if (ImGui::Button("<<", button_sz))
3151                 request_move_all = 1;
3152 
3153             // Process requests
3154             if (request_move_all != \-1)
3155                 MoveAll(request_move_all, request_move_all ^ 1);
3156             if (request_move_selected != \-1)
3157                 MoveSelected(request_move_selected, request_move_selected ^ 1);
3158 
3159             // FIXME\-MULTISELECT: Support action from outside
3160             /*
3161             if (OptKeepSorted == false)
3162             {
3163                 ImGui::NewLine();
3164                 if (ImGui::ArrowButton("MoveUp", ImGuiDir_Up)) {}
3165                 if (ImGui::ArrowButton("MoveDown", ImGuiDir_Down)) {}
3166             }
3167             */
3168 
3169             ImGui::EndTable();
3170         }
3171     }
.PP
.fi

.PP
References \fBApplySelectionRequests()\fP, \fBItems\fP, \fBMoveAll()\fP, \fBMoveSelected()\fP, and \fBSelections\fP\&.
.SS "void ExampleDualListBox::SortItems (int n)\fR [inline]\fP"

.PP
Definition at line \fB3065\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
3066     {
3067         qsort(Items[n]\&.Data, (size_t)Items[n]\&.Size, sizeof(Items[n][0]), CompareItemsByValue);
3068     }
.PP
.fi

.PP
References \fBCompareItemsByValue()\fP, and \fBItems\fP\&.
.PP
Referenced by \fBMoveAll()\fP, and \fBMoveSelected()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "ImVector<ImGuiID> ExampleDualListBox::Items[2]"

.PP
Definition at line \fB3022\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBApplySelectionRequests()\fP, \fBMoveAll()\fP, \fBMoveSelected()\fP, \fBShow()\fP, and \fBSortItems()\fP\&.
.SS "bool ExampleDualListBox::OptKeepSorted = true"

.PP
Definition at line \fB3024\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBMoveSelected()\fP\&.
.SS "ImGuiSelectionBasicStorage ExampleDualListBox::Selections[2]"

.PP
Definition at line \fB3023\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBApplySelectionRequests()\fP, \fBMoveAll()\fP, \fBMoveSelected()\fP, and \fBShow()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
