.TH "ExampleAssetsBrowser" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleAssetsBrowser
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExampleAssetsBrowser\fP ()"
.br
.ti -1c
.RI "void \fBAddItems\fP (int count)"
.br
.ti -1c
.RI "void \fBClearItems\fP ()"
.br
.ti -1c
.RI "void \fBUpdateLayoutSizes\fP (float avail_width)"
.br
.ti -1c
.RI "void \fBDraw\fP (const char *title, bool *p_open)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBShowTypeOverlay\fP = true"
.br
.ti -1c
.RI "bool \fBAllowSorting\fP = true"
.br
.ti -1c
.RI "bool \fBAllowDragUnselected\fP = false"
.br
.ti -1c
.RI "bool \fBAllowBoxSelect\fP = true"
.br
.ti -1c
.RI "float \fBIconSize\fP = 32\&.0f"
.br
.ti -1c
.RI "int \fBIconSpacing\fP = 10"
.br
.ti -1c
.RI "int \fBIconHitSpacing\fP = 4"
.br
.ti -1c
.RI "bool \fBStretchSpacing\fP = true"
.br
.ti -1c
.RI "ImVector< \fBExampleAsset\fP > \fBItems\fP"
.br
.ti -1c
.RI "\fBExampleSelectionWithDeletion\fP \fBSelection\fP"
.br
.ti -1c
.RI "ImGuiID \fBNextItemId\fP = 0"
.br
.ti -1c
.RI "bool \fBRequestDelete\fP = false"
.br
.ti -1c
.RI "bool \fBRequestSort\fP = false"
.br
.ti -1c
.RI "float \fBZoomWheelAccum\fP = 0\&.0f"
.br
.ti -1c
.RI "ImVec2 \fBLayoutItemSize\fP"
.br
.ti -1c
.RI "ImVec2 \fBLayoutItemStep\fP"
.br
.ti -1c
.RI "float \fBLayoutItemSpacing\fP = 0\&.0f"
.br
.ti -1c
.RI "float \fBLayoutSelectableSpacing\fP = 0\&.0f"
.br
.ti -1c
.RI "float \fBLayoutOuterPadding\fP = 0\&.0f"
.br
.ti -1c
.RI "int \fBLayoutColumnCount\fP = 0"
.br
.ti -1c
.RI "int \fBLayoutLineCount\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10252\fP of file \fBimgui_demo\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExampleAssetsBrowser::ExampleAssetsBrowser ()\fR [inline]\fP"

.PP
Definition at line \fB10282\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
10283     {
10284         AddItems(10000);
10285     }
.PP
.fi

.PP
References \fBAddItems()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ExampleAssetsBrowser::AddItems (int count)\fR [inline]\fP"

.PP
Definition at line \fB10286\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
10287     {
10288         if (Items\&.Size == 0)
10289             NextItemId = 0;
10290         Items\&.reserve(Items\&.Size + count);
10291         for (int n = 0; n < count; n++, NextItemId++)
10292             Items\&.push_back(ExampleAsset(NextItemId, (NextItemId % 20) < 15 ? 0 : (NextItemId % 20) < 18 ? 1 : 2));
10293         RequestSort = true;
10294     }
.PP
.fi

.PP
References \fBItems\fP, \fBNextItemId\fP, and \fBRequestSort\fP\&.
.PP
Referenced by \fBDraw()\fP, and \fBExampleAssetsBrowser()\fP\&.
.SS "void ExampleAssetsBrowser::ClearItems ()\fR [inline]\fP"

.PP
Definition at line \fB10295\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
10296     {
10297         Items\&.clear();
10298         Selection\&.Clear();
10299     }
.PP
.fi

.PP
References \fBItems\fP, and \fBSelection\fP\&.
.PP
Referenced by \fBDraw()\fP\&.
.SS "void ExampleAssetsBrowser::Draw (const char * title, bool * p_open)\fR [inline]\fP"

.PP
Definition at line \fB10324\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
10325     {
10326         ImGui::SetNextWindowSize(ImVec2(IconSize * 25, IconSize * 15), ImGuiCond_FirstUseEver);
10327         if (!ImGui::Begin(title, p_open, ImGuiWindowFlags_MenuBar))
10328         {
10329             ImGui::End();
10330             return;
10331         }
10332 
10333         // Menu bar
10334         if (ImGui::BeginMenuBar())
10335         {
10336             if (ImGui::BeginMenu("File"))
10337             {
10338                 if (ImGui::MenuItem("Add 10000 items"))
10339                     AddItems(10000);
10340                 if (ImGui::MenuItem("Clear items"))
10341                     ClearItems();
10342                 ImGui::Separator();
10343                 if (ImGui::MenuItem("Close", NULL, false, p_open != NULL))
10344                     *p_open = false;
10345                 ImGui::EndMenu();
10346             }
10347             if (ImGui::BeginMenu("Edit"))
10348             {
10349                 if (ImGui::MenuItem("Delete", "Del", false, Selection\&.Size > 0))
10350                     RequestDelete = true;
10351                 ImGui::EndMenu();
10352             }
10353             if (ImGui::BeginMenu("Options"))
10354             {
10355                 ImGui::PushItemWidth(ImGui::GetFontSize() * 10);
10356 
10357                 ImGui::SeparatorText("Contents");
10358                 ImGui::Checkbox("Show Type Overlay", &ShowTypeOverlay);
10359                 ImGui::Checkbox("Allow Sorting", &AllowSorting);
10360 
10361                 ImGui::SeparatorText("Selection Behavior");
10362                 ImGui::Checkbox("Allow dragging unselected item", &AllowDragUnselected);
10363                 ImGui::Checkbox("Allow box\-selection", &AllowBoxSelect);
10364 
10365                 ImGui::SeparatorText("Layout");
10366                 ImGui::SliderFloat("Icon Size", &IconSize, 16\&.0f, 128\&.0f, "%\&.0f");
10367                 ImGui::SameLine(); HelpMarker("Use CTRL+Wheel to zoom");
10368                 ImGui::SliderInt("Icon Spacing", &IconSpacing, 0, 32);
10369                 ImGui::SliderInt("Icon Hit Spacing", &IconHitSpacing, 0, 32);
10370                 ImGui::Checkbox("Stretch Spacing", &StretchSpacing);
10371                 ImGui::PopItemWidth();
10372                 ImGui::EndMenu();
10373             }
10374             ImGui::EndMenuBar();
10375         }
10376 
10377         // Show a table with ONLY one header row to showcase the idea/possibility of using this to provide a sorting UI
10378         if (AllowSorting)
10379         {
10380             ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0, 0));
10381             ImGuiTableFlags table_flags_for_sort_specs = ImGuiTableFlags_Sortable | ImGuiTableFlags_SortMulti | ImGuiTableFlags_SizingFixedFit | ImGuiTableFlags_Borders;
10382             if (ImGui::BeginTable("for_sort_specs_only", 2, table_flags_for_sort_specs, ImVec2(0\&.0f, ImGui::GetFrameHeight())))
10383             {
10384                 ImGui::TableSetupColumn("Index");
10385                 ImGui::TableSetupColumn("Type");
10386                 ImGui::TableHeadersRow();
10387                 if (ImGuiTableSortSpecs* sort_specs = ImGui::TableGetSortSpecs())
10388                     if (sort_specs\->SpecsDirty || RequestSort)
10389                     {
10390                         ExampleAsset::SortWithSortSpecs(sort_specs, Items\&.Data, Items\&.Size);
10391                         sort_specs\->SpecsDirty = RequestSort = false;
10392                     }
10393                 ImGui::EndTable();
10394             }
10395             ImGui::PopStyleVar();
10396         }
10397 
10398         ImGuiIO& io = ImGui::GetIO();
10399         ImGui::SetNextWindowContentSize(ImVec2(0\&.0f, LayoutOuterPadding + LayoutLineCount * (LayoutItemSize\&.x + LayoutItemSpacing)));
10400         if (ImGui::BeginChild("Assets", ImVec2(0\&.0f, \-ImGui::GetTextLineHeightWithSpacing()), ImGuiChildFlags_Border, ImGuiWindowFlags_NoMove))
10401         {
10402             ImDrawList* draw_list = ImGui::GetWindowDrawList();
10403 
10404             const float avail_width = ImGui::GetContentRegionAvail()\&.x;
10405             UpdateLayoutSizes(avail_width);
10406 
10407             // Calculate and store start position\&.
10408             ImVec2 start_pos = ImGui::GetCursorScreenPos();
10409             start_pos = ImVec2(start_pos\&.x + LayoutOuterPadding, start_pos\&.y + LayoutOuterPadding);
10410             ImGui::SetCursorScreenPos(start_pos);
10411 
10412             // Multi\-select
10413             ImGuiMultiSelectFlags ms_flags = ImGuiMultiSelectFlags_ClearOnEscape | ImGuiMultiSelectFlags_ClearOnClickVoid;
10414 
10415             // \- Enable box\-select (in 2D mode, so that changing box\-select rectangle X1/X2 boundaries will affect clipped items)
10416             if (AllowBoxSelect)
10417                 ms_flags |= ImGuiMultiSelectFlags_BoxSelect2d;
10418 
10419             // \- This feature allows dragging an unselected item without selecting it (rarely used)
10420             if (AllowDragUnselected)
10421                 ms_flags |= ImGuiMultiSelectFlags_SelectOnClickRelease;
10422 
10423             // \- Enable keyboard wrapping on X axis
10424             // (FIXME\-MULTISELECT: We haven't designed/exposed a general nav wrapping api yet, so this flag is provided as a courtesy to avoid doing:
10425             //    ImGui::NavMoveRequestTryWrapping(ImGui::GetCurrentWindow(), ImGuiNavMoveFlags_WrapX);
10426             // When we finish implementing a more general API for this, we will obsolete this flag in favor of the new system)
10427             ms_flags |= ImGuiMultiSelectFlags_NavWrapX;
10428 
10429             ImGuiMultiSelectIO* ms_io = ImGui::BeginMultiSelect(ms_flags, Selection\&.Size, Items\&.Size);
10430 
10431             // Use custom selection adapter: store ID in selection (recommended)
10432             Selection\&.UserData = this;
10433             Selection\&.AdapterIndexToStorageId = [](ImGuiSelectionBasicStorage* self_, int idx) { ExampleAssetsBrowser* self = (ExampleAssetsBrowser*)self_\->UserData; return self\->Items[idx]\&.ID; };
10434             Selection\&.ApplyRequests(ms_io);
10435 
10436             const bool want_delete = (ImGui::Shortcut(ImGuiKey_Delete, ImGuiInputFlags_Repeat) && (Selection\&.Size > 0)) || RequestDelete;
10437             const int item_curr_idx_to_focus = want_delete ? Selection\&.ApplyDeletionPreLoop(ms_io, Items\&.Size) : \-1;
10438             RequestDelete = false;
10439 
10440             // Push LayoutSelectableSpacing (which is LayoutItemSpacing minus hit\-spacing, if we decide to have hit gaps between items)
10441             // Altering style ItemSpacing may seem unnecessary as we position every items using SetCursorScreenPos()\&.\&.\&.
10442             // But it is necessary for two reasons:
10443             // \- Selectables uses it by default to visually fill the space between two items\&.
10444             // \- The vertical spacing would be measured by Clipper to calculate line height if we didn't provide it explicitly (here we do)\&.
10445             ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(LayoutSelectableSpacing, LayoutSelectableSpacing));
10446 
10447             // Rendering parameters
10448             const ImU32 icon_type_overlay_colors[3] = { 0, IM_COL32(200, 70, 70, 255), IM_COL32(70, 170, 70, 255) };
10449             const ImU32 icon_bg_color = ImGui::GetColorU32(ImGuiCol_MenuBarBg);
10450             const ImVec2 icon_type_overlay_size = ImVec2(4\&.0f, 4\&.0f);
10451             const bool display_label = (LayoutItemSize\&.x >= ImGui::CalcTextSize("999")\&.x);
10452 
10453             const int column_count = LayoutColumnCount;
10454             ImGuiListClipper clipper;
10455             clipper\&.Begin(LayoutLineCount, LayoutItemStep\&.y);
10456             if (item_curr_idx_to_focus != \-1)
10457                 clipper\&.IncludeItemByIndex(item_curr_idx_to_focus / column_count); // Ensure focused item line is not clipped\&.
10458             if (ms_io\->RangeSrcItem != \-1)
10459                 clipper\&.IncludeItemByIndex((int)ms_io\->RangeSrcItem / column_count); // Ensure RangeSrc item line is not clipped\&.
10460             while (clipper\&.Step())
10461             {
10462                 for (int line_idx = clipper\&.DisplayStart; line_idx < clipper\&.DisplayEnd; line_idx++)
10463                 {
10464                     const int item_min_idx_for_current_line = line_idx * column_count;
10465                     const int item_max_idx_for_current_line = IM_MIN((line_idx + 1) * column_count, Items\&.Size);
10466                     for (int item_idx = item_min_idx_for_current_line; item_idx < item_max_idx_for_current_line; ++item_idx)
10467                     {
10468                         ExampleAsset* item_data = &Items[item_idx];
10469                         ImGui::PushID((int)item_data\->ID);
10470 
10471                         // Position item
10472                         ImVec2 pos = ImVec2(start_pos\&.x + (item_idx % column_count) * LayoutItemStep\&.x, start_pos\&.y + line_idx * LayoutItemStep\&.y);
10473                         ImGui::SetCursorScreenPos(pos);
10474 
10475                         ImGui::SetNextItemSelectionUserData(item_idx);
10476                         bool item_is_selected = Selection\&.Contains((ImGuiID)item_data\->ID);
10477                         bool item_is_visible = ImGui::IsRectVisible(LayoutItemSize);
10478                         ImGui::Selectable("", item_is_selected, ImGuiSelectableFlags_None, LayoutItemSize);
10479 
10480                         // Update our selection state immediately (without waiting for EndMultiSelect() requests)
10481                         // because we use this to alter the color of our text/icon\&.
10482                         if (ImGui::IsItemToggledSelection())
10483                             item_is_selected = !item_is_selected;
10484 
10485                         // Focus (for after deletion)
10486                         if (item_curr_idx_to_focus == item_idx)
10487                             ImGui::SetKeyboardFocusHere(\-1);
10488 
10489                         // Drag and drop
10490                         if (ImGui::BeginDragDropSource())
10491                         {
10492                             // Create payload with full selection OR single unselected item\&.
10493                             // (the later is only possible when using ImGuiMultiSelectFlags_SelectOnClickRelease)
10494                             if (ImGui::GetDragDropPayload() == NULL)
10495                             {
10496                                 ImVector<ImGuiID> payload_items;
10497                                 void* it = NULL;
10498                                 ImGuiID id = 0;
10499                                 if (!item_is_selected)
10500                                     payload_items\&.push_back(item_data\->ID);
10501                                 else
10502                                     while (Selection\&.GetNextSelectedItem(&it, &id))
10503                                         payload_items\&.push_back(id);
10504                                 ImGui::SetDragDropPayload("ASSETS_BROWSER_ITEMS", payload_items\&.Data, (size_t)payload_items\&.size_in_bytes());
10505                             }
10506 
10507                             // Display payload content in tooltip, by extracting it from the payload data
10508                             // (we could read from selection, but it is more correct and reusable to read from payload)
10509                             const ImGuiPayload* payload = ImGui::GetDragDropPayload();
10510                             const int payload_count = (int)payload\->DataSize / (int)sizeof(ImGuiID);
10511                             ImGui::Text("%d assets", payload_count);
10512 
10513                             ImGui::EndDragDropSource();
10514                         }
10515 
10516                         // Render icon (a real app would likely display an image/thumbnail here)
10517                         // Because we use ImGuiMultiSelectFlags_BoxSelect2d, clipping vertical may occasionally be larger, so we coarse\-clip our rendering as well\&.
10518                         if (item_is_visible)
10519                         {
10520                             ImVec2 box_min(pos\&.x \- 1, pos\&.y \- 1);
10521                             ImVec2 box_max(box_min\&.x + LayoutItemSize\&.x + 2, box_min\&.y + LayoutItemSize\&.y + 2); // Dubious
10522                             draw_list\->AddRectFilled(box_min, box_max, icon_bg_color); // Background color
10523                             if (ShowTypeOverlay && item_data\->Type != 0)
10524                             {
10525                                 ImU32 type_col = icon_type_overlay_colors[item_data\->Type % IM_ARRAYSIZE(icon_type_overlay_colors)];
10526                                 draw_list\->AddRectFilled(ImVec2(box_max\&.x \- 2 \- icon_type_overlay_size\&.x, box_min\&.y + 2), ImVec2(box_max\&.x \- 2, box_min\&.y + 2 + icon_type_overlay_size\&.y), type_col);
10527                             }
10528                             if (display_label)
10529                             {
10530                                 ImU32 label_col = ImGui::GetColorU32(item_is_selected ? ImGuiCol_Text : ImGuiCol_TextDisabled);
10531                                 char label[32];
10532                                 sprintf(label, "%d", item_data\->ID);
10533                                 draw_list\->AddText(ImVec2(box_min\&.x, box_max\&.y \- ImGui::GetFontSize()), label_col, label);
10534                             }
10535                         }
10536 
10537                         ImGui::PopID();
10538                     }
10539                 }
10540             }
10541             clipper\&.End();
10542             ImGui::PopStyleVar(); // ImGuiStyleVar_ItemSpacing
10543 
10544             // Context menu
10545             if (ImGui::BeginPopupContextWindow())
10546             {
10547                 ImGui::Text("Selection: %d items", Selection\&.Size);
10548                 ImGui::Separator();
10549                 if (ImGui::MenuItem("Delete", "Del", false, Selection\&.Size > 0))
10550                     RequestDelete = true;
10551                 ImGui::EndPopup();
10552             }
10553 
10554             ms_io = ImGui::EndMultiSelect();
10555             Selection\&.ApplyRequests(ms_io);
10556             if (want_delete)
10557                 Selection\&.ApplyDeletionPostLoop(ms_io, Items, item_curr_idx_to_focus);
10558 
10559             // Zooming with CTRL+Wheel
10560             if (ImGui::IsWindowAppearing())
10561                 ZoomWheelAccum = 0\&.0f;
10562             if (ImGui::IsWindowHovered() && io\&.MouseWheel != 0\&.0f && ImGui::IsKeyDown(ImGuiMod_Ctrl) && ImGui::IsAnyItemActive() == false)
10563             {
10564                 ZoomWheelAccum += io\&.MouseWheel;
10565                 if (fabsf(ZoomWheelAccum) >= 1\&.0f)
10566                 {
10567                     // Calculate hovered item index from mouse location
10568                     // FIXME: Locking aiming on 'hovered_item_idx' (with a cool\-down timer) would ensure zoom keeps on it\&.
10569                     const float hovered_item_nx = (io\&.MousePos\&.x \- start_pos\&.x + LayoutItemSpacing * 0\&.5f) / LayoutItemStep\&.x;
10570                     const float hovered_item_ny = (io\&.MousePos\&.y \- start_pos\&.y + LayoutItemSpacing * 0\&.5f) / LayoutItemStep\&.y;
10571                     const int hovered_item_idx = ((int)hovered_item_ny * LayoutColumnCount) + (int)hovered_item_nx;
10572                     //ImGui::SetTooltip("%f,%f \-> item %d", hovered_item_nx, hovered_item_ny, hovered_item_idx); // Move those 4 lines in block above for easy debugging
10573 
10574                     // Zoom
10575                     IconSize *= powf(1\&.1f, (float)(int)ZoomWheelAccum);
10576                     IconSize = IM_CLAMP(IconSize, 16\&.0f, 128\&.0f);
10577                     ZoomWheelAccum \-= (int)ZoomWheelAccum;
10578                     UpdateLayoutSizes(avail_width);
10579 
10580                     // Manipulate scroll to that we will land at the same Y location of currently hovered item\&.
10581                     // \- Calculate next frame position of item under mouse
10582                     // \- Set new scroll position to be used in next ImGui::BeginChild() call\&.
10583                     float hovered_item_rel_pos_y = ((float)(hovered_item_idx / LayoutColumnCount) + fmodf(hovered_item_ny, 1\&.0f)) * LayoutItemStep\&.y;
10584                     hovered_item_rel_pos_y += ImGui::GetStyle()\&.WindowPadding\&.y;
10585                     float mouse_local_y = io\&.MousePos\&.y \- ImGui::GetWindowPos()\&.y;
10586                     ImGui::SetScrollY(hovered_item_rel_pos_y \- mouse_local_y);
10587                 }
10588             }
10589         }
10590         ImGui::EndChild();
10591 
10592         ImGui::Text("Selected: %d/%d items", Selection\&.Size, Items\&.Size);
10593         ImGui::End();
10594     }
.PP
.fi

.PP
References \fBAddItems()\fP, \fBAllowBoxSelect\fP, \fBAllowDragUnselected\fP, \fBAllowSorting\fP, \fBExampleSelectionWithDeletion::ApplyDeletionPostLoop()\fP, \fBExampleSelectionWithDeletion::ApplyDeletionPreLoop()\fP, \fBClearItems()\fP, \fBIconHitSpacing\fP, \fBIconSize\fP, \fBIconSpacing\fP, \fBExampleAsset::ID\fP, \fBIM_CLAMP\fP, \fBIM_MIN\fP, \fBItems\fP, \fBLayoutColumnCount\fP, \fBLayoutItemSize\fP, \fBLayoutItemSpacing\fP, \fBLayoutItemStep\fP, \fBLayoutLineCount\fP, \fBLayoutOuterPadding\fP, \fBLayoutSelectableSpacing\fP, \fBRequestDelete\fP, \fBRequestSort\fP, \fBSelection\fP, \fBShowTypeOverlay\fP, \fBExampleAsset::SortWithSortSpecs()\fP, \fBStretchSpacing\fP, \fBExampleAsset::Type\fP, \fBUpdateLayoutSizes()\fP, and \fBZoomWheelAccum\fP\&.
.SS "void ExampleAssetsBrowser::UpdateLayoutSizes (float avail_width)\fR [inline]\fP"

.PP
Definition at line \fB10303\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
10304     {
10305         // Layout: when not stretching: allow extending into right\-most spacing\&.
10306         LayoutItemSpacing = (float)IconSpacing;
10307         if (StretchSpacing == false)
10308             avail_width += floorf(LayoutItemSpacing * 0\&.5f);
10309 
10310         // Layout: calculate number of icon per line and number of lines
10311         LayoutItemSize = ImVec2(floorf(IconSize), floorf(IconSize));
10312         LayoutColumnCount = IM_MAX((int)(avail_width / (LayoutItemSize\&.x + LayoutItemSpacing)), 1);
10313         LayoutLineCount = (Items\&.Size + LayoutColumnCount \- 1) / LayoutColumnCount;
10314 
10315         // Layout: when stretching: allocate remaining space to more spacing\&. Round before division, so item_spacing may be non\-integer\&.
10316         if (StretchSpacing && LayoutColumnCount > 1)
10317             LayoutItemSpacing = floorf(avail_width \- LayoutItemSize\&.x * LayoutColumnCount) / LayoutColumnCount;
10318 
10319         LayoutItemStep = ImVec2(LayoutItemSize\&.x + LayoutItemSpacing, LayoutItemSize\&.y + LayoutItemSpacing);
10320         LayoutSelectableSpacing = IM_MAX(floorf(LayoutItemSpacing) \- IconHitSpacing, 0\&.0f);
10321         LayoutOuterPadding = floorf(LayoutItemSpacing * 0\&.5f);
10322     }
.PP
.fi

.PP
References \fBIconHitSpacing\fP, \fBIconSize\fP, \fBIconSpacing\fP, \fBIM_MAX\fP, \fBItems\fP, \fBLayoutColumnCount\fP, \fBLayoutItemSize\fP, \fBLayoutItemSpacing\fP, \fBLayoutItemStep\fP, \fBLayoutLineCount\fP, \fBLayoutOuterPadding\fP, \fBLayoutSelectableSpacing\fP, and \fBStretchSpacing\fP\&.
.PP
Referenced by \fBDraw()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool ExampleAssetsBrowser::AllowBoxSelect = true"

.PP
Definition at line \fB10258\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP\&.
.SS "bool ExampleAssetsBrowser::AllowDragUnselected = false"

.PP
Definition at line \fB10257\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP\&.
.SS "bool ExampleAssetsBrowser::AllowSorting = true"

.PP
Definition at line \fB10256\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP\&.
.SS "int ExampleAssetsBrowser::IconHitSpacing = 4"

.PP
Definition at line \fB10261\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP, and \fBUpdateLayoutSizes()\fP\&.
.SS "float ExampleAssetsBrowser::IconSize = 32\&.0f"

.PP
Definition at line \fB10259\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP, and \fBUpdateLayoutSizes()\fP\&.
.SS "int ExampleAssetsBrowser::IconSpacing = 10"

.PP
Definition at line \fB10260\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP, and \fBUpdateLayoutSizes()\fP\&.
.SS "ImVector<\fBExampleAsset\fP> ExampleAssetsBrowser::Items"

.PP
Definition at line \fB10265\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBAddItems()\fP, \fBClearItems()\fP, \fBDraw()\fP, and \fBUpdateLayoutSizes()\fP\&.
.SS "int ExampleAssetsBrowser::LayoutColumnCount = 0"

.PP
Definition at line \fB10278\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP, and \fBUpdateLayoutSizes()\fP\&.
.SS "ImVec2 ExampleAssetsBrowser::LayoutItemSize"

.PP
Definition at line \fB10273\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP, and \fBUpdateLayoutSizes()\fP\&.
.SS "float ExampleAssetsBrowser::LayoutItemSpacing = 0\&.0f"

.PP
Definition at line \fB10275\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP, and \fBUpdateLayoutSizes()\fP\&.
.SS "ImVec2 ExampleAssetsBrowser::LayoutItemStep"

.PP
Definition at line \fB10274\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP, and \fBUpdateLayoutSizes()\fP\&.
.SS "int ExampleAssetsBrowser::LayoutLineCount = 0"

.PP
Definition at line \fB10279\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP, and \fBUpdateLayoutSizes()\fP\&.
.SS "float ExampleAssetsBrowser::LayoutOuterPadding = 0\&.0f"

.PP
Definition at line \fB10277\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP, and \fBUpdateLayoutSizes()\fP\&.
.SS "float ExampleAssetsBrowser::LayoutSelectableSpacing = 0\&.0f"

.PP
Definition at line \fB10276\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP, and \fBUpdateLayoutSizes()\fP\&.
.SS "ImGuiID ExampleAssetsBrowser::NextItemId = 0"

.PP
Definition at line \fB10267\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBAddItems()\fP\&.
.SS "bool ExampleAssetsBrowser::RequestDelete = false"

.PP
Definition at line \fB10268\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP\&.
.SS "bool ExampleAssetsBrowser::RequestSort = false"

.PP
Definition at line \fB10269\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBAddItems()\fP, and \fBDraw()\fP\&.
.SS "\fBExampleSelectionWithDeletion\fP ExampleAssetsBrowser::Selection"

.PP
Definition at line \fB10266\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBClearItems()\fP, and \fBDraw()\fP\&.
.SS "bool ExampleAssetsBrowser::ShowTypeOverlay = true"

.PP
Definition at line \fB10255\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP\&.
.SS "bool ExampleAssetsBrowser::StretchSpacing = true"

.PP
Definition at line \fB10262\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP, and \fBUpdateLayoutSizes()\fP\&.
.SS "float ExampleAssetsBrowser::ZoomWheelAccum = 0\&.0f"

.PP
Definition at line \fB10270\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
