.TH "ExampleAppLog" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleAppLog
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExampleAppLog\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBAddLog\fP (const char *fmt,\&.\&.\&.) IM_FMTARGS(2)"
.br
.ti -1c
.RI "void \fBDraw\fP (const char *title, bool *p_open=NULL)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiTextBuffer \fBBuf\fP"
.br
.ti -1c
.RI "ImGuiTextFilter \fBFilter\fP"
.br
.ti -1c
.RI "ImVector< int > \fBLineOffsets\fP"
.br
.ti -1c
.RI "bool \fBAutoScroll\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8696\fP of file \fBimgui_demo\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExampleAppLog::ExampleAppLog ()\fR [inline]\fP"

.PP
Definition at line \fB8703\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
8704     {
8705         AutoScroll = true;
8706         Clear();
8707     }
.PP
.fi

.PP
References \fBAutoScroll\fP, and \fBClear()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ExampleAppLog::AddLog (const char * fmt,  \&.\&.\&.)\fR [inline]\fP"

.PP
Definition at line \fB8716\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
8717     {
8718         int old_size = Buf\&.size();
8719         va_list args;
8720         va_start(args, fmt);
8721         Buf\&.appendfv(fmt, args);
8722         va_end(args);
8723         for (int new_size = Buf\&.size(); old_size < new_size; old_size++)
8724             if (Buf[old_size] == '\\n')
8725                 LineOffsets\&.push_back(old_size + 1);
8726     }
.PP
.fi

.PP
References \fBBuf\fP, and \fBLineOffsets\fP\&.
.SS "void ExampleAppLog::Clear ()\fR [inline]\fP"

.PP
Definition at line \fB8709\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
8710     {
8711         Buf\&.clear();
8712         LineOffsets\&.clear();
8713         LineOffsets\&.push_back(0);
8714     }
.PP
.fi

.PP
References \fBBuf\fP, and \fBLineOffsets\fP\&.
.PP
Referenced by \fBDraw()\fP, and \fBExampleAppLog()\fP\&.
.SS "void ExampleAppLog::Draw (const char * title, bool * p_open = \fRNULL\fP)\fR [inline]\fP"

.PP
Definition at line \fB8728\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
8729     {
8730         if (!ImGui::Begin(title, p_open))
8731         {
8732             ImGui::End();
8733             return;
8734         }
8735 
8736         // Options menu
8737         if (ImGui::BeginPopup("Options"))
8738         {
8739             ImGui::Checkbox("Auto\-scroll", &AutoScroll);
8740             ImGui::EndPopup();
8741         }
8742 
8743         // Main window
8744         if (ImGui::Button("Options"))
8745             ImGui::OpenPopup("Options");
8746         ImGui::SameLine();
8747         bool clear = ImGui::Button("Clear");
8748         ImGui::SameLine();
8749         bool copy = ImGui::Button("Copy");
8750         ImGui::SameLine();
8751         Filter\&.Draw("Filter", \-100\&.0f);
8752 
8753         ImGui::Separator();
8754 
8755         if (ImGui::BeginChild("scrolling", ImVec2(0, 0), ImGuiChildFlags_None, ImGuiWindowFlags_HorizontalScrollbar))
8756         {
8757             if (clear)
8758                 Clear();
8759             if (copy)
8760                 ImGui::LogToClipboard();
8761 
8762             ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0, 0));
8763             const char* buf = Buf\&.begin();
8764             const char* buf_end = Buf\&.end();
8765             if (Filter\&.IsActive())
8766             {
8767                 // In this example we don't use the clipper when Filter is enabled\&.
8768                 // This is because we don't have random access to the result of our filter\&.
8769                 // A real application processing logs with ten of thousands of entries may want to store the result of
8770                 // search/filter\&.\&. especially if the filtering function is not trivial (e\&.g\&. reg\-exp)\&.
8771                 for (int line_no = 0; line_no < LineOffsets\&.Size; line_no++)
8772                 {
8773                     const char* line_start = buf + LineOffsets[line_no];
8774                     const char* line_end = (line_no + 1 < LineOffsets\&.Size) ? (buf + LineOffsets[line_no + 1] \- 1) : buf_end;
8775                     if (Filter\&.PassFilter(line_start, line_end))
8776                         ImGui::TextUnformatted(line_start, line_end);
8777                 }
8778             }
8779             else
8780             {
8781                 // The simplest and easy way to display the entire buffer:
8782                 //   ImGui::TextUnformatted(buf_begin, buf_end);
8783                 // And it'll just work\&. TextUnformatted() has specialization for large blob of text and will fast\-forward
8784                 // to skip non\-visible lines\&. Here we instead demonstrate using the clipper to only process lines that are
8785                 // within the visible area\&.
8786                 // If you have tens of thousands of items and their processing cost is non\-negligible, coarse clipping them
8787                 // on your side is recommended\&. Using ImGuiListClipper requires
8788                 // \- A) random access into your data
8789                 // \- B) items all being the  same height,
8790                 // both of which we can handle since we have an array pointing to the beginning of each line of text\&.
8791                 // When using the filter (in the block of code above) we don't have random access into the data to display
8792                 // anymore, which is why we don't use the clipper\&. Storing or skimming through the search result would make
8793                 // it possible (and would be recommended if you want to search through tens of thousands of entries)\&.
8794                 ImGuiListClipper clipper;
8795                 clipper\&.Begin(LineOffsets\&.Size);
8796                 while (clipper\&.Step())
8797                 {
8798                     for (int line_no = clipper\&.DisplayStart; line_no < clipper\&.DisplayEnd; line_no++)
8799                     {
8800                         const char* line_start = buf + LineOffsets[line_no];
8801                         const char* line_end = (line_no + 1 < LineOffsets\&.Size) ? (buf + LineOffsets[line_no + 1] \- 1) : buf_end;
8802                         ImGui::TextUnformatted(line_start, line_end);
8803                     }
8804                 }
8805                 clipper\&.End();
8806             }
8807             ImGui::PopStyleVar();
8808 
8809             // Keep up at the bottom of the scroll region if we were already at the bottom at the beginning of the frame\&.
8810             // Using a scrollbar or mouse\-wheel will take away from the bottom edge\&.
8811             if (AutoScroll && ImGui::GetScrollY() >= ImGui::GetScrollMaxY())
8812                 ImGui::SetScrollHereY(1\&.0f);
8813         }
8814         ImGui::EndChild();
8815         ImGui::End();
8816     }
.PP
.fi

.PP
References \fBAutoScroll\fP, \fBBuf\fP, \fBClear()\fP, \fBFilter\fP, and \fBLineOffsets\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool ExampleAppLog::AutoScroll"

.PP
Definition at line \fB8701\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP, and \fBExampleAppLog()\fP\&.
.SS "ImGuiTextBuffer ExampleAppLog::Buf"

.PP
Definition at line \fB8698\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBAddLog()\fP, \fBClear()\fP, and \fBDraw()\fP\&.
.SS "ImGuiTextFilter ExampleAppLog::Filter"

.PP
Definition at line \fB8699\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBDraw()\fP\&.
.SS "ImVector<int> ExampleAppLog::LineOffsets"

.PP
Definition at line \fB8700\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBAddLog()\fP, \fBClear()\fP, and \fBDraw()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
