.TH "ExampleAsset" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleAsset
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExampleAsset\fP (ImGuiID id, int type)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSortWithSortSpecs\fP (ImGuiTableSortSpecs *sort_specs, \fBExampleAsset\fP *items, int items_count)"
.br
.ti -1c
.RI "static int \fBIMGUI_CDECL\fP \fBCompareWithSortSpecs\fP (const void *lhs, const void *rhs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "int \fBType\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const ImGuiTableSortSpecs * \fBs_current_sort_specs\fP = NULL"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10212\fP of file \fBimgui_demo\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExampleAsset::ExampleAsset (ImGuiID id, int type)\fR [inline]\fP"

.PP
Definition at line \fB10217\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
10217 { ID = id; Type = type; }
.PP
.fi

.PP
References \fBID\fP, and \fBType\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static int \fBIMGUI_CDECL\fP ExampleAsset::CompareWithSortSpecs (const void * lhs, const void * rhs)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB10230\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
10231     {
10232         const ExampleAsset* a = (const ExampleAsset*)lhs;
10233         const ExampleAsset* b = (const ExampleAsset*)rhs;
10234         for (int n = 0; n < s_current_sort_specs\->SpecsCount; n++)
10235         {
10236             const ImGuiTableColumnSortSpecs* sort_spec = &s_current_sort_specs\->Specs[n];
10237             int delta = 0;
10238             if (sort_spec\->ColumnIndex == 0)
10239                 delta = ((int)a\->ID \- (int)b\->ID);
10240             else if (sort_spec\->ColumnIndex == 1)
10241                 delta = (a\->Type \- b\->Type);
10242             if (delta > 0)
10243                 return (sort_spec\->SortDirection == ImGuiSortDirection_Ascending) ? +1 : \-1;
10244             if (delta < 0)
10245                 return (sort_spec\->SortDirection == ImGuiSortDirection_Ascending) ? \-1 : +1;
10246         }
10247         return ((int)a\->ID \- (int)b\->ID);
10248     }
.PP
.fi

.PP
References \fBID\fP, \fBs_current_sort_specs\fP, and \fBType\fP\&.
.PP
Referenced by \fBSortWithSortSpecs()\fP\&.
.SS "static void ExampleAsset::SortWithSortSpecs (ImGuiTableSortSpecs * sort_specs, \fBExampleAsset\fP * items, int items_count)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB10221\fP of file \fBimgui_demo\&.cpp\fP\&.
.nf
10222     {
10223         s_current_sort_specs = sort_specs; // Store in variable accessible by the sort function\&.
10224         if (items_count > 1)
10225             qsort(items, (size_t)items_count, sizeof(items[0]), ExampleAsset::CompareWithSortSpecs);
10226         s_current_sort_specs = NULL;
10227     }
.PP
.fi

.PP
References \fBCompareWithSortSpecs()\fP, and \fBs_current_sort_specs\fP\&.
.PP
Referenced by \fBExampleAssetsBrowser::Draw()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "ImGuiID ExampleAsset::ID"

.PP
Definition at line \fB10214\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBCompareWithSortSpecs()\fP, \fBExampleAssetsBrowser::Draw()\fP, and \fBExampleAsset()\fP\&.
.SS "const ImGuiTableSortSpecs * ExampleAsset::s_current_sort_specs = NULL\fR [static]\fP"

.PP
Definition at line \fB10219\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBCompareWithSortSpecs()\fP, and \fBSortWithSortSpecs()\fP\&.
.SS "int ExampleAsset::Type"

.PP
Definition at line \fB10215\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBCompareWithSortSpecs()\fP, \fBExampleAssetsBrowser::Draw()\fP, and \fBExampleAsset()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
