.TH "ext_quaternion_geometric" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_quaternion_geometric \- GLM_EXT_quaternion_geometric
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::length\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &q)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > \fBglm::normalize\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &q)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBT\fP \fBglm::dot\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBqua\fP< \fBT\fP, \fBQ\fP > \fBglm::cross\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &q1, \fBqua\fP< \fBT\fP, \fBQ\fP > const &q2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides geometric functions for quaternion types
.PP
Include <\fBglm/ext/quaternion_geometric\&.hpp\fP> to use the features of this extension\&.
.PP
\fBSee also\fP
.RS 4
\fBGeometric functions\fP 
.PP
\fBGLM_EXT_quaternion_float\fP 
.PP
\fBGLM_EXT_quaternion_double\fP
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBqua\fP< \fBT\fP, \fBQ\fP > glm::cross (\fBqua\fP< \fBT\fP, \fBQ\fP > const & q1, \fBqua\fP< \fBT\fP, \fBQ\fP > const & q2)"
Compute a cross product\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_quaternion_geometric\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBT\fP glm::dot (\fBqua\fP< \fBT\fP, \fBQ\fP > const & x, \fBqua\fP< \fBT\fP, \fBQ\fP > const & y)"
Returns dot product of q1 and q2, i\&.e\&., q1[0] * q2[0] + q1[1] * q2[1] + \&.\&.\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types\&. 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_quaternion_geometric\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::length (\fBqua\fP< \fBT\fP, \fBQ\fP > const & q)"
Returns the norm of a quaternions
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_quaternion_geometric\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > glm::normalize (\fBqua\fP< \fBT\fP, \fBQ\fP > const & q)"
Returns the normalized quaternion\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_quaternion_geometric\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
