.TH "ext_matrix_clip_space" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_matrix_clip_space \- GLM_EXT_matrix_clip_space
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::ortho\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::orthoLH_ZO\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::orthoLH_NO\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::orthoRH_ZO\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::orthoRH_NO\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::orthoZO\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::orthoNO\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::orthoLH\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::orthoRH\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::ortho\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::frustumLH_ZO\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::frustumLH_NO\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::frustumRH_ZO\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::frustumRH_NO\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::frustumZO\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::frustumNO\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::frustumLH\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::frustumRH\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::frustum\fP (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveRH_ZO\fP (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveRH_NO\fP (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveLH_ZO\fP (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveLH_NO\fP (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveZO\fP (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveNO\fP (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveRH\fP (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveLH\fP (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspective\fP (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveFovRH_ZO\fP (\fBT\fP fov, \fBT\fP \fBwidth\fP, \fBT\fP \fBheight\fP, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveFovRH_NO\fP (\fBT\fP fov, \fBT\fP \fBwidth\fP, \fBT\fP \fBheight\fP, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveFovLH_ZO\fP (\fBT\fP fov, \fBT\fP \fBwidth\fP, \fBT\fP \fBheight\fP, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveFovLH_NO\fP (\fBT\fP fov, \fBT\fP \fBwidth\fP, \fBT\fP \fBheight\fP, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveFovZO\fP (\fBT\fP fov, \fBT\fP \fBwidth\fP, \fBT\fP \fBheight\fP, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveFovNO\fP (\fBT\fP fov, \fBT\fP \fBwidth\fP, \fBT\fP \fBheight\fP, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveFovRH\fP (\fBT\fP fov, \fBT\fP \fBwidth\fP, \fBT\fP \fBheight\fP, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveFovLH\fP (\fBT\fP fov, \fBT\fP \fBwidth\fP, \fBT\fP \fBheight\fP, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::perspectiveFov\fP (\fBT\fP fov, \fBT\fP \fBwidth\fP, \fBT\fP \fBheight\fP, \fBT\fP near, \fBT\fP far)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::infinitePerspectiveLH\fP (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::infinitePerspectiveRH\fP (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::infinitePerspective\fP (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::tweakedInfinitePerspective\fP (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::tweakedInfinitePerspective\fP (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP ep)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines functions that generate clip space transformation matrices\&.
.PP
The matrices generated by this extension use standard OpenGL fixed-function conventions\&. For example, the lookAt function generates a transform from world space into the specific eye space that the projective matrix functions (perspective, ortho, etc) are designed to expect\&. The OpenGL compatibility specifications defines the particular layout of this eye space\&.
.PP
Include <\fBglm/ext/matrix_clip_space\&.hpp\fP> to use the features of this extension\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_matrix_transform\fP 
.PP
\fBGLM_EXT_matrix_projection\fP
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::frustum (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
Creates a frustum matrix with default handedness, using the default handedness and default near and far clip planes definition\&. To change default handedness use GLM_FORCE_LEFT_HANDED\&. To change default near and far clip planes definition use GLM_FORCE_DEPTH_ZERO_TO_ONE\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP
\fBSee also\fP
.RS 4
\fRglFrustum man page\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::frustumLH (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
Creates a left-handed frustum matrix\&. If GLM_FORCE_DEPTH_ZERO_TO_ONE is defined, the near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition) Otherwise, the near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::frustumLH_NO (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
Creates a left-handed frustum matrix\&. The near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::frustumLH_ZO (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
Creates a left-handed frustum matrix\&. The near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::frustumNO (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
Creates a frustum matrix using left-handed coordinates if GLM_FORCE_LEFT_HANDED if defined or right-handed coordinates otherwise\&. The near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::frustumRH (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
Creates a right-handed frustum matrix\&. If GLM_FORCE_DEPTH_ZERO_TO_ONE is defined, the near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition) Otherwise, the near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::frustumRH_NO (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
Creates a right-handed frustum matrix\&. The near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::frustumRH_ZO (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
Creates a right-handed frustum matrix\&. The near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::frustumZO (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP near, \fBT\fP far)"
Creates a frustum matrix using left-handed coordinates if GLM_FORCE_LEFT_HANDED if defined or right-handed coordinates otherwise\&. The near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::infinitePerspective (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near)"
Creates a matrix for a symmetric perspective-view frustum with far plane at infinite with default handedness\&.
.PP
\fBParameters\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::infinitePerspectiveLH (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near)"
Creates a matrix for a left-handed, symmetric perspective-view frustum with far plane at infinite\&.
.PP
\fBParameters\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::infinitePerspectiveRH (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near)"
Creates a matrix for a right-handed, symmetric perspective-view frustum with far plane at infinite\&.
.PP
\fBParameters\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::ortho (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top)"
Creates a matrix for projecting two-dimensional coordinates onto the screen\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type
.RE
.PP
\fBSee also\fP
.RS 4
- glm::ortho(T const& left, T const& right, T const& bottom, T const& top, T const& zNear, T const& zFar) 
.PP
\fRgluOrtho2D man page\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::ortho (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
Creates a matrix for an orthographic parallel viewing volume, using the default handedness and default near and far clip planes definition\&. To change default handedness use GLM_FORCE_LEFT_HANDED\&. To change default near and far clip planes definition use GLM_FORCE_DEPTH_ZERO_TO_ONE\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type
.RE
.PP
\fBSee also\fP
.RS 4
- glm::ortho(T const& left, T const& right, T const& bottom, T const& top) 
.PP
\fRglOrtho man page\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::orthoLH (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
Creates a matrix for an orthographic parallel viewing volume, using left-handed coordinates\&. If GLM_FORCE_DEPTH_ZERO_TO_ONE is defined, the near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition) Otherwise, the near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type
.RE
.PP
\fBSee also\fP
.RS 4
- glm::ortho(T const& left, T const& right, T const& bottom, T const& top) 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::orthoLH_NO (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
Creates a matrix for an orthographic parallel viewing volume using left-handed coordinates\&. The near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type
.RE
.PP
\fBSee also\fP
.RS 4
- glm::ortho(T const& left, T const& right, T const& bottom, T const& top) 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::orthoLH_ZO (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
Creates a matrix for an orthographic parallel viewing volume, using left-handed coordinates\&. The near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type
.RE
.PP
\fBSee also\fP
.RS 4
- glm::ortho(T const& left, T const& right, T const& bottom, T const& top) 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::orthoNO (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
Creates a matrix for an orthographic parallel viewing volume, using left-handed coordinates if GLM_FORCE_LEFT_HANDED if defined or right-handed coordinates otherwise\&. The near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type
.RE
.PP
\fBSee also\fP
.RS 4
- glm::ortho(T const& left, T const& right, T const& bottom, T const& top) 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::orthoRH (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
Creates a matrix for an orthographic parallel viewing volume, using right-handed coordinates\&. If GLM_FORCE_DEPTH_ZERO_TO_ONE is defined, the near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition) Otherwise, the near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type
.RE
.PP
\fBSee also\fP
.RS 4
- glm::ortho(T const& left, T const& right, T const& bottom, T const& top) 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::orthoRH_NO (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
Creates a matrix for an orthographic parallel viewing volume, using right-handed coordinates\&. The near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type
.RE
.PP
\fBSee also\fP
.RS 4
- glm::ortho(T const& left, T const& right, T const& bottom, T const& top) 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::orthoRH_ZO (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
Creates a matrix for an orthographic parallel viewing volume, using right-handed coordinates\&. The near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type
.RE
.PP
\fBSee also\fP
.RS 4
- glm::ortho(T const& left, T const& right, T const& bottom, T const& top) 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::orthoZO (\fBT\fP left, \fBT\fP right, \fBT\fP bottom, \fBT\fP top, \fBT\fP zNear, \fBT\fP zFar)"
Creates a matrix for an orthographic parallel viewing volume, using left-handed coordinates\&. The near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type
.RE
.PP
\fBSee also\fP
.RS 4
- glm::ortho(T const& left, T const& right, T const& bottom, T const& top) 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspective (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
Creates a matrix for a symmetric perspective-view frustum based on the default handedness and default near and far clip planes definition\&. To change default handedness use GLM_FORCE_LEFT_HANDED\&. To change default near and far clip planes definition use GLM_FORCE_DEPTH_ZERO_TO_ONE\&.
.PP
\fBParameters\fP
.RS 4
\fIfovy\fP Specifies the field of view angle in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP
\fBSee also\fP
.RS 4
\fRgluPerspective man page\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveFov (\fBT\fP fov, \fBT\fP width, \fBT\fP height, \fBT\fP near, \fBT\fP far)"
Builds a perspective projection matrix based on a field of view and the default handedness and default near and far clip planes definition\&. To change default handedness use GLM_FORCE_LEFT_HANDED\&. To change default near and far clip planes definition use GLM_FORCE_DEPTH_ZERO_TO_ONE\&.
.PP
\fBParameters\fP
.RS 4
\fIfov\fP Expressed in radians\&. 
.br
\fIwidth\fP Width of the viewport 
.br
\fIheight\fP Height of the viewport 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveFovLH (\fBT\fP fov, \fBT\fP width, \fBT\fP height, \fBT\fP near, \fBT\fP far)"
Builds a left-handed perspective projection matrix based on a field of view\&. If GLM_FORCE_DEPTH_ZERO_TO_ONE is defined, the near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition) Otherwise, the near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBParameters\fP
.RS 4
\fIfov\fP Expressed in radians\&. 
.br
\fIwidth\fP Width of the viewport 
.br
\fIheight\fP Height of the viewport 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveFovLH_NO (\fBT\fP fov, \fBT\fP width, \fBT\fP height, \fBT\fP near, \fBT\fP far)"
Builds a perspective projection matrix based on a field of view using left-handed coordinates\&. The near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBParameters\fP
.RS 4
\fIfov\fP Expressed in radians\&. 
.br
\fIwidth\fP Width of the viewport 
.br
\fIheight\fP Height of the viewport 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP
todo max(width , Height) / min(width , Height)?
.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveFovLH_ZO (\fBT\fP fov, \fBT\fP width, \fBT\fP height, \fBT\fP near, \fBT\fP far)"
Builds a perspective projection matrix based on a field of view using left-handed coordinates\&. The near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition)
.PP
\fBParameters\fP
.RS 4
\fIfov\fP Expressed in radians\&. 
.br
\fIwidth\fP Width of the viewport 
.br
\fIheight\fP Height of the viewport 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP
todo max(width , Height) / min(width , Height)?
.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveFovNO (\fBT\fP fov, \fBT\fP width, \fBT\fP height, \fBT\fP near, \fBT\fP far)"
Builds a perspective projection matrix based on a field of view using left-handed coordinates if GLM_FORCE_LEFT_HANDED if defined or right-handed coordinates otherwise\&. The near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBParameters\fP
.RS 4
\fIfov\fP Expressed in radians\&. 
.br
\fIwidth\fP Width of the viewport 
.br
\fIheight\fP Height of the viewport 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveFovRH (\fBT\fP fov, \fBT\fP width, \fBT\fP height, \fBT\fP near, \fBT\fP far)"
Builds a right-handed perspective projection matrix based on a field of view\&. If GLM_FORCE_DEPTH_ZERO_TO_ONE is defined, the near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition) Otherwise, the near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBParameters\fP
.RS 4
\fIfov\fP Expressed in radians\&. 
.br
\fIwidth\fP Width of the viewport 
.br
\fIheight\fP Height of the viewport 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveFovRH_NO (\fBT\fP fov, \fBT\fP width, \fBT\fP height, \fBT\fP near, \fBT\fP far)"
Builds a perspective projection matrix based on a field of view using right-handed coordinates\&. The near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBParameters\fP
.RS 4
\fIfov\fP Expressed in radians\&. 
.br
\fIwidth\fP Width of the viewport 
.br
\fIheight\fP Height of the viewport 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP
todo max(width , Height) / min(width , Height)?
.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveFovRH_ZO (\fBT\fP fov, \fBT\fP width, \fBT\fP height, \fBT\fP near, \fBT\fP far)"
Builds a perspective projection matrix based on a field of view using right-handed coordinates\&. The near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition)
.PP
\fBParameters\fP
.RS 4
\fIfov\fP Expressed in radians\&. 
.br
\fIwidth\fP Width of the viewport 
.br
\fIheight\fP Height of the viewport 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP
todo max(width , Height) / min(width , Height)?
.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveFovZO (\fBT\fP fov, \fBT\fP width, \fBT\fP height, \fBT\fP near, \fBT\fP far)"
Builds a perspective projection matrix based on a field of view using left-handed coordinates if GLM_FORCE_LEFT_HANDED if defined or right-handed coordinates otherwise\&. The near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition)
.PP
\fBParameters\fP
.RS 4
\fIfov\fP Expressed in radians\&. 
.br
\fIwidth\fP Width of the viewport 
.br
\fIheight\fP Height of the viewport 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveLH (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
Creates a matrix for a left-handed, symmetric perspective-view frustum\&. If GLM_FORCE_DEPTH_ZERO_TO_ONE is defined, the near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition) Otherwise, the near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBParameters\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveLH_NO (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
Creates a matrix for a left-handed, symmetric perspective-view frustum\&. The near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBParameters\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveLH_ZO (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
Creates a matrix for a left-handed, symmetric perspective-view frustum\&. The near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition)
.PP
\fBParameters\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveNO (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
Creates a matrix for a symmetric perspective-view frustum using left-handed coordinates if GLM_FORCE_LEFT_HANDED if defined or right-handed coordinates otherwise\&. The near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBParameters\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveRH (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
Creates a matrix for a right-handed, symmetric perspective-view frustum\&. If GLM_FORCE_DEPTH_ZERO_TO_ONE is defined, the near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition) Otherwise, the near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBParameters\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveRH_NO (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
Creates a matrix for a right-handed, symmetric perspective-view frustum\&. The near and far clip planes correspond to z normalized device coordinates of -1 and +1 respectively\&. (OpenGL clip volume definition)
.PP
\fBParameters\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveRH_ZO (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
Creates a matrix for a right-handed, symmetric perspective-view frustum\&. The near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition)
.PP
\fBParameters\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::perspectiveZO (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP far)"
Creates a matrix for a symmetric perspective-view frustum using left-handed coordinates if GLM_FORCE_LEFT_HANDED if defined or right-handed coordinates otherwise\&. The near and far clip planes correspond to z normalized device coordinates of 0 and +1 respectively\&. (Direct3D clip volume definition)
.PP
\fBParameters\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::tweakedInfinitePerspective (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near)"
Creates a matrix for a symmetric perspective-view frustum with far plane at infinite for graphics hardware that doesn't support depth clamping\&.
.PP
\fBParameters\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::tweakedInfinitePerspective (\fBT\fP fovy, \fBT\fP aspect, \fBT\fP near, \fBT\fP ep)"
Creates a matrix for a symmetric perspective-view frustum with far plane at infinite for graphics hardware that doesn't support depth clamping\&.
.PP
\fBParameters\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIep\fP Epsilon
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
