.TH "ext_matrix_transform" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_matrix_transform \- GLM_EXT_matrix_transform
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP genType \fBglm::identity\fP ()"
.br
.RI "Builds an identity matrix\&. "
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::translate\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::rotate\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBT\fP \fBangle\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBaxis\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::scale\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::shear\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &p, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &l_x, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &l_y, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &l_z)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::lookAtRH\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &eye, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &center, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &up)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::lookAtLH\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &eye, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &center, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &up)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::lookAt\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &eye, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &center, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &up)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines functions that generate common transformation matrices\&.
.PP
The matrices generated by this extension use standard OpenGL fixed-function conventions\&. For example, the lookAt function generates a transform from world space into the specific eye space that the projective matrix functions (perspective, ortho, etc) are designed to expect\&. The OpenGL compatibility specifications defines the particular layout of this eye space\&.
.PP
Include <\fBglm/ext/matrix_transform\&.hpp\fP> to use the features of this extension\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_matrix_projection\fP 
.PP
\fBGLM_EXT_matrix_clip_space\fP
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP genType glm::identity ()"

.PP
Builds an identity matrix\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::lookAt (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & eye, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & center, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & up)"
Build a look at view matrix based on the default handedness\&.
.PP
\fBParameters\fP
.RS 4
\fIeye\fP Position of the camera 
.br
\fIcenter\fP Position where the camera is looking at 
.br
\fIup\fP Normalized up vector, how the camera is oriented\&. Typically (0, 0, 1)
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.br
\fIQ\fP A value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
- frustum(T const& left, T const& right, T const& bottom, T const& top, T const& nearVal, T const& farVal) frustum(T const& left, T const& right, T const& bottom, T const& top, T const& nearVal, T const& farVal) 
.PP
\fRgluLookAt man page\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::lookAtLH (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & eye, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & center, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & up)"
Build a left handed look at view matrix\&.
.PP
\fBParameters\fP
.RS 4
\fIeye\fP Position of the camera 
.br
\fIcenter\fP Position where the camera is looking at 
.br
\fIup\fP Normalized up vector, how the camera is oriented\&. Typically (0, 0, 1)
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.br
\fIQ\fP A value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
- frustum(T const& left, T const& right, T const& bottom, T const& top, T const& nearVal, T const& farVal) frustum(T const& left, T const& right, T const& bottom, T const& top, T const& nearVal, T const& farVal) 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::lookAtRH (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & eye, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & center, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & up)"
Build a right handed look at view matrix\&.
.PP
\fBParameters\fP
.RS 4
\fIeye\fP Position of the camera 
.br
\fIcenter\fP Position where the camera is looking at 
.br
\fIup\fP Normalized up vector, how the camera is oriented\&. Typically (0, 0, 1)
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.br
\fIQ\fP A value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
- frustum(T const& left, T const& right, T const& bottom, T const& top, T const& nearVal, T const& farVal) frustum(T const& left, T const& right, T const& bottom, T const& top, T const& nearVal, T const& farVal) 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::rotate (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & m, \fBT\fP angle, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & axis)"
Builds a rotation 4 * 4 matrix created from an axis vector and an angle\&.
.PP
\fBParameters\fP
.RS 4
\fIm\fP Input matrix multiplied by this rotation matrix\&. 
.br
\fIangle\fP Rotation angle expressed in radians\&. 
.br
\fIaxis\fP Rotation axis, recommended to be normalized\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.br
\fIQ\fP A value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
- rotate(mat<4, 4, T, Q> const& m, T angle, T x, T y, T z) 
.PP
- \fBrotate(T angle, vec<3, T, Q> const& v)\fP 
.PP
\fRglRotate man page\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::scale (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & m, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v)"
Builds a scale 4 * 4 matrix created from 3 scalars\&.
.PP
\fBParameters\fP
.RS 4
\fIm\fP Input matrix multiplied by this scale matrix\&. 
.br
\fIv\fP Ratio of scaling for each axis\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.br
\fIQ\fP A value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
- scale(mat<4, 4, T, Q> const& m, T x, T y, T z) 
.PP
- \fBscale(vec<3, T, Q> const& v)\fP 
.PP
\fRglScale man page\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::shear (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & m, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & p, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & l_x, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & l_y, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & l_z)"
Builds a scale 4 * 4 matrix created from point referent 3 shearers\&.
.PP
\fBParameters\fP
.RS 4
\fIm\fP Input matrix multiplied by this shear matrix\&. 
.br
\fIp\fP Point of shearing as reference\&. 
.br
\fIl_x\fP Ratio of matrix\&.x projection in YZ plane relative to the y-axis/z-axis\&. 
.br
\fIl_y\fP Ratio of matrix\&.y projection in XZ plane relative to the x-axis/z-axis\&. 
.br
\fIl_z\fP Ratio of matrix\&.z projection in XY plane relative to the x-axis/y-axis\&.
.RE
.PP
as example: [1 , l_xy, l_xz, -(l_xy+l_xz) * p_x] [x] T [x\fR, y\fP, z\fR, w\fP] = [x\fR, y\fP, z\fR, w\fP] * [l_yx, 1 , l_yz, -(l_yx+l_yz) * p_y] [y] [l_zx, l_zy, 1 , -(l_zx+l_zy) * p_z] [z] [0 , 0 , 0 , 1 ] [w]
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point shear type 
.br
\fIQ\fP A value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
- shear(mat<4, 4, T, Q> const& m, T x, T y, T z) 
.PP
- shear(vec<3, T, Q> const& p) 
.PP
- shear(vec<2, T, Q> const& l_x) 
.PP
- shear(vec<2, T, Q> const& l_y) 
.PP
- shear(vec<2, T, Q> const& l_z) 
.PP
no resource\&.\&.\&. 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::translate (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & m, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v)"
Builds a translation 4 * 4 matrix created from a vector of 3 components\&.
.PP
\fBParameters\fP
.RS 4
\fIm\fP Input matrix multiplied by this translation matrix\&. 
.br
\fIv\fP Coordinates of a translation vector\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A floating-point scalar type 
.br
\fIQ\fP A value from qualifier enum
.RE
.PP
.PP
.nf
#include <glm/glm\&.hpp>
#include <glm/gtc/matrix_transform\&.hpp>
\&.\&.\&.
glm::mat4 m = glm::translate(glm::mat4(1\&.0f), glm::vec3(1\&.0f));
// m[0][0] == 1\&.0f, m[0][1] == 0\&.0f, m[0][2] == 0\&.0f, m[0][3] == 0\&.0f
// m[1][0] == 0\&.0f, m[1][1] == 1\&.0f, m[1][2] == 0\&.0f, m[1][3] == 0\&.0f
// m[2][0] == 0\&.0f, m[2][1] == 0\&.0f, m[2][2] == 1\&.0f, m[2][3] == 0\&.0f
// m[3][0] == 1\&.0f, m[3][1] == 1\&.0f, m[3][2] == 1\&.0f, m[3][3] == 1\&.0f
.fi
.PP
.PP
\fBSee also\fP
.RS 4
- translate(mat<4, 4, T, Q> const& m, T x, T y, T z) 
.PP
- \fBtranslate(vec<3, T, Q> const& v)\fP 
.PP
\fRglTranslate man page\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
