.TH "ext_vector_ulp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_vector_ulp \- GLM_EXT_vector_ulp
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::nextFloat\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::nextFloat\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, int ULPs)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::nextFloat\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, int, \fBQ\fP > const &ULPs)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::prevFloat\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::prevFloat\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, int ULPs)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::prevFloat\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, int, \fBQ\fP > const &ULPs)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, int, \fBQ\fP > \fBglm::floatDistance\fP (\fBvec\fP< \fBL\fP, float, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, float, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBint64\fP, \fBQ\fP > \fBglm::floatDistance\fP (\fBvec\fP< \fBL\fP, double, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, double, \fBQ\fP > const &\fBy\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allow the measurement of the accuracy of a function against a reference implementation\&. This extension works on floating-point data and provide results in ULP\&.
.PP
Include <\fBglm/ext/vector_ulp\&.hpp\fP> to use the features of this extension\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_scalar_ulp\fP 
.PP
\fBGLM_EXT_scalar_relational\fP 
.PP
\fBGLM_EXT_vector_relational\fP
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBint64\fP, \fBQ\fP > glm::floatDistance (\fBvec\fP< \fBL\fP, double, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, double, \fBQ\fP > const & y)"
Return the distance in the number of ULP between 2 double-precision floating-point scalars\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_scalar_ulp\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, int, \fBQ\fP > glm::floatDistance (\fBvec\fP< \fBL\fP, float, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, float, \fBQ\fP > const & y)"
Return the distance in the number of ULP between 2 single-precision floating-point scalars\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_scalar_ulp\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::nextFloat (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Return the next ULP \fBvalue(s)\fP after the input \fBvalue(s)\fP\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_scalar_ulp\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::nextFloat (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, int ULPs)"
Return the \fBvalue(s)\fP ULP distance after the input \fBvalue(s)\fP\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_scalar_ulp\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::nextFloat (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, int, \fBQ\fP > const & ULPs)"
Return the \fBvalue(s)\fP ULP distance after the input \fBvalue(s)\fP\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_scalar_ulp\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::prevFloat (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Return the previous ULP \fBvalue(s)\fP before the input \fBvalue(s)\fP\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_scalar_ulp\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::prevFloat (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, int ULPs)"
Return the \fBvalue(s)\fP ULP distance before the input \fBvalue(s)\fP\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_scalar_ulp\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::prevFloat (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, int, \fBQ\fP > const & ULPs)"
Return the \fBvalue(s)\fP ULP distance before the input \fBvalue(s)\fP\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_scalar_ulp\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
