.TH "ext_vector_int1_sized" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_vector_int1_sized \- GLM_EXT_vector_int1_sized
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBint8\fP, \fBdefaultp\fP > \fBglm::i8vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBint16\fP, \fBdefaultp\fP > \fBglm::i16vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBint32\fP, \fBdefaultp\fP > \fBglm::i32vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBint64\fP, \fBdefaultp\fP > \fBglm::i64vec1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exposes sized signed integer vector types\&.
.PP
Include <\fBglm/ext/vector_int1_sized\&.hpp\fP> to use the features of this extension\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_scalar_int_sized\fP 
.PP
\fBGLM_EXT_vector_uint1_sized\fP
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef \fBvec\fP< 1, \fBi16\fP, \fBdefaultp\fP > \fBglm::i16vec1\fP"
16 bit signed integer vector of 1 component type\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_vector_int1_sized\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 1, \fBi32\fP, \fBdefaultp\fP > \fBglm::i32vec1\fP"
32 bit signed integer vector of 1 component type\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_vector_int1_sized\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 1, \fBi64\fP, \fBdefaultp\fP > \fBglm::i64vec1\fP"
64 bit signed integer vector of 1 component type\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_vector_int1_sized\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 1, \fBi8\fP, \fBdefaultp\fP > \fBglm::i8vec1\fP"
8 bit signed integer vector of 1 component type\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_vector_int1_sized\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
