.TH "ext_scalar_ulp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_scalar_ulp \- GLM_EXT_scalar_ulp
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::nextFloat\fP (genType \fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::prevFloat\fP (genType \fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::nextFloat\fP (genType \fBx\fP, int ULPs)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::prevFloat\fP (genType \fBx\fP, int ULPs)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP int \fBglm::floatDistance\fP (float \fBx\fP, float \fBy\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBint64\fP \fBglm::floatDistance\fP (double \fBx\fP, double \fBy\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allow the measurement of the accuracy of a function against a reference implementation\&. This extension works on floating-point data and provide results in ULP\&.
.PP
Include <\fBglm/ext/scalar_ulp\&.hpp\fP> to use the features of this extension\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_vector_ulp\fP 
.PP
\fBGLM_EXT_scalar_relational\fP
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "\fBGLM_FUNC_QUALIFIER\fP \fBint64\fP glm::floatDistance (double x, double y)"
Return the distance in the number of ULP between 2 double-precision floating-point scalars\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_scalar_ulp\fP 
.RE
.PP

.SS "\fBGLM_FUNC_QUALIFIER\fP int glm::floatDistance (float x, float y)"
Return the distance in the number of ULP between 2 single-precision floating-point scalars\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_scalar_ulp\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::nextFloat (genType x)"
Return the next ULP \fBvalue(s)\fP after the input \fBvalue(s)\fP\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP A floating-point scalar type\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_scalar_ulp\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::nextFloat (genType x, int ULPs)"
Return the \fBvalue(s)\fP ULP distance after the input \fBvalue(s)\fP\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP A floating-point scalar type\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_scalar_ulp\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::prevFloat (genType x)"
Return the previous ULP \fBvalue(s)\fP before the input \fBvalue(s)\fP\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP A floating-point scalar type\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_scalar_ulp\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::prevFloat (genType x, int ULPs)"
Return the \fBvalue(s)\fP ULP distance before the input \fBvalue(s)\fP\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP A floating-point scalar type\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_scalar_ulp\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
