.TH "ext_matrix_uint2x4_sized" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_matrix_uint2x4_sized \- GLM_EXT_matrix_uint2x4_sized
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint8\fP, \fBdefaultp\fP > \fBglm::u8mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint16\fP, \fBdefaultp\fP > \fBglm::u16mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint32\fP, \fBdefaultp\fP > \fBglm::u32mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint64\fP, \fBdefaultp\fP > \fBglm::u64mat2x4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/ext/matrix_uint2x4_sized\&.hpp\fP> to use the features of this extension\&.
.PP
Defines a number of matrices with integer types\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBmat\fP< 2, 4, \fBuint16\fP, \fBdefaultp\fP > \fBglm::u16mat2x4\fP"
16 bit unsigned integer 2x4 matrix\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_matrix_uint2x4_sized\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 2, 4, \fBuint32\fP, \fBdefaultp\fP > \fBglm::u32mat2x4\fP"
32 bit unsigned integer 2x4 matrix\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_matrix_uint2x4_sized\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 2, 4, \fBuint64\fP, \fBdefaultp\fP > \fBglm::u64mat2x4\fP"
64 bit unsigned integer 2x4 matrix\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_matrix_uint2x4_sized\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 2, 4, \fBuint8\fP, \fBdefaultp\fP > \fBglm::u8mat2x4\fP"
8 bit unsigned integer 2x4 matrix\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_matrix_uint2x4_sized\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
