.TH "ext_vector_bool1_precision" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_vector_bool1_precision \- GLM_EXT_vector_bool1_precision
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBvec\fP< 1, bool, \fBhighp\fP > \fBglm::highp_bvec1\fP"
.br
.RI "1 component vector of bool values\&. "
.ti -1c
.RI "typedef \fBvec\fP< 1, bool, \fBmediump\fP > \fBglm::mediump_bvec1\fP"
.br
.RI "1 component vector of bool values\&. "
.ti -1c
.RI "typedef \fBvec\fP< 1, bool, \fBlowp\fP > \fBglm::lowp_bvec1\fP"
.br
.RI "1 component vector of bool values\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exposes highp_bvec1, mediump_bvec1 and lowp_bvec1 types\&.
.PP
Include <\fBglm/ext/vector_bool1_precision\&.hpp\fP> to use the features of this extension\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBvec\fP< 1, bool, \fBhighp\fP > \fBglm::highp_bvec1\fP"

.PP
1 component vector of bool values\&. 
.SS "typedef \fBvec\fP< 1, bool, \fBlowp\fP > \fBglm::lowp_bvec1\fP"

.PP
1 component vector of bool values\&. 
.SS "typedef \fBvec\fP< 1, bool, \fBmediump\fP > \fBglm::mediump_bvec1\fP"

.PP
1 component vector of bool values\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
