.TH "ext_matrix_int3x4" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_matrix_int3x4 \- GLM_EXT_matrix_int3x4
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, int, \fBdefaultp\fP > \fBglm::imat3x4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/ext/matrix_int3x4\&.hpp\fP> to use the features of this extension\&.
.PP
Defines a number of matrices with integer types\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBmat\fP< 3, 4, int, \fBdefaultp\fP > \fBglm::imat3x4\fP"
Signed integer 3x4 matrix\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_matrix_int3x4\fP
.RE
.PP
Signed integer 3x4 matrix\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
