.TH "ext_vector_packing" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_vector_packing \- GLM_EXT_vector_packing
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Include <\fBglm/ext/vector_packing\&.hpp\fP> to use the features of this extension\&.
.PP
This extension provides a set of function to convert vectors to packed formats\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
