.TH "ext_scalar_relational" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_scalar_relational \- GLM_EXT_scalar_relational
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP bool \fBglm::equal\fP (genType const &\fBx\fP, genType const &\fBy\fP, genType const &\fBepsilon\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP bool \fBglm::notEqual\fP (genType const &\fBx\fP, genType const &\fBy\fP, genType const &\fBepsilon\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP bool \fBglm::equal\fP (genType const &\fBx\fP, genType const &\fBy\fP, int ULPs)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP bool \fBglm::notEqual\fP (genType const &\fBx\fP, genType const &\fBy\fP, int ULPs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exposes comparison functions for scalar types that take a user defined epsilon values\&.
.PP
Include <\fBglm/ext/scalar_relational\&.hpp\fP> to use the features of this extension\&.
.PP
\fBSee also\fP
.RS 4
core_vector_relational 
.PP
\fBGLM_EXT_vector_relational\fP 
.PP
\fBGLM_EXT_matrix_relational\fP
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP bool glm::equal (genType const & x, genType const & y, genType const & epsilon)"
Returns the component-wise comparison of |x - y| < epsilon\&. True if this expression is satisfied\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP Floating-point or integer scalar types 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP bool glm::equal (genType const & x, genType const & y, int ULPs)"
Returns the component-wise comparison between two scalars in term of ULPs\&. True if this expression is satisfied\&.
.PP
\fBParameters\fP
.RS 4
\fIx\fP First operand\&. 
.br
\fIy\fP Second operand\&. 
.br
\fIULPs\fP Maximum difference in ULPs between the two operators to consider them equal\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP Floating-point or integer scalar types 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP bool glm::notEqual (genType const & x, genType const & y, genType const & epsilon)"
Returns the component-wise comparison of |x - y| >= epsilon\&. True if this expression is not satisfied\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP Floating-point or integer scalar types 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP bool glm::notEqual (genType const & x, genType const & y, int ULPs)"
Returns the component-wise comparison between two scalars in term of ULPs\&. True if this expression is not satisfied\&.
.PP
\fBParameters\fP
.RS 4
\fIx\fP First operand\&. 
.br
\fIy\fP Second operand\&. 
.br
\fIULPs\fP Maximum difference in ULPs between the two operators to consider them not equal\&.
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP Floating-point or integer scalar types 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
