.TH "ext_vector_reciprocal" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_vector_reciprocal \- GLM_EXT_vector_reciprocal
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Include <\fBglm/ext/vector_reciprocal\&.hpp\fP> to use the features of this extension\&.
.PP
Define secant, cosecant and cotangent functions\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
