.TH "ext_matrix_uint3x3_sized" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_matrix_uint3x3_sized \- GLM_EXT_matrix_uint3x3_sized
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint8\fP, \fBdefaultp\fP > \fBglm::u8mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint16\fP, \fBdefaultp\fP > \fBglm::u16mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint32\fP, \fBdefaultp\fP > \fBglm::u32mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint64\fP, \fBdefaultp\fP > \fBglm::u64mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint8\fP, \fBdefaultp\fP > \fBglm::u8mat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint16\fP, \fBdefaultp\fP > \fBglm::u16mat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint32\fP, \fBdefaultp\fP > \fBglm::u32mat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint64\fP, \fBdefaultp\fP > \fBglm::u64mat3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/ext/matrix_uint3x3_sized\&.hpp\fP> to use the features of this extension\&.
.PP
Defines a number of matrices with integer types\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBmat\fP<3, 3, \fBuint16\fP, \fBdefaultp\fP> \fBglm::u16mat3\fP"
16 bit unsigned integer 3x3 matrix\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_matrix_uint3x3_sized\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 3, 3, \fBuint16\fP, \fBdefaultp\fP > \fBglm::u16mat3x3\fP"
16 bit unsigned integer 3x3 matrix\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_matrix_uint3x3_sized\fP 
.RE
.PP

.SS "typedef \fBmat\fP<3, 3, \fBuint32\fP, \fBdefaultp\fP> \fBglm::u32mat3\fP"
32 bit unsigned integer 3x3 matrix\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_matrix_uint3x3_sized\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 3, 3, \fBuint32\fP, \fBdefaultp\fP > \fBglm::u32mat3x3\fP"
32 bit unsigned integer 3x3 matrix\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_matrix_uint3x3_sized\fP 
.RE
.PP

.SS "typedef \fBmat\fP<3, 3, \fBuint64\fP, \fBdefaultp\fP> \fBglm::u64mat3\fP"
64 bit unsigned integer 3x3 matrix\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_matrix_uint3x3_sized\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 3, 3, \fBuint64\fP, \fBdefaultp\fP > \fBglm::u64mat3x3\fP"
64 bit unsigned integer 3x3 matrix\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_matrix_uint3x3_sized\fP 
.RE
.PP

.SS "typedef \fBmat\fP<3, 3, \fBuint8\fP, \fBdefaultp\fP> \fBglm::u8mat3\fP"
8 bit unsigned integer 3x3 matrix\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_matrix_uint3x3_sized\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 3, 3, \fBuint8\fP, \fBdefaultp\fP > \fBglm::u8mat3x3\fP"
8 bit unsigned integer 3x3 matrix\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_matrix_uint3x3_sized\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
