.TH "adhed/glm/gtx/extend.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/extend.inl
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::extend\fP (genType const &Origin, genType const &Source, genType const &Distance)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::extend\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &Origin, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &Source, \fBT\fP const &Distance)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::extend\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &Origin, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &Source, \fBT\fP const &Distance)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::extend\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &Origin, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &Source, \fBT\fP const &Distance)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
