.TH "FaceWithSmoothingGroup" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FaceWithSmoothingGroup
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SmoothingGroups\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFaceWithSmoothingGroup\fP () \fBAI_NO_EXCEPT\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBmIndices\fP [3]"
.br
.ti -1c
.RI "uint32_t \fBiSmoothGroup\fP"
.br
.RI "specifies to which smoothing group the face belongs to "
.in -1c
.SH "Detailed Description"
.PP 
Helper structure representing a face with smoothing groups assigned 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FaceWithSmoothingGroup::FaceWithSmoothingGroup ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "uint32_t FaceWithSmoothingGroup::iSmoothGroup"

.PP
specifies to which smoothing group the face belongs to 
.SS "uint32_t FaceWithSmoothingGroup::mIndices[3]"
Indices\&. \&.3ds is using uint16\&. However, after an unique vertex set has been generated, individual index values might exceed 2^16 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
