.TH "fact" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fact
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pch\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBCreatorFunc\fP = std::function<std::shared_ptr<\fBCORE::Behaviour\fP>()>"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBVEC\fP (std::shared_ptr< \fBCORE::Behaviour\fP >) \fBinst\fP"
.br
.ti -1c
.RI "static \fBVEC\fP (std::any) anys"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static std::map< std::string, \fBCreatorFunc\fP > \fBcreators\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB151\fP of file \fBpch\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBfact::CreatorFunc\fP = std::function<std::shared_ptr<\fBCORE::Behaviour\fP>()>"

.PP
Definition at line \fB156\fP of file \fBpch\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static fact::VEC (std::any )\fR [static]\fP"

.SS "static fact::VEC (std::shared_ptr< \fBCORE::Behaviour\fP > )\fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::map< std::string, \fBCreatorFunc\fP > fact::creators\fR [static]\fP"

.PP
Definition at line \fB159\fP of file \fBpch\&.h\fP\&.
.PP
Referenced by \fBmain()\fP, and \fBRegister< _T >::Register()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
