.TH "factT" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
factT
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <C_BEHAVIOUR\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBCreatorFunc\fP = std::function<std::shared_ptr<\fBCORE::Behaviour\fP>()>"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBVEC\fP (std::any) anys"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static std::shared_ptr< std::map< std::string, \fBCreatorFunc\fP > > \fBcreators\fP"
.br
.ti -1c
.RI "static std::map< std::string, \fBCreatorFunc\fP > \fBcreatorS\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBfactT::CreatorFunc\fP = std::function<std::shared_ptr<\fBCORE::Behaviour\fP>()>"

.SH "Member Function Documentation"
.PP 
.SS "static factT::VEC (std::any )\fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::map< std::string, \fBCreatorFunc\fP > factT::creatorS\fR [static]\fP"

.SS "std::shared_ptr< std::map< std::string, \fBCreatorFunc\fP > > factT::creators\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
