.TH "adhed/glm/gtx/fast_exponential.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/fast_exponential.inl
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::fastPow\fP (genType \fBx\fP, genType \fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::fastPow\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::fastPow\fP (\fBT\fP \fBx\fP, int \fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::fastPow\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, int, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::fastExp\fP (\fBT\fP \fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::fastExp\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::fastLog\fP (genType \fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::fastLog\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::fastExp2\fP (genType \fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::fastExp2\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::fastLog2\fP (genType \fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::fastLog2\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
