.TH "adhed/glm/gtx/fast_trigonometry.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/fast_trigonometry.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./gtc/constants\&.hpp'\fP
.br
\fR#include 'fast_trigonometry\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::wrapAngle\fP (\fBT\fP \fBangle\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::fastSin\fP (\fBT\fP \fBangle\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::fastCos\fP (\fBT\fP \fBangle\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::fastTan\fP (\fBT\fP \fBangle\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::fastAsin\fP (\fBT\fP \fBangle\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::fastAcos\fP (\fBT\fP \fBangle\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::fastAtan\fP (\fBT\fP \fBy\fP, \fBT\fP \fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::fastAtan\fP (\fBT\fP \fBangle\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_fast_trigonometry\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
