.TH "adhed/libbacktrace/filenames.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/libbacktrace/filenames.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGCC_VERSION\fP   (__GNUC__ * 1000 + __GNUC_MINOR__)"
.br
.ti -1c
.RI "#define \fB__attribute__\fP(\fBx\fP)"
.br
.ti -1c
.RI "#define \fBATTRIBUTE_UNUSED\fP   \fB__attribute__\fP ((__unused__))"
.br
.ti -1c
.RI "#define \fBIS_DIR_SEPARATOR\fP(c)   ((c) == '/')"
.br
.ti -1c
.RI "#define \fBIS_ABSOLUTE_PATH\fP(\fBf\fP)   (\fBIS_DIR_SEPARATOR\fP((\fBf\fP)[0]))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __attribute__( \fBx\fP)"

.SS "#define ATTRIBUTE_UNUSED   \fB__attribute__\fP ((__unused__))"

.SS "#define GCC_VERSION   (__GNUC__ * 1000 + __GNUC_MINOR__)"

.SS "#define IS_ABSOLUTE_PATH( \fBf\fP)   (\fBIS_DIR_SEPARATOR\fP((\fBf\fP)[0]))"

.SS "#define IS_DIR_SEPARATOR( c)   ((c) == '/')"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
