.TH "adhed/libbacktrace/fileline.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/libbacktrace/fileline.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include <sys/types\&.h>\fP
.br
\fR#include <sys/stat\&.h>\fP
.br
\fR#include <errno\&.h>\fP
.br
\fR#include <fcntl\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include 'backtrace\&.hpp'\fP
.br
\fR#include 'internal\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBgetexecname\fP()   NULL"
.br
.ti -1c
.RI "#define \fBsysctl_exec_name1\fP(state,  error_callback,  \fBdata\fP)   NULL"
.br
.ti -1c
.RI "#define \fBsysctl_exec_name2\fP(state,  error_callback,  \fBdata\fP)   NULL"
.br
.ti -1c
.RI "#define \fBmacho_get_executable_path\fP(state,  error_callback,  \fBdata\fP)   NULL"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtracy::backtrace_pcinfo\fP (\fBstruct\fP \fBbacktrace_state\fP *state, uintptr_t pc, \fBbacktrace_full_callback\fP callback, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP)"
.br
.ti -1c
.RI "int \fBtracy::backtrace_syminfo\fP (\fBstruct\fP \fBbacktrace_state\fP *state, uintptr_t addr, \fBbacktrace_syminfo_callback\fP callback, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtracy::backtrace_syminfo_to_full_callback\fP (\fBvoid\fP *\fBdata\fP, uintptr_t pc, const char *symname, uintptr_t symval \fBATTRIBUTE_UNUSED\fP, uintptr_t symsize \fBATTRIBUTE_UNUSED\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtracy::backtrace_syminfo_to_full_error_callback\fP (\fBvoid\fP *\fBdata\fP, const char *msg, int errnum)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define getexecname()   NULL"

.SS "#define macho_get_executable_path( state,  error_callback,  \fBdata\fP)   NULL"

.SS "#define sysctl_exec_name1( state,  error_callback,  \fBdata\fP)   NULL"

.SS "#define sysctl_exec_name2( state,  error_callback,  \fBdata\fP)   NULL"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
