.TH "adhed/glm/detail/func_geometric.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/detail/func_geometric.inl
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./exponential\&.hpp'\fP
.br
\fR#include '\&.\&./common\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBglm::detail::compute_length< L, T, Q, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_distance< L, T, Q, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_dot< V, T, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_dot< vec< 1, T, Q >, T, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_dot< vec< 2, T, Q >, T, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_dot< vec< 3, T, Q >, T, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_dot< vec< 4, T, Q >, T, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_cross< T, Q, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_normalize< L, T, Q, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_faceforward< L, T, Q, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_reflect< L, T, Q, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_refract< L, T, Q, Aligned >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.ti -1c
.RI "namespace \fBglm::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::length\fP (genType \fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::length\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::distance\fP (genType const &p0, genType const &p1)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::distance\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &p0, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &p1)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBT\fP \fBglm::dot\fP (\fBT\fP \fBx\fP, \fBT\fP \fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBT\fP \fBglm::dot\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::cross\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::normalize\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::faceforward\fP (genType const &\fBN\fP, genType const &\fBI\fP, genType const &Nref)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::faceforward\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBN\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBI\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &Nref)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::reflect\fP (genType const &\fBI\fP, genType const &\fBN\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::reflect\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBI\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBN\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::refract\fP (genType const &\fBI\fP, genType const &\fBN\fP, genType eta)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::refract\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBI\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBN\fP, \fBT\fP eta)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
