.TH "adhed/glm/detail/func_integer.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/detail/func_integer.inl
.SH SYNOPSIS
.br
.PP
\fR#include '_vectorize\&.hpp'\fP
.br
\fR#include <limits>\fP
.br
\fR#include 'func_integer_simd\&.inl'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBglm::detail::compute_bitfieldReverseStep< L, T, Q, Aligned, EXEC >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_bitfieldReverseStep< L, T, Q, Aligned, true >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_bitfieldBitCountStep< L, T, Q, Aligned, EXEC >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_bitfieldBitCountStep< L, T, Q, Aligned, true >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_findLSB< genIUType, Bits >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_findMSB_step_vec< L, T, Q, EXEC >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_findMSB_step_vec< L, T, Q, false >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_findMSB_vec< L, T, Q, int >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.ti -1c
.RI "namespace \fBglm::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::detail::mask\fP (\fBT\fP Bits)"
.br
.ti -1c
.RI "\fBGLM_FUNC_QUALIFIER\fP \fBuint\fP \fBglm::uaddCarry\fP (\fBuint\fP const &\fBx\fP, \fBuint\fP const &\fBy\fP, \fBuint\fP &Carry)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, \fBuint\fP, \fBQ\fP > \fBglm::uaddCarry\fP (\fBvec\fP< \fBL\fP, \fBuint\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBuint\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBuint\fP, \fBQ\fP > &Carry)"
.br
.ti -1c
.RI "\fBGLM_FUNC_QUALIFIER\fP \fBuint\fP \fBglm::usubBorrow\fP (\fBuint\fP const &\fBx\fP, \fBuint\fP const &\fBy\fP, \fBuint\fP &Borrow)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, \fBuint\fP, \fBQ\fP > \fBglm::usubBorrow\fP (\fBvec\fP< \fBL\fP, \fBuint\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBuint\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBuint\fP, \fBQ\fP > &Borrow)"
.br
.ti -1c
.RI "\fBGLM_FUNC_QUALIFIER\fP \fBvoid\fP \fBglm::umulExtended\fP (\fBuint\fP const &\fBx\fP, \fBuint\fP const &\fBy\fP, \fBuint\fP &msb, \fBuint\fP &lsb)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvoid\fP \fBglm::umulExtended\fP (\fBvec\fP< \fBL\fP, \fBuint\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBuint\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBuint\fP, \fBQ\fP > &msb, \fBvec\fP< \fBL\fP, \fBuint\fP, \fBQ\fP > &lsb)"
.br
.ti -1c
.RI "\fBGLM_FUNC_QUALIFIER\fP \fBvoid\fP \fBglm::imulExtended\fP (int \fBx\fP, int \fBy\fP, int &msb, int &lsb)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvoid\fP \fBglm::imulExtended\fP (\fBvec\fP< \fBL\fP, int, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, int, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, int, \fBQ\fP > &msb, \fBvec\fP< \fBL\fP, int, \fBQ\fP > &lsb)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_QUALIFIER\fP genIUType \fBglm::bitfieldExtract\fP (genIUType \fBValue\fP, int Offset, int Bits)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::bitfieldExtract\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBValue\fP, int Offset, int Bits)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_QUALIFIER\fP genIUType \fBglm::bitfieldInsert\fP (genIUType const &Base, genIUType const &Insert, int Offset, int Bits)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::bitfieldInsert\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &Base, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &Insert, int Offset, int Bits)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_QUALIFIER\fP genIUType \fBglm::bitfieldReverse\fP (genIUType \fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::bitfieldReverse\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_QUALIFIER\fP int \fBglm::bitCount\fP (genIUType \fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, int, \fBQ\fP > \fBglm::bitCount\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_QUALIFIER\fP int \fBglm::findLSB\fP (genIUType \fBValue\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, int, \fBQ\fP > \fBglm::findLSB\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_QUALIFIER\fP int \fBglm::findMSB\fP (genIUType \fBv\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< \fBL\fP, int, \fBQ\fP > \fBglm::findMSB\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
