.TH "adhed/glm/fwd.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/fwd.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'detail/qualifier\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBint8\fP \fBglm::lowp_i8\fP"
.br
.ti -1c
.RI "typedef \fBint8\fP \fBglm::mediump_i8\fP"
.br
.ti -1c
.RI "typedef \fBint8\fP \fBglm::highp_i8\fP"
.br
.ti -1c
.RI "typedef \fBint8\fP \fBglm::i8\fP"
.br
.ti -1c
.RI "typedef \fBint8\fP \fBglm::lowp_int8\fP"
.br
.ti -1c
.RI "typedef \fBint8\fP \fBglm::mediump_int8\fP"
.br
.ti -1c
.RI "typedef \fBint8\fP \fBglm::highp_int8\fP"
.br
.ti -1c
.RI "typedef \fBint8\fP \fBglm::lowp_int8_t\fP"
.br
.ti -1c
.RI "typedef \fBint8\fP \fBglm::mediump_int8_t\fP"
.br
.ti -1c
.RI "typedef \fBint8\fP \fBglm::highp_int8_t\fP"
.br
.ti -1c
.RI "typedef \fBint8\fP \fBglm::int8_t\fP"
.br
.ti -1c
.RI "typedef \fBint16\fP \fBglm::lowp_i16\fP"
.br
.ti -1c
.RI "typedef \fBint16\fP \fBglm::mediump_i16\fP"
.br
.ti -1c
.RI "typedef \fBint16\fP \fBglm::highp_i16\fP"
.br
.ti -1c
.RI "typedef \fBint16\fP \fBglm::i16\fP"
.br
.ti -1c
.RI "typedef \fBint16\fP \fBglm::lowp_int16\fP"
.br
.ti -1c
.RI "typedef \fBint16\fP \fBglm::mediump_int16\fP"
.br
.ti -1c
.RI "typedef \fBint16\fP \fBglm::highp_int16\fP"
.br
.ti -1c
.RI "typedef \fBint16\fP \fBglm::lowp_int16_t\fP"
.br
.ti -1c
.RI "typedef \fBint16\fP \fBglm::mediump_int16_t\fP"
.br
.ti -1c
.RI "typedef \fBint16\fP \fBglm::highp_int16_t\fP"
.br
.ti -1c
.RI "typedef \fBint16\fP \fBglm::int16_t\fP"
.br
.ti -1c
.RI "typedef \fBint32\fP \fBglm::lowp_i32\fP"
.br
.ti -1c
.RI "typedef \fBint32\fP \fBglm::mediump_i32\fP"
.br
.ti -1c
.RI "typedef \fBint32\fP \fBglm::highp_i32\fP"
.br
.ti -1c
.RI "typedef \fBint32\fP \fBglm::i32\fP"
.br
.ti -1c
.RI "typedef \fBint32\fP \fBglm::lowp_int32\fP"
.br
.ti -1c
.RI "typedef \fBint32\fP \fBglm::mediump_int32\fP"
.br
.ti -1c
.RI "typedef \fBint32\fP \fBglm::highp_int32\fP"
.br
.ti -1c
.RI "typedef \fBint32\fP \fBglm::lowp_int32_t\fP"
.br
.ti -1c
.RI "typedef \fBint32\fP \fBglm::mediump_int32_t\fP"
.br
.ti -1c
.RI "typedef \fBint32\fP \fBglm::highp_int32_t\fP"
.br
.ti -1c
.RI "typedef \fBint32\fP \fBglm::int32_t\fP"
.br
.ti -1c
.RI "typedef \fBint64\fP \fBglm::lowp_i64\fP"
.br
.ti -1c
.RI "typedef \fBint64\fP \fBglm::mediump_i64\fP"
.br
.ti -1c
.RI "typedef \fBint64\fP \fBglm::highp_i64\fP"
.br
.ti -1c
.RI "typedef \fBint64\fP \fBglm::i64\fP"
.br
.ti -1c
.RI "typedef \fBint64\fP \fBglm::lowp_int64\fP"
.br
.ti -1c
.RI "typedef \fBint64\fP \fBglm::mediump_int64\fP"
.br
.ti -1c
.RI "typedef \fBint64\fP \fBglm::highp_int64\fP"
.br
.ti -1c
.RI "typedef \fBint64\fP \fBglm::lowp_int64_t\fP"
.br
.ti -1c
.RI "typedef \fBint64\fP \fBglm::mediump_int64_t\fP"
.br
.ti -1c
.RI "typedef \fBint64\fP \fBglm::highp_int64_t\fP"
.br
.ti -1c
.RI "typedef \fBint64\fP \fBglm::int64_t\fP"
.br
.ti -1c
.RI "typedef \fBuint8\fP \fBglm::lowp_u8\fP"
.br
.ti -1c
.RI "typedef \fBuint8\fP \fBglm::mediump_u8\fP"
.br
.ti -1c
.RI "typedef \fBuint8\fP \fBglm::highp_u8\fP"
.br
.ti -1c
.RI "typedef \fBuint8\fP \fBglm::u8\fP"
.br
.ti -1c
.RI "typedef \fBuint8\fP \fBglm::lowp_uint8\fP"
.br
.ti -1c
.RI "typedef \fBuint8\fP \fBglm::mediump_uint8\fP"
.br
.ti -1c
.RI "typedef \fBuint8\fP \fBglm::highp_uint8\fP"
.br
.ti -1c
.RI "typedef \fBuint8\fP \fBglm::lowp_uint8_t\fP"
.br
.ti -1c
.RI "typedef \fBuint8\fP \fBglm::mediump_uint8_t\fP"
.br
.ti -1c
.RI "typedef \fBuint8\fP \fBglm::highp_uint8_t\fP"
.br
.ti -1c
.RI "typedef \fBuint8\fP \fBglm::uint8_t\fP"
.br
.ti -1c
.RI "typedef \fBuint16\fP \fBglm::lowp_u16\fP"
.br
.ti -1c
.RI "typedef \fBuint16\fP \fBglm::mediump_u16\fP"
.br
.ti -1c
.RI "typedef \fBuint16\fP \fBglm::highp_u16\fP"
.br
.ti -1c
.RI "typedef \fBuint16\fP \fBglm::u16\fP"
.br
.ti -1c
.RI "typedef \fBuint16\fP \fBglm::lowp_uint16\fP"
.br
.ti -1c
.RI "typedef \fBuint16\fP \fBglm::mediump_uint16\fP"
.br
.ti -1c
.RI "typedef \fBuint16\fP \fBglm::highp_uint16\fP"
.br
.ti -1c
.RI "typedef \fBuint16\fP \fBglm::lowp_uint16_t\fP"
.br
.ti -1c
.RI "typedef \fBuint16\fP \fBglm::mediump_uint16_t\fP"
.br
.ti -1c
.RI "typedef \fBuint16\fP \fBglm::highp_uint16_t\fP"
.br
.ti -1c
.RI "typedef \fBuint16\fP \fBglm::uint16_t\fP"
.br
.ti -1c
.RI "typedef \fBuint32\fP \fBglm::lowp_u32\fP"
.br
.ti -1c
.RI "typedef \fBuint32\fP \fBglm::mediump_u32\fP"
.br
.ti -1c
.RI "typedef \fBuint32\fP \fBglm::highp_u32\fP"
.br
.ti -1c
.RI "typedef \fBuint32\fP \fBglm::u32\fP"
.br
.ti -1c
.RI "typedef \fBuint32\fP \fBglm::lowp_uint32\fP"
.br
.ti -1c
.RI "typedef \fBuint32\fP \fBglm::mediump_uint32\fP"
.br
.ti -1c
.RI "typedef \fBuint32\fP \fBglm::highp_uint32\fP"
.br
.ti -1c
.RI "typedef \fBuint32\fP \fBglm::lowp_uint32_t\fP"
.br
.ti -1c
.RI "typedef \fBuint32\fP \fBglm::mediump_uint32_t\fP"
.br
.ti -1c
.RI "typedef \fBuint32\fP \fBglm::highp_uint32_t\fP"
.br
.ti -1c
.RI "typedef \fBuint32\fP \fBglm::uint32_t\fP"
.br
.ti -1c
.RI "typedef \fBuint64\fP \fBglm::lowp_u64\fP"
.br
.ti -1c
.RI "typedef \fBuint64\fP \fBglm::mediump_u64\fP"
.br
.ti -1c
.RI "typedef \fBuint64\fP \fBglm::highp_u64\fP"
.br
.ti -1c
.RI "typedef \fBuint64\fP \fBglm::u64\fP"
.br
.ti -1c
.RI "typedef \fBuint64\fP \fBglm::lowp_uint64\fP"
.br
.ti -1c
.RI "typedef \fBuint64\fP \fBglm::mediump_uint64\fP"
.br
.ti -1c
.RI "typedef \fBuint64\fP \fBglm::highp_uint64\fP"
.br
.ti -1c
.RI "typedef \fBuint64\fP \fBglm::lowp_uint64_t\fP"
.br
.ti -1c
.RI "typedef \fBuint64\fP \fBglm::mediump_uint64_t\fP"
.br
.ti -1c
.RI "typedef \fBuint64\fP \fBglm::highp_uint64_t\fP"
.br
.ti -1c
.RI "typedef \fBuint64\fP \fBglm::uint64_t\fP"
.br
.ti -1c
.RI "typedef float \fBglm::lowp_f32\fP"
.br
.ti -1c
.RI "typedef float \fBglm::mediump_f32\fP"
.br
.ti -1c
.RI "typedef float \fBglm::highp_f32\fP"
.br
.ti -1c
.RI "typedef float \fBglm::f32\fP"
.br
.ti -1c
.RI "typedef float \fBglm::lowp_float32\fP"
.br
.ti -1c
.RI "typedef float \fBglm::mediump_float32\fP"
.br
.ti -1c
.RI "typedef float \fBglm::highp_float32\fP"
.br
.ti -1c
.RI "typedef float \fBglm::float32\fP"
.br
.ti -1c
.RI "typedef float \fBglm::lowp_float32_t\fP"
.br
.ti -1c
.RI "typedef float \fBglm::mediump_float32_t\fP"
.br
.ti -1c
.RI "typedef float \fBglm::highp_float32_t\fP"
.br
.ti -1c
.RI "typedef float \fBglm::float32_t\fP"
.br
.ti -1c
.RI "typedef double \fBglm::lowp_f64\fP"
.br
.ti -1c
.RI "typedef double \fBglm::mediump_f64\fP"
.br
.ti -1c
.RI "typedef double \fBglm::highp_f64\fP"
.br
.ti -1c
.RI "typedef double \fBglm::f64\fP"
.br
.ti -1c
.RI "typedef double \fBglm::lowp_float64\fP"
.br
.ti -1c
.RI "typedef double \fBglm::mediump_float64\fP"
.br
.ti -1c
.RI "typedef double \fBglm::highp_float64\fP"
.br
.ti -1c
.RI "typedef double \fBglm::float64\fP"
.br
.ti -1c
.RI "typedef double \fBglm::lowp_float64_t\fP"
.br
.ti -1c
.RI "typedef double \fBglm::mediump_float64_t\fP"
.br
.ti -1c
.RI "typedef double \fBglm::highp_float64_t\fP"
.br
.ti -1c
.RI "typedef double \fBglm::float64_t\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, int, \fBlowp\fP > \fBglm::lowp_ivec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, int, \fBlowp\fP > \fBglm::lowp_ivec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, int, \fBlowp\fP > \fBglm::lowp_ivec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, int, \fBlowp\fP > \fBglm::lowp_ivec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, int, \fBmediump\fP > \fBglm::mediump_ivec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, int, \fBmediump\fP > \fBglm::mediump_ivec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, int, \fBmediump\fP > \fBglm::mediump_ivec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, int, \fBmediump\fP > \fBglm::mediump_ivec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, int, \fBhighp\fP > \fBglm::highp_ivec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, int, \fBhighp\fP > \fBglm::highp_ivec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, int, \fBhighp\fP > \fBglm::highp_ivec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, int, \fBhighp\fP > \fBglm::highp_ivec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBi8\fP, \fBlowp\fP > \fBglm::lowp_i8vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBi8\fP, \fBlowp\fP > \fBglm::lowp_i8vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBi8\fP, \fBlowp\fP > \fBglm::lowp_i8vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBi8\fP, \fBlowp\fP > \fBglm::lowp_i8vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBi8\fP, \fBmediump\fP > \fBglm::mediump_i8vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBi8\fP, \fBmediump\fP > \fBglm::mediump_i8vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBi8\fP, \fBmediump\fP > \fBglm::mediump_i8vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBi8\fP, \fBmediump\fP > \fBglm::mediump_i8vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBi8\fP, \fBhighp\fP > \fBglm::highp_i8vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBi8\fP, \fBhighp\fP > \fBglm::highp_i8vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBi8\fP, \fBhighp\fP > \fBglm::highp_i8vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBi8\fP, \fBhighp\fP > \fBglm::highp_i8vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBi16\fP, \fBlowp\fP > \fBglm::lowp_i16vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBi16\fP, \fBlowp\fP > \fBglm::lowp_i16vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBi16\fP, \fBlowp\fP > \fBglm::lowp_i16vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBi16\fP, \fBlowp\fP > \fBglm::lowp_i16vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBi16\fP, \fBmediump\fP > \fBglm::mediump_i16vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBi16\fP, \fBmediump\fP > \fBglm::mediump_i16vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBi16\fP, \fBmediump\fP > \fBglm::mediump_i16vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBi16\fP, \fBmediump\fP > \fBglm::mediump_i16vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBi16\fP, \fBhighp\fP > \fBglm::highp_i16vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBi16\fP, \fBhighp\fP > \fBglm::highp_i16vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBi16\fP, \fBhighp\fP > \fBglm::highp_i16vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBi16\fP, \fBhighp\fP > \fBglm::highp_i16vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBi32\fP, \fBlowp\fP > \fBglm::lowp_i32vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBi32\fP, \fBlowp\fP > \fBglm::lowp_i32vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBi32\fP, \fBlowp\fP > \fBglm::lowp_i32vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBi32\fP, \fBlowp\fP > \fBglm::lowp_i32vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBi32\fP, \fBmediump\fP > \fBglm::mediump_i32vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBi32\fP, \fBmediump\fP > \fBglm::mediump_i32vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBi32\fP, \fBmediump\fP > \fBglm::mediump_i32vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBi32\fP, \fBmediump\fP > \fBglm::mediump_i32vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBi32\fP, \fBhighp\fP > \fBglm::highp_i32vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBi32\fP, \fBhighp\fP > \fBglm::highp_i32vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBi32\fP, \fBhighp\fP > \fBglm::highp_i32vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBi32\fP, \fBhighp\fP > \fBglm::highp_i32vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBi64\fP, \fBlowp\fP > \fBglm::lowp_i64vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBi64\fP, \fBlowp\fP > \fBglm::lowp_i64vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBi64\fP, \fBlowp\fP > \fBglm::lowp_i64vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBi64\fP, \fBlowp\fP > \fBglm::lowp_i64vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBi64\fP, \fBmediump\fP > \fBglm::mediump_i64vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBi64\fP, \fBmediump\fP > \fBglm::mediump_i64vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBi64\fP, \fBmediump\fP > \fBglm::mediump_i64vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBi64\fP, \fBmediump\fP > \fBglm::mediump_i64vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBi64\fP, \fBhighp\fP > \fBglm::highp_i64vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBi64\fP, \fBhighp\fP > \fBglm::highp_i64vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBi64\fP, \fBhighp\fP > \fBglm::highp_i64vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBi64\fP, \fBhighp\fP > \fBglm::highp_i64vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBuint\fP, \fBlowp\fP > \fBglm::lowp_uvec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBuint\fP, \fBlowp\fP > \fBglm::lowp_uvec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBuint\fP, \fBlowp\fP > \fBglm::lowp_uvec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBuint\fP, \fBlowp\fP > \fBglm::lowp_uvec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBuint\fP, \fBmediump\fP > \fBglm::mediump_uvec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBuint\fP, \fBmediump\fP > \fBglm::mediump_uvec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBuint\fP, \fBmediump\fP > \fBglm::mediump_uvec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBuint\fP, \fBmediump\fP > \fBglm::mediump_uvec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBuint\fP, \fBhighp\fP > \fBglm::highp_uvec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBuint\fP, \fBhighp\fP > \fBglm::highp_uvec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBuint\fP, \fBhighp\fP > \fBglm::highp_uvec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBuint\fP, \fBhighp\fP > \fBglm::highp_uvec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBu8\fP, \fBlowp\fP > \fBglm::lowp_u8vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBu8\fP, \fBlowp\fP > \fBglm::lowp_u8vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBu8\fP, \fBlowp\fP > \fBglm::lowp_u8vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBu8\fP, \fBlowp\fP > \fBglm::lowp_u8vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBu8\fP, \fBmediump\fP > \fBglm::mediump_u8vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBu8\fP, \fBmediump\fP > \fBglm::mediump_u8vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBu8\fP, \fBmediump\fP > \fBglm::mediump_u8vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBu8\fP, \fBmediump\fP > \fBglm::mediump_u8vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBu8\fP, \fBhighp\fP > \fBglm::highp_u8vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBu8\fP, \fBhighp\fP > \fBglm::highp_u8vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBu8\fP, \fBhighp\fP > \fBglm::highp_u8vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBu8\fP, \fBhighp\fP > \fBglm::highp_u8vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBu16\fP, \fBlowp\fP > \fBglm::lowp_u16vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBu16\fP, \fBlowp\fP > \fBglm::lowp_u16vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBu16\fP, \fBlowp\fP > \fBglm::lowp_u16vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBu16\fP, \fBlowp\fP > \fBglm::lowp_u16vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBu16\fP, \fBmediump\fP > \fBglm::mediump_u16vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBu16\fP, \fBmediump\fP > \fBglm::mediump_u16vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBu16\fP, \fBmediump\fP > \fBglm::mediump_u16vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBu16\fP, \fBmediump\fP > \fBglm::mediump_u16vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBu16\fP, \fBhighp\fP > \fBglm::highp_u16vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBu16\fP, \fBhighp\fP > \fBglm::highp_u16vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBu16\fP, \fBhighp\fP > \fBglm::highp_u16vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBu16\fP, \fBhighp\fP > \fBglm::highp_u16vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBu32\fP, \fBlowp\fP > \fBglm::lowp_u32vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBu32\fP, \fBlowp\fP > \fBglm::lowp_u32vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBu32\fP, \fBlowp\fP > \fBglm::lowp_u32vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBu32\fP, \fBlowp\fP > \fBglm::lowp_u32vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBu32\fP, \fBmediump\fP > \fBglm::mediump_u32vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBu32\fP, \fBmediump\fP > \fBglm::mediump_u32vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBu32\fP, \fBmediump\fP > \fBglm::mediump_u32vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBu32\fP, \fBmediump\fP > \fBglm::mediump_u32vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBu32\fP, \fBhighp\fP > \fBglm::highp_u32vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBu32\fP, \fBhighp\fP > \fBglm::highp_u32vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBu32\fP, \fBhighp\fP > \fBglm::highp_u32vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBu32\fP, \fBhighp\fP > \fBglm::highp_u32vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBu64\fP, \fBlowp\fP > \fBglm::lowp_u64vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBu64\fP, \fBlowp\fP > \fBglm::lowp_u64vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBu64\fP, \fBlowp\fP > \fBglm::lowp_u64vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBu64\fP, \fBlowp\fP > \fBglm::lowp_u64vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBu64\fP, \fBmediump\fP > \fBglm::mediump_u64vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBu64\fP, \fBmediump\fP > \fBglm::mediump_u64vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBu64\fP, \fBmediump\fP > \fBglm::mediump_u64vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBu64\fP, \fBmediump\fP > \fBglm::mediump_u64vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBu64\fP, \fBhighp\fP > \fBglm::highp_u64vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBu64\fP, \fBhighp\fP > \fBglm::highp_u64vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBu64\fP, \fBhighp\fP > \fBglm::highp_u64vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBu64\fP, \fBhighp\fP > \fBglm::highp_u64vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, float, \fBlowp\fP > \fBglm::lowp_fvec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, float, \fBlowp\fP > \fBglm::lowp_fvec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, float, \fBlowp\fP > \fBglm::lowp_fvec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, float, \fBlowp\fP > \fBglm::lowp_fvec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, float, \fBmediump\fP > \fBglm::mediump_fvec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, float, \fBmediump\fP > \fBglm::mediump_fvec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, float, \fBmediump\fP > \fBglm::mediump_fvec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, float, \fBmediump\fP > \fBglm::mediump_fvec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, float, \fBhighp\fP > \fBglm::highp_fvec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, float, \fBhighp\fP > \fBglm::highp_fvec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, float, \fBhighp\fP > \fBglm::highp_fvec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, float, \fBhighp\fP > \fBglm::highp_fvec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBf32\fP, \fBdefaultp\fP > \fBglm::fvec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBf32\fP, \fBdefaultp\fP > \fBglm::fvec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBf32\fP, \fBdefaultp\fP > \fBglm::fvec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBf32\fP, \fBdefaultp\fP > \fBglm::fvec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBf32\fP, \fBdefaultp\fP > \fBglm::f32vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBf32\fP, \fBdefaultp\fP > \fBglm::f32vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBf32\fP, \fBdefaultp\fP > \fBglm::f32vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBf32\fP, \fBdefaultp\fP > \fBglm::f32vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, \fBf64\fP, \fBdefaultp\fP > \fBglm::f64vec1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, \fBf64\fP, \fBdefaultp\fP > \fBglm::f64vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, \fBf64\fP, \fBdefaultp\fP > \fBglm::f64vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, \fBf64\fP, \fBdefaultp\fP > \fBglm::f64vec4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_fmat2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_fmat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_fmat4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_fmat2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_fmat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_fmat4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf32\fP, \fBhighp\fP > \fBglm::highp_fmat2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf32\fP, \fBhighp\fP > \fBglm::highp_fmat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf32\fP, \fBhighp\fP > \fBglm::highp_fmat4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf32\fP, \fBdefaultp\fP > \fBglm::fmat2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf32\fP, \fBdefaultp\fP > \fBglm::fmat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf32\fP, \fBdefaultp\fP > \fBglm::fmat4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32mat2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32mat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32mat4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32mat2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32mat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32mat4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32mat2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32mat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32mat4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf32\fP, \fBdefaultp\fP > \fBglm::f32mat2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf32\fP, \fBdefaultp\fP > \fBglm::f32mat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf32\fP, \fBdefaultp\fP > \fBglm::f32mat4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64mat2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64mat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64mat4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64mat2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64mat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64mat4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64mat2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64mat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64mat4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf64\fP, \fBdefaultp\fP > \fBglm::f64mat2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf64\fP, \fBdefaultp\fP > \fBglm::f64mat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf64\fP, \fBdefaultp\fP > \fBglm::f64mat4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_fmat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_fmat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_fmat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_fmat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_fmat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_fmat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_fmat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_fmat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_fmat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_fmat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_fmat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_fmat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_fmat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_fmat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_fmat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_fmat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_fmat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_fmat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf32\fP, \fBhighp\fP > \fBglm::highp_fmat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBf32\fP, \fBhighp\fP > \fBglm::highp_fmat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBf32\fP, \fBhighp\fP > \fBglm::highp_fmat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBf32\fP, \fBhighp\fP > \fBglm::highp_fmat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf32\fP, \fBhighp\fP > \fBglm::highp_fmat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBf32\fP, \fBhighp\fP > \fBglm::highp_fmat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBf32\fP, \fBhighp\fP > \fBglm::highp_fmat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBf32\fP, \fBhighp\fP > \fBglm::highp_fmat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf32\fP, \fBhighp\fP > \fBglm::highp_fmat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf32\fP, \fBdefaultp\fP > \fBglm::fmat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBf32\fP, \fBdefaultp\fP > \fBglm::fmat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBf32\fP, \fBdefaultp\fP > \fBglm::fmat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBf32\fP, \fBdefaultp\fP > \fBglm::fmat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf32\fP, \fBdefaultp\fP > \fBglm::fmat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBf32\fP, \fBdefaultp\fP > \fBglm::fmat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBf32\fP, \fBdefaultp\fP > \fBglm::fmat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBf32\fP, \fBdefaultp\fP > \fBglm::fmat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf32\fP, \fBdefaultp\fP > \fBglm::fmat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf32\fP, \fBdefaultp\fP > \fBglm::f32mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBf32\fP, \fBdefaultp\fP > \fBglm::f32mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBf32\fP, \fBdefaultp\fP > \fBglm::f32mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBf32\fP, \fBdefaultp\fP > \fBglm::f32mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf32\fP, \fBdefaultp\fP > \fBglm::f32mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBf32\fP, \fBdefaultp\fP > \fBglm::f32mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBf32\fP, \fBdefaultp\fP > \fBglm::f32mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBf32\fP, \fBdefaultp\fP > \fBglm::f32mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf32\fP, \fBdefaultp\fP > \fBglm::f32mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBf64\fP, \fBdefaultp\fP > \fBglm::f64mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBf64\fP, \fBdefaultp\fP > \fBglm::f64mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBf64\fP, \fBdefaultp\fP > \fBglm::f64mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBf64\fP, \fBdefaultp\fP > \fBglm::f64mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBf64\fP, \fBdefaultp\fP > \fBglm::f64mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBf64\fP, \fBdefaultp\fP > \fBglm::f64mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBf64\fP, \fBdefaultp\fP > \fBglm::f64mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBf64\fP, \fBdefaultp\fP > \fBglm::f64mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBf64\fP, \fBdefaultp\fP > \fBglm::f64mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, int, \fBlowp\fP > \fBglm::lowp_imat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, int, \fBlowp\fP > \fBglm::lowp_imat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, int, \fBlowp\fP > \fBglm::lowp_imat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, int, \fBlowp\fP > \fBglm::lowp_imat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, int, \fBlowp\fP > \fBglm::lowp_imat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, int, \fBlowp\fP > \fBglm::lowp_imat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, int, \fBlowp\fP > \fBglm::lowp_imat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, int, \fBlowp\fP > \fBglm::lowp_imat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, int, \fBlowp\fP > \fBglm::lowp_imat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, int, \fBmediump\fP > \fBglm::mediump_imat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, int, \fBmediump\fP > \fBglm::mediump_imat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, int, \fBmediump\fP > \fBglm::mediump_imat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, int, \fBmediump\fP > \fBglm::mediump_imat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, int, \fBmediump\fP > \fBglm::mediump_imat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, int, \fBmediump\fP > \fBglm::mediump_imat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, int, \fBmediump\fP > \fBglm::mediump_imat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, int, \fBmediump\fP > \fBglm::mediump_imat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, int, \fBmediump\fP > \fBglm::mediump_imat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, int, \fBhighp\fP > \fBglm::highp_imat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, int, \fBhighp\fP > \fBglm::highp_imat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, int, \fBhighp\fP > \fBglm::highp_imat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, int, \fBhighp\fP > \fBglm::highp_imat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, int, \fBhighp\fP > \fBglm::highp_imat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, int, \fBhighp\fP > \fBglm::highp_imat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, int, \fBhighp\fP > \fBglm::highp_imat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, int, \fBhighp\fP > \fBglm::highp_imat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, int, \fBhighp\fP > \fBglm::highp_imat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBint8\fP, \fBlowp\fP > \fBglm::lowp_i8mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBint8\fP, \fBlowp\fP > \fBglm::lowp_i8mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBint8\fP, \fBlowp\fP > \fBglm::lowp_i8mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBint8\fP, \fBlowp\fP > \fBglm::lowp_i8mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBint8\fP, \fBlowp\fP > \fBglm::lowp_i8mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBint8\fP, \fBlowp\fP > \fBglm::lowp_i8mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBint8\fP, \fBlowp\fP > \fBglm::lowp_i8mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBint8\fP, \fBlowp\fP > \fBglm::lowp_i8mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBint8\fP, \fBlowp\fP > \fBglm::lowp_i8mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBint8\fP, \fBmediump\fP > \fBglm::mediump_i8mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBint8\fP, \fBmediump\fP > \fBglm::mediump_i8mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBint8\fP, \fBmediump\fP > \fBglm::mediump_i8mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBint8\fP, \fBmediump\fP > \fBglm::mediump_i8mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBint8\fP, \fBmediump\fP > \fBglm::mediump_i8mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBint8\fP, \fBmediump\fP > \fBglm::mediump_i8mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBint8\fP, \fBmediump\fP > \fBglm::mediump_i8mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBint8\fP, \fBmediump\fP > \fBglm::mediump_i8mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBint8\fP, \fBmediump\fP > \fBglm::mediump_i8mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBint8\fP, \fBhighp\fP > \fBglm::highp_i8mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBint8\fP, \fBhighp\fP > \fBglm::highp_i8mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBint8\fP, \fBhighp\fP > \fBglm::highp_i8mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBint8\fP, \fBhighp\fP > \fBglm::highp_i8mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBint8\fP, \fBhighp\fP > \fBglm::highp_i8mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBint8\fP, \fBhighp\fP > \fBglm::highp_i8mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBint8\fP, \fBhighp\fP > \fBglm::highp_i8mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBint8\fP, \fBhighp\fP > \fBglm::highp_i8mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBint8\fP, \fBhighp\fP > \fBglm::highp_i8mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBint16\fP, \fBlowp\fP > \fBglm::lowp_i16mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBint16\fP, \fBlowp\fP > \fBglm::lowp_i16mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBint16\fP, \fBlowp\fP > \fBglm::lowp_i16mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBint16\fP, \fBlowp\fP > \fBglm::lowp_i16mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBint16\fP, \fBlowp\fP > \fBglm::lowp_i16mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBint16\fP, \fBlowp\fP > \fBglm::lowp_i16mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBint16\fP, \fBlowp\fP > \fBglm::lowp_i16mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBint16\fP, \fBlowp\fP > \fBglm::lowp_i16mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBint16\fP, \fBlowp\fP > \fBglm::lowp_i16mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBint16\fP, \fBmediump\fP > \fBglm::mediump_i16mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBint16\fP, \fBmediump\fP > \fBglm::mediump_i16mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBint16\fP, \fBmediump\fP > \fBglm::mediump_i16mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBint16\fP, \fBmediump\fP > \fBglm::mediump_i16mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBint16\fP, \fBmediump\fP > \fBglm::mediump_i16mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBint16\fP, \fBmediump\fP > \fBglm::mediump_i16mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBint16\fP, \fBmediump\fP > \fBglm::mediump_i16mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBint16\fP, \fBmediump\fP > \fBglm::mediump_i16mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBint16\fP, \fBmediump\fP > \fBglm::mediump_i16mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBint16\fP, \fBhighp\fP > \fBglm::highp_i16mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBint16\fP, \fBhighp\fP > \fBglm::highp_i16mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBint16\fP, \fBhighp\fP > \fBglm::highp_i16mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBint16\fP, \fBhighp\fP > \fBglm::highp_i16mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBint16\fP, \fBhighp\fP > \fBglm::highp_i16mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBint16\fP, \fBhighp\fP > \fBglm::highp_i16mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBint16\fP, \fBhighp\fP > \fBglm::highp_i16mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBint16\fP, \fBhighp\fP > \fBglm::highp_i16mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBint16\fP, \fBhighp\fP > \fBglm::highp_i16mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBint32\fP, \fBlowp\fP > \fBglm::lowp_i32mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBint32\fP, \fBlowp\fP > \fBglm::lowp_i32mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBint32\fP, \fBlowp\fP > \fBglm::lowp_i32mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBint32\fP, \fBlowp\fP > \fBglm::lowp_i32mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBint32\fP, \fBlowp\fP > \fBglm::lowp_i32mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBint32\fP, \fBlowp\fP > \fBglm::lowp_i32mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBint32\fP, \fBlowp\fP > \fBglm::lowp_i32mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBint32\fP, \fBlowp\fP > \fBglm::lowp_i32mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBint32\fP, \fBlowp\fP > \fBglm::lowp_i32mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBint32\fP, \fBmediump\fP > \fBglm::mediump_i32mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBint32\fP, \fBmediump\fP > \fBglm::mediump_i32mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBint32\fP, \fBmediump\fP > \fBglm::mediump_i32mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBint32\fP, \fBmediump\fP > \fBglm::mediump_i32mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBint32\fP, \fBmediump\fP > \fBglm::mediump_i32mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBint32\fP, \fBmediump\fP > \fBglm::mediump_i32mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBint32\fP, \fBmediump\fP > \fBglm::mediump_i32mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBint32\fP, \fBmediump\fP > \fBglm::mediump_i32mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBint32\fP, \fBmediump\fP > \fBglm::mediump_i32mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBint32\fP, \fBhighp\fP > \fBglm::highp_i32mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBint32\fP, \fBhighp\fP > \fBglm::highp_i32mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBint32\fP, \fBhighp\fP > \fBglm::highp_i32mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBint32\fP, \fBhighp\fP > \fBglm::highp_i32mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBint32\fP, \fBhighp\fP > \fBglm::highp_i32mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBint32\fP, \fBhighp\fP > \fBglm::highp_i32mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBint32\fP, \fBhighp\fP > \fBglm::highp_i32mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBint32\fP, \fBhighp\fP > \fBglm::highp_i32mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBint32\fP, \fBhighp\fP > \fBglm::highp_i32mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBint64\fP, \fBlowp\fP > \fBglm::lowp_i64mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBint64\fP, \fBlowp\fP > \fBglm::lowp_i64mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBint64\fP, \fBlowp\fP > \fBglm::lowp_i64mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBint64\fP, \fBlowp\fP > \fBglm::lowp_i64mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBint64\fP, \fBlowp\fP > \fBglm::lowp_i64mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBint64\fP, \fBlowp\fP > \fBglm::lowp_i64mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBint64\fP, \fBlowp\fP > \fBglm::lowp_i64mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBint64\fP, \fBlowp\fP > \fBglm::lowp_i64mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBint64\fP, \fBlowp\fP > \fBglm::lowp_i64mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBint64\fP, \fBmediump\fP > \fBglm::mediump_i64mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBint64\fP, \fBmediump\fP > \fBglm::mediump_i64mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBint64\fP, \fBmediump\fP > \fBglm::mediump_i64mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBint64\fP, \fBmediump\fP > \fBglm::mediump_i64mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBint64\fP, \fBmediump\fP > \fBglm::mediump_i64mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBint64\fP, \fBmediump\fP > \fBglm::mediump_i64mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBint64\fP, \fBmediump\fP > \fBglm::mediump_i64mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBint64\fP, \fBmediump\fP > \fBglm::mediump_i64mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBint64\fP, \fBmediump\fP > \fBglm::mediump_i64mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBint64\fP, \fBhighp\fP > \fBglm::highp_i64mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBint64\fP, \fBhighp\fP > \fBglm::highp_i64mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBint64\fP, \fBhighp\fP > \fBglm::highp_i64mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBint64\fP, \fBhighp\fP > \fBglm::highp_i64mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBint64\fP, \fBhighp\fP > \fBglm::highp_i64mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBint64\fP, \fBhighp\fP > \fBglm::highp_i64mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBint64\fP, \fBhighp\fP > \fBglm::highp_i64mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBint64\fP, \fBhighp\fP > \fBglm::highp_i64mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBint64\fP, \fBhighp\fP > \fBglm::highp_i64mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBuint\fP, \fBlowp\fP > \fBglm::lowp_umat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBuint\fP, \fBlowp\fP > \fBglm::lowp_umat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint\fP, \fBlowp\fP > \fBglm::lowp_umat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBuint\fP, \fBlowp\fP > \fBglm::lowp_umat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint\fP, \fBlowp\fP > \fBglm::lowp_umat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBuint\fP, \fBlowp\fP > \fBglm::lowp_umat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBuint\fP, \fBlowp\fP > \fBglm::lowp_umat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBuint\fP, \fBlowp\fP > \fBglm::lowp_umat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBuint\fP, \fBlowp\fP > \fBglm::lowp_umat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBuint\fP, \fBmediump\fP > \fBglm::mediump_umat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBuint\fP, \fBmediump\fP > \fBglm::mediump_umat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint\fP, \fBmediump\fP > \fBglm::mediump_umat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBuint\fP, \fBmediump\fP > \fBglm::mediump_umat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint\fP, \fBmediump\fP > \fBglm::mediump_umat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBuint\fP, \fBmediump\fP > \fBglm::mediump_umat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBuint\fP, \fBmediump\fP > \fBglm::mediump_umat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBuint\fP, \fBmediump\fP > \fBglm::mediump_umat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBuint\fP, \fBmediump\fP > \fBglm::mediump_umat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBuint\fP, \fBhighp\fP > \fBglm::highp_umat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBuint\fP, \fBhighp\fP > \fBglm::highp_umat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint\fP, \fBhighp\fP > \fBglm::highp_umat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBuint\fP, \fBhighp\fP > \fBglm::highp_umat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint\fP, \fBhighp\fP > \fBglm::highp_umat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBuint\fP, \fBhighp\fP > \fBglm::highp_umat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBuint\fP, \fBhighp\fP > \fBglm::highp_umat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBuint\fP, \fBhighp\fP > \fBglm::highp_umat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBuint\fP, \fBhighp\fP > \fBglm::highp_umat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBuint8\fP, \fBlowp\fP > \fBglm::lowp_u8mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBuint8\fP, \fBlowp\fP > \fBglm::lowp_u8mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint8\fP, \fBlowp\fP > \fBglm::lowp_u8mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBuint8\fP, \fBlowp\fP > \fBglm::lowp_u8mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint8\fP, \fBlowp\fP > \fBglm::lowp_u8mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBuint8\fP, \fBlowp\fP > \fBglm::lowp_u8mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBuint8\fP, \fBlowp\fP > \fBglm::lowp_u8mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBuint8\fP, \fBlowp\fP > \fBglm::lowp_u8mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBuint8\fP, \fBlowp\fP > \fBglm::lowp_u8mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBuint8\fP, \fBmediump\fP > \fBglm::mediump_u8mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBuint8\fP, \fBmediump\fP > \fBglm::mediump_u8mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint8\fP, \fBmediump\fP > \fBglm::mediump_u8mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBuint8\fP, \fBmediump\fP > \fBglm::mediump_u8mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint8\fP, \fBmediump\fP > \fBglm::mediump_u8mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBuint8\fP, \fBmediump\fP > \fBglm::mediump_u8mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBuint8\fP, \fBmediump\fP > \fBglm::mediump_u8mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBuint8\fP, \fBmediump\fP > \fBglm::mediump_u8mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBuint8\fP, \fBmediump\fP > \fBglm::mediump_u8mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBuint8\fP, \fBhighp\fP > \fBglm::highp_u8mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBuint8\fP, \fBhighp\fP > \fBglm::highp_u8mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint8\fP, \fBhighp\fP > \fBglm::highp_u8mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBuint8\fP, \fBhighp\fP > \fBglm::highp_u8mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint8\fP, \fBhighp\fP > \fBglm::highp_u8mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBuint8\fP, \fBhighp\fP > \fBglm::highp_u8mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBuint8\fP, \fBhighp\fP > \fBglm::highp_u8mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBuint8\fP, \fBhighp\fP > \fBglm::highp_u8mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBuint8\fP, \fBhighp\fP > \fBglm::highp_u8mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBuint16\fP, \fBlowp\fP > \fBglm::lowp_u16mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBuint16\fP, \fBlowp\fP > \fBglm::lowp_u16mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint16\fP, \fBlowp\fP > \fBglm::lowp_u16mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBuint16\fP, \fBlowp\fP > \fBglm::lowp_u16mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint16\fP, \fBlowp\fP > \fBglm::lowp_u16mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBuint16\fP, \fBlowp\fP > \fBglm::lowp_u16mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBuint16\fP, \fBlowp\fP > \fBglm::lowp_u16mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBuint16\fP, \fBlowp\fP > \fBglm::lowp_u16mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBuint16\fP, \fBlowp\fP > \fBglm::lowp_u16mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBuint16\fP, \fBmediump\fP > \fBglm::mediump_u16mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBuint16\fP, \fBmediump\fP > \fBglm::mediump_u16mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint16\fP, \fBmediump\fP > \fBglm::mediump_u16mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBuint16\fP, \fBmediump\fP > \fBglm::mediump_u16mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint16\fP, \fBmediump\fP > \fBglm::mediump_u16mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBuint16\fP, \fBmediump\fP > \fBglm::mediump_u16mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBuint16\fP, \fBmediump\fP > \fBglm::mediump_u16mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBuint16\fP, \fBmediump\fP > \fBglm::mediump_u16mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBuint16\fP, \fBmediump\fP > \fBglm::mediump_u16mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBuint16\fP, \fBhighp\fP > \fBglm::highp_u16mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBuint16\fP, \fBhighp\fP > \fBglm::highp_u16mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint16\fP, \fBhighp\fP > \fBglm::highp_u16mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBuint16\fP, \fBhighp\fP > \fBglm::highp_u16mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint16\fP, \fBhighp\fP > \fBglm::highp_u16mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBuint16\fP, \fBhighp\fP > \fBglm::highp_u16mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBuint16\fP, \fBhighp\fP > \fBglm::highp_u16mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBuint16\fP, \fBhighp\fP > \fBglm::highp_u16mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBuint16\fP, \fBhighp\fP > \fBglm::highp_u16mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBuint32\fP, \fBlowp\fP > \fBglm::lowp_u32mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBuint32\fP, \fBlowp\fP > \fBglm::lowp_u32mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint32\fP, \fBlowp\fP > \fBglm::lowp_u32mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBuint32\fP, \fBlowp\fP > \fBglm::lowp_u32mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint32\fP, \fBlowp\fP > \fBglm::lowp_u32mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBuint32\fP, \fBlowp\fP > \fBglm::lowp_u32mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBuint32\fP, \fBlowp\fP > \fBglm::lowp_u32mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBuint32\fP, \fBlowp\fP > \fBglm::lowp_u32mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBuint32\fP, \fBlowp\fP > \fBglm::lowp_u32mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBuint32\fP, \fBmediump\fP > \fBglm::mediump_u32mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBuint32\fP, \fBmediump\fP > \fBglm::mediump_u32mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint32\fP, \fBmediump\fP > \fBglm::mediump_u32mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBuint32\fP, \fBmediump\fP > \fBglm::mediump_u32mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint32\fP, \fBmediump\fP > \fBglm::mediump_u32mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBuint32\fP, \fBmediump\fP > \fBglm::mediump_u32mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBuint32\fP, \fBmediump\fP > \fBglm::mediump_u32mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBuint32\fP, \fBmediump\fP > \fBglm::mediump_u32mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBuint32\fP, \fBmediump\fP > \fBglm::mediump_u32mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBuint32\fP, \fBhighp\fP > \fBglm::highp_u32mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBuint32\fP, \fBhighp\fP > \fBglm::highp_u32mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint32\fP, \fBhighp\fP > \fBglm::highp_u32mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBuint32\fP, \fBhighp\fP > \fBglm::highp_u32mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint32\fP, \fBhighp\fP > \fBglm::highp_u32mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBuint32\fP, \fBhighp\fP > \fBglm::highp_u32mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBuint32\fP, \fBhighp\fP > \fBglm::highp_u32mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBuint32\fP, \fBhighp\fP > \fBglm::highp_u32mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBuint32\fP, \fBhighp\fP > \fBglm::highp_u32mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBuint64\fP, \fBlowp\fP > \fBglm::lowp_u64mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBuint64\fP, \fBlowp\fP > \fBglm::lowp_u64mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint64\fP, \fBlowp\fP > \fBglm::lowp_u64mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBuint64\fP, \fBlowp\fP > \fBglm::lowp_u64mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint64\fP, \fBlowp\fP > \fBglm::lowp_u64mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBuint64\fP, \fBlowp\fP > \fBglm::lowp_u64mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBuint64\fP, \fBlowp\fP > \fBglm::lowp_u64mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBuint64\fP, \fBlowp\fP > \fBglm::lowp_u64mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBuint64\fP, \fBlowp\fP > \fBglm::lowp_u64mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBuint64\fP, \fBmediump\fP > \fBglm::mediump_u64mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBuint64\fP, \fBmediump\fP > \fBglm::mediump_u64mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint64\fP, \fBmediump\fP > \fBglm::mediump_u64mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBuint64\fP, \fBmediump\fP > \fBglm::mediump_u64mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint64\fP, \fBmediump\fP > \fBglm::mediump_u64mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBuint64\fP, \fBmediump\fP > \fBglm::mediump_u64mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBuint64\fP, \fBmediump\fP > \fBglm::mediump_u64mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBuint64\fP, \fBmediump\fP > \fBglm::mediump_u64mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBuint64\fP, \fBmediump\fP > \fBglm::mediump_u64mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, \fBuint64\fP, \fBhighp\fP > \fBglm::highp_u64mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, \fBuint64\fP, \fBhighp\fP > \fBglm::highp_u64mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, \fBuint64\fP, \fBhighp\fP > \fBglm::highp_u64mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, \fBuint64\fP, \fBhighp\fP > \fBglm::highp_u64mat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, \fBuint64\fP, \fBhighp\fP > \fBglm::highp_u64mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBuint64\fP, \fBhighp\fP > \fBglm::highp_u64mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, \fBuint64\fP, \fBhighp\fP > \fBglm::highp_u64mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, \fBuint64\fP, \fBhighp\fP > \fBglm::highp_u64mat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, \fBuint64\fP, \fBhighp\fP > \fBglm::highp_u64mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBqua\fP< float, \fBlowp\fP > \fBglm::lowp_fquat\fP"
.br
.ti -1c
.RI "typedef \fBqua\fP< float, \fBmediump\fP > \fBglm::mediump_fquat\fP"
.br
.ti -1c
.RI "typedef \fBqua\fP< float, \fBhighp\fP > \fBglm::highp_fquat\fP"
.br
.ti -1c
.RI "typedef \fBqua\fP< float, \fBdefaultp\fP > \fBglm::fquat\fP"
.br
.ti -1c
.RI "typedef \fBqua\fP< \fBf32\fP, \fBlowp\fP > \fBglm::lowp_f32quat\fP"
.br
.ti -1c
.RI "typedef \fBqua\fP< \fBf32\fP, \fBmediump\fP > \fBglm::mediump_f32quat\fP"
.br
.ti -1c
.RI "typedef \fBqua\fP< \fBf32\fP, \fBhighp\fP > \fBglm::highp_f32quat\fP"
.br
.ti -1c
.RI "typedef \fBqua\fP< \fBf32\fP, \fBdefaultp\fP > \fBglm::f32quat\fP"
.br
.ti -1c
.RI "typedef \fBqua\fP< \fBf64\fP, \fBlowp\fP > \fBglm::lowp_f64quat\fP"
.br
.ti -1c
.RI "typedef \fBqua\fP< \fBf64\fP, \fBmediump\fP > \fBglm::mediump_f64quat\fP"
.br
.ti -1c
.RI "typedef \fBqua\fP< \fBf64\fP, \fBhighp\fP > \fBglm::highp_f64quat\fP"
.br
.ti -1c
.RI "typedef \fBqua\fP< \fBf64\fP, \fBdefaultp\fP > \fBglm::f64quat\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
