.TH "gamepad_buttons" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gamepad_buttons \- Gamepad buttons
.PP
 \- Gamepad buttons\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_A\fP   0"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_B\fP   1"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_X\fP   2"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_Y\fP   3"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_LEFT_BUMPER\fP   4"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_RIGHT_BUMPER\fP   5"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_BACK\fP   6"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_START\fP   7"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_GUIDE\fP   8"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_LEFT_THUMB\fP   9"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_RIGHT_THUMB\fP   10"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_DPAD_UP\fP   11"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_DPAD_RIGHT\fP   12"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_DPAD_DOWN\fP   13"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_DPAD_LEFT\fP   14"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_LAST\fP   \fBGLFW_GAMEPAD_BUTTON_DPAD_LEFT\fP"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_CROSS\fP   \fBGLFW_GAMEPAD_BUTTON_A\fP"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_CIRCLE\fP   \fBGLFW_GAMEPAD_BUTTON_B\fP"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_SQUARE\fP   \fBGLFW_GAMEPAD_BUTTON_X\fP"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_TRIANGLE\fP   \fBGLFW_GAMEPAD_BUTTON_Y\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Gamepad buttons\&. 

See \fBgamepad\fP for how these are used\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define GLFW_GAMEPAD_BUTTON_A   0"

.SS "#define GLFW_GAMEPAD_BUTTON_B   1"

.SS "#define GLFW_GAMEPAD_BUTTON_BACK   6"

.SS "#define GLFW_GAMEPAD_BUTTON_CIRCLE   \fBGLFW_GAMEPAD_BUTTON_B\fP"

.SS "#define GLFW_GAMEPAD_BUTTON_CROSS   \fBGLFW_GAMEPAD_BUTTON_A\fP"

.SS "#define GLFW_GAMEPAD_BUTTON_DPAD_DOWN   13"

.SS "#define GLFW_GAMEPAD_BUTTON_DPAD_LEFT   14"

.SS "#define GLFW_GAMEPAD_BUTTON_DPAD_RIGHT   12"

.SS "#define GLFW_GAMEPAD_BUTTON_DPAD_UP   11"

.SS "#define GLFW_GAMEPAD_BUTTON_GUIDE   8"

.SS "#define GLFW_GAMEPAD_BUTTON_LAST   \fBGLFW_GAMEPAD_BUTTON_DPAD_LEFT\fP"

.SS "#define GLFW_GAMEPAD_BUTTON_LEFT_BUMPER   4"

.SS "#define GLFW_GAMEPAD_BUTTON_LEFT_THUMB   9"

.SS "#define GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER   5"

.SS "#define GLFW_GAMEPAD_BUTTON_RIGHT_THUMB   10"

.SS "#define GLFW_GAMEPAD_BUTTON_SQUARE   \fBGLFW_GAMEPAD_BUTTON_X\fP"

.SS "#define GLFW_GAMEPAD_BUTTON_START   7"

.SS "#define GLFW_GAMEPAD_BUTTON_TRIANGLE   \fBGLFW_GAMEPAD_BUTTON_Y\fP"

.SS "#define GLFW_GAMEPAD_BUTTON_X   2"

.SS "#define GLFW_GAMEPAD_BUTTON_Y   3"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
