.TH "adhed/assimp/GenericProperty.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/assimp/GenericProperty.h
.SH SYNOPSIS
.br
.PP
\fR#include <assimp/Hash\&.h>\fP
.br
\fR#include <assimp/ai_assert\&.h>\fP
.br
\fR#include <assimp/Importer\&.hpp>\fP
.br
\fR#include <map>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAI_GENERIC_PROPERTY_H_INCLUDED\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class \fBT\fP > bool \fBSetGenericProperty\fP (std::map< unsigned int, \fBT\fP > &list, const char *szName, const \fBT\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "template<class \fBT\fP > const \fBT\fP & \fBGetGenericProperty\fP (const std::map< unsigned int, \fBT\fP > &list, const char *szName, const \fBT\fP &errorReturn)"
.br
.ti -1c
.RI "template<class \fBT\fP > \fBvoid\fP \fBSetGenericPropertyPtr\fP (std::map< unsigned int, \fBT\fP * > &list, const char *szName, \fBT\fP *\fBvalue\fP, bool *bWasExisting=nullptr)"
.br
.ti -1c
.RI "template<class \fBT\fP > bool \fBHasGenericProperty\fP (const std::map< unsigned int, \fBT\fP > &list, const char *szName)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AI_GENERIC_PROPERTY_H_INCLUDED"

.SH "Function Documentation"
.PP 
.SS "template<class \fBT\fP > const \fBT\fP & GetGenericProperty (const std::map< unsigned int, \fBT\fP > & list, const char * szName, const \fBT\fP & errorReturn)\fR [inline]\fP"

.SS "template<class \fBT\fP > bool HasGenericProperty (const std::map< unsigned int, \fBT\fP > & list, const char * szName)\fR [inline]\fP"

.SS "template<class \fBT\fP > bool SetGenericProperty (std::map< unsigned int, \fBT\fP > & list, const char * szName, const \fBT\fP & value)\fR [inline]\fP"

.SS "template<class \fBT\fP > \fBvoid\fP SetGenericPropertyPtr (std::map< unsigned int, \fBT\fP * > & list, const char * szName, \fBT\fP * value, bool * bWasExisting = \fRnullptr\fP)\fR [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
