.TH "adhed/glm/geometric.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/geometric.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'detail/type_vec3\&.hpp'\fP
.br
\fR#include 'detail/func_geometric\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::length\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::distance\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &p0, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &p1)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBT\fP \fBglm::dot\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::cross\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::normalize\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::faceforward\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBN\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBI\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &Nref)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::reflect\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBI\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBN\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::refract\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBI\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBN\fP, \fBT\fP eta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCore features\fP
.PP
\fBSee also\fP
.RS 4
\fRGLSL 4\&.20\&.8 specification, section 8\&.5 Geometric Functions\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
