.TH "adhed/glm/gtx/gradient_paint.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/gradient_paint.inl
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::radialGradient\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &Center, \fBT\fP const &Radius, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &Focal, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &Position)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::linearGradient\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &Point0, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &Point1, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &Position)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
