.TH "packages/directxtk12_uwp.2024.6.5.1/include/GraphicsMemory.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/directxtk12_uwp.2024.6.5.1/include/GraphicsMemory.h
.SH SYNOPSIS
.br
.PP
\fR#include <d3d12\&.h>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDirectX::DX12::GraphicsResource\fP"
.br
.ti -1c
.RI "class \fBDirectX::DX12::SharedGraphicsResource\fP"
.br
.ti -1c
.RI "struct \fBDirectX::DX12::GraphicsMemoryStatistics\fP"
.br
.ti -1c
.RI "class \fBDirectX::DX12::GraphicsMemory\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDirectX\fP"
.br
.ti -1c
.RI "namespace \fBDirectX::DX12\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
