.TH "gtc_color_space" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_color_space \- GLM_GTC_color_space
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::convertLinearToSRGB\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &ColorLinear)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::convertLinearToSRGB\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &ColorLinear, \fBT\fP Gamma)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::convertSRGBToLinear\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &ColorSRGB)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::convertSRGBToLinear\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &ColorSRGB, \fBT\fP Gamma)"
.br
.RI "Convert a sRGB color to linear color using a custom gamma correction\&. "
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtc/color_space\&.hpp\fP> to use the features of this extension\&.
.PP
Allow to perform bit operations on integer values
.SH "Function Documentation"
.PP 
.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::convertLinearToSRGB (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & ColorLinear)"
Convert a linear color to sRGB color using a standard gamma correction\&. IEC 61966-2-1:1999 / Rec\&. 709 specification https://www.w3.org/Graphics/Color/srgb 
.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::convertLinearToSRGB (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & ColorLinear, \fBT\fP Gamma)"
Convert a linear color to sRGB color using a custom gamma correction\&. IEC 61966-2-1:1999 / Rec\&. 709 specification https://www.w3.org/Graphics/Color/srgb 
.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::convertSRGBToLinear (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & ColorSRGB)"
Convert a sRGB color to linear color using a standard gamma correction\&. IEC 61966-2-1:1999 / Rec\&. 709 specification https://www.w3.org/Graphics/Color/srgb 
.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::convertSRGBToLinear (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & ColorSRGB, \fBT\fP Gamma)"

.PP
Convert a sRGB color to linear color using a custom gamma correction\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
