.TH "gtc_round" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_round \- GLM_GTC_round
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType \fBglm::ceilPowerOfTwo\fP (genIUType \fBv\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::ceilPowerOfTwo\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType \fBglm::floorPowerOfTwo\fP (genIUType \fBv\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::floorPowerOfTwo\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType \fBglm::roundPowerOfTwo\fP (genIUType \fBv\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::roundPowerOfTwo\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::ceilMultiple\fP (genType \fBv\fP, genType Multiple)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::ceilMultiple\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &Multiple)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::floorMultiple\fP (genType \fBv\fP, genType Multiple)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::floorMultiple\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &Multiple)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::roundMultiple\fP (genType \fBv\fP, genType Multiple)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::roundMultiple\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &Multiple)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtc/round\&.hpp\fP> to use the features of this extension\&.
.PP
Rounding value to specific boundings
.SH "Function Documentation"
.PP 
.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::ceilMultiple (genType v, genType Multiple)"
Higher multiple number of Source\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP Floating-point or integer scalar or vector types\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIv\fP Source value to which is applied the function 
.br
\fIMultiple\fP Must be a null or positive value
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::ceilMultiple (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & v, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & Multiple)"
Higher multiple number of Source\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point or integer scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBParameters\fP
.RS 4
\fIv\fP Source values to which is applied the function 
.br
\fIMultiple\fP Must be a null or positive value
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType glm::ceilPowerOfTwo (genIUType v)"
Return the power of two number which value is just higher the input value, round up to a power of two\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::ceilPowerOfTwo (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & v)"
Return the power of two number which value is just higher the input value, round up to a power of two\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point or integer scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::floorMultiple (genType v, genType Multiple)"
Lower multiple number of Source\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP Floating-point or integer scalar or vector types\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIv\fP Source value to which is applied the function 
.br
\fIMultiple\fP Must be a null or positive value
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::floorMultiple (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & v, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & Multiple)"
Lower multiple number of Source\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point or integer scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBParameters\fP
.RS 4
\fIv\fP Source values to which is applied the function 
.br
\fIMultiple\fP Must be a null or positive value
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType glm::floorPowerOfTwo (genIUType v)"
Return the power of two number which value is just lower the input value, round down to a power of two\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::floorPowerOfTwo (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & v)"
Return the power of two number which value is just lower the input value, round down to a power of two\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point or integer scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::roundMultiple (genType v, genType Multiple)"
Lower multiple number of Source\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIgenType\fP Floating-point or integer scalar or vector types\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIv\fP Source value to which is applied the function 
.br
\fIMultiple\fP Must be a null or positive value
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::roundMultiple (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & v, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & Multiple)"
Lower multiple number of Source\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point or integer scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBParameters\fP
.RS 4
\fIv\fP Source values to which is applied the function 
.br
\fIMultiple\fP Must be a null or positive value
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType glm::roundPowerOfTwo (genIUType v)"
Return the power of two number which value is the closet to the input value\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::roundPowerOfTwo (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & v)"
Return the power of two number which value is the closet to the input value\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIL\fP Integer between 1 and 4 included that qualify the dimension of the vector 
.br
\fIT\fP Floating-point or integer scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
