.TH "gtc_type_ptr" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_type_ptr \- GLM_GTC_type_ptr
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType::value_type const * \fBglm::value_ptr\fP (genType const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::make_vec1\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::make_vec1\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::make_vec1\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::make_vec1\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::make_vec2\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::make_vec2\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::make_vec2\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::make_vec2\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::make_vec3\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::make_vec3\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::make_vec3\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::make_vec3\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::make_vec4\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::make_vec4\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::make_vec4\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::make_vec4\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBvec\fP< 2, \fBT\fP, \fBdefaultp\fP > \fBglm::make_vec2\fP (\fBT\fP const *const ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBdefaultp\fP > \fBglm::make_vec3\fP (\fBT\fP const *const ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, \fBT\fP, \fBdefaultp\fP > \fBglm::make_vec4\fP (\fBT\fP const *const ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 2, 2, \fBT\fP, \fBdefaultp\fP > \fBglm::make_mat2x2\fP (\fBT\fP const *const ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 2, 3, \fBT\fP, \fBdefaultp\fP > \fBglm::make_mat2x3\fP (\fBT\fP const *const ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 2, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::make_mat2x4\fP (\fBT\fP const *const ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 2, \fBT\fP, \fBdefaultp\fP > \fBglm::make_mat3x2\fP (\fBT\fP const *const ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBdefaultp\fP > \fBglm::make_mat3x3\fP (\fBT\fP const *const ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::make_mat3x4\fP (\fBT\fP const *const ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 2, \fBT\fP, \fBdefaultp\fP > \fBglm::make_mat4x2\fP (\fBT\fP const *const ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 3, \fBT\fP, \fBdefaultp\fP > \fBglm::make_mat4x3\fP (\fBT\fP const *const ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::make_mat4x4\fP (\fBT\fP const *const ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 2, 2, \fBT\fP, \fBdefaultp\fP > \fBglm::make_mat2\fP (\fBT\fP const *const ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBdefaultp\fP > \fBglm::make_mat3\fP (\fBT\fP const *const ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::make_mat4\fP (\fBT\fP const *const ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBdefaultp\fP > \fBglm::make_quat\fP (\fBT\fP const *const ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const * \fBglm::value_ptr\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * \fBglm::value_ptr\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const * \fBglm::value_ptr\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * \fBglm::value_ptr\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const * \fBglm::value_ptr\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * \fBglm::value_ptr\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const * \fBglm::value_ptr\fP (\fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * \fBglm::value_ptr\fP (\fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const * \fBglm::value_ptr\fP (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * \fBglm::value_ptr\fP (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const * \fBglm::value_ptr\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * \fBglm::value_ptr\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const * \fBglm::value_ptr\fP (\fBmat\fP< 2, 3, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * \fBglm::value_ptr\fP (\fBmat\fP< 2, 3, \fBT\fP, \fBQ\fP > &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const * \fBglm::value_ptr\fP (\fBmat\fP< 3, 2, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * \fBglm::value_ptr\fP (\fBmat\fP< 3, 2, \fBT\fP, \fBQ\fP > &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const * \fBglm::value_ptr\fP (\fBmat\fP< 2, 4, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * \fBglm::value_ptr\fP (\fBmat\fP< 2, 4, \fBT\fP, \fBQ\fP > &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const * \fBglm::value_ptr\fP (\fBmat\fP< 4, 2, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * \fBglm::value_ptr\fP (\fBmat\fP< 4, 2, \fBT\fP, \fBQ\fP > &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const * \fBglm::value_ptr\fP (\fBmat\fP< 3, 4, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * \fBglm::value_ptr\fP (\fBmat\fP< 3, 4, \fBT\fP, \fBQ\fP > &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const * \fBglm::value_ptr\fP (\fBmat\fP< 4, 3, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * \fBglm::value_ptr\fP (\fBmat\fP< 4, 3, \fBT\fP, \fBQ\fP > &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const * \fBglm::value_ptr\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &q)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * \fBglm::value_ptr\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > &q)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtc/type_ptr\&.hpp\fP> to use the features of this extension\&.
.PP
Handles the interaction between pointers and vector, matrix types\&.
.PP
This extension defines an overloaded function, \fBglm::value_ptr\fP\&. It returns a pointer to the memory layout of the object\&. Matrix types store their values in column-major order\&.
.PP
This is useful for uploading data to matrices or copying data to buffer objects\&.
.PP
Example: 
.PP
.nf
#include <glm/glm\&.hpp>
#include <glm/gtc/type_ptr\&.hpp>

glm::vec3 aVector(3);
glm::mat4 someMatrix(1\&.0);

glUniform3fv(uniformLoc, 1, glm::value_ptr(aVector));
glUniformMatrix4fv(uniformMatrixLoc, 1, GL_FALSE, glm::value_ptr(someMatrix));

.fi
.PP
.PP
<\fBglm/gtc/type_ptr\&.hpp\fP> need to be included to use the features of this extension\&.
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 2, 2, \fBT\fP, \fBdefaultp\fP > glm::make_mat2 (\fBT\fP const *const ptr)"
Build a matrix from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 2, 2, \fBT\fP, \fBdefaultp\fP > glm::make_mat2x2 (\fBT\fP const *const ptr)"
Build a matrix from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 2, 3, \fBT\fP, \fBdefaultp\fP > glm::make_mat2x3 (\fBT\fP const *const ptr)"
Build a matrix from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 2, 4, \fBT\fP, \fBdefaultp\fP > glm::make_mat2x4 (\fBT\fP const *const ptr)"
Build a matrix from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBdefaultp\fP > glm::make_mat3 (\fBT\fP const *const ptr)"
Build a matrix from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 2, \fBT\fP, \fBdefaultp\fP > glm::make_mat3x2 (\fBT\fP const *const ptr)"
Build a matrix from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBdefaultp\fP > glm::make_mat3x3 (\fBT\fP const *const ptr)"
Build a matrix from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 4, \fBT\fP, \fBdefaultp\fP > glm::make_mat3x4 (\fBT\fP const *const ptr)"
Build a matrix from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::make_mat4 (\fBT\fP const *const ptr)"
Build a matrix from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 2, \fBT\fP, \fBdefaultp\fP > glm::make_mat4x2 (\fBT\fP const *const ptr)"
Build a matrix from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 3, \fBT\fP, \fBdefaultp\fP > glm::make_mat4x3 (\fBT\fP const *const ptr)"
Build a matrix from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::make_mat4x4 (\fBT\fP const *const ptr)"
Build a matrix from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBdefaultp\fP > glm::make_quat (\fBT\fP const *const ptr)"
Build a quaternion from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > glm::make_vec1 (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const & v)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > glm::make_vec1 (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & v)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > glm::make_vec1 (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > glm::make_vec1 (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const & v)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBvec\fP< 2, \fBT\fP, \fBdefaultp\fP > glm::make_vec2 (\fBT\fP const *const ptr)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 2, \fBT\fP, \fBQ\fP > glm::make_vec2 (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const & v)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 2, \fBT\fP, \fBQ\fP > glm::make_vec2 (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & v)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 2, \fBT\fP, \fBQ\fP > glm::make_vec2 (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 2, \fBT\fP, \fBQ\fP > glm::make_vec2 (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const & v)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBdefaultp\fP > glm::make_vec3 (\fBT\fP const *const ptr)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::make_vec3 (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const & v)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::make_vec3 (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & v)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::make_vec3 (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::make_vec3 (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const & v)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, \fBT\fP, \fBdefaultp\fP > glm::make_vec4 (\fBT\fP const *const ptr)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > glm::make_vec4 (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const & v)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > glm::make_vec4 (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & v)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > glm::make_vec4 (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > glm::make_vec4 (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const & v)"
Build a vector from a pointer\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType::value_type const  * glm::value_ptr (genType const & v)"
Return the constant address to the data of the input parameter\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_type_ptr\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * glm::value_ptr (\fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const  * glm::value_ptr (\fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > const & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * glm::value_ptr (\fBmat\fP< 2, 3, \fBT\fP, \fBQ\fP > & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const  * glm::value_ptr (\fBmat\fP< 2, 3, \fBT\fP, \fBQ\fP > const & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * glm::value_ptr (\fBmat\fP< 2, 4, \fBT\fP, \fBQ\fP > & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const  * glm::value_ptr (\fBmat\fP< 2, 4, \fBT\fP, \fBQ\fP > const & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * glm::value_ptr (\fBmat\fP< 3, 2, \fBT\fP, \fBQ\fP > & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const  * glm::value_ptr (\fBmat\fP< 3, 2, \fBT\fP, \fBQ\fP > const & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * glm::value_ptr (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const  * glm::value_ptr (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * glm::value_ptr (\fBmat\fP< 3, 4, \fBT\fP, \fBQ\fP > & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const  * glm::value_ptr (\fBmat\fP< 3, 4, \fBT\fP, \fBQ\fP > const & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * glm::value_ptr (\fBmat\fP< 4, 2, \fBT\fP, \fBQ\fP > & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const  * glm::value_ptr (\fBmat\fP< 4, 2, \fBT\fP, \fBQ\fP > const & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * glm::value_ptr (\fBmat\fP< 4, 3, \fBT\fP, \fBQ\fP > & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const  * glm::value_ptr (\fBmat\fP< 4, 3, \fBT\fP, \fBQ\fP > const & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * glm::value_ptr (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const  * glm::value_ptr (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & m)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * glm::value_ptr (\fBqua\fP< \fBT\fP, \fBQ\fP > & q)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const  * glm::value_ptr (\fBqua\fP< \fBT\fP, \fBQ\fP > const & q)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * glm::value_ptr (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > & v)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const  * glm::value_ptr (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & v)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * glm::value_ptr (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > & v)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const  * glm::value_ptr (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP * glm::value_ptr (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > & v)"

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP const  * glm::value_ptr (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const & v)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
