.TH "gtc_quaternion" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_quaternion \- GLM_GTC_quaternion
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::eulerAngles\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::roll\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::pitch\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::yaw\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > \fBglm::mat3_cast\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::mat4_cast\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > \fBglm::quat_cast\fP (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > \fBglm::quat_cast\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, bool, \fBQ\fP > \fBglm::lessThan\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, bool, \fBQ\fP > \fBglm::lessThanEqual\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, bool, \fBQ\fP > \fBglm::greaterThan\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, bool, \fBQ\fP > \fBglm::greaterThanEqual\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > \fBglm::quatLookAt\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &direction, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &up)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > \fBglm::quatLookAtRH\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &direction, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &up)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > \fBglm::quatLookAtLH\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &direction, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &up)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtc/quaternion\&.hpp\fP> to use the features of this extension\&.
.PP
Defines a templated quaternion type and several quaternion operations\&.
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::eulerAngles (\fBqua\fP< \fBT\fP, \fBQ\fP > const & x)"
Returns euler angles, pitch as x, yaw as y, roll as z\&. The result is expressed in radians\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, bool, \fBQ\fP > glm::greaterThan (\fBqua\fP< \fBT\fP, \fBQ\fP > const & x, \fBqua\fP< \fBT\fP, \fBQ\fP > const & y)"
Returns the component-wise comparison of result x > y\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_quaternion_relational\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, bool, \fBQ\fP > glm::greaterThanEqual (\fBqua\fP< \fBT\fP, \fBQ\fP > const & x, \fBqua\fP< \fBT\fP, \fBQ\fP > const & y)"
Returns the component-wise comparison of result x >= y\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_quaternion_relational\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, bool, \fBQ\fP > glm::lessThan (\fBqua\fP< \fBT\fP, \fBQ\fP > const & x, \fBqua\fP< \fBT\fP, \fBQ\fP > const & y)"
Returns the component-wise comparison result of x < y\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_quaternion_relational\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, bool, \fBQ\fP > glm::lessThanEqual (\fBqua\fP< \fBT\fP, \fBQ\fP > const & x, \fBqua\fP< \fBT\fP, \fBQ\fP > const & y)"
Returns the component-wise comparison of result x <= y\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_EXT_quaternion_relational\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > glm::mat3_cast (\fBqua\fP< \fBT\fP, \fBQ\fP > const & x)"
Converts a quaternion to a 3 * 3 matrix\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::mat4_cast (\fBqua\fP< \fBT\fP, \fBQ\fP > const & x)"
Converts a quaternion to a 4 * 4 matrix\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::pitch (\fBqua\fP< \fBT\fP, \fBQ\fP > const & x)"
Returns pitch value of euler angles expressed in radians\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > glm::quat_cast (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const & x)"
Converts a pure rotation 3 * 3 matrix to a quaternion\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > glm::quat_cast (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & x)"
Converts a pure rotation 4 * 4 matrix to a quaternion\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > glm::quatLookAt (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & direction, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & up)"
Build a look at quaternion based on the default handedness\&.
.PP
\fBParameters\fP
.RS 4
\fIdirection\fP Desired forward direction\&. \fBNeeds\fP to be normalized\&. 
.br
\fIup\fP Up vector, how the camera is oriented\&. Typically (0, 1, 0)\&. 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > glm::quatLookAtLH (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & direction, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & up)"
Build a left-handed look at quaternion\&.
.PP
\fBParameters\fP
.RS 4
\fIdirection\fP Desired forward direction onto which the +z-axis gets mapped\&. \fBNeeds\fP to be normalized\&. 
.br
\fIup\fP Up vector, how the camera is oriented\&. Typically (0, 1, 0)\&. 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > glm::quatLookAtRH (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & direction, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & up)"
Build a right-handed look at quaternion\&.
.PP
\fBParameters\fP
.RS 4
\fIdirection\fP Desired forward direction onto which the -z-axis gets mapped\&. \fBNeeds\fP to be normalized\&. 
.br
\fIup\fP Up vector, how the camera is oriented\&. Typically (0, 1, 0)\&. 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::roll (\fBqua\fP< \fBT\fP, \fBQ\fP > const & x)"
Returns roll value of euler angles expressed in radians\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::yaw (\fBqua\fP< \fBT\fP, \fBQ\fP > const & x)"
Returns yaw value of euler angles expressed in radians\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
