.TH "gtx_normalize_dot" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_normalize_dot \- GLM_GTX_normalize_dot
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::normalizeDot\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::fastNormalizeDot\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/normalize_dot\&.hpp\fP> to use the features of this extension\&.
.PP
Dot product of vectors that need to be normalize with a single square root\&.
.SH "Function Documentation"
.PP 
.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::fastNormalizeDot (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y)"
Normalize parameters and returns the dot product of x and y\&. Faster that dot(fastNormalize(x), fastNormalize(y))\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_normalize_dot\fP extension\&. 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::normalizeDot (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y)"
Normalize parameters and returns the dot product of x and y\&. It's faster that dot(normalize(x), normalize(y))\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_normalize_dot\fP extension\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
