.TH "gtx_matrix_interpolation" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_matrix_interpolation \- GLM_GTX_matrix_interpolation
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP \fBvoid\fP \fBglm::axisAngle\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &Mat, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > &Axis, \fBT\fP &Angle)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::axisAngleMatrix\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &Axis, \fBT\fP const Angle)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::extractMatrixRotation\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &Mat)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::interpolate\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m1, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m2, \fBT\fP const Delta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/matrix_interpolation\&.hpp\fP> to use the features of this extension\&.
.PP
Allows to directly interpolate two matrices\&.
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP \fBvoid\fP glm::axisAngle (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & Mat, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > & Axis, \fBT\fP & Angle)"
Get the axis and angle of the rotation from a matrix\&. From GLM_GTX_matrix_interpolation extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::axisAngleMatrix (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & Axis, \fBT\fP const Angle)"
Build a matrix from axis and angle\&. From GLM_GTX_matrix_interpolation extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::extractMatrixRotation (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & Mat)"
Extracts the rotation part of a matrix\&. From GLM_GTX_matrix_interpolation extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::interpolate (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & m1, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & m2, \fBT\fP const Delta)"
Build a interpolation of 4 * 4 matrixes\&. From GLM_GTX_matrix_interpolation extension\&. Warning! works only with rotation and/or translation matrixes, scale will generate unexpected results\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
