.TH "gtx_normal" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_normal \- GLM_GTX_normal
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::triangleNormal\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &p1, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &p2, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &p3)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/normal\&.hpp\fP> to use the features of this extension\&.
.PP
Compute the normal of a triangle\&.
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::triangleNormal (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & p1, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & p2, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & p3)"
Computes triangle normal from triangle points\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_normal\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
