.TH "gtx_quaternion" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_quaternion \- GLM_GTX_quaternion
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBqua\fP< \fBT\fP, \fBQ\fP > \fBglm::quat_identity\fP ()"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::cross\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &q, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::cross\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBqua\fP< \fBT\fP, \fBQ\fP > const &q)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > \fBglm::squad\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &q1, \fBqua\fP< \fBT\fP, \fBQ\fP > const &q2, \fBqua\fP< \fBT\fP, \fBQ\fP > const &s1, \fBqua\fP< \fBT\fP, \fBQ\fP > const &s2, \fBT\fP const &h)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > \fBglm::intermediate\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &prev, \fBqua\fP< \fBT\fP, \fBQ\fP > const &curr, \fBqua\fP< \fBT\fP, \fBQ\fP > const &next)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::rotate\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &q, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::rotate\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &q, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::extractRealComponent\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &q)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > \fBglm::toMat3\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::toMat4\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBqua\fP< \fBT\fP, \fBQ\fP > \fBglm::toQuat\fP (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBqua\fP< \fBT\fP, \fBQ\fP > \fBglm::toQuat\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > \fBglm::shortMix\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBT\fP const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > \fBglm::fastMix\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBT\fP const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > \fBglm::rotation\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &orig, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &dest)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBT\fP \fBglm::length2\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &q)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/quaternion\&.hpp\fP> to use the features of this extension\&.
.PP
Extended quaternion types and functions
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::cross (\fBqua\fP< \fBT\fP, \fBQ\fP > const & q, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v)"
Compute a cross product between a quaternion and a vector\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::cross (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v, \fBqua\fP< \fBT\fP, \fBQ\fP > const & q)"
Compute a cross product between a vector and a quaternion\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::extractRealComponent (\fBqua\fP< \fBT\fP, \fBQ\fP > const & q)"
Extract the real component of a quaternion\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > glm::fastMix (\fBqua\fP< \fBT\fP, \fBQ\fP > const & x, \fBqua\fP< \fBT\fP, \fBQ\fP > const & y, \fBT\fP const & a)"
Quaternion normalized linear interpolation\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > glm::intermediate (\fBqua\fP< \fBT\fP, \fBQ\fP > const & prev, \fBqua\fP< \fBT\fP, \fBQ\fP > const & curr, \fBqua\fP< \fBT\fP, \fBQ\fP > const & next)"
Returns an intermediate control point for squad interpolation\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBT\fP glm::length2 (\fBqua\fP< \fBT\fP, \fBQ\fP > const & q)"
Returns the squared length of x\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBqua\fP< \fBT\fP, \fBQ\fP > glm::quat_identity ()"
Create an identity quaternion\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::rotate (\fBqua\fP< \fBT\fP, \fBQ\fP > const & q, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v)"
Returns quarternion square root\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_quaternion\fP Rotates \fBa\fP 3 \fBcomponents\fP vector by \fBa\fP quaternion\&.
.PP
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > glm::rotate (\fBqua\fP< \fBT\fP, \fBQ\fP > const & q, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const & v)"
Rotates a 4 components vector by a quaternion\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > glm::rotation (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & orig, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & dest)"
Compute the rotation between two vectors\&. 
.PP
\fBParameters\fP
.RS 4
\fIorig\fP vector, needs to be normalized 
.br
\fIdest\fP vector, needs to be normalized
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > glm::shortMix (\fBqua\fP< \fBT\fP, \fBQ\fP > const & x, \fBqua\fP< \fBT\fP, \fBQ\fP > const & y, \fBT\fP const & a)"
Quaternion interpolation using the rotation short path\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBqua\fP< \fBT\fP, \fBQ\fP > glm::squad (\fBqua\fP< \fBT\fP, \fBQ\fP > const & q1, \fBqua\fP< \fBT\fP, \fBQ\fP > const & q2, \fBqua\fP< \fBT\fP, \fBQ\fP > const & s1, \fBqua\fP< \fBT\fP, \fBQ\fP > const & s2, \fBT\fP const & h)"
Compute a point on a path according squad equation\&. q1 and q2 are control points; s1 and s2 are intermediate control points\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > glm::toMat3 (\fBqua\fP< \fBT\fP, \fBQ\fP > const & x)"
Converts a quaternion to a 3 * 3 matrix\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::toMat4 (\fBqua\fP< \fBT\fP, \fBQ\fP > const & x)"
Converts a quaternion to a 4 * 4 matrix\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBqua\fP< \fBT\fP, \fBQ\fP > glm::toQuat (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const & x)"
Converts a 3 * 3 matrix to a quaternion\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBqua\fP< \fBT\fP, \fBQ\fP > glm::toQuat (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & x)"
Converts a 4 * 4 matrix to a quaternion\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
