.TH "gtx_matrix_major_storage" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_matrix_major_storage \- GLM_GTX_matrix_major_storage
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > \fBglm::rowMajor2\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > \fBglm::rowMajor2\fP (\fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > \fBglm::rowMajor3\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv2\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv3\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > \fBglm::rowMajor3\fP (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::rowMajor4\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv3\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &v4)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::rowMajor4\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > \fBglm::colMajor2\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > \fBglm::colMajor2\fP (\fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > \fBglm::colMajor3\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv2\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv3\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > \fBglm::colMajor3\fP (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::colMajor4\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv3\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &v4)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::colMajor4\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/matrix_major_storage\&.hpp\fP> to use the features of this extension\&.
.PP
Build matrices with specific matrix order, row or column
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > glm::colMajor2 (\fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > const & m)"
Build a column major matrix from other matrix\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > glm::colMajor2 (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & v1, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & v2)"
Build a column major matrix from column vectors\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > glm::colMajor3 (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const & m)"
Build a column major matrix from other matrix\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > glm::colMajor3 (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v1, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v2, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v3)"
Build a column major matrix from column vectors\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::colMajor4 (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & m)"
Build a column major matrix from other matrix\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::colMajor4 (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const & v1, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const & v2, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const & v3, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const & v4)"
Build a column major matrix from column vectors\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > glm::rowMajor2 (\fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > const & m)"
Build a row major matrix from other matrix\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > glm::rowMajor2 (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & v1, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & v2)"
Build a row major matrix from row vectors\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > glm::rowMajor3 (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const & m)"
Build a row major matrix from other matrix\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > glm::rowMajor3 (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v1, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v2, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v3)"
Build a row major matrix from row vectors\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::rowMajor4 (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & m)"
Build a row major matrix from other matrix\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::rowMajor4 (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const & v1, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const & v2, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const & v3, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const & v4)"
Build a row major matrix from row vectors\&. From GLM_GTX_matrix_major_storage extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
