.TH "gtx_associated_min_max" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_associated_min_max \- GLM_GTX_associated_min_max
.PP
 \- Min and max functions that return associated values not the compared ones\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP \fBglm::associatedMin\fP (\fBT\fP \fBx\fP, \fBU\fP \fBa\fP, \fBT\fP \fBy\fP, \fBU\fP \fBb\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMin\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMin\fP (\fBT\fP \fBx\fP, const \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > &\fBa\fP, \fBT\fP \fBy\fP, const \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > &\fBb\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMin\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBU\fP \fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBU\fP \fBb\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP \fBglm::associatedMin\fP (\fBT\fP \fBx\fP, \fBU\fP \fBa\fP, \fBT\fP \fBy\fP, \fBU\fP \fBb\fP, \fBT\fP \fBz\fP, \fBU\fP c)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMin\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBz\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &c)"
.br
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP \fBglm::associatedMin\fP (\fBT\fP \fBx\fP, \fBU\fP \fBa\fP, \fBT\fP \fBy\fP, \fBU\fP \fBb\fP, \fBT\fP \fBz\fP, \fBU\fP c, \fBT\fP \fBw\fP, \fBU\fP d)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMin\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBz\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &c, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBw\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &d)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMin\fP (\fBT\fP \fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBT\fP \fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP, \fBT\fP \fBz\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &c, \fBT\fP \fBw\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &d)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMin\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBU\fP \fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBU\fP \fBb\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBz\fP, \fBU\fP c, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBw\fP, \fBU\fP d)"
.br
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP \fBglm::associatedMax\fP (\fBT\fP \fBx\fP, \fBU\fP \fBa\fP, \fBT\fP \fBy\fP, \fBU\fP \fBb\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBT\fP \fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBT\fP \fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBU\fP \fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBU\fP \fBb\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP \fBglm::associatedMax\fP (\fBT\fP \fBx\fP, \fBU\fP \fBa\fP, \fBT\fP \fBy\fP, \fBU\fP \fBb\fP, \fBT\fP \fBz\fP, \fBU\fP c)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBz\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &c)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBT\fP \fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBT\fP \fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP, \fBT\fP \fBz\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &c)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBU\fP \fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBU\fP \fBb\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBz\fP, \fBU\fP c)"
.br
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP \fBglm::associatedMax\fP (\fBT\fP \fBx\fP, \fBU\fP \fBa\fP, \fBT\fP \fBy\fP, \fBU\fP \fBb\fP, \fBT\fP \fBz\fP, \fBU\fP c, \fBT\fP \fBw\fP, \fBU\fP d)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBz\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &c, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBw\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &d)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBT\fP \fBx\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBa\fP, \fBT\fP \fBy\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &\fBb\fP, \fBT\fP \fBz\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &c, \fBT\fP \fBw\fP, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const &d)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > \fBglm::associatedMax\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBU\fP \fBa\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBU\fP \fBb\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBz\fP, \fBU\fP c, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBw\fP, \fBU\fP d)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Min and max functions that return associated values not the compared ones\&. 

Include <\fBglm/gtx/associated_min_max\&.hpp\fP> to use the features of this extension\&.
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP glm::associatedMax (\fBT\fP x, \fBU\fP a, \fBT\fP y, \fBU\fP b)"
Maximum comparison between 2 variables and returns 2 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP glm::associatedMax (\fBT\fP x, \fBU\fP a, \fBT\fP y, \fBU\fP b, \fBT\fP z, \fBU\fP c)"
Maximum comparison between 3 variables and returns 3 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP glm::associatedMax (\fBT\fP x, \fBU\fP a, \fBT\fP y, \fBU\fP b, \fBT\fP z, \fBU\fP c, \fBT\fP w, \fBU\fP d)"
Maximum comparison between 4 variables and returns 4 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::associatedMax (\fBT\fP x, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & a, \fBT\fP y, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & b)"
Maximum comparison between 2 variables and returns 2 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::associatedMax (\fBT\fP x, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & a, \fBT\fP y, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & b, \fBT\fP z, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & c)"
Maximum comparison between 3 variables and returns 3 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > glm::associatedMax (\fBT\fP x, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & a, \fBT\fP y, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & b, \fBT\fP z, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & c, \fBT\fP w, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & d)"
Maximum comparison between 4 variables and returns 4 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > glm::associatedMax (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBU\fP a, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y, \fBU\fP b)"
Maximum comparison between 2 variables and returns 2 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > glm::associatedMax (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBU\fP a, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y, \fBU\fP b, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & z, \fBU\fP c)"
Maximum comparison between 3 variables and returns 3 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > glm::associatedMax (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBU\fP a, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y, \fBU\fP b, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & z, \fBU\fP c, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & w, \fBU\fP d)"
Maximum comparison between 4 variables and returns 4 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > glm::associatedMax (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & a, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & b)"
Maximum comparison between 2 variables and returns 2 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > glm::associatedMax (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & a, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & b, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & z, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & c)"
Maximum comparison between 3 variables and returns 3 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > glm::associatedMax (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & a, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & b, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & z, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & c, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & w, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & d)"
Maximum comparison between 4 variables and returns 4 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > glm::associatedMin (\fBT\fP x, const \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > & a, \fBT\fP y, const \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > & b)"
Minimum comparison between 2 variables and returns 2 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP glm::associatedMin (\fBT\fP x, \fBU\fP a, \fBT\fP y, \fBU\fP b)"
Minimum comparison between 2 variables and returns 2 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP glm::associatedMin (\fBT\fP x, \fBU\fP a, \fBT\fP y, \fBU\fP b, \fBT\fP z, \fBU\fP c)"
Minimum comparison between 3 variables and returns 3 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<typename \fBT\fP , typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBU\fP glm::associatedMin (\fBT\fP x, \fBU\fP a, \fBT\fP y, \fBU\fP b, \fBT\fP z, \fBU\fP c, \fBT\fP w, \fBU\fP d)"
Minimum comparison between 4 variables and returns 4 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > glm::associatedMin (\fBT\fP x, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & a, \fBT\fP y, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & b, \fBT\fP z, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & c, \fBT\fP w, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & d)"
Minimum comparison between 4 variables and returns 4 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > glm::associatedMin (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBU\fP a, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y, \fBU\fP b)"
Minimum comparison between 2 variables and returns 2 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > glm::associatedMin (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBU\fP a, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y, \fBU\fP b, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & z, \fBU\fP c, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & w, \fBU\fP d)"
Minimum comparison between 4 variables and returns 4 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > glm::associatedMin (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & a, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & b)"
Minimum comparison between 2 variables and returns 2 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > glm::associatedMin (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & a, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & b, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & z, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & c)"
Minimum comparison between 3 variables and returns 3 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > glm::associatedMin (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & a, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & y, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & b, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & z, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & c, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & w, \fBvec\fP< \fBL\fP, \fBU\fP, \fBQ\fP > const & d)"
Minimum comparison between 4 variables and returns 4 associated variable values 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
