.TH "gtx_exterior_product" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_exterior_product \- GLM_GTX_exterior_product
.PP
 \- Allow to perform bit operations on integer values\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBT\fP \fBglm::cross\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &u)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allow to perform bit operations on integer values\&. 

Include <\fBglm/gtx/exterior_product\&.hpp\fP> to use the features of this extension\&.
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBT\fP glm::cross (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & v, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & u)"
Returns the cross product of x and y\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also\fP
.RS 4
\fRExterior product\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
