.TH "gtx_bit" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_bit \- GLM_GTX_bit
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType \fBglm::highestBitValue\fP (genIUType \fBValue\fP)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType \fBglm::lowestBitValue\fP (genIUType \fBValue\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::highestBitValue\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBvalue\fP)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_DEPRECATED\fP \fBGLM_FUNC_DECL\fP genIUType \fBglm::powerOfTwoAbove\fP (genIUType \fBValue\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_DEPRECATED\fP \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::powerOfTwoAbove\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBvalue\fP)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_DEPRECATED\fP \fBGLM_FUNC_DECL\fP genIUType \fBglm::powerOfTwoBelow\fP (genIUType \fBValue\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_DEPRECATED\fP \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::powerOfTwoBelow\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBvalue\fP)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_DEPRECATED\fP \fBGLM_FUNC_DECL\fP genIUType \fBglm::powerOfTwoNearest\fP (genIUType \fBValue\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_DEPRECATED\fP \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::powerOfTwoNearest\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBvalue\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/bit\&.hpp\fP> to use the features of this extension\&.
.PP
Allow to perform bit operations on integer values
.SH "Function Documentation"
.PP 
.SS "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType glm::highestBitValue (genIUType Value)"

.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::highestBitValue (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & value)"
Find the highest bit set to 1 in a integer variable and return its value\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType glm::lowestBitValue (genIUType Value)"

.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<typename genIUType > \fBGLM_DEPRECATED\fP \fBGLM_FUNC_DECL\fP genIUType glm::powerOfTwoAbove (genIUType Value)"
Return the power of two number which value is just higher the input value\&. Deprecated, use ceilPowerOfTwo from GTC_round instead
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_DEPRECATED\fP \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::powerOfTwoAbove (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & value)"
Return the power of two number which value is just higher the input value\&. Deprecated, use ceilPowerOfTwo from GTC_round instead
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<typename genIUType > \fBGLM_DEPRECATED\fP \fBGLM_FUNC_DECL\fP genIUType glm::powerOfTwoBelow (genIUType Value)"
Return the power of two number which value is just lower the input value\&. Deprecated, use floorPowerOfTwo from GTC_round instead
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_DEPRECATED\fP \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::powerOfTwoBelow (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & value)"
Return the power of two number which value is just lower the input value\&. Deprecated, use floorPowerOfTwo from GTC_round instead
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<typename genIUType > \fBGLM_DEPRECATED\fP \fBGLM_FUNC_DECL\fP genIUType glm::powerOfTwoNearest (genIUType Value)"
Return the power of two number which value is the closet to the input value\&. Deprecated, use roundPowerOfTwo from GTC_round instead
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_DEPRECATED\fP \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::powerOfTwoNearest (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & value)"
Return the power of two number which value is the closet to the input value\&. Deprecated, use roundPowerOfTwo from GTC_round instead
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTC_round\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
