.TH "gtx_color_space_YCoCg" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_color_space_YCoCg \- GLM_GTX_color_space_YCoCg
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::rgb2YCoCg\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBrgbColor\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::YCoCg2rgb\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &YCoCgColor)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::rgb2YCoCgR\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBrgbColor\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::YCoCgR2rgb\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &YCoCgColor)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/color_space_YCoCg\&.hpp\fP> to use the features of this extension\&.
.PP
RGB to YCoCg conversions and operations
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::rgb2YCoCg (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & rgbColor)"
Convert a color from RGB color space to YCoCg color space\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_color_space_YCoCg\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::rgb2YCoCgR (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & rgbColor)"
Convert a color from RGB color space to YCoCgR color space\&. 
.PP
\fBSee also\fP
.RS 4
'YCoCg-R: A Color Space with RGB Reversibility and Low Dynamic Range' 
.PP
\fBGLM_GTX_color_space_YCoCg\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::YCoCg2rgb (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & YCoCgColor)"
Convert a color from YCoCg color space to RGB color space\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_color_space_YCoCg\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::YCoCgR2rgb (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & YCoCgColor)"
Convert a color from YCoCgR color space to RGB color space\&. 
.PP
\fBSee also\fP
.RS 4
'YCoCg-R: A Color Space with RGB Reversibility and Low Dynamic Range' 
.PP
\fBGLM_GTX_color_space_YCoCg\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
