.TH "gtx_transform2" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_transform2 \- GLM_GTX_transform2
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > \fBglm::shearX2D\fP (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const &m, \fBT\fP \fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > \fBglm::shearY2D\fP (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const &m, \fBT\fP \fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::shearX3D\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBT\fP \fBy\fP, \fBT\fP \fBz\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::shearY3D\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBT\fP \fBx\fP, \fBT\fP \fBz\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::shearZ3D\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBT\fP \fBx\fP, \fBT\fP \fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > \fBglm::proj2D\fP (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const &m, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &normal)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::proj3D\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &normal)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::scaleBias\fP (\fBT\fP \fBscale\fP, \fBT\fP bias)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::scaleBias\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBT\fP \fBscale\fP, \fBT\fP bias)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/transform2\&.hpp\fP> to use the features of this extension\&.
.PP
Add extra transformation matrices
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > glm::proj2D (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const & m, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & normal)"
Build planar projection matrix along normal axis\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::proj3D (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & m, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & normal)"
Build planar projection matrix along normal axis\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::scaleBias (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & m, \fBT\fP scale, \fBT\fP bias)"
Build a scale bias matrix\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::scaleBias (\fBT\fP scale, \fBT\fP bias)"
Build a scale bias matrix\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > glm::shearX2D (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const & m, \fBT\fP y)"
Transforms a matrix with a shearing on X axis\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::shearX3D (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & m, \fBT\fP y, \fBT\fP z)"
Transforms a matrix with a shearing on X axis From GLM_GTX_transform2 extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > glm::shearY2D (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const & m, \fBT\fP x)"
Transforms a matrix with a shearing on Y axis\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::shearY3D (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & m, \fBT\fP x, \fBT\fP z)"
Transforms a matrix with a shearing on Y axis\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > glm::shearZ3D (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const & m, \fBT\fP x, \fBT\fP y)"
Transforms a matrix with a shearing on Z axis\&. From GLM_GTX_transform2 extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
