.TH "gtx_gradient_paint" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_gradient_paint \- GLM_GTX_gradient_paint
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::radialGradient\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &Center, \fBT\fP const &Radius, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &Focal, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &Position)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::linearGradient\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &Point0, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &Point1, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &Position)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/gradient_paint\&.hpp\fP> to use the features of this extension\&.
.PP
Functions that return the color of procedural gradient for specific coordinates\&.
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::linearGradient (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & Point0, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & Point1, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & Position)"
Return a color from a linear gradient\&. 
.PP
\fBSee also\fP
.RS 4
- \fBGLM_GTX_gradient_paint\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::radialGradient (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & Center, \fBT\fP const & Radius, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & Focal, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & Position)"
Return a color from a radial gradient\&. 
.PP
\fBSee also\fP
.RS 4
- \fBGLM_GTX_gradient_paint\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
