.TH "gtx_norm" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_norm \- GLM_GTX_norm
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::length2\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::distance2\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &p0, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &p1)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::l1Norm\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::l1Norm\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::l2Norm\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::l2Norm\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::lxNorm\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBy\fP, unsigned int Depth)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::lxNorm\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBx\fP, unsigned int Depth)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::lMaxNorm\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::lMaxNorm\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/norm\&.hpp\fP> to use the features of this extension\&.
.PP
Various ways to compute vector norms\&.
.SH "Function Documentation"
.PP 
.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::distance2 (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & p0, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & p1)"
Returns the squared distance between p0 and p1, i\&.e\&., length2(p0 - p1)\&. From GLM_GTX_norm extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::l1Norm (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v)"
Returns the L1 norm of v\&. From GLM_GTX_norm extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::l1Norm (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & y)"
Returns the L1 norm between x and y\&. From GLM_GTX_norm extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::l2Norm (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & x)"
Returns the L2 norm of v\&. From GLM_GTX_norm extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::l2Norm (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & y)"
Returns the L2 norm between x and y\&. From GLM_GTX_norm extension\&. 
.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::length2 (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x)"
Returns the squared length of x\&. From GLM_GTX_norm extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::lMaxNorm (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & x)"
Returns the LMax norm of v\&. From GLM_GTX_norm extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::lMaxNorm (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & y)"
Returns the LMax norm between x and y\&. From GLM_GTX_norm extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::lxNorm (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & x, unsigned int Depth)"
Returns the L norm of v\&. From GLM_GTX_norm extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::lxNorm (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & y, unsigned int Depth)"
Returns the L norm between x and y\&. From GLM_GTX_norm extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
