.TH "gtx_mixed_product" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_mixed_product \- GLM_GTX_mixed_producte
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::mixedProduct\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv2\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv3\fP)"
.br
.RI "Mixed product of 3 vectors (from GLM_GTX_mixed_product extension) "
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/mixed_product\&.hpp\fP> to use the features of this extension\&.
.PP
Mixed product of 3 vectors\&.
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::mixedProduct (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v1, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v2, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & v3)"

.PP
Mixed product of 3 vectors (from GLM_GTX_mixed_product extension) 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
