.TH "gtx_handed_coordinate_space" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_handed_coordinate_space \- GLM_GTX_handed_coordinate_space
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP bool \fBglm::rightHanded\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &tangent, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &binormal, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &normal)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP bool \fBglm::leftHanded\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &tangent, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &binormal, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &normal)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/handed_coordinate_space\&.hpp\fP> to use the features of this extension\&.
.PP
To know if a set of three basis vectors defines a right or left-handed coordinate system\&.
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP bool glm::leftHanded (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & tangent, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & binormal, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & normal)"
Return if a trihedron left handed or not\&. From GLM_GTX_handed_coordinate_space extension\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP bool glm::rightHanded (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & tangent, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & binormal, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & normal)"
Return if a trihedron right handed or not\&. From GLM_GTX_handed_coordinate_space extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
