.TH "gtx_log_base" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_log_base \- GLM_GTX_log_base
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::log\fP (genType const &\fBx\fP, genType const &base)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::sign\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &base)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/log_base\&.hpp\fP> to use the features of this extension\&.
.PP
Logarithm for any base\&. base can be a vector or a scalar\&.
.SH "Function Documentation"
.PP 
.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::log (genType const & x, genType const & base)"
Logarithm for any base\&. From GLM_GTX_log_base\&. 
.SS "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > glm::sign (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const & base)"
Logarithm for any base\&. From GLM_GTX_log_base\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
