.TH "gtx_color_space" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_color_space \- GLM_GTX_color_space
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::rgbColor\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &hsvValue)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::hsvColor\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &rgbValue)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > \fBglm::saturation\fP (\fBT\fP const s)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::saturation\fP (\fBT\fP const s, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBcolor\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::saturation\fP (\fBT\fP const s, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBcolor\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP \fBglm::luminosity\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBcolor\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/color_space\&.hpp\fP> to use the features of this extension\&.
.PP
Related to RGB to HSV conversions and operations\&.
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::hsvColor (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & rgbValue)"
Converts a color from RGB color space to its color in HSV color space\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_color_space\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBT\fP glm::luminosity (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & color)"
Compute color luminosity associating ratios (0\&.33, 0\&.59, 0\&.11) to RGB canals\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_color_space\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::rgbColor (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & hsvValue)"
Converts a color from HSV color space to its color in RGB color space\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_color_space\fP 
.RE
.PP

.SS "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBdefaultp\fP > glm::saturation (\fBT\fP const s)"
Build a saturation matrix\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_color_space\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::saturation (\fBT\fP const s, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & color)"
Modify the saturation of a color\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_color_space\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > glm::saturation (\fBT\fP const s, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const & color)"
Modify the saturation of a color\&. 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_color_space\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
