.TH "gtx_color_encoding" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_color_encoding \- GLM_GTX_color_encoding
.PP
 \- Allow to perform bit operations on integer values\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::convertLinearSRGBToD65XYZ\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &ColorLinearSRGB)"
.br
.RI "Convert a linear sRGB color to D65 YUV\&. "
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::convertLinearSRGBToD50XYZ\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &ColorLinearSRGB)"
.br
.RI "Convert a linear sRGB color to D50 YUV\&. "
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::convertD65XYZToLinearSRGB\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &ColorD65XYZ)"
.br
.RI "Convert a D65 YUV color to linear sRGB\&. "
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::convertD65XYZToD50XYZ\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &ColorD65XYZ)"
.br
.RI "Convert a D65 YUV color to D50 YUV\&. "
.in -1c
.SH "Detailed Description"
.PP 
Allow to perform bit operations on integer values\&. 

Include <\fBglm/gtx/color_encoding\&.hpp\fP> to use the features of this extension\&.
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::convertD65XYZToD50XYZ (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & ColorD65XYZ)"

.PP
Convert a D65 YUV color to D50 YUV\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::convertD65XYZToLinearSRGB (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & ColorD65XYZ)"

.PP
Convert a D65 YUV color to linear sRGB\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::convertLinearSRGBToD50XYZ (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & ColorLinearSRGB)"

.PP
Convert a linear sRGB color to D50 YUV\&. 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::convertLinearSRGBToD65XYZ (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & ColorLinearSRGB)"

.PP
Convert a linear sRGB color to D65 YUV\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
