.TH "gtx_polar_coordinates" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_polar_coordinates \- GLM_GTX_polar_coordinates
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::polar\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBeuclidean\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::euclidean\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &\fBpolar\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/polar_coordinates\&.hpp\fP> to use the features of this extension\&.
.PP
Conversion from Euclidean space to polar space and revert\&.
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::euclidean (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const & polar)"
Convert Polar to Euclidean coordinates\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_polar_coordinates\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::polar (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & euclidean)"
Convert Euclidean to Polar coordinates, x is the latitude, y the longitude and z the xz distance\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_polar_coordinates\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
