.TH "gtx_easing" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_easing \- GLM_GTX_easing
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::linearInterpolation\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quadraticEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quadraticEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quadraticEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::cubicEaseIn\fP (genType const &\fBa\fP)"
.br
.RI "Modelled after the cubic y = x^3\&. "
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::cubicEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::cubicEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quarticEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quarticEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quarticEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quinticEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quinticEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::quinticEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::sineEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::sineEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::sineEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::circularEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::circularEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::circularEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::exponentialEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::exponentialEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::exponentialEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::elasticEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::elasticEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::elasticEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::backEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::backEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::backEaseInOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::backEaseIn\fP (genType const &\fBa\fP, genType const &o)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::backEaseOut\fP (genType const &\fBa\fP, genType const &o)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::backEaseInOut\fP (genType const &\fBa\fP, genType const &o)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::bounceEaseIn\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::bounceEaseOut\fP (genType const &\fBa\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::bounceEaseInOut\fP (genType const &\fBa\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/easing\&.hpp\fP> to use the features of this extension\&.
.PP
Easing functions for animations and transitions All functions take a parameter x in the range [0\&.0,1\&.0]
.PP
Based on the AHEasing project of Warren Moore (https://github.com/warrenm/AHEasing)
.SH "Function Documentation"
.PP 
.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::backEaseIn (genType const & a)"

.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::backEaseIn (genType const & a, genType const & o)"

.PP
\fBParameters\fP
.RS 4
\fIa\fP parameter 
.br
\fIo\fP Optional overshoot modifier 
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::backEaseInOut (genType const & a)"

.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::backEaseInOut (genType const & a, genType const & o)"

.PP
\fBParameters\fP
.RS 4
\fIa\fP parameter 
.br
\fIo\fP Optional overshoot modifier 
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::backEaseOut (genType const & a)"

.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::backEaseOut (genType const & a, genType const & o)"

.PP
\fBParameters\fP
.RS 4
\fIa\fP parameter 
.br
\fIo\fP Optional overshoot modifier 
.RE
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::bounceEaseIn (genType const & a)"

.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::bounceEaseInOut (genType const & a)"

.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::bounceEaseOut (genType const & a)"

.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::circularEaseIn (genType const & a)"
Modelled after shifted quadrant IV of unit circle 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::circularEaseInOut (genType const & a)"
Modelled after the piecewise circular function y = (1/2)(1 - sqrt(1 - 4x^2)) ; [0, 0\&.5) y = (1/2)(sqrt(-(2x - 3)*(2x - 1)) + 1) ; [0\&.5, 1] 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::circularEaseOut (genType const & a)"
Modelled after shifted quadrant II of unit circle 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::cubicEaseIn (genType const & a)"

.PP
Modelled after the cubic y = x^3\&. 
.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::cubicEaseInOut (genType const & a)"
Modelled after the piecewise cubic y = (1/2)((2x)^3) ; [0, 0\&.5) y = (1/2)((2x-2)^3 + 2) ; [0\&.5, 1] 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::cubicEaseOut (genType const & a)"
Modelled after the cubic y = (x - 1)^3 + 1 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::elasticEaseIn (genType const & a)"
Modelled after the damped sine wave y = sin(13pi/2*x)*pow(2, 10 * (x - 1)) 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::elasticEaseInOut (genType const & a)"
Modelled after the piecewise exponentially-damped sine wave: y = (1/2)*sin(13pi/2*(2*x))*pow(2, 10 * ((2*x) - 1)) ; [0,0\&.5) y = (1/2)*(sin(-13pi/2*((2x-1)+1))*pow(2,-10(2*x-1)) + 2) ; [0\&.5, 1] 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::elasticEaseOut (genType const & a)"
Modelled after the damped sine wave y = sin(-13pi/2*(x + 1))*pow(2, -10x) + 1 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::exponentialEaseIn (genType const & a)"
Modelled after the exponential function y = 2^(10(x - 1)) 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::exponentialEaseInOut (genType const & a)"
Modelled after the piecewise exponential y = (1/2)2^(10(2x - 1)) ; [0,0\&.5) y = -(1/2)*2^(-10(2x - 1))) + 1 ; [0\&.5,1] 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::exponentialEaseOut (genType const & a)"
Modelled after the exponential function y = -2^(-10x) + 1 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::linearInterpolation (genType const & a)"
Modelled after the line y = x 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::quadraticEaseIn (genType const & a)"
Modelled after the parabola y = x^2 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::quadraticEaseInOut (genType const & a)"
Modelled after the piecewise quadratic y = (1/2)((2x)^2) ; [0, 0\&.5) y = -(1/2)((2x-1)*(2x-3) - 1) ; [0\&.5, 1] 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::quadraticEaseOut (genType const & a)"
Modelled after the parabola y = -x^2 + 2x 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::quarticEaseIn (genType const & a)"
Modelled after the quartic x^4 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::quarticEaseInOut (genType const & a)"
Modelled after the piecewise quartic y = (1/2)((2x)^4) ; [0, 0\&.5) y = -(1/2)((2x-2)^4 - 2) ; [0\&.5, 1] 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::quarticEaseOut (genType const & a)"
Modelled after the quartic y = 1 - (x - 1)^4 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::quinticEaseIn (genType const & a)"
Modelled after the quintic y = x^5 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::quinticEaseInOut (genType const & a)"
Modelled after the piecewise quintic y = (1/2)((2x)^5) ; [0, 0\&.5) y = (1/2)((2x-2)^5 + 2) ; [0\&.5, 1] 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::quinticEaseOut (genType const & a)"
Modelled after the quintic y = (x - 1)^5 + 1 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::sineEaseIn (genType const & a)"
Modelled after quarter-cycle of sine wave 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::sineEaseInOut (genType const & a)"
Modelled after half sine wave 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SS "template<typename genType > \fBGLM_FUNC_DECL\fP genType glm::sineEaseOut (genType const & a)"
Modelled after quarter-cycle of sine wave (different phase) 
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_easing\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
