.TH "gtx_orthonormalize" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_orthonormalize \- GLM_GTX_orthonormalize
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > \fBglm::orthonormalize\fP (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::orthonormalize\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/orthonormalize\&.hpp\fP> to use the features of this extension\&.
.PP
Orthonormalize matrices\&.
.SH "Function Documentation"
.PP 
.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > glm::orthonormalize (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const & m)"
Returns the orthonormalized matrix of m\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_orthonormalize\fP 
.RE
.PP

.SS "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > glm::orthonormalize (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & x, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const & y)"
Orthonormalizes x according y\&.
.PP
\fBSee also\fP
.RS 4
\fBGLM_GTX_orthonormalize\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
