.TH "UPRISE_ENGINE/Helpers.h" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/Helpers.h
.SH SYNOPSIS
.br
.PP
\fR#include 'pch\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBHasher\fP"
.br
.ti -1c
.RI "struct \fBEqualTo\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBTypeInfoRef\fP = std::reference_wrapper<const std::type_info>"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBThrowIfFailed\fP (HRESULT hr)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBTypeInfoRef\fP = std::reference_wrapper<const std::type_info>"

.PP
Definition at line \fB27\fP of file \fBHelpers\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void ThrowIfFailed (HRESULT hr)\fR [inline]\fP"

.PP
Definition at line \fB9\fP of file \fBHelpers\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
