.TH "ID3DDestructionNotifier" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ID3DDestructionNotifier
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3dcommon\&.idl;\fP
.PP
Inherits IUnknown\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "HRESULT \fBRegisterDestructionCallback\fP ([annotation('_In_')] \fBPFN_DESTRUCTION_CALLBACK\fP callbackFn, [annotation('_In_')] \fBvoid\fP *pData, [annotation('_Out_')] UINT *pCallbackID)"
.br
.ti -1c
.RI "HRESULT \fBUnregisterDestructionCallback\fP ([annotation('_In_')] UINT callbackID)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "HRESULT ID3DDestructionNotifier::RegisterDestructionCallback ([annotation('_In_')] \fBPFN_DESTRUCTION_CALLBACK\fP callbackFn, [annotation('_In_')] \fBvoid\fP * pData, [annotation('_Out_')] UINT * pCallbackID)"

.SS "HRESULT ID3DDestructionNotifier::UnregisterDestructionCallback ([annotation('_In_')] UINT callbackID)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
