.TH "ID3D12Resource2" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ID3D12Resource2
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.PP
Inherits \fBID3D12Resource1\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBD3D12_RESOURCE_DESC1\fP \fBGetDesc1\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBID3D12Resource1\fP
.in +1c
.ti -1c
.RI "HRESULT \fBGetProtectedResourceSession\fP ([in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_opt_')] \fBvoid\fP **ppProtectedSession)"
.br
.in -1c

Public Member Functions inherited from \fBID3D12Resource\fP
.in +1c
.ti -1c
.RI "HRESULT \fBMap\fP (UINT Subresource, [annotation('_In_opt_')] const \fBD3D12_RANGE\fP *pReadRange, [annotation('_Outptr_opt_result_bytebuffer_(_Inexpressible_(\\'Dependent on resource\\'))')] void **ppData)"
.br
.ti -1c
.RI "\fBvoid\fP \fBUnmap\fP (UINT Subresource, [annotation('_In_opt_')] const \fBD3D12_RANGE\fP *pWrittenRange)"
.br
.ti -1c
.RI "\fBD3D12_RESOURCE_DESC\fP \fBGetDesc\fP ()"
.br
.ti -1c
.RI "\fBD3D12_GPU_VIRTUAL_ADDRESS\fP \fBGetGPUVirtualAddress\fP ()"
.br
.ti -1c
.RI "HRESULT \fBWriteToSubresource\fP (UINT DstSubresource, [annotation('_In_opt_')] const \fBD3D12_BOX\fP *pDstBox, [annotation('_In_')] const \fBvoid\fP *pSrcData, UINT SrcRowPitch, UINT SrcDepthPitch)"
.br
.ti -1c
.RI "HRESULT \fBReadFromSubresource\fP ([annotation('_Out_')] \fBvoid\fP *pDstData, UINT DstRowPitch, UINT DstDepthPitch, UINT SrcSubresource, [annotation('_In_opt_')] const \fBD3D12_BOX\fP *pSrcBox)"
.br
.ti -1c
.RI "HRESULT \fBGetHeapProperties\fP ([annotation('_Out_opt_')] \fBD3D12_HEAP_PROPERTIES\fP *pHeapProperties, [annotation('_Out_opt_')] \fBD3D12_HEAP_FLAGS\fP *pHeapFlags)"
.br
.in -1c

Public Member Functions inherited from \fBID3D12DeviceChild\fP
.in +1c
.ti -1c
.RI "HRESULT \fBGetDevice\fP ([in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_opt_')] \fBvoid\fP **ppvDevice)"
.br
.in -1c

Public Member Functions inherited from \fBID3D12Object\fP
.in +1c
.ti -1c
.RI "HRESULT \fBGetPrivateData\fP ([annotation('_In_')] REFGUID guid, [annotation('_Inout_')] UINT *pDataSize, [annotation('_Out_writes_bytes_opt_( *pDataSize )')] void *pData)"
.br
.ti -1c
.RI "HRESULT \fBSetPrivateData\fP ([annotation('_In_')] REFGUID guid, [annotation('_In_')] UINT DataSize, [annotation('_In_reads_bytes_opt_( DataSize )')] const \fBvoid\fP *pData)"
.br
.ti -1c
.RI "HRESULT \fBSetPrivateDataInterface\fP ([annotation('_In_')] REFGUID guid, [annotation('_In_opt_')] const IUnknown *pData)"
.br
.ti -1c
.RI "HRESULT \fBSetName\fP ([annotation('_In_z_')] LPCWSTR Name)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBD3D12_RESOURCE_DESC1\fP ID3D12Resource2::GetDesc1 ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
