.TH "ID3DX12PipelineParserCallbacks" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ID3DX12PipelineParserCallbacks
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3dx12_pipeline_state_stream\&.h>\fP
.PP
Inherited by \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBvoid\fP \fBFlagsCb\fP (\fBD3D12_PIPELINE_STATE_FLAGS\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBNodeMaskCb\fP (UINT)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBRootSignatureCb\fP (\fBID3D12RootSignature\fP *)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBInputLayoutCb\fP (const \fBD3D12_INPUT_LAYOUT_DESC\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBIBStripCutValueCb\fP (\fBD3D12_INDEX_BUFFER_STRIP_CUT_VALUE\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBPrimitiveTopologyTypeCb\fP (\fBD3D12_PRIMITIVE_TOPOLOGY_TYPE\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBVSCb\fP (const \fBD3D12_SHADER_BYTECODE\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBGSCb\fP (const \fBD3D12_SHADER_BYTECODE\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBStreamOutputCb\fP (const \fBD3D12_STREAM_OUTPUT_DESC\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBHSCb\fP (const \fBD3D12_SHADER_BYTECODE\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBDSCb\fP (const \fBD3D12_SHADER_BYTECODE\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBPSCb\fP (const \fBD3D12_SHADER_BYTECODE\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBCSCb\fP (const \fBD3D12_SHADER_BYTECODE\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBASCb\fP (const \fBD3D12_SHADER_BYTECODE\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBMSCb\fP (const \fBD3D12_SHADER_BYTECODE\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBBlendStateCb\fP (const \fBD3D12_BLEND_DESC\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBDepthStencilStateCb\fP (const \fBD3D12_DEPTH_STENCIL_DESC\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBDepthStencilState1Cb\fP (const \fBD3D12_DEPTH_STENCIL_DESC1\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBDSVFormatCb\fP (\fBDXGI_FORMAT\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBRasterizerStateCb\fP (const \fBD3D12_RASTERIZER_DESC\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBRTVFormatsCb\fP (const \fBD3D12_RT_FORMAT_ARRAY\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBSampleDescCb\fP (const \fBDXGI_SAMPLE_DESC\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBSampleMaskCb\fP (UINT)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBViewInstancingCb\fP (const \fBD3D12_VIEW_INSTANCING_DESC\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBCachedPSOCb\fP (const \fBD3D12_CACHED_PIPELINE_STATE\fP &)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBErrorBadInputParameter\fP (UINT)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBErrorDuplicateSubobject\fP (\fBD3D12_PIPELINE_STATE_SUBOBJECT_TYPE\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBErrorUnknownSubobject\fP (UINT)"
.br
.ti -1c
.RI "virtual \fB~ID3DX12PipelineParserCallbacks\fP ()=default"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ID3DX12PipelineParserCallbacks::~ID3DX12PipelineParserCallbacks ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::ASCb (const \fBD3D12_SHADER_BYTECODE\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::BlendStateCb (const \fBD3D12_BLEND_DESC\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::CachedPSOCb (const \fBD3D12_CACHED_PIPELINE_STATE\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::CSCb (const \fBD3D12_SHADER_BYTECODE\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::DepthStencilState1Cb (const \fBD3D12_DEPTH_STENCIL_DESC1\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::DepthStencilStateCb (const \fBD3D12_DEPTH_STENCIL_DESC\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::DSCb (const \fBD3D12_SHADER_BYTECODE\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::DSVFormatCb (\fBDXGI_FORMAT\fP )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::ErrorBadInputParameter (UINT )\fR [inline]\fP, \fR [virtual]\fP"

.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::ErrorDuplicateSubobject (\fBD3D12_PIPELINE_STATE_SUBOBJECT_TYPE\fP )\fR [inline]\fP, \fR [virtual]\fP"

.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::ErrorUnknownSubobject (UINT )\fR [inline]\fP, \fR [virtual]\fP"

.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::FlagsCb (\fBD3D12_PIPELINE_STATE_FLAGS\fP )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::GSCb (const \fBD3D12_SHADER_BYTECODE\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::HSCb (const \fBD3D12_SHADER_BYTECODE\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::IBStripCutValueCb (\fBD3D12_INDEX_BUFFER_STRIP_CUT_VALUE\fP )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::InputLayoutCb (const \fBD3D12_INPUT_LAYOUT_DESC\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::MSCb (const \fBD3D12_SHADER_BYTECODE\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::NodeMaskCb (UINT )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::PrimitiveTopologyTypeCb (\fBD3D12_PRIMITIVE_TOPOLOGY_TYPE\fP )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::PSCb (const \fBD3D12_SHADER_BYTECODE\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::RasterizerStateCb (const \fBD3D12_RASTERIZER_DESC\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::RootSignatureCb (\fBID3D12RootSignature\fP * )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::RTVFormatsCb (const \fBD3D12_RT_FORMAT_ARRAY\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::SampleDescCb (const \fBDXGI_SAMPLE_DESC\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::SampleMaskCb (UINT )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::StreamOutputCb (const \fBD3D12_STREAM_OUTPUT_DESC\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::ViewInstancingCb (const \fBD3D12_VIEW_INSTANCING_DESC\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.
.SS "virtual \fBvoid\fP ID3DX12PipelineParserCallbacks::VSCb (const \fBD3D12_SHADER_BYTECODE\fP & )\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBCD3DX12_PIPELINE_STATE_STREAM2_PARSE_HELPER\fP, and \fBCD3DX12_PIPELINE_STATE_STREAM_PARSE_HELPER\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
