.TH "ID3D12VideoDevice" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ID3D12VideoDevice
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12video\&.idl;\fP
.PP
Inherits IUnknown\&.
.PP
Inherited by \fBstruct\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "HRESULT \fBCheckFeatureSupport\fP (\fBD3D12_FEATURE_VIDEO\fP FeatureVideo, [annotation('_Inout_updates_bytes_(FeatureSupportDataSize)')] void *pFeatureSupportData, UINT FeatureSupportDataSize)"
.br
.ti -1c
.RI "HRESULT \fBCreateVideoDecoder\fP ([annotation('_In_')] const \fBD3D12_VIDEO_DECODER_DESC\fP *pDesc, [annotation('_In_')] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppVideoDecoder)"
.br
.ti -1c
.RI "HRESULT \fBCreateVideoDecoderHeap\fP ([annotation('_In_')]const \fBD3D12_VIDEO_DECODER_HEAP_DESC\fP *pVideoDecoderHeapDesc, [annotation('_In_')] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppVideoDecoderHeap)"
.br
.ti -1c
.RI "HRESULT \fBCreateVideoProcessor\fP (UINT NodeMask, [annotation('_In_')] const \fBD3D12_VIDEO_PROCESS_OUTPUT_STREAM_DESC\fP *pOutputStreamDesc, UINT NumInputStreamDescs, [annotation('_In_reads_(NumInputStreamDescs)')]const \fBD3D12_VIDEO_PROCESS_INPUT_STREAM_DESC\fP *pInputStreamDescs, [annotation('_In_')] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppVideoProcessor)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "HRESULT ID3D12VideoDevice::CheckFeatureSupport (\fBD3D12_FEATURE_VIDEO\fP FeatureVideo, [annotation('_Inout_updates_bytes_(FeatureSupportDataSize)')] \fBvoid\fP * pFeatureSupportData, UINT FeatureSupportDataSize)"

.SS "HRESULT ID3D12VideoDevice::CreateVideoDecoder ([annotation('_In_')] const \fBD3D12_VIDEO_DECODER_DESC\fP * pDesc, [annotation('_In_')] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP ** ppVideoDecoder)"

.SS "HRESULT ID3D12VideoDevice::CreateVideoDecoderHeap ([annotation('_In_')] const \fBD3D12_VIDEO_DECODER_HEAP_DESC\fP * pVideoDecoderHeapDesc, [annotation('_In_')] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP ** ppVideoDecoderHeap)"

.SS "HRESULT ID3D12VideoDevice::CreateVideoProcessor (UINT NodeMask, [annotation('_In_')] const \fBD3D12_VIDEO_PROCESS_OUTPUT_STREAM_DESC\fP * pOutputStreamDesc, UINT NumInputStreamDescs, [annotation('_In_reads_(NumInputStreamDescs)')] const \fBD3D12_VIDEO_PROCESS_INPUT_STREAM_DESC\fP * pInputStreamDescs, [annotation('_In_')] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP ** ppVideoProcessor)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
