.TH "ID3D12InfoQueue" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ID3D12InfoQueue
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12sdklayers\&.idl;\fP
.PP
Inherits IUnknown\&.
.PP
Inherited by \fBID3D12InfoQueue1\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "HRESULT \fBSetMessageCountLimit\fP ([annotation('_In_')] UINT64 MessageCountLimit)"
.br
.ti -1c
.RI "\fBvoid\fP \fBClearStoredMessages\fP ()"
.br
.ti -1c
.RI "HRESULT \fBGetMessage\fP ([annotation('_In_')] UINT64 MessageIndex, [annotation('_Out_writes_bytes_opt_(*pMessageByteLength)')] D3D12_MESSAGE *pMessage, [annotation('_Inout_')] SIZE_T *pMessageByteLength)"
.br
.ti -1c
.RI "UINT64 \fBGetNumMessagesAllowedByStorageFilter\fP ()"
.br
.ti -1c
.RI "UINT64 \fBGetNumMessagesDeniedByStorageFilter\fP ()"
.br
.ti -1c
.RI "UINT64 \fBGetNumStoredMessages\fP ()"
.br
.ti -1c
.RI "UINT64 \fBGetNumStoredMessagesAllowedByRetrievalFilter\fP ()"
.br
.ti -1c
.RI "UINT64 \fBGetNumMessagesDiscardedByMessageCountLimit\fP ()"
.br
.ti -1c
.RI "UINT64 \fBGetMessageCountLimit\fP ()"
.br
.ti -1c
.RI "HRESULT \fBAddStorageFilterEntries\fP ([annotation('_In_')] \fBD3D12_INFO_QUEUE_FILTER\fP *pFilter)"
.br
.ti -1c
.RI "HRESULT \fBGetStorageFilter\fP ([annotation('_Out_writes_bytes_opt_(*pFilterByteLength)')] D3D12_INFO_QUEUE_FILTER *pFilter, [annotation('_Inout_')] SIZE_T *pFilterByteLength)"
.br
.ti -1c
.RI "\fBvoid\fP \fBClearStorageFilter\fP ()"
.br
.ti -1c
.RI "HRESULT \fBPushEmptyStorageFilter\fP ()"
.br
.ti -1c
.RI "HRESULT \fBPushCopyOfStorageFilter\fP ()"
.br
.ti -1c
.RI "HRESULT \fBPushStorageFilter\fP ([annotation('_In_')] \fBD3D12_INFO_QUEUE_FILTER\fP *pFilter)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPopStorageFilter\fP ()"
.br
.ti -1c
.RI "UINT \fBGetStorageFilterStackSize\fP ()"
.br
.ti -1c
.RI "HRESULT \fBAddRetrievalFilterEntries\fP ([annotation('_In_')] \fBD3D12_INFO_QUEUE_FILTER\fP *pFilter)"
.br
.ti -1c
.RI "HRESULT \fBGetRetrievalFilter\fP ([annotation('_Out_writes_bytes_opt_(*pFilterByteLength)')] D3D12_INFO_QUEUE_FILTER *pFilter, [annotation('_Inout_')] SIZE_T *pFilterByteLength)"
.br
.ti -1c
.RI "\fBvoid\fP \fBClearRetrievalFilter\fP ()"
.br
.ti -1c
.RI "HRESULT \fBPushEmptyRetrievalFilter\fP ()"
.br
.ti -1c
.RI "HRESULT \fBPushCopyOfRetrievalFilter\fP ()"
.br
.ti -1c
.RI "HRESULT \fBPushRetrievalFilter\fP ([annotation('_In_')] \fBD3D12_INFO_QUEUE_FILTER\fP *pFilter)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPopRetrievalFilter\fP ()"
.br
.ti -1c
.RI "UINT \fBGetRetrievalFilterStackSize\fP ()"
.br
.ti -1c
.RI "HRESULT \fBAddMessage\fP ([annotation('_In_')] \fBD3D12_MESSAGE_CATEGORY\fP Category, [annotation('_In_')] \fBD3D12_MESSAGE_SEVERITY\fP \fBSeverity\fP, [annotation('_In_')] \fBD3D12_MESSAGE_ID\fP \fBID\fP, [annotation('_In_')] LPCSTR \fBpDescription\fP)"
.br
.ti -1c
.RI "HRESULT \fBAddApplicationMessage\fP ([annotation('_In_')] \fBD3D12_MESSAGE_SEVERITY\fP \fBSeverity\fP, [annotation('_In_')] LPCSTR \fBpDescription\fP)"
.br
.ti -1c
.RI "HRESULT \fBSetBreakOnCategory\fP ([annotation('_In_')] \fBD3D12_MESSAGE_CATEGORY\fP Category, [annotation('_In_')] BOOL bEnable)"
.br
.ti -1c
.RI "HRESULT \fBSetBreakOnSeverity\fP ([annotation('_In_')] \fBD3D12_MESSAGE_SEVERITY\fP \fBSeverity\fP, [annotation('_In_')] BOOL bEnable)"
.br
.ti -1c
.RI "HRESULT \fBSetBreakOnID\fP ([annotation('_In_')] \fBD3D12_MESSAGE_ID\fP \fBID\fP, [annotation('_In_')] BOOL bEnable)"
.br
.ti -1c
.RI "BOOL \fBGetBreakOnCategory\fP ([annotation('_In_')] \fBD3D12_MESSAGE_CATEGORY\fP Category)"
.br
.ti -1c
.RI "BOOL \fBGetBreakOnSeverity\fP ([annotation('_In_')] \fBD3D12_MESSAGE_SEVERITY\fP \fBSeverity\fP)"
.br
.ti -1c
.RI "BOOL \fBGetBreakOnID\fP ([annotation('_In_')] \fBD3D12_MESSAGE_ID\fP \fBID\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetMuteDebugOutput\fP ([annotation('_In_')] BOOL bMute)"
.br
.ti -1c
.RI "BOOL \fBGetMuteDebugOutput\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "HRESULT ID3D12InfoQueue::AddApplicationMessage ([annotation('_In_')] \fBD3D12_MESSAGE_SEVERITY\fP Severity, [annotation('_In_')] LPCSTR pDescription)"

.SS "HRESULT ID3D12InfoQueue::AddMessage ([annotation('_In_')] \fBD3D12_MESSAGE_CATEGORY\fP Category, [annotation('_In_')] \fBD3D12_MESSAGE_SEVERITY\fP Severity, [annotation('_In_')] \fBD3D12_MESSAGE_ID\fP ID, [annotation('_In_')] LPCSTR pDescription)"

.SS "HRESULT ID3D12InfoQueue::AddRetrievalFilterEntries ([annotation('_In_')] \fBD3D12_INFO_QUEUE_FILTER\fP * pFilter)"

.SS "HRESULT ID3D12InfoQueue::AddStorageFilterEntries ([annotation('_In_')] \fBD3D12_INFO_QUEUE_FILTER\fP * pFilter)"

.SS "\fBvoid\fP ID3D12InfoQueue::ClearRetrievalFilter ()"

.SS "\fBvoid\fP ID3D12InfoQueue::ClearStorageFilter ()"

.SS "\fBvoid\fP ID3D12InfoQueue::ClearStoredMessages ()"

.SS "BOOL ID3D12InfoQueue::GetBreakOnCategory ([annotation('_In_')] \fBD3D12_MESSAGE_CATEGORY\fP Category)"

.SS "BOOL ID3D12InfoQueue::GetBreakOnID ([annotation('_In_')] \fBD3D12_MESSAGE_ID\fP ID)"

.SS "BOOL ID3D12InfoQueue::GetBreakOnSeverity ([annotation('_In_')] \fBD3D12_MESSAGE_SEVERITY\fP Severity)"

.SS "HRESULT ID3D12InfoQueue::GetMessage ([annotation('_In_')] UINT64 MessageIndex, [annotation('_Out_writes_bytes_opt_(*pMessageByteLength)')] \fBD3D12_MESSAGE\fP * pMessage, [annotation('_Inout_')] SIZE_T * pMessageByteLength)"

.SS "UINT64 ID3D12InfoQueue::GetMessageCountLimit ()"

.SS "BOOL ID3D12InfoQueue::GetMuteDebugOutput ()"

.SS "UINT64 ID3D12InfoQueue::GetNumMessagesAllowedByStorageFilter ()"

.SS "UINT64 ID3D12InfoQueue::GetNumMessagesDeniedByStorageFilter ()"

.SS "UINT64 ID3D12InfoQueue::GetNumMessagesDiscardedByMessageCountLimit ()"

.SS "UINT64 ID3D12InfoQueue::GetNumStoredMessages ()"

.SS "UINT64 ID3D12InfoQueue::GetNumStoredMessagesAllowedByRetrievalFilter ()"

.SS "HRESULT ID3D12InfoQueue::GetRetrievalFilter ([annotation('_Out_writes_bytes_opt_(*pFilterByteLength)')] \fBD3D12_INFO_QUEUE_FILTER\fP * pFilter, [annotation('_Inout_')] SIZE_T * pFilterByteLength)"

.SS "UINT ID3D12InfoQueue::GetRetrievalFilterStackSize ()"

.SS "HRESULT ID3D12InfoQueue::GetStorageFilter ([annotation('_Out_writes_bytes_opt_(*pFilterByteLength)')] \fBD3D12_INFO_QUEUE_FILTER\fP * pFilter, [annotation('_Inout_')] SIZE_T * pFilterByteLength)"

.SS "UINT ID3D12InfoQueue::GetStorageFilterStackSize ()"

.SS "\fBvoid\fP ID3D12InfoQueue::PopRetrievalFilter ()"

.SS "\fBvoid\fP ID3D12InfoQueue::PopStorageFilter ()"

.SS "HRESULT ID3D12InfoQueue::PushCopyOfRetrievalFilter ()"

.SS "HRESULT ID3D12InfoQueue::PushCopyOfStorageFilter ()"

.SS "HRESULT ID3D12InfoQueue::PushEmptyRetrievalFilter ()"

.SS "HRESULT ID3D12InfoQueue::PushEmptyStorageFilter ()"

.SS "HRESULT ID3D12InfoQueue::PushRetrievalFilter ([annotation('_In_')] \fBD3D12_INFO_QUEUE_FILTER\fP * pFilter)"

.SS "HRESULT ID3D12InfoQueue::PushStorageFilter ([annotation('_In_')] \fBD3D12_INFO_QUEUE_FILTER\fP * pFilter)"

.SS "HRESULT ID3D12InfoQueue::SetBreakOnCategory ([annotation('_In_')] \fBD3D12_MESSAGE_CATEGORY\fP Category, [annotation('_In_')] BOOL bEnable)"

.SS "HRESULT ID3D12InfoQueue::SetBreakOnID ([annotation('_In_')] \fBD3D12_MESSAGE_ID\fP ID, [annotation('_In_')] BOOL bEnable)"

.SS "HRESULT ID3D12InfoQueue::SetBreakOnSeverity ([annotation('_In_')] \fBD3D12_MESSAGE_SEVERITY\fP Severity, [annotation('_In_')] BOOL bEnable)"

.SS "HRESULT ID3D12InfoQueue::SetMessageCountLimit ([annotation('_In_')] UINT64 MessageCountLimit)"

.SS "\fBvoid\fP ID3D12InfoQueue::SetMuteDebugOutput ([annotation('_In_')] BOOL bMute)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
