.TH "ID3D12SwapChainAssistant" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ID3D12SwapChainAssistant
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.PP
Inherits IUnknown\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLUID\fP \fBGetLUID\fP ()"
.br
.ti -1c
.RI "HRESULT \fBGetSwapChainObject\fP (REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppv)"
.br
.ti -1c
.RI "HRESULT \fBGetCurrentResourceAndCommandQueue\fP (REFIID riidResource, [out, iid_is(riidResource), annotation('_COM_Outptr_')] \fBvoid\fP **ppvResource, REFIID riidQueue, [out, iid_is(riidQueue), annotation('_COM_Outptr_')] \fBvoid\fP **ppvQueue)"
.br
.ti -1c
.RI "HRESULT \fBInsertImplicitSync\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "HRESULT ID3D12SwapChainAssistant::GetCurrentResourceAndCommandQueue (REFIID riidResource, [out, iid_is(riidResource), annotation('_COM_Outptr_')] \fBvoid\fP ** ppvResource, REFIID riidQueue, [out, iid_is(riidQueue), annotation('_COM_Outptr_')] \fBvoid\fP ** ppvQueue)"

.SS "\fBLUID\fP ID3D12SwapChainAssistant::GetLUID ()"

.SS "HRESULT ID3D12SwapChainAssistant::GetSwapChainObject (REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP ** ppv)"

.SS "HRESULT ID3D12SwapChainAssistant::InsertImplicitSync ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
