.TH "ID3D12SDKConfiguration" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ID3D12SDKConfiguration
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.PP
Inherits IUnknown\&.
.PP
Inherited by \fBenum\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "HRESULT \fBSetSDKVersion\fP (UINT SDKVersion, [annotation('_In_z_')] LPCSTR SDKPath)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "HRESULT ID3D12SDKConfiguration::SetSDKVersion (UINT SDKVersion, [annotation('_In_z_')] LPCSTR SDKPath)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
