.TH "ID3D10BlobVtbl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ID3D10BlobVtbl
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <d3dcommon\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBHRESULT\fP (STDMETHODCALLTYPE *QueryInterface)(\fBID3D10Blob\fP *This"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *AddRef)(\fBID3D10Blob\fP *This)"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *Release)(\fBID3D10Blob\fP *This)"
.br
.ti -1c
.RI "\fBLPVOID\fP (STDMETHODCALLTYPE *GetBufferPointer)(\fBID3D10Blob\fP *This)"
.br
.ti -1c
.RI "\fBSIZE_T\fP (STDMETHODCALLTYPE *GetBufferSize)(\fBID3D10Blob\fP *This)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE REFIID \fBriid\fP"
.br
.ti -1c
.RI "BEGIN_INTERFACE REFIID _COM_Outptr_ \fBvoid\fP ** \fBppvObject\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "BEGIN_INTERFACE ID3D10BlobVtbl::HRESULT (STDMETHODCALLTYPE * QueryInterface)"

.SS "ID3D10BlobVtbl::LPVOID (STDMETHODCALLTYPE * GetBufferPointer)"

.SS "ID3D10BlobVtbl::SIZE_T (STDMETHODCALLTYPE * GetBufferSize)"

.SS "ID3D10BlobVtbl::ULONG (STDMETHODCALLTYPE * AddRef)"

.SS "ID3D10BlobVtbl::ULONG (STDMETHODCALLTYPE * Release)"

.SH "Member Data Documentation"
.PP 
.SS "BEGIN_INTERFACE REFIID _COM_Outptr_ \fBvoid\fP** ID3D10BlobVtbl::ppvObject"

.SS "BEGIN_INTERFACE REFIID ID3D10BlobVtbl::riid"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
