.TH "ID3D12VirtualizationGuestDevice" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ID3D12VirtualizationGuestDevice
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.PP
Inherits IUnknown\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "HRESULT \fBShareWithHost\fP ([annotation('_In_')] \fBID3D12DeviceChild\fP *pObject, [annotation('_Out_')] HANDLE *pHandle)"
.br
.ti -1c
.RI "HRESULT \fBCreateFenceFd\fP ([annotation('_In_')] \fBID3D12Fence\fP *pFence, UINT64 FenceValue, [annotation('_Out_')] int *pFenceFd)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "HRESULT ID3D12VirtualizationGuestDevice::CreateFenceFd ([annotation('_In_')] \fBID3D12Fence\fP * pFence, UINT64 FenceValue, [annotation('_Out_')] int * pFenceFd)"

.SS "HRESULT ID3D12VirtualizationGuestDevice::ShareWithHost ([annotation('_In_')] \fBID3D12DeviceChild\fP * pObject, [annotation('_Out_')] HANDLE * pHandle)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
