.TH "ID3D12Device1" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ID3D12Device1
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.PP
Inherits \fBID3D12Device\fP\&.
.PP
Inherited by \fBenum\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "HRESULT \fBCreatePipelineLibrary\fP ([annotation('_In_reads_(BlobLength)')] const \fBvoid\fP *pLibraryBlob, SIZE_T BlobLength, [in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppPipelineLibrary)"
.br
.ti -1c
.RI "HRESULT \fBSetEventOnMultipleFenceCompletion\fP ([annotation('_In_reads_(NumFences)')] ID3D12Fence *const *ppFences, [annotation('_In_reads_(NumFences)')] const UINT64 *pFenceValues, UINT NumFences, \fBD3D12_MULTIPLE_FENCE_WAIT_FLAGS\fP \fBFlags\fP, HANDLE hEvent)"
.br
.ti -1c
.RI "HRESULT \fBSetResidencyPriority\fP (UINT NumObjects, [annotation('_In_reads_(NumObjects)')] ID3D12Pageable *const *ppObjects, [annotation('_In_reads_(NumObjects)')] const \fBD3D12_RESIDENCY_PRIORITY\fP *pPriorities)"
.br
.in -1c

Public Member Functions inherited from \fBID3D12Device\fP
.in +1c
.ti -1c
.RI "UINT \fBGetNodeCount\fP ()"
.br
.ti -1c
.RI "HRESULT \fBCreateCommandQueue\fP ([annotation('_In_')] const \fBD3D12_COMMAND_QUEUE_DESC\fP *pDesc, [in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppCommandQueue)"
.br
.ti -1c
.RI "HRESULT \fBCreateCommandAllocator\fP ([annotation('_In_')] \fBD3D12_COMMAND_LIST_TYPE\fP \fBtype\fP, [in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppCommandAllocator)"
.br
.ti -1c
.RI "HRESULT \fBCreateGraphicsPipelineState\fP ([annotation('_In_')] const \fBD3D12_GRAPHICS_PIPELINE_STATE_DESC\fP *pDesc, [in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppPipelineState)"
.br
.ti -1c
.RI "HRESULT \fBCreateComputePipelineState\fP ([annotation('_In_')] const \fBD3D12_COMPUTE_PIPELINE_STATE_DESC\fP *pDesc, [in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppPipelineState)"
.br
.ti -1c
.RI "HRESULT \fBCreateCommandList\fP ([annotation('_In_')] UINT nodeMask, [annotation('_In_')] \fBD3D12_COMMAND_LIST_TYPE\fP \fBtype\fP, [annotation('_In_')] \fBID3D12CommandAllocator\fP *pCommandAllocator, [annotation('_In_opt_')] \fBID3D12PipelineState\fP *pInitialState, [in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppCommandList)"
.br
.ti -1c
.RI "HRESULT \fBCheckFeatureSupport\fP (\fBD3D12_FEATURE\fP Feature, [annotation('_Inout_updates_bytes_(FeatureSupportDataSize)')] void *pFeatureSupportData, UINT FeatureSupportDataSize)"
.br
.ti -1c
.RI "HRESULT \fBCreateDescriptorHeap\fP ([annotation('_In_')] const \fBD3D12_DESCRIPTOR_HEAP_DESC\fP *pDescriptorHeapDesc, [in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppvHeap)"
.br
.ti -1c
.RI "UINT \fBGetDescriptorHandleIncrementSize\fP ([annotation('_In_')] \fBD3D12_DESCRIPTOR_HEAP_TYPE\fP DescriptorHeapType)"
.br
.ti -1c
.RI "HRESULT \fBCreateRootSignature\fP ([annotation('_In_')] UINT nodeMask, [annotation('_In_reads_(blobLengthInBytes)')] const \fBvoid\fP *pBlobWithRootSignature, [annotation('_In_')] SIZE_T blobLengthInBytes, [in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppvRootSignature)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCreateConstantBufferView\fP ([annotation('_In_opt_')] const \fBD3D12_CONSTANT_BUFFER_VIEW_DESC\fP *pDesc, [annotation('_In_')] \fBD3D12_CPU_DESCRIPTOR_HANDLE\fP DestDescriptor)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCreateShaderResourceView\fP ([annotation('_In_opt_')] \fBID3D12Resource\fP *pResource, [annotation('_In_opt_')] const \fBD3D12_SHADER_RESOURCE_VIEW_DESC\fP *pDesc, [annotation('_In_')] \fBD3D12_CPU_DESCRIPTOR_HANDLE\fP DestDescriptor)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCreateUnorderedAccessView\fP ([annotation('_In_opt_')] \fBID3D12Resource\fP *pResource, [annotation('_In_opt_')] \fBID3D12Resource\fP *pCounterResource, [annotation('_In_opt_')] const \fBD3D12_UNORDERED_ACCESS_VIEW_DESC\fP *pDesc, [annotation('_In_')] \fBD3D12_CPU_DESCRIPTOR_HANDLE\fP DestDescriptor)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCreateRenderTargetView\fP ([annotation('_In_opt_')] \fBID3D12Resource\fP *pResource, [annotation('_In_opt_')] const \fBD3D12_RENDER_TARGET_VIEW_DESC\fP *pDesc, [annotation('_In_')] \fBD3D12_CPU_DESCRIPTOR_HANDLE\fP DestDescriptor)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCreateDepthStencilView\fP ([annotation('_In_opt_')] \fBID3D12Resource\fP *pResource, [annotation('_In_opt_')] const \fBD3D12_DEPTH_STENCIL_VIEW_DESC\fP *pDesc, [annotation('_In_')] \fBD3D12_CPU_DESCRIPTOR_HANDLE\fP DestDescriptor)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCreateSampler\fP ([annotation('_In_')] const \fBD3D12_SAMPLER_DESC\fP *pDesc, [annotation('_In_')] \fBD3D12_CPU_DESCRIPTOR_HANDLE\fP DestDescriptor)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCopyDescriptors\fP ([annotation('_In_')] UINT NumDestDescriptorRanges, [annotation('_In_reads_(NumDestDescriptorRanges)')] const \fBD3D12_CPU_DESCRIPTOR_HANDLE\fP *pDestDescriptorRangeStarts, [annotation('_In_reads_opt_(NumDestDescriptorRanges)')] const UINT *pDestDescriptorRangeSizes, [annotation('_In_')] UINT NumSrcDescriptorRanges, [annotation('_In_reads_(NumSrcDescriptorRanges)')] const \fBD3D12_CPU_DESCRIPTOR_HANDLE\fP *pSrcDescriptorRangeStarts, [annotation('_In_reads_opt_(NumSrcDescriptorRanges)')] const UINT *pSrcDescriptorRangeSizes, [annotation('_In_')] \fBD3D12_DESCRIPTOR_HEAP_TYPE\fP DescriptorHeapsType)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCopyDescriptorsSimple\fP ([annotation('_In_')] UINT NumDescriptors, [annotation('_In_')] \fBD3D12_CPU_DESCRIPTOR_HANDLE\fP DestDescriptorRangeStart, [annotation('_In_')] \fBD3D12_CPU_DESCRIPTOR_HANDLE\fP SrcDescriptorRangeStart, [annotation('_In_')] \fBD3D12_DESCRIPTOR_HEAP_TYPE\fP DescriptorHeapsType)"
.br
.ti -1c
.RI "\fBD3D12_RESOURCE_ALLOCATION_INFO\fP \fBGetResourceAllocationInfo\fP ([annotation('_In_')] UINT visibleMask, [annotation('_In_')] UINT numResourceDescs, [annotation('_In_reads_(numResourceDescs)')] const \fBD3D12_RESOURCE_DESC\fP *pResourceDescs)"
.br
.ti -1c
.RI "\fBD3D12_HEAP_PROPERTIES\fP \fBGetCustomHeapProperties\fP ([annotation('_In_')] UINT nodeMask, \fBD3D12_HEAP_TYPE\fP heapType)"
.br
.ti -1c
.RI "HRESULT \fBCreateCommittedResource\fP ([annotation('_In_')] const \fBD3D12_HEAP_PROPERTIES\fP *pHeapProperties, \fBD3D12_HEAP_FLAGS\fP HeapFlags, [annotation('_In_')] const \fBD3D12_RESOURCE_DESC\fP *pDesc, \fBD3D12_RESOURCE_STATES\fP InitialResourceState, [annotation('_In_opt_')] const \fBD3D12_CLEAR_VALUE\fP *pOptimizedClearValue, [in] REFIID riidResource, [out, iid_is(riidResource), annotation('_COM_Outptr_opt_')] \fBvoid\fP **ppvResource)"
.br
.ti -1c
.RI "HRESULT \fBCreateHeap\fP ([annotation('_In_')] const \fBD3D12_HEAP_DESC\fP *pDesc, [in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_opt_')] \fBvoid\fP **ppvHeap)"
.br
.ti -1c
.RI "HRESULT \fBCreatePlacedResource\fP ([annotation('_In_')] \fBID3D12Heap\fP *pHeap, UINT64 HeapOffset, [annotation('_In_')] const \fBD3D12_RESOURCE_DESC\fP *pDesc, \fBD3D12_RESOURCE_STATES\fP InitialState, [annotation('_In_opt_')] const \fBD3D12_CLEAR_VALUE\fP *pOptimizedClearValue, [in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_opt_')] \fBvoid\fP **ppvResource)"
.br
.ti -1c
.RI "HRESULT \fBCreateReservedResource\fP ([annotation('_In_')] const \fBD3D12_RESOURCE_DESC\fP *pDesc, \fBD3D12_RESOURCE_STATES\fP InitialState, [annotation('_In_opt_')] const \fBD3D12_CLEAR_VALUE\fP *pOptimizedClearValue, [in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_opt_')] \fBvoid\fP **ppvResource)"
.br
.ti -1c
.RI "HRESULT \fBCreateSharedHandle\fP ([annotation('_In_')] \fBID3D12DeviceChild\fP *pObject, [annotation('_In_opt_')] const SECURITY_ATTRIBUTES *pAttributes, DWORD Access, [annotation('_In_opt_')] LPCWSTR Name, [annotation('_Out_')] HANDLE *pHandle)"
.br
.ti -1c
.RI "HRESULT \fBOpenSharedHandle\fP ([annotation('_In_')] HANDLE NTHandle, [in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_opt_')] \fBvoid\fP **ppvObj)"
.br
.ti -1c
.RI "HRESULT \fBOpenSharedHandleByName\fP ([annotation('_In_')] LPCWSTR Name, DWORD Access, [out, annotation('_Out_')] HANDLE *pNTHandle)"
.br
.ti -1c
.RI "HRESULT \fBMakeResident\fP (UINT NumObjects, [annotation('_In_reads_(NumObjects)')] ID3D12Pageable *const *ppObjects)"
.br
.ti -1c
.RI "HRESULT \fBEvict\fP (UINT NumObjects, [annotation('_In_reads_(NumObjects)')] ID3D12Pageable *const *ppObjects)"
.br
.ti -1c
.RI "HRESULT \fBCreateFence\fP (UINT64 InitialValue, \fBD3D12_FENCE_FLAGS\fP \fBFlags\fP, [in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppFence)"
.br
.ti -1c
.RI "HRESULT \fBGetDeviceRemovedReason\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBGetCopyableFootprints\fP ([annotation('_In_')] const \fBD3D12_RESOURCE_DESC\fP *pResourceDesc, [annotation('_In_range_(0,\fBD3D12_REQ_SUBRESOURCES\fP)')] UINT FirstSubresource, [annotation('_In_range_(0,\fBD3D12_REQ_SUBRESOURCES\fP\-FirstSubresource)')] UINT NumSubresources, UINT64 BaseOffset, [annotation('_Out_writes_opt_(NumSubresources)')] D3D12_PLACED_SUBRESOURCE_FOOTPRINT *pLayouts, [annotation('_Out_writes_opt_(NumSubresources)')] UINT *pNumRows, [annotation('_Out_writes_opt_(NumSubresources)')] UINT64 *pRowSizeInBytes, [annotation('_Out_opt_')] UINT64 *pTotalBytes)"
.br
.ti -1c
.RI "HRESULT \fBCreateQueryHeap\fP ([annotation('_In_')] const \fBD3D12_QUERY_HEAP_DESC\fP *pDesc, [in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_opt_')] \fBvoid\fP **ppvHeap)"
.br
.ti -1c
.RI "HRESULT \fBSetStablePowerState\fP (BOOL Enable)"
.br
.ti -1c
.RI "HRESULT \fBCreateCommandSignature\fP ([annotation('_In_')] const \fBD3D12_COMMAND_SIGNATURE_DESC\fP *pDesc, [annotation('_In_opt_')] \fBID3D12RootSignature\fP *pRootSignature, [in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_opt_')] \fBvoid\fP **ppvCommandSignature)"
.br
.ti -1c
.RI "\fBvoid\fP \fBGetResourceTiling\fP ([annotation('_In_')] \fBID3D12Resource\fP *pTiledResource, [annotation('_Out_opt_')] UINT *pNumTilesForEntireResource, [annotation('_Out_opt_')] \fBD3D12_PACKED_MIP_INFO\fP *pPackedMipDesc, [annotation('_Out_opt_')] \fBD3D12_TILE_SHAPE\fP *pStandardTileShapeForNonPackedMips, [annotation('_Inout_opt_')] UINT *pNumSubresourceTilings, [annotation('_In_')] UINT FirstSubresourceTilingToGet, [annotation('_Out_writes_(*pNumSubresourceTilings)')] D3D12_SUBRESOURCE_TILING *pSubresourceTilingsForNonPackedMips)"
.br
.ti -1c
.RI "\fBLUID\fP \fBGetAdapterLuid\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBID3D12Object\fP
.in +1c
.ti -1c
.RI "HRESULT \fBGetPrivateData\fP ([annotation('_In_')] REFGUID guid, [annotation('_Inout_')] UINT *pDataSize, [annotation('_Out_writes_bytes_opt_( *pDataSize )')] void *pData)"
.br
.ti -1c
.RI "HRESULT \fBSetPrivateData\fP ([annotation('_In_')] REFGUID guid, [annotation('_In_')] UINT DataSize, [annotation('_In_reads_bytes_opt_( DataSize )')] const \fBvoid\fP *pData)"
.br
.ti -1c
.RI "HRESULT \fBSetPrivateDataInterface\fP ([annotation('_In_')] REFGUID guid, [annotation('_In_opt_')] const IUnknown *pData)"
.br
.ti -1c
.RI "HRESULT \fBSetName\fP ([annotation('_In_z_')] LPCWSTR Name)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "HRESULT ID3D12Device1::CreatePipelineLibrary ([annotation('_In_reads_(BlobLength)')] const \fBvoid\fP * pLibraryBlob, SIZE_T BlobLength, [in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP ** ppPipelineLibrary)"

.SS "HRESULT ID3D12Device1::SetEventOnMultipleFenceCompletion ([annotation('_In_reads_(NumFences)')] \fBID3D12Fence\fP *const * ppFences, [annotation('_In_reads_(NumFences)')] const UINT64 * pFenceValues, UINT NumFences, \fBD3D12_MULTIPLE_FENCE_WAIT_FLAGS\fP Flags, HANDLE hEvent)"

.SS "HRESULT ID3D12Device1::SetResidencyPriority (UINT NumObjects, [annotation('_In_reads_(NumObjects)')] \fBID3D12Pageable\fP *const * ppObjects, [annotation('_In_reads_(NumObjects)')] const \fBD3D12_RESIDENCY_PRIORITY\fP * pPriorities)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
