.TH "ieee_double_shape_type" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ieee_double_shape_type
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBvalue\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBlsw\fP"
.br
.ti -1c
.RI "   int \fBmsw\fP"
.br
.ti -1c
.RI "} \fBparts\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ieee_double_shape_type::lsw"

.SS "int ieee_double_shape_type::msw"

.SS "struct  { \&.\&.\&. }  ieee_double_shape_type::parts"

.SS "double ieee_double_shape_type::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
