.TH "ieee_float_shape_type" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ieee_float_shape_type
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBvalue\fP"
.br
.ti -1c
.RI "unsigned int \fBword\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Copyright (C) 1993 by Sun Microsystems, Inc\&. All rights reserved\&.
.PP
Developed at SunPro, a Sun Microsystems, Inc\&. business\&. Permission to use, copy, modify, and distribute this software is freely granted, provided that this notice is preserved\&. 
.SH "Member Data Documentation"
.PP 
.SS "float ieee_float_shape_type::value"

.SS "unsigned int ieee_float_shape_type::word"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
