.TH "ImFontGlyphRangesBuilder" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImFontGlyphRangesBuilder
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImFontGlyphRangesBuilder\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBClear\fP ()"
.br
.ti -1c
.RI "bool \fBGetBit\fP (size_t n) const"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetBit\fP (size_t n)"
.br
.ti -1c
.RI "\fBvoid\fP \fBAddChar\fP (\fBImWchar\fP c)"
.br
.ti -1c
.RI "\fBIMGUI_API\fP \fBvoid\fP \fBAddText\fP (const char *text, const char *text_end=NULL)"
.br
.ti -1c
.RI "\fBIMGUI_API\fP \fBvoid\fP \fBAddRanges\fP (const \fBImWchar\fP *ranges)"
.br
.ti -1c
.RI "\fBIMGUI_API\fP \fBvoid\fP \fBBuildRanges\fP (\fBImVector\fP< \fBImWchar\fP > *out_ranges)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVector\fP< \fBImU32\fP > \fBUsedChars\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImFontGlyphRangesBuilder::ImFontGlyphRangesBuilder ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP ImFontGlyphRangesBuilder::AddChar (\fBImWchar\fP c)\fR [inline]\fP"

.SS "\fBvoid\fP ImFontGlyphRangesBuilder::AddRanges (const \fBImWchar\fP * ranges)"

.SS "\fBvoid\fP ImFontGlyphRangesBuilder::AddText (const char * text, const char * text_end = \fRNULL\fP)"

.SS "\fBvoid\fP ImFontGlyphRangesBuilder::BuildRanges (\fBImVector\fP< \fBImWchar\fP > * out_ranges)"

.SS "\fBvoid\fP ImFontGlyphRangesBuilder::Clear ()\fR [inline]\fP"

.SS "bool ImFontGlyphRangesBuilder::GetBit (size_t n) const\fR [inline]\fP"

.SS "\fBvoid\fP ImFontGlyphRangesBuilder::SetBit (size_t n)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImVector\fP<\fBImU32\fP> ImFontGlyphRangesBuilder::UsedChars"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
