.TH "ImGL3WProcs" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGL3WProcs
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_impl_opengl3_loader\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGL3WglProc\fP \fBptr\fP [59]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   PFNGLACTIVETEXTUREPROC \fBActiveTexture\fP"
.br
.ti -1c
.RI "   PFNGLATTACHSHADERPROC \fBAttachShader\fP"
.br
.ti -1c
.RI "   PFNGLBINDBUFFERPROC \fBBindBuffer\fP"
.br
.ti -1c
.RI "   PFNGLBINDSAMPLERPROC \fBBindSampler\fP"
.br
.ti -1c
.RI "   PFNGLBINDTEXTUREPROC \fBBindTexture\fP"
.br
.ti -1c
.RI "   PFNGLBINDVERTEXARRAYPROC \fBBindVertexArray\fP"
.br
.ti -1c
.RI "   PFNGLBLENDEQUATIONPROC \fBBlendEquation\fP"
.br
.ti -1c
.RI "   PFNGLBLENDEQUATIONSEPARATEPROC \fBBlendEquationSeparate\fP"
.br
.ti -1c
.RI "   PFNGLBLENDFUNCSEPARATEPROC \fBBlendFuncSeparate\fP"
.br
.ti -1c
.RI "   PFNGLBUFFERDATAPROC \fBBufferData\fP"
.br
.ti -1c
.RI "   PFNGLBUFFERSUBDATAPROC \fBBufferSubData\fP"
.br
.ti -1c
.RI "   PFNGLCLEARPROC \fBClear\fP"
.br
.ti -1c
.RI "   PFNGLCLEARCOLORPROC \fBClearColor\fP"
.br
.ti -1c
.RI "   PFNGLCOMPILESHADERPROC \fBCompileShader\fP"
.br
.ti -1c
.RI "   PFNGLCREATEPROGRAMPROC \fBCreateProgram\fP"
.br
.ti -1c
.RI "   PFNGLCREATESHADERPROC \fBCreateShader\fP"
.br
.ti -1c
.RI "   PFNGLDELETEBUFFERSPROC \fBDeleteBuffers\fP"
.br
.ti -1c
.RI "   PFNGLDELETEPROGRAMPROC \fBDeleteProgram\fP"
.br
.ti -1c
.RI "   PFNGLDELETESHADERPROC \fBDeleteShader\fP"
.br
.ti -1c
.RI "   PFNGLDELETETEXTURESPROC \fBDeleteTextures\fP"
.br
.ti -1c
.RI "   PFNGLDELETEVERTEXARRAYSPROC \fBDeleteVertexArrays\fP"
.br
.ti -1c
.RI "   PFNGLDETACHSHADERPROC \fBDetachShader\fP"
.br
.ti -1c
.RI "   PFNGLDISABLEPROC \fBDisable\fP"
.br
.ti -1c
.RI "   PFNGLDISABLEVERTEXATTRIBARRAYPROC \fBDisableVertexAttribArray\fP"
.br
.ti -1c
.RI "   PFNGLDRAWELEMENTSPROC \fBDrawElements\fP"
.br
.ti -1c
.RI "   PFNGLDRAWELEMENTSBASEVERTEXPROC \fBDrawElementsBaseVertex\fP"
.br
.ti -1c
.RI "   PFNGLENABLEPROC \fBEnable\fP"
.br
.ti -1c
.RI "   PFNGLENABLEVERTEXATTRIBARRAYPROC \fBEnableVertexAttribArray\fP"
.br
.ti -1c
.RI "   PFNGLFLUSHPROC \fBFlush\fP"
.br
.ti -1c
.RI "   PFNGLGENBUFFERSPROC \fBGenBuffers\fP"
.br
.ti -1c
.RI "   PFNGLGENTEXTURESPROC \fBGenTextures\fP"
.br
.ti -1c
.RI "   PFNGLGENVERTEXARRAYSPROC \fBGenVertexArrays\fP"
.br
.ti -1c
.RI "   PFNGLGETATTRIBLOCATIONPROC \fBGetAttribLocation\fP"
.br
.ti -1c
.RI "   PFNGLGETERRORPROC \fBGetError\fP"
.br
.ti -1c
.RI "   PFNGLGETINTEGERVPROC \fBGetIntegerv\fP"
.br
.ti -1c
.RI "   PFNGLGETPROGRAMINFOLOGPROC \fBGetProgramInfoLog\fP"
.br
.ti -1c
.RI "   PFNGLGETPROGRAMIVPROC \fBGetProgramiv\fP"
.br
.ti -1c
.RI "   PFNGLGETSHADERINFOLOGPROC \fBGetShaderInfoLog\fP"
.br
.ti -1c
.RI "   PFNGLGETSHADERIVPROC \fBGetShaderiv\fP"
.br
.ti -1c
.RI "   \fBPFNGLGETSTRINGPROC\fP \fBGetString\fP"
.br
.ti -1c
.RI "   \fBPFNGLGETSTRINGIPROC\fP \fBGetStringi\fP"
.br
.ti -1c
.RI "   PFNGLGETUNIFORMLOCATIONPROC \fBGetUniformLocation\fP"
.br
.ti -1c
.RI "   PFNGLGETVERTEXATTRIBPOINTERVPROC \fBGetVertexAttribPointerv\fP"
.br
.ti -1c
.RI "   PFNGLGETVERTEXATTRIBIVPROC \fBGetVertexAttribiv\fP"
.br
.ti -1c
.RI "   PFNGLISENABLEDPROC \fBIsEnabled\fP"
.br
.ti -1c
.RI "   PFNGLISPROGRAMPROC \fBIsProgram\fP"
.br
.ti -1c
.RI "   PFNGLLINKPROGRAMPROC \fBLinkProgram\fP"
.br
.ti -1c
.RI "   PFNGLPIXELSTOREIPROC \fBPixelStorei\fP"
.br
.ti -1c
.RI "   PFNGLPOLYGONMODEPROC \fBPolygonMode\fP"
.br
.ti -1c
.RI "   PFNGLREADPIXELSPROC \fBReadPixels\fP"
.br
.ti -1c
.RI "   PFNGLSCISSORPROC \fBScissor\fP"
.br
.ti -1c
.RI "   PFNGLSHADERSOURCEPROC \fBShaderSource\fP"
.br
.ti -1c
.RI "   PFNGLTEXIMAGE2DPROC \fBTexImage2D\fP"
.br
.ti -1c
.RI "   PFNGLTEXPARAMETERIPROC \fBTexParameteri\fP"
.br
.ti -1c
.RI "   PFNGLUNIFORM1IPROC \fBUniform1i\fP"
.br
.ti -1c
.RI "   PFNGLUNIFORMMATRIX4FVPROC \fBUniformMatrix4fv\fP"
.br
.ti -1c
.RI "   PFNGLUSEPROGRAMPROC \fBUseProgram\fP"
.br
.ti -1c
.RI "   PFNGLVERTEXATTRIBPOINTERPROC \fBVertexAttribPointer\fP"
.br
.ti -1c
.RI "   PFNGLVIEWPORTPROC \fBViewport\fP"
.br
.ti -1c
.RI "} \fBgl\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "PFNGLACTIVETEXTUREPROC ImGL3WProcs::ActiveTexture"

.SS "PFNGLATTACHSHADERPROC ImGL3WProcs::AttachShader"

.SS "PFNGLBINDBUFFERPROC ImGL3WProcs::BindBuffer"

.SS "PFNGLBINDSAMPLERPROC ImGL3WProcs::BindSampler"

.SS "PFNGLBINDTEXTUREPROC ImGL3WProcs::BindTexture"

.SS "PFNGLBINDVERTEXARRAYPROC ImGL3WProcs::BindVertexArray"

.SS "PFNGLBLENDEQUATIONPROC ImGL3WProcs::BlendEquation"

.SS "PFNGLBLENDEQUATIONSEPARATEPROC ImGL3WProcs::BlendEquationSeparate"

.SS "PFNGLBLENDFUNCSEPARATEPROC ImGL3WProcs::BlendFuncSeparate"

.SS "PFNGLBUFFERDATAPROC ImGL3WProcs::BufferData"

.SS "PFNGLBUFFERSUBDATAPROC ImGL3WProcs::BufferSubData"

.SS "PFNGLCLEARPROC ImGL3WProcs::Clear"

.SS "PFNGLCLEARCOLORPROC ImGL3WProcs::ClearColor"

.SS "PFNGLCOMPILESHADERPROC ImGL3WProcs::CompileShader"

.SS "PFNGLCREATEPROGRAMPROC ImGL3WProcs::CreateProgram"

.SS "PFNGLCREATESHADERPROC ImGL3WProcs::CreateShader"

.SS "PFNGLDELETEBUFFERSPROC ImGL3WProcs::DeleteBuffers"

.SS "PFNGLDELETEPROGRAMPROC ImGL3WProcs::DeleteProgram"

.SS "PFNGLDELETESHADERPROC ImGL3WProcs::DeleteShader"

.SS "PFNGLDELETETEXTURESPROC ImGL3WProcs::DeleteTextures"

.SS "PFNGLDELETEVERTEXARRAYSPROC ImGL3WProcs::DeleteVertexArrays"

.SS "PFNGLDETACHSHADERPROC ImGL3WProcs::DetachShader"

.SS "PFNGLDISABLEPROC ImGL3WProcs::Disable"

.SS "PFNGLDISABLEVERTEXATTRIBARRAYPROC ImGL3WProcs::DisableVertexAttribArray"

.SS "PFNGLDRAWELEMENTSPROC ImGL3WProcs::DrawElements"

.SS "PFNGLDRAWELEMENTSBASEVERTEXPROC ImGL3WProcs::DrawElementsBaseVertex"

.SS "PFNGLENABLEPROC ImGL3WProcs::Enable"

.SS "PFNGLENABLEVERTEXATTRIBARRAYPROC ImGL3WProcs::EnableVertexAttribArray"

.SS "PFNGLFLUSHPROC ImGL3WProcs::Flush"

.SS "PFNGLGENBUFFERSPROC ImGL3WProcs::GenBuffers"

.SS "PFNGLGENTEXTURESPROC ImGL3WProcs::GenTextures"

.SS "PFNGLGENVERTEXARRAYSPROC ImGL3WProcs::GenVertexArrays"

.SS "PFNGLGETATTRIBLOCATIONPROC ImGL3WProcs::GetAttribLocation"

.SS "PFNGLGETERRORPROC ImGL3WProcs::GetError"

.SS "PFNGLGETINTEGERVPROC ImGL3WProcs::GetIntegerv"

.SS "PFNGLGETPROGRAMINFOLOGPROC ImGL3WProcs::GetProgramInfoLog"

.SS "PFNGLGETPROGRAMIVPROC ImGL3WProcs::GetProgramiv"

.SS "PFNGLGETSHADERINFOLOGPROC ImGL3WProcs::GetShaderInfoLog"

.SS "PFNGLGETSHADERIVPROC ImGL3WProcs::GetShaderiv"

.SS "\fBPFNGLGETSTRINGPROC\fP ImGL3WProcs::GetString"

.SS "\fBPFNGLGETSTRINGIPROC\fP ImGL3WProcs::GetStringi"

.SS "PFNGLGETUNIFORMLOCATIONPROC ImGL3WProcs::GetUniformLocation"

.SS "PFNGLGETVERTEXATTRIBIVPROC ImGL3WProcs::GetVertexAttribiv"

.SS "PFNGLGETVERTEXATTRIBPOINTERVPROC ImGL3WProcs::GetVertexAttribPointerv"

.SS "struct  { \&.\&.\&. }  ImGL3WProcs::gl"

.SS "PFNGLISENABLEDPROC ImGL3WProcs::IsEnabled"

.SS "PFNGLISPROGRAMPROC ImGL3WProcs::IsProgram"

.SS "PFNGLLINKPROGRAMPROC ImGL3WProcs::LinkProgram"

.SS "PFNGLPIXELSTOREIPROC ImGL3WProcs::PixelStorei"

.SS "PFNGLPOLYGONMODEPROC ImGL3WProcs::PolygonMode"

.SS "\fBGL3WglProc\fP ImGL3WProcs::ptr[59]"

.SS "PFNGLREADPIXELSPROC ImGL3WProcs::ReadPixels"

.SS "PFNGLSCISSORPROC ImGL3WProcs::Scissor"

.SS "PFNGLSHADERSOURCEPROC ImGL3WProcs::ShaderSource"

.SS "PFNGLTEXIMAGE2DPROC ImGL3WProcs::TexImage2D"

.SS "PFNGLTEXPARAMETERIPROC ImGL3WProcs::TexParameteri"

.SS "PFNGLUNIFORM1IPROC ImGL3WProcs::Uniform1i"

.SS "PFNGLUNIFORMMATRIX4FVPROC ImGL3WProcs::UniformMatrix4fv"

.SS "PFNGLUSEPROGRAMPROC ImGL3WProcs::UseProgram"

.SS "PFNGLVERTEXATTRIBPOINTERPROC ImGL3WProcs::VertexAttribPointer"

.SS "PFNGLVIEWPORTPROC ImGL3WProcs::Viewport"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
