.TH "ImGuiViewportP" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiViewportP
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.PP
Inherits \fBImGuiViewport\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiViewportP\fP ()"
.br
.ti -1c
.RI "\fB~ImGuiViewportP\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBClearRequestFlags\fP ()"
.br
.ti -1c
.RI "\fBImVec2\fP \fBCalcWorkRectPos\fP (const \fBImVec2\fP &inset_min) const"
.br
.ti -1c
.RI "\fBImVec2\fP \fBCalcWorkRectSize\fP (const \fBImVec2\fP &inset_min, const \fBImVec2\fP &inset_max) const"
.br
.ti -1c
.RI "\fBvoid\fP \fBUpdateWorkRect\fP ()"
.br
.ti -1c
.RI "\fBImRect\fP \fBGetMainRect\fP () const"
.br
.ti -1c
.RI "\fBImRect\fP \fBGetWorkRect\fP () const"
.br
.ti -1c
.RI "\fBImRect\fP \fBGetBuildWorkRect\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBImGuiViewport\fP
.in +1c
.ti -1c
.RI "\fBImGuiViewport\fP ()"
.br
.ti -1c
.RI "\fB~ImGuiViewport\fP ()"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGetCenter\fP () const"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGetWorkCenter\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiWindow\fP * \fBWindow\fP"
.br
.ti -1c
.RI "int \fBIdx\fP"
.br
.ti -1c
.RI "int \fBLastFrameActive\fP"
.br
.ti -1c
.RI "int \fBLastFocusedStampCount\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBLastNameHash\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLastPos\fP"
.br
.ti -1c
.RI "float \fBAlpha\fP"
.br
.ti -1c
.RI "float \fBLastAlpha\fP"
.br
.ti -1c
.RI "bool \fBLastFocusedHadNavWindow\fP"
.br
.ti -1c
.RI "short \fBPlatformMonitor\fP"
.br
.ti -1c
.RI "int \fBBgFgDrawListsLastFrame\fP [2]"
.br
.ti -1c
.RI "\fBImDrawList\fP * \fBBgFgDrawLists\fP [2]"
.br
.ti -1c
.RI "\fBImDrawData\fP \fBDrawDataP\fP"
.br
.ti -1c
.RI "\fBImDrawDataBuilder\fP \fBDrawDataBuilder\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLastPlatformPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLastPlatformSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLastRendererSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWorkInsetMin\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWorkInsetMax\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBuildWorkInsetMin\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBuildWorkInsetMax\fP"
.br
.in -1c

Public Attributes inherited from \fBImGuiViewport\fP
.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBID\fP"
.br
.ti -1c
.RI "\fBImGuiViewportFlags\fP \fBFlags\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWorkPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWorkSize\fP"
.br
.ti -1c
.RI "float \fBDpiScale\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBParentViewportId\fP"
.br
.ti -1c
.RI "\fBImDrawData\fP * \fBDrawData\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBRendererUserData\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBPlatformUserData\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBPlatformHandle\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBPlatformHandleRaw\fP"
.br
.ti -1c
.RI "bool \fBPlatformWindowCreated\fP"
.br
.ti -1c
.RI "bool \fBPlatformRequestMove\fP"
.br
.ti -1c
.RI "bool \fBPlatformRequestResize\fP"
.br
.ti -1c
.RI "bool \fBPlatformRequestClose\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiViewportP::ImGuiViewportP ()\fR [inline]\fP"

.SS "ImGuiViewportP::~ImGuiViewportP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBImVec2\fP ImGuiViewportP::CalcWorkRectPos (const \fBImVec2\fP & inset_min) const\fR [inline]\fP"

.SS "\fBImVec2\fP ImGuiViewportP::CalcWorkRectSize (const \fBImVec2\fP & inset_min, const \fBImVec2\fP & inset_max) const\fR [inline]\fP"

.SS "\fBvoid\fP ImGuiViewportP::ClearRequestFlags ()\fR [inline]\fP"

.SS "\fBImRect\fP ImGuiViewportP::GetBuildWorkRect () const\fR [inline]\fP"

.SS "\fBImRect\fP ImGuiViewportP::GetMainRect () const\fR [inline]\fP"

.SS "\fBImRect\fP ImGuiViewportP::GetWorkRect () const\fR [inline]\fP"

.SS "\fBvoid\fP ImGuiViewportP::UpdateWorkRect ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float ImGuiViewportP::Alpha"

.SS "\fBImDrawList\fP* ImGuiViewportP::BgFgDrawLists[2]"

.SS "int ImGuiViewportP::BgFgDrawListsLastFrame[2]"

.SS "\fBImVec2\fP ImGuiViewportP::BuildWorkInsetMax"

.SS "\fBImVec2\fP ImGuiViewportP::BuildWorkInsetMin"

.SS "\fBImDrawDataBuilder\fP ImGuiViewportP::DrawDataBuilder"

.SS "\fBImDrawData\fP ImGuiViewportP::DrawDataP"

.SS "int ImGuiViewportP::Idx"

.SS "float ImGuiViewportP::LastAlpha"

.SS "bool ImGuiViewportP::LastFocusedHadNavWindow"

.SS "int ImGuiViewportP::LastFocusedStampCount"

.SS "int ImGuiViewportP::LastFrameActive"

.SS "\fBImGuiID\fP ImGuiViewportP::LastNameHash"

.SS "\fBImVec2\fP ImGuiViewportP::LastPlatformPos"

.SS "\fBImVec2\fP ImGuiViewportP::LastPlatformSize"

.SS "\fBImVec2\fP ImGuiViewportP::LastPos"

.SS "\fBImVec2\fP ImGuiViewportP::LastRendererSize"

.SS "short ImGuiViewportP::PlatformMonitor"

.SS "\fBImGuiWindow\fP* ImGuiViewportP::Window"

.SS "\fBImVec2\fP ImGuiViewportP::WorkInsetMax"

.SS "\fBImVec2\fP ImGuiViewportP::WorkInsetMin"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
