.TH "ImGuiPlatformImeData" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiPlatformImeData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiPlatformImeData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBWantVisible\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBInputPos\fP"
.br
.ti -1c
.RI "float \fBInputLineHeight\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiPlatformImeData::ImGuiPlatformImeData ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float ImGuiPlatformImeData::InputLineHeight"

.SS "\fBImVec2\fP ImGuiPlatformImeData::InputPos"

.SS "bool ImGuiPlatformImeData::WantVisible"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
