.TH "ImGuiPlatformMonitor" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiPlatformMonitor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiPlatformMonitor\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVec2\fP \fBMainPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBMainSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWorkPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWorkSize\fP"
.br
.ti -1c
.RI "float \fBDpiScale\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBPlatformHandle\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiPlatformMonitor::ImGuiPlatformMonitor ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float ImGuiPlatformMonitor::DpiScale"

.SS "\fBImVec2\fP ImGuiPlatformMonitor::MainPos"

.SS "\fBImVec2\fP ImGuiPlatformMonitor::MainSize"

.SS "\fBvoid\fP* ImGuiPlatformMonitor::PlatformHandle"

.SS "\fBImVec2\fP ImGuiPlatformMonitor::WorkPos"

.SS "\fBImVec2\fP ImGuiPlatformMonitor::WorkSize"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
