.TH "UPRISE_ENGINE/imgui_impl_opengl3.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/imgui_impl_opengl3.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'imgui\&.h'\fP
.br
\fR#include 'imgui_impl_opengl3\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include 'imgui_impl_opengl3_loader\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBImGui_ImplOpenGL3_Data\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIMGL3W_IMPL\fP"
.br
.ti -1c
.RI "#define \fBIMGUI_IMPL_OPENGL_USE_VERTEX_ARRAY\fP"
.br
.ti -1c
.RI "#define \fBIMGUI_IMPL_OPENGL_HAS_EXTENSIONS\fP"
.br
.ti -1c
.RI "#define \fBIMGUI_IMPL_OPENGL_MAY_HAVE_POLYGON_MODE\fP"
.br
.ti -1c
.RI "#define \fBIMGUI_IMPL_OPENGL_MAY_HAVE_BIND_BUFFER_PIXEL_UNPACK\fP"
.br
.ti -1c
.RI "#define \fBGL_CALL\fP(_CALL)   _CALL"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBImGui_ImplOpenGL3_Init\fP (const char *glsl_version)"
.br
.ti -1c
.RI "void \fBImGui_ImplOpenGL3_Shutdown\fP ()"
.br
.ti -1c
.RI "void \fBImGui_ImplOpenGL3_NewFrame\fP ()"
.br
.ti -1c
.RI "void \fBImGui_ImplOpenGL3_RenderDrawData\fP (ImDrawData *draw_data)"
.br
.ti -1c
.RI "bool \fBImGui_ImplOpenGL3_CreateFontsTexture\fP ()"
.br
.ti -1c
.RI "void \fBImGui_ImplOpenGL3_DestroyFontsTexture\fP ()"
.br
.ti -1c
.RI "bool \fBImGui_ImplOpenGL3_CreateDeviceObjects\fP ()"
.br
.ti -1c
.RI "void \fBImGui_ImplOpenGL3_DestroyDeviceObjects\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GL_CALL( _CALL)   _CALL"

.PP
Definition at line \fB218\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_CreateFontsTexture()\fP, and \fBImGui_ImplOpenGL3_RenderDrawData()\fP\&.
.SS "#define IMGL3W_IMPL"

.PP
Definition at line \fB170\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.SS "#define IMGUI_IMPL_OPENGL_HAS_EXTENSIONS"

.PP
Definition at line \fB188\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.SS "#define IMGUI_IMPL_OPENGL_MAY_HAVE_BIND_BUFFER_PIXEL_UNPACK"

.PP
Definition at line \fB194\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.SS "#define IMGUI_IMPL_OPENGL_MAY_HAVE_POLYGON_MODE"

.PP
Definition at line \fB189\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.SS "#define IMGUI_IMPL_OPENGL_USE_VERTEX_ARRAY"

.PP
Definition at line \fB176\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "bool ImGui_ImplOpenGL3_CreateDeviceObjects ()"

.PP
Definition at line \fB759\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.nf
760 {
761     ImGui_ImplOpenGL3_Data* bd = ImGui_ImplOpenGL3_GetBackendData();
762 
763     // Backup GL state
764     GLint last_texture, last_array_buffer;
765     glGetIntegerv(GL_TEXTURE_BINDING_2D, &last_texture);
766     glGetIntegerv(GL_ARRAY_BUFFER_BINDING, &last_array_buffer);
767 #ifdef IMGUI_IMPL_OPENGL_MAY_HAVE_BIND_BUFFER_PIXEL_UNPACK
768     GLint last_pixel_unpack_buffer = 0;
769     if (bd\->GlVersion >= 210) { glGetIntegerv(GL_PIXEL_UNPACK_BUFFER_BINDING, &last_pixel_unpack_buffer); glBindBuffer(GL_PIXEL_UNPACK_BUFFER, 0); }
770 #endif
771 #ifdef IMGUI_IMPL_OPENGL_USE_VERTEX_ARRAY
772     GLint last_vertex_array;
773     glGetIntegerv(GL_VERTEX_ARRAY_BINDING, &last_vertex_array);
774 #endif
775 
776     // Parse GLSL version string
777     int glsl_version = 130;
778     sscanf(bd\->GlslVersionString, "#version %d", &glsl_version);
779 
780     const GLchar* vertex_shader_glsl_120 =
781         "uniform mat4 ProjMtx;\\n"
782         "attribute vec2 Position;\\n"
783         "attribute vec2 UV;\\n"
784         "attribute vec4 Color;\\n"
785         "varying vec2 Frag_UV;\\n"
786         "varying vec4 Frag_Color;\\n"
787         "void main()\\n"
788         "{\\n"
789         "    Frag_UV = UV;\\n"
790         "    Frag_Color = Color;\\n"
791         "    gl_Position = ProjMtx * vec4(Position\&.xy,0,1);\\n"
792         "}\\n";
793 
794     const GLchar* vertex_shader_glsl_130 =
795         "uniform mat4 ProjMtx;\\n"
796         "in vec2 Position;\\n"
797         "in vec2 UV;\\n"
798         "in vec4 Color;\\n"
799         "out vec2 Frag_UV;\\n"
800         "out vec4 Frag_Color;\\n"
801         "void main()\\n"
802         "{\\n"
803         "    Frag_UV = UV;\\n"
804         "    Frag_Color = Color;\\n"
805         "    gl_Position = ProjMtx * vec4(Position\&.xy,0,1);\\n"
806         "}\\n";
807 
808     const GLchar* vertex_shader_glsl_300_es =
809         "precision highp float;\\n"
810         "layout (location = 0) in vec2 Position;\\n"
811         "layout (location = 1) in vec2 UV;\\n"
812         "layout (location = 2) in vec4 Color;\\n"
813         "uniform mat4 ProjMtx;\\n"
814         "out vec2 Frag_UV;\\n"
815         "out vec4 Frag_Color;\\n"
816         "void main()\\n"
817         "{\\n"
818         "    Frag_UV = UV;\\n"
819         "    Frag_Color = Color;\\n"
820         "    gl_Position = ProjMtx * vec4(Position\&.xy,0,1);\\n"
821         "}\\n";
822 
823     const GLchar* vertex_shader_glsl_410_core =
824         "layout (location = 0) in vec2 Position;\\n"
825         "layout (location = 1) in vec2 UV;\\n"
826         "layout (location = 2) in vec4 Color;\\n"
827         "uniform mat4 ProjMtx;\\n"
828         "out vec2 Frag_UV;\\n"
829         "out vec4 Frag_Color;\\n"
830         "void main()\\n"
831         "{\\n"
832         "    Frag_UV = UV;\\n"
833         "    Frag_Color = Color;\\n"
834         "    gl_Position = ProjMtx * vec4(Position\&.xy,0,1);\\n"
835         "}\\n";
836 
837     const GLchar* fragment_shader_glsl_120 =
838         "#ifdef GL_ES\\n"
839         "    precision mediump float;\\n"
840         "#endif\\n"
841         "uniform sampler2D Texture;\\n"
842         "varying vec2 Frag_UV;\\n"
843         "varying vec4 Frag_Color;\\n"
844         "void main()\\n"
845         "{\\n"
846         "    gl_FragColor = Frag_Color * texture2D(Texture, Frag_UV\&.st);\\n"
847         "}\\n";
848 
849     const GLchar* fragment_shader_glsl_130 =
850         "uniform sampler2D Texture;\\n"
851         "in vec2 Frag_UV;\\n"
852         "in vec4 Frag_Color;\\n"
853         "out vec4 Out_Color;\\n"
854         "void main()\\n"
855         "{\\n"
856         "    Out_Color = Frag_Color * texture(Texture, Frag_UV\&.st);\\n"
857         "}\\n";
858 
859     const GLchar* fragment_shader_glsl_300_es =
860         "precision mediump float;\\n"
861         "uniform sampler2D Texture;\\n"
862         "in vec2 Frag_UV;\\n"
863         "in vec4 Frag_Color;\\n"
864         "layout (location = 0) out vec4 Out_Color;\\n"
865         "void main()\\n"
866         "{\\n"
867         "    Out_Color = Frag_Color * texture(Texture, Frag_UV\&.st);\\n"
868         "}\\n";
869 
870     const GLchar* fragment_shader_glsl_410_core =
871         "in vec2 Frag_UV;\\n"
872         "in vec4 Frag_Color;\\n"
873         "uniform sampler2D Texture;\\n"
874         "layout (location = 0) out vec4 Out_Color;\\n"
875         "void main()\\n"
876         "{\\n"
877         "    Out_Color = Frag_Color * texture(Texture, Frag_UV\&.st);\\n"
878         "}\\n";
879 
880     // Select shaders matching our GLSL versions
881     const GLchar* vertex_shader = nullptr;
882     const GLchar* fragment_shader = nullptr;
883     if (glsl_version < 130)
884     {
885         vertex_shader = vertex_shader_glsl_120;
886         fragment_shader = fragment_shader_glsl_120;
887     }
888     else if (glsl_version >= 410)
889     {
890         vertex_shader = vertex_shader_glsl_410_core;
891         fragment_shader = fragment_shader_glsl_410_core;
892     }
893     else if (glsl_version == 300)
894     {
895         vertex_shader = vertex_shader_glsl_300_es;
896         fragment_shader = fragment_shader_glsl_300_es;
897     }
898     else
899     {
900         vertex_shader = vertex_shader_glsl_130;
901         fragment_shader = fragment_shader_glsl_130;
902     }
903 
904     // Create shaders
905     const GLchar* vertex_shader_with_version[2] = { bd\->GlslVersionString, vertex_shader };
906     GLuint vert_handle = glCreateShader(GL_VERTEX_SHADER);
907     glShaderSource(vert_handle, 2, vertex_shader_with_version, nullptr);
908     glCompileShader(vert_handle);
909     CheckShader(vert_handle, "vertex shader");
910 
911     const GLchar* fragment_shader_with_version[2] = { bd\->GlslVersionString, fragment_shader };
912     GLuint frag_handle = glCreateShader(GL_FRAGMENT_SHADER);
913     glShaderSource(frag_handle, 2, fragment_shader_with_version, nullptr);
914     glCompileShader(frag_handle);
915     CheckShader(frag_handle, "fragment shader");
916 
917     // Link
918     bd\->ShaderHandle = glCreateProgram();
919     glAttachShader(bd\->ShaderHandle, vert_handle);
920     glAttachShader(bd\->ShaderHandle, frag_handle);
921     glLinkProgram(bd\->ShaderHandle);
922     CheckProgram(bd\->ShaderHandle, "shader program");
923 
924     glDetachShader(bd\->ShaderHandle, vert_handle);
925     glDetachShader(bd\->ShaderHandle, frag_handle);
926     glDeleteShader(vert_handle);
927     glDeleteShader(frag_handle);
928 
929     bd\->AttribLocationTex = glGetUniformLocation(bd\->ShaderHandle, "Texture");
930     bd\->AttribLocationProjMtx = glGetUniformLocation(bd\->ShaderHandle, "ProjMtx");
931     bd\->AttribLocationVtxPos = (GLuint)glGetAttribLocation(bd\->ShaderHandle, "Position");
932     bd\->AttribLocationVtxUV = (GLuint)glGetAttribLocation(bd\->ShaderHandle, "UV");
933     bd\->AttribLocationVtxColor = (GLuint)glGetAttribLocation(bd\->ShaderHandle, "Color");
934 
935     // Create buffers
936     glGenBuffers(1, &bd\->VboHandle);
937     glGenBuffers(1, &bd\->ElementsHandle);
938 
939     ImGui_ImplOpenGL3_CreateFontsTexture();
940 
941     // Restore modified GL state
942     glBindTexture(GL_TEXTURE_2D, last_texture);
943     glBindBuffer(GL_ARRAY_BUFFER, last_array_buffer);
944 #ifdef IMGUI_IMPL_OPENGL_MAY_HAVE_BIND_BUFFER_PIXEL_UNPACK
945     if (bd\->GlVersion >= 210) { glBindBuffer(GL_PIXEL_UNPACK_BUFFER, last_pixel_unpack_buffer); }
946 #endif
947 #ifdef IMGUI_IMPL_OPENGL_USE_VERTEX_ARRAY
948     glBindVertexArray(last_vertex_array);
949 #endif
950 
951     return true;
952 }
.PP
.fi

.PP
References \fBImGui_ImplOpenGL3_Data::AttribLocationProjMtx\fP, \fBImGui_ImplOpenGL3_Data::AttribLocationTex\fP, \fBImGui_ImplOpenGL3_Data::AttribLocationVtxColor\fP, \fBImGui_ImplOpenGL3_Data::AttribLocationVtxPos\fP, \fBImGui_ImplOpenGL3_Data::AttribLocationVtxUV\fP, \fBImGui_ImplOpenGL3_Data::ElementsHandle\fP, \fBImGui_ImplOpenGL3_Data::GlslVersionString\fP, \fBImGui_ImplOpenGL3_Data::GlVersion\fP, \fBImGui_ImplOpenGL3_CreateFontsTexture()\fP, \fBImGui_ImplOpenGL3_Data::ShaderHandle\fP, and \fBImGui_ImplOpenGL3_Data::VboHandle\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_NewFrame()\fP\&.
.SS "bool ImGui_ImplOpenGL3_CreateFontsTexture ()"

.PP
Definition at line \fB677\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.nf
678 {
679     ImGuiIO& io = ImGui::GetIO();
680     ImGui_ImplOpenGL3_Data* bd = ImGui_ImplOpenGL3_GetBackendData();
681 
682     // Build texture atlas
683     unsigned char* pixels;
684     int width, height;
685     io\&.Fonts\->GetTexDataAsRGBA32(&pixels, &width, &height);   // Load as RGBA 32\-bit (75% of the memory is wasted, but default font is so small) because it is more likely to be compatible with user's existing shaders\&. If your ImTextureId represent a higher\-level concept than just a GL texture id, consider calling GetTexDataAsAlpha8() instead to save on GPU memory\&.
686 
687     // Upload texture to graphics system
688     // (Bilinear sampling is required by default\&. Set 'io\&.Fonts\->Flags |= ImFontAtlasFlags_NoBakedLines' or 'style\&.AntiAliasedLinesUseTex = false' to allow point/nearest sampling)
689     GLint last_texture;
690     GL_CALL(glGetIntegerv(GL_TEXTURE_BINDING_2D, &last_texture));
691     GL_CALL(glGenTextures(1, &bd\->FontTexture));
692     GL_CALL(glBindTexture(GL_TEXTURE_2D, bd\->FontTexture));
693     GL_CALL(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR));
694     GL_CALL(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR));
695 #ifdef GL_UNPACK_ROW_LENGTH // Not on WebGL/ES
696     GL_CALL(glPixelStorei(GL_UNPACK_ROW_LENGTH, 0));
697 #endif
698     GL_CALL(glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, pixels));
699 
700     // Store our identifier
701     io\&.Fonts\->SetTexID((ImTextureID)(intptr_t)bd\->FontTexture);
702 
703     // Restore state
704     GL_CALL(glBindTexture(GL_TEXTURE_2D, last_texture));
705 
706     return true;
707 }
.PP
.fi

.PP
References \fBImGui_ImplOpenGL3_Data::FontTexture\fP, and \fBGL_CALL\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_CreateDeviceObjects()\fP, and \fBImGui_ImplOpenGL3_NewFrame()\fP\&.
.SS "void ImGui_ImplOpenGL3_DestroyDeviceObjects ()"

.PP
Definition at line \fB954\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.nf
955 {
956     ImGui_ImplOpenGL3_Data* bd = ImGui_ImplOpenGL3_GetBackendData();
957     if (bd\->VboHandle)      { glDeleteBuffers(1, &bd\->VboHandle); bd\->VboHandle = 0; }
958     if (bd\->ElementsHandle) { glDeleteBuffers(1, &bd\->ElementsHandle); bd\->ElementsHandle = 0; }
959     if (bd\->ShaderHandle)   { glDeleteProgram(bd\->ShaderHandle); bd\->ShaderHandle = 0; }
960     ImGui_ImplOpenGL3_DestroyFontsTexture();
961 }
.PP
.fi

.PP
References \fBImGui_ImplOpenGL3_Data::ElementsHandle\fP, \fBImGui_ImplOpenGL3_DestroyFontsTexture()\fP, \fBImGui_ImplOpenGL3_Data::ShaderHandle\fP, and \fBImGui_ImplOpenGL3_Data::VboHandle\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_Shutdown()\fP\&.
.SS "void ImGui_ImplOpenGL3_DestroyFontsTexture ()"

.PP
Definition at line \fB709\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.nf
710 {
711     ImGuiIO& io = ImGui::GetIO();
712     ImGui_ImplOpenGL3_Data* bd = ImGui_ImplOpenGL3_GetBackendData();
713     if (bd\->FontTexture)
714     {
715         glDeleteTextures(1, &bd\->FontTexture);
716         io\&.Fonts\->SetTexID(0);
717         bd\->FontTexture = 0;
718     }
719 }
.PP
.fi

.PP
References \fBImGui_ImplOpenGL3_Data::FontTexture\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_DestroyDeviceObjects()\fP\&.
.SS "bool ImGui_ImplOpenGL3_Init (const char * glsl_version)"

.PP
Definition at line \fB283\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.nf
284 {
285     ImGuiIO& io = ImGui::GetIO();
286     IMGUI_CHECKVERSION();
287     IM_ASSERT(io\&.BackendRendererUserData == nullptr && "Already initialized a renderer backend!");
288 
289     // Initialize our loader
290 #if !defined(IMGUI_IMPL_OPENGL_ES2) && !defined(IMGUI_IMPL_OPENGL_ES3) && !defined(IMGUI_IMPL_OPENGL_LOADER_CUSTOM)
291     if (imgl3wInit() != 0)
292     {
293         fprintf(stderr, "Failed to initialize OpenGL loader!\\n");
294         return false;
295     }
296 #endif
297 
298     // Setup backend capabilities flags
299     ImGui_ImplOpenGL3_Data* bd = IM_NEW(ImGui_ImplOpenGL3_Data)();
300     io\&.BackendRendererUserData = (void*)bd;
301     io\&.BackendRendererName = "imgui_impl_opengl3";
302 
303     // Query for GL version (e\&.g\&. 320 for GL 3\&.2)
304 #if defined(IMGUI_IMPL_OPENGL_ES2)
305     // GLES 2
306     bd\->GlVersion = 200;
307     bd\->GlProfileIsES2 = true;
308 #else
309     // Desktop or GLES 3
310     const char* gl_version_str = (const char*)glGetString(GL_VERSION);
311     GLint major = 0;
312     GLint minor = 0;
313     glGetIntegerv(GL_MAJOR_VERSION, &major);
314     glGetIntegerv(GL_MINOR_VERSION, &minor);
315     if (major == 0 && minor == 0)
316         sscanf(gl_version_str, "%d\&.%d", &major, &minor); // Query GL_VERSION in desktop GL 2\&.x, the string will start with "<major>\&.<minor>"
317     bd\->GlVersion = (GLuint)(major * 100 + minor * 10);
318 #if defined(GL_CONTEXT_PROFILE_MASK)
319     if (bd\->GlVersion >= 320)
320         glGetIntegerv(GL_CONTEXT_PROFILE_MASK, &bd\->GlProfileMask);
321     bd\->GlProfileIsCompat = (bd\->GlProfileMask & GL_CONTEXT_COMPATIBILITY_PROFILE_BIT) != 0;
322 #endif
323 
324 #if defined(IMGUI_IMPL_OPENGL_ES3)
325     bd\->GlProfileIsES3 = true;
326 #else
327     if (strncmp(gl_version_str, "OpenGL ES 3", 11) == 0)
328         bd\->GlProfileIsES3 = true;
329 #endif
330 
331     bd\->UseBufferSubData = false;
332     /*
333     // Query vendor to enable glBufferSubData kludge
334 #ifdef _WIN32
335     if (const char* vendor = (const char*)glGetString(GL_VENDOR))
336         if (strncmp(vendor, "Intel", 5) == 0)
337             bd\->UseBufferSubData = true;
338 #endif
339     */
340 #endif
341 
342 #ifdef IMGUI_IMPL_OPENGL_DEBUG
343     printf("GlVersion = %d, \\"%s\\"\\nGlProfileIsCompat = %d\\nGlProfileMask = 0x%X\\nGlProfileIsES2 = %d, GlProfileIsES3 = %d\\nGL_VENDOR = '%s'\\nGL_RENDERER = '%s'\\n", bd\->GlVersion, gl_version_str, bd\->GlProfileIsCompat, bd\->GlProfileMask, bd\->GlProfileIsES2, bd\->GlProfileIsES3, (const char*)glGetString(GL_VENDOR), (const char*)glGetString(GL_RENDERER)); // [DEBUG]
344 #endif
345 
346 #ifdef IMGUI_IMPL_OPENGL_MAY_HAVE_VTX_OFFSET
347     if (bd\->GlVersion >= 320)
348         io\&.BackendFlags |= ImGuiBackendFlags_RendererHasVtxOffset;  // We can honor the ImDrawCmd::VtxOffset field, allowing for large meshes\&.
349 #endif
350     io\&.BackendFlags |= ImGuiBackendFlags_RendererHasViewports;  // We can create multi\-viewports on the Renderer side (optional)
351 
352     // Store GLSL version string so we can refer to it later in case we recreate shaders\&.
353     // Note: GLSL version is NOT the same as GL version\&. Leave this to nullptr if unsure\&.
354     if (glsl_version == nullptr)
355     {
356 #if defined(IMGUI_IMPL_OPENGL_ES2)
357         glsl_version = "#version 100";
358 #elif defined(IMGUI_IMPL_OPENGL_ES3)
359         glsl_version = "#version 300 es";
360 #elif defined(__APPLE__)
361         glsl_version = "#version 150";
362 #else
363         glsl_version = "#version 130";
364 #endif
365     }
366     IM_ASSERT((int)strlen(glsl_version) + 2 < IM_ARRAYSIZE(bd\->GlslVersionString));
367     strcpy(bd\->GlslVersionString, glsl_version);
368     strcat(bd\->GlslVersionString, "\\n");
369 
370     // Make an arbitrary GL call (we don't actually need the result)
371     // IF YOU GET A CRASH HERE: it probably means the OpenGL function loader didn't do its job\&. Let us know!
372     GLint current_texture;
373     glGetIntegerv(GL_TEXTURE_BINDING_2D, &current_texture);
374 
375     // Detect extensions we support
376 #ifdef IMGUI_IMPL_OPENGL_MAY_HAVE_POLYGON_MODE
377     bd\->HasPolygonMode = (!bd\->GlProfileIsES2 && !bd\->GlProfileIsES3);
378 #endif
379     bd\->HasClipOrigin = (bd\->GlVersion >= 450);
380 #ifdef IMGUI_IMPL_OPENGL_HAS_EXTENSIONS
381     GLint num_extensions = 0;
382     glGetIntegerv(GL_NUM_EXTENSIONS, &num_extensions);
383     for (GLint i = 0; i < num_extensions; i++)
384     {
385         const char* extension = (const char*)glGetStringi(GL_EXTENSIONS, i);
386         if (extension != nullptr && strcmp(extension, "GL_ARB_clip_control") == 0)
387             bd\->HasClipOrigin = true;
388     }
389 #endif
390 
391     if (io\&.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
392         ImGui_ImplOpenGL3_InitPlatformInterface();
393 
394     return true;
395 }
.PP
.fi

.PP
References \fBImGui_ImplOpenGL3_Data::GlProfileIsCompat\fP, \fBImGui_ImplOpenGL3_Data::GlProfileIsES2\fP, \fBImGui_ImplOpenGL3_Data::GlProfileIsES3\fP, \fBImGui_ImplOpenGL3_Data::GlProfileMask\fP, \fBImGui_ImplOpenGL3_Data::GlslVersionString\fP, \fBImGui_ImplOpenGL3_Data::GlVersion\fP, \fBImGui_ImplOpenGL3_Data::HasClipOrigin\fP, \fBImGui_ImplOpenGL3_Data::HasPolygonMode\fP, \fBi\fP, and \fBImGui_ImplOpenGL3_Data::UseBufferSubData\fP\&.
.PP
Referenced by \fBCORE::Startup::StartEditor()\fP\&.
.SS "void ImGui_ImplOpenGL3_NewFrame ()"

.PP
Definition at line \fB411\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.nf
412 {
413     ImGui_ImplOpenGL3_Data* bd = ImGui_ImplOpenGL3_GetBackendData();
414     IM_ASSERT(bd != nullptr && "Context or backend not initialized! Did you call ImGui_ImplOpenGL3_Init()?");
415 
416     if (!bd\->ShaderHandle)
417         ImGui_ImplOpenGL3_CreateDeviceObjects();
418     if (!bd\->FontTexture)
419         ImGui_ImplOpenGL3_CreateFontsTexture();
420 }
.PP
.fi

.PP
References \fBImGui_ImplOpenGL3_Data::FontTexture\fP, \fBImGui_ImplOpenGL3_CreateDeviceObjects()\fP, \fBImGui_ImplOpenGL3_CreateFontsTexture()\fP, and \fBImGui_ImplOpenGL3_Data::ShaderHandle\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "void ImGui_ImplOpenGL3_RenderDrawData (ImDrawData * draw_data)"

.PP
Definition at line \fB499\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.nf
500 {
501     // Avoid rendering when minimized, scale coordinates for retina displays (screen coordinates != framebuffer coordinates)
502     int fb_width = (int)(draw_data\->DisplaySize\&.x * draw_data\->FramebufferScale\&.x);
503     int fb_height = (int)(draw_data\->DisplaySize\&.y * draw_data\->FramebufferScale\&.y);
504     if (fb_width <= 0 || fb_height <= 0)
505         return;
506 
507     ImGui_ImplOpenGL3_Data* bd = ImGui_ImplOpenGL3_GetBackendData();
508 
509     // Backup GL state
510     GLenum last_active_texture; glGetIntegerv(GL_ACTIVE_TEXTURE, (GLint*)&last_active_texture);
511     glActiveTexture(GL_TEXTURE0);
512     GLuint last_program; glGetIntegerv(GL_CURRENT_PROGRAM, (GLint*)&last_program);
513     GLuint last_texture; glGetIntegerv(GL_TEXTURE_BINDING_2D, (GLint*)&last_texture);
514 #ifdef IMGUI_IMPL_OPENGL_MAY_HAVE_BIND_SAMPLER
515     GLuint last_sampler; if (bd\->GlVersion >= 330 || bd\->GlProfileIsES3) { glGetIntegerv(GL_SAMPLER_BINDING, (GLint*)&last_sampler); } else { last_sampler = 0; }
516 #endif
517     GLuint last_array_buffer; glGetIntegerv(GL_ARRAY_BUFFER_BINDING, (GLint*)&last_array_buffer);
518 #ifndef IMGUI_IMPL_OPENGL_USE_VERTEX_ARRAY
519     // This is part of VAO on OpenGL 3\&.0+ and OpenGL ES 3\&.0+\&.
520     GLint last_element_array_buffer; glGetIntegerv(GL_ELEMENT_ARRAY_BUFFER_BINDING, &last_element_array_buffer);
521     ImGui_ImplOpenGL3_VtxAttribState last_vtx_attrib_state_pos; last_vtx_attrib_state_pos\&.GetState(bd\->AttribLocationVtxPos);
522     ImGui_ImplOpenGL3_VtxAttribState last_vtx_attrib_state_uv; last_vtx_attrib_state_uv\&.GetState(bd\->AttribLocationVtxUV);
523     ImGui_ImplOpenGL3_VtxAttribState last_vtx_attrib_state_color; last_vtx_attrib_state_color\&.GetState(bd\->AttribLocationVtxColor);
524 #endif
525 #ifdef IMGUI_IMPL_OPENGL_USE_VERTEX_ARRAY
526     GLuint last_vertex_array_object; glGetIntegerv(GL_VERTEX_ARRAY_BINDING, (GLint*)&last_vertex_array_object);
527 #endif
528 #ifdef IMGUI_IMPL_OPENGL_MAY_HAVE_POLYGON_MODE
529     GLint last_polygon_mode[2]; if (bd\->HasPolygonMode) { glGetIntegerv(GL_POLYGON_MODE, last_polygon_mode); }
530 #endif
531     GLint last_viewport[4]; glGetIntegerv(GL_VIEWPORT, last_viewport);
532     GLint last_scissor_box[4]; glGetIntegerv(GL_SCISSOR_BOX, last_scissor_box);
533     GLenum last_blend_src_rgb; glGetIntegerv(GL_BLEND_SRC_RGB, (GLint*)&last_blend_src_rgb);
534     GLenum last_blend_dst_rgb; glGetIntegerv(GL_BLEND_DST_RGB, (GLint*)&last_blend_dst_rgb);
535     GLenum last_blend_src_alpha; glGetIntegerv(GL_BLEND_SRC_ALPHA, (GLint*)&last_blend_src_alpha);
536     GLenum last_blend_dst_alpha; glGetIntegerv(GL_BLEND_DST_ALPHA, (GLint*)&last_blend_dst_alpha);
537     GLenum last_blend_equation_rgb; glGetIntegerv(GL_BLEND_EQUATION_RGB, (GLint*)&last_blend_equation_rgb);
538     GLenum last_blend_equation_alpha; glGetIntegerv(GL_BLEND_EQUATION_ALPHA, (GLint*)&last_blend_equation_alpha);
539     GLboolean last_enable_blend = glIsEnabled(GL_BLEND);
540     GLboolean last_enable_cull_face = glIsEnabled(GL_CULL_FACE);
541     GLboolean last_enable_depth_test = glIsEnabled(GL_DEPTH_TEST);
542     GLboolean last_enable_stencil_test = glIsEnabled(GL_STENCIL_TEST);
543     GLboolean last_enable_scissor_test = glIsEnabled(GL_SCISSOR_TEST);
544 #ifdef IMGUI_IMPL_OPENGL_MAY_HAVE_PRIMITIVE_RESTART
545     GLboolean last_enable_primitive_restart = (bd\->GlVersion >= 310) ? glIsEnabled(GL_PRIMITIVE_RESTART) : GL_FALSE;
546 #endif
547 
548     // Setup desired GL state
549     // Recreate the VAO every time (this is to easily allow multiple GL contexts to be rendered to\&. VAO are not shared among GL contexts)
550     // The renderer would actually work without any VAO bound, but then our VertexAttrib calls would overwrite the default one currently bound\&.
551     GLuint vertex_array_object = 0;
552 #ifdef IMGUI_IMPL_OPENGL_USE_VERTEX_ARRAY
553     GL_CALL(glGenVertexArrays(1, &vertex_array_object));
554 #endif
555     ImGui_ImplOpenGL3_SetupRenderState(draw_data, fb_width, fb_height, vertex_array_object);
556 
557     // Will project scissor/clipping rectangles into framebuffer space
558     ImVec2 clip_off = draw_data\->DisplayPos;         // (0,0) unless using multi\-viewports
559     ImVec2 clip_scale = draw_data\->FramebufferScale; // (1,1) unless using retina display which are often (2,2)
560 
561     // Render command lists
562     for (int n = 0; n < draw_data\->CmdListsCount; n++)
563     {
564         const ImDrawList* cmd_list = draw_data\->CmdLists[n];
565 
566         // Upload vertex/index buffers
567         // \- OpenGL drivers are in a very sorry state nowadays\&.\&.\&.\&.
568         //   During 2021 we attempted to switch from glBufferData() to orphaning+glBufferSubData() following reports
569         //   of leaks on Intel GPU when using multi\-viewports on Windows\&.
570         // \- After this we kept hearing of various display corruptions issues\&. We started disabling on non\-Intel GPU, but issues still got reported on Intel\&.
571         // \- We are now back to using exclusively glBufferData()\&. So bd\->UseBufferSubData IS ALWAYS FALSE in this code\&.
572         //   We are keeping the old code path for a while in case people finding new issues may want to test the bd\->UseBufferSubData path\&.
573         // \- See https://github\&.com/ocornut/imgui/issues/4468 and please report any corruption issues\&.
574         const GLsizeiptr vtx_buffer_size = (GLsizeiptr)cmd_list\->VtxBuffer\&.Size * (int)sizeof(ImDrawVert);
575         const GLsizeiptr idx_buffer_size = (GLsizeiptr)cmd_list\->IdxBuffer\&.Size * (int)sizeof(ImDrawIdx);
576         if (bd\->UseBufferSubData)
577         {
578             if (bd\->VertexBufferSize < vtx_buffer_size)
579             {
580                 bd\->VertexBufferSize = vtx_buffer_size;
581                 GL_CALL(glBufferData(GL_ARRAY_BUFFER, bd\->VertexBufferSize, nullptr, GL_STREAM_DRAW));
582             }
583             if (bd\->IndexBufferSize < idx_buffer_size)
584             {
585                 bd\->IndexBufferSize = idx_buffer_size;
586                 GL_CALL(glBufferData(GL_ELEMENT_ARRAY_BUFFER, bd\->IndexBufferSize, nullptr, GL_STREAM_DRAW));
587             }
588             GL_CALL(glBufferSubData(GL_ARRAY_BUFFER, 0, vtx_buffer_size, (const GLvoid*)cmd_list\->VtxBuffer\&.Data));
589             GL_CALL(glBufferSubData(GL_ELEMENT_ARRAY_BUFFER, 0, idx_buffer_size, (const GLvoid*)cmd_list\->IdxBuffer\&.Data));
590         }
591         else
592         {
593             GL_CALL(glBufferData(GL_ARRAY_BUFFER, vtx_buffer_size, (const GLvoid*)cmd_list\->VtxBuffer\&.Data, GL_STREAM_DRAW));
594             GL_CALL(glBufferData(GL_ELEMENT_ARRAY_BUFFER, idx_buffer_size, (const GLvoid*)cmd_list\->IdxBuffer\&.Data, GL_STREAM_DRAW));
595         }
596 
597         for (int cmd_i = 0; cmd_i < cmd_list\->CmdBuffer\&.Size; cmd_i++)
598         {
599             const ImDrawCmd* pcmd = &cmd_list\->CmdBuffer[cmd_i];
600             if (pcmd\->UserCallback != nullptr)
601             {
602                 // User callback, registered via ImDrawList::AddCallback()
603                 // (ImDrawCallback_ResetRenderState is a special callback value used by the user to request the renderer to reset render state\&.)
604                 if (pcmd\->UserCallback == ImDrawCallback_ResetRenderState)
605                     ImGui_ImplOpenGL3_SetupRenderState(draw_data, fb_width, fb_height, vertex_array_object);
606                 else
607                     pcmd\->UserCallback(cmd_list, pcmd);
608             }
609             else
610             {
611                 // Project scissor/clipping rectangles into framebuffer space
612                 ImVec2 clip_min((pcmd\->ClipRect\&.x \- clip_off\&.x) * clip_scale\&.x, (pcmd\->ClipRect\&.y \- clip_off\&.y) * clip_scale\&.y);
613                 ImVec2 clip_max((pcmd\->ClipRect\&.z \- clip_off\&.x) * clip_scale\&.x, (pcmd\->ClipRect\&.w \- clip_off\&.y) * clip_scale\&.y);
614                 if (clip_max\&.x <= clip_min\&.x || clip_max\&.y <= clip_min\&.y)
615                     continue;
616 
617                 // Apply scissor/clipping rectangle (Y is inverted in OpenGL)
618                 GL_CALL(glScissor((int)clip_min\&.x, (int)((float)fb_height \- clip_max\&.y), (int)(clip_max\&.x \- clip_min\&.x), (int)(clip_max\&.y \- clip_min\&.y)));
619 
620                 // Bind texture, Draw
621                 GL_CALL(glBindTexture(GL_TEXTURE_2D, (GLuint)(intptr_t)pcmd\->GetTexID()));
622 #ifdef IMGUI_IMPL_OPENGL_MAY_HAVE_VTX_OFFSET
623                 if (bd\->GlVersion >= 320)
624                     GL_CALL(glDrawElementsBaseVertex(GL_TRIANGLES, (GLsizei)pcmd\->ElemCount, sizeof(ImDrawIdx) == 2 ? GL_UNSIGNED_SHORT : GL_UNSIGNED_INT, (void*)(intptr_t)(pcmd\->IdxOffset * sizeof(ImDrawIdx)), (GLint)pcmd\->VtxOffset));
625                 else
626 #endif
627                 GL_CALL(glDrawElements(GL_TRIANGLES, (GLsizei)pcmd\->ElemCount, sizeof(ImDrawIdx) == 2 ? GL_UNSIGNED_SHORT : GL_UNSIGNED_INT, (void*)(intptr_t)(pcmd\->IdxOffset * sizeof(ImDrawIdx))));
628             }
629         }
630     }
631 
632     // Destroy the temporary VAO
633 #ifdef IMGUI_IMPL_OPENGL_USE_VERTEX_ARRAY
634     GL_CALL(glDeleteVertexArrays(1, &vertex_array_object));
635 #endif
636 
637     // Restore modified GL state
638     // This "glIsProgram()" check is required because if the program is "pending deletion" at the time of binding backup, it will have been deleted by now and will cause an OpenGL error\&. See #6220\&.
639     if (last_program == 0 || glIsProgram(last_program)) glUseProgram(last_program);
640     glBindTexture(GL_TEXTURE_2D, last_texture);
641 #ifdef IMGUI_IMPL_OPENGL_MAY_HAVE_BIND_SAMPLER
642     if (bd\->GlVersion >= 330 || bd\->GlProfileIsES3)
643         glBindSampler(0, last_sampler);
644 #endif
645     glActiveTexture(last_active_texture);
646 #ifdef IMGUI_IMPL_OPENGL_USE_VERTEX_ARRAY
647     glBindVertexArray(last_vertex_array_object);
648 #endif
649     glBindBuffer(GL_ARRAY_BUFFER, last_array_buffer);
650 #ifndef IMGUI_IMPL_OPENGL_USE_VERTEX_ARRAY
651     glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, last_element_array_buffer);
652     last_vtx_attrib_state_pos\&.SetState(bd\->AttribLocationVtxPos);
653     last_vtx_attrib_state_uv\&.SetState(bd\->AttribLocationVtxUV);
654     last_vtx_attrib_state_color\&.SetState(bd\->AttribLocationVtxColor);
655 #endif
656     glBlendEquationSeparate(last_blend_equation_rgb, last_blend_equation_alpha);
657     glBlendFuncSeparate(last_blend_src_rgb, last_blend_dst_rgb, last_blend_src_alpha, last_blend_dst_alpha);
658     if (last_enable_blend) glEnable(GL_BLEND); else glDisable(GL_BLEND);
659     if (last_enable_cull_face) glEnable(GL_CULL_FACE); else glDisable(GL_CULL_FACE);
660     if (last_enable_depth_test) glEnable(GL_DEPTH_TEST); else glDisable(GL_DEPTH_TEST);
661     if (last_enable_stencil_test) glEnable(GL_STENCIL_TEST); else glDisable(GL_STENCIL_TEST);
662     if (last_enable_scissor_test) glEnable(GL_SCISSOR_TEST); else glDisable(GL_SCISSOR_TEST);
663 #ifdef IMGUI_IMPL_OPENGL_MAY_HAVE_PRIMITIVE_RESTART
664     if (bd\->GlVersion >= 310) { if (last_enable_primitive_restart) glEnable(GL_PRIMITIVE_RESTART); else glDisable(GL_PRIMITIVE_RESTART); }
665 #endif
666 
667 #ifdef IMGUI_IMPL_OPENGL_MAY_HAVE_POLYGON_MODE
668     // Desktop OpenGL 3\&.0 and OpenGL 3\&.1 had separate polygon draw modes for front\-facing and back\-facing faces of polygons
669     if (bd\->HasPolygonMode) { if (bd\->GlVersion <= 310 || bd\->GlProfileIsCompat) { glPolygonMode(GL_FRONT, (GLenum)last_polygon_mode[0]); glPolygonMode(GL_BACK, (GLenum)last_polygon_mode[1]); } else { glPolygonMode(GL_FRONT_AND_BACK, (GLenum)last_polygon_mode[0]); } }
670 #endif // IMGUI_IMPL_OPENGL_MAY_HAVE_POLYGON_MODE
671 
672     glViewport(last_viewport[0], last_viewport[1], (GLsizei)last_viewport[2], (GLsizei)last_viewport[3]);
673     glScissor(last_scissor_box[0], last_scissor_box[1], (GLsizei)last_scissor_box[2], (GLsizei)last_scissor_box[3]);
674     (void)bd; // Not all compilation paths use this
675 }
.PP
.fi

.PP
References \fBImGui_ImplOpenGL3_Data::AttribLocationVtxColor\fP, \fBImGui_ImplOpenGL3_Data::AttribLocationVtxPos\fP, \fBImGui_ImplOpenGL3_Data::AttribLocationVtxUV\fP, \fBGL_CALL\fP, \fBImGui_ImplOpenGL3_Data::GlProfileIsCompat\fP, \fBImGui_ImplOpenGL3_Data::GlProfileIsES3\fP, \fBImGui_ImplOpenGL3_Data::GlVersion\fP, \fBImGui_ImplOpenGL3_Data::HasPolygonMode\fP, \fBImGui_ImplOpenGL3_Data::IndexBufferSize\fP, \fBImGui_ImplOpenGL3_Data::UseBufferSubData\fP, and \fBImGui_ImplOpenGL3_Data::VertexBufferSize\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "void ImGui_ImplOpenGL3_Shutdown ()"

.PP
Definition at line \fB397\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.nf
398 {
399     ImGui_ImplOpenGL3_Data* bd = ImGui_ImplOpenGL3_GetBackendData();
400     IM_ASSERT(bd != nullptr && "No renderer backend to shutdown, or already shutdown?");
401     ImGuiIO& io = ImGui::GetIO();
402 
403     ImGui_ImplOpenGL3_ShutdownPlatformInterface();
404     ImGui_ImplOpenGL3_DestroyDeviceObjects();
405     io\&.BackendRendererName = nullptr;
406     io\&.BackendRendererUserData = nullptr;
407     io\&.BackendFlags &= ~(ImGuiBackendFlags_RendererHasVtxOffset | ImGuiBackendFlags_RendererHasViewports);
408     IM_DELETE(bd);
409 }
.PP
.fi

.PP
References \fBImGui_ImplOpenGL3_DestroyDeviceObjects()\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
