.TH "ImGui_ImplGlfw_ViewportData" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGui_ImplGlfw_ViewportData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGui_ImplGlfw_ViewportData\fP ()"
.br
.ti -1c
.RI "\fB~ImGui_ImplGlfw_ViewportData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLFWwindow * \fBWindow\fP"
.br
.ti -1c
.RI "bool \fBWindowOwned\fP"
.br
.ti -1c
.RI "int \fBIgnoreWindowPosEventFrame\fP"
.br
.ti -1c
.RI "int \fBIgnoreWindowSizeEventFrame\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1018\fP of file \fBimgui_impl_glfw\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGui_ImplGlfw_ViewportData::ImGui_ImplGlfw_ViewportData ()\fR [inline]\fP"

.PP
Definition at line \fB1028\fP of file \fBimgui_impl_glfw\&.cpp\fP\&.
.nf
1028 { memset(this, 0, sizeof(*this)); IgnoreWindowSizeEventFrame = IgnoreWindowPosEventFrame = \-1; }
.PP
.fi

.PP
References \fBIgnoreWindowPosEventFrame\fP, and \fBIgnoreWindowSizeEventFrame\fP\&.
.SS "ImGui_ImplGlfw_ViewportData::~ImGui_ImplGlfw_ViewportData ()\fR [inline]\fP"

.PP
Definition at line \fB1029\fP of file \fBimgui_impl_glfw\&.cpp\fP\&.
.nf
1029 { IM_ASSERT(Window == nullptr); }
.PP
.fi

.PP
References \fBWindow\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ImGui_ImplGlfw_ViewportData::IgnoreWindowPosEventFrame"

.PP
Definition at line \fB1022\fP of file \fBimgui_impl_glfw\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplGlfw_ViewportData()\fP\&.
.SS "int ImGui_ImplGlfw_ViewportData::IgnoreWindowSizeEventFrame"

.PP
Definition at line \fB1023\fP of file \fBimgui_impl_glfw\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplGlfw_ViewportData()\fP\&.
.SS "GLFWwindow* ImGui_ImplGlfw_ViewportData::Window"

.PP
Definition at line \fB1020\fP of file \fBimgui_impl_glfw\&.cpp\fP\&.
.PP
Referenced by \fB~ImGui_ImplGlfw_ViewportData()\fP\&.
.SS "bool ImGui_ImplGlfw_ViewportData::WindowOwned"

.PP
Definition at line \fB1021\fP of file \fBimgui_impl_glfw\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
