.TH "adhed/imgui_stdlib.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/imgui_stdlib.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBImGui\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIMGUI_API\fP bool \fBImGui::InputText\fP (const char *label, std::string *str, \fBImGuiInputTextFlags\fP \fBflags\fP=0, \fBImGuiInputTextCallback\fP callback=nullptr, \fBvoid\fP *user_data=nullptr)"
.br
.ti -1c
.RI "\fBIMGUI_API\fP bool \fBImGui::InputTextMultiline\fP (const char *label, std::string *str, const \fBImVec2\fP &\fBsize\fP=\fBImVec2\fP(0, 0), \fBImGuiInputTextFlags\fP \fBflags\fP=0, \fBImGuiInputTextCallback\fP callback=nullptr, \fBvoid\fP *user_data=nullptr)"
.br
.ti -1c
.RI "\fBIMGUI_API\fP bool \fBImGui::InputTextWithHint\fP (const char *label, const char *hint, std::string *str, \fBImGuiInputTextFlags\fP \fBflags\fP=0, \fBImGuiInputTextCallback\fP callback=nullptr, \fBvoid\fP *user_data=nullptr)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
