.TH "ImGuiViewport" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiViewport
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.PP
Inherited by \fBImGuiViewportP\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiViewport\fP ()"
.br
.ti -1c
.RI "\fB~ImGuiViewport\fP ()"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGetCenter\fP () const"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGetWorkCenter\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBID\fP"
.br
.ti -1c
.RI "\fBImGuiViewportFlags\fP \fBFlags\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWorkPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWorkSize\fP"
.br
.ti -1c
.RI "float \fBDpiScale\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBParentViewportId\fP"
.br
.ti -1c
.RI "\fBImDrawData\fP * \fBDrawData\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBRendererUserData\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBPlatformUserData\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBPlatformHandle\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBPlatformHandleRaw\fP"
.br
.ti -1c
.RI "bool \fBPlatformWindowCreated\fP"
.br
.ti -1c
.RI "bool \fBPlatformRequestMove\fP"
.br
.ti -1c
.RI "bool \fBPlatformRequestResize\fP"
.br
.ti -1c
.RI "bool \fBPlatformRequestClose\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiViewport::ImGuiViewport ()\fR [inline]\fP"

.SS "ImGuiViewport::~ImGuiViewport ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBImVec2\fP ImGuiViewport::GetCenter () const\fR [inline]\fP"

.SS "\fBImVec2\fP ImGuiViewport::GetWorkCenter () const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float ImGuiViewport::DpiScale"

.SS "\fBImDrawData\fP* ImGuiViewport::DrawData"

.SS "\fBImGuiViewportFlags\fP ImGuiViewport::Flags"

.SS "\fBImGuiID\fP ImGuiViewport::ID"

.SS "\fBImGuiID\fP ImGuiViewport::ParentViewportId"

.SS "\fBvoid\fP* ImGuiViewport::PlatformHandle"

.SS "\fBvoid\fP* ImGuiViewport::PlatformHandleRaw"

.SS "bool ImGuiViewport::PlatformRequestClose"

.SS "bool ImGuiViewport::PlatformRequestMove"

.SS "bool ImGuiViewport::PlatformRequestResize"

.SS "\fBvoid\fP* ImGuiViewport::PlatformUserData"

.SS "bool ImGuiViewport::PlatformWindowCreated"

.SS "\fBImVec2\fP ImGuiViewport::Pos"

.SS "\fBvoid\fP* ImGuiViewport::RendererUserData"

.SS "\fBImVec2\fP ImGuiViewport::Size"

.SS "\fBImVec2\fP ImGuiViewport::WorkPos"

.SS "\fBImVec2\fP ImGuiViewport::WorkSize"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
