.TH "ImGuiResizeBorderDef" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiResizeBorderDef
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImVec2 \fBInnerDir\fP"
.br
.ti -1c
.RI "ImVec2 \fBSegmentN1\fP"
.br
.ti -1c
.RI "ImVec2 \fBSegmentN2\fP"
.br
.ti -1c
.RI "float \fBOuterAngle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6305\fP of file \fBimgui\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "ImVec2 ImGuiResizeBorderDef::InnerDir"

.PP
Definition at line \fB6307\fP of file \fBimgui\&.cpp\fP\&.
.SS "float ImGuiResizeBorderDef::OuterAngle"

.PP
Definition at line \fB6309\fP of file \fBimgui\&.cpp\fP\&.
.SS "ImVec2 ImGuiResizeBorderDef::SegmentN1"

.PP
Definition at line \fB6308\fP of file \fBimgui\&.cpp\fP\&.
.SS "ImVec2 ImGuiResizeBorderDef::SegmentN2"

.PP
Definition at line \fB6308\fP of file \fBimgui\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
