.TH "ImGuiNextWindowData" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiNextWindowData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiNextWindowData\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBClearFlags\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiNextWindowDataFlags\fP \fBFlags\fP"
.br
.ti -1c
.RI "\fBImGuiCond\fP \fBPosCond\fP"
.br
.ti -1c
.RI "\fBImGuiCond\fP \fBSizeCond\fP"
.br
.ti -1c
.RI "\fBImGuiCond\fP \fBCollapsedCond\fP"
.br
.ti -1c
.RI "\fBImGuiCond\fP \fBDockCond\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPosVal\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPosPivotVal\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSizeVal\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBContentSizeVal\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBScrollVal\fP"
.br
.ti -1c
.RI "\fBImGuiChildFlags\fP \fBChildFlags\fP"
.br
.ti -1c
.RI "bool \fBPosUndock\fP"
.br
.ti -1c
.RI "bool \fBCollapsedVal\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBSizeConstraintRect\fP"
.br
.ti -1c
.RI "\fBImGuiSizeCallback\fP \fBSizeCallback\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBSizeCallbackUserData\fP"
.br
.ti -1c
.RI "float \fBBgAlphaVal\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBViewportId\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBDockId\fP"
.br
.ti -1c
.RI "\fBImGuiWindowClass\fP \fBWindowClass\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBMenuBarOffsetMinVal\fP"
.br
.ti -1c
.RI "\fBImGuiWindowRefreshFlags\fP \fBRefreshFlagsVal\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiNextWindowData::ImGuiNextWindowData ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP ImGuiNextWindowData::ClearFlags ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float ImGuiNextWindowData::BgAlphaVal"

.SS "\fBImGuiChildFlags\fP ImGuiNextWindowData::ChildFlags"

.SS "\fBImGuiCond\fP ImGuiNextWindowData::CollapsedCond"

.SS "bool ImGuiNextWindowData::CollapsedVal"

.SS "\fBImVec2\fP ImGuiNextWindowData::ContentSizeVal"

.SS "\fBImGuiCond\fP ImGuiNextWindowData::DockCond"

.SS "\fBImGuiID\fP ImGuiNextWindowData::DockId"

.SS "\fBImGuiNextWindowDataFlags\fP ImGuiNextWindowData::Flags"

.SS "\fBImVec2\fP ImGuiNextWindowData::MenuBarOffsetMinVal"

.SS "\fBImGuiCond\fP ImGuiNextWindowData::PosCond"

.SS "\fBImVec2\fP ImGuiNextWindowData::PosPivotVal"

.SS "bool ImGuiNextWindowData::PosUndock"

.SS "\fBImVec2\fP ImGuiNextWindowData::PosVal"

.SS "\fBImGuiWindowRefreshFlags\fP ImGuiNextWindowData::RefreshFlagsVal"

.SS "\fBImVec2\fP ImGuiNextWindowData::ScrollVal"

.SS "\fBImGuiSizeCallback\fP ImGuiNextWindowData::SizeCallback"

.SS "\fBvoid\fP* ImGuiNextWindowData::SizeCallbackUserData"

.SS "\fBImGuiCond\fP ImGuiNextWindowData::SizeCond"

.SS "\fBImRect\fP ImGuiNextWindowData::SizeConstraintRect"

.SS "\fBImVec2\fP ImGuiNextWindowData::SizeVal"

.SS "\fBImGuiID\fP ImGuiNextWindowData::ViewportId"

.SS "\fBImGuiWindowClass\fP ImGuiNextWindowData::WindowClass"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
