.TH "ImGuiDemoWindowData" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiDemoWindowData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBShowMainMenuBar\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppAssetsBrowser\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppConsole\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppCustomRendering\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppDocuments\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppDockSpace\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppLog\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppLayout\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppPropertyEditor\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppSimpleOverlay\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppAutoResize\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppConstrainedResize\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppFullscreen\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppLongText\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppWindowTitles\fP = false"
.br
.ti -1c
.RI "bool \fBShowMetrics\fP = false"
.br
.ti -1c
.RI "bool \fBShowDebugLog\fP = false"
.br
.ti -1c
.RI "bool \fBShowIDStackTool\fP = false"
.br
.ti -1c
.RI "bool \fBShowStyleEditor\fP = false"
.br
.ti -1c
.RI "bool \fBShowAbout\fP = false"
.br
.ti -1c
.RI "\fBExampleTreeNode\fP * \fBDemoTree\fP = NULL"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB355\fP of file \fBimgui_demo\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBExampleTreeNode\fP* ImGuiDemoWindowData::DemoTree = NULL"

.PP
Definition at line \fB382\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowAbout = false"

.PP
Definition at line \fB379\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowAppAssetsBrowser = false"

.PP
Definition at line \fB359\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowAppAutoResize = false"

.PP
Definition at line \fB368\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowAppConsole = false"

.PP
Definition at line \fB360\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowAppConstrainedResize = false"

.PP
Definition at line \fB369\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowAppCustomRendering = false"

.PP
Definition at line \fB361\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowAppDockSpace = false"

.PP
Definition at line \fB363\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowAppDocuments = false"

.PP
Definition at line \fB362\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowAppFullscreen = false"

.PP
Definition at line \fB370\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowAppLayout = false"

.PP
Definition at line \fB365\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowAppLog = false"

.PP
Definition at line \fB364\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowAppLongText = false"

.PP
Definition at line \fB371\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowAppPropertyEditor = false"

.PP
Definition at line \fB366\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowAppSimpleOverlay = false"

.PP
Definition at line \fB367\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowAppWindowTitles = false"

.PP
Definition at line \fB372\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowDebugLog = false"

.PP
Definition at line \fB376\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowIDStackTool = false"

.PP
Definition at line \fB377\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowMainMenuBar = false"

.PP
Definition at line \fB358\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowMetrics = false"

.PP
Definition at line \fB375\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "bool ImGuiDemoWindowData::ShowStyleEditor = false"

.PP
Definition at line \fB378\fP of file \fBimgui_demo\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
