.TH "ImGuiWindowSettings" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiWindowSettings
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiWindowSettings\fP ()"
.br
.ti -1c
.RI "char * \fBGetName\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBID\fP"
.br
.ti -1c
.RI "\fBImVec2ih\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImVec2ih\fP \fBSize\fP"
.br
.ti -1c
.RI "\fBImVec2ih\fP \fBViewportPos\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBViewportId\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBDockId\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBClassId\fP"
.br
.ti -1c
.RI "short \fBDockOrder\fP"
.br
.ti -1c
.RI "bool \fBCollapsed\fP"
.br
.ti -1c
.RI "bool \fBIsChild\fP"
.br
.ti -1c
.RI "bool \fBWantApply\fP"
.br
.ti -1c
.RI "bool \fBWantDelete\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiWindowSettings::ImGuiWindowSettings ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "char * ImGuiWindowSettings::GetName ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiID\fP ImGuiWindowSettings::ClassId"

.SS "bool ImGuiWindowSettings::Collapsed"

.SS "\fBImGuiID\fP ImGuiWindowSettings::DockId"

.SS "short ImGuiWindowSettings::DockOrder"

.SS "\fBImGuiID\fP ImGuiWindowSettings::ID"

.SS "bool ImGuiWindowSettings::IsChild"

.SS "\fBImVec2ih\fP ImGuiWindowSettings::Pos"

.SS "\fBImVec2ih\fP ImGuiWindowSettings::Size"

.SS "\fBImGuiID\fP ImGuiWindowSettings::ViewportId"

.SS "\fBImVec2ih\fP ImGuiWindowSettings::ViewportPos"

.SS "bool ImGuiWindowSettings::WantApply"

.SS "bool ImGuiWindowSettings::WantDelete"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
