.TH "ImGui_ImplOpenGL3_Data" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGui_ImplOpenGL3_Data
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGui_ImplOpenGL3_Data\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLuint \fBGlVersion\fP"
.br
.ti -1c
.RI "char \fBGlslVersionString\fP [32]"
.br
.ti -1c
.RI "bool \fBGlProfileIsES2\fP"
.br
.ti -1c
.RI "bool \fBGlProfileIsES3\fP"
.br
.ti -1c
.RI "bool \fBGlProfileIsCompat\fP"
.br
.ti -1c
.RI "GLint \fBGlProfileMask\fP"
.br
.ti -1c
.RI "GLuint \fBFontTexture\fP"
.br
.ti -1c
.RI "GLuint \fBShaderHandle\fP"
.br
.ti -1c
.RI "GLint \fBAttribLocationTex\fP"
.br
.ti -1c
.RI "GLint \fBAttribLocationProjMtx\fP"
.br
.ti -1c
.RI "GLuint \fBAttribLocationVtxPos\fP"
.br
.ti -1c
.RI "GLuint \fBAttribLocationVtxUV\fP"
.br
.ti -1c
.RI "GLuint \fBAttribLocationVtxColor\fP"
.br
.ti -1c
.RI "unsigned int \fBVboHandle\fP"
.br
.ti -1c
.RI "unsigned int \fBElementsHandle\fP"
.br
.ti -1c
.RI "GLsizeiptr \fBVertexBufferSize\fP"
.br
.ti -1c
.RI "GLsizeiptr \fBIndexBufferSize\fP"
.br
.ti -1c
.RI "bool \fBHasPolygonMode\fP"
.br
.ti -1c
.RI "bool \fBHasClipOrigin\fP"
.br
.ti -1c
.RI "bool \fBUseBufferSubData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB222\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGui_ImplOpenGL3_Data::ImGui_ImplOpenGL3_Data ()\fR [inline]\fP"

.PP
Definition at line \fB244\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.nf
244 { memset((void*)this, 0, sizeof(*this)); }
.PP
.fi

.SH "Member Data Documentation"
.PP 
.SS "GLint ImGui_ImplOpenGL3_Data::AttribLocationProjMtx"

.PP
Definition at line \fB233\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_CreateDeviceObjects()\fP\&.
.SS "GLint ImGui_ImplOpenGL3_Data::AttribLocationTex"

.PP
Definition at line \fB232\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_CreateDeviceObjects()\fP\&.
.SS "GLuint ImGui_ImplOpenGL3_Data::AttribLocationVtxColor"

.PP
Definition at line \fB236\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_CreateDeviceObjects()\fP, and \fBImGui_ImplOpenGL3_RenderDrawData()\fP\&.
.SS "GLuint ImGui_ImplOpenGL3_Data::AttribLocationVtxPos"

.PP
Definition at line \fB234\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_CreateDeviceObjects()\fP, and \fBImGui_ImplOpenGL3_RenderDrawData()\fP\&.
.SS "GLuint ImGui_ImplOpenGL3_Data::AttribLocationVtxUV"

.PP
Definition at line \fB235\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_CreateDeviceObjects()\fP, and \fBImGui_ImplOpenGL3_RenderDrawData()\fP\&.
.SS "unsigned int ImGui_ImplOpenGL3_Data::ElementsHandle"

.PP
Definition at line \fB237\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_CreateDeviceObjects()\fP, and \fBImGui_ImplOpenGL3_DestroyDeviceObjects()\fP\&.
.SS "GLuint ImGui_ImplOpenGL3_Data::FontTexture"

.PP
Definition at line \fB230\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_CreateFontsTexture()\fP, \fBImGui_ImplOpenGL3_DestroyFontsTexture()\fP, and \fBImGui_ImplOpenGL3_NewFrame()\fP\&.
.SS "bool ImGui_ImplOpenGL3_Data::GlProfileIsCompat"

.PP
Definition at line \fB228\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_Init()\fP, and \fBImGui_ImplOpenGL3_RenderDrawData()\fP\&.
.SS "bool ImGui_ImplOpenGL3_Data::GlProfileIsES2"

.PP
Definition at line \fB226\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_Init()\fP\&.
.SS "bool ImGui_ImplOpenGL3_Data::GlProfileIsES3"

.PP
Definition at line \fB227\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_Init()\fP, and \fBImGui_ImplOpenGL3_RenderDrawData()\fP\&.
.SS "GLint ImGui_ImplOpenGL3_Data::GlProfileMask"

.PP
Definition at line \fB229\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_Init()\fP\&.
.SS "char ImGui_ImplOpenGL3_Data::GlslVersionString[32]"

.PP
Definition at line \fB225\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_CreateDeviceObjects()\fP, and \fBImGui_ImplOpenGL3_Init()\fP\&.
.SS "GLuint ImGui_ImplOpenGL3_Data::GlVersion"

.PP
Definition at line \fB224\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_CreateDeviceObjects()\fP, \fBImGui_ImplOpenGL3_Init()\fP, and \fBImGui_ImplOpenGL3_RenderDrawData()\fP\&.
.SS "bool ImGui_ImplOpenGL3_Data::HasClipOrigin"

.PP
Definition at line \fB241\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_Init()\fP\&.
.SS "bool ImGui_ImplOpenGL3_Data::HasPolygonMode"

.PP
Definition at line \fB240\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_Init()\fP, and \fBImGui_ImplOpenGL3_RenderDrawData()\fP\&.
.SS "GLsizeiptr ImGui_ImplOpenGL3_Data::IndexBufferSize"

.PP
Definition at line \fB239\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_RenderDrawData()\fP\&.
.SS "GLuint ImGui_ImplOpenGL3_Data::ShaderHandle"

.PP
Definition at line \fB231\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_CreateDeviceObjects()\fP, \fBImGui_ImplOpenGL3_DestroyDeviceObjects()\fP, and \fBImGui_ImplOpenGL3_NewFrame()\fP\&.
.SS "bool ImGui_ImplOpenGL3_Data::UseBufferSubData"

.PP
Definition at line \fB242\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_Init()\fP, and \fBImGui_ImplOpenGL3_RenderDrawData()\fP\&.
.SS "unsigned int ImGui_ImplOpenGL3_Data::VboHandle"

.PP
Definition at line \fB237\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_CreateDeviceObjects()\fP, and \fBImGui_ImplOpenGL3_DestroyDeviceObjects()\fP\&.
.SS "GLsizeiptr ImGui_ImplOpenGL3_Data::VertexBufferSize"

.PP
Definition at line \fB238\fP of file \fBimgui_impl_opengl3\&.cpp\fP\&.
.PP
Referenced by \fBImGui_ImplOpenGL3_RenderDrawData()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
