.TH "UPRISE_ENGINE/imgui_stdlib.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/imgui_stdlib.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'imgui\&.h'\fP
.br
\fR#include 'imgui_stdlib\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBInputTextCallback_UserData\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
