.TH "UPRISE_ENGINE/imgui.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/imgui.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'imgui\&.h'\fP
.br
\fR#include 'imgui_internal\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include <sys/wait\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBImGuiResizeGripDef\fP"
.br
.ti -1c
.RI "struct \fBImGuiResizeBorderDef\fP"
.br
.ti -1c
.RI "struct \fBImGuiDockRequest\fP"
.br
.ti -1c
.RI "struct \fBImGuiDockPreviewData\fP"
.br
.ti -1c
.RI "struct \fBImGuiDockNodeSettings\fP"
.br
.ti -1c
.RI "struct \fBImGuiDockContextPruneNodeData\fP"
.br
.ti -1c
.RI "struct \fBImGuiDockNodeTreeInfo\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBImGui\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIMGUI_DEFINE_MATH_OPERATORS\fP"
.br
.ti -1c
.RI "#define \fBIMGUI_DEBUG_NAV_SCORING\fP   0"
.br
.ti -1c
.RI "#define \fBIMGUI_DEBUG_NAV_RECTS\fP   0"
.br
.ti -1c
.RI "#define \fBva_copy\fP(dest,  src)   (dest = src)"
.br
.ti -1c
.RI "#define \fBMAP_LEGACY_NAV_INPUT_TO_KEY1\fP(_KEY,  _NAV1)   do { io\&.KeysData[_KEY]\&.Down = (io\&.NavInputs[_NAV1] > 0\&.0f); io\&.KeysData[_KEY]\&.AnalogValue = io\&.NavInputs[_NAV1]; } while (0)"
.br
.ti -1c
.RI "#define \fBMAP_LEGACY_NAV_INPUT_TO_KEY2\fP(_KEY,  _NAV1,  _NAV2)   do { io\&.KeysData[_KEY]\&.Down = (io\&.NavInputs[_NAV1] > 0\&.0f) || (io\&.NavInputs[_NAV2] > 0\&.0f); io\&.KeysData[_KEY]\&.AnalogValue = ImMax(io\&.NavInputs[_NAV1], io\&.NavInputs[_NAV2]); } while (0)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBImGuiDockRequestType\fP { \fBImGuiDockRequestType_None\fP = 0, \fBImGuiDockRequestType_Dock\fP, \fBImGuiDockRequestType_Undock\fP, \fBImGuiDockRequestType_Split\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ImVec2 \fBImBezierCubicClosestPoint\fP (const ImVec2 &p1, const ImVec2 &p2, const ImVec2 &p3, const ImVec2 &p4, const ImVec2 &p, int num_segments)"
.br
.ti -1c
.RI "ImVec2 \fBImBezierCubicClosestPointCasteljau\fP (const ImVec2 &p1, const ImVec2 &p2, const ImVec2 &p3, const ImVec2 &p4, const ImVec2 &p, float tess_tol)"
.br
.ti -1c
.RI "ImVec2 \fBImLineClosestPoint\fP (const ImVec2 &a, const ImVec2 &b, const ImVec2 &p)"
.br
.ti -1c
.RI "bool \fBImTriangleContainsPoint\fP (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &p)"
.br
.ti -1c
.RI "void \fBImTriangleBarycentricCoords\fP (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &p, float &out_u, float &out_v, float &out_w)"
.br
.ti -1c
.RI "ImVec2 \fBImTriangleClosestPoint\fP (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &p)"
.br
.ti -1c
.RI "int \fBImStricmp\fP (const char *str1, const char *str2)"
.br
.ti -1c
.RI "int \fBImStrnicmp\fP (const char *str1, const char *str2, size_t count)"
.br
.ti -1c
.RI "void \fBImStrncpy\fP (char *dst, const char *src, size_t count)"
.br
.ti -1c
.RI "char * \fBImStrdup\fP (const char *str)"
.br
.ti -1c
.RI "char * \fBImStrdupcpy\fP (char *dst, size_t *p_dst_size, const char *src)"
.br
.ti -1c
.RI "const char * \fBImStrchrRange\fP (const char *str, const char *str_end, char c)"
.br
.ti -1c
.RI "int \fBImStrlenW\fP (const ImWchar *str)"
.br
.ti -1c
.RI "const char * \fBImStreolRange\fP (const char *str, const char *str_end)"
.br
.ti -1c
.RI "const ImWchar * \fBImStrbolW\fP (const ImWchar *buf_mid_line, const ImWchar *buf_begin)"
.br
.ti -1c
.RI "const char * \fBImStristr\fP (const char *haystack, const char *haystack_end, const char *needle, const char *needle_end)"
.br
.ti -1c
.RI "void \fBImStrTrimBlanks\fP (char *buf)"
.br
.ti -1c
.RI "const char * \fBImStrSkipBlank\fP (const char *str)"
.br
.ti -1c
.RI "int \fBImFormatString\fP (char *buf, size_t buf_size, const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "int \fBImFormatStringV\fP (char *buf, size_t buf_size, const char *fmt, va_list args)"
.br
.ti -1c
.RI "void \fBImFormatStringToTempBuffer\fP (const char **out_buf, const char **out_buf_end, const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBImFormatStringToTempBufferV\fP (const char **out_buf, const char **out_buf_end, const char *fmt, va_list args)"
.br
.ti -1c
.RI "ImGuiID \fBImHashData\fP (const void *data_p, size_t data_size, ImGuiID seed)"
.br
.ti -1c
.RI "ImGuiID \fBImHashStr\fP (const char *data_p, size_t data_size, ImGuiID seed)"
.br
.ti -1c
.RI "ImFileHandle \fBImFileOpen\fP (const char *filename, const char *\fBmode\fP)"
.br
.ti -1c
.RI "bool \fBImFileClose\fP (ImFileHandle f)"
.br
.ti -1c
.RI "ImU64 \fBImFileGetSize\fP (ImFileHandle f)"
.br
.ti -1c
.RI "ImU64 \fBImFileRead\fP (void *data, ImU64 sz, ImU64 count, ImFileHandle f)"
.br
.ti -1c
.RI "ImU64 \fBImFileWrite\fP (const void *data, ImU64 sz, ImU64 count, ImFileHandle f)"
.br
.ti -1c
.RI "void * \fBImFileLoadToMemory\fP (const char *filename, const char *\fBmode\fP, size_t *out_file_size, int padding_bytes)"
.br
.ti -1c
.RI "IM_MSVC_RUNTIME_CHECKS_OFF int \fBImTextCharFromUtf8\fP (unsigned int *out_char, const char *in_text, const char *in_text_end)"
.br
.ti -1c
.RI "int \fBImTextStrFromUtf8\fP (ImWchar *buf, int buf_size, const char *in_text, const char *in_text_end, const char **in_text_remaining)"
.br
.ti -1c
.RI "int \fBImTextCountCharsFromUtf8\fP (const char *in_text, const char *in_text_end)"
.br
.ti -1c
.RI "const char * \fBImTextCharToUtf8\fP (char out_buf[5], unsigned int c)"
.br
.ti -1c
.RI "int \fBImTextCountUtf8BytesFromChar\fP (const char *in_text, const char *in_text_end)"
.br
.ti -1c
.RI "int \fBImTextStrToUtf8\fP (char *out_buf, int out_buf_size, const ImWchar *in_text, const ImWchar *in_text_end)"
.br
.ti -1c
.RI "int \fBImTextCountUtf8BytesFromStr\fP (const ImWchar *in_text, const ImWchar *in_text_end)"
.br
.ti -1c
.RI "const char * \fBImTextFindPreviousUtf8Codepoint\fP (const char *in_text_start, const char *in_text_curr)"
.br
.ti -1c
.RI "int \fBImTextCountLines\fP (const char *in_text, const char *in_text_end)"
.br
.ti -1c
.RI "IM_MSVC_RUNTIME_CHECKS_RESTORE IMGUI_API ImU32 \fBImAlphaBlendColors\fP (ImU32 col_a, ImU32 col_b)"
.br
.ti -1c
.RI "ImGuiStoragePair * \fBImLowerBound\fP (ImGuiStoragePair *in_begin, ImGuiStoragePair *in_end, ImGuiID key)"
.br
.ti -1c
.RI "\fBIM_STATIC_ASSERT\fP (ImGuiKey_NamedKey_COUNT==IM_ARRAYSIZE(GKeyNames))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const ImGuiID \fBImGui::IMGUI_VIEWPORT_DEFAULT_ID\fP = 0x11111111"
.br
.ti -1c
.RI "ImGuiContext * \fBGImGui\fP = NULL"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define IMGUI_DEBUG_NAV_RECTS   0"

.PP
Definition at line \fB1121\fP of file \fBimgui\&.cpp\fP\&.
.SS "#define IMGUI_DEBUG_NAV_SCORING   0"

.PP
Definition at line \fB1120\fP of file \fBimgui\&.cpp\fP\&.
.SS "#define IMGUI_DEFINE_MATH_OPERATORS"

.PP
Definition at line \fB1031\fP of file \fBimgui\&.cpp\fP\&.
.SS "#define MAP_LEGACY_NAV_INPUT_TO_KEY1( _KEY,  _NAV1)   do { io\&.KeysData[_KEY]\&.Down = (io\&.NavInputs[_NAV1] > 0\&.0f); io\&.KeysData[_KEY]\&.AnalogValue = io\&.NavInputs[_NAV1]; } while (0)"

.SS "#define MAP_LEGACY_NAV_INPUT_TO_KEY2( _KEY,  _NAV1,  _NAV2)   do { io\&.KeysData[_KEY]\&.Down = (io\&.NavInputs[_NAV1] > 0\&.0f) || (io\&.NavInputs[_NAV2] > 0\&.0f); io\&.KeysData[_KEY]\&.AnalogValue = ImMax(io\&.NavInputs[_NAV1], io\&.NavInputs[_NAV2]); } while (0)"

.SS "#define va_copy( dest,  src)   (dest = src)"

.PP
Definition at line \fB2856\fP of file \fBimgui\&.cpp\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBImGuiDockRequestType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIImGuiDockRequestType_None \fP\fP
.TP
\fB\fIImGuiDockRequestType_Dock \fP\fP
.TP
\fB\fIImGuiDockRequestType_Undock \fP\fP
.TP
\fB\fIImGuiDockRequestType_Split \fP\fP
.PP
Definition at line \fB16009\fP of file \fBimgui\&.cpp\fP\&.
.nf
16010 {
16011     ImGuiDockRequestType_None = 0,
16012     ImGuiDockRequestType_Dock,
16013     ImGuiDockRequestType_Undock,
16014     ImGuiDockRequestType_Split                  // Split is the same as Dock but without a DockPayload
16015 };
.PP
.fi

.SH "Function Documentation"
.PP 
.SS "IM_STATIC_ASSERT (ImGuiKey_NamedKey_COUNT  = \fR=IM_ARRAYSIZE(GKeyNames)\fP)"

.SS "IM_MSVC_RUNTIME_CHECKS_RESTORE IMGUI_API ImU32 ImAlphaBlendColors (ImU32 col_a, ImU32 col_b)"

.PP
Definition at line \fB2529\fP of file \fBimgui\&.cpp\fP\&.
.nf
2530 {
2531     float t = ((col_b >> IM_COL32_A_SHIFT) & 0xFF) / 255\&.f;
2532     int r = ImLerp((int)(col_a >> IM_COL32_R_SHIFT) & 0xFF, (int)(col_b >> IM_COL32_R_SHIFT) & 0xFF, t);
2533     int g = ImLerp((int)(col_a >> IM_COL32_G_SHIFT) & 0xFF, (int)(col_b >> IM_COL32_G_SHIFT) & 0xFF, t);
2534     int b = ImLerp((int)(col_a >> IM_COL32_B_SHIFT) & 0xFF, (int)(col_b >> IM_COL32_B_SHIFT) & 0xFF, t);
2535     return IM_COL32(r, g, b, 0xFF);
2536 }
.PP
.fi

.SS "ImVec2 ImBezierCubicClosestPoint (const ImVec2 & p1, const ImVec2 & p2, const ImVec2 & p3, const ImVec2 & p4, const ImVec2 & p, int num_segments)"

.PP
Definition at line \fB1830\fP of file \fBimgui\&.cpp\fP\&.
.nf
1831 {
1832     IM_ASSERT(num_segments > 0); // Use ImBezierCubicClosestPointCasteljau()
1833     ImVec2 p_last = p1;
1834     ImVec2 p_closest;
1835     float p_closest_dist2 = FLT_MAX;
1836     float t_step = 1\&.0f / (float)num_segments;
1837     for (int i_step = 1; i_step <= num_segments; i_step++)
1838     {
1839         ImVec2 p_current = ImBezierCubicCalc(p1, p2, p3, p4, t_step * i_step);
1840         ImVec2 p_line = ImLineClosestPoint(p_last, p_current, p);
1841         float dist2 = ImLengthSqr(p \- p_line);
1842         if (dist2 < p_closest_dist2)
1843         {
1844             p_closest = p_line;
1845             p_closest_dist2 = dist2;
1846         }
1847         p_last = p_current;
1848     }
1849     return p_closest;
1850 }
.PP
.fi

.PP
References \fBImBezierCubicCalc()\fP, and \fBImLineClosestPoint()\fP\&.
.SS "ImVec2 ImBezierCubicClosestPointCasteljau (const ImVec2 & p1, const ImVec2 & p2, const ImVec2 & p3, const ImVec2 & p4, const ImVec2 & p, float tess_tol)"

.PP
Definition at line \fB1888\fP of file \fBimgui\&.cpp\fP\&.
.nf
1889 {
1890     IM_ASSERT(tess_tol > 0\&.0f);
1891     ImVec2 p_last = p1;
1892     ImVec2 p_closest;
1893     float p_closest_dist2 = FLT_MAX;
1894     ImBezierCubicClosestPointCasteljauStep(p, p_closest, p_last, p_closest_dist2, p1\&.x, p1\&.y, p2\&.x, p2\&.y, p3\&.x, p3\&.y, p4\&.x, p4\&.y, tess_tol, 0);
1895     return p_closest;
1896 }
.PP
.fi

.SS "bool ImFileClose (ImFileHandle f)"

.PP
Definition at line \fB2271\fP of file \fBimgui\&.cpp\fP\&.
.nf
2271 { return fclose(f) == 0; }
.PP
.fi

.PP
Referenced by \fBImFileLoadToMemory()\fP\&.
.SS "ImU64 ImFileGetSize (ImFileHandle f)"

.PP
Definition at line \fB2272\fP of file \fBimgui\&.cpp\fP\&.
.nf
2272 { long off = 0, sz = 0; return ((off = ftell(f)) != \-1 && !fseek(f, 0, SEEK_END) && (sz = ftell(f)) != \-1 && !fseek(f, off, SEEK_SET)) ? (ImU64)sz : (ImU64)\-1; }
.PP
.fi

.PP
Referenced by \fBImFileLoadToMemory()\fP\&.
.SS "void * ImFileLoadToMemory (const char * filename, const char * mode, size_t * out_file_size, int padding_bytes)"

.PP
Definition at line \fB2280\fP of file \fBimgui\&.cpp\fP\&.
.nf
2281 {
2282     IM_ASSERT(filename && mode);
2283     if (out_file_size)
2284         *out_file_size = 0;
2285 
2286     ImFileHandle f;
2287     if ((f = ImFileOpen(filename, mode)) == NULL)
2288         return NULL;
2289 
2290     size_t file_size = (size_t)ImFileGetSize(f);
2291     if (file_size == (size_t)\-1)
2292     {
2293         ImFileClose(f);
2294         return NULL;
2295     }
2296 
2297     void* file_data = IM_ALLOC(file_size + padding_bytes);
2298     if (file_data == NULL)
2299     {
2300         ImFileClose(f);
2301         return NULL;
2302     }
2303     if (ImFileRead(file_data, 1, file_size, f) != file_size)
2304     {
2305         ImFileClose(f);
2306         IM_FREE(file_data);
2307         return NULL;
2308     }
2309     if (padding_bytes > 0)
2310         memset((void*)(((char*)file_data) + file_size), 0, (size_t)padding_bytes);
2311 
2312     ImFileClose(f);
2313     if (out_file_size)
2314         *out_file_size = file_size;
2315 
2316     return file_data;
2317 }
.PP
.fi

.PP
References \fBImFileClose()\fP, \fBImFileGetSize()\fP, \fBImFileOpen()\fP, \fBImFileRead()\fP, and \fBmode\fP\&.
.SS "ImFileHandle ImFileOpen (const char * filename, const char * mode)"

.PP
Definition at line \fB2246\fP of file \fBimgui\&.cpp\fP\&.
.nf
2247 {
2248 #if defined(_WIN32) && !defined(IMGUI_DISABLE_WIN32_FUNCTIONS) && !defined(__CYGWIN__) && !defined(__GNUC__)
2249     // We need a fopen() wrapper because MSVC/Windows fopen doesn't handle UTF\-8 filenames\&.
2250     // Previously we used ImTextCountCharsFromUtf8/ImTextStrFromUtf8 here but we now need to support ImWchar16 and ImWchar32!
2251     const int filename_wsize = ::MultiByteToWideChar(CP_UTF8, 0, filename, \-1, NULL, 0);
2252     const int mode_wsize = ::MultiByteToWideChar(CP_UTF8, 0, mode, \-1, NULL, 0);
2253 
2254     // Use stack buffer if possible, otherwise heap buffer\&. Sizes include zero terminator\&.
2255     // We don't rely on current ImGuiContext as this is implied to be a helper function which doesn't depend on it (see #7314)\&.
2256     wchar_t local_temp_stack[FILENAME_MAX];
2257     ImVector<wchar_t> local_temp_heap;
2258     if (filename_wsize + mode_wsize > IM_ARRAYSIZE(local_temp_stack))
2259         local_temp_heap\&.resize(filename_wsize + mode_wsize);
2260     wchar_t* filename_wbuf = local_temp_heap\&.Data ? local_temp_heap\&.Data : local_temp_stack;
2261     wchar_t* mode_wbuf = filename_wbuf + filename_wsize;
2262     ::MultiByteToWideChar(CP_UTF8, 0, filename, \-1, filename_wbuf, filename_wsize);
2263     ::MultiByteToWideChar(CP_UTF8, 0, mode, \-1, mode_wbuf, mode_wsize);
2264     return ::_wfopen(filename_wbuf, mode_wbuf);
2265 #else
2266     return fopen(filename, mode);
2267 #endif
2268 }
.PP
.fi

.PP
References \fBmode\fP\&.
.PP
Referenced by \fBImFileLoadToMemory()\fP\&.
.SS "ImU64 ImFileRead (void * data, ImU64 sz, ImU64 count, ImFileHandle f)"

.PP
Definition at line \fB2273\fP of file \fBimgui\&.cpp\fP\&.
.nf
2273 { return fread(data, (size_t)sz, (size_t)count, f); }
.PP
.fi

.PP
Referenced by \fBImFileLoadToMemory()\fP\&.
.SS "ImU64 ImFileWrite (const void * data, ImU64 sz, ImU64 count, ImFileHandle f)"

.PP
Definition at line \fB2274\fP of file \fBimgui\&.cpp\fP\&.
.nf
2274 { return fwrite(data, (size_t)sz, (size_t)count, f); }
.PP
.fi

.SS "int ImFormatString (char * buf, size_t buf_size, const char * fmt,  \&.\&.\&.)"

.PP
Definition at line \fB2092\fP of file \fBimgui\&.cpp\fP\&.
.nf
2093 {
2094     va_list args;
2095     va_start(args, fmt);
2096 #ifdef IMGUI_USE_STB_SPRINTF
2097     int w = stbsp_vsnprintf(buf, (int)buf_size, fmt, args);
2098 #else
2099     int w = vsnprintf(buf, buf_size, fmt, args);
2100 #endif
2101     va_end(args);
2102     if (buf == NULL)
2103         return w;
2104     if (w == \-1 || w >= (int)buf_size)
2105         w = (int)buf_size \- 1;
2106     buf[w] = 0;
2107     return w;
2108 }
.PP
.fi

.SS "void ImFormatStringToTempBuffer (const char ** out_buf, const char ** out_buf_end, const char * fmt,  \&.\&.\&.)"

.PP
Definition at line \fB2126\fP of file \fBimgui\&.cpp\fP\&.
.nf
2127 {
2128     va_list args;
2129     va_start(args, fmt);
2130     ImFormatStringToTempBufferV(out_buf, out_buf_end, fmt, args);
2131     va_end(args);
2132 }
.PP
.fi

.PP
References \fBImFormatStringToTempBufferV()\fP\&.
.SS "void ImFormatStringToTempBufferV (const char ** out_buf, const char ** out_buf_end, const char * fmt, va_list args)"

.PP
Definition at line \fB2138\fP of file \fBimgui\&.cpp\fP\&.
.nf
2139 {
2140     ImGuiContext& g = *GImGui;
2141     if (fmt[0] == '%' && fmt[1] == 's' && fmt[2] == 0)
2142     {
2143         const char* buf = va_arg(args, const char*); // Skip formatting when using "%s"
2144         if (buf == NULL)
2145             buf = "(null)";
2146         *out_buf = buf;
2147         if (out_buf_end) { *out_buf_end = buf + strlen(buf); }
2148     }
2149     else if (fmt[0] == '%' && fmt[1] == '\&.' && fmt[2] == '*' && fmt[3] == 's' && fmt[4] == 0)
2150     {
2151         int buf_len = va_arg(args, int); // Skip formatting when using "%\&.*s"
2152         const char* buf = va_arg(args, const char*);
2153         if (buf == NULL)
2154         {
2155             buf = "(null)";
2156             buf_len = ImMin(buf_len, 6);
2157         }
2158         *out_buf = buf;
2159         *out_buf_end = buf + buf_len; // Disallow not passing 'out_buf_end' here\&. User is expected to use it\&.
2160     }
2161     else
2162     {
2163         int buf_len = ImFormatStringV(g\&.TempBuffer\&.Data, g\&.TempBuffer\&.Size, fmt, args);
2164         *out_buf = g\&.TempBuffer\&.Data;
2165         if (out_buf_end) { *out_buf_end = g\&.TempBuffer\&.Data + buf_len; }
2166     }
2167 }
.PP
.fi

.PP
References \fBGImGui\fP, and \fBImFormatStringV()\fP\&.
.PP
Referenced by \fBImFormatStringToTempBuffer()\fP\&.
.SS "int ImFormatStringV (char * buf, size_t buf_size, const char * fmt, va_list args)"

.PP
Definition at line \fB2110\fP of file \fBimgui\&.cpp\fP\&.
.nf
2111 {
2112 #ifdef IMGUI_USE_STB_SPRINTF
2113     int w = stbsp_vsnprintf(buf, (int)buf_size, fmt, args);
2114 #else
2115     int w = vsnprintf(buf, buf_size, fmt, args);
2116 #endif
2117     if (buf == NULL)
2118         return w;
2119     if (w == \-1 || w >= (int)buf_size)
2120         w = (int)buf_size \- 1;
2121     buf[w] = 0;
2122     return w;
2123 }
.PP
.fi

.PP
Referenced by \fBImFormatStringToTempBufferV()\fP\&.
.SS "ImGuiID ImHashData (const void * data_p, size_t data_size, ImGuiID seed)"

.PP
Definition at line \fB2195\fP of file \fBimgui\&.cpp\fP\&.
.nf
2196 {
2197     ImU32 crc = ~seed;
2198     const unsigned char* data = (const unsigned char*)data_p;
2199     const ImU32* crc32_lut = GCrc32LookupTable;
2200     while (data_size\-\- != 0)
2201         crc = (crc >> 8) ^ crc32_lut[(crc & 0xFF) ^ *data++];
2202     return ~crc;
2203 }
.PP
.fi

.SS "ImGuiID ImHashStr (const char * data_p, size_t data_size, ImGuiID seed)"

.PP
Definition at line \fB2211\fP of file \fBimgui\&.cpp\fP\&.
.nf
2212 {
2213     seed = ~seed;
2214     ImU32 crc = seed;
2215     const unsigned char* data = (const unsigned char*)data_p;
2216     const ImU32* crc32_lut = GCrc32LookupTable;
2217     if (data_size != 0)
2218     {
2219         while (data_size\-\- != 0)
2220         {
2221             unsigned char c = *data++;
2222             if (c == '#' && data_size >= 2 && data[0] == '#' && data[1] == '#')
2223                 crc = seed;
2224             crc = (crc >> 8) ^ crc32_lut[(crc & 0xFF) ^ c];
2225         }
2226     }
2227     else
2228     {
2229         while (unsigned char c = *data++)
2230         {
2231             if (c == '#' && data[0] == '#' && data[1] == '#')
2232                 crc = seed;
2233             crc = (crc >> 8) ^ crc32_lut[(crc & 0xFF) ^ c];
2234         }
2235     }
2236     return ~crc;
2237 }
.PP
.fi

.SS "ImVec2 ImLineClosestPoint (const ImVec2 & a, const ImVec2 & b, const ImVec2 & p)"

.PP
Definition at line \fB1898\fP of file \fBimgui\&.cpp\fP\&.
.nf
1899 {
1900     ImVec2 ap = p \- a;
1901     ImVec2 ab_dir = b \- a;
1902     float dot = ap\&.x * ab_dir\&.x + ap\&.y * ab_dir\&.y;
1903     if (dot < 0\&.0f)
1904         return a;
1905     float ab_len_sqr = ab_dir\&.x * ab_dir\&.x + ab_dir\&.y * ab_dir\&.y;
1906     if (dot > ab_len_sqr)
1907         return b;
1908     return a + ab_dir * dot / ab_len_sqr;
1909 }
.PP
.fi

.PP
Referenced by \fBImBezierCubicClosestPoint()\fP, and \fBImTriangleClosestPoint()\fP\&.
.SS "ImGuiStoragePair * ImLowerBound (ImGuiStoragePair * in_begin, ImGuiStoragePair * in_end, ImGuiID key)"

.PP
Definition at line \fB2615\fP of file \fBimgui\&.cpp\fP\&.
.nf
2616 {
2617     ImGuiStoragePair* in_p = in_begin;
2618     for (size_t count = (size_t)(in_end \- in_p); count > 0; )
2619     {
2620         size_t count2 = count >> 1;
2621         ImGuiStoragePair* mid = in_p + count2;
2622         if (mid\->key < key)
2623         {
2624             in_p = ++mid;
2625             count \-= count2 + 1;
2626         }
2627         else
2628         {
2629             count = count2;
2630         }
2631     }
2632     return in_p;
2633 }
.PP
.fi

.SS "const ImWchar * ImStrbolW (const ImWchar * buf_mid_line, const ImWchar * buf_begin)"

.PP
Definition at line \fB2016\fP of file \fBimgui\&.cpp\fP\&.
.nf
2017 {
2018     while (buf_mid_line > buf_begin && buf_mid_line[\-1] != '\\n')
2019         buf_mid_line\-\-;
2020     return buf_mid_line;
2021 }
.PP
.fi

.SS "const char * ImStrchrRange (const char * str, const char * str_end, char c)"

.PP
Definition at line \fB1995\fP of file \fBimgui\&.cpp\fP\&.
.nf
1996 {
1997     const char* p = (const char*)memchr(str, (int)c, str_end \- str);
1998     return p;
1999 }
.PP
.fi

.SS "char * ImStrdup (const char * str)"

.PP
Definition at line \fB1974\fP of file \fBimgui\&.cpp\fP\&.
.nf
1975 {
1976     size_t len = strlen(str);
1977     void* buf = IM_ALLOC(len + 1);
1978     return (char*)memcpy(buf, (const void*)str, len + 1);
1979 }
.PP
.fi

.SS "char * ImStrdupcpy (char * dst, size_t * p_dst_size, const char * src)"

.PP
Definition at line \fB1981\fP of file \fBimgui\&.cpp\fP\&.
.nf
1982 {
1983     size_t dst_buf_size = p_dst_size ? *p_dst_size : strlen(dst) + 1;
1984     size_t src_size = strlen(src) + 1;
1985     if (dst_buf_size < src_size)
1986     {
1987         IM_FREE(dst);
1988         dst = (char*)IM_ALLOC(src_size);
1989         if (p_dst_size)
1990             *p_dst_size = src_size;
1991     }
1992     return (char*)memcpy(dst, (const void*)src, src_size);
1993 }
.PP
.fi

.SS "const char * ImStreolRange (const char * str, const char * str_end)"

.PP
Definition at line \fB2010\fP of file \fBimgui\&.cpp\fP\&.
.nf
2011 {
2012     const char* p = (const char*)memchr(str, '\\n', str_end \- str);
2013     return p ? p : str_end;
2014 }
.PP
.fi

.SS "int ImStricmp (const char * str1, const char * str2)"

.PP
Definition at line \fB1951\fP of file \fBimgui\&.cpp\fP\&.
.nf
1952 {
1953     int d;
1954     while ((d = ImToUpper(*str2) \- ImToUpper(*str1)) == 0 && *str1) { str1++; str2++; }
1955     return d;
1956 }
.PP
.fi

.SS "const char * ImStristr (const char * haystack, const char * haystack_end, const char * needle, const char * needle_end)"

.PP
Definition at line \fB2023\fP of file \fBimgui\&.cpp\fP\&.
.nf
2024 {
2025     if (!needle_end)
2026         needle_end = needle + strlen(needle);
2027 
2028     const char un0 = (char)ImToUpper(*needle);
2029     while ((!haystack_end && *haystack) || (haystack_end && haystack < haystack_end))
2030     {
2031         if (ImToUpper(*haystack) == un0)
2032         {
2033             const char* b = needle + 1;
2034             for (const char* a = haystack + 1; b < needle_end; a++, b++)
2035                 if (ImToUpper(*a) != ImToUpper(*b))
2036                     break;
2037             if (b == needle_end)
2038                 return haystack;
2039         }
2040         haystack++;
2041     }
2042     return NULL;
2043 }
.PP
.fi

.SS "int ImStrlenW (const ImWchar * str)"

.PP
Definition at line \fB2001\fP of file \fBimgui\&.cpp\fP\&.
.nf
2002 {
2003     //return (int)wcslen((const wchar_t*)str);  // FIXME\-OPT: Could use this when wchar_t are 16\-bit
2004     int n = 0;
2005     while (*str++) n++;
2006     return n;
2007 }
.PP
.fi

.SS "void ImStrncpy (char * dst, const char * src, size_t count)"

.PP
Definition at line \fB1965\fP of file \fBimgui\&.cpp\fP\&.
.nf
1966 {
1967     if (count < 1)
1968         return;
1969     if (count > 1)
1970         strncpy(dst, src, count \- 1);
1971     dst[count \- 1] = 0;
1972 }
.PP
.fi

.PP
Referenced by \fBImParseFormatTrimDecorations()\fP\&.
.SS "int ImStrnicmp (const char * str1, const char * str2, size_t count)"

.PP
Definition at line \fB1958\fP of file \fBimgui\&.cpp\fP\&.
.nf
1959 {
1960     int d = 0;
1961     while (count > 0 && (d = ImToUpper(*str2) \- ImToUpper(*str1)) == 0 && *str1) { str1++; str2++; count\-\-; }
1962     return d;
1963 }
.PP
.fi

.SS "const char * ImStrSkipBlank (const char * str)"

.PP
Definition at line \fB2061\fP of file \fBimgui\&.cpp\fP\&.
.nf
2062 {
2063     while (str[0] == ' ' || str[0] == '\\t')
2064         str++;
2065     return str;
2066 }
.PP
.fi

.SS "void ImStrTrimBlanks (char * buf)"

.PP
Definition at line \fB2046\fP of file \fBimgui\&.cpp\fP\&.
.nf
2047 {
2048     char* p = buf;
2049     while (p[0] == ' ' || p[0] == '\\t')     // Leading blanks
2050         p++;
2051     char* p_start = p;
2052     while (*p != 0)                         // Find end of string
2053         p++;
2054     while (p > p_start && (p[\-1] == ' ' || p[\-1] == '\\t'))  // Trailing blanks
2055         p\-\-;
2056     if (p_start != buf)                     // Copy memory if we had leading blanks
2057         memmove(buf, p_start, p \- p_start);
2058     buf[p \- p_start] = 0;                   // Zero terminate
2059 }
.PP
.fi

.SS "IM_MSVC_RUNTIME_CHECKS_OFF int ImTextCharFromUtf8 (unsigned int * out_char, const char * in_text, const char * in_text_end)"

.PP
Definition at line \fB2328\fP of file \fBimgui\&.cpp\fP\&.
.nf
2329 {
2330     static const char lengths[32] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 3, 3, 4, 0 };
2331     static const int masks[]  = { 0x00, 0x7f, 0x1f, 0x0f, 0x07 };
2332     static const uint32_t mins[] = { 0x400000, 0, 0x80, 0x800, 0x10000 };
2333     static const int shiftc[] = { 0, 18, 12, 6, 0 };
2334     static const int shifte[] = { 0, 6, 4, 2, 0 };
2335     int len = lengths[*(const unsigned char*)in_text >> 3];
2336     int wanted = len + (len ? 0 : 1);
2337 
2338     if (in_text_end == NULL)
2339         in_text_end = in_text + wanted; // Max length, nulls will be taken into account\&.
2340 
2341     // Copy at most 'len' bytes, stop copying at 0 or past in_text_end\&. Branch predictor does a good job here,
2342     // so it is fast even with excessive branching\&.
2343     unsigned char s[4];
2344     s[0] = in_text + 0 < in_text_end ? in_text[0] : 0;
2345     s[1] = in_text + 1 < in_text_end ? in_text[1] : 0;
2346     s[2] = in_text + 2 < in_text_end ? in_text[2] : 0;
2347     s[3] = in_text + 3 < in_text_end ? in_text[3] : 0;
2348 
2349     // Assume a four\-byte character and load four bytes\&. Unused bits are shifted out\&.
2350     *out_char  = (uint32_t)(s[0] & masks[len]) << 18;
2351     *out_char |= (uint32_t)(s[1] & 0x3f) << 12;
2352     *out_char |= (uint32_t)(s[2] & 0x3f) <<  6;
2353     *out_char |= (uint32_t)(s[3] & 0x3f) <<  0;
2354     *out_char >>= shiftc[len];
2355 
2356     // Accumulate the various error conditions\&.
2357     int e = 0;
2358     e  = (*out_char < mins[len]) << 6; // non\-canonical encoding
2359     e |= ((*out_char >> 11) == 0x1b) << 7;  // surrogate half?
2360     e |= (*out_char > IM_UNICODE_CODEPOINT_MAX) << 8;  // out of range?
2361     e |= (s[1] & 0xc0) >> 2;
2362     e |= (s[2] & 0xc0) >> 4;
2363     e |= (s[3]       ) >> 6;
2364     e ^= 0x2a; // top two bits of each tail byte correct?
2365     e >>= shifte[len];
2366 
2367     if (e)
2368     {
2369         // No bytes are consumed when *in_text == 0 || in_text == in_text_end\&.
2370         // One byte is consumed in case of invalid first byte of in_text\&.
2371         // All available bytes (at most `len` bytes) are consumed on incomplete/invalid second to last bytes\&.
2372         // Invalid or incomplete input may consume less bytes than wanted, therefore every byte has to be inspected in s\&.
2373         wanted = ImMin(wanted, !!s[0] + !!s[1] + !!s[2] + !!s[3]);
2374         *out_char = IM_UNICODE_CODEPOINT_INVALID;
2375     }
2376 
2377     return wanted;
2378 }
.PP
.fi

.PP
Referenced by \fBImTextCountCharsFromUtf8()\fP, \fBImTextCountUtf8BytesFromChar()\fP, and \fBImTextStrFromUtf8()\fP\&.
.SS "const char * ImTextCharToUtf8 (char out_buf[5], unsigned int c)"

.PP
Definition at line \fB2444\fP of file \fBimgui\&.cpp\fP\&.
.nf
2445 {
2446     int count = ImTextCharToUtf8_inline(out_buf, 5, c);
2447     out_buf[count] = 0;
2448     return out_buf;
2449 }
.PP
.fi

.SS "int ImTextCountCharsFromUtf8 (const char * in_text, const char * in_text_end)"

.PP
Definition at line \fB2396\fP of file \fBimgui\&.cpp\fP\&.
.nf
2397 {
2398     int char_count = 0;
2399     while ((!in_text_end || in_text < in_text_end) && *in_text)
2400     {
2401         unsigned int c;
2402         in_text += ImTextCharFromUtf8(&c, in_text, in_text_end);
2403         char_count++;
2404     }
2405     return char_count;
2406 }
.PP
.fi

.PP
References \fBImTextCharFromUtf8()\fP\&.
.SS "int ImTextCountLines (const char * in_text, const char * in_text_end)"

.PP
Definition at line \fB2508\fP of file \fBimgui\&.cpp\fP\&.
.nf
2509 {
2510     if (in_text_end == NULL)
2511         in_text_end = in_text + strlen(in_text); // FIXME\-OPT: Not optimal approach, discourage use for now\&.
2512     int count = 0;
2513     while (in_text < in_text_end)
2514     {
2515         const char* line_end = (const char*)memchr(in_text, '\\n', in_text_end \- in_text);
2516         in_text = line_end ? line_end + 1 : in_text_end;
2517         count++;
2518     }
2519     return count;
2520 }
.PP
.fi

.SS "int ImTextCountUtf8BytesFromChar (const char * in_text, const char * in_text_end)"

.PP
Definition at line \fB2452\fP of file \fBimgui\&.cpp\fP\&.
.nf
2453 {
2454     unsigned int unused = 0;
2455     return ImTextCharFromUtf8(&unused, in_text, in_text_end);
2456 }
.PP
.fi

.PP
References \fBImTextCharFromUtf8()\fP\&.
.PP
Referenced by \fBImTextCountUtf8BytesFromStr()\fP\&.
.SS "int ImTextCountUtf8BytesFromStr (const ImWchar * in_text, const ImWchar * in_text_end)"

.PP
Definition at line \fB2483\fP of file \fBimgui\&.cpp\fP\&.
.nf
2484 {
2485     int bytes_count = 0;
2486     while ((!in_text_end || in_text < in_text_end) && *in_text)
2487     {
2488         unsigned int c = (unsigned int)(*in_text++);
2489         if (c < 0x80)
2490             bytes_count++;
2491         else
2492             bytes_count += ImTextCountUtf8BytesFromChar(c);
2493     }
2494     return bytes_count;
2495 }
.PP
.fi

.PP
References \fBImTextCountUtf8BytesFromChar()\fP\&.
.SS "const char * ImTextFindPreviousUtf8Codepoint (const char * in_text_start, const char * in_text_curr)"

.PP
Definition at line \fB2497\fP of file \fBimgui\&.cpp\fP\&.
.nf
2498 {
2499     while (in_text_curr > in_text_start)
2500     {
2501         in_text_curr\-\-;
2502         if ((*in_text_curr & 0xC0) != 0x80)
2503             return in_text_curr;
2504     }
2505     return in_text_start;
2506 }
.PP
.fi

.SS "int ImTextStrFromUtf8 (ImWchar * buf, int buf_size, const char * in_text, const char * in_text_end, const char ** in_text_remaining)"

.PP
Definition at line \fB2380\fP of file \fBimgui\&.cpp\fP\&.
.nf
2381 {
2382     ImWchar* buf_out = buf;
2383     ImWchar* buf_end = buf + buf_size;
2384     while (buf_out < buf_end \- 1 && (!in_text_end || in_text < in_text_end) && *in_text)
2385     {
2386         unsigned int c;
2387         in_text += ImTextCharFromUtf8(&c, in_text, in_text_end);
2388         *buf_out++ = (ImWchar)c;
2389     }
2390     *buf_out = 0;
2391     if (in_text_remaining)
2392         *in_text_remaining = in_text;
2393     return (int)(buf_out \- buf);
2394 }
.PP
.fi

.PP
References \fBImTextCharFromUtf8()\fP\&.
.SS "int ImTextStrToUtf8 (char * out_buf, int out_buf_size, const ImWchar * in_text, const ImWchar * in_text_end)"

.PP
Definition at line \fB2467\fP of file \fBimgui\&.cpp\fP\&.
.nf
2468 {
2469     char* buf_p = out_buf;
2470     const char* buf_end = out_buf + out_buf_size;
2471     while (buf_p < buf_end \- 1 && (!in_text_end || in_text < in_text_end) && *in_text)
2472     {
2473         unsigned int c = (unsigned int)(*in_text++);
2474         if (c < 0x80)
2475             *buf_p++ = (char)c;
2476         else
2477             buf_p += ImTextCharToUtf8_inline(buf_p, (int)(buf_end \- buf_p \- 1), c);
2478     }
2479     *buf_p = 0;
2480     return (int)(buf_p \- out_buf);
2481 }
.PP
.fi

.SS "void ImTriangleBarycentricCoords (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & p, float & out_u, float & out_v, float & out_w)"

.PP
Definition at line \fB1919\fP of file \fBimgui\&.cpp\fP\&.
.nf
1920 {
1921     ImVec2 v0 = b \- a;
1922     ImVec2 v1 = c \- a;
1923     ImVec2 v2 = p \- a;
1924     const float denom = v0\&.x * v1\&.y \- v1\&.x * v0\&.y;
1925     out_v = (v2\&.x * v1\&.y \- v1\&.x * v2\&.y) / denom;
1926     out_w = (v0\&.x * v2\&.y \- v2\&.x * v0\&.y) / denom;
1927     out_u = 1\&.0f \- out_v \- out_w;
1928 }
.PP
.fi

.SS "ImVec2 ImTriangleClosestPoint (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & p)"

.PP
Definition at line \fB1930\fP of file \fBimgui\&.cpp\fP\&.
.nf
1931 {
1932     ImVec2 proj_ab = ImLineClosestPoint(a, b, p);
1933     ImVec2 proj_bc = ImLineClosestPoint(b, c, p);
1934     ImVec2 proj_ca = ImLineClosestPoint(c, a, p);
1935     float dist2_ab = ImLengthSqr(p \- proj_ab);
1936     float dist2_bc = ImLengthSqr(p \- proj_bc);
1937     float dist2_ca = ImLengthSqr(p \- proj_ca);
1938     float m = ImMin(dist2_ab, ImMin(dist2_bc, dist2_ca));
1939     if (m == dist2_ab)
1940         return proj_ab;
1941     if (m == dist2_bc)
1942         return proj_bc;
1943     return proj_ca;
1944 }
.PP
.fi

.PP
References \fBImLineClosestPoint()\fP\&.
.SS "bool ImTriangleContainsPoint (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & p)"

.PP
Definition at line \fB1911\fP of file \fBimgui\&.cpp\fP\&.
.nf
1912 {
1913     bool b1 = ((p\&.x \- b\&.x) * (a\&.y \- b\&.y) \- (p\&.y \- b\&.y) * (a\&.x \- b\&.x)) < 0\&.0f;
1914     bool b2 = ((p\&.x \- c\&.x) * (b\&.y \- c\&.y) \- (p\&.y \- c\&.y) * (b\&.x \- c\&.x)) < 0\&.0f;
1915     bool b3 = ((p\&.x \- a\&.x) * (c\&.y \- a\&.y) \- (p\&.y \- a\&.y) * (c\&.x \- a\&.x)) < 0\&.0f;
1916     return ((b1 == b2) && (b2 == b3));
1917 }
.PP
.fi

.PP
Referenced by \fBImTriangulator::IsEar()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "ImGuiContext* GImGui = NULL"

.PP
Definition at line \fB1254\fP of file \fBimgui\&.cpp\fP\&.
.PP
Referenced by \fBImFormatStringToTempBufferV()\fP, and \fBImGui::ShowFontAtlas()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
