.TH "ImGuiDockNodeSettings" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiDockNodeSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiDockNodeSettings\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "ImGuiID \fBParentNodeId\fP"
.br
.ti -1c
.RI "ImGuiID \fBParentWindowId\fP"
.br
.ti -1c
.RI "ImGuiID \fBSelectedTabId\fP"
.br
.ti -1c
.RI "signed char \fBSplitAxis\fP"
.br
.ti -1c
.RI "char \fBDepth\fP"
.br
.ti -1c
.RI "ImGuiDockNodeFlags \fBFlags\fP"
.br
.ti -1c
.RI "ImVec2ih \fBPos\fP"
.br
.ti -1c
.RI "ImVec2ih \fBSize\fP"
.br
.ti -1c
.RI "ImVec2ih \fBSizeRef\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16056\fP of file \fBimgui\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiDockNodeSettings::ImGuiDockNodeSettings ()\fR [inline]\fP"

.PP
Definition at line \fB16068\fP of file \fBimgui\&.cpp\fP\&.
.nf
16068 { memset(this, 0, sizeof(*this)); SplitAxis = ImGuiAxis_None; }
.PP
.fi

.PP
References \fBSplitAxis\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char ImGuiDockNodeSettings::Depth"

.PP
Definition at line \fB16063\fP of file \fBimgui\&.cpp\fP\&.
.SS "ImGuiDockNodeFlags ImGuiDockNodeSettings::Flags"

.PP
Definition at line \fB16064\fP of file \fBimgui\&.cpp\fP\&.
.SS "ImGuiID ImGuiDockNodeSettings::ID"

.PP
Definition at line \fB16058\fP of file \fBimgui\&.cpp\fP\&.
.SS "ImGuiID ImGuiDockNodeSettings::ParentNodeId"

.PP
Definition at line \fB16059\fP of file \fBimgui\&.cpp\fP\&.
.SS "ImGuiID ImGuiDockNodeSettings::ParentWindowId"

.PP
Definition at line \fB16060\fP of file \fBimgui\&.cpp\fP\&.
.SS "ImVec2ih ImGuiDockNodeSettings::Pos"

.PP
Definition at line \fB16065\fP of file \fBimgui\&.cpp\fP\&.
.SS "ImGuiID ImGuiDockNodeSettings::SelectedTabId"

.PP
Definition at line \fB16061\fP of file \fBimgui\&.cpp\fP\&.
.SS "ImVec2ih ImGuiDockNodeSettings::Size"

.PP
Definition at line \fB16066\fP of file \fBimgui\&.cpp\fP\&.
.SS "ImVec2ih ImGuiDockNodeSettings::SizeRef"

.PP
Definition at line \fB16067\fP of file \fBimgui\&.cpp\fP\&.
.SS "signed char ImGuiDockNodeSettings::SplitAxis"

.PP
Definition at line \fB16062\fP of file \fBimgui\&.cpp\fP\&.
.PP
Referenced by \fBImGuiDockNodeSettings()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
