.TH "UPRISE_ENGINE/imgui_widgets.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/imgui_widgets.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'imgui\&.h'\fP
.br
\fR#include 'imgui_internal\&.h'\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include 'imstb_textedit\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBImGuiGetNameFromIndexOldToNewCallbackData\fP"
.br
.ti -1c
.RI "struct \fBImGuiPlotArrayGetterData\fP"
.br
.ti -1c
.RI "struct \fBImGuiTabBarSection\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBImStb\fP"
.br
.ti -1c
.RI "namespace \fBImGui\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIMGUI_DEFINE_MATH_OPERATORS\fP"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_MOVEWORDLEFT\fP   STB_TEXTEDIT_MOVEWORDLEFT_IMPL"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_MOVEWORDRIGHT\fP   STB_TEXTEDIT_MOVEWORDRIGHT_IMPL"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_LEFT\fP   0x200000"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_RIGHT\fP   0x200001"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_UP\fP   0x200002"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_DOWN\fP   0x200003"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_LINESTART\fP   0x200004"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_LINEEND\fP   0x200005"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_TEXTSTART\fP   0x200006"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_TEXTEND\fP   0x200007"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_DELETE\fP   0x200008"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_BACKSPACE\fP   0x200009"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_UNDO\fP   0x20000A"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_REDO\fP   0x20000B"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_WORDLEFT\fP   0x20000C"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_WORDRIGHT\fP   0x20000D"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_PGUP\fP   0x20000E"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_PGDOWN\fP   0x20000F"
.br
.ti -1c
.RI "#define \fBSTB_TEXTEDIT_K_SHIFT\fP   0x400000"
.br
.ti -1c
.RI "#define \fBIMSTB_TEXTEDIT_IMPLEMENTATION\fP"
.br
.ti -1c
.RI "#define \fBIMSTB_TEXTEDIT_memmove\fP   memmove"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIM_STATIC_ASSERT\fP (IM_ARRAYSIZE(GDataTypeInfo)==ImGuiDataType_COUNT)"
.br
.ti -1c
.RI "const char * \fBImParseFormatFindStart\fP (const char *fmt)"
.br
.ti -1c
.RI "const char * \fBImParseFormatFindEnd\fP (const char *fmt)"
.br
.ti -1c
.RI "const char * \fBImParseFormatTrimDecorations\fP (const char *fmt, char *buf, size_t buf_size)"
.br
.ti -1c
.RI "void \fBImParseFormatSanitizeForPrinting\fP (const char *fmt_in, char *fmt_out, size_t fmt_out_size)"
.br
.ti -1c
.RI "const char * \fBImParseFormatSanitizeForScanning\fP (const char *fmt_in, char *fmt_out, size_t fmt_out_size)"
.br
.ti -1c
.RI "int \fBImParseFormatPrecision\fP (const char *fmt, int default_precision)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define IMGUI_DEFINE_MATH_OPERATORS"

.PP
Definition at line \fB40\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define IMSTB_TEXTEDIT_IMPLEMENTATION"

.PP
Definition at line \fB4006\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define IMSTB_TEXTEDIT_memmove   memmove"

.PP
Definition at line \fB4007\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_BACKSPACE   0x200009"

.PP
Definition at line \fB3997\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_DELETE   0x200008"

.PP
Definition at line \fB3996\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_DOWN   0x200003"

.PP
Definition at line \fB3991\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_LEFT   0x200000"

.PP
Definition at line \fB3988\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_LINEEND   0x200005"

.PP
Definition at line \fB3993\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_LINESTART   0x200004"

.PP
Definition at line \fB3992\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_PGDOWN   0x20000F"

.PP
Definition at line \fB4003\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_PGUP   0x20000E"

.PP
Definition at line \fB4002\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_REDO   0x20000B"

.PP
Definition at line \fB3999\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_RIGHT   0x200001"

.PP
Definition at line \fB3989\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_SHIFT   0x400000"

.PP
Definition at line \fB4004\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_TEXTEND   0x200007"

.PP
Definition at line \fB3995\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_TEXTSTART   0x200006"

.PP
Definition at line \fB3994\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_UNDO   0x20000A"

.PP
Definition at line \fB3998\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_UP   0x200002"

.PP
Definition at line \fB3990\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_WORDLEFT   0x20000C"

.PP
Definition at line \fB4000\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_K_WORDRIGHT   0x20000D"

.PP
Definition at line \fB4001\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_MOVEWORDLEFT   STB_TEXTEDIT_MOVEWORDLEFT_IMPL"

.PP
Definition at line \fB3936\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "#define STB_TEXTEDIT_MOVEWORDRIGHT   STB_TEXTEDIT_MOVEWORDRIGHT_IMPL"

.PP
Definition at line \fB3937\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "IM_STATIC_ASSERT (IM_ARRAYSIZE(GDataTypeInfo)  = \fR=ImGuiDataType_COUNT\fP)"

.SS "const char * ImParseFormatFindEnd (const char * fmt)"

.PP
Definition at line \fB3450\fP of file \fBimgui_widgets\&.cpp\fP\&.
.nf
3451 {
3452     // Printf/scanf types modifiers: I/L/h/j/l/t/w/z\&. Other uppercase letters qualify as types aka end of the format\&.
3453     if (fmt[0] != '%')
3454         return fmt;
3455     const unsigned int ignored_uppercase_mask = (1 << ('I'\-'A')) | (1 << ('L'\-'A'));
3456     const unsigned int ignored_lowercase_mask = (1 << ('h'\-'a')) | (1 << ('j'\-'a')) | (1 << ('l'\-'a')) | (1 << ('t'\-'a')) | (1 << ('w'\-'a')) | (1 << ('z'\-'a'));
3457     for (char c; (c = *fmt) != 0; fmt++)
3458     {
3459         if (c >= 'A' && c <= 'Z' && ((1 << (c \- 'A')) & ignored_uppercase_mask) == 0)
3460             return fmt + 1;
3461         if (c >= 'a' && c <= 'z' && ((1 << (c \- 'a')) & ignored_lowercase_mask) == 0)
3462             return fmt + 1;
3463     }
3464     return fmt;
3465 }
.PP
.fi

.PP
Referenced by \fBImParseFormatSanitizeForPrinting()\fP, \fBImParseFormatSanitizeForScanning()\fP, and \fBImParseFormatTrimDecorations()\fP\&.
.SS "const char * ImParseFormatFindStart (const char * fmt)"

.PP
Definition at line \fB3437\fP of file \fBimgui_widgets\&.cpp\fP\&.
.nf
3438 {
3439     while (char c = fmt[0])
3440     {
3441         if (c == '%' && fmt[1] != '%')
3442             return fmt;
3443         else if (c == '%')
3444             fmt++;
3445         fmt++;
3446     }
3447     return fmt;
3448 }
.PP
.fi

.PP
Referenced by \fBImParseFormatPrecision()\fP, and \fBImParseFormatTrimDecorations()\fP\&.
.SS "int ImParseFormatPrecision (const char * fmt, int default_precision)"

.PP
Definition at line \fB3537\fP of file \fBimgui_widgets\&.cpp\fP\&.
.nf
3538 {
3539     fmt = ImParseFormatFindStart(fmt);
3540     if (fmt[0] != '%')
3541         return default_precision;
3542     fmt++;
3543     while (*fmt >= '0' && *fmt <= '9')
3544         fmt++;
3545     int precision = INT_MAX;
3546     if (*fmt == '\&.')
3547     {
3548         fmt = ImAtoi<int>(fmt + 1, &precision);
3549         if (precision < 0 || precision > 99)
3550             precision = default_precision;
3551     }
3552     if (*fmt == 'e' || *fmt == 'E') // Maximum precision with scientific notation
3553         precision = \-1;
3554     if ((*fmt == 'g' || *fmt == 'G') && precision == INT_MAX)
3555         precision = \-1;
3556     return (precision == INT_MAX) ? default_precision : precision;
3557 }
.PP
.fi

.PP
References \fBImParseFormatFindStart()\fP\&.
.SS "void ImParseFormatSanitizeForPrinting (const char * fmt_in, char * fmt_out, size_t fmt_out_size)"

.PP
Definition at line \fB3487\fP of file \fBimgui_widgets\&.cpp\fP\&.
.nf
3488 {
3489     const char* fmt_end = ImParseFormatFindEnd(fmt_in);
3490     IM_UNUSED(fmt_out_size);
3491     IM_ASSERT((size_t)(fmt_end \- fmt_in + 1) < fmt_out_size); // Format is too long, let us know if this happens to you!
3492     while (fmt_in < fmt_end)
3493     {
3494         char c = *fmt_in++;
3495         if (c != '\\'' && c != '$' && c != '_') // Custom flags provided by stb_sprintf\&.h\&. POSIX 2008 also supports '\&.
3496             *(fmt_out++) = c;
3497     }
3498     *fmt_out = 0; // Zero\-terminate
3499 }
.PP
.fi

.PP
References \fBImParseFormatFindEnd()\fP\&.
.SS "const char * ImParseFormatSanitizeForScanning (const char * fmt_in, char * fmt_out, size_t fmt_out_size)"

.PP
Definition at line \fB3502\fP of file \fBimgui_widgets\&.cpp\fP\&.
.nf
3503 {
3504     const char* fmt_end = ImParseFormatFindEnd(fmt_in);
3505     const char* fmt_out_begin = fmt_out;
3506     IM_UNUSED(fmt_out_size);
3507     IM_ASSERT((size_t)(fmt_end \- fmt_in + 1) < fmt_out_size); // Format is too long, let us know if this happens to you!
3508     bool has_type = false;
3509     while (fmt_in < fmt_end)
3510     {
3511         char c = *fmt_in++;
3512         if (!has_type && ((c >= '0' && c <= '9') || c == '\&.' || c == '+' || c == '#'))
3513             continue;
3514         has_type |= ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')); // Stop skipping digits
3515         if (c != '\\'' && c != '$' && c != '_') // Custom flags provided by stb_sprintf\&.h\&. POSIX 2008 also supports '\&.
3516             *(fmt_out++) = c;
3517     }
3518     *fmt_out = 0; // Zero\-terminate
3519     return fmt_out_begin;
3520 }
.PP
.fi

.PP
References \fBImParseFormatFindEnd()\fP\&.
.SS "const char * ImParseFormatTrimDecorations (const char * fmt, char * buf, size_t buf_size)"

.PP
Definition at line \fB3472\fP of file \fBimgui_widgets\&.cpp\fP\&.
.nf
3473 {
3474     const char* fmt_start = ImParseFormatFindStart(fmt);
3475     if (fmt_start[0] != '%')
3476         return "";
3477     const char* fmt_end = ImParseFormatFindEnd(fmt_start);
3478     if (fmt_end[0] == 0) // If we only have leading decoration, we don't need to copy the data\&.
3479         return fmt_start;
3480     ImStrncpy(buf, fmt_start, ImMin((size_t)(fmt_end \- fmt_start) + 1, buf_size));
3481     return buf;
3482 }
.PP
.fi

.PP
References \fBImParseFormatFindEnd()\fP, \fBImParseFormatFindStart()\fP, and \fBImStrncpy()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
