.TH "ImGuiResizeGripDef" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiResizeGripDef
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImVec2 \fBCornerPosN\fP"
.br
.ti -1c
.RI "ImVec2 \fBInnerDir\fP"
.br
.ti -1c
.RI "int \fBAngleMin12\fP"
.br
.ti -1c
.RI "int \fBAngleMax12\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6290\fP of file \fBimgui\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ImGuiResizeGripDef::AngleMax12"

.PP
Definition at line \fB6294\fP of file \fBimgui\&.cpp\fP\&.
.SS "int ImGuiResizeGripDef::AngleMin12"

.PP
Definition at line \fB6294\fP of file \fBimgui\&.cpp\fP\&.
.SS "ImVec2 ImGuiResizeGripDef::CornerPosN"

.PP
Definition at line \fB6292\fP of file \fBimgui\&.cpp\fP\&.
.SS "ImVec2 ImGuiResizeGripDef::InnerDir"

.PP
Definition at line \fB6293\fP of file \fBimgui\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
