.TH "ImGuiInputEventMouseViewport" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiInputEventMouseViewport
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBHoveredViewportID\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiID\fP ImGuiInputEventMouseViewport::HoveredViewportID"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
