.TH "UPRISE_ENGINE/imgui_demo.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/imgui_demo.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'imgui\&.h'\fP
.br
\fR#include <ctype\&.h>\fP
.br
\fR#include <limits\&.h>\fP
.br
\fR#include <math\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include <inttypes\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBExampleTreeNode\fP"
.br
.ti -1c
.RI "struct \fBExampleMemberInfo\fP"
.br
.ti -1c
.RI "struct \fBImGuiDemoWindowData\fP"
.br
.ti -1c
.RI "struct \fBExampleSelectionWithDeletion\fP"
.br
.ti -1c
.RI "struct \fBExampleDualListBox\fP"
.br
.ti -1c
.RI "struct \fBExampleAppConsole\fP"
.br
.ti -1c
.RI "struct \fBExampleAppLog\fP"
.br
.ti -1c
.RI "struct \fBExampleAppPropertyEditor\fP"
.br
.ti -1c
.RI "struct \fBMyDocument\fP"
.br
.ti -1c
.RI "struct \fBExampleAppDocuments\fP"
.br
.ti -1c
.RI "struct \fBExampleAsset\fP"
.br
.ti -1c
.RI "struct \fBExampleAssetsBrowser\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBImGui\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIM_NEWLINE\fP   '\\n'"
.br
.ti -1c
.RI "#define \fBPRId64\fP   'lld'"
.br
.ti -1c
.RI "#define \fBPRIu64\fP   'llu'"
.br
.ti -1c
.RI "#define \fBIM_MIN\fP(\fBA\fP,  \fBB\fP)   (((\fBA\fP) < (\fBB\fP)) ? (\fBA\fP) : (\fBB\fP))"
.br
.ti -1c
.RI "#define \fBIM_MAX\fP(\fBA\fP,  \fBB\fP)   (((\fBA\fP) >= (\fBB\fP)) ? (\fBA\fP) : (\fBB\fP))"
.br
.ti -1c
.RI "#define \fBIM_CLAMP\fP(\fBV\fP,  MN,  MX)   ((\fBV\fP) < (MN) ? (MN) : (\fBV\fP) > (MX) ? (MX) : (\fBV\fP))"
.br
.ti -1c
.RI "#define \fBIMGUI_CDECL\fP"
.br
.ti -1c
.RI "#define \fBIMGUI_DEMO_MARKER\fP(section)   do { if (\fBGImGuiDemoMarkerCallback\fP != NULL) \fBGImGuiDemoMarkerCallback\fP(__FILE__, __LINE__, section, \fBGImGuiDemoMarkerCallbackUserData\fP); } while (0)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBImGuiDemoMarkerCallback\fP) (const char *file, int line, const char *section, void *user_data)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "IMGUI_API void \fBImGui::ShowFontAtlas\fP (ImFontAtlas *atlas)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBImGuiDemoMarkerCallback\fP \fBGImGuiDemoMarkerCallback\fP = NULL"
.br
.ti -1c
.RI "void * \fBGImGuiDemoMarkerCallbackUserData\fP = NULL"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define IM_CLAMP( \fBV\fP,  MN,  MX)   ((\fBV\fP) < (MN) ? (MN) : (\fBV\fP) > (MX) ? (MX) : (\fBV\fP))"

.PP
Definition at line \fB184\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBExampleAssetsBrowser::Draw()\fP\&.
.SS "#define IM_MAX( \fBA\fP,  \fBB\fP)   (((\fBA\fP) >= (\fBB\fP)) ? (\fBA\fP) : (\fBB\fP))"

.PP
Definition at line \fB183\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBExampleAssetsBrowser::UpdateLayoutSizes()\fP\&.
.SS "#define IM_MIN( \fBA\fP,  \fBB\fP)   (((\fBA\fP) < (\fBB\fP)) ? (\fBA\fP) : (\fBB\fP))"

.PP
Definition at line \fB182\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBExampleSelectionWithDeletion::ApplyDeletionPreLoop()\fP, and \fBExampleAssetsBrowser::Draw()\fP\&.
.SS "#define IM_NEWLINE   '\\n'"

.PP
Definition at line \fB158\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "#define IMGUI_CDECL"

.PP
Definition at line \fB192\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "#define IMGUI_DEMO_MARKER( section)   do { if (\fBGImGuiDemoMarkerCallback\fP != NULL) \fBGImGuiDemoMarkerCallback\fP(__FILE__, __LINE__, section, \fBGImGuiDemoMarkerCallbackUserData\fP); } while (0)"

.PP
Definition at line \fB266\fP of file \fBimgui_demo\&.cpp\fP\&.
.PP
Referenced by \fBExampleAppConsole::ExampleAppConsole()\fP\&.
.SS "#define PRId64   'lld'"

.PP
Definition at line \fB174\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "#define PRIu64   'llu'"

.PP
Definition at line \fB175\fP of file \fBimgui_demo\&.cpp\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* ImGuiDemoMarkerCallback) (const char *file, int line, const char *section, void *user_data)"

.PP
Definition at line \fB261\fP of file \fBimgui_demo\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBImGuiDemoMarkerCallback\fP GImGuiDemoMarkerCallback = NULL"

.PP
Definition at line \fB264\fP of file \fBimgui_demo\&.cpp\fP\&.
.SS "void * GImGuiDemoMarkerCallbackUserData = NULL"

.PP
Definition at line \fB265\fP of file \fBimgui_demo\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
