.TH "ImGuiDockContextPruneNodeData" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiDockContextPruneNodeData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiDockContextPruneNodeData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBCountWindows\fP"
.br
.ti -1c
.RI "int \fBCountChildWindows\fP"
.br
.ti -1c
.RI "int \fBCountChildNodes\fP"
.br
.ti -1c
.RI "ImGuiID \fBRootId\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16374\fP of file \fBimgui\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiDockContextPruneNodeData::ImGuiDockContextPruneNodeData ()\fR [inline]\fP"

.PP
Definition at line \fB16378\fP of file \fBimgui\&.cpp\fP\&.
.nf
16378 { CountWindows = CountChildWindows = CountChildNodes = 0; RootId = 0; }
.PP
.fi

.PP
References \fBCountChildNodes\fP, \fBCountChildWindows\fP, \fBCountWindows\fP, and \fBRootId\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ImGuiDockContextPruneNodeData::CountChildNodes"

.PP
Definition at line \fB16376\fP of file \fBimgui\&.cpp\fP\&.
.PP
Referenced by \fBImGuiDockContextPruneNodeData()\fP\&.
.SS "int ImGuiDockContextPruneNodeData::CountChildWindows"

.PP
Definition at line \fB16376\fP of file \fBimgui\&.cpp\fP\&.
.PP
Referenced by \fBImGuiDockContextPruneNodeData()\fP\&.
.SS "int ImGuiDockContextPruneNodeData::CountWindows"

.PP
Definition at line \fB16376\fP of file \fBimgui\&.cpp\fP\&.
.PP
Referenced by \fBImGuiDockContextPruneNodeData()\fP\&.
.SS "ImGuiID ImGuiDockContextPruneNodeData::RootId"

.PP
Definition at line \fB16377\fP of file \fBimgui\&.cpp\fP\&.
.PP
Referenced by \fBImGuiDockContextPruneNodeData()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
