.TH "ImGuiDockPreviewData" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiDockPreviewData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiDockPreviewData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiDockNode \fBFutureNode\fP"
.br
.ti -1c
.RI "bool \fBIsDropAllowed\fP"
.br
.ti -1c
.RI "bool \fBIsCenterAvailable\fP"
.br
.ti -1c
.RI "bool \fBIsSidesAvailable\fP"
.br
.ti -1c
.RI "bool \fBIsSplitDirExplicit\fP"
.br
.ti -1c
.RI "ImGuiDockNode * \fBSplitNode\fP"
.br
.ti -1c
.RI "ImGuiDir \fBSplitDir\fP"
.br
.ti -1c
.RI "float \fBSplitRatio\fP"
.br
.ti -1c
.RI "ImRect \fBDropRectsDraw\fP [ImGuiDir_COUNT+1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16040\fP of file \fBimgui\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiDockPreviewData::ImGuiDockPreviewData ()\fR [inline]\fP"

.PP
Definition at line \fB16052\fP of file \fBimgui\&.cpp\fP\&.
.nf
16052 : FutureNode(0) { IsDropAllowed = IsCenterAvailable = IsSidesAvailable = IsSplitDirExplicit = false; SplitNode = NULL; SplitDir = ImGuiDir_None; SplitRatio = 0\&.f; for (int n = 0; n < IM_ARRAYSIZE(DropRectsDraw); n++) DropRectsDraw[n] = ImRect(+FLT_MAX, +FLT_MAX, \-FLT_MAX, \-FLT_MAX); }
.PP
.fi

.PP
References \fBDropRectsDraw\fP, \fBIsCenterAvailable\fP, \fBIsDropAllowed\fP, \fBIsSidesAvailable\fP, \fBIsSplitDirExplicit\fP, \fBSplitDir\fP, \fBSplitNode\fP, and \fBSplitRatio\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "ImRect ImGuiDockPreviewData::DropRectsDraw[ImGuiDir_COUNT+1]"

.PP
Definition at line \fB16050\fP of file \fBimgui\&.cpp\fP\&.
.PP
Referenced by \fBImGuiDockPreviewData()\fP\&.
.SS "ImGuiDockNode ImGuiDockPreviewData::FutureNode"

.PP
Definition at line \fB16042\fP of file \fBimgui\&.cpp\fP\&.
.SS "bool ImGuiDockPreviewData::IsCenterAvailable"

.PP
Definition at line \fB16044\fP of file \fBimgui\&.cpp\fP\&.
.PP
Referenced by \fBImGuiDockPreviewData()\fP\&.
.SS "bool ImGuiDockPreviewData::IsDropAllowed"

.PP
Definition at line \fB16043\fP of file \fBimgui\&.cpp\fP\&.
.PP
Referenced by \fBImGuiDockPreviewData()\fP\&.
.SS "bool ImGuiDockPreviewData::IsSidesAvailable"

.PP
Definition at line \fB16045\fP of file \fBimgui\&.cpp\fP\&.
.PP
Referenced by \fBImGuiDockPreviewData()\fP\&.
.SS "bool ImGuiDockPreviewData::IsSplitDirExplicit"

.PP
Definition at line \fB16046\fP of file \fBimgui\&.cpp\fP\&.
.PP
Referenced by \fBImGuiDockPreviewData()\fP\&.
.SS "ImGuiDir ImGuiDockPreviewData::SplitDir"

.PP
Definition at line \fB16048\fP of file \fBimgui\&.cpp\fP\&.
.PP
Referenced by \fBImGuiDockPreviewData()\fP\&.
.SS "ImGuiDockNode* ImGuiDockPreviewData::SplitNode"

.PP
Definition at line \fB16047\fP of file \fBimgui\&.cpp\fP\&.
.PP
Referenced by \fBImGuiDockPreviewData()\fP\&.
.SS "float ImGuiDockPreviewData::SplitRatio"

.PP
Definition at line \fB16049\fP of file \fBimgui\&.cpp\fP\&.
.PP
Referenced by \fBImGuiDockPreviewData()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
