.TH "ImGuiTabBarSection" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTabBarSection
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiTabBarSection\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBTabCount\fP"
.br
.ti -1c
.RI "float \fBWidth\fP"
.br
.ti -1c
.RI "float \fBSpacing\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8992\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiTabBarSection::ImGuiTabBarSection ()\fR [inline]\fP"

.PP
Definition at line \fB8998\fP of file \fBimgui_widgets\&.cpp\fP\&.
.nf
8998 { memset(this, 0, sizeof(*this)); }
.PP
.fi

.SH "Member Data Documentation"
.PP 
.SS "float ImGuiTabBarSection::Spacing"

.PP
Definition at line \fB8996\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "int ImGuiTabBarSection::TabCount"

.PP
Definition at line \fB8994\fP of file \fBimgui_widgets\&.cpp\fP\&.
.SS "float ImGuiTabBarSection::Width"

.PP
Definition at line \fB8995\fP of file \fBimgui_widgets\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
