.TH "IMPORTANT" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IMPORTANT
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pch\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBDATALINK\fP * \fBDATA\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBDATALINK\fP * IMPORTANT::DATA\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
