.TH "ImSpan< T >" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImSpan< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImSpan\fP ()"
.br
.ti -1c
.RI "\fBImSpan\fP (\fBT\fP *\fBdata\fP, int \fBsize\fP)"
.br
.ti -1c
.RI "\fBImSpan\fP (\fBT\fP *\fBdata\fP, \fBT\fP *data_end)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset\fP (\fBT\fP *\fBdata\fP, int \fBsize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset\fP (\fBT\fP *\fBdata\fP, \fBT\fP *data_end)"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.ti -1c
.RI "int \fBsize_in_bytes\fP () const"
.br
.ti -1c
.RI "\fBT\fP & \fBoperator[]\fP (int \fBi\fP)"
.br
.ti -1c
.RI "const \fBT\fP & \fBoperator[]\fP (int \fBi\fP) const"
.br
.ti -1c
.RI "\fBT\fP * \fBbegin\fP ()"
.br
.ti -1c
.RI "const \fBT\fP * \fBbegin\fP () const"
.br
.ti -1c
.RI "\fBT\fP * \fBend\fP ()"
.br
.ti -1c
.RI "const \fBT\fP * \fBend\fP () const"
.br
.ti -1c
.RI "int \fBindex_from_ptr\fP (const \fBT\fP *it) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBT\fP * \fBData\fP"
.br
.ti -1c
.RI "\fBT\fP * \fBDataEnd\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \fBT\fP > \fBImSpan\fP< \fBT\fP >\fB::ImSpan\fP ()\fR [inline]\fP"

.SS "template<typename \fBT\fP > \fBImSpan\fP< \fBT\fP >\fB::ImSpan\fP (\fBT\fP * data, int size)\fR [inline]\fP"

.SS "template<typename \fBT\fP > \fBImSpan\fP< \fBT\fP >\fB::ImSpan\fP (\fBT\fP * data, \fBT\fP * data_end)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBT\fP > \fBT\fP * \fBImSpan\fP< \fBT\fP >::begin ()\fR [inline]\fP"

.SS "template<typename \fBT\fP > const \fBT\fP * \fBImSpan\fP< \fBT\fP >::begin () const\fR [inline]\fP"

.SS "template<typename \fBT\fP > \fBT\fP * \fBImSpan\fP< \fBT\fP >\fB::end\fP ()\fR [inline]\fP"

.SS "template<typename \fBT\fP > const \fBT\fP * \fBImSpan\fP< \fBT\fP >\fB::end\fP () const\fR [inline]\fP"

.SS "template<typename \fBT\fP > int \fBImSpan\fP< \fBT\fP >::index_from_ptr (const \fBT\fP * it) const\fR [inline]\fP"

.SS "template<typename \fBT\fP > \fBT\fP & \fBImSpan\fP< \fBT\fP >::operator[] (int i)\fR [inline]\fP"

.SS "template<typename \fBT\fP > const \fBT\fP & \fBImSpan\fP< \fBT\fP >::operator[] (int i) const\fR [inline]\fP"

.SS "template<typename \fBT\fP > \fBvoid\fP \fBImSpan\fP< \fBT\fP >::set (\fBT\fP * data, int size)\fR [inline]\fP"

.SS "template<typename \fBT\fP > \fBvoid\fP \fBImSpan\fP< \fBT\fP >::set (\fBT\fP * data, \fBT\fP * data_end)\fR [inline]\fP"

.SS "template<typename \fBT\fP > int \fBImSpan\fP< \fBT\fP >\fB::size\fP () const\fR [inline]\fP"

.SS "template<typename \fBT\fP > int \fBImSpan\fP< \fBT\fP >::size_in_bytes () const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBT\fP > \fBT\fP* \fBImSpan\fP< \fBT\fP >::Data"

.SS "template<typename \fBT\fP > \fBT\fP* \fBImSpan\fP< \fBT\fP >::DataEnd"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
