.TH "ImTriangulatorNode" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImTriangulatorNode
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUnlink\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImTriangulatorNodeType\fP \fBType\fP"
.br
.ti -1c
.RI "int \fBIndex\fP"
.br
.ti -1c
.RI "ImVec2 \fBPos\fP"
.br
.ti -1c
.RI "\fBImTriangulatorNode\fP * \fBNext\fP"
.br
.ti -1c
.RI "\fBImTriangulatorNode\fP * \fBPrev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1739\fP of file \fBimgui_draw\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ImTriangulatorNode::Unlink ()\fR [inline]\fP"

.PP
Definition at line \fB1747\fP of file \fBimgui_draw\&.cpp\fP\&.
.nf
1747 { Next\->Prev = Prev; Prev\->Next = Next; }
.PP
.fi

.PP
References \fBNext\fP, and \fBPrev\fP\&.
.PP
Referenced by \fBImTriangulator::GetNextTriangle()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ImTriangulatorNode::Index"

.PP
Definition at line \fB1742\fP of file \fBimgui_draw\&.cpp\fP\&.
.PP
Referenced by \fBImTriangulator::BuildEars()\fP, \fBImTriangulator::BuildNodes()\fP, \fBImTriangulator::GetNextTriangle()\fP, \fBImTriangulator::IsEar()\fP, and \fBImTriangulator::ReclassifyNode()\fP\&.
.SS "\fBImTriangulatorNode\fP* ImTriangulatorNode::Next"

.PP
Definition at line \fB1744\fP of file \fBimgui_draw\&.cpp\fP\&.
.PP
Referenced by \fBImTriangulator::BuildEars()\fP, \fBImTriangulator::BuildNodes()\fP, \fBImTriangulator::BuildReflexes()\fP, \fBImTriangulator::FlipNodeList()\fP, \fBImTriangulator::GetNextTriangle()\fP, \fBImTriangulator::ReclassifyNode()\fP, and \fBUnlink()\fP\&.
.SS "ImVec2 ImTriangulatorNode::Pos"

.PP
Definition at line \fB1743\fP of file \fBimgui_draw\&.cpp\fP\&.
.PP
Referenced by \fBImTriangulator::BuildEars()\fP, \fBImTriangulator::BuildNodes()\fP, \fBImTriangulator::BuildReflexes()\fP, \fBImTriangulator::IsEar()\fP, and \fBImTriangulator::ReclassifyNode()\fP\&.
.SS "\fBImTriangulatorNode\fP* ImTriangulatorNode::Prev"

.PP
Definition at line \fB1745\fP of file \fBimgui_draw\&.cpp\fP\&.
.PP
Referenced by \fBImTriangulator::BuildEars()\fP, \fBImTriangulator::BuildNodes()\fP, \fBImTriangulator::BuildReflexes()\fP, \fBImTriangulator::FlipNodeList()\fP, \fBImTriangulator::GetNextTriangle()\fP, \fBImTriangulator::ReclassifyNode()\fP, and \fBUnlink()\fP\&.
.SS "\fBImTriangulatorNodeType\fP ImTriangulatorNode::Type"

.PP
Definition at line \fB1741\fP of file \fBimgui_draw\&.cpp\fP\&.
.PP
Referenced by \fBImTriangulator::BuildEars()\fP, \fBImTriangulator::BuildNodes()\fP, \fBImTriangulator::BuildReflexes()\fP, \fBImTriangulator::GetNextTriangle()\fP, and \fBImTriangulator::ReclassifyNode()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
