.TH "ImTriangulatorNodeSpan" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImTriangulatorNodeSpan
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpush_back\fP (\fBImTriangulatorNode\fP *node)"
.br
.ti -1c
.RI "void \fBfind_erase_unsorted\fP (int idx)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImTriangulatorNode\fP ** \fBData\fP = NULL"
.br
.ti -1c
.RI "int \fBSize\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1750\fP of file \fBimgui_draw\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ImTriangulatorNodeSpan::find_erase_unsorted (int idx)\fR [inline]\fP"

.PP
Definition at line \fB1756\fP of file \fBimgui_draw\&.cpp\fP\&.
.nf
1756 { for (int i = Size \- 1; i >= 0; i\-\-) if (Data[i]\->Index == idx) { Data[i] = Data[Size \- 1]; Size\-\-; return; } }
.PP
.fi

.PP
References \fBData\fP, \fBi\fP, and \fBSize\fP\&.
.PP
Referenced by \fBImTriangulator::ReclassifyNode()\fP\&.
.SS "void ImTriangulatorNodeSpan::push_back (\fBImTriangulatorNode\fP * node)\fR [inline]\fP"

.PP
Definition at line \fB1755\fP of file \fBimgui_draw\&.cpp\fP\&.
.nf
1755 { Data[Size++] = node; }
.PP
.fi

.PP
References \fBData\fP, and \fBSize\fP\&.
.PP
Referenced by \fBImTriangulator::BuildEars()\fP, \fBImTriangulator::BuildReflexes()\fP, and \fBImTriangulator::ReclassifyNode()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBImTriangulatorNode\fP** ImTriangulatorNodeSpan::Data = NULL"

.PP
Definition at line \fB1752\fP of file \fBimgui_draw\&.cpp\fP\&.
.PP
Referenced by \fBfind_erase_unsorted()\fP, \fBImTriangulator::GetNextTriangle()\fP, \fBImTriangulator::Init()\fP, \fBImTriangulator::IsEar()\fP, and \fBpush_back()\fP\&.
.SS "int ImTriangulatorNodeSpan::Size = 0"

.PP
Definition at line \fB1753\fP of file \fBimgui_draw\&.cpp\fP\&.
.PP
Referenced by \fBfind_erase_unsorted()\fP, \fBImTriangulator::GetNextTriangle()\fP, \fBImTriangulator::IsEar()\fP, and \fBpush_back()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
