.TH "adhed/libbacktrace/internal.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/libbacktrace/internal.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtracy::backtrace_state\fP"
.br
.ti -1c
.RI "struct \fBtracy::backtrace_view\fP"
.br
.ti -1c
.RI "struct \fBtracy::backtrace_vector\fP"
.br
.ti -1c
.RI "struct \fBtracy::dwarf_sections\fP"
.br
.ti -1c
.RI "struct \fBtracy::backtrace_call_full\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGCC_VERSION\fP   (__GNUC__ * 1000 + __GNUC_MINOR__)"
.br
.ti -1c
.RI "#define \fB__attribute__\fP(\fBx\fP)"
.br
.ti -1c
.RI "#define \fBATTRIBUTE_UNUSED\fP   \fB__attribute__\fP ((__unused__))"
.br
.ti -1c
.RI "#define \fBATTRIBUTE_MALLOC\fP"
.br
.ti -1c
.RI "#define \fBATTRIBUTE_FALLTHROUGH\fP"
.br
.ti -1c
.RI "#define \fB__sync_bool_compare_and_swap\fP(\fBA\fP,  \fBB\fP,  \fBC\fP)   (abort(), 1)"
.br
.ti -1c
.RI "#define \fB__sync_lock_test_and_set\fP(\fBA\fP,  \fBB\fP)   (abort(), 0)"
.br
.ti -1c
.RI "#define \fB__sync_lock_release\fP(\fBA\fP)   abort()"
.br
.ti -1c
.RI "#define \fBbacktrace_atomic_load_pointer\fP(p)   (abort(), (\fBvoid\fP *) NULL)"
.br
.ti -1c
.RI "#define \fBbacktrace_atomic_load_int\fP(p)   (abort(), 0)"
.br
.ti -1c
.RI "#define \fBbacktrace_atomic_store_pointer\fP(p,  \fBv\fP)   abort()"
.br
.ti -1c
.RI "#define \fBbacktrace_atomic_store_size_t\fP(p,  \fBv\fP)   abort()"
.br
.ti -1c
.RI "#define \fBbacktrace_atomic_store_int\fP(p,  \fBv\fP)   abort()"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int(* \fBtracy::fileline\fP) (\fBstruct\fP \fBbacktrace_state\fP *state, uintptr_t pc, \fBbacktrace_full_callback\fP callback, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP)"
.br
.ti -1c
.RI "typedef \fBvoid\fP(* \fBtracy::syminfo\fP) (\fBstruct\fP \fBbacktrace_state\fP *state, uintptr_t pc, \fBbacktrace_syminfo_callback\fP callback, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtracy::dwarf_section\fP { \fBtracy::DEBUG_INFO\fP, \fBtracy::DEBUG_LINE\fP, \fBtracy::DEBUG_ABBREV\fP, \fBtracy::DEBUG_RANGES\fP, \fBtracy::DEBUG_STR\fP, \fBtracy::DEBUG_ADDR\fP, \fBtracy::DEBUG_STR_OFFSETS\fP, \fBtracy::DEBUG_LINE_STR\fP, \fBtracy::DEBUG_RNGLISTS\fP, \fBtracy::DEBUG_MAX\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtracy::backtrace_open\fP (const char *filename, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP, int *does_not_exist)"
.br
.ti -1c
.RI "int \fBtracy::backtrace_get_view\fP (\fBstruct\fP \fBbacktrace_state\fP *state, int descriptor, off_t \fBoffset\fP, uint64_t \fBsize\fP, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP, \fBstruct\fP \fBbacktrace_view\fP *view)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtracy::backtrace_release_view\fP (\fBstruct\fP \fBbacktrace_state\fP *state, \fBstruct\fP \fBbacktrace_view\fP *view, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP)"
.br
.ti -1c
.RI "int \fBtracy::backtrace_close\fP (int descriptor, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtracy::backtrace_qsort\fP (\fBvoid\fP *base, size_t \fBcount\fP, size_t \fBsize\fP, int(*compar)(const \fBvoid\fP *, const \fBvoid\fP *))"
.br
.ti -1c
.RI "\fBvoid\fP * \fBtracy::backtrace_alloc\fP (\fBstruct\fP \fBbacktrace_state\fP *state, size_t \fBsize\fP, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP) \fBATTRIBUTE_MALLOC\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBtracy::backtrace_free\fP (\fBstruct\fP \fBbacktrace_state\fP *state, \fBvoid\fP *mem, size_t \fBsize\fP, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBtracy::backtrace_vector_grow\fP (\fBstruct\fP \fBbacktrace_state\fP *state, size_t \fBsize\fP, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP, \fBstruct\fP \fBbacktrace_vector\fP *vec)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBtracy::backtrace_vector_finish\fP (\fBstruct\fP \fBbacktrace_state\fP *state, \fBstruct\fP \fBbacktrace_vector\fP *vec, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP)"
.br
.ti -1c
.RI "int \fBtracy::backtrace_vector_release\fP (\fBstruct\fP \fBbacktrace_state\fP *state, \fBstruct\fP \fBbacktrace_vector\fP *vec, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP)"
.br
.ti -1c
.RI "int \fBtracy::backtrace_initialize\fP (\fBstruct\fP \fBbacktrace_state\fP *state, const char *filename, int descriptor, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP, \fBfileline\fP *fileline_fn)"
.br
.ti -1c
.RI "int \fBtracy::backtrace_dwarf_add\fP (\fBstruct\fP \fBbacktrace_state\fP *state, uintptr_t base_address, const \fBstruct\fP \fBdwarf_sections\fP *\fBdwarf_sections\fP, int is_bigendian, \fBstruct\fP \fBdwarf_data\fP *fileline_altlink, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP, \fBfileline\fP *fileline_fn, \fBstruct\fP \fBdwarf_data\fP **fileline_entry)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtracy::backtrace_syminfo_to_full_callback\fP (\fBvoid\fP *\fBdata\fP, uintptr_t pc, const char *symname, uintptr_t symval \fBATTRIBUTE_UNUSED\fP, uintptr_t symsize \fBATTRIBUTE_UNUSED\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtracy::backtrace_syminfo_to_full_error_callback\fP (\fBvoid\fP *\fBdata\fP, const char *msg, int errnum)"
.br
.ti -1c
.RI "int \fBtracy::backtrace_uncompress_zdebug\fP (\fBstruct\fP \fBbacktrace_state\fP *state, const unsigned char *compressed, size_t compressed_size, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP, unsigned char **uncompressed, size_t *uncompressed_size)"
.br
.ti -1c
.RI "int \fBtracy::backtrace_uncompress_zstd\fP (\fBstruct\fP \fBbacktrace_state\fP *state, const unsigned char *compressed, size_t compressed_size, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP, unsigned char *uncompressed, size_t uncompressed_size)"
.br
.ti -1c
.RI "int \fBtracy::backtrace_uncompress_lzma\fP (\fBstruct\fP \fBbacktrace_state\fP *state, const unsigned char *compressed, size_t compressed_size, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP, unsigned char **uncompressed, size_t *uncompressed_size)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __attribute__( \fBx\fP)"

.SS "#define __sync_bool_compare_and_swap( \fBA\fP,  \fBB\fP,  \fBC\fP)   (abort(), 1)"

.SS "#define __sync_lock_release( \fBA\fP)   abort()"

.SS "#define __sync_lock_test_and_set( \fBA\fP,  \fBB\fP)   (abort(), 0)"

.SS "#define ATTRIBUTE_FALLTHROUGH"

.SS "#define ATTRIBUTE_MALLOC"

.SS "#define ATTRIBUTE_UNUSED   \fB__attribute__\fP ((__unused__))"

.SS "#define backtrace_atomic_load_int( p)   (abort(), 0)"

.SS "#define backtrace_atomic_load_pointer( p)   (abort(), (\fBvoid\fP *) NULL)"

.SS "#define backtrace_atomic_store_int( p,  \fBv\fP)   abort()"

.SS "#define backtrace_atomic_store_pointer( p,  \fBv\fP)   abort()"

.SS "#define backtrace_atomic_store_size_t( p,  \fBv\fP)   abort()"

.SS "#define GCC_VERSION   (__GNUC__ * 1000 + __GNUC_MINOR__)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
