.TH "adhed/glm/gtx/intersect.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/intersect.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <cfloat>\fP
.br
\fR#include <limits>\fP
.br
\fR#include '\&.\&./glm\&.hpp'\fP
.br
\fR#include '\&.\&./geometric\&.hpp'\fP
.br
\fR#include '\&.\&./gtx/closest_point\&.hpp'\fP
.br
\fR#include '\&.\&./gtx/vector_query\&.hpp'\fP
.br
\fR#include 'intersect\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP bool \fBglm::intersectRayPlane\fP (genType const &orig, genType const &dir, genType const &planeOrig, genType const &planeNormal, typename genType::value_type &intersectionDistance)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP bool \fBglm::intersectRayTriangle\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &orig, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &dir, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv0\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv2\fP, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > &baryPosition, \fBT\fP &distance)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP bool \fBglm::intersectLineTriangle\fP (genType const &orig, genType const &dir, genType const &vert0, genType const &vert1, genType const &vert2, genType &position)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP bool \fBglm::intersectRaySphere\fP (genType const &rayStarting, genType const &rayNormalizedDirection, genType const &sphereCenter, typename genType::value_type const sphereRadiusSquared, typename genType::value_type &intersectionDistance)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP bool \fBglm::intersectRaySphere\fP (genType const &rayStarting, genType const &rayNormalizedDirection, genType const &sphereCenter, const typename genType::value_type sphereRadius, genType &intersectionPosition, genType &intersectionNormal)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP bool \fBglm::intersectLineSphere\fP (genType const &point0, genType const &point1, genType const &sphereCenter, typename genType::value_type sphereRadius, genType &intersectionPosition1, genType &intersectionNormal1, genType &intersectionPosition2=genType(), genType &intersectionNormal2=genType())"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_intersect\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTX_closest_point\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
