.TH "adhed/glm/gtx/io.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/io.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./glm\&.hpp'\fP
.br
\fR#include '\&.\&./gtx/quaternion\&.hpp'\fP
.br
\fR#include <iosfwd>\fP
.br
\fR#include <locale>\fP
.br
\fR#include <utility>\fP
.br
\fR#include 'io\&.inl'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBglm::io::format_punct< CTy >\fP"
.br
.ti -1c
.RI "class \fBglm::io::basic_state_saver< CTy, CTr >\fP"
.br
.ti -1c
.RI "class \fBglm::io::basic_format_saver< CTy, CTr >\fP"
.br
.ti -1c
.RI "struct \fBglm::io::precision\fP"
.br
.ti -1c
.RI "struct \fBglm::io::width\fP"
.br
.ti -1c
.RI "struct \fBglm::io::delimeter< CTy >\fP"
.br
.ti -1c
.RI "struct \fBglm::io::order\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.ti -1c
.RI "namespace \fBglm::io\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBbasic_state_saver\fP< char > \fBglm::io::state_saver\fP"
.br
.ti -1c
.RI "typedef \fBbasic_state_saver\fP< wchar_t > \fBglm::io::wstate_saver\fP"
.br
.ti -1c
.RI "typedef \fBbasic_format_saver\fP< char > \fBglm::io::format_saver\fP"
.br
.ti -1c
.RI "typedef \fBbasic_format_saver\fP< wchar_t > \fBglm::io::wformat_saver\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBglm::io::order_type\fP { \fBglm::io::column_major\fP, \fBglm::io::row_major\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename FTy , typename CTy , typename CTr > FTy const & \fBglm::io::get_facet\fP (std::basic_ios< CTy, CTr > &)"
.br
.ti -1c
.RI "template<typename FTy , typename CTy , typename CTr > std::basic_ios< CTy, CTr > & \fBglm::io::formatted\fP (std::basic_ios< CTy, CTr > &)"
.br
.ti -1c
.RI "template<typename FTy , typename CTy , typename CTr > std::basic_ios< CTy, CTr > & \fBglm::io::unformatted\fP (std::basic_ios< CTy, CTr > &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > std::basic_ostream< CTy, CTr > & \fBglm::io::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBprecision\fP const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > std::basic_ostream< CTy, CTr > & \fBglm::io::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBwidth\fP const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > std::basic_ostream< CTy, CTr > & \fBglm::io::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBdelimeter\fP< CTy > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > std::basic_ostream< CTy, CTr > & \fBglm::io::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBorder\fP const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBqua\fP< \fBT\fP, \fBQ\fP > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 2, 3, \fBT\fP, \fBQ\fP > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 2, 4, \fBT\fP, \fBQ\fP > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 3, 2, \fBT\fP, \fBQ\fP > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 3, 4, \fBT\fP, \fBQ\fP > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 4, 2, \fBT\fP, \fBQ\fP > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 4, 3, \fBT\fP, \fBQ\fP > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, std::pair< \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const > const &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_io\fP
.PP
\fBAuthor\fP
.RS 4
Jan P Springer (regnirpsj@gmail.com)
.RE
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTC_matrix_access\fP (dependence) 
.PP
\fBGLM_GTC_quaternion\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
