.TH "packages/directxtk12_uwp.2024.6.5.1/include/Keyboard.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/directxtk12_uwp.2024.6.5.1/include/Keyboard.h
.SH SYNOPSIS
.br
.PP
\fR#include <cstdint>\fP
.br
\fR#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDirectX::Keyboard\fP"
.br
.ti -1c
.RI "struct \fBDirectX::Keyboard::State\fP"
.br
.ti -1c
.RI "class \fBDirectX::Keyboard::KeyboardStateTracker\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDirectX\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
