.TH "Layer" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Layer
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <D_TAG_LAYERS\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLayer\fP ()=default"
.br
.ti -1c
.RI "\fBLayer\fP (int id, std::string name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBD_TAG_LAYERS\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Layer::Layer ()\fR [default]\fP"

.SS "Layer::Layer (int id, std::string name)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
