.TH "adhed/libbacktrace/macho.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/libbacktrace/macho.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include <sys/types\&.h>\fP
.br
\fR#include <dirent\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include 'backtrace\&.hpp'\fP
.br
\fR#include 'internal\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtracy::macho_header_32\fP"
.br
.ti -1c
.RI "struct \fBtracy::macho_header_64\fP"
.br
.ti -1c
.RI "struct \fBtracy::macho_header_fat\fP"
.br
.ti -1c
.RI "struct \fBtracy::macho_fat_arch\fP"
.br
.ti -1c
.RI "struct \fBtracy::macho_fat_arch_64\fP"
.br
.ti -1c
.RI "struct \fBtracy::macho_load_command\fP"
.br
.ti -1c
.RI "struct \fBtracy::macho_segment_command\fP"
.br
.ti -1c
.RI "struct \fBtracy::macho_segment_64_command\fP"
.br
.ti -1c
.RI "struct \fBtracy::macho_symtab_command\fP"
.br
.ti -1c
.RI "struct \fBtracy::macho_uuid_command\fP"
.br
.ti -1c
.RI "struct \fBtracy::macho_section\fP"
.br
.ti -1c
.RI "struct \fBtracy::macho_section_64\fP"
.br
.ti -1c
.RI "struct \fBtracy::macho_nlist\fP"
.br
.ti -1c
.RI "struct \fBtracy::macho_nlist_64\fP"
.br
.ti -1c
.RI "struct \fBtracy::macho_symbol\fP"
.br
.ti -1c
.RI "struct \fBtracy::macho_syminfo_data\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMACH_O_MH_MAGIC_32\fP   0xfeedface"
.br
.ti -1c
.RI "#define \fBMACH_O_MH_MAGIC_64\fP   0xfeedfacf"
.br
.ti -1c
.RI "#define \fBMACH_O_MH_MAGIC_FAT\fP   0xcafebabe"
.br
.ti -1c
.RI "#define \fBMACH_O_MH_CIGAM_FAT\fP   0xbebafeca"
.br
.ti -1c
.RI "#define \fBMACH_O_MH_MAGIC_FAT_64\fP   0xcafebabf"
.br
.ti -1c
.RI "#define \fBMACH_O_MH_CIGAM_FAT_64\fP   0xbfbafeca"
.br
.ti -1c
.RI "#define \fBMACH_O_MH_EXECUTE\fP   0x02"
.br
.ti -1c
.RI "#define \fBMACH_O_MH_DYLIB\fP   0x06"
.br
.ti -1c
.RI "#define \fBMACH_O_MH_DSYM\fP   0x0a"
.br
.ti -1c
.RI "#define \fBMACH_O_CPU_ARCH_ABI64\fP   0x01000000"
.br
.ti -1c
.RI "#define \fBMACH_O_CPU_TYPE_X86\fP   7"
.br
.ti -1c
.RI "#define \fBMACH_O_CPU_TYPE_ARM\fP   12"
.br
.ti -1c
.RI "#define \fBMACH_O_CPU_TYPE_PPC\fP   18"
.br
.ti -1c
.RI "#define \fBMACH_O_CPU_TYPE_X86_64\fP   (\fBMACH_O_CPU_TYPE_X86\fP | \fBMACH_O_CPU_ARCH_ABI64\fP)"
.br
.ti -1c
.RI "#define \fBMACH_O_CPU_TYPE_ARM64\fP   (\fBMACH_O_CPU_TYPE_ARM\fP | \fBMACH_O_CPU_ARCH_ABI64\fP)"
.br
.ti -1c
.RI "#define \fBMACH_O_CPU_TYPE_PPC64\fP   (\fBMACH_O_CPU_TYPE_PPC\fP | \fBMACH_O_CPU_ARCH_ABI64\fP)"
.br
.ti -1c
.RI "#define \fBMACH_O_LC_SEGMENT\fP   0x01"
.br
.ti -1c
.RI "#define \fBMACH_O_LC_SYMTAB\fP   0x02"
.br
.ti -1c
.RI "#define \fBMACH_O_LC_SEGMENT_64\fP   0x19"
.br
.ti -1c
.RI "#define \fBMACH_O_LC_UUID\fP   0x1b"
.br
.ti -1c
.RI "#define \fBMACH_O_NAMELEN\fP   (16)"
.br
.ti -1c
.RI "#define \fBMACH_O_UUID_LEN\fP   (16)"
.br
.ti -1c
.RI "#define \fBMACH_O_N_EXT\fP   0x01	/* Extern symbol */"
.br
.ti -1c
.RI "#define \fBMACH_O_N_ABS\fP   0x02	/* Absolute symbol */"
.br
.ti -1c
.RI "#define \fBMACH_O_N_SECT\fP   0x0e	/* Defined in section */"
.br
.ti -1c
.RI "#define \fBMACH_O_N_TYPE\fP   0x0e	/* Mask for \fBtype\fP bits */"
.br
.ti -1c
.RI "#define \fBMACH_O_N_STAB\fP   0xe0	/* Stabs debugging symbol */"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtracy::backtrace_initialize\fP (\fBstruct\fP \fBbacktrace_state\fP *state, const char *filename, int descriptor, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP, \fBfileline\fP *fileline_fn)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MACH_O_CPU_ARCH_ABI64   0x01000000"

.SS "#define MACH_O_CPU_TYPE_ARM   12"

.SS "#define MACH_O_CPU_TYPE_ARM64   (\fBMACH_O_CPU_TYPE_ARM\fP | \fBMACH_O_CPU_ARCH_ABI64\fP)"

.SS "#define MACH_O_CPU_TYPE_PPC   18"

.SS "#define MACH_O_CPU_TYPE_PPC64   (\fBMACH_O_CPU_TYPE_PPC\fP | \fBMACH_O_CPU_ARCH_ABI64\fP)"

.SS "#define MACH_O_CPU_TYPE_X86   7"

.SS "#define MACH_O_CPU_TYPE_X86_64   (\fBMACH_O_CPU_TYPE_X86\fP | \fBMACH_O_CPU_ARCH_ABI64\fP)"

.SS "#define MACH_O_LC_SEGMENT   0x01"

.SS "#define MACH_O_LC_SEGMENT_64   0x19"

.SS "#define MACH_O_LC_SYMTAB   0x02"

.SS "#define MACH_O_LC_UUID   0x1b"

.SS "#define MACH_O_MH_CIGAM_FAT   0xbebafeca"

.SS "#define MACH_O_MH_CIGAM_FAT_64   0xbfbafeca"

.SS "#define MACH_O_MH_DSYM   0x0a"

.SS "#define MACH_O_MH_DYLIB   0x06"

.SS "#define MACH_O_MH_EXECUTE   0x02"

.SS "#define MACH_O_MH_MAGIC_32   0xfeedface"

.SS "#define MACH_O_MH_MAGIC_64   0xfeedfacf"

.SS "#define MACH_O_MH_MAGIC_FAT   0xcafebabe"

.SS "#define MACH_O_MH_MAGIC_FAT_64   0xcafebabf"

.SS "#define MACH_O_N_ABS   0x02	/* Absolute symbol */"

.SS "#define MACH_O_N_EXT   0x01	/* Extern symbol */"

.SS "#define MACH_O_N_SECT   0x0e	/* Defined in section */"

.SS "#define MACH_O_N_STAB   0xe0	/* Stabs debugging symbol */"

.SS "#define MACH_O_N_TYPE   0x0e	/* Mask for \fBtype\fP bits */"

.SS "#define MACH_O_NAMELEN   (16)"

.SS "#define MACH_O_UUID_LEN   (16)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
