.TH "adhed/glm/mat2x4.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/mat2x4.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&./ext/matrix_double2x4\&.hpp'\fP
.br
\fR#include '\&./ext/matrix_double2x4_precision\&.hpp'\fP
.br
\fR#include '\&./ext/matrix_float2x4\&.hpp'\fP
.br
\fR#include '\&./ext/matrix_float2x4_precision\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
\fBCore features\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
