.TH "adhed/assimp/matrix3x3.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/assimp/matrix3x3.h \- Definition of a 3x3 matrix, including operators when compiling in C++\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <assimp/defs\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBaiMatrix3x3\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAI_MATRIX3X3_H_INC\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of a 3x3 matrix, including operators when compiling in C++\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AI_MATRIX3X3_H_INC"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
