.TH "adhed/glm/gtc/matrix_access.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtc/matrix_access.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./detail/setup\&.hpp'\fP
.br
\fR#include 'matrix_access\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType::row_type \fBglm::row\fP (genType const &m, \fBlength_t\fP \fBindex\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::row\fP (genType const &m, \fBlength_t\fP \fBindex\fP, typename genType::row_type const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType::col_type \fBglm::column\fP (genType const &m, \fBlength_t\fP \fBindex\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::column\fP (genType const &m, \fBlength_t\fP \fBindex\fP, typename genType::col_type const &\fBx\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTC_matrix_access\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
