.TH "adhed/glm/gtc/matrix_transform.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtc/matrix_transform.inl
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./geometric\&.hpp'\fP
.br
\fR#include '\&.\&./trigonometric\&.hpp'\fP
.br
\fR#include '\&.\&./matrix\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
