.TH "adhed/glm/gtx/matrix_interpolation.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/matrix_interpolation.inl
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./ext/scalar_constants\&.hpp'\fP
.br
\fR#include <limits>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvoid\fP \fBglm::axisAngle\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > &\fBaxis\fP, \fBT\fP &\fBangle\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::axisAngleMatrix\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBaxis\fP, \fBT\fP const \fBangle\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::extractMatrixRotation\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::interpolate\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m1, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m2, \fBT\fP const delta)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
