.TH "adhed/glm/gtc/matrix_access.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtc/matrix_access.inl
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::row\fP (genType const &m, \fBlength_t\fP \fBindex\fP, typename genType::row_type const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType::row_type \fBglm::row\fP (genType const &m, \fBlength_t\fP \fBindex\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::column\fP (genType const &m, \fBlength_t\fP \fBindex\fP, typename genType::col_type const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType::col_type \fBglm::column\fP (genType const &m, \fBlength_t\fP \fBindex\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
