.TH "adhed/glm/ext/matrix_relational.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/ext/matrix_relational.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./detail/qualifier\&.hpp'\fP
.br
\fR#include 'matrix_relational\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBlength_t\fP C, \fBlength_t\fP R, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBC\fP, bool, \fBQ\fP > \fBglm::equal\fP (\fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP C, \fBlength_t\fP R, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBC\fP, bool, \fBQ\fP > \fBglm::notEqual\fP (\fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP C, \fBlength_t\fP R, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBC\fP, bool, \fBQ\fP > \fBglm::equal\fP (\fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBT\fP \fBepsilon\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP C, \fBlength_t\fP R, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBC\fP, bool, \fBQ\fP > \fBglm::equal\fP (\fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBC\fP, \fBT\fP, \fBQ\fP > const &\fBepsilon\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP C, \fBlength_t\fP R, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBC\fP, bool, \fBQ\fP > \fBglm::notEqual\fP (\fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBT\fP \fBepsilon\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP C, \fBlength_t\fP R, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBC\fP, bool, \fBQ\fP > \fBglm::notEqual\fP (\fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBC\fP, \fBT\fP, \fBQ\fP > const &\fBepsilon\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP C, \fBlength_t\fP R, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBC\fP, bool, \fBQ\fP > \fBglm::equal\fP (\fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, int ULPs)"
.br
.ti -1c
.RI "template<\fBlength_t\fP C, \fBlength_t\fP R, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBC\fP, bool, \fBQ\fP > \fBglm::equal\fP (\fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBC\fP, int, \fBQ\fP > const &ULPs)"
.br
.ti -1c
.RI "template<\fBlength_t\fP C, \fBlength_t\fP R, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBC\fP, bool, \fBQ\fP > \fBglm::notEqual\fP (\fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, int ULPs)"
.br
.ti -1c
.RI "template<\fBlength_t\fP C, \fBlength_t\fP R, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBC\fP, bool, \fBQ\fP > \fBglm::notEqual\fP (\fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBC\fP, int, \fBQ\fP > const &ULPs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_matrix_relational\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
