.TH "adhed/glm/ext/matrix_uint3x4.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/ext/matrix_uint3x4.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./mat3x4\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, \fBuint\fP, \fBdefaultp\fP > \fBglm::umat3x4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_matrix_uint3x4\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
