.TH "adhed/glm/gtx/matrix_decompose.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/matrix_decompose.inl
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./gtc/constants\&.hpp'\fP
.br
\fR#include '\&.\&./gtc/epsilon\&.hpp'\fP
.br
\fR#include '\&.\&./gtx/transform\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.ti -1c
.RI "namespace \fBglm::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::detail::combine\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBa\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBb\fP, \fBT\fP ascl, \fBT\fP bscl)"
.br
.RI "Make a linear combination of two vectors and return the result\&. "
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::detail::scale\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP desiredLength)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP bool \fBglm::decompose\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &ModelMatrix, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > &Scale, \fBqua\fP< \fBT\fP, \fBQ\fP > &Orientation, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > &Translation, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > &Skew, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > &Perspective)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::recompose\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBscale\fP, \fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBorientation\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &translation, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &skew, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBperspective\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
