.TH "adhed/glm/gtc/matrix_transform.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtc/matrix_transform.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./mat4x4\&.hpp'\fP
.br
\fR#include '\&.\&./vec2\&.hpp'\fP
.br
\fR#include '\&.\&./vec3\&.hpp'\fP
.br
\fR#include '\&.\&./vec4\&.hpp'\fP
.br
\fR#include '\&.\&./ext/matrix_projection\&.hpp'\fP
.br
\fR#include '\&.\&./ext/matrix_clip_space\&.hpp'\fP
.br
\fR#include '\&.\&./ext/matrix_transform\&.hpp'\fP
.br
\fR#include 'matrix_transform\&.inl'\fP
.br

.SH "Detailed Description"
.PP 
\fBGLM_GTC_matrix_transform\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTX_transform\fP 
.PP
\fBGLM_GTX_transform2\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
