.TH "adhed/glm/gtx/matrix_interpolation.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/matrix_interpolation.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./glm\&.hpp'\fP
.br
\fR#include 'matrix_interpolation\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP \fBvoid\fP \fBglm::axisAngle\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &Mat, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > &Axis, \fBT\fP &Angle)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::axisAngleMatrix\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &Axis, \fBT\fP const Angle)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::extractMatrixRotation\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &Mat)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::interpolate\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m1, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m2, \fBT\fP const Delta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_matrix_interpolation\fP
.PP
\fBAuthor\fP
.RS 4
Ghenadii Ursachi (the.asteroth@gmail.com)
.RE
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
