.TH "adhed/glm/ext/matrix_projection.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/ext/matrix_projection.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./gtc/constants\&.hpp'\fP
.br
\fR#include '\&.\&./geometric\&.hpp'\fP
.br
\fR#include '\&.\&./trigonometric\&.hpp'\fP
.br
\fR#include '\&.\&./matrix\&.hpp'\fP
.br
\fR#include 'matrix_projection\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::projectZO\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &obj, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &model, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &\fBproj\fP, \fBvec\fP< 4, \fBU\fP, \fBQ\fP > const &viewport)"
.br
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::projectNO\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &obj, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &model, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &\fBproj\fP, \fBvec\fP< 4, \fBU\fP, \fBQ\fP > const &viewport)"
.br
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::project\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &obj, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &model, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &\fBproj\fP, \fBvec\fP< 4, \fBU\fP, \fBQ\fP > const &viewport)"
.br
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::unProjectZO\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &win, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &model, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &\fBproj\fP, \fBvec\fP< 4, \fBU\fP, \fBQ\fP > const &viewport)"
.br
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::unProjectNO\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &win, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &model, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &\fBproj\fP, \fBvec\fP< 4, \fBU\fP, \fBQ\fP > const &viewport)"
.br
.ti -1c
.RI "template<typename \fBT\fP , typename \fBU\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::unProject\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &win, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &model, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &\fBproj\fP, \fBvec\fP< 4, \fBU\fP, \fBQ\fP > const &viewport)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q, typename \fBU\fP > \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::pickMatrix\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &center, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &delta, \fBvec\fP< 4, \fBU\fP, \fBQ\fP > const &viewport)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_matrix_projection\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
