.TH "adhed/glm/gtx/matrix_factorisation.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/matrix_factorisation.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./glm\&.hpp'\fP
.br
\fR#include 'matrix_factorisation\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBlength_t\fP C, \fBlength_t\fP R, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > \fBglm::flipud\fP (\fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &in)"
.br
.ti -1c
.RI "template<\fBlength_t\fP C, \fBlength_t\fP R, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > \fBglm::fliplr\fP (\fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &in)"
.br
.ti -1c
.RI "template<\fBlength_t\fP C, \fBlength_t\fP R, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP \fBvoid\fP \fBglm::qr_decompose\fP (\fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &in, \fBmat\fP<(\fBC\fP< \fBR\fP ? \fBC\fP :\fBR\fP), \fBR\fP, \fBT\fP, \fBQ\fP > &q, \fBmat\fP< \fBC\fP,(\fBC\fP< \fBR\fP ? \fBC\fP :\fBR\fP), \fBT\fP, \fBQ\fP > &\fBr\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP C, \fBlength_t\fP R, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DISCARD_DECL\fP \fBvoid\fP \fBglm::rq_decompose\fP (\fBmat\fP< \fBC\fP, \fBR\fP, \fBT\fP, \fBQ\fP > const &in, \fBmat\fP<(\fBC\fP< \fBR\fP ? \fBC\fP :\fBR\fP), \fBR\fP, \fBT\fP, \fBQ\fP > &\fBr\fP, \fBmat\fP< \fBC\fP,(\fBC\fP< \fBR\fP ? \fBC\fP :\fBR\fP), \fBT\fP, \fBQ\fP > &q)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_matrix_factorisation\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
