.TH "md_packages_2directxtk12__uwp_82024_86_85_81_2docs_2_r_e_a_d_m_e" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_packages_2directxtk12__uwp_82024_86_85_81_2docs_2_r_e_a_d_m_e \- README 
.PP

.SH "DirectX Tool Kit for DirectX 12"
.PP
http://go.microsoft.com/fwlink/?LinkID=615561
.PP
Copyright (c) Microsoft Corporation\&.
.PP
\fBJune 4, 2024\fP
.PP
This package contains the 'DirectX Tool Kit', a collection of helper classes for writing Direct3D 12 C++ code for Universal Windows Platform (UWP) apps for Windows 11 and Windows 10, game titles for Xbox Series X|S and Xbox One, and Win32 desktop applications for Windows 11 and Windows 10\&.
.PP
This code is designed to build with Visual Studio 2019 (16\&.11), Visual Studio 2022, clang for Windows v12 or later, or MinGW 12\&.2\&. Use of the Windows 10 May 2020 Update SDK (\fR19041\fP) or later is required for Visual Studio\&.
.PP
These components are designed to work without requiring any content from the legacy \fBDirectX\fP SDK\&. For details, see \fRWhere is the DirectX SDK?\fP\&.
.SS "Directory Layout"
.IP "\(bu" 2
\fRInc\\\fP
.IP "  \(bu" 4
Public Header Files (in the \fBDirectX\fP C++ namespace):
.IP "    \(bu" 6
Audio\&.h - low-level audio API using XAudio2 (DirectXTK for Audio public header)
.IP "    \(bu" 6
BufferHelpers\&.h - C++ helpers for creating D3D resources from CPU data
.IP "    \(bu" 6
CommonStates\&.h - common D3D state combinations
.IP "    \(bu" 6
DDSTextureLoader\&.h - light-weight DDS file texture loader
.IP "    \(bu" 6
DescriptorHeap\&.h - helper for managing DX12 descriptor heaps
.IP "    \(bu" 6
DirectXHelpers\&.h - misc C++ helpers for D3D programming
.IP "    \(bu" 6
EffectPipelineStateDescription\&.h - helper for creating PSOs
.IP "    \(bu" 6
Effects\&.h - set of built-in shaders for common rendering tasks
.IP "    \(bu" 6
GamePad\&.h - gamepad controller helper using Windows\&.Gaming\&.Input or GameInput
.IP "    \(bu" 6
GeometricPrimitive\&.h - draws basic shapes such as cubes and spheres
.IP "    \(bu" 6
GraphicsMemory\&.h - helper for managing dynamic graphics memory allocation
.IP "    \(bu" 6
Keyboard\&.h - keyboard state tracking helper
.IP "    \(bu" 6
Model\&.h - draws meshes loaded from \&.CMO, \&.SDKMESH, or \&.VBO files
.IP "    \(bu" 6
Mouse\&.h - mouse helper
.IP "    \(bu" 6
PostProcess\&.h - set of built-in shaders for common post-processing operations
.IP "    \(bu" 6
PrimitiveBatch\&.h - simple and efficient way to draw user primitives
.IP "    \(bu" 6
RenderTargetState\&.h - helper for communicating render target requirements when creating PSOs
.IP "    \(bu" 6
ResourceUploadBatch\&.h - helper for managing texture resource upload to the GPU
.IP "    \(bu" 6
ScreenGrab\&.h - light-weight screen shot saver
.IP "    \(bu" 6
SimpleMath\&.h - simplified C++ wrapper for DirectXMath
.IP "    \(bu" 6
SpriteBatch\&.h - simple & efficient 2D sprite rendering
.IP "    \(bu" 6
SpriteFont\&.h - bitmap based text rendering
.IP "    \(bu" 6
VertexTypes\&.h - structures for commonly used vertex data formats
.IP "    \(bu" 6
WICTextureLoader\&.h - WIC-based image file texture loader
.IP "    \(bu" 6
XboxDDSTextureLoader\&.h - Xbox exclusive apps variant of DDSTextureLoader
.PP

.PP

.IP "\(bu" 2
\fRSrc\\\fP
.IP "  \(bu" 4
DirectXTK source files and internal implementation headers
.PP

.IP "\(bu" 2
\fRAudio\\\fP
.IP "  \(bu" 4
DirectXTK for Audio source files and internal implementation headers
.PP

.IP "\(bu" 2
\fRbuild\\\fP
.IP "  \(bu" 4
Contains YAML files for the build pipelines along with some miscellaneous build files and scripts\&.
.PP

.PP
.PP
.RS 4
MakeSpriteFont and XWBTool can be found in the \fRDirectX Tool Kit for DirectX 11\fP 
.RE
.PP
.SS "Documentation"
Documentation is available on the \fRGitHub wiki\fP\&.
.SS "Notices"
All content and source code for this package are subject to the terms of the \fRMIT License\fP\&.
.PP
For the latest version of DirectXTK12, bug reports, etc\&. please visit the project site on \fRGitHub\fP\&.
.SS "Comparisons to DirectX 11 Version"
.IP "\(bu" 2
No support for Visual Studio Directed Graph Shader Language (DGSL) effect shaders (i\&.e\&. \fIDGSLEffect\fP)\&. CMO files are loaded using BasicEffect or SkinnedEffect materials\&.
.IP "\(bu" 2
VertexTypes does not include VertexPositionNormalTangentColorTexture or VertexPositionNormalTangentColorTextureSkinning which were intended for use with the DGSL pipeline\&.
.IP "\(bu" 2
\fBDirectX\fP Tool Kit for \fBDirectX\fP 11 supports Feature Level 9\&.x, while \fBDirectX\fP 12 requires Direct3D Feature Level 11\&.0\&. There are no expected \fBDirectX\fP 12 drivers for any lower feature level devices\&.
.IP "\(bu" 2
The library assumes it is building for Windows 10 (aka \fR_WIN32_WINNT=0x0A00\fP) so it makes use of XAudio 2\&.9 and WIC2 as well as \fBDirectX\fP 12\&.
.IP "\(bu" 2
\fBDirectX\fP Tool Kit for Audio, GamePad, Keyboard, Mouse, and SimpleMath are identical to the \fBDirectX\fP 11 version\&.
.PP
.SS "Release Notes"
FOR SECURITY ADVISORIES, see \fRGitHub\fP\&.
.PP
For a full change history, see \fRCHANGELOG\&.md\fP\&.
.PP
.IP "\(bu" 2
In the June 2024 release, the defaulted parameter \fRinitialState\fP for the \fRCreateUploadBuffer\fP function in \fIBufferHelpers\fP was removed\&. Per the \fBDirectX\fP 12 validation layer, the only valid initial state for an upload buffer is \fRD3D12_RESOURCE_STATE_GENERIC_READ\fP\&.
.IP "\(bu" 2
Starting with the February 2023 release, the Mouse class implementation of relative mouse movement was updated to accumulate changes between calls to \fRGetState\fP\&. By default, each time you call \fRGetState\fP the deltas are reset which works for scenarios where you use relative movement but only call the method once per frame\&. If you call it more than once per frame, then add an explicit call to \fREndOfInputFrame\fP to use an explicit reset model instead\&.
.IP "\(bu" 2
As of the September 2022 release, the library makes use of C++11 inline namespaces for differing types that have the same names in the \fBDirectX\fP 11 and \fBDirectX\fP 12 version of the \fI\fBDirectX\fP Tool Kit\fP\&. This provides a link-unique name such as \fR\fBDirectX::DX12::SpriteBatch\fP\fP that will appear in linker output messages\&. In most use cases, however, there is no need to add explicit \fRDX12\fP namespace resolution in client code\&.
.IP "\(bu" 2
Starting with the June 2021 release, this library builds the HLSL shaders with Shader Model 6 via DXC\&. See \fRthis wiki page\fP for more information\&. The Microsoft GDK projects have always used Shader Model 6\&.
.IP "\(bu" 2
Starting with the June 2020 release, this library makes use of \fRtyped enum bitmask flags\fP per the recommendation of the \fIC++ Standard\fP section \fI17\&.5\&.2\&.1\&.3 Bitmask types\fP\&. This may have \fIbreaking change\fP impacts to client code:
.IP "  \(bu" 4
You cannot pass the \fR0\fP literal as your flags value\&. Instead you must make use of the appropriate default enum value: \fRAudioEngine_Default\fP, \fRSoundEffectInstance_Default\fP, \fRModelLoader_Clockwise\fP, \fRDDS_LOADER_DEFAULT\fP, or \fRWIC_LOADER_DEFAULT\fP\&.
.IP "  \(bu" 4
Use the enum type instead of \fRDWORD\fP if building up flags values locally with bitmask operations\&. For example, \fRWIC_LOADER_FLAGS flags = WIC_LOADER_DEFAULT; if (\&.\&.\&.) flags |= WIC_LOADER_FORCE_SRGB;\fP
.PP

.IP "\(bu" 2
The UWP projects and the Win10 classic desktop project include configurations for the ARM64 platform\&. \fBBuilding\fP these requires installing the ARM64 toolset\&.
.IP "\(bu" 2
When using clang/LLVM for the ARM64 platform, the Windows 11 SDK (\fR22000\fP) or later is required\&.
.IP "\(bu" 2
The \fRCompileShaders\&.cmd\fP script must have Windows-style (CRLF) line-endings\&. If it is changed to Linux-style (LF) line-endings, it can fail to build all the required shaders\&.
.PP
.SS "Support"
For questions, consider using \fRStack Overflow\fP with the \fIdirectxtk\fP tag, or the \fRDirectX Discord Server\fP in the \fIdx12-developers\fP channel\&.
.PP
For bug reports and feature requests, please use GitHub \fRissues\fP for this project\&.
.SS "Contributing"
This project welcomes contributions and suggestions\&. Most contributions require you to agree to a Contributor License Agreement (CLA) declaring that you have the right to, and actually do, grant us the rights to use your contribution\&. For details, visit https://cla.opensource.microsoft.com\&.
.PP
When you submit a pull request, a CLA bot will automatically determine whether you need to provide a CLA and decorate the PR appropriately (e\&.g\&., status check, comment)\&. Simply follow the instructions provided by the bot\&. You will only need to do this once across all repos using our CLA\&.
.PP
Tests for new features should also be submitted as a PR to the \fRTest Suite\fP repository\&.
.SS "Code of Conduct"
This project has adopted the \fRMicrosoft Open Source Code of Conduct\fP\&. For more informatsion see the \fRCode of Conduct FAQ\fP or contact \fRopencode@microsoft\&.com\fP with any additional questions or comments\&.
.SS "Trademarks"
This project may contain trademarks or logos for projects, products, or services\&. Authorized use of Microsoft trademarks or logos is subject to and must follow \fRMicrosoft's Trademark & Brand Guidelines\fP\&. Use of Microsoft trademarks or logos in modified versions of this project must not cause confusion or imply Microsoft sponsorship\&. Any use of third-party trademarks or logos are subject to those third-party's policies\&.
.SS "Credits"
The \fI\fBDirectX\fP Tool Kit for \fBDirectX\fP 11\fP is the work of Shawn Hargreaves and Chuck Walbourn, with contributions from Aaron Rodriguez Hernandez and Dani Roman\&.
.PP
The \fI\fBDirectX\fP Tool Kit for \fBDirectX\fP 12\fP is the work of Pete Lewis, Justin Saunders, and Chuck Walbourn based heavily on the \fBDirectX\fP Tool Kit for \fBDirectX\fP 11\&.
.PP
Thanks to Shanon Drone for the SDKMESH file format\&.
.PP
Thanks to Adrian Tsai for the geodesic sphere implementation\&.
.PP
Thanks to Garrett Serack for his help in creating the NuGet packages for \fBDirectX\fP Tool Kit\&.
.PP
Thanks to Pete Lewis and Justin Saunders for the normal-mapped and PBR shaders implementation\&.
.PP
Thanks for Travis Johnson for the mGPU support\&.
.PP
Thanks to Roberto Sonnino for his help with the CMO format and the VS Starter Kit animation\&.
.PP
Thanks to Richie Meyer for their contribution of Xbox PIX custom memory and type allocation tracking events support\&.
.PP
Thanks to Andrew Farrier and Scott Matloff for their on-going help with code reviews\&. 
