.TH "MESSAGES::Message_Bus" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MESSAGES::Message_Bus
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MMESSAGE_BUS\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBExists\fP = false"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static vector< \fBDATATYPES::Mesage\fP > \fBmessages\fP"
.br
.ti -1c
.RI "static vector< \fBDATATYPES::slow_Message\fP > \fBslow_Messages\fP"
.br
.ti -1c
.RI "static vector< \fBDATATYPES::Urgent_Message\fP > \fBUrgent_Messages\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBMMESSAGE_BUS\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool MESSAGES::Message_Bus::Exists = false"

.PP
Definition at line \fB15\fP of file \fBMMESSAGE_BUS\&.h\fP\&.
.SS "vector<\fBDATATYPES::Mesage\fP> MESSAGES::Message_Bus::messages\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBMMESSAGE_BUS\&.h\fP\&.
.SS "vector<\fBDATATYPES::slow_Message\fP> MESSAGES::Message_Bus::slow_Messages\fR [static]\fP"

.PP
Definition at line \fB17\fP of file \fBMMESSAGE_BUS\&.h\fP\&.
.SS "vector<\fBDATATYPES::Urgent_Message\fP> MESSAGES::Message_Bus::Urgent_Messages\fR [static]\fP"

.PP
Definition at line \fB18\fP of file \fBMMESSAGE_BUS\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
