.TH "UPRISE_ENGINE/MESSAGE_BUS.cpp" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/MESSAGE_BUS.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'pch\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMESSAGES\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
