.TH "adhed/libbacktrace/mmapio.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/libbacktrace/mmapio.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include <errno\&.h>\fP
.br
\fR#include <sys/types\&.h>\fP
.br
\fR#include <sys/mman\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include 'backtrace\&.hpp'\fP
.br
\fR#include 'internal\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAP_FAILED\fP   ((\fBvoid\fP *)\-1)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBgetpagesize\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "int \fBtracy::backtrace_get_view\fP (\fBstruct\fP \fBbacktrace_state\fP *state \fBATTRIBUTE_UNUSED\fP, int descriptor, off_t \fBoffset\fP, uint64_t \fBsize\fP, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP, \fBstruct\fP \fBbacktrace_view\fP *view)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtracy::backtrace_release_view\fP (\fBstruct\fP \fBbacktrace_state\fP *state \fBATTRIBUTE_UNUSED\fP, \fBstruct\fP \fBbacktrace_view\fP *view, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAP_FAILED   ((\fBvoid\fP *)\-1)"

.SH "Function Documentation"
.PP 
.SS "int getpagesize (\fBvoid\fP )\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
