.TH "packages/directxtk12_uwp.2024.6.5.1/include/Model.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/directxtk12_uwp.2024.6.5.1/include/Model.h
.SH SYNOPSIS
.br
.PP
\fR#include <d3d12\&.h>\fP
.br
\fR#include <dxgiformat\&.h>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <iterator>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <new>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <string>\fP
.br
\fR#include <type_traits>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <malloc\&.h>\fP
.br
\fR#include <wrl/client\&.h>\fP
.br
\fR#include <DirectXMath\&.h>\fP
.br
\fR#include <DirectXCollision\&.h>\fP
.br
\fR#include 'GraphicsMemory\&.h'\fP
.br
\fR#include 'Effects\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDirectX::DX12::ModelBone\fP"
.br
.ti -1c
.RI "struct \fBDirectX::DX12::ModelBone::aligned_deleter\fP"
.br
.ti -1c
.RI "class \fBDirectX::DX12::ModelMeshPart\fP"
.br
.ti -1c
.RI "class \fBDirectX::DX12::ModelMesh\fP"
.br
.ti -1c
.RI "class \fBDirectX::DX12::Model\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDirectX\fP"
.br
.ti -1c
.RI "namespace \fBDirectX::DX12\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDirectX::DX12::ModelLoaderFlags\fP : uint32_t { \fBDirectX::DX12::ModelLoader_Default\fP = 0x0, \fBDirectX::DX12::ModelLoader_MaterialColorsSRGB\fP = 0x1, \fBDirectX::DX12::ModelLoader_AllowLargeModels\fP = 0x2, \fBDirectX::DX12::ModelLoader_IncludeBones\fP = 0x4, \fBDirectX::DX12::ModelLoader_DisableSkinning\fP = 0x8, \fBDirectX::DX12::ModelLoader_Default\fP = 0x0, \fBDirectX::DX12::ModelLoader_MaterialColorsSRGB\fP = 0x1, \fBDirectX::DX12::ModelLoader_AllowLargeModels\fP = 0x2, \fBDirectX::DX12::ModelLoader_IncludeBones\fP = 0x4, \fBDirectX::DX12::ModelLoader_DisableSkinning\fP = 0x8 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDirectX::DX12::DEFINE_ENUM_FLAG_OPERATORS\fP (\fBModelLoaderFlags\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
