.TH "BLINK/source/msf_reader.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLINK/source/msf_reader.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <fstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBblink::msf_reader\fP"
.br
.RI "Class which splits a multi-stream file into its content streams\&. "
.ti -1c
.RI "struct \fBblink::msf_reader::content_stream\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBblink\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
