.TH "BLINK/source/msf_reader.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLINK/source/msf_reader.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'msf_reader\&.hpp'\fP
.br
\fR#include <algorithm>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBmsf_file_header\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
