.TH "adhed/glm/gtx/number_precision.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/number_precision.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./glm\&.hpp'\fP
.br
\fR#include '\&.\&./gtc/type_precision\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBf32\fP \fBglm::f32mat1\fP"
.br
.RI "Single-qualifier floating-point scalar\&. (from GLM_GTX_number_precision extension) "
.ti -1c
.RI "typedef \fBf32\fP \fBglm::f32mat1x1\fP"
.br
.RI "Single-qualifier floating-point scalar\&. (from GLM_GTX_number_precision extension) "
.ti -1c
.RI "typedef \fBf64\fP \fBglm::f64mat1\fP"
.br
.RI "Double-qualifier floating-point scalar\&. (from GLM_GTX_number_precision extension) "
.ti -1c
.RI "typedef \fBf64\fP \fBglm::f64mat1x1\fP"
.br
.RI "Double-qualifier floating-point scalar\&. (from GLM_GTX_number_precision extension) "
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_number_precision\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTC_type_precision\fP (dependence) 
.PP
\fBGLM_GTC_quaternion\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
