.TH "adhed/assimp/ObjMaterial.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/assimp/ObjMaterial.h \- Obj-specific material macros\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <assimp/material\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAI_MATKEY_OBJ_ILLUM\fP   '$mat\&.illum', 0, 0"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_OBJ_BUMPMULT\fP(\fBtype\fP,  \fBN\fP)   _AI_MATKEY_OBJ_BUMPMULT_BASE, \fBtype\fP, \fBN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Obj-specific material macros\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AI_MATKEY_OBJ_BUMPMULT( \fBtype\fP,  \fBN\fP)   _AI_MATKEY_OBJ_BUMPMULT_BASE, \fBtype\fP, \fBN\fP"

.SS "#define AI_MATKEY_OBJ_ILLUM   '$mat\&.illum', 0, 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
