.TH "adhed/glm/gtx/orthonormalize.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/orthonormalize.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./vec3\&.hpp'\fP
.br
\fR#include '\&.\&./mat3x3\&.hpp'\fP
.br
\fR#include '\&.\&./geometric\&.hpp'\fP
.br
\fR#include 'orthonormalize\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > \fBglm::orthonormalize\fP (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::orthonormalize\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_orthonormalize\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
gtx_extented_min_max (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
