.TH "adhed/glm/gtx/orthonormalize.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/orthonormalize.inl
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > \fBglm::orthonormalize\fP (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::orthonormalize\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
