.TH "PAIN::ShaderU" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAIN::ShaderU
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RENDER_SHADER_UTILLS\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShaderU\fP (char *vertexPath, char *fragmentPath)"
.br
.ti -1c
.RI "void \fBuse\fP () const"
.br
.ti -1c
.RI "void \fBsetBool\fP (const std::string &name, bool value) const"
.br
.ti -1c
.RI "void \fBsetInt\fP (const std::string &name, int value) const"
.br
.ti -1c
.RI "void \fBsetFloat\fP (const std::string &name, float value) const"
.br
.ti -1c
.RI "void \fBsetVec2\fP (const std::string &name, const glm::vec2 &value) const"
.br
.ti -1c
.RI "void \fBsetVec2\fP (const std::string &name, float x, float y) const"
.br
.ti -1c
.RI "void \fBsetVec3\fP (const std::string &name, const glm::vec3 &value) const"
.br
.ti -1c
.RI "void \fBsetVec3\fP (const std::string &name, float x, float y, float z) const"
.br
.ti -1c
.RI "void \fBsetVec4\fP (const std::string &name, const glm::vec4 &value) const"
.br
.ti -1c
.RI "void \fBsetVec4\fP (const std::string &name, float x, float y, float z, float w) const"
.br
.ti -1c
.RI "void \fBsetMat2\fP (const std::string &name, const glm::mat2 &mat) const"
.br
.ti -1c
.RI "void \fBsetMat3\fP (const std::string &name, const glm::mat3 &mat) const"
.br
.ti -1c
.RI "void \fBsetMat4\fP (const std::string &name, const glm::mat4 &mat) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBID\fP"
.br
.ti -1c
.RI "unsigned short \fBtextcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBRENDER_SHADER_UTILLS\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PAIN::ShaderU::ShaderU (char * vertexPath, char * fragmentPath)"

.PP
Definition at line \fB209\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PAIN::ShaderU::setBool (const std::string & name, bool value) const"

.PP
Definition at line \fB257\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.SS "void PAIN::ShaderU::setFloat (const std::string & name, float value) const"

.PP
Definition at line \fB271\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.SS "void PAIN::ShaderU::setInt (const std::string & name, int value) const"

.PP
Definition at line \fB264\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.SS "void PAIN::ShaderU::setMat2 (const std::string & name, const glm::mat2 & mat) const"

.PP
Definition at line \fB314\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.SS "void PAIN::ShaderU::setMat3 (const std::string & name, const glm::mat3 & mat) const"

.PP
Definition at line \fB321\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.SS "void PAIN::ShaderU::setMat4 (const std::string & name, const glm::mat4 & mat) const"

.PP
Definition at line \fB328\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.SS "void PAIN::ShaderU::setVec2 (const std::string & name, const glm::vec2 & value) const"

.PP
Definition at line \fB278\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.SS "void PAIN::ShaderU::setVec2 (const std::string & name, float x, float y) const"

.PP
Definition at line \fB283\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.SS "void PAIN::ShaderU::setVec3 (const std::string & name, const glm::vec3 & value) const"

.PP
Definition at line \fB290\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.SS "void PAIN::ShaderU::setVec3 (const std::string & name, float x, float y, float z) const"

.PP
Definition at line \fB295\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.SS "void PAIN::ShaderU::setVec4 (const std::string & name, const glm::vec4 & value) const"

.PP
Definition at line \fB302\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.SS "void PAIN::ShaderU::setVec4 (const std::string & name, float x, float y, float z, float w) const"

.PP
Definition at line \fB307\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.SS "void PAIN::ShaderU::use () const"

.PP
Definition at line \fB249\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int PAIN::ShaderU::ID"

.PP
Definition at line \fB21\fP of file \fBRENDER_SHADER_UTILLS\&.h\fP\&.
.SS "unsigned short PAIN::ShaderU::textcount"

.PP
Definition at line \fB22\fP of file \fBRENDER_SHADER_UTILLS\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
