.TH "PAIN::Render" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAIN::Render
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RENDER_MATERIAL\&.h>\fP
.PP
Inherited by \fBPAIN::Material\fP, and \fBPAIN::TerrainModel\fP\fR [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBDrawObj\fP ()=0"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBDrawAll\fP ()"
.br
.ti -1c
.RI "static void \fBInit\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::shared_ptr< \fBGameObject\fP > > \fBobjects\fP"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBCORE::Object\fP > > \fBptrobjects\fP"
.br
.ti -1c
.RI "std::vector< void * > \fBvoidobjects\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static std::unordered_map< std::string, std::shared_ptr< \fBPAIN::Model\fP > > \fBModeldict\fP"
.br
.ti -1c
.RI "static std::vector< \fBPAIN::Material\fP > \fBmats\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBPAIN::TerrainModel\fP > > \fBterrains\fP"
.br
.ti -1c
.RI "static \fBPAIN::Render_Camera\fP * \fBRenderCam\fP"
.br
.ti -1c
.RI "static std::shared_ptr< \fBCORE::Behaviour\fP > \fBCAM\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PAIN::Render::DrawAll ()\fR [static]\fP"

.PP
Definition at line \fB47\fP of file \fBRENDER_MATERIAL\&.cpp\fP\&.
.SS "virtual void PAIN::Render::DrawObj ()\fR [pure virtual]\fP"

.PP
Implemented in \fBPAIN::Material\fP, and \fBPAIN::TerrainModel\fP\&.
.SS "void PAIN::Render::Init ()\fR [static]\fP"

.PP
Definition at line \fB60\fP of file \fBRENDER_MATERIAL\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::shared_ptr< \fBCORE::Behaviour\fP > PAIN::Render::CAM\fR [static]\fP"

.PP
Definition at line \fB23\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SS "std::vector< \fBPAIN::Material\fP > PAIN::Render::mats\fR [static]\fP"

.PP
Definition at line \fB17\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SS "std::unordered_map< std::string, std::shared_ptr< \fBPAIN::Model\fP > > PAIN::Render::Modeldict\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SS "std::vector< std::shared_ptr<\fBGameObject\fP> > PAIN::Render::objects"

.PP
Definition at line \fB19\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SS "std::vector< std::shared_ptr<\fBCORE::Object\fP> > PAIN::Render::ptrobjects"

.PP
Definition at line \fB20\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SS "\fBPAIN::Render_Camera\fP * PAIN::Render::RenderCam\fR [static]\fP"

.PP
Definition at line \fB22\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SS "std::vector< std::shared_ptr< \fBPAIN::TerrainModel\fP > > PAIN::Render::terrains\fR [static]\fP"

.PP
Definition at line \fB18\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SS "std::vector< void* > PAIN::Render::voidobjects"

.PP
Definition at line \fB21\fP of file \fBRENDER_MATERIAL\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
