.TH "PAIN::Model" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAIN::Model
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RENDER_DATATYPES\&.h>\fP
.PP
Inherited by \fBPAIN::TerrainModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModel\fP ()"
.br
.ti -1c
.RI "\fBModel\fP (std::string path)"
.br
.ti -1c
.RI "void \fBDraw\fP (\fBShader\fP &\fBshader\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< \fBMesh\fP > \fBmeshes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB79\fP of file \fBRENDER_DATATYPES\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PAIN::Model::Model ()"

.PP
Definition at line \fB103\fP of file \fBRENDER_DATATYPES\&.cpp\fP\&.
.SS "PAIN::Model::Model (std::string path)"

.PP
Definition at line \fB105\fP of file \fBRENDER_DATATYPES\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PAIN::Model::Draw (\fBShader\fP & shader)"

.PP
Definition at line \fB111\fP of file \fBRENDER_DATATYPES\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "vector<\fBMesh\fP> PAIN::Model::meshes"

.PP
Definition at line \fB85\fP of file \fBRENDER_DATATYPES\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
