.TH "PAIN::Render_Camera" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAIN::Render_Camera
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RENDER_CAMERA\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRender_Camera\fP ()"
.br
.ti -1c
.RI "glm::mat4 \fBGetViewMatrix\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRender_Camera\fP \fBCreate\fP (std::shared_ptr< \fBTransform\fP > tr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBFOV\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBTransform\fP > \fBtransf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBRENDER_CAMERA\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PAIN::Render_Camera::Render_Camera ()"

.PP
Definition at line \fB4\fP of file \fBRENDER_CAMERA\&.cpp\fP\&.
.nf
4 {}
.PP
.fi

.SH "Member Function Documentation"
.PP 
.SS "\fBPAIN::Render_Camera\fP PAIN::Render_Camera::Create (std::shared_ptr< \fBTransform\fP > tr)\fR [static]\fP"

.PP
Definition at line \fB6\fP of file \fBRENDER_CAMERA\&.cpp\fP\&.
.nf
7  {
8     TrPr(ctx, __func__)
9      auto cam = Render_Camera();
10      cam\&.FOV = 45;
11      
12      cam\&.transf = tr;
13      TrPrE(ctx);
14      return cam;
15  }
.PP
.fi

.PP
References \fBTrPr\fP, and \fBTrPrE\fP\&.
.SS "glm::mat4 PAIN::Render_Camera::GetViewMatrix ()"

.PP
Definition at line \fB17\fP of file \fBRENDER_CAMERA\&.cpp\fP\&.
.nf
18  {
19     TrPr(ctx, __func__)
20         TrPrE(ctx);
21      return glm::lookAt((glm::vec3)transf\->Position, (glm::vec3)(transf\->Position + transf\->forward), (glm::vec3)transf\->up);
22      
23  }
.PP
.fi

.PP
References \fBTrPr\fP, and \fBTrPrE\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float PAIN::Render_Camera::FOV"

.PP
Definition at line \fB17\fP of file \fBRENDER_CAMERA\&.h\fP\&.
.SS "std::shared_ptr<\fBTransform\fP> PAIN::Render_Camera::transf"

.PP
Definition at line \fB20\fP of file \fBRENDER_CAMERA\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
