.TH "PAIN::TerrainModel" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAIN::TerrainModel
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RENDER_MATERIAL\&.h>\fP
.PP
Inherits \fBPAIN::Model\fP, and \fBPAIN::Render\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTerrainModel\fP ()"
.br
.ti -1c
.RI "\fBTerrainModel\fP (void *data, int width, int depth, float maxHeight, \fBShader\fP *shade)"
.br
.ti -1c
.RI "void \fBDrawObj\fP () override"
.br
.ti -1c
.RI "\fBMesh\fP \fBgenerateTerrainMesh\fP (int width, int depth, float maxHeight)"
.br
.in -1c

Public Member Functions inherited from \fBPAIN::Model\fP
.in +1c
.ti -1c
.RI "\fBModel\fP ()"
.br
.ti -1c
.RI "\fBModel\fP (std::string path)"
.br
.ti -1c
.RI "void \fBDraw\fP (\fBShader\fP &\fBshader\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBTerraindata\fP"
.br
.ti -1c
.RI "\fBShader\fP * \fBshader\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBGameObject\fP > \fBobject\fP"
.br
.in -1c

Public Attributes inherited from \fBPAIN::Model\fP
.in +1c
.ti -1c
.RI "vector< \fBMesh\fP > \fBmeshes\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBPAIN::Model\fP
.in +1c
.ti -1c
.RI "static std::shared_ptr< \fBModel\fP > \fBEmpty\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB65\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PAIN::TerrainModel::TerrainModel ()"

.PP
Definition at line \fB87\fP of file \fBRENDER_MATERIAL\&.cpp\fP\&.
.nf
88   {
89   }
.PP
.fi

.SS "PAIN::TerrainModel::TerrainModel (void * data, int width, int depth, float maxHeight, \fBShader\fP * shade)"

.PP
Definition at line \fB91\fP of file \fBRENDER_MATERIAL\&.cpp\fP\&.
.nf
92   {
93       shader = shade;
94       Terraindata = data;
95       
96       meshes\&.push_back(generateTerrainMesh(width, depth, maxHeight));
97   }
.PP
.fi

.PP
References \fBshader\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PAIN::TerrainModel::DrawObj ()\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBPAIN::Render\fP\&.
.PP
Definition at line \fB99\fP of file \fBRENDER_MATERIAL\&.cpp\fP\&.
.nf
100   {
101       auto poss = std::dynamic_pointer_cast<Transform>(object\->behaviours[1]);
102 
103       glm::mat4 projection = glm::perspective(glm::radians(std::dynamic_pointer_cast<Camera>(CAM)\&.get()\->camera\&.FOV), (float)1600 / (float)900, 0\&.1f, 500\&.0f);
104       glm::mat4 view = std::dynamic_pointer_cast<Camera>(CAM)\&.get()\->camera\&.GetViewMatrix();
105       glm::mat4 rotation = poss\&.get()\->rotation\&.ToMat4();
106       glm::mat4 model = glm::mat4(1\&.0f);
107       model = glm::translate(model, (glm::vec3)poss\&.get()\->Position);
108       shader\->setMat4("projection", projection);
109       shader\->setMat4("view", view);
110       shader\->setMat4("model", model);
111       shader\->setMat4("Rotation", rotation);
112       std::dynamic_pointer_cast<Terrain_Data>(object\&.get()\->behaviours[0])\&.get()\->model\&.Draw(*shader);
113 
114 
115   }
.PP
.fi

.PP
References \fBPAIN::Shader::setMat4()\fP, and \fBshader\fP\&.
.SS "\fBPAIN::Mesh\fP PAIN::TerrainModel::generateTerrainMesh (int width, int depth, float maxHeight)"

.PP
Definition at line \fB117\fP of file \fBRENDER_MATERIAL\&.cpp\fP\&.
.nf
118   {
119       auto data = (Terrain_Data*)Terraindata;
120       std::vector<Vertex> vertices;
121       std::vector<unsigned int> indices;
122       Vertex vertex;
123       for (int z = 0; z < depth; z++) {
124 
125           for (int x = 0; x < width; x++) {
126               vertex\&.Position = DATATYPES::TS_P_Vector3(x, data\->GetHeight(x, z), z);
127               vertex\&.Normal = DATATYPES::TS_P_Vector3(0, 1, 0);
128               vertex\&.TexCoords = glm::vec2((float)x / data\->width, (float)z / data\->depth);
129               vertices\&.push_back(vertex);
130           }
131 
132       }
133       for (int z = 0; z < data\->depth \- 1; ++z) {
134           for (int x = 0; x < data\->width \- 1; ++x) {
135               int topLeft = z * data\->width + x;
136               int topRight = topLeft + 1;
137               int bottomLeft = (z + 1) * data\->width + x;
138               int bottomRight = bottomLeft + 1;
139 
140               indices\&.push_back(topLeft);
141               indices\&.push_back(bottomLeft);
142               indices\&.push_back(topRight);
143 
144               indices\&.push_back(topRight);
145               indices\&.push_back(bottomLeft);
146               indices\&.push_back(bottomRight);
147           }
148       }
149       return Mesh(vertices, indices, std::vector<Texture>());
150   }
.PP
.fi

.PP
References \fBPAIN::Vertex::Normal\fP, \fBPAIN::Vertex::Position\fP, and \fBPAIN::Vertex::TexCoords\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::shared_ptr<\fBGameObject\fP> PAIN::TerrainModel::object"

.PP
Definition at line \fB71\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SS "\fBShader\fP* PAIN::TerrainModel::shader"

.PP
Definition at line \fB70\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SS "void* PAIN::TerrainModel::Terraindata"

.PP
Definition at line \fB67\fP of file \fBRENDER_MATERIAL\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
