.TH "PAIN::Mesh" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAIN::Mesh
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RENDER_DATATYPES\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMesh\fP (vector< \fBVertex\fP > \fBvertices\fP, vector< unsigned int > \fBindices\fP, vector< \fBTexture\fP > \fBtextures\fP)"
.br
.ti -1c
.RI "void \fBDraw\fP (\fBShader\fP &\fBshader\fP)"
.br
.ti -1c
.RI "void \fBDraw\fP (\fBShaderU\fP &\fBshader\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< \fBVertex\fP > \fBvertices\fP"
.br
.ti -1c
.RI "vector< unsigned int > \fBindices\fP"
.br
.ti -1c
.RI "vector< \fBTexture\fP > \fBtextures\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB63\fP of file \fBRENDER_DATATYPES\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PAIN::Mesh::Mesh (vector< \fBVertex\fP > vertices, vector< unsigned int > indices, vector< \fBTexture\fP > textures)"

.PP
Definition at line \fB11\fP of file \fBRENDER_DATATYPES\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PAIN::Mesh::Draw (\fBShader\fP & shader)"

.PP
Definition at line \fB19\fP of file \fBRENDER_DATATYPES\&.cpp\fP\&.
.SS "void PAIN::Mesh::Draw (\fBShaderU\fP & shader)"

.PP
Definition at line \fB44\fP of file \fBRENDER_DATATYPES\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "vector<unsigned int> PAIN::Mesh::indices"

.PP
Definition at line \fB67\fP of file \fBRENDER_DATATYPES\&.h\fP\&.
.SS "vector<\fBTexture\fP> PAIN::Mesh::textures"

.PP
Definition at line \fB68\fP of file \fBRENDER_DATATYPES\&.h\fP\&.
.SS "vector<\fBVertex\fP> PAIN::Mesh::vertices"

.PP
Definition at line \fB66\fP of file \fBRENDER_DATATYPES\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
