.TH "PAIN::Render_Camera" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAIN::Render_Camera
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RENDER_CAMERA\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetTransf\fP (std::shared_ptr< \fBCORE::Behaviour\fP > \fBtransform\fP)"
.br
.ti -1c
.RI "\fBTransform\fP * \fBGetTransf\fP ()"
.br
.ti -1c
.RI "\fBRender_Camera\fP ()"
.br
.ti -1c
.RI "glm::mat4 \fBGetViewMatrix\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRender_Camera\fP \fBCreate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBFOV\fP"
.br
.ti -1c
.RI "\fBTransform\fP * \fBtransform\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBRENDER_CAMERA\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PAIN::Render_Camera::Render_Camera ()"

.PP
Definition at line \fB3\fP of file \fBRENDER_CAMERA\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPAIN::Render_Camera\fP PAIN::Render_Camera::Create ()\fR [static]\fP"

.PP
Definition at line \fB5\fP of file \fBRENDER_CAMERA\&.cpp\fP\&.
.SS "\fBTransform\fP * PAIN::Render_Camera::GetTransf ()\fR [inline]\fP"

.PP
Definition at line \fB22\fP of file \fBRENDER_CAMERA\&.h\fP\&.
.SS "glm::mat4 PAIN::Render_Camera::GetViewMatrix ()"

.PP
Definition at line \fB12\fP of file \fBRENDER_CAMERA\&.cpp\fP\&.
.SS "void PAIN::Render_Camera::setTransf (std::shared_ptr< \fBCORE::Behaviour\fP > transform)\fR [inline]\fP"

.PP
Definition at line \fB19\fP of file \fBRENDER_CAMERA\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float PAIN::Render_Camera::FOV"

.PP
Definition at line \fB18\fP of file \fBRENDER_CAMERA\&.h\fP\&.
.SS "\fBTransform\fP* PAIN::Render_Camera::transform"

.PP
Definition at line \fB27\fP of file \fBRENDER_CAMERA\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
