.TH "PAIN::Material" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAIN::Material
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RENDER_MATERIAL\&.h>\fP
.PP
Inherits \fBPAIN::Render\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaterial\fP (\fBShader\fP *shade)"
.br
.ti -1c
.RI "\fBMaterial\fP (\fBShader\fP shade)"
.br
.ti -1c
.RI "void \fBDrawObj\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBPAIN::Render\fP
.in +1c
.ti -1c
.RI "\fBVEC\fP (std::shared_ptr< \fBMiniModel\fP >) Object_ModelSubstitute"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBID\fP"
.br
.ti -1c
.RI "\fBShader\fP * \fBshader\fP"
.br
.ti -1c
.RI "\fBShader\fP \fBShader_\fP"
.br
.in -1c

Public Attributes inherited from \fBPAIN::Render\fP
.in +1c
.ti -1c
.RI "std::vector< std::shared_ptr< \fBGameObject\fP > > \fBobjects\fP"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBCORE::Object\fP > > \fBptrobjects\fP"
.br
.ti -1c
.RI "std::vector< void * > \fBvoidobjects\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBPAIN::Render\fP
.in +1c
.ti -1c
.RI "static void \fBDrawAll\fP ()"
.br
.ti -1c
.RI "static void \fBInit\fP ()"
.br
.in -1c

Static Public Attributes inherited from \fBPAIN::Render\fP
.in +1c
.ti -1c
.RI "static unsigned int \fBFBO\fP"
.br
.ti -1c
.RI "static std::unordered_map< std::string, int > \fBMaterialIdLinkDict\fP"
.br
.ti -1c
.RI "static std::unordered_map< std::string, std::shared_ptr< \fBPAIN::Model\fP > > \fBModeldict\fP"
.br
.ti -1c
.RI "static std::vector< \fBPAIN::Material\fP > \fBmats\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBPAIN::TerrainModel\fP > > \fBterrains\fP"
.br
.ti -1c
.RI "static \fBPAIN::Render_Camera\fP * \fBRenderCam\fP"
.br
.ti -1c
.RI "static std::shared_ptr< \fBCamera\fP > \fBCAM\fP"
.br
.ti -1c
.RI "static bool \fBCheck_Removed\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB56\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Material::Material (\fBShader\fP * shade)"

.PP
Definition at line \fB7\fP of file \fBRENDER_MATERIAL\&.cpp\fP\&.
.nf
7 { shader = shade; }
.PP
.fi

.PP
References \fBshader\fP\&.
.SS "Material::Material (\fBShader\fP shade)"

.PP
Definition at line \fB8\fP of file \fBRENDER_MATERIAL\&.cpp\fP\&.
.nf
9  {
10      Shader_ = shade;
11  }
.PP
.fi

.SH "Member Function Documentation"
.PP 
.SS "void Material::DrawObj ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBPAIN::Render\fP\&.
.PP
Definition at line \fB20\fP of file \fBRENDER_MATERIAL\&.cpp\fP\&.
.nf
20                                   {
21     //glBindFramebuffer(GL_FRAMEBUFFER, PAIN::Render::FBO);
22 
23     shader\->use();
24     int i = Object_ModelSubstitute\&.size() \- 1;
25     for (; i >= 0; i\-\-) {
26 
27         if (*Object_ModelSubstitute[i]\->_enabled >= 1) {
28 
29 
30             //auto poss = std::dynamic_pointer_cast<Transform>(objects[i]\->behaviours[1]);
31 
32             
33             glm::mat4 projection = glm::perspective(glm::radians(CAM\->camera\&.FOV), (float)1600 / (float)900, 0\&.1f, 500\&.0f);
34             //auto rott = poss\&.get();
35             //auto rot = rott\->rotation;
36             glm::mat4 view = CAM\->camera\&.GetViewMatrix();
37             glm::mat4 rotation = Object_ModelSubstitute[i]\->_Transform\->rotation\&.ToMat4();
38             glm::mat4 model = glm::mat4(1\&.0f);
39             //DATATYPES::TS_P_Vector3 pos = std::dynamic_pointer_cast<Transform>(objects[i]\&.get()\->behaviours[1])\&.get()\->Position;
40             //auto ooo = objects[i]\->TrAnSfOrM\->Position;
41             //pos = ooo\->Position;
42             model = glm::translate(model, glm::vec3(Object_ModelSubstitute[i]\->_Transform\->Position));
43             shader\->setMat4("projection", projection);
44             shader\->setMat4("view", view);
45             shader\->setMat4("model", model);
46             shader\->setMat4("Rotation", rotation);
47 
48             //auto aa = std::dynamic_pointer_cast<COMPONENTS::_Mesh>(objects[i]\->MesH);
49             //objects[i]\->MESH\->Model\->Draw(*shader);
50             Object_ModelSubstitute[i]\->_Model\->Draw(*shader);
51             //aa\&.get()\->Model\&.get()\->Draw(*shader);
52             //auto meesh = (COMPONENTS::_Mesh*)objects[i]\->msh;
53             //meesh\->Model\&.Draw(*shader);
54             //objects[i]\->MesH\&.Model\&.Draw(*shader);
55         }
56         //else {
57         //  //if //(*Object_ModelSubstitute[i]\->_removed == true) {
58         //  //  Object_ModelSubstitute[i]\->~MiniModel();
59         //      Object_ModelSubstitute[i]\&.reset();
60         //      Object_ModelSubstitute[i] = NULL;
61         //      Object_ModelSubstitute\&.erase(Object_ModelSubstitute\&.begin() + i);
62         //  }
63         //}
64     }
65     //glBindFramebuffer(GL_FRAMEBUFFER, 0);
66 
67 }
.PP
.fi

.PP
References \fBi\fP, \fBPAIN::Shader::setMat4()\fP, \fBshader\fP, and \fBPAIN::Shader::use()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int PAIN::Material::ID"

.PP
Definition at line \fB58\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.PP
Referenced by \fBbb()\fP, \fBCreateMaterial()\fP, and \fBprocessInput()\fP\&.
.SS "\fBShader\fP* PAIN::Material::shader"

.PP
Definition at line \fB59\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.PP
Referenced by \fBMaterial()\fP\&.
.SS "\fBShader\fP PAIN::Material::Shader_"

.PP
Definition at line \fB60\fP of file \fBRENDER_MATERIAL\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
