.TH "PAIN::ModelU" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAIN::ModelU
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RENDER_DATATYPES\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModelU\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB53\fP of file \fBRENDER_DATATYPES\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PAIN::ModelU::ModelU ()"

.PP
Definition at line \fB320\fP of file \fBRENDER_DATATYPES\&.cpp\fP\&.
.nf
320 {}
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
