.TH "PAIN::ShaderU" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAIN::ShaderU
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RENDER_SHADER_UTILLS\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShaderU\fP (char *vertexPath, char *fragmentPath)"
.br
.ti -1c
.RI "void \fBuse\fP () const"
.br
.ti -1c
.RI "void \fBsetBool\fP (const std::string &name, bool value) const"
.br
.ti -1c
.RI "void \fBsetInt\fP (const std::string &name, int value) const"
.br
.ti -1c
.RI "void \fBsetFloat\fP (const std::string &name, float value) const"
.br
.ti -1c
.RI "void \fBsetVec2\fP (const std::string &name, const glm::vec2 &value) const"
.br
.ti -1c
.RI "void \fBsetVec2\fP (const std::string &name, float x, float y) const"
.br
.ti -1c
.RI "void \fBsetVec3\fP (const std::string &name, const glm::vec3 &value) const"
.br
.ti -1c
.RI "void \fBsetVec3\fP (const std::string &name, float x, float y, float z) const"
.br
.ti -1c
.RI "void \fBsetVec4\fP (const std::string &name, const glm::vec4 &value) const"
.br
.ti -1c
.RI "void \fBsetVec4\fP (const std::string &name, float x, float y, float z, float w) const"
.br
.ti -1c
.RI "void \fBsetMat2\fP (const std::string &name, const glm::mat2 &mat) const"
.br
.ti -1c
.RI "void \fBsetMat3\fP (const std::string &name, const glm::mat3 &mat) const"
.br
.ti -1c
.RI "void \fBsetMat4\fP (const std::string &name, const glm::mat4 &mat) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBID\fP"
.br
.ti -1c
.RI "unsigned short \fBtextcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBRENDER_SHADER_UTILLS\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PAIN::ShaderU::ShaderU (char * vertexPath, char * fragmentPath)"

.PP
Definition at line \fB270\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.nf
270                                                           {
271         std::string vertexCode;
272         std::string fragmentCode;
273         std::ifstream vShaderFile;
274         std::ifstream fShaderFile;
275         vShaderFile\&.open(vertexPath);
276         fShaderFile\&.open(fragmentPath);
277         std::stringstream vShaderStream, fShaderStream;
278 
279         if (vShaderFile\&.good() && fShaderFile\&.good()) {
280             vShaderStream << vShaderFile\&.rdbuf();
281             fShaderStream << fShaderFile\&.rdbuf();
282             vShaderFile\&.close();
283             fShaderFile\&.close();
284             vertexCode = vShaderStream\&.str();
285             fragmentCode = fShaderStream\&.str();
286             const char* vShaderCode = vertexCode\&.c_str();
287             const char* fShaderCode = fragmentCode\&.c_str();
288             textcount = fShaderCode[2];
289             unsigned int vertex, fragment;
290             vertex = glCreateShader(GL_VERTEX_SHADER);
291             glShaderSource(vertex, 1, &vShaderCode, NULL);
292             glCompileShader(vertex);
293             checkCompileErrors(vertex, "VERTEX");
294             fragment = glCreateShader(GL_FRAGMENT_SHADER);
295             glShaderSource(fragment, 1, &fShaderCode, NULL);
296             glCompileShader(fragment);
297             checkCompileErrors(fragment, "FRAGMENT");
298             ID = glCreateProgram();
299             glAttachShader(ID, vertex);
300             glAttachShader(ID, fragment);
301             glLinkProgram(ID);
302             checkCompileErrors(ID, "PROGRAM");
303             glDeleteShader(vertex);
304             glDeleteShader(fragment);
305 
306         }
307 
308     }
.PP
.fi

.PP
References \fBID\fP, and \fBtextcount\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PAIN::ShaderU::setBool (const std::string & name, bool value) const"

.PP
Definition at line \fB318\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.nf
319     {
320         glUniform1i(glGetUniformLocation(ID, name\&.c_str()), (int)value);
321     }
.PP
.fi

.PP
References \fBID\fP\&.
.SS "void PAIN::ShaderU::setFloat (const std::string & name, float value) const"

.PP
Definition at line \fB332\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.nf
333     {
334         glUniform1f(glGetUniformLocation(ID, name\&.c_str()), value);
335     }
.PP
.fi

.PP
References \fBID\fP\&.
.SS "void PAIN::ShaderU::setInt (const std::string & name, int value) const"

.PP
Definition at line \fB325\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.nf
326     {
327         glUniform1i(glGetUniformLocation(ID, name\&.c_str()), value);
328     }
.PP
.fi

.PP
References \fBID\fP\&.
.SS "void PAIN::ShaderU::setMat2 (const std::string & name, const glm::mat2 & mat) const"

.PP
Definition at line \fB375\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.nf
376     {
377         glUniformMatrix2fv(glGetUniformLocation(ID, name\&.c_str()), 1, GL_FALSE, &mat[0][0]);
378     }
.PP
.fi

.PP
References \fBID\fP\&.
.SS "void PAIN::ShaderU::setMat3 (const std::string & name, const glm::mat3 & mat) const"

.PP
Definition at line \fB382\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.nf
383     {
384         glUniformMatrix3fv(glGetUniformLocation(ID, name\&.c_str()), 1, GL_FALSE, &mat[0][0]);
385     }
.PP
.fi

.PP
References \fBID\fP\&.
.SS "void PAIN::ShaderU::setMat4 (const std::string & name, const glm::mat4 & mat) const"

.PP
Definition at line \fB389\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.nf
390     {
391         glUniformMatrix4fv(glGetUniformLocation(ID, name\&.c_str()), 1, GL_FALSE, &mat[0][0]);
392     }
.PP
.fi

.PP
References \fBID\fP\&.
.SS "void PAIN::ShaderU::setVec2 (const std::string & name, const glm::vec2 & value) const"

.PP
Definition at line \fB339\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.nf
340     {
341         glUniform2fv(glGetUniformLocation(ID, name\&.c_str()), 1, &value[0]);
342     }
.PP
.fi

.PP
References \fBID\fP\&.
.SS "void PAIN::ShaderU::setVec2 (const std::string & name, float x, float y) const"

.PP
Definition at line \fB344\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.nf
345     {
346         glUniform2f(glGetUniformLocation(ID, name\&.c_str()), x, y);
347     }
.PP
.fi

.PP
References \fBID\fP\&.
.SS "void PAIN::ShaderU::setVec3 (const std::string & name, const glm::vec3 & value) const"

.PP
Definition at line \fB351\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.nf
352     {
353         glUniform3fv(glGetUniformLocation(ID, name\&.c_str()), 1, &value[0]);
354     }
.PP
.fi

.PP
References \fBID\fP\&.
.SS "void PAIN::ShaderU::setVec3 (const std::string & name, float x, float y, float z) const"

.PP
Definition at line \fB356\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.nf
357     {
358         glUniform3f(glGetUniformLocation(ID, name\&.c_str()), x, y, z);
359     }
.PP
.fi

.PP
References \fBID\fP\&.
.SS "void PAIN::ShaderU::setVec4 (const std::string & name, const glm::vec4 & value) const"

.PP
Definition at line \fB363\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.nf
364     {
365         glUniform4fv(glGetUniformLocation(ID, name\&.c_str()), 1, &value[0]);
366     }
.PP
.fi

.PP
References \fBID\fP\&.
.SS "void PAIN::ShaderU::setVec4 (const std::string & name, float x, float y, float z, float w) const"

.PP
Definition at line \fB368\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.nf
369     {
370         glUniform4f(glGetUniformLocation(ID, name\&.c_str()), x, y, z, w);
371     }
.PP
.fi

.PP
References \fBID\fP\&.
.SS "void PAIN::ShaderU::use () const"

.PP
Definition at line \fB310\fP of file \fBRENDER_SHADER_UTILLS\&.cpp\fP\&.
.nf
311     {
312         glUseProgram(ID);
313     }
.PP
.fi

.PP
References \fBID\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int PAIN::ShaderU::ID"

.PP
Definition at line \fB22\fP of file \fBRENDER_SHADER_UTILLS\&.h\fP\&.
.PP
Referenced by \fBsetBool()\fP, \fBsetFloat()\fP, \fBsetInt()\fP, \fBsetMat2()\fP, \fBsetMat3()\fP, \fBsetMat4()\fP, \fBsetVec2()\fP, \fBsetVec2()\fP, \fBsetVec3()\fP, \fBsetVec3()\fP, \fBsetVec4()\fP, \fBsetVec4()\fP, \fBShaderU()\fP, and \fBuse()\fP\&.
.SS "unsigned short PAIN::ShaderU::textcount"

.PP
Definition at line \fB23\fP of file \fBRENDER_SHADER_UTILLS\&.h\fP\&.
.PP
Referenced by \fBShaderU()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
