.TH "PAIN::Material" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAIN::Material
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RENDER_MATERIAL\&.h>\fP
.PP
Inherits \fBPAIN::Render\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaterial\fP (\fBShader\fP *shade)"
.br
.ti -1c
.RI "void \fBDrawObj\fP () override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBID\fP"
.br
.ti -1c
.RI "\fBShader\fP * \fBshader\fP"
.br
.in -1c

Public Attributes inherited from \fBPAIN::Render\fP
.in +1c
.ti -1c
.RI "std::vector< std::shared_ptr< \fBGameObject\fP > > \fBobjects\fP"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBCORE::Object\fP > > \fBptrobjects\fP"
.br
.ti -1c
.RI "std::vector< void * > \fBvoidobjects\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBPAIN::Render\fP
.in +1c
.ti -1c
.RI "static void \fBDrawAll\fP ()"
.br
.ti -1c
.RI "static void \fBInit\fP ()"
.br
.in -1c

Static Public Attributes inherited from \fBPAIN::Render\fP
.in +1c
.ti -1c
.RI "static std::unordered_map< std::string, std::shared_ptr< \fBPAIN::Model\fP > > \fBModeldict\fP"
.br
.ti -1c
.RI "static std::vector< \fBPAIN::Material\fP > \fBmats\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBPAIN::TerrainModel\fP > > \fBterrains\fP"
.br
.ti -1c
.RI "static \fBPAIN::Render_Camera\fP * \fBRenderCam\fP"
.br
.ti -1c
.RI "static std::shared_ptr< \fBCORE::Behaviour\fP > \fBCAM\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB31\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PAIN::Material::Material (\fBShader\fP * shade)"

.PP
Definition at line \fB5\fP of file \fBRENDER_MATERIAL\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PAIN::Material::DrawObj ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBPAIN::Render\fP\&.
.PP
Definition at line \fB12\fP of file \fBRENDER_MATERIAL\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int PAIN::Material::ID"

.PP
Definition at line \fB33\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SS "\fBShader\fP* PAIN::Material::shader"

.PP
Definition at line \fB34\fP of file \fBRENDER_MATERIAL\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
