.TH "PAIN::TerrainModel" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAIN::TerrainModel
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RENDER_MATERIAL\&.h>\fP
.PP
Inherits \fBPAIN::Model\fP, and \fBPAIN::Render\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTerrainModel\fP ()"
.br
.ti -1c
.RI "\fBTerrainModel\fP (void *data, int width, int depth, float maxHeight, \fBShader\fP *shade)"
.br
.ti -1c
.RI "void \fBDrawObj\fP () override"
.br
.ti -1c
.RI "\fBMesh\fP \fBgenerateTerrainMesh\fP (int width, int depth, float maxHeight)"
.br
.in -1c

Public Member Functions inherited from \fBPAIN::Model\fP
.in +1c
.ti -1c
.RI "\fBModel\fP ()"
.br
.ti -1c
.RI "\fBModel\fP (std::string path)"
.br
.ti -1c
.RI "void \fBDraw\fP (\fBShader\fP &\fBshader\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBTerraindata\fP"
.br
.ti -1c
.RI "\fBShader\fP * \fBshader\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBGameObject\fP > \fBobject\fP"
.br
.in -1c

Public Attributes inherited from \fBPAIN::Model\fP
.in +1c
.ti -1c
.RI "vector< \fBMesh\fP > \fBmeshes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB38\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PAIN::TerrainModel::TerrainModel ()"

.PP
Definition at line \fB64\fP of file \fBRENDER_MATERIAL\&.cpp\fP\&.
.SS "PAIN::TerrainModel::TerrainModel (void * data, int width, int depth, float maxHeight, \fBShader\fP * shade)"

.PP
Definition at line \fB68\fP of file \fBRENDER_MATERIAL\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PAIN::TerrainModel::DrawObj ()\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBPAIN::Render\fP\&.
.PP
Definition at line \fB76\fP of file \fBRENDER_MATERIAL\&.cpp\fP\&.
.SS "\fBPAIN::Mesh\fP PAIN::TerrainModel::generateTerrainMesh (int width, int depth, float maxHeight)"

.PP
Definition at line \fB94\fP of file \fBRENDER_MATERIAL\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::shared_ptr<\fBGameObject\fP> PAIN::TerrainModel::object"

.PP
Definition at line \fB44\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SS "\fBShader\fP* PAIN::TerrainModel::shader"

.PP
Definition at line \fB43\fP of file \fBRENDER_MATERIAL\&.h\fP\&.
.SS "void* PAIN::TerrainModel::Terraindata"

.PP
Definition at line \fB40\fP of file \fBRENDER_MATERIAL\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
