.TH "PAIN" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAIN
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaterial\fP"
.br
.ti -1c
.RI "class \fBMesh\fP"
.br
.ti -1c
.RI "class \fBMewshU\fP"
.br
.ti -1c
.RI "class \fBModel\fP"
.br
.ti -1c
.RI "class \fBModelU\fP"
.br
.ti -1c
.RI "class \fBRender\fP"
.br
.ti -1c
.RI "class \fBRender_Camera\fP"
.br
.ti -1c
.RI "class \fBRenderStup\fP"
.br
.ti -1c
.RI "class \fBShader\fP"
.br
.ti -1c
.RI "class \fBShaderU\fP"
.br
.ti -1c
.RI "class \fBShaderUtills\fP"
.br
.ti -1c
.RI "class \fBTerrainModel\fP"
.br
.ti -1c
.RI "struct \fBTexture\fP"
.br
.ti -1c
.RI "struct \fBVertex\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBTextureFromFile\fP (const char *path, const string &directory, bool gamma=false)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned int PAIN::TextureFromFile (const char * path, const string & directory, bool gamma = \fRfalse\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
