.TH "PAIN::RenderStup" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAIN::RenderStup
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RENDERSETUP\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GLFWwindow * \fBWindow\fP (int w, int h, const char *Title)"
.br
.ti -1c
.RI "static void \fBframebuffer_size_callback\fP (GLFWwindow *window, int width, int height)"
.br
.ti -1c
.RI "static void \fBSetup\fP (int w, int h, const char *Title)"
.br
.RI "HAS TO BE CALLED TWICE!! "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBGameObject\fP \fBRender_cam\fP"
.br
.ti -1c
.RI "static GLFWwindow * \fBWindowvar\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBRENDERSETUP\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PAIN::RenderStup::framebuffer_size_callback (GLFWwindow * window, int width, int height)\fR [static]\fP"

.PP
Definition at line \fB37\fP of file \fBRenderSetup\&.cpp\fP\&.
.SS "void PAIN::RenderStup::Setup (int w, int h, const char * Title)\fR [static]\fP"

.PP
HAS TO BE CALLED TWICE!! 
.PP
\fBParameters\fP
.RS 4
\fIw\fP 
.br
\fIh\fP 
.br
\fITitle\fP 
.RE
.PP

.PP
Definition at line \fB42\fP of file \fBRenderSetup\&.cpp\fP\&.
.SS "GLFWwindow * PAIN::RenderStup::Window (int w, int h, const char * Title)\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBRenderSetup\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGameObject\fP PAIN::RenderStup::Render_cam\fR [static]\fP"

.PP
Definition at line \fB15\fP of file \fBRENDERSETUP\&.h\fP\&.
.SS "GLFWwindow * PAIN::RenderStup::Windowvar\fR [static]\fP"

.PP
Definition at line \fB17\fP of file \fBRENDERSETUP\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
