.TH "adhed/assimp/pbrmaterial.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/assimp/pbrmaterial.h \- Deprecated GLTF_PBR macros\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <assimp/material\&.h>\fP
.br
\fR#include <assimp/GltfMaterial\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAI_PBRMATERIAL_H_INC\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_PBRMETALLICROUGHNESS_BASE_COLOR_FACTOR\fP   \fBAI_MATKEY_BASE_COLOR\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_PBRMETALLICROUGHNESS_BASE_COLOR_TEXTURE\fP   \fBAI_MATKEY_BASE_COLOR_TEXTURE\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_PBRMETALLICROUGHNESS_METALLIC_FACTOR\fP   \fBAI_MATKEY_METALLIC_FACTOR\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_PBRMETALLICROUGHNESS_ROUGHNESS_FACTOR\fP   \fBAI_MATKEY_ROUGHNESS_FACTOR\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_PBRSPECULARGLOSSINESS\fP   \fBAI_MATKEY_GLOSSINESS_FACTOR\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_PBRSPECULARGLOSSINESS_GLOSSINESS_FACTOR\fP   \fBAI_MATKEY_GLOSSINESS_FACTOR\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_UNLIT\fP   '$mat\&.gltf\&.unlit', 0, 0"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_MATERIAL_SHEEN_COLOR_FACTOR\fP   \fBAI_MATKEY_SHEEN_COLOR_FACTOR\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_MATERIAL_SHEEN_ROUGHNESS_FACTOR\fP   \fBAI_MATKEY_SHEEN_ROUGHNESS_FACTOR\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_MATERIAL_SHEEN_COLOR_TEXTURE\fP   \fBAI_MATKEY_SHEEN_COLOR_TEXTURE\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_MATERIAL_SHEEN_ROUGHNESS_TEXTURE\fP   \fBAI_MATKEY_SHEEN_ROUGHNESS_TEXTURE\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_MATERIAL_CLEARCOAT_FACTOR\fP   \fBAI_MATKEY_CLEARCOAT_FACTOR\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_MATERIAL_CLEARCOAT_ROUGHNESS_FACTOR\fP   \fBAI_MATKEY_CLEARCOAT_ROUGHNESS_FACTOR\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_MATERIAL_CLEARCOAT_TEXTURE\fP   \fBAI_MATKEY_CLEARCOAT_TEXTURE\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_MATERIAL_CLEARCOAT_ROUGHNESS_TEXTURE\fP   \fBAI_MATKEY_CLEARCOAT_ROUGHNESS_TEXTURE\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_MATERIAL_CLEARCOAT_NORMAL_TEXTURE\fP   \fBAI_MATKEY_CLEARCOAT_NORMAL_TEXTURE\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_MATERIAL_TRANSMISSION_FACTOR\fP   \fBAI_MATKEY_TRANSMISSION_FACTOR\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_MATERIAL_TRANSMISSION_TEXTURE\fP   \fBAI_MATKEY_TRANSMISSION_TEXTURE\fP"
.br
.ti -1c
.RI "#define \fBAI_MATKEY_GLTF_TEXTURE_TEXCOORD\fP(\fBtype\fP,  \fBN\fP)   \fBAI_MATKEY_UVWSRC\fP(\fBtype\fP, \fBN\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Deprecated GLTF_PBR macros\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AI_MATKEY_GLTF_MATERIAL_CLEARCOAT_FACTOR   \fBAI_MATKEY_CLEARCOAT_FACTOR\fP"

.SS "#define AI_MATKEY_GLTF_MATERIAL_CLEARCOAT_NORMAL_TEXTURE   \fBAI_MATKEY_CLEARCOAT_NORMAL_TEXTURE\fP"

.SS "#define AI_MATKEY_GLTF_MATERIAL_CLEARCOAT_ROUGHNESS_FACTOR   \fBAI_MATKEY_CLEARCOAT_ROUGHNESS_FACTOR\fP"

.SS "#define AI_MATKEY_GLTF_MATERIAL_CLEARCOAT_ROUGHNESS_TEXTURE   \fBAI_MATKEY_CLEARCOAT_ROUGHNESS_TEXTURE\fP"

.SS "#define AI_MATKEY_GLTF_MATERIAL_CLEARCOAT_TEXTURE   \fBAI_MATKEY_CLEARCOAT_TEXTURE\fP"

.SS "#define AI_MATKEY_GLTF_MATERIAL_SHEEN_COLOR_FACTOR   \fBAI_MATKEY_SHEEN_COLOR_FACTOR\fP"

.SS "#define AI_MATKEY_GLTF_MATERIAL_SHEEN_COLOR_TEXTURE   \fBAI_MATKEY_SHEEN_COLOR_TEXTURE\fP"

.SS "#define AI_MATKEY_GLTF_MATERIAL_SHEEN_ROUGHNESS_FACTOR   \fBAI_MATKEY_SHEEN_ROUGHNESS_FACTOR\fP"

.SS "#define AI_MATKEY_GLTF_MATERIAL_SHEEN_ROUGHNESS_TEXTURE   \fBAI_MATKEY_SHEEN_ROUGHNESS_TEXTURE\fP"

.SS "#define AI_MATKEY_GLTF_MATERIAL_TRANSMISSION_FACTOR   \fBAI_MATKEY_TRANSMISSION_FACTOR\fP"

.SS "#define AI_MATKEY_GLTF_MATERIAL_TRANSMISSION_TEXTURE   \fBAI_MATKEY_TRANSMISSION_TEXTURE\fP"

.SS "#define AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_BASE_COLOR_FACTOR   \fBAI_MATKEY_BASE_COLOR\fP"

.SS "#define AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_BASE_COLOR_TEXTURE   \fBAI_MATKEY_BASE_COLOR_TEXTURE\fP"

.SS "#define AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_METALLIC_FACTOR   \fBAI_MATKEY_METALLIC_FACTOR\fP"

.SS "#define AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_ROUGHNESS_FACTOR   \fBAI_MATKEY_ROUGHNESS_FACTOR\fP"

.SS "#define AI_MATKEY_GLTF_PBRSPECULARGLOSSINESS   \fBAI_MATKEY_GLOSSINESS_FACTOR\fP"

.SS "#define AI_MATKEY_GLTF_PBRSPECULARGLOSSINESS_GLOSSINESS_FACTOR   \fBAI_MATKEY_GLOSSINESS_FACTOR\fP"

.SS "#define AI_MATKEY_GLTF_TEXTURE_TEXCOORD( \fBtype\fP,  \fBN\fP)   \fBAI_MATKEY_UVWSRC\fP(\fBtype\fP, \fBN\fP)"

.SS "#define AI_MATKEY_GLTF_UNLIT   '$mat\&.gltf\&.unlit', 0, 0"

.SS "#define AI_PBRMATERIAL_H_INC"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
