.TH "adhed/glm/gtx/pca.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/pca.inl
.SH SYNOPSIS
.br
.PP
\fR#include <algorithm>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.ti -1c
.RI "namespace \fBglm::_internal_\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBlength_t\fP D, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< \fBD\fP, \fBD\fP, \fBT\fP, \fBQ\fP > \fBglm::computeCovarianceMatrix\fP (\fBvec\fP< \fBD\fP, \fBT\fP, \fBQ\fP > const *\fBv\fP, size_t n)"
.br
.ti -1c
.RI "template<\fBlength_t\fP D, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< \fBD\fP, \fBD\fP, \fBT\fP, \fBQ\fP > \fBglm::computeCovarianceMatrix\fP (\fBvec\fP< \fBD\fP, \fBT\fP, \fBQ\fP > const *\fBv\fP, size_t n, \fBvec\fP< \fBD\fP, \fBT\fP, \fBQ\fP > const &c)"
.br
.ti -1c
.RI "template<\fBlength_t\fP D, typename \fBT\fP , \fBqualifier\fP Q, typename \fBI\fP > \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< \fBD\fP, \fBD\fP, \fBT\fP, \fBQ\fP > \fBglm::computeCovarianceMatrix\fP (\fBI\fP const &\fBb\fP, \fBI\fP const &\fBe\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP D, typename \fBT\fP , \fBqualifier\fP Q, typename \fBI\fP > \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< \fBD\fP, \fBD\fP, \fBT\fP, \fBQ\fP > \fBglm::computeCovarianceMatrix\fP (\fBI\fP const &\fBb\fP, \fBI\fP const &\fBe\fP, \fBvec\fP< \fBD\fP, \fBT\fP, \fBQ\fP > const &c)"
.br
.ti -1c
.RI "template<\fBlength_t\fP D, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP unsigned int \fBglm::findEigenvaluesSymReal\fP (\fBmat\fP< \fBD\fP, \fBD\fP, \fBT\fP, \fBQ\fP > const &covarMat, \fBvec\fP< \fBD\fP, \fBT\fP, \fBQ\fP > &outEigenvalues, \fBmat\fP< \fBD\fP, \fBD\fP, \fBT\fP, \fBQ\fP > &outEigenvectors)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvoid\fP \fBglm::sortEigenvalues\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > &eigenvalues, \fBmat\fP< 2, 2, \fBT\fP, \fBQ\fP > &eigenvectors)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvoid\fP \fBglm::sortEigenvalues\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > &eigenvalues, \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > &eigenvectors)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBvoid\fP \fBglm::sortEigenvalues\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > &eigenvalues, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > &eigenvectors)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
