.TH "UPRISE_ENGINE/pch.h" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/pch.h
.SH SYNOPSIS
.br
.PP
\fR#include 'tracy/Tracy\&.hpp'\fP
.br
\fR#include 'tracy/TracyC\&.h'\fP
.br
\fR#include <Windows\&.h>\fP
.br
\fR#include <shellapi\&.h>\fP
.br
\fR#include <wrl\&.h>\fP
.br
\fR#include 'vector'\fP
.br
\fR#include <immintrin\&.h>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include 'numeric'\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include 'string'\fP
.br
\fR#include 'memory'\fP
.br
\fR#include 'filesystem'\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <array>\fP
.br
\fR#include <bitset>\fP
.br
\fR#include <intrin\&.h>\fP
.br
\fR#include 'sysinfoapi\&.h'\fP
.br
\fR#include 'stb_image\&.h'\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include 'functional'\fP
.br
\fR#include 'mutex'\fP
.br
\fR#include <xmmintrin\&.h>\fP
.br
\fR#include <emmintrin\&.h>\fP
.br
\fR#include <cmath>\fP
.br
\fR#include 'nlohmann/json\&.hpp'\fP
.br
\fR#include <assimp/Importer\&.hpp>\fP
.br
\fR#include <assimp/scene\&.h>\fP
.br
\fR#include <assimp/postprocess\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBHasher\fP"
.br
.ti -1c
.RI "struct \fBEqualTo\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWIN32_LEAN_AND_MEAN\fP"
.br
.ti -1c
.RI "#define \fBsymLoad\fP   GetProcAddress"
.br
.ti -1c
.RI "#define \fB_assimp_\fP"
.br
.ti -1c
.RI "#define \fBGameObject_\fP   std::shared_ptr<\fBGameObject\fP>"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBTypeInfoRef\fP = std::reference_wrapper<const std::type_info>"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBThrowIfFailed\fP (HRESULT hr)"
.br
.ti -1c
.RI "template<class _Ty , class _Arg > _Ty \fBCallCSharpFunction\fP (const WCHAR *patrh, char *functionName, _Arg argument)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _assimp_"

.PP
Definition at line \fB58\fP of file \fBpch\&.h\fP\&.
.SS "#define GameObject_   std::shared_ptr<\fBGameObject\fP>"

.PP
Definition at line \fB117\fP of file \fBpch\&.h\fP\&.
.SS "#define symLoad   GetProcAddress"

.PP
Definition at line \fB13\fP of file \fBpch\&.h\fP\&.
.SS "#define WIN32_LEAN_AND_MEAN"

.PP
Definition at line \fB11\fP of file \fBpch\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "using \fBTypeInfoRef\fP = std::reference_wrapper<const std::type_info>"

.PP
Definition at line \fB91\fP of file \fBpch\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "template<class _Ty , class _Arg > _Ty CallCSharpFunction (const WCHAR * patrh, char * functionName, _Arg argument)"

.PP
Definition at line \fB109\fP of file \fBpch\&.h\fP\&.
.SS "void ThrowIfFailed (HRESULT hr)\fR [inline]\fP"

.PP
Definition at line \fB73\fP of file \fBpch\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
