.TH "pdb_dbi_module_info" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdb_dbi_module_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBis_opened\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint16_t \fBindex\fP"
.br
.ti -1c
.RI "   uint16_t \fBpadding1\fP"
.br
.ti -1c
.RI "   uint32_t \fBoffset\fP"
.br
.ti -1c
.RI "   uint32_t \fBsize\fP"
.br
.ti -1c
.RI "   uint32_t \fBcharacteristics\fP"
.br
.ti -1c
.RI "   uint16_t \fBmodule_index\fP"
.br
.ti -1c
.RI "   uint16_t \fBpadding2\fP"
.br
.ti -1c
.RI "   uint32_t \fBdata_crc\fP"
.br
.ti -1c
.RI "   uint32_t \fBrelocation_crc\fP"
.br
.ti -1c
.RI "} \fBsection\fP"
.br
.ti -1c
.RI "uint16_t \fBis_dirty\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBhas_ec_info\fP: 1"
.br
.ti -1c
.RI "uint16_t \fBtype_server_index\fP: 8"
.br
.ti -1c
.RI "uint16_t \fBsymbol_stream\fP"
.br
.ti -1c
.RI "uint32_t \fBsymbol_byte_size\fP"
.br
.ti -1c
.RI "uint32_t \fBold_lines_byte_size\fP"
.br
.ti -1c
.RI "uint32_t \fBlines_byte_size\fP"
.br
.ti -1c
.RI "uint16_t \fBnum_source_files\fP"
.br
.ti -1c
.RI "uint32_t \fBoffsets\fP"
.br
.ti -1c
.RI "uint32_t \fBsource_file_name_index\fP"
.br
.ti -1c
.RI "uint32_t \fBpdb_file_name_index\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint32_t pdb_dbi_module_info::characteristics"

.SS "uint32_t pdb_dbi_module_info::data_crc"

.SS "uint16_t pdb_dbi_module_info::has_ec_info"

.SS "uint16_t pdb_dbi_module_info::index"

.SS "uint16_t pdb_dbi_module_info::is_dirty"

.SS "uint32_t pdb_dbi_module_info::is_opened"

.SS "uint32_t pdb_dbi_module_info::lines_byte_size"

.SS "uint16_t pdb_dbi_module_info::module_index"

.SS "uint16_t pdb_dbi_module_info::num_source_files"

.SS "uint32_t pdb_dbi_module_info::offset"

.SS "uint32_t pdb_dbi_module_info::offsets"

.SS "uint32_t pdb_dbi_module_info::old_lines_byte_size"

.SS "uint16_t pdb_dbi_module_info::padding1"

.SS "uint16_t pdb_dbi_module_info::padding2"

.SS "uint32_t pdb_dbi_module_info::pdb_file_name_index"

.SS "uint32_t pdb_dbi_module_info::relocation_crc"

.SS "struct  { \&.\&.\&. }  pdb_dbi_module_info::section"

.SS "uint32_t pdb_dbi_module_info::size"

.SS "uint32_t pdb_dbi_module_info::source_file_name_index"

.SS "uint32_t pdb_dbi_module_info::symbol_byte_size"

.SS "uint16_t pdb_dbi_module_info::symbol_stream"

.SS "uint16_t pdb_dbi_module_info::type_server_index"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
