.TH "pdb_header" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdb_header
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBversion\fP"
.br
.ti -1c
.RI "uint32_t \fBtime_date_stamp\fP"
.br
.ti -1c
.RI "uint32_t \fBage\fP"
.br
.ti -1c
.RI "\fBblink::guid\fP \fBguid\fP"
.br
.ti -1c
.RI "uint32_t \fBnames_map_offset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Copyright (C) 2016 Patrick Mours\&. All rights reserved\&. License: https://github.com/crosire/blink#license Microsoft program debug database file
.PP
File is a multi-stream file with various different data streams\&. Some streams are located at a fixed index:
.IP "\(bu" 2
Stream 1: PDB headers and list of named streams
.IP "\(bu" 2
Stream 2: Type info (TPI stream)
.IP "\(bu" 2
Stream 3: \fBDebug\fP info (DBI stream) 
.PP

.SH "Member Data Documentation"
.PP 
.SS "uint32_t pdb_header::age"

.SS "\fBblink::guid\fP pdb_header::guid"

.SS "uint32_t pdb_header::names_map_offset"

.SS "uint32_t pdb_header::time_date_stamp"

.SS "uint32_t pdb_header::version"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
