.TH "pdb_dbi_debug_header" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdb_dbi_debug_header
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBfpo\fP"
.br
.ti -1c
.RI "uint16_t \fBexception\fP"
.br
.ti -1c
.RI "uint16_t \fBfixup\fP"
.br
.ti -1c
.RI "uint16_t \fBomap_to_src\fP"
.br
.ti -1c
.RI "uint16_t \fBomap_from_src\fP"
.br
.ti -1c
.RI "uint16_t \fBsection_header\fP"
.br
.ti -1c
.RI "uint16_t \fBtoken_rid_map\fP"
.br
.ti -1c
.RI "uint16_t \fBxdata\fP"
.br
.ti -1c
.RI "uint16_t \fBpdata\fP"
.br
.ti -1c
.RI "uint16_t \fBnew_fpo\fP"
.br
.ti -1c
.RI "uint16_t \fBsection_header_orig\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint16_t pdb_dbi_debug_header::exception"

.SS "uint16_t pdb_dbi_debug_header::fixup"

.SS "uint16_t pdb_dbi_debug_header::fpo"

.SS "uint16_t pdb_dbi_debug_header::new_fpo"

.SS "uint16_t pdb_dbi_debug_header::omap_from_src"

.SS "uint16_t pdb_dbi_debug_header::omap_to_src"

.SS "uint16_t pdb_dbi_debug_header::pdata"

.SS "uint16_t pdb_dbi_debug_header::section_header"

.SS "uint16_t pdb_dbi_debug_header::section_header_orig"

.SS "uint16_t pdb_dbi_debug_header::token_rid_map"

.SS "uint16_t pdb_dbi_debug_header::xdata"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
