.TH "UPRISE_ENGINE/PHYSICS_MANAGER.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/PHYSICS_MANAGER.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'pch\&.h'\fP
.br
\fR#include 'PHYSICS_MANAGER\&.h'\fP
.br
\fR#include 'HeaderE/CORE/C_THREADING\&.h'\fP
.br
\fR#include 'TRANSFORM\&.h'\fP
.br
\fR#include 'PHYSICS_OBJECT\&.h'\fP
.br
\fR#include '_PHYSICSOBJEC\&.h'\fP
.br
\fR#include 'GAMEOBJECT\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
