.TH "UPRISE_ENGINE/PHYSICS_MANAGER.h" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/PHYSICS_MANAGER.h
.SH SYNOPSIS
.br
.PP
\fR#include 'pch\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPHYSICS::Physics\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPHYSICS\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_PHYSICS_MANAGER_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _PHYSICS_MANAGER_"

.PP
Definition at line \fB3\fP of file \fBPHYSICS_MANAGER\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
