.TH "adhed/glm/simd/platform.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/simd/platform.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLM_PLATFORM_UNKNOWN\fP   0x00000000"
.br
.ti -1c
.RI "#define \fBGLM_PLATFORM_WINDOWS\fP   0x00010000"
.br
.ti -1c
.RI "#define \fBGLM_PLATFORM_LINUX\fP   0x00020000"
.br
.ti -1c
.RI "#define \fBGLM_PLATFORM_APPLE\fP   0x00040000"
.br
.ti -1c
.RI "#define \fBGLM_PLATFORM_ANDROID\fP   0x00100000"
.br
.ti -1c
.RI "#define \fBGLM_PLATFORM_CHROME_NACL\fP   0x00200000"
.br
.ti -1c
.RI "#define \fBGLM_PLATFORM_UNIX\fP   0x00400000"
.br
.ti -1c
.RI "#define \fBGLM_PLATFORM_QNXNTO\fP   0x00800000"
.br
.ti -1c
.RI "#define \fBGLM_PLATFORM_WINCE\fP   0x01000000"
.br
.ti -1c
.RI "#define \fBGLM_PLATFORM_CYGWIN\fP   0x02000000"
.br
.ti -1c
.RI "#define \fBGLM_PLATFORM\fP   \fBGLM_PLATFORM_UNKNOWN\fP"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_UNKNOWN\fP   0x00000000"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_INTEL\fP   0x00100000"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_INTEL14\fP   0x00100040"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_INTEL15\fP   0x00100050"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_INTEL16\fP   0x00100060"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_INTEL17\fP   0x00100070"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_INTEL18\fP   0x00100080"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_INTEL19\fP   0x00100090"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_INTEL21\fP   0x001000A0"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_VC\fP   0x01000000"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_VC12\fP   0x01000001"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_VC14\fP   0x01000002"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_VC15\fP   0x01000003"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_VC15_3\fP   0x01000004"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_VC15_5\fP   0x01000005"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_VC15_6\fP   0x01000006"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_VC15_7\fP   0x01000007"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_VC15_8\fP   0x01000008"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_VC15_9\fP   0x01000009"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_VC16\fP   0x0100000A"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_VC17\fP   0x0100000B"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_GCC\fP   0x02000000"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_GCC46\fP   0x020000D0"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_GCC47\fP   0x020000E0"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_GCC48\fP   0x020000F0"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_GCC49\fP   0x02000100"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_GCC5\fP   0x02000200"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_GCC6\fP   0x02000300"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_GCC61\fP   0x02000800"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_GCC7\fP   0x02000400"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_GCC8\fP   0x02000500"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_GCC9\fP   0x02000600"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_GCC10\fP   0x02000700"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_GCC11\fP   0x02000800"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_GCC12\fP   0x02000900"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_GCC13\fP   0x02000A00"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_GCC14\fP   0x02000B00"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CUDA\fP   0x10000000"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CUDA75\fP   0x10000001"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CUDA80\fP   0x10000002"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CUDA90\fP   0x10000004"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CUDA_RTC\fP   0x10000100"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG\fP   0x20000000"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG34\fP   0x20000050"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG35\fP   0x20000060"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG36\fP   0x20000070"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG37\fP   0x20000080"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG38\fP   0x20000090"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG39\fP   0x200000A0"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG4\fP   0x200000B0"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG5\fP   0x200000C0"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG6\fP   0x200000D0"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG7\fP   0x200000E0"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG8\fP   0x200000F0"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG9\fP   0x20000100"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG10\fP   0x20000200"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG11\fP   0x20000300"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG12\fP   0x20000400"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG13\fP   0x20000500"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG14\fP   0x20000600"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG15\fP   0x20000700"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG16\fP   0x20000800"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG17\fP   0x20000900"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG18\fP   0x20000A00"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_CLANG19\fP   0x20000B00"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER_HIP\fP   0x40000000"
.br
.ti -1c
.RI "#define \fBGLM_MODEL_32\fP   0x00000010"
.br
.ti -1c
.RI "#define \fBGLM_MODEL_64\fP   0x00000020"
.br
.ti -1c
.RI "#define \fBGLM_COMPILER\fP   \fBGLM_COMPILER_UNKNOWN\fP"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_MIPS_BIT\fP   (0x10000000)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_PPC_BIT\fP   (0x20000000)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_ARM_BIT\fP   (0x40000000)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_ARMV8_BIT\fP   (0x01000000)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_X86_BIT\fP   (0x80000000)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_SIMD_BIT\fP   (0x00001000)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_NEON_BIT\fP   (0x00000001)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_SSE_BIT\fP   (0x00000002)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_SSE2_BIT\fP   (0x00000004)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_SSE3_BIT\fP   (0x00000008)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_SSSE3_BIT\fP   (0x00000010)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_SSE41_BIT\fP   (0x00000020)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_SSE42_BIT\fP   (0x00000040)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_AVX_BIT\fP   (0x00000080)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_AVX2_BIT\fP   (0x00000100)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_UNKNOWN\fP   (0)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_X86\fP   (\fBGLM_ARCH_X86_BIT\fP)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_SSE\fP   (\fBGLM_ARCH_SSE_BIT\fP | \fBGLM_ARCH_SIMD_BIT\fP | \fBGLM_ARCH_X86\fP)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_SSE2\fP   (\fBGLM_ARCH_SSE2_BIT\fP | \fBGLM_ARCH_SSE\fP)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_SSE3\fP   (\fBGLM_ARCH_SSE3_BIT\fP | \fBGLM_ARCH_SSE2\fP)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_SSSE3\fP   (\fBGLM_ARCH_SSSE3_BIT\fP | \fBGLM_ARCH_SSE3\fP)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_SSE41\fP   (\fBGLM_ARCH_SSE41_BIT\fP | \fBGLM_ARCH_SSSE3\fP)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_SSE42\fP   (\fBGLM_ARCH_SSE42_BIT\fP | \fBGLM_ARCH_SSE41\fP)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_AVX\fP   (\fBGLM_ARCH_AVX_BIT\fP | \fBGLM_ARCH_SSE42\fP)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_AVX2\fP   (\fBGLM_ARCH_AVX2_BIT\fP | \fBGLM_ARCH_AVX\fP)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_ARM\fP   (\fBGLM_ARCH_ARM_BIT\fP)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_ARMV8\fP   (\fBGLM_ARCH_NEON_BIT\fP | \fBGLM_ARCH_SIMD_BIT\fP | \fBGLM_ARCH_ARM\fP | \fBGLM_ARCH_ARMV8_BIT\fP)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_NEON\fP   (\fBGLM_ARCH_NEON_BIT\fP | \fBGLM_ARCH_SIMD_BIT\fP | \fBGLM_ARCH_ARM\fP)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_MIPS\fP   (\fBGLM_ARCH_MIPS_BIT\fP)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH_PPC\fP   (\fBGLM_ARCH_PPC_BIT\fP)"
.br
.ti -1c
.RI "#define \fBGLM_ARCH\fP   (\fBGLM_ARCH_UNKNOWN\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GLM_ARCH   (\fBGLM_ARCH_UNKNOWN\fP)"

.SS "#define GLM_ARCH_ARM   (\fBGLM_ARCH_ARM_BIT\fP)"

.SS "#define GLM_ARCH_ARM_BIT   (0x40000000)"

.SS "#define GLM_ARCH_ARMV8   (\fBGLM_ARCH_NEON_BIT\fP | \fBGLM_ARCH_SIMD_BIT\fP | \fBGLM_ARCH_ARM\fP | \fBGLM_ARCH_ARMV8_BIT\fP)"

.SS "#define GLM_ARCH_ARMV8_BIT   (0x01000000)"

.SS "#define GLM_ARCH_AVX   (\fBGLM_ARCH_AVX_BIT\fP | \fBGLM_ARCH_SSE42\fP)"

.SS "#define GLM_ARCH_AVX2   (\fBGLM_ARCH_AVX2_BIT\fP | \fBGLM_ARCH_AVX\fP)"

.SS "#define GLM_ARCH_AVX2_BIT   (0x00000100)"

.SS "#define GLM_ARCH_AVX_BIT   (0x00000080)"

.SS "#define GLM_ARCH_MIPS   (\fBGLM_ARCH_MIPS_BIT\fP)"

.SS "#define GLM_ARCH_MIPS_BIT   (0x10000000)"

.SS "#define GLM_ARCH_NEON   (\fBGLM_ARCH_NEON_BIT\fP | \fBGLM_ARCH_SIMD_BIT\fP | \fBGLM_ARCH_ARM\fP)"

.SS "#define GLM_ARCH_NEON_BIT   (0x00000001)"

.SS "#define GLM_ARCH_PPC   (\fBGLM_ARCH_PPC_BIT\fP)"

.SS "#define GLM_ARCH_PPC_BIT   (0x20000000)"

.SS "#define GLM_ARCH_SIMD_BIT   (0x00001000)"

.SS "#define GLM_ARCH_SSE   (\fBGLM_ARCH_SSE_BIT\fP | \fBGLM_ARCH_SIMD_BIT\fP | \fBGLM_ARCH_X86\fP)"

.SS "#define GLM_ARCH_SSE2   (\fBGLM_ARCH_SSE2_BIT\fP | \fBGLM_ARCH_SSE\fP)"

.SS "#define GLM_ARCH_SSE2_BIT   (0x00000004)"

.SS "#define GLM_ARCH_SSE3   (\fBGLM_ARCH_SSE3_BIT\fP | \fBGLM_ARCH_SSE2\fP)"

.SS "#define GLM_ARCH_SSE3_BIT   (0x00000008)"

.SS "#define GLM_ARCH_SSE41   (\fBGLM_ARCH_SSE41_BIT\fP | \fBGLM_ARCH_SSSE3\fP)"

.SS "#define GLM_ARCH_SSE41_BIT   (0x00000020)"

.SS "#define GLM_ARCH_SSE42   (\fBGLM_ARCH_SSE42_BIT\fP | \fBGLM_ARCH_SSE41\fP)"

.SS "#define GLM_ARCH_SSE42_BIT   (0x00000040)"

.SS "#define GLM_ARCH_SSE_BIT   (0x00000002)"

.SS "#define GLM_ARCH_SSSE3   (\fBGLM_ARCH_SSSE3_BIT\fP | \fBGLM_ARCH_SSE3\fP)"

.SS "#define GLM_ARCH_SSSE3_BIT   (0x00000010)"

.SS "#define GLM_ARCH_UNKNOWN   (0)"

.SS "#define GLM_ARCH_X86   (\fBGLM_ARCH_X86_BIT\fP)"

.SS "#define GLM_ARCH_X86_BIT   (0x80000000)"

.SS "#define GLM_COMPILER   \fBGLM_COMPILER_UNKNOWN\fP"

.SS "#define GLM_COMPILER_CLANG   0x20000000"

.SS "#define GLM_COMPILER_CLANG10   0x20000200"

.SS "#define GLM_COMPILER_CLANG11   0x20000300"

.SS "#define GLM_COMPILER_CLANG12   0x20000400"

.SS "#define GLM_COMPILER_CLANG13   0x20000500"

.SS "#define GLM_COMPILER_CLANG14   0x20000600"

.SS "#define GLM_COMPILER_CLANG15   0x20000700"

.SS "#define GLM_COMPILER_CLANG16   0x20000800"

.SS "#define GLM_COMPILER_CLANG17   0x20000900"

.SS "#define GLM_COMPILER_CLANG18   0x20000A00"

.SS "#define GLM_COMPILER_CLANG19   0x20000B00"

.SS "#define GLM_COMPILER_CLANG34   0x20000050"

.SS "#define GLM_COMPILER_CLANG35   0x20000060"

.SS "#define GLM_COMPILER_CLANG36   0x20000070"

.SS "#define GLM_COMPILER_CLANG37   0x20000080"

.SS "#define GLM_COMPILER_CLANG38   0x20000090"

.SS "#define GLM_COMPILER_CLANG39   0x200000A0"

.SS "#define GLM_COMPILER_CLANG4   0x200000B0"

.SS "#define GLM_COMPILER_CLANG5   0x200000C0"

.SS "#define GLM_COMPILER_CLANG6   0x200000D0"

.SS "#define GLM_COMPILER_CLANG7   0x200000E0"

.SS "#define GLM_COMPILER_CLANG8   0x200000F0"

.SS "#define GLM_COMPILER_CLANG9   0x20000100"

.SS "#define GLM_COMPILER_CUDA   0x10000000"

.SS "#define GLM_COMPILER_CUDA75   0x10000001"

.SS "#define GLM_COMPILER_CUDA80   0x10000002"

.SS "#define GLM_COMPILER_CUDA90   0x10000004"

.SS "#define GLM_COMPILER_CUDA_RTC   0x10000100"

.SS "#define GLM_COMPILER_GCC   0x02000000"

.SS "#define GLM_COMPILER_GCC10   0x02000700"

.SS "#define GLM_COMPILER_GCC11   0x02000800"

.SS "#define GLM_COMPILER_GCC12   0x02000900"

.SS "#define GLM_COMPILER_GCC13   0x02000A00"

.SS "#define GLM_COMPILER_GCC14   0x02000B00"

.SS "#define GLM_COMPILER_GCC46   0x020000D0"

.SS "#define GLM_COMPILER_GCC47   0x020000E0"

.SS "#define GLM_COMPILER_GCC48   0x020000F0"

.SS "#define GLM_COMPILER_GCC49   0x02000100"

.SS "#define GLM_COMPILER_GCC5   0x02000200"

.SS "#define GLM_COMPILER_GCC6   0x02000300"

.SS "#define GLM_COMPILER_GCC61   0x02000800"

.SS "#define GLM_COMPILER_GCC7   0x02000400"

.SS "#define GLM_COMPILER_GCC8   0x02000500"

.SS "#define GLM_COMPILER_GCC9   0x02000600"

.SS "#define GLM_COMPILER_HIP   0x40000000"

.SS "#define GLM_COMPILER_INTEL   0x00100000"

.SS "#define GLM_COMPILER_INTEL14   0x00100040"

.SS "#define GLM_COMPILER_INTEL15   0x00100050"

.SS "#define GLM_COMPILER_INTEL16   0x00100060"

.SS "#define GLM_COMPILER_INTEL17   0x00100070"

.SS "#define GLM_COMPILER_INTEL18   0x00100080"

.SS "#define GLM_COMPILER_INTEL19   0x00100090"

.SS "#define GLM_COMPILER_INTEL21   0x001000A0"

.SS "#define GLM_COMPILER_UNKNOWN   0x00000000"

.SS "#define GLM_COMPILER_VC   0x01000000"

.SS "#define GLM_COMPILER_VC12   0x01000001"

.SS "#define GLM_COMPILER_VC14   0x01000002"

.SS "#define GLM_COMPILER_VC15   0x01000003"

.SS "#define GLM_COMPILER_VC15_3   0x01000004"

.SS "#define GLM_COMPILER_VC15_5   0x01000005"

.SS "#define GLM_COMPILER_VC15_6   0x01000006"

.SS "#define GLM_COMPILER_VC15_7   0x01000007"

.SS "#define GLM_COMPILER_VC15_8   0x01000008"

.SS "#define GLM_COMPILER_VC15_9   0x01000009"

.SS "#define GLM_COMPILER_VC16   0x0100000A"

.SS "#define GLM_COMPILER_VC17   0x0100000B"

.SS "#define GLM_MODEL_32   0x00000010"

.SS "#define GLM_MODEL_64   0x00000020"

.SS "#define GLM_PLATFORM   \fBGLM_PLATFORM_UNKNOWN\fP"

.SS "#define GLM_PLATFORM_ANDROID   0x00100000"

.SS "#define GLM_PLATFORM_APPLE   0x00040000"

.SS "#define GLM_PLATFORM_CHROME_NACL   0x00200000"

.SS "#define GLM_PLATFORM_CYGWIN   0x02000000"

.SS "#define GLM_PLATFORM_LINUX   0x00020000"

.SS "#define GLM_PLATFORM_QNXNTO   0x00800000"

.SS "#define GLM_PLATFORM_UNIX   0x00400000"

.SS "#define GLM_PLATFORM_UNKNOWN   0x00000000"

.SS "#define GLM_PLATFORM_WINCE   0x01000000"

.SS "#define GLM_PLATFORM_WINDOWS   0x00010000"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
