.TH "packages/directxtk12_uwp.2024.6.5.1/include/PostProcess.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/directxtk12_uwp.2024.6.5.1/include/PostProcess.h
.SH SYNOPSIS
.br
.PP
\fR#include <d3d12\&.h>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <DirectXMath\&.h>\fP
.br
\fR#include 'RenderTargetState\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDirectX::DX12::IPostProcess\fP"
.br
.ti -1c
.RI "class \fBDirectX::DX12::BasicPostProcess\fP"
.br
.ti -1c
.RI "class \fBDirectX::DX12::DualPostProcess\fP"
.br
.ti -1c
.RI "class \fBDirectX::DX12::ToneMapPostProcess\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDirectX\fP"
.br
.ti -1c
.RI "namespace \fBDirectX::DX12\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
