.TH "adhed/assimp/qnan.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/assimp/qnan.h \- Some utilities for our dealings with qnans\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <assimp/defs\&.h>\fP
.br
\fR#include <limits>\fP
.br
\fR#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "union \fB_IEEESingle\fP"
.br
.ti -1c
.RI "union \fB_IEEEDouble\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAI_QNAN_H_INCLUDED\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP bool \fBis_qnan\fP (float in)"
.br
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP bool \fBis_qnan\fP (double in)"
.br
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP bool \fBis_special_float\fP (float in)"
.br
.RI "check whether a float is either NaN or (+/-) INF\&. "
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP bool \fBis_special_float\fP (double in)"
.br
.RI "check whether a double is either NaN or (+/-) INF\&. "
.ti -1c
.RI "template<class TReal > \fBAI_FORCE_INLINE\fP bool \fBis_not_qnan\fP (TReal in)"
.br
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP \fBai_real\fP \fBget_qnan\fP ()"
.br
.RI "Get a fresh qnan\&. 
.br
 "
.in -1c
.SH "Detailed Description"
.PP 
Some utilities for our dealings with qnans\&. 


.PP
\fBNote\fP
.RS 4
Some loaders use qnans to mark invalid values tempoarily, also \fBAssimp\fP explicitly enforces undefined normals to be set to qnan\&. qnan utilities are available in standard libraries (C99 for example) but last time I checked compiler coverage was so bad that I decided to reinvent the wheel\&. 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define AI_QNAN_H_INCLUDED"

.SH "Function Documentation"
.PP 
.SS "\fBAI_FORCE_INLINE\fP \fBai_real\fP get_qnan ()"

.PP
Get a fresh qnan\&. 
.br
 
.SS "template<class TReal > \fBAI_FORCE_INLINE\fP bool is_not_qnan (TReal in)"
Check whether a float is NOT qNaN\&. 
.PP
\fBParameters\fP
.RS 4
\fIin\fP Input value 
.RE
.PP

.SS "\fBAI_FORCE_INLINE\fP bool is_qnan (double in)"
Check whether a given double is qNaN\&. 
.PP
\fBParameters\fP
.RS 4
\fIin\fP Input value 
.RE
.PP

.SS "\fBAI_FORCE_INLINE\fP bool is_qnan (float in)"
Check whether a given float is qNaN\&. 
.PP
\fBParameters\fP
.RS 4
\fIin\fP Input value 
.RE
.PP

.SS "\fBAI_FORCE_INLINE\fP bool is_special_float (double in)"

.PP
check whether a double is either NaN or (+/-) INF\&. Denorms return false, they're treated like normal values\&. 
.PP
\fBParameters\fP
.RS 4
\fIin\fP Input value 
.RE
.PP

.SS "\fBAI_FORCE_INLINE\fP bool is_special_float (float in)"

.PP
check whether a float is either NaN or (+/-) INF\&. Denorms return false, they're treated like normal values\&. 
.PP
\fBParameters\fP
.RS 4
\fIin\fP Input value 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
