.TH "adhed/glm/ext/quaternion_float_precision.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/ext/quaternion_float_precision.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./detail/type_quat\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBqua\fP< float, \fBlowp\fP > \fBglm::lowp_quat\fP"
.br
.RI "Quaternion of single-precision floating-point numbers using high precision arithmetic in term of ULPs\&. "
.ti -1c
.RI "typedef \fBqua\fP< float, \fBmediump\fP > \fBglm::mediump_quat\fP"
.br
.RI "Quaternion of single-precision floating-point numbers using high precision arithmetic in term of ULPs\&. "
.ti -1c
.RI "typedef \fBqua\fP< float, \fBhighp\fP > \fBglm::highp_quat\fP"
.br
.RI "Quaternion of single-precision floating-point numbers using high precision arithmetic in term of ULPs\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_quaternion_float_precision\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
