.TH "adhed/glm/ext/quaternion_relational.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/ext/quaternion_relational.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./vector_relational\&.hpp'\fP
.br
\fR#include 'quaternion_relational\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, bool, \fBQ\fP > \fBglm::equal\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, bool, \fBQ\fP > \fBglm::equal\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBT\fP \fBepsilon\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, bool, \fBQ\fP > \fBglm::notEqual\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< 4, bool, \fBQ\fP > \fBglm::notEqual\fP (\fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBqua\fP< \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBT\fP \fBepsilon\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_quaternion_relational\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
