.TH "adhed/glm/gtc/random.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtc/random.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./ext/scalar_int_sized\&.hpp'\fP
.br
\fR#include '\&.\&./ext/scalar_uint_sized\&.hpp'\fP
.br
\fR#include '\&.\&./detail/qualifier\&.hpp'\fP
.br
\fR#include 'random\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::linearRand\fP (genType Min, genType Max)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::linearRand\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &Min, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &Max)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::gaussRand\fP (genType Mean, genType Deviation)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBvec\fP< 2, \fBT\fP, \fBdefaultp\fP > \fBglm::circularRand\fP (\fBT\fP Radius)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBdefaultp\fP > \fBglm::sphericalRand\fP (\fBT\fP Radius)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBvec\fP< 2, \fBT\fP, \fBdefaultp\fP > \fBglm::diskRand\fP (\fBT\fP Radius)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_DECL\fP \fBvec\fP< 3, \fBT\fP, \fBdefaultp\fP > \fBglm::ballRand\fP (\fBT\fP Radius)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTC_random\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
gtx_random (extended) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
