.TH "Ray" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ray
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <D_RAY\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRay\fP (\fBDATATYPES::TS_P_Vector3\fP origin, \fBDATATYPES::TS_P_Vector3\fP direction)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDATATYPES::TS_P_Vector3\fP \fBOrigin\fP"
.br
.ti -1c
.RI "\fBDATATYPES::TS_P_Vector3\fP \fBDirection\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBGameObject\fP > \fBhit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBD_RAY\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Ray::Ray (\fBDATATYPES::TS_P_Vector3\fP origin, \fBDATATYPES::TS_P_Vector3\fP direction)"

.SH "Member Data Documentation"
.PP 
.SS "\fBDATATYPES::TS_P_Vector3\fP Ray::Direction"

.PP
Definition at line \fB10\fP of file \fBD_RAY\&.h\fP\&.
.SS "std::shared_ptr<\fBGameObject\fP> Ray::hit"

.PP
Definition at line \fB11\fP of file \fBD_RAY\&.h\fP\&.
.SS "\fBDATATYPES::TS_P_Vector3\fP Ray::Origin"

.PP
Definition at line \fB10\fP of file \fBD_RAY\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
