.TH "RegisterScripts.py" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RegisterScripts.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBRegisterScripts\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRegisterScripts\&.generate_guard_name\fP (file_path)"
.br
.ti -1c
.RI "\fBRegisterScripts\&.process_file\fP (file_path)"
.br
.ti -1c
.RI "\fBRegisterScripts\&.process_directory\fP (directory)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
