.TH "UPRISE_ENGINE/RENDER_MATERIAL.cpp" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/RENDER_MATERIAL.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'GLINCLUDES\&.h'\fP
.br
\fR#include 'RENDER_MATERIAL\&.h'\fP
.br
\fR#include 'DATATYPES\&.h'\fP
.br
\fR#include 'TERRAIN_DATA\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
