.TH "UPRISE_ENGINE/RENDER_SHADER_UTILLS.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/RENDER_SHADER_UTILLS.h
.SH SYNOPSIS
.br
.PP
\fR#include 'GLINCLUDES\&.h'\fP
.br
\fR#include 'pch\&.h'\fP
.br
\fR#include 'HeaderE/DATATYPES/D_CONFIGFILE\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPAIN::ShaderU\fP"
.br
.ti -1c
.RI "class \fBPAIN::ShaderUtills\fP"
.br
.ti -1c
.RI "class \fBPAIN::Shader\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPAIN\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_RENDER_SHADER_UTILLS_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _RENDER_SHADER_UTILLS_"

.PP
Definition at line \fB8\fP of file \fBRENDER_SHADER_UTILLS\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
