.TH "UPRISE_ENGINE/RENDER_OBJECT_SPAWNING.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/RENDER_OBJECT_SPAWNING.h
.SH SYNOPSIS
.br
.PP
\fR#include 'HeaderE/DATATYPES/D_DATATYPES\&.h'\fP
.br
\fR#include 'GLINCLUDES\&.h'\fP
.br
\fR#include 'pch\&.h'\fP
.br
\fR#include 'RENDER_DATATYPES\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPAIN\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_RENDER_OBJECT_SPAWNING_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _RENDER_OBJECT_SPAWNING_"

.PP
Definition at line \fB4\fP of file \fBRENDER_OBJECT_SPAWNING\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
