.TH "UPRISE_ENGINE/RenderSetup.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/RenderSetup.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'pch\&.h'\fP
.br
\fR#include 'RENDER\&.h'\fP
.br
\fR#include 'RENDERSETUP\&.h'\fP
.br
\fR#include 'RENDER_MATERIAL\&.h'\fP
.br
\fR#include 'GAMEOBJECT\&.h'\fP
.br
\fR#include 'DEBUG_LOGGER\&.h'\fP
.br
\fR#include 'CAMERA\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBRenderer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
