.TH "ResidentTier" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResidentTier
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <D_DEMOGRAFICCLASS\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBTier\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBD_DEMOGRAFICCLASS\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ResidentTier::Tier"

.PP
Definition at line \fB7\fP of file \fBD_DEMOGRAFICCLASS\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
