.TH "adhed/glm/gtc/round.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtc/round.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./detail/setup\&.hpp'\fP
.br
\fR#include '\&.\&./detail/qualifier\&.hpp'\fP
.br
\fR#include '\&.\&./detail/_vectorize\&.hpp'\fP
.br
\fR#include '\&.\&./vector_relational\&.hpp'\fP
.br
\fR#include '\&.\&./common\&.hpp'\fP
.br
\fR#include <limits>\fP
.br
\fR#include 'round\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType \fBglm::ceilPowerOfTwo\fP (genIUType \fBv\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::ceilPowerOfTwo\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType \fBglm::floorPowerOfTwo\fP (genIUType \fBv\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::floorPowerOfTwo\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_DECL\fP genIUType \fBglm::roundPowerOfTwo\fP (genIUType \fBv\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::roundPowerOfTwo\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::ceilMultiple\fP (genType \fBv\fP, genType Multiple)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::ceilMultiple\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &Multiple)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::floorMultiple\fP (genType \fBv\fP, genType Multiple)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::floorMultiple\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &Multiple)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::roundMultiple\fP (genType \fBv\fP, genType Multiple)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::roundMultiple\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &Multiple)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTC_round\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTC_round\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
