.TH "adhed/glm/ext/scalar_integer.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/ext/scalar_integer.inl
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./integer\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBglm::detail::compute_ceilShift< L, T, Q, compute >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_ceilShift< L, T, Q, true >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_ceilPowerOfTwo< L, T, Q, isSigned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_ceilPowerOfTwo< L, T, Q, false >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_ceilMultiple< is_float, is_signed >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_ceilMultiple< true, true >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_ceilMultiple< false, false >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_ceilMultiple< false, true >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_floorMultiple< is_float, is_signed >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_floorMultiple< true, true >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_floorMultiple< false, false >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_floorMultiple< false, true >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.ti -1c
.RI "namespace \fBglm::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_QUALIFIER\fP bool \fBglm::isPowerOfTwo\fP (genIUType \fBValue\fP)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_QUALIFIER\fP genIUType \fBglm::nextPowerOfTwo\fP (genIUType \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_QUALIFIER\fP genIUType \fBglm::prevPowerOfTwo\fP (genIUType \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_QUALIFIER\fP bool \fBglm::isMultiple\fP (genIUType \fBValue\fP, genIUType Multiple)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_QUALIFIER\fP genIUType \fBglm::nextMultiple\fP (genIUType Source, genIUType Multiple)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_QUALIFIER\fP genIUType \fBglm::prevMultiple\fP (genIUType Source, genIUType Multiple)"
.br
.ti -1c
.RI "template<typename genIUType > \fBGLM_FUNC_QUALIFIER\fP int \fBglm::findNSB\fP (genIUType \fBx\fP, int significantBitCount)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
