.TH "adhed/glm/ext/scalar_ulp.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/ext/scalar_ulp.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./ext/scalar_int_sized\&.hpp'\fP
.br
\fR#include '\&.\&./common\&.hpp'\fP
.br
\fR#include '\&.\&./detail/qualifier\&.hpp'\fP
.br
\fR#include 'scalar_ulp\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::nextFloat\fP (genType \fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::prevFloat\fP (genType \fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::nextFloat\fP (genType \fBx\fP, int ULPs)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::prevFloat\fP (genType \fBx\fP, int ULPs)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP int \fBglm::floatDistance\fP (float \fBx\fP, float \fBy\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBint64\fP \fBglm::floatDistance\fP (double \fBx\fP, double \fBy\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_scalar_ulp\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
