.TH "adhed/glm/ext/scalar_common.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/ext/scalar_common.inl
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::min\fP (\fBT\fP \fBa\fP, \fBT\fP \fBb\fP, \fBT\fP c)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::min\fP (\fBT\fP \fBa\fP, \fBT\fP \fBb\fP, \fBT\fP c, \fBT\fP d)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::max\fP (\fBT\fP \fBa\fP, \fBT\fP \fBb\fP, \fBT\fP c)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::max\fP (\fBT\fP \fBa\fP, \fBT\fP \fBb\fP, \fBT\fP c, \fBT\fP d)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::fmin\fP (\fBT\fP \fBa\fP, \fBT\fP \fBb\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::fmin\fP (\fBT\fP \fBa\fP, \fBT\fP \fBb\fP, \fBT\fP c)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::fmin\fP (\fBT\fP \fBa\fP, \fBT\fP \fBb\fP, \fBT\fP c, \fBT\fP d)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::fmax\fP (\fBT\fP \fBa\fP, \fBT\fP \fBb\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::fmax\fP (\fBT\fP \fBa\fP, \fBT\fP \fBb\fP, \fBT\fP c)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::fmax\fP (\fBT\fP \fBa\fP, \fBT\fP \fBb\fP, \fBT\fP c, \fBT\fP d)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::fclamp\fP (genType \fBx\fP, genType minVal, genType maxVal)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::clamp\fP (genType const &Texcoord)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::repeat\fP (genType const &Texcoord)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::mirrorClamp\fP (genType const &Texcoord)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::mirrorRepeat\fP (genType const &Texcoord)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP int \fBglm::iround\fP (genType const &\fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP \fBuint\fP \fBglm::uround\fP (genType const &\fBx\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
