.TH "scoped_handle" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scoped_handle
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <scoped_handle\&.hpp>\fP
.PP
Inherited by \fBthread_scope_guard\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBscoped_handle\fP ()"
.br
.ti -1c
.RI "\fBscoped_handle\fP (HANDLE \fBhandle\fP)"
.br
.ti -1c
.RI "\fBscoped_handle\fP (\fBscoped_handle\fP &&other)"
.br
.ti -1c
.RI "\fB~scoped_handle\fP ()"
.br
.ti -1c
.RI "\fBoperator HANDLE\fP () const"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator=\fP (HANDLE p)"
.br
.ti -1c
.RI "HANDLE * \fBoperator&\fP ()"
.br
.ti -1c
.RI "const HANDLE * \fBoperator&\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "HANDLE \fBhandle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Copyright (C) 2016 Patrick Mours\&. All rights reserved\&. License: https://github.com/crosire/blink#license 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "scoped_handle::scoped_handle ()\fR [inline]\fP"

.SS "scoped_handle::scoped_handle (HANDLE handle)\fR [inline]\fP"

.SS "scoped_handle::scoped_handle (\fBscoped_handle\fP && other)\fR [inline]\fP"

.SS "scoped_handle::~scoped_handle ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "scoped_handle::operator HANDLE () const\fR [inline]\fP"

.SS "HANDLE * scoped_handle::operator& ()\fR [inline]\fP"

.SS "const HANDLE * scoped_handle::operator& () const\fR [inline]\fP"

.SS "\fBvoid\fP scoped_handle::operator= (HANDLE p)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "HANDLE scoped_handle::handle"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
