.TH "SettingsFile" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SettingsFile
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CONFIGFILE\&.h>\fP
.SH "Detailed Description"
.PP 
Definition at line \fB84\fP of file \fBCONFIGFILE\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
