.TH "packages/directxtk12_uwp.2024.6.5.1/include/SimpleMath.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/directxtk12_uwp.2024.6.5.1/include/SimpleMath.h
.SH SYNOPSIS
.br
.PP
\fR#include <cassert>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <DirectXMath\&.h>\fP
.br
\fR#include <DirectXPackedVector\&.h>\fP
.br
\fR#include <DirectXCollision\&.h>\fP
.br
\fR#include 'SimpleMath\&.inl'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDirectX::SimpleMath::Rectangle\fP"
.br
.ti -1c
.RI "struct \fBDirectX::SimpleMath::Vector2\fP"
.br
.ti -1c
.RI "struct \fBDirectX::SimpleMath::Vector3\fP"
.br
.ti -1c
.RI "struct \fBDirectX::SimpleMath::Vector4\fP"
.br
.ti -1c
.RI "struct \fBDirectX::SimpleMath::Matrix\fP"
.br
.ti -1c
.RI "struct \fBDirectX::SimpleMath::Plane\fP"
.br
.ti -1c
.RI "struct \fBDirectX::SimpleMath::Quaternion\fP"
.br
.ti -1c
.RI "struct \fBDirectX::SimpleMath::Color\fP"
.br
.ti -1c
.RI "class \fBDirectX::SimpleMath::Ray\fP"
.br
.ti -1c
.RI "class \fBDirectX::SimpleMath::Viewport\fP"
.br
.ti -1c
.RI "struct \fBstd::less< DirectX::SimpleMath::Rectangle >\fP"
.br
.ti -1c
.RI "struct \fBstd::less< DirectX::SimpleMath::Vector2 >\fP"
.br
.ti -1c
.RI "struct \fBstd::less< DirectX::SimpleMath::Vector3 >\fP"
.br
.ti -1c
.RI "struct \fBstd::less< DirectX::SimpleMath::Vector4 >\fP"
.br
.ti -1c
.RI "struct \fBstd::less< DirectX::SimpleMath::Matrix >\fP"
.br
.ti -1c
.RI "struct \fBstd::less< DirectX::SimpleMath::Plane >\fP"
.br
.ti -1c
.RI "struct \fBstd::less< DirectX::SimpleMath::Quaternion >\fP"
.br
.ti -1c
.RI "struct \fBstd::less< DirectX::SimpleMath::Color >\fP"
.br
.ti -1c
.RI "struct \fBstd::less< DirectX::SimpleMath::Ray >\fP"
.br
.ti -1c
.RI "struct \fBstd::less< DirectX::SimpleMath::Viewport >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDirectX\fP"
.br
.ti -1c
.RI "namespace \fBDirectX::SimpleMath\fP"
.br
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBVector2\fP \fBDirectX::SimpleMath::operator+\fP (const \fBVector2\fP &V1, const \fBVector2\fP &V2) noexcept"
.br
.ti -1c
.RI "\fBVector2\fP \fBDirectX::SimpleMath::operator\-\fP (const \fBVector2\fP &V1, const \fBVector2\fP &V2) noexcept"
.br
.ti -1c
.RI "\fBVector2\fP \fBDirectX::SimpleMath::operator*\fP (const \fBVector2\fP &V1, const \fBVector2\fP &V2) noexcept"
.br
.ti -1c
.RI "\fBVector2\fP \fBDirectX::SimpleMath::operator*\fP (const \fBVector2\fP &\fBV\fP, float \fBS\fP) noexcept"
.br
.ti -1c
.RI "\fBVector2\fP \fBDirectX::SimpleMath::operator/\fP (const \fBVector2\fP &V1, const \fBVector2\fP &V2) noexcept"
.br
.ti -1c
.RI "\fBVector2\fP \fBDirectX::SimpleMath::operator/\fP (const \fBVector2\fP &\fBV\fP, float \fBS\fP) noexcept"
.br
.ti -1c
.RI "\fBVector2\fP \fBDirectX::SimpleMath::operator*\fP (float \fBS\fP, const \fBVector2\fP &\fBV\fP) noexcept"
.br
.ti -1c
.RI "\fBVector3\fP \fBDirectX::SimpleMath::operator+\fP (const \fBVector3\fP &V1, const \fBVector3\fP &V2) noexcept"
.br
.ti -1c
.RI "\fBVector3\fP \fBDirectX::SimpleMath::operator\-\fP (const \fBVector3\fP &V1, const \fBVector3\fP &V2) noexcept"
.br
.ti -1c
.RI "\fBVector3\fP \fBDirectX::SimpleMath::operator*\fP (const \fBVector3\fP &V1, const \fBVector3\fP &V2) noexcept"
.br
.ti -1c
.RI "\fBVector3\fP \fBDirectX::SimpleMath::operator*\fP (const \fBVector3\fP &\fBV\fP, float \fBS\fP) noexcept"
.br
.ti -1c
.RI "\fBVector3\fP \fBDirectX::SimpleMath::operator/\fP (const \fBVector3\fP &V1, const \fBVector3\fP &V2) noexcept"
.br
.ti -1c
.RI "\fBVector3\fP \fBDirectX::SimpleMath::operator/\fP (const \fBVector3\fP &\fBV\fP, float \fBS\fP) noexcept"
.br
.ti -1c
.RI "\fBVector3\fP \fBDirectX::SimpleMath::operator*\fP (float \fBS\fP, const \fBVector3\fP &\fBV\fP) noexcept"
.br
.ti -1c
.RI "\fBVector4\fP \fBDirectX::SimpleMath::operator+\fP (const \fBVector4\fP &V1, const \fBVector4\fP &V2) noexcept"
.br
.ti -1c
.RI "\fBVector4\fP \fBDirectX::SimpleMath::operator\-\fP (const \fBVector4\fP &V1, const \fBVector4\fP &V2) noexcept"
.br
.ti -1c
.RI "\fBVector4\fP \fBDirectX::SimpleMath::operator*\fP (const \fBVector4\fP &V1, const \fBVector4\fP &V2) noexcept"
.br
.ti -1c
.RI "\fBVector4\fP \fBDirectX::SimpleMath::operator*\fP (const \fBVector4\fP &\fBV\fP, float \fBS\fP) noexcept"
.br
.ti -1c
.RI "\fBVector4\fP \fBDirectX::SimpleMath::operator/\fP (const \fBVector4\fP &V1, const \fBVector4\fP &V2) noexcept"
.br
.ti -1c
.RI "\fBVector4\fP \fBDirectX::SimpleMath::operator/\fP (const \fBVector4\fP &\fBV\fP, float \fBS\fP) noexcept"
.br
.ti -1c
.RI "\fBVector4\fP \fBDirectX::SimpleMath::operator*\fP (float \fBS\fP, const \fBVector4\fP &\fBV\fP) noexcept"
.br
.ti -1c
.RI "\fBMatrix\fP \fBDirectX::SimpleMath::operator+\fP (const \fBMatrix\fP &M1, const \fBMatrix\fP &M2) noexcept"
.br
.ti -1c
.RI "\fBMatrix\fP \fBDirectX::SimpleMath::operator\-\fP (const \fBMatrix\fP &M1, const \fBMatrix\fP &M2) noexcept"
.br
.ti -1c
.RI "\fBMatrix\fP \fBDirectX::SimpleMath::operator*\fP (const \fBMatrix\fP &M1, const \fBMatrix\fP &M2) noexcept"
.br
.ti -1c
.RI "\fBMatrix\fP \fBDirectX::SimpleMath::operator*\fP (const \fBMatrix\fP &\fBM\fP, float \fBS\fP) noexcept"
.br
.ti -1c
.RI "\fBMatrix\fP \fBDirectX::SimpleMath::operator/\fP (const \fBMatrix\fP &\fBM\fP, float \fBS\fP) noexcept"
.br
.ti -1c
.RI "\fBMatrix\fP \fBDirectX::SimpleMath::operator/\fP (const \fBMatrix\fP &M1, const \fBMatrix\fP &M2) noexcept"
.br
.ti -1c
.RI "\fBMatrix\fP \fBDirectX::SimpleMath::operator*\fP (float \fBS\fP, const \fBMatrix\fP &\fBM\fP) noexcept"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBDirectX::SimpleMath::operator+\fP (const \fBQuaternion\fP &Q1, const \fBQuaternion\fP &Q2) noexcept"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBDirectX::SimpleMath::operator\-\fP (const \fBQuaternion\fP &Q1, const \fBQuaternion\fP &Q2) noexcept"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBDirectX::SimpleMath::operator*\fP (const \fBQuaternion\fP &Q1, const \fBQuaternion\fP &Q2) noexcept"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBDirectX::SimpleMath::operator*\fP (const \fBQuaternion\fP &\fBQ\fP, float \fBS\fP) noexcept"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBDirectX::SimpleMath::operator/\fP (const \fBQuaternion\fP &Q1, const \fBQuaternion\fP &Q2) noexcept"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBDirectX::SimpleMath::operator*\fP (float \fBS\fP, const \fBQuaternion\fP &\fBQ\fP) noexcept"
.br
.ti -1c
.RI "\fBColor\fP \fBDirectX::SimpleMath::operator+\fP (const \fBColor\fP &C1, const \fBColor\fP &C2) noexcept"
.br
.ti -1c
.RI "\fBColor\fP \fBDirectX::SimpleMath::operator\-\fP (const \fBColor\fP &C1, const \fBColor\fP &C2) noexcept"
.br
.ti -1c
.RI "\fBColor\fP \fBDirectX::SimpleMath::operator*\fP (const \fBColor\fP &C1, const \fBColor\fP &C2) noexcept"
.br
.ti -1c
.RI "\fBColor\fP \fBDirectX::SimpleMath::operator*\fP (const \fBColor\fP &\fBC\fP, float \fBS\fP) noexcept"
.br
.ti -1c
.RI "\fBColor\fP \fBDirectX::SimpleMath::operator/\fP (const \fBColor\fP &C1, const \fBColor\fP &C2) noexcept"
.br
.ti -1c
.RI "\fBColor\fP \fBDirectX::SimpleMath::operator*\fP (float \fBS\fP, const \fBColor\fP &\fBC\fP) noexcept"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
