.TH "adhed/assimp/SkeletonMeshBuilder.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/assimp/SkeletonMeshBuilder.h
.SH SYNOPSIS
.br
.PP
\fR#include <assimp/mesh\&.h>\fP
.br
\fR#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAssimp::SkeletonMeshBuilder\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAssimp\fP"
.br
.RI "Some C++ utilities for inter- and extrapolation\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAI_SKELETONMESHBUILDER_H_INC\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helper class to construct a dummy mesh for file formats containing only motion data
.PP
Declares SkeletonMeshBuilder, a tiny utility to build dummy meshes for animation skeletons\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define AI_SKELETONMESHBUILDER_H_INC"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
