.TH "packages/directxtk12_uwp.2024.6.5.1/include/SpriteBatch.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/directxtk12_uwp.2024.6.5.1/include/SpriteBatch.h
.SH SYNOPSIS
.br
.PP
\fR#include <d3d12\&.h>\fP
.br
\fR#include <dxgi1_4\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <DirectXMath\&.h>\fP
.br
\fR#include <DirectXColors\&.h>\fP
.br
\fR#include 'RenderTargetState\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDirectX::DX12::SpriteBatchPipelineStateDescription\fP"
.br
.ti -1c
.RI "class \fBDirectX::DX12::SpriteBatch\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDirectX\fP"
.br
.ti -1c
.RI "namespace \fBDirectX::DX12\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDirectX::DX12::SpriteSortMode\fP { \fBDirectX::DX12::SpriteSortMode_Deferred\fP, \fBDirectX::DX12::SpriteSortMode_Immediate\fP, \fBDirectX::DX12::SpriteSortMode_Texture\fP, \fBDirectX::DX12::SpriteSortMode_BackToFront\fP, \fBDirectX::DX12::SpriteSortMode_FrontToBack\fP, \fBDirectX::DX12::SpriteSortMode_Deferred\fP, \fBDirectX::DX12::SpriteSortMode_Immediate\fP, \fBDirectX::DX12::SpriteSortMode_Texture\fP, \fBDirectX::DX12::SpriteSortMode_BackToFront\fP, \fBDirectX::DX12::SpriteSortMode_FrontToBack\fP }"
.br
.ti -1c
.RI "enum \fBDirectX::DX12::SpriteEffects\fP : uint32_t { \fBDirectX::DX12::SpriteEffects_None\fP = 0, \fBDirectX::DX12::SpriteEffects_FlipHorizontally\fP = 1, \fBDirectX::DX12::SpriteEffects_FlipVertically\fP = 2, \fBDirectX::DX12::SpriteEffects_FlipBoth\fP = SpriteEffects_FlipHorizontally | SpriteEffects_FlipVertically, \fBDirectX::DX12::SpriteEffects_None\fP = 0, \fBDirectX::DX12::SpriteEffects_FlipHorizontally\fP = 1, \fBDirectX::DX12::SpriteEffects_FlipVertically\fP = 2, \fBDirectX::DX12::SpriteEffects_FlipBoth\fP = SpriteEffects_FlipHorizontally | SpriteEffects_FlipVertically }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
