.TH "adhed/libbacktrace/state.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/libbacktrace/state.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <sys/types\&.h>\fP
.br
\fR#include 'backtrace\&.hpp'\fP
.br
\fR#include 'internal\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstruct\fP \fBbacktrace_state\fP * \fBtracy::backtrace_create_state\fP (const char *filename, int threaded, \fBbacktrace_error_callback\fP error_callback, \fBvoid\fP *\fBdata\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
