.TH "stbi_io_callbacks" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbi_io_callbacks
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stb_image\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int(* \fBread\fP )(\fBvoid\fP *user, char *\fBdata\fP, int \fBsize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBskip\fP )(\fBvoid\fP *user, int n)"
.br
.ti -1c
.RI "int(* \fBeof\fP )(\fBvoid\fP *user)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int(* stbi_io_callbacks::eof) (\fBvoid\fP *user)"

.SS "int(* stbi_io_callbacks::read) (\fBvoid\fP *user, char *\fBdata\fP, int \fBsize\fP)"

.SS "\fBvoid\fP(* stbi_io_callbacks::skip) (\fBvoid\fP *user, int n)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
