.TH "adhed/glm/gtx/string_cast.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/string_cast.inl
.SH SYNOPSIS
.br
.PP
\fR#include <cstdarg>\fP
.br
\fR#include <cstdio>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBglm::detail::cast< T >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::cast< float >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::literal< T, isFloat >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::literal< T, true >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::prefix< T >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::prefix< float >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::prefix< double >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::prefix< bool >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::prefix< uint8_t >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::prefix< int8_t >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::prefix< uint16_t >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::prefix< int16_t >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::prefix< uint32_t >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::prefix< int32_t >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::prefix< uint64_t >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::prefix< int64_t >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< matType >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< vec< 1, bool, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< vec< 2, bool, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< vec< 3, bool, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< vec< 4, bool, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< vec< 1, T, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< vec< 2, T, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< vec< 3, T, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< vec< 4, T, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< mat< 2, 2, T, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< mat< 2, 3, T, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< mat< 2, 4, T, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< mat< 3, 2, T, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< mat< 3, 3, T, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< mat< 3, 4, T, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< mat< 4, 2, T, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< mat< 4, 3, T, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< mat< 4, 4, T, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< qua< T, Q > >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_to_string< tdualquat< T, Q > >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.ti -1c
.RI "namespace \fBglm::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGLM_FUNC_QUALIFIER\fP std::string \fBglm::detail::format\fP (const char *message,\&.\&.\&.)"
.br
.ti -1c
.RI "template<class matType > \fBGLM_FUNC_QUALIFIER\fP std::string \fBglm::to_string\fP (matType const &\fBx\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
