.TH "adhed/assimp/StringUtils.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/assimp/StringUtils.h
.SH SYNOPSIS
.br
.PP
\fR#include <assimp/defs\&.h>\fP
.br
\fR#include <cstdarg>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <cctype>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include <locale>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <iomanip>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINCLUDED_AI_STRINGUTILS_H\fP"
.br
.ti -1c
.RI "#define \fBAI_SIZEFMT\fP   '%zu'"
.br
.ti -1c
.RI "#define \fBai_snprintf\fP   snprintf"
.br
.RI "The portable version of the function snprintf ( C99 standard ), which works on visual studio compilers 2013 and earlier\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP > \fBAI_FORCE_INLINE\fP \fBstd::string\fP \fBai_to_string\fP (\fBT\fP \fBvalue\fP)"
.br
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP float \fBai_strtof\fP (const char *begin, const char *\fBend\fP)"
.br
.ti -1c
.RI "template<class \fBT\fP > \fBAI_FORCE_INLINE\fP \fBstd::string\fP \fBai_decimal_to_hexa\fP (\fBT\fP toConvert)"
.br
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP \fBstd::string\fP \fBai_rgba2hex\fP (int \fBr\fP, int \fBg\fP, int \fBb\fP, int \fBa\fP, bool with_head)"
.br
.RI "translate RGBA to String "
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP \fBvoid\fP \fBai_trim_left\fP (\fBstd::string\fP &s)"
.br
.RI "Performs a trim from start (in place) "
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP \fBvoid\fP \fBai_trim_right\fP (\fBstd::string\fP &s)"
.br
.RI "Performs a trim from end (in place)\&. "
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP \fBstd::string\fP \fBai_trim\fP (\fBstd::string\fP &s)"
.br
.RI "Performs a trim from both ends (in place)\&. "
.ti -1c
.RI "template<class char_t > \fBAI_FORCE_INLINE\fP char_t \fBai_tolower\fP (char_t in)"
.br
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP \fBstd::string\fP \fBai_tolower\fP (const \fBstd::string\fP &in)"
.br
.RI "Performs a ToLower-operation and return the lower-case string\&. "
.ti -1c
.RI "template<class char_t > \fBAI_FORCE_INLINE\fP char_t \fBai_toupper\fP (char_t in)"
.br
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP \fBstd::string\fP \fBai_str_toupper\fP (const \fBstd::string\fP &in)"
.br
.RI "Performs a ToLower-operation and return the upper-case string\&. "
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP \fBstd::string\fP \fBai_str_toprintable\fP (const \fBstd::string\fP &in, char placeholder='?')"
.br
.RI "Make a string printable by replacing all non-printable characters with the specified placeholder character\&. "
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP \fBstd::string\fP \fBai_str_toprintable\fP (const char *in, int len, char placeholder='?')"
.br
.RI "Make a string printable by replacing all non-printable characters with the specified placeholder character\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AI_SIZEFMT   '%zu'"

.SS "#define ai_snprintf   snprintf"

.PP
The portable version of the function snprintf ( C99 standard ), which works on visual studio compilers 2013 and earlier\&. 
.PP
\fBParameters\fP
.RS 4
\fIoutBuf\fP The buffer to write in 
.br
\fIsize\fP The buffer size 
.br
\fIformat\fP The format string 
.br
\fIap\fP The additional arguments\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The number of written characters if the buffer size was big enough\&. If an encoding error occurs, a negative number is returned\&. 
.RE
.PP

.SS "#define INCLUDED_AI_STRINGUTILS_H"

.SH "Function Documentation"
.PP 
.SS "template<class \fBT\fP > \fBAI_FORCE_INLINE\fP \fBstd::string\fP ai_decimal_to_hexa (\fBT\fP toConvert)"

.SS "\fBAI_FORCE_INLINE\fP \fBstd::string\fP ai_rgba2hex (int r, int g, int b, int a, bool with_head)"

.PP
translate RGBA to String 
.PP
\fBParameters\fP
.RS 4
\fIr\fP aiColor\&.r 
.br
\fIg\fP aiColor\&.g 
.br
\fIb\fP aiColor\&.b 
.br
\fIa\fP aiColor\&.a 
.br
\fIwith_head\fP # 
.RE
.PP
\fBReturns\fP
.RS 4
The hexadecimal string, is empty in case of an error\&. 
.RE
.PP

.SS "\fBAI_FORCE_INLINE\fP \fBstd::string\fP ai_str_toprintable (const char * in, int len, char placeholder = \fR'?'\fP)"

.PP
Make a string printable by replacing all non-printable characters with the specified placeholder character\&. 
.PP
\fBParameters\fP
.RS 4
\fIin\fP The incoming string\&. 
.br
\fIlen\fP The length of the incoming string\&. 
.br
\fIplaceholder\fP Placeholder character, default is a question mark\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The string, with all non-printable characters replaced\&. Will return an empty string if in is null or len is <= 0\&. 
.RE
.PP

.SS "\fBAI_FORCE_INLINE\fP \fBstd::string\fP ai_str_toprintable (const \fBstd::string\fP & in, char placeholder = \fR'?'\fP)"

.PP
Make a string printable by replacing all non-printable characters with the specified placeholder character\&. 
.PP
\fBParameters\fP
.RS 4
\fIin\fP The incoming string\&. 
.br
\fIplaceholder\fP Placeholder character, default is a question mark\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The string, with all non-printable characters replaced\&. 
.RE
.PP

.SS "\fBAI_FORCE_INLINE\fP \fBstd::string\fP ai_str_toupper (const \fBstd::string\fP & in)"

.PP
Performs a ToLower-operation and return the upper-case string\&. 
.PP
\fBParameters\fP
.RS 4
\fIin\fP The incoming string\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The string as uppercase\&. 
.RE
.PP

.SS "\fBAI_FORCE_INLINE\fP float ai_strtof (const char * begin, const char * end)"

.SS "template<typename \fBT\fP > \fBAI_FORCE_INLINE\fP \fBstd::string\fP ai_to_string (\fBT\fP value)"

.SS "template<class char_t > \fBAI_FORCE_INLINE\fP char_t ai_tolower (char_t in)"

.SS "\fBAI_FORCE_INLINE\fP \fBstd::string\fP ai_tolower (const \fBstd::string\fP & in)"

.PP
Performs a ToLower-operation and return the lower-case string\&. 
.PP
\fBParameters\fP
.RS 4
\fIin\fP The incoming string\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The string as lowercase\&. 
.RE
.PP

.SS "template<class char_t > \fBAI_FORCE_INLINE\fP char_t ai_toupper (char_t in)"

.SS "\fBAI_FORCE_INLINE\fP \fBstd::string\fP ai_trim (\fBstd::string\fP & s)"

.PP
Performs a trim from both ends (in place)\&. 
.PP
\fBParameters\fP
.RS 4
\fIs\fP string to trim\&. 
.RE
.PP

.SS "\fBAI_FORCE_INLINE\fP \fBvoid\fP ai_trim_left (\fBstd::string\fP & s)"

.PP
Performs a trim from start (in place) 
.PP
\fBParameters\fP
.RS 4
\fIs\fP string to trim\&. 
.RE
.PP

.SS "\fBAI_FORCE_INLINE\fP \fBvoid\fP ai_trim_right (\fBstd::string\fP & s)"

.PP
Performs a trim from end (in place)\&. 
.PP
\fBParameters\fP
.RS 4
\fIs\fP string to trim\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
