.TH "struct" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
struct
.SH SYNOPSIS
.br
.PP
.PP
\fRimport <d3d12\&.idl;\fP
.PP
Inherits \fBID3D12DeviceChild\fP, \fBID3D12GraphicsCommandList\fP, IUnknown, ID3D12StateObjectProperties, IUnknown, ID3D12GraphicsCommandList4, \fBID3D12CommandList\fP, \fBID3D12VideoDecodeCommandList\fP, \fBID3D12Pageable\fP, and \fBID3D12VideoDevice\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBAtomicCopyBufferUINT\fP ([annotation('_In_')] \fBID3D12Resource\fP *pDstBuffer, UINT64 DstOffset, [annotation('_In_')] \fBID3D12Resource\fP *pSrcBuffer, UINT64 SrcOffset, UINT Dependencies, [annotation('_In_reads_(Dependencies)')] ID3D12Resource *const *ppDependentResources, [annotation('_In_reads_(Dependencies)')] const \fBD3D12_SUBRESOURCE_RANGE_UINT64\fP *pDependentSubresourceRanges)"
.br
.ti -1c
.RI "\fBvoid\fP \fBAtomicCopyBufferUINT64\fP ([annotation('_In_')] \fBID3D12Resource\fP *pDstBuffer, UINT64 DstOffset, [annotation('_In_')] \fBID3D12Resource\fP *pSrcBuffer, UINT64 SrcOffset, UINT Dependencies, [annotation('_In_reads_(Dependencies)')] ID3D12Resource *const *ppDependentResources, [annotation('_In_reads_(Dependencies)')] const \fBD3D12_SUBRESOURCE_RANGE_UINT64\fP *pDependentSubresourceRanges)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOMSetDepthBounds\fP ([annotation('_In_')] FLOAT Min, [annotation('_In_')] FLOAT Max)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetSamplePositions\fP ([annotation('_In_')] UINT NumSamplesPerPixel, [annotation('_In_')] UINT NumPixels, [annotation('_In_reads_(NumSamplesPerPixel*NumPixels)')] D3D12_SAMPLE_POSITION *pSamplePositions)"
.br
.ti -1c
.RI "\fBvoid\fP \fBResolveSubresourceRegion\fP ([annotation('_In_')] \fBID3D12Resource\fP *pDstResource, [annotation('_In_')] UINT DstSubresource, [annotation('_In_')] UINT DstX, [annotation('_In_')] UINT DstY, [annotation('_In_')] \fBID3D12Resource\fP *pSrcResource, [annotation('_In_')] UINT SrcSubresource, [annotation('_In_opt_')] \fBD3D12_RECT\fP *pSrcRect, [annotation('_In_')] \fBDXGI_FORMAT\fP Format, [annotation('_In_')] \fBD3D12_RESOLVE_MODE\fP ResolveMode)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetViewInstanceMask\fP ([annotation('_In_')] UINT Mask)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBGetShaderIdentifier\fP ([annotation('_In_')] LPCWSTR pExportName)"
.br
.ti -1c
.RI "UINT64 \fBGetShaderStackSize\fP ([annotation('_In_')] LPCWSTR pExportName)"
.br
.ti -1c
.RI "UINT64 \fBGetPipelineStackSize\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetPipelineStackSize\fP (UINT64 PipelineStackSizeInBytes)"
.br
.ti -1c
.RI "\fBD3D12_PROGRAM_IDENTIFIER\fP \fBGetProgramIdentifier\fP (LPCWSTR pProgramName)"
.br
.ti -1c
.RI "\fBvoid\fP \fBEnableShaderInstrumentation\fP (BOOL bEnable)"
.br
.ti -1c
.RI "BOOL \fBShaderInstrumentationEnabled\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBRSSetShadingRate\fP ([annotation('_In_')] \fBD3D12_SHADING_RATE\fP baseShadingRate, [annotation('_In_reads_opt_(\fBD3D12_RS_SET_SHADING_RATE_COMBINER_COUNT\fP)')] const \fBD3D12_SHADING_RATE_COMBINER\fP *combiners)"
.br
.ti -1c
.RI "\fBvoid\fP \fBRSSetShadingRateImage\fP ([annotation('_In_opt_')] \fBID3D12Resource\fP *shadingRateImage)"
.br
.ti -1c
.RI "HRESULT \fBClose\fP ()"
.br
.ti -1c
.RI "HRESULT \fBReset\fP ([annotation('_In_')] \fBID3D12CommandAllocator\fP *pAllocator)"
.br
.ti -1c
.RI "\fBvoid\fP \fBClearState\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBResourceBarrier\fP ([annotation('_In_')] UINT NumBarriers, [annotation('_In_reads_(NumBarriers)')] const \fBD3D12_RESOURCE_BARRIER\fP *pBarriers)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDiscardResource\fP ([annotation('_In_')] \fBID3D12Resource\fP *pResource, [annotation('_In_opt_')] const \fBD3D12_DISCARD_REGION\fP *pRegion)"
.br
.ti -1c
.RI "\fBvoid\fP \fBBeginQuery\fP ([annotation('_In_')] \fBID3D12QueryHeap\fP *pQueryHeap, [annotation('_In_')] \fBD3D12_QUERY_TYPE\fP Type, [annotation('_In_')] UINT Index)"
.br
.ti -1c
.RI "\fBvoid\fP \fBEndQuery\fP ([annotation('_In_')] \fBID3D12QueryHeap\fP *pQueryHeap, [annotation('_In_')] \fBD3D12_QUERY_TYPE\fP Type, [annotation('_In_')] UINT Index)"
.br
.ti -1c
.RI "\fBvoid\fP \fBResolveQueryData\fP ([annotation('_In_')] \fBID3D12QueryHeap\fP *pQueryHeap, [annotation('_In_')] \fBD3D12_QUERY_TYPE\fP Type, [annotation('_In_')] UINT StartIndex, [annotation('_In_')] UINT NumQueries, [annotation('_In_')] \fBID3D12Resource\fP *pDestinationBuffer, [annotation('_In_')] UINT64 AlignedDestinationBufferOffset)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetPredication\fP ([annotation('_In_opt_')] \fBID3D12Resource\fP *\fBpBuffer\fP, [annotation('_In_')] UINT64 AlignedBufferOffset, [annotation('_In_')] \fBD3D12_PREDICATION_OP\fP Operation)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetMarker\fP (UINT Metadata, [annotation('_In_reads_bytes_opt_(Size)')] const \fBvoid\fP *pData, UINT Size)"
.br
.ti -1c
.RI "\fBvoid\fP \fBBeginEvent\fP (UINT Metadata, [annotation('_In_reads_bytes_opt_(Size)')] const \fBvoid\fP *pData, UINT Size)"
.br
.ti -1c
.RI "\fBvoid\fP \fBEndEvent\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBProcessFrames\fP ([annotation('_In_')] \fBID3D12VideoProcessor\fP *pVideoProcessor, [annotation('_In_')] const \fBD3D12_VIDEO_PROCESS_OUTPUT_STREAM_ARGUMENTS\fP *pOutputArguments, UINT NumInputStreams, [annotation('_In_reads_(NumInputStreams)')] const \fBD3D12_VIDEO_PROCESS_INPUT_STREAM_ARGUMENTS\fP *pInputArguments)"
.br
.ti -1c
.RI "\fBvoid\fP \fBWriteBufferImmediate\fP (UINT Count, [annotation('_In_reads_(Count)')] const \fBD3D12_WRITEBUFFERIMMEDIATE_PARAMETER\fP *pParams, [annotation('_In_reads_opt_(Count)')] const \fBD3D12_WRITEBUFFERIMMEDIATE_MODE\fP *pModes)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDecodeFrame1\fP ([annotation('_In_')] \fBID3D12VideoDecoder\fP *pDecoder, [annotation('_In_')] const \fBD3D12_VIDEO_DECODE_OUTPUT_STREAM_ARGUMENTS1\fP *pOutputArguments, [annotation('_In_')] const \fBD3D12_VIDEO_DECODE_INPUT_STREAM_ARGUMENTS\fP *pInputArguments)"
.br
.ti -1c
.RI "\fBD3D12_VIDEO_MOTION_ESTIMATOR_DESC\fP \fBGetDesc\fP ()"
.br
.ti -1c
.RI "HRESULT \fBGetProtectedResourceSession\fP ([in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_opt_')] \fBvoid\fP **ppProtectedSession)"
.br
.ti -1c
.RI "HRESULT \fBCreateVideoMotionEstimator\fP ([annotation('_In_')] const \fBD3D12_VIDEO_MOTION_ESTIMATOR_DESC\fP *pDesc, [annotation('_In_opt_')] \fBID3D12ProtectedResourceSession\fP *pProtectedResourceSession, [annotation('_In_')] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppVideoMotionEstimator)"
.br
.ti -1c
.RI "HRESULT \fBCreateVideoMotionVectorHeap\fP ([annotation('_In_')] const \fBD3D12_VIDEO_MOTION_VECTOR_HEAP_DESC\fP *pDesc, [annotation('_In_opt_')] \fBID3D12ProtectedResourceSession\fP *pProtectedResourceSession, [annotation('_In_')] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppVideoMotionVectorHeap)"
.br
.in -1c

Public Member Functions inherited from \fBID3D12DeviceChild\fP
.in +1c
.ti -1c
.RI "HRESULT \fBGetDevice\fP ([in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_opt_')] \fBvoid\fP **ppvDevice)"
.br
.in -1c

Public Member Functions inherited from \fBID3D12Object\fP
.in +1c
.ti -1c
.RI "HRESULT \fBGetPrivateData\fP ([annotation('_In_')] REFGUID guid, [annotation('_Inout_')] UINT *pDataSize, [annotation('_Out_writes_bytes_opt_( *pDataSize )')] void *pData)"
.br
.ti -1c
.RI "HRESULT \fBSetPrivateData\fP ([annotation('_In_')] REFGUID guid, [annotation('_In_')] UINT DataSize, [annotation('_In_reads_bytes_opt_( DataSize )')] const \fBvoid\fP *pData)"
.br
.ti -1c
.RI "HRESULT \fBSetPrivateDataInterface\fP ([annotation('_In_')] REFGUID guid, [annotation('_In_opt_')] const IUnknown *pData)"
.br
.ti -1c
.RI "HRESULT \fBSetName\fP ([annotation('_In_z_')] LPCWSTR Name)"
.br
.in -1c

Public Member Functions inherited from \fBID3D12GraphicsCommandList\fP
.in +1c
.ti -1c
.RI "HRESULT \fBReset\fP ([annotation('_In_')] \fBID3D12CommandAllocator\fP *pAllocator, [annotation('_In_opt_')] \fBID3D12PipelineState\fP *pInitialState)"
.br
.ti -1c
.RI "\fBvoid\fP \fBClearState\fP ([annotation('_In_opt_')] \fBID3D12PipelineState\fP *pPipelineState)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDrawInstanced\fP ([annotation('_In_')] UINT VertexCountPerInstance, [annotation('_In_')] UINT InstanceCount, [annotation('_In_')] UINT StartVertexLocation, [annotation('_In_')] UINT StartInstanceLocation)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDrawIndexedInstanced\fP ([annotation('_In_')] UINT IndexCountPerInstance, [annotation('_In_')] UINT InstanceCount, [annotation('_In_')] UINT StartIndexLocation, [annotation('_In_')] INT BaseVertexLocation, [annotation('_In_')] UINT StartInstanceLocation)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDispatch\fP ([annotation('_In_')] UINT ThreadGroupCountX, [annotation('_In_')] UINT \fBThreadGroupCountY\fP, [annotation('_In_')] UINT \fBThreadGroupCountZ\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCopyBufferRegion\fP ([annotation('_In_')] \fBID3D12Resource\fP *pDstBuffer, UINT64 DstOffset, [annotation('_In_')] \fBID3D12Resource\fP *pSrcBuffer, UINT64 SrcOffset, UINT64 NumBytes)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCopyTextureRegion\fP ([annotation('_In_')] const \fBD3D12_TEXTURE_COPY_LOCATION\fP *pDst, UINT DstX, UINT DstY, UINT DstZ, [annotation('_In_')] const \fBD3D12_TEXTURE_COPY_LOCATION\fP *pSrc, [annotation('_In_opt_')] const \fBD3D12_BOX\fP *pSrcBox)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCopyResource\fP ([annotation('_In_')] \fBID3D12Resource\fP *pDstResource, [annotation('_In_')] \fBID3D12Resource\fP *pSrcResource)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCopyTiles\fP ([annotation('_In_')] \fBID3D12Resource\fP *pTiledResource, [annotation('_In_')] const \fBD3D12_TILED_RESOURCE_COORDINATE\fP *pTileRegionStartCoordinate, [annotation('_In_')] const \fBD3D12_TILE_REGION_SIZE\fP *pTileRegionSize, [annotation('_In_')] \fBID3D12Resource\fP *\fBpBuffer\fP, UINT64 BufferStartOffsetInBytes, \fBD3D12_TILE_COPY_FLAGS\fP \fBFlags\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBResolveSubresource\fP ([annotation('_In_')] \fBID3D12Resource\fP *pDstResource, [annotation('_In_')] UINT DstSubresource, [annotation('_In_')] \fBID3D12Resource\fP *pSrcResource, [annotation('_In_')] UINT SrcSubresource, [annotation('_In_')] \fBDXGI_FORMAT\fP Format)"
.br
.ti -1c
.RI "\fBvoid\fP \fBIASetPrimitiveTopology\fP ([annotation('_In_')] \fBD3D12_PRIMITIVE_TOPOLOGY\fP PrimitiveTopology)"
.br
.ti -1c
.RI "\fBvoid\fP \fBRSSetViewports\fP ([annotation('_In_range_(0, \fBD3D12_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE\fP)')] UINT NumViewports, [annotation('_In_reads_( NumViewports)')] const \fBD3D12_VIEWPORT\fP *pViewports)"
.br
.ti -1c
.RI "\fBvoid\fP \fBRSSetScissorRects\fP ([annotation('_In_range_(0, \fBD3D12_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE\fP)')] UINT NumRects, [annotation('_In_reads_( NumRects)')] const \fBD3D12_RECT\fP *pRects)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOMSetBlendFactor\fP ([annotation('_In_reads_opt_(4)')] const FLOAT BlendFactor[4])"
.br
.ti -1c
.RI "\fBvoid\fP \fBOMSetStencilRef\fP ([annotation('_In_')] UINT StencilRef)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetPipelineState\fP ([annotation('_In_')] \fBID3D12PipelineState\fP *pPipelineState)"
.br
.ti -1c
.RI "\fBvoid\fP \fBExecuteBundle\fP ([annotation('_In_')] \fBID3D12GraphicsCommandList\fP *pCommandList)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetDescriptorHeaps\fP ([annotation('_In_')] UINT NumDescriptorHeaps, [annotation('_In_reads_(NumDescriptorHeaps)')] ID3D12DescriptorHeap *const *ppDescriptorHeaps)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetComputeRootSignature\fP ([annotation('_In_opt_')] \fBID3D12RootSignature\fP *pRootSignature)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetGraphicsRootSignature\fP ([annotation('_In_opt_')] \fBID3D12RootSignature\fP *pRootSignature)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetComputeRootDescriptorTable\fP ([annotation('_In_')] UINT RootParameterIndex, [annotation('_In_')] \fBD3D12_GPU_DESCRIPTOR_HANDLE\fP BaseDescriptor)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetGraphicsRootDescriptorTable\fP ([annotation('_In_')] UINT RootParameterIndex, [annotation('_In_')] \fBD3D12_GPU_DESCRIPTOR_HANDLE\fP BaseDescriptor)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetComputeRoot32BitConstant\fP ([annotation('_In_')] UINT RootParameterIndex, [annotation('_In_')] UINT SrcData, [annotation('_In_')] UINT DestOffsetIn32BitValues)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetGraphicsRoot32BitConstant\fP ([annotation('_In_')] UINT RootParameterIndex, [annotation('_In_')] UINT SrcData, [annotation('_In_')] UINT DestOffsetIn32BitValues)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetComputeRoot32BitConstants\fP ([annotation('_In_')] UINT RootParameterIndex, [annotation('_In_')] UINT Num32BitValuesToSet, [annotation('_In_reads_(Num32BitValuesToSet*sizeof(UINT))')] const \fBvoid\fP *pSrcData, [annotation('_In_')] UINT DestOffsetIn32BitValues)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetGraphicsRoot32BitConstants\fP ([annotation('_In_')] UINT RootParameterIndex, [annotation('_In_')] UINT Num32BitValuesToSet, [annotation('_In_reads_(Num32BitValuesToSet*sizeof(UINT))')] const \fBvoid\fP *pSrcData, [annotation('_In_')] UINT DestOffsetIn32BitValues)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetComputeRootConstantBufferView\fP ([annotation('_In_')] UINT RootParameterIndex, [annotation('_In_')] \fBD3D12_GPU_VIRTUAL_ADDRESS\fP BufferLocation)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetGraphicsRootConstantBufferView\fP ([annotation('_In_')] UINT RootParameterIndex, [annotation('_In_')] \fBD3D12_GPU_VIRTUAL_ADDRESS\fP BufferLocation)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetComputeRootShaderResourceView\fP ([annotation('_In_')] UINT RootParameterIndex, [annotation('_In_')] \fBD3D12_GPU_VIRTUAL_ADDRESS\fP BufferLocation)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetGraphicsRootShaderResourceView\fP ([annotation('_In_')] UINT RootParameterIndex, [annotation('_In_')] \fBD3D12_GPU_VIRTUAL_ADDRESS\fP BufferLocation)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetComputeRootUnorderedAccessView\fP ([annotation('_In_')] UINT RootParameterIndex, [annotation('_In_')] \fBD3D12_GPU_VIRTUAL_ADDRESS\fP BufferLocation)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetGraphicsRootUnorderedAccessView\fP ([annotation('_In_')] UINT RootParameterIndex, [annotation('_In_')] \fBD3D12_GPU_VIRTUAL_ADDRESS\fP BufferLocation)"
.br
.ti -1c
.RI "\fBvoid\fP \fBIASetIndexBuffer\fP ([annotation('_In_opt_')] const \fBD3D12_INDEX_BUFFER_VIEW\fP *pView)"
.br
.ti -1c
.RI "\fBvoid\fP \fBIASetVertexBuffers\fP ([annotation('_In_')] UINT StartSlot, [annotation('_In_')] UINT NumViews, [annotation('_In_reads_opt_(NumViews)')] const \fBD3D12_VERTEX_BUFFER_VIEW\fP *pViews)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSOSetTargets\fP ([annotation('_In_')] UINT StartSlot, [annotation('_In_')] UINT NumViews, [annotation('_In_reads_opt_(NumViews)')] const \fBD3D12_STREAM_OUTPUT_BUFFER_VIEW\fP *pViews)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOMSetRenderTargets\fP ([annotation('_In_')] UINT NumRenderTargetDescriptors, [annotation('_In_opt_')] const \fBD3D12_CPU_DESCRIPTOR_HANDLE\fP *pRenderTargetDescriptors, [annotation('_In_')] BOOL RTsSingleHandleToDescriptorRange, [annotation('_In_opt_')] const \fBD3D12_CPU_DESCRIPTOR_HANDLE\fP *pDepthStencilDescriptor)"
.br
.ti -1c
.RI "\fBvoid\fP \fBClearDepthStencilView\fP ([annotation('_In_')] \fBD3D12_CPU_DESCRIPTOR_HANDLE\fP DepthStencilView, [annotation('_In_')] \fBD3D12_CLEAR_FLAGS\fP ClearFlags, [annotation('_In_')] FLOAT Depth, [annotation('_In_')] UINT8 Stencil, [annotation('_In_')] UINT NumRects, [annotation('_In_reads_(NumRects)')] const \fBD3D12_RECT\fP *pRects)"
.br
.ti -1c
.RI "\fBvoid\fP \fBClearRenderTargetView\fP ([annotation('_In_')] \fBD3D12_CPU_DESCRIPTOR_HANDLE\fP RenderTargetView, [annotation('_In_')] const FLOAT ColorRGBA[4], [annotation('_In_')] UINT NumRects, [annotation('_In_reads_(NumRects)')] const \fBD3D12_RECT\fP *pRects)"
.br
.ti -1c
.RI "\fBvoid\fP \fBClearUnorderedAccessViewUint\fP ([annotation('_In_')] \fBD3D12_GPU_DESCRIPTOR_HANDLE\fP ViewGPUHandleInCurrentHeap, [annotation('_In_')] \fBD3D12_CPU_DESCRIPTOR_HANDLE\fP ViewCPUHandle, [annotation('_In_')] \fBID3D12Resource\fP *pResource, [annotation('_In_')] const UINT Values[4], [annotation('_In_')] UINT NumRects, [annotation('_In_reads_(NumRects)')] const \fBD3D12_RECT\fP *pRects)"
.br
.ti -1c
.RI "\fBvoid\fP \fBClearUnorderedAccessViewFloat\fP ([annotation('_In_')] \fBD3D12_GPU_DESCRIPTOR_HANDLE\fP ViewGPUHandleInCurrentHeap, [annotation('_In_')] \fBD3D12_CPU_DESCRIPTOR_HANDLE\fP ViewCPUHandle, [annotation('_In_')] \fBID3D12Resource\fP *pResource, [annotation('_In_')] const FLOAT Values[4], [annotation('_In_')] UINT NumRects, [annotation('_In_reads_(NumRects)')] const \fBD3D12_RECT\fP *pRects)"
.br
.ti -1c
.RI "\fBvoid\fP \fBExecuteIndirect\fP ([annotation('_In_')] \fBID3D12CommandSignature\fP *pCommandSignature, [annotation('_In_')] UINT MaxCommandCount, [annotation('_In_')] \fBID3D12Resource\fP *pArgumentBuffer, [annotation('_In_')] UINT64 ArgumentBufferOffset, [annotation('_In_opt_')] \fBID3D12Resource\fP *pCountBuffer, [annotation('_In_')] UINT64 CountBufferOffset)"
.br
.in -1c

Public Member Functions inherited from \fBID3D12CommandList\fP
.in +1c
.ti -1c
.RI "\fBD3D12_COMMAND_LIST_TYPE\fP \fBGetType\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBID3D12VideoDecodeCommandList\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP \fBDecodeFrame\fP ([annotation('_In_')] \fBID3D12VideoDecoder\fP *pDecoder, [annotation('_In_')] const \fBD3D12_VIDEO_DECODE_OUTPUT_STREAM_ARGUMENTS\fP *pOutputArguments, [annotation('_In_')] const \fBD3D12_VIDEO_DECODE_INPUT_STREAM_ARGUMENTS\fP *pInputArguments)"
.br
.in -1c

Public Member Functions inherited from \fBID3D12VideoDevice\fP
.in +1c
.ti -1c
.RI "HRESULT \fBCheckFeatureSupport\fP (\fBD3D12_FEATURE_VIDEO\fP FeatureVideo, [annotation('_Inout_updates_bytes_(FeatureSupportDataSize)')] void *pFeatureSupportData, UINT FeatureSupportDataSize)"
.br
.ti -1c
.RI "HRESULT \fBCreateVideoDecoder\fP ([annotation('_In_')] const \fBD3D12_VIDEO_DECODER_DESC\fP *pDesc, [annotation('_In_')] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppVideoDecoder)"
.br
.ti -1c
.RI "HRESULT \fBCreateVideoDecoderHeap\fP ([annotation('_In_')]const \fBD3D12_VIDEO_DECODER_HEAP_DESC\fP *pVideoDecoderHeapDesc, [annotation('_In_')] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppVideoDecoderHeap)"
.br
.ti -1c
.RI "HRESULT \fBCreateVideoProcessor\fP (UINT NodeMask, [annotation('_In_')] const \fBD3D12_VIDEO_PROCESS_OUTPUT_STREAM_DESC\fP *pOutputStreamDesc, UINT NumInputStreamDescs, [annotation('_In_reads_(NumInputStreamDescs)')]const \fBD3D12_VIDEO_PROCESS_INPUT_STREAM_DESC\fP *pInputStreamDescs, [annotation('_In_')] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP **ppVideoProcessor)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP struct::AtomicCopyBufferUINT ([annotation('_In_')] \fBID3D12Resource\fP * pDstBuffer, UINT64 DstOffset, [annotation('_In_')] \fBID3D12Resource\fP * pSrcBuffer, UINT64 SrcOffset, UINT Dependencies, [annotation('_In_reads_(Dependencies)')] \fBID3D12Resource\fP *const * ppDependentResources, [annotation('_In_reads_(Dependencies)')] const \fBD3D12_SUBRESOURCE_RANGE_UINT64\fP * pDependentSubresourceRanges)"

.SS "\fBvoid\fP struct::AtomicCopyBufferUINT64 ([annotation('_In_')] \fBID3D12Resource\fP * pDstBuffer, UINT64 DstOffset, [annotation('_In_')] \fBID3D12Resource\fP * pSrcBuffer, UINT64 SrcOffset, UINT Dependencies, [annotation('_In_reads_(Dependencies)')] \fBID3D12Resource\fP *const * ppDependentResources, [annotation('_In_reads_(Dependencies)')] const \fBD3D12_SUBRESOURCE_RANGE_UINT64\fP * pDependentSubresourceRanges)"

.SS "\fBvoid\fP struct::BeginEvent (UINT Metadata, [annotation('_In_reads_bytes_opt_(Size)')] const \fBvoid\fP * pData, UINT Size)"

.PP
Implements \fBID3D12GraphicsCommandList\fP\&.
.SS "\fBvoid\fP struct::BeginQuery ([annotation('_In_')] \fBID3D12QueryHeap\fP * pQueryHeap, [annotation('_In_')] \fBD3D12_QUERY_TYPE\fP Type, [annotation('_In_')] UINT Index)"

.PP
Implements \fBID3D12GraphicsCommandList\fP\&.
.SS "\fBvoid\fP struct::ClearState ()"

.PP
Implements \fBID3D12VideoDecodeCommandList\fP\&.
.SS "HRESULT struct::Close ()"

.PP
Implements \fBID3D12GraphicsCommandList\fP\&.
.SS "HRESULT struct::CreateVideoMotionEstimator ([annotation('_In_')] const \fBD3D12_VIDEO_MOTION_ESTIMATOR_DESC\fP * pDesc, [annotation('_In_opt_')] \fBID3D12ProtectedResourceSession\fP * pProtectedResourceSession, [annotation('_In_')] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP ** ppVideoMotionEstimator)"

.SS "HRESULT struct::CreateVideoMotionVectorHeap ([annotation('_In_')] const \fBD3D12_VIDEO_MOTION_VECTOR_HEAP_DESC\fP * pDesc, [annotation('_In_opt_')] \fBID3D12ProtectedResourceSession\fP * pProtectedResourceSession, [annotation('_In_')] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_')] \fBvoid\fP ** ppVideoMotionVectorHeap)"

.SS "\fBvoid\fP struct::DecodeFrame1 ([annotation('_In_')] \fBID3D12VideoDecoder\fP * pDecoder, [annotation('_In_')] const \fBD3D12_VIDEO_DECODE_OUTPUT_STREAM_ARGUMENTS1\fP * pOutputArguments, [annotation('_In_')] const \fBD3D12_VIDEO_DECODE_INPUT_STREAM_ARGUMENTS\fP * pInputArguments)"

.SS "\fBvoid\fP struct::DiscardResource ([annotation('_In_')] \fBID3D12Resource\fP * pResource, [annotation('_In_opt_')] const \fBD3D12_DISCARD_REGION\fP * pRegion)"

.PP
Implements \fBID3D12GraphicsCommandList\fP\&.
.SS "\fBvoid\fP struct::EnableShaderInstrumentation (BOOL bEnable)"

.SS "\fBvoid\fP struct::EndEvent ()"

.PP
Implements \fBID3D12GraphicsCommandList\fP\&.
.SS "\fBvoid\fP struct::EndQuery ([annotation('_In_')] \fBID3D12QueryHeap\fP * pQueryHeap, [annotation('_In_')] \fBD3D12_QUERY_TYPE\fP Type, [annotation('_In_')] UINT Index)"

.PP
Implements \fBID3D12GraphicsCommandList\fP\&.
.SS "\fBD3D12_VIDEO_MOTION_ESTIMATOR_DESC\fP struct::GetDesc ()"

.SS "UINT64 struct::GetPipelineStackSize ()"

.SS "\fBD3D12_PROGRAM_IDENTIFIER\fP struct::GetProgramIdentifier (LPCWSTR pProgramName)"

.SS "HRESULT struct::GetProtectedResourceSession ([in] REFIID riid, [out, iid_is(riid), annotation('_COM_Outptr_opt_')] \fBvoid\fP ** ppProtectedSession)"

.SS "\fBvoid\fP * struct::GetShaderIdentifier ([annotation('_In_')] LPCWSTR pExportName)"

.SS "UINT64 struct::GetShaderStackSize ([annotation('_In_')] LPCWSTR pExportName)"

.SS "\fBvoid\fP struct::OMSetDepthBounds ([annotation('_In_')] FLOAT Min, [annotation('_In_')] FLOAT Max)"

.SS "\fBvoid\fP struct::ProcessFrames ([annotation('_In_')] \fBID3D12VideoProcessor\fP * pVideoProcessor, [annotation('_In_')] const \fBD3D12_VIDEO_PROCESS_OUTPUT_STREAM_ARGUMENTS\fP * pOutputArguments, UINT NumInputStreams, [annotation('_In_reads_(NumInputStreams)')] const \fBD3D12_VIDEO_PROCESS_INPUT_STREAM_ARGUMENTS\fP * pInputArguments)"

.SS "HRESULT struct::Reset ([annotation('_In_')] \fBID3D12CommandAllocator\fP * pAllocator)"

.PP
Implements \fBID3D12VideoDecodeCommandList\fP\&.
.SS "\fBvoid\fP struct::ResolveQueryData ([annotation('_In_')] \fBID3D12QueryHeap\fP * pQueryHeap, [annotation('_In_')] \fBD3D12_QUERY_TYPE\fP Type, [annotation('_In_')] UINT StartIndex, [annotation('_In_')] UINT NumQueries, [annotation('_In_')] \fBID3D12Resource\fP * pDestinationBuffer, [annotation('_In_')] UINT64 AlignedDestinationBufferOffset)"

.PP
Implements \fBID3D12GraphicsCommandList\fP\&.
.SS "\fBvoid\fP struct::ResolveSubresourceRegion ([annotation('_In_')] \fBID3D12Resource\fP * pDstResource, [annotation('_In_')] UINT DstSubresource, [annotation('_In_')] UINT DstX, [annotation('_In_')] UINT DstY, [annotation('_In_')] \fBID3D12Resource\fP * pSrcResource, [annotation('_In_')] UINT SrcSubresource, [annotation('_In_opt_')] \fBD3D12_RECT\fP * pSrcRect, [annotation('_In_')] \fBDXGI_FORMAT\fP Format, [annotation('_In_')] \fBD3D12_RESOLVE_MODE\fP ResolveMode)"

.SS "\fBvoid\fP struct::ResourceBarrier ([annotation('_In_')] UINT NumBarriers, [annotation('_In_reads_(NumBarriers)')] const \fBD3D12_RESOURCE_BARRIER\fP * pBarriers)"

.PP
Implements \fBID3D12GraphicsCommandList\fP\&.
.SS "\fBvoid\fP struct::RSSetShadingRate ([annotation('_In_')] \fBD3D12_SHADING_RATE\fP baseShadingRate, [annotation('_In_reads_opt_(D3D12_RS_SET_SHADING_RATE_COMBINER_COUNT)')] const \fBD3D12_SHADING_RATE_COMBINER\fP * combiners)"

.SS "\fBvoid\fP struct::RSSetShadingRateImage ([annotation('_In_opt_')] \fBID3D12Resource\fP * shadingRateImage)"

.SS "\fBvoid\fP struct::SetMarker (UINT Metadata, [annotation('_In_reads_bytes_opt_(Size)')] const \fBvoid\fP * pData, UINT Size)"

.PP
Implements \fBID3D12GraphicsCommandList\fP\&.
.SS "\fBvoid\fP struct::SetPipelineStackSize (UINT64 PipelineStackSizeInBytes)"

.SS "\fBvoid\fP struct::SetPredication ([annotation('_In_opt_')] \fBID3D12Resource\fP * pBuffer, [annotation('_In_')] UINT64 AlignedBufferOffset, [annotation('_In_')] \fBD3D12_PREDICATION_OP\fP Operation)"

.PP
Implements \fBID3D12GraphicsCommandList\fP\&.
.SS "\fBvoid\fP struct::SetSamplePositions ([annotation('_In_')] UINT NumSamplesPerPixel, [annotation('_In_')] UINT NumPixels, [annotation('_In_reads_(NumSamplesPerPixel*NumPixels)')] \fBD3D12_SAMPLE_POSITION\fP * pSamplePositions)"

.SS "\fBvoid\fP struct::SetViewInstanceMask ([annotation('_In_')] UINT Mask)"

.SS "BOOL struct::ShaderInstrumentationEnabled ()"

.SS "\fBvoid\fP struct::WriteBufferImmediate (UINT Count, [annotation('_In_reads_(Count)')] const \fBD3D12_WRITEBUFFERIMMEDIATE_PARAMETER\fP * pParams, [annotation('_In_reads_opt_(Count)')] const \fBD3D12_WRITEBUFFERIMMEDIATE_MODE\fP * pModes)"

.PP
Implements \fBID3D12VideoDecodeCommandList\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
