.TH "adhed/assimp/Subdivision.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/assimp/Subdivision.h
.SH SYNOPSIS
.br
.PP
\fR#include <assimp/types\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAssimp::Subdivider\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAssimp\fP"
.br
.RI "Some C++ utilities for inter- and extrapolation\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAI_SUBDISIVION_H_INC\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AI_SUBDISIVION_H_INC"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
