.TH "UPRISE_ENGINE/Teleport.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/Teleport.h
.SH SYNOPSIS
.br
.PP
\fR#include 'pch\&.h'\fP
.br
\fR#include 'HeaderE/CORE/C_BEHAVIOUR\&.h'\fP
.br
\fR#include 'HeaderE/CORE/C_INPUT\&.h'\fP
.br
\fR#include 'TRANSFORM\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTeleport\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_TELEPORT_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _TELEPORT_"

.PP
Definition at line \fB7\fP of file \fBTeleport\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
