.TH "Terrain_Data" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Terrain_Data
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <TERRAIN_DATA\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTerrain_Data\fP ()"
.br
.ti -1c
.RI "bool \fBLoadHeightmap\fP (const char *filename)"
.br
.ti -1c
.RI "float \fBGetHeight\fP (int x, int z) const"
.br
.ti -1c
.RI "void \fBSetHeight\fP (int x, int z, float height)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::shared_ptr< \fBTerrain_Data\fP > \fBCreate\fP (const char *path, int w, int d, int mh, \fBPAIN::Shader\fP *\fBshader\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBdepth\fP"
.br
.ti -1c
.RI "float \fBmaxHeight\fP"
.br
.ti -1c
.RI "\fBPAIN::TerrainModel\fP \fBmodel\fP"
.br
.ti -1c
.RI "std::vector< std::vector< float > > \fBheightMap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBTERRAIN_DATA\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Terrain_Data::Terrain_Data ()"

.PP
Definition at line \fB5\fP of file \fBTERRAIN_DATA\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "std::shared_ptr< \fBTerrain_Data\fP > Terrain_Data::Create (const char * path, int w, int d, int mh, \fBPAIN::Shader\fP * shader)\fR [static]\fP"

.PP
Definition at line \fB60\fP of file \fBTERRAIN_DATA\&.cpp\fP\&.
.SS "float Terrain_Data::GetHeight (int x, int z) const\fR [inline]\fP"

.PP
Definition at line \fB15\fP of file \fBTERRAIN_DATA\&.h\fP\&.
.SS "bool Terrain_Data::LoadHeightmap (const char * filename)"

.PP
Definition at line \fB28\fP of file \fBTERRAIN_DATA\&.cpp\fP\&.
.SS "void Terrain_Data::SetHeight (int x, int z, float height)\fR [inline]\fP"

.PP
Definition at line \fB21\fP of file \fBTERRAIN_DATA\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Terrain_Data::depth"

.PP
Definition at line \fB9\fP of file \fBTERRAIN_DATA\&.h\fP\&.
.SS "std::vector<std::vector<float> > Terrain_Data::heightMap"

.PP
Definition at line \fB13\fP of file \fBTERRAIN_DATA\&.h\fP\&.
.SS "float Terrain_Data::maxHeight"

.PP
Definition at line \fB10\fP of file \fBTERRAIN_DATA\&.h\fP\&.
.SS "\fBPAIN::TerrainModel\fP Terrain_Data::model"

.PP
Definition at line \fB12\fP of file \fBTERRAIN_DATA\&.h\fP\&.
.SS "int Terrain_Data::width"

.PP
Definition at line \fB8\fP of file \fBTERRAIN_DATA\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
