.TH "test" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBe\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBprnt\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBPrint\fP (\fBtest\fP *in)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB184\fP of file \fBUPRISE_ENGINE_MAIN\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void test::Print (\fBtest\fP * in)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB188\fP of file \fBUPRISE_ENGINE_MAIN\&.cpp\fP\&.
.nf
188                                {
189 
190     }
.PP
.fi

.SS "virtual void test::prnt ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBe\fP\&.
.PP
Definition at line \fB191\fP of file \fBUPRISE_ENGINE_MAIN\&.cpp\fP\&.
.nf
191                         {
192 
193     }
.PP
.fi

.SH "Member Data Documentation"
.PP 
.SS "int test::i"

.PP
Definition at line \fB186\fP of file \fBUPRISE_ENGINE_MAIN\&.cpp\fP\&.
.PP
Referenced by \fBmain()\fP, and \fBe::prnt()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
