.TH "UPRISE_ENGINE/TEST.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/TEST.h
.SH SYNOPSIS
.br
.PP
\fR#include 'HeaderE/CORE/C_BEHAVIOUR\&.h'\fP
.br
\fR#include 'HeaderE/CORE/C_INPUT\&.h'\fP
.br
\fR#include '_COMPONENT\&.h'\fP
.br
\fR#include 'HeaderE/DATATYPES/D_DATATYPES\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTest\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_TEST_\fP"
.br
.ti -1c
.RI "#define \fB_REGISTER_TEST_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _REGISTER_TEST_"

.PP
Definition at line \fB43\fP of file \fBTEST\&.h\fP\&.
.SS "#define _TEST_"

.PP
Definition at line \fB3\fP of file \fBTEST\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
