.TH "adhed/glm/gtx/texture.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/texture.inl
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBT\fP \fBglm::levels\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &Extent)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBT\fP \fBglm::levels\fP (\fBT\fP Extent)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
