.TH "adhed/assimp/TinyFormatter.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/assimp/TinyFormatter.h \- Utility to format log messages more easily\&. Introduced to get rid of the boost::format dependency\&. Much slinker, basically just extends stringstream\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAssimp::Formatter::basic_formatter< T, CharTraits, Allocator >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAssimp\fP"
.br
.RI "Some C++ utilities for inter- and extrapolation\&. "
.ti -1c
.RI "namespace \fBAssimp::Formatter\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINCLUDED_TINY_FORMATTER_H\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBbasic_formatter\fP< char > \fBAssimp::Formatter::format\fP"
.br
.ti -1c
.RI "typedef \fBbasic_formatter\fP< wchar_t > \fBAssimp::Formatter::wformat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Utility to format log messages more easily\&. Introduced to get rid of the boost::format dependency\&. Much slinker, basically just extends stringstream\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define INCLUDED_TINY_FORMATTER_H"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
