.TH "adhed/client/TracyProfiler.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/client/TracyProfiler.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <assert\&.h>\fP
.br
\fR#include <atomic>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <time\&.h>\fP
.br
\fR#include 'tracy_concurrentqueue\&.h'\fP
.br
\fR#include 'tracy_SPSCQueue\&.h'\fP
.br
\fR#include 'TracyCallstack\&.hpp'\fP
.br
\fR#include 'TracySysPower\&.hpp'\fP
.br
\fR#include 'TracySysTime\&.hpp'\fP
.br
\fR#include 'TracyFastVector\&.hpp'\fP
.br
\fR#include '\&.\&./common/TracyQueue\&.hpp'\fP
.br
\fR#include '\&.\&./common/TracyAlign\&.hpp'\fP
.br
\fR#include '\&.\&./common/TracyAlloc\&.hpp'\fP
.br
\fR#include '\&.\&./common/TracyMutex\&.hpp'\fP
.br
\fR#include '\&.\&./common/TracyProtocol\&.hpp'\fP
.br
\fR#include <chrono>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtracy::GpuCtxWrapper\fP"
.br
.ti -1c
.RI "struct \fBtracy::SourceLocationData\fP"
.br
.ti -1c
.RI "class \fBtracy::Profiler\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTracyConcat\fP(\fBx\fP,  \fBy\fP)   \fBTracyConcatIndirect\fP(\fBx\fP,\fBy\fP)"
.br
.ti -1c
.RI "#define \fBTracyConcatIndirect\fP(\fBx\fP,  \fBy\fP)   \fBx\fP##\fBy\fP"
.br
.ti -1c
.RI "#define \fBTracyLfqPrepare\fP(_type)"
.br
.ti -1c
.RI "#define \fBTracyLfqCommit\fP       __tail\&.store( __magic + 1, std::memory_order_release );"
.br
.ti -1c
.RI "#define \fBTracyLfqPrepareC\fP(_type)"
.br
.ti -1c
.RI "#define \fBTracyLfqCommitC\fP       __tail\&.store( __magic + 1, std::memory_order_release );"
.br
.ti -1c
.RI "#define \fBTracyQueuePrepare\fP(_type)   \fBTracyLfqPrepare\fP( _type )"
.br
.ti -1c
.RI "#define \fBTracyQueueCommit\fP(_name)   \fBTracyLfqCommit\fP"
.br
.ti -1c
.RI "#define \fBTracyQueuePrepareC\fP(_type)   \fBTracyLfqPrepareC\fP( _type )"
.br
.ti -1c
.RI "#define \fBTracyQueueCommitC\fP(_name)   \fBTracyLfqCommitC\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBvoid\fP(* \fBtracy::ParameterCallback\fP) (\fBvoid\fP *\fBdata\fP, uint32_t idx, int32_t \fBval\fP)"
.br
.ti -1c
.RI "typedef char *(* \fBtracy::SourceContentsCallback\fP) (\fBvoid\fP *\fBdata\fP, const char *filename, size_t &\fBsize\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTRACY_API\fP \fBmoodycamel::ConcurrentQueue\fP< \fBQueueItem\fP >::ExplicitProducer * \fBtracy::GetToken\fP ()"
.br
.ti -1c
.RI "\fBTRACY_API\fP \fBProfiler\fP & \fBtracy::GetProfiler\fP ()"
.br
.ti -1c
.RI "\fBTRACY_API\fP std::atomic< uint32_t > & \fBtracy::GetLockCounter\fP ()"
.br
.ti -1c
.RI "\fBTRACY_API\fP std::atomic< uint8_t > & \fBtracy::GetGpuCtxCounter\fP ()"
.br
.ti -1c
.RI "\fBTRACY_API\fP \fBGpuCtxWrapper\fP & \fBtracy::GetGpuCtx\fP ()"
.br
.ti -1c
.RI "\fBTRACY_API\fP uint32_t \fBtracy::GetThreadHandle\fP ()"
.br
.ti -1c
.RI "\fBTRACY_API\fP bool \fBtracy::ProfilerAvailable\fP ()"
.br
.ti -1c
.RI "\fBTRACY_API\fP bool \fBtracy::ProfilerAllocatorAvailable\fP ()"
.br
.ti -1c
.RI "\fBTRACY_API\fP int64_t \fBtracy::GetFrequencyQpc\fP ()"
.br
.ti -1c
.RI "\fBtracy_force_inline\fP bool \fBtracy::HardwareSupportsInvariantTSC\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TracyConcat( \fBx\fP,  \fBy\fP)   \fBTracyConcatIndirect\fP(\fBx\fP,\fBy\fP)"

.SS "#define TracyConcatIndirect( \fBx\fP,  \fBy\fP)   \fBx\fP##\fBy\fP"

.SS "#define TracyLfqCommit       __tail\&.store( __magic + 1, std::memory_order_release );"

.SS "#define TracyLfqCommitC       __tail\&.store( __magic + 1, std::memory_order_release );"

.SS "#define TracyLfqPrepare( _type)"
\fBValue:\fP
.nf
    moodycamel::ConcurrentQueueDefaultTraits::index_t __magic; \\
    auto __token = GetToken(); \\
    auto& __tail = __token\->get_tail_index(); \\
    auto item = __token\->enqueue_begin( __magic ); \\
    MemWrite( &item\->hdr\&.type, _type );
.PP
.fi

.SS "#define TracyLfqPrepareC( _type)"
\fBValue:\fP
.nf
    tracy::moodycamel::ConcurrentQueueDefaultTraits::index_t __magic; \\
    auto __token = tracy::GetToken(); \\
    auto& __tail = __token\->get_tail_index(); \\
    auto item = __token\->enqueue_begin( __magic ); \\
    tracy::MemWrite( &item\->hdr\&.type, _type );
.PP
.fi

.SS "#define TracyQueueCommit( _name)   \fBTracyLfqCommit\fP"

.SS "#define TracyQueueCommitC( _name)   \fBTracyLfqCommitC\fP"

.SS "#define TracyQueuePrepare( _type)   \fBTracyLfqPrepare\fP( _type )"

.SS "#define TracyQueuePrepareC( _type)   \fBTracyLfqPrepareC\fP( _type )"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
