.TH "adhed/client/TracyCallstack.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/client/TracyCallstack.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./common/TracyApi\&.h'\fP
.br
\fR#include '\&.\&./common/TracyForceInline\&.hpp'\fP
.br
\fR#include 'TracyCallstack\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
