.TH "adhed/tracy/TracyVulkan.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/tracy/TracyVulkan.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtracy::VkCtxScope\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTracyVkContext\fP(\fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP)   nullptr"
.br
.ti -1c
.RI "#define \fBTracyVkContextCalibrated\fP(\fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP,  \fBa\fP,  \fBb\fP)   nullptr"
.br
.ti -1c
.RI "#define \fBTracyVkDestroy\fP(\fBx\fP)"
.br
.ti -1c
.RI "#define \fBTracyVkContextName\fP(c,  \fBx\fP,  \fBy\fP)"
.br
.ti -1c
.RI "#define \fBTracyVkNamedZone\fP(c,  \fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP)"
.br
.ti -1c
.RI "#define \fBTracyVkNamedZoneC\fP(c,  \fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP,  \fBa\fP)"
.br
.ti -1c
.RI "#define \fBTracyVkZone\fP(c,  \fBx\fP,  \fBy\fP)"
.br
.ti -1c
.RI "#define \fBTracyVkZoneC\fP(c,  \fBx\fP,  \fBy\fP,  \fBz\fP)"
.br
.ti -1c
.RI "#define \fBTracyVkZoneTransient\fP(c,  \fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP)"
.br
.ti -1c
.RI "#define \fBTracyVkCollect\fP(c,  \fBx\fP)"
.br
.ti -1c
.RI "#define \fBTracyVkNamedZoneS\fP(c,  \fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP,  \fBa\fP)"
.br
.ti -1c
.RI "#define \fBTracyVkNamedZoneCS\fP(c,  \fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP,  \fBv\fP,  \fBa\fP)"
.br
.ti -1c
.RI "#define \fBTracyVkZoneS\fP(c,  \fBx\fP,  \fBy\fP,  \fBz\fP)"
.br
.ti -1c
.RI "#define \fBTracyVkZoneCS\fP(c,  \fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP)"
.br
.ti -1c
.RI "#define \fBTracyVkZoneTransientS\fP(c,  \fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP,  \fBa\fP)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBTracyVkCtx\fP = \fBvoid\fP*"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TracyVkCollect( c,  \fBx\fP)"

.SS "#define TracyVkContext( \fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP)   nullptr"

.SS "#define TracyVkContextCalibrated( \fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP,  \fBa\fP,  \fBb\fP)   nullptr"

.SS "#define TracyVkContextName( c,  \fBx\fP,  \fBy\fP)"

.SS "#define TracyVkDestroy( \fBx\fP)"

.SS "#define TracyVkNamedZone( c,  \fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP)"

.SS "#define TracyVkNamedZoneC( c,  \fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP,  \fBa\fP)"

.SS "#define TracyVkNamedZoneCS( c,  \fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP,  \fBv\fP,  \fBa\fP)"

.SS "#define TracyVkNamedZoneS( c,  \fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP,  \fBa\fP)"

.SS "#define TracyVkZone( c,  \fBx\fP,  \fBy\fP)"

.SS "#define TracyVkZoneC( c,  \fBx\fP,  \fBy\fP,  \fBz\fP)"

.SS "#define TracyVkZoneCS( c,  \fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP)"

.SS "#define TracyVkZoneS( c,  \fBx\fP,  \fBy\fP,  \fBz\fP)"

.SS "#define TracyVkZoneTransient( c,  \fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP)"

.SS "#define TracyVkZoneTransientS( c,  \fBx\fP,  \fBy\fP,  \fBz\fP,  \fBw\fP,  \fBa\fP)"

.SH "Typedef Documentation"
.PP 
.SS "using \fBTracyVkCtx\fP = \fBvoid\fP*"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
