.TH "adhed/common/tracy_lz4hc.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/common/tracy_lz4hc.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'tracy_lz4\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtracy::LZ4HC_CCtx_internal\fP"
.br
.ti -1c
.RI "union \fBtracy::LZ4_streamHC_u\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLZ4HC_CLEVEL_MIN\fP   3"
.br
.ti -1c
.RI "#define \fBLZ4HC_CLEVEL_DEFAULT\fP   9"
.br
.ti -1c
.RI "#define \fBLZ4HC_CLEVEL_OPT_MIN\fP   10"
.br
.ti -1c
.RI "#define \fBLZ4HC_CLEVEL_MAX\fP   12"
.br
.ti -1c
.RI "#define \fBLZ4HC_DICTIONARY_LOGSIZE\fP   16"
.br
.ti -1c
.RI "#define \fBLZ4HC_MAXD\fP   (1<<\fBLZ4HC_DICTIONARY_LOGSIZE\fP)"
.br
.ti -1c
.RI "#define \fBLZ4HC_MAXD_MASK\fP   (\fBLZ4HC_MAXD\fP \- 1)"
.br
.ti -1c
.RI "#define \fBLZ4HC_HASH_LOG\fP   15"
.br
.ti -1c
.RI "#define \fBLZ4HC_HASHTABLESIZE\fP   (1 << \fBLZ4HC_HASH_LOG\fP)"
.br
.ti -1c
.RI "#define \fBLZ4HC_HASH_MASK\fP   (\fBLZ4HC_HASHTABLESIZE\fP \- 1)"
.br
.ti -1c
.RI "#define \fBLZ4_STREAMHC_MINSIZE\fP   262200  /* static \fBsize\fP, for inter\-version compatibility */"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef union \fBLZ4_streamHC_u\fP \fBtracy::LZ4_streamHC_t\fP"
.br
.ti -1c
.RI "typedef \fBstruct\fP LZ4HC_CCtx_internal \fBtracy::LZ4HC_CCtx_internal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtracy::LZ4_compress_HC\fP (const char *\fBsrc\fP, char *\fBdst\fP, int \fBsrcSize\fP, int dstCapacity, int \fBcompressionLevel\fP)"
.br
.ti -1c
.RI "int \fBtracy::LZ4_sizeofStateHC\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "int \fBtracy::LZ4_compress_HC_extStateHC\fP (\fBvoid\fP *state, const char *\fBsrc\fP, char *\fBdst\fP, int \fBsrcSize\fP, int dstCapacity, int \fBcompressionLevel\fP)"
.br
.ti -1c
.RI "int \fBtracy::LZ4_compress_HC_destSize\fP (\fBvoid\fP *state, const char *\fBsource\fP, char *\fBdest\fP, int *sourceSizePtr, int targetDestSize, int cLevel)"
.br
.ti -1c
.RI "\fBLZ4_streamHC_t\fP * \fBtracy::LZ4_createStreamHC\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "int \fBtracy::LZ4_freeStreamHC\fP (\fBLZ4_streamHC_t\fP *LZ4_streamHCPtr)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtracy::LZ4_resetStreamHC_fast\fP (\fBLZ4_streamHC_t\fP *LZ4_streamHCPtr, int \fBcompressionLevel\fP)"
.br
.ti -1c
.RI "int \fBtracy::LZ4_loadDictHC\fP (\fBLZ4_streamHC_t\fP *LZ4_streamHCPtr, const char *dictionary, int dictSize)"
.br
.ti -1c
.RI "int \fBtracy::LZ4_compress_HC_continue\fP (\fBLZ4_streamHC_t\fP *LZ4_streamHCPtr, const char *\fBsrc\fP, char *\fBdst\fP, int \fBsrcSize\fP, int dstCapacity)"
.br
.ti -1c
.RI "int \fBtracy::LZ4_compress_HC_continue_destSize\fP (\fBLZ4_streamHC_t\fP *LZ4_streamHCPtr, const char *\fBsrc\fP, char *\fBdst\fP, int *srcSizePtr, int targetDestSize)"
.br
.ti -1c
.RI "int \fBtracy::LZ4_saveDictHC\fP (\fBLZ4_streamHC_t\fP *LZ4_streamHCPtr, char *safeBuffer, int dictSize)"
.br
.ti -1c
.RI "\fBLZ4_streamHC_t\fP * \fBtracy::LZ4_initStreamHC\fP (\fBvoid\fP *\fBbuffer\fP, size_t \fBsize\fP)"
.br
.ti -1c
.RI "\fBtracy::LZ4_DEPRECATED\fP ('use \fBLZ4_compress_HC\fP() instead') \fBLZ4LIB_API\fP int \fBLZ4_compressHC\fP(const char *\fBsource\fP"
.br
.ti -1c
.RI "\fBtracy::LZ4_DEPRECATED\fP ('use \fBLZ4_compress_HC_extStateHC\fP() instead') \fBLZ4LIB_API\fP int \fBLZ4_compressHC_withStateHC\fP(\fBvoid\fP *state"
.br
.ti -1c
.RI "\fBtracy::LZ4_DEPRECATED\fP ('use \fBLZ4_compress_HC_continue\fP() instead') \fBLZ4LIB_API\fP int \fBLZ4_compressHC_continue\fP(\fBLZ4_streamHC_t\fP *LZ4_streamHCPtr"
.br
.ti -1c
.RI "\fBtracy::LZ4_DEPRECATED\fP ('use \fBLZ4_createStreamHC\fP() instead') \fBLZ4LIB_API\fP \fBvoid\fP *\fBLZ4_createHC\fP(const char *\fBinputBuffer\fP)"
.br
.ti -1c
.RI "\fBtracy::LZ4_DEPRECATED\fP ('use \fBLZ4_freeStreamHC\fP() instead') \fBLZ4LIB_API\fP int \fBLZ4_freeHC\fP(\fBvoid\fP *LZ4HC_Data)"
.br
.ti -1c
.RI "\fBtracy::LZ4_DEPRECATED\fP ('use \fBLZ4_saveDictHC\fP() instead') \fBLZ4LIB_API\fP char *\fBLZ4_slideInputBufferHC\fP(\fBvoid\fP *LZ4HC_Data)"
.br
.ti -1c
.RI "\fBtracy::LZ4_DEPRECATED\fP ('use \fBLZ4_initStreamHC\fP() instead') \fBLZ4LIB_API\fP int \fBLZ4_resetStreamStateHC\fP(\fBvoid\fP *state"
.br
.ti -1c
.RI "\fBvoid\fP \fBtracy::LZ4_resetStreamHC\fP (\fBLZ4_streamHC_t\fP *LZ4_streamHCPtr, int \fBcompressionLevel\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char int int \fBtracy::compressionLevel\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LZ4_STREAMHC_MINSIZE   262200  /* static \fBsize\fP, for inter\-version compatibility */"

.SS "#define LZ4HC_CLEVEL_DEFAULT   9"

.SS "#define LZ4HC_CLEVEL_MAX   12"

.SS "#define LZ4HC_CLEVEL_MIN   3"

.SS "#define LZ4HC_CLEVEL_OPT_MIN   10"

.SS "#define LZ4HC_DICTIONARY_LOGSIZE   16"

.SS "#define LZ4HC_HASH_LOG   15"

.SS "#define LZ4HC_HASH_MASK   (\fBLZ4HC_HASHTABLESIZE\fP \- 1)"

.SS "#define LZ4HC_HASHTABLESIZE   (1 << \fBLZ4HC_HASH_LOG\fP)"

.SS "#define LZ4HC_MAXD   (1<<\fBLZ4HC_DICTIONARY_LOGSIZE\fP)"

.SS "#define LZ4HC_MAXD_MASK   (\fBLZ4HC_MAXD\fP \- 1)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
