.TH "adhed/common/TracyAlign.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/common/TracyAlign.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <string\&.h>\fP
.br
\fR#include 'TracyForceInline\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP > \fBtracy_force_inline\fP \fBT\fP \fBtracy::MemRead\fP (const \fBvoid\fP *ptr)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBtracy_force_inline\fP \fBvoid\fP \fBtracy::MemWrite\fP (\fBvoid\fP *ptr, \fBT\fP \fBval\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
