.TH "adhed/common/TracyApi.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/common/TracyApi.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTRACY_API\fP   \fB__attribute__\fP((visibility('default')))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TRACY_API   \fB__attribute__\fP((visibility('default')))"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
