.TH "adhed/common/TracySystem.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/common/TracySystem.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include 'TracyApi\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.ti -1c
.RI "namespace \fBtracy::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTRACY_API\fP uint32_t \fBtracy::detail::GetThreadHandleImpl\fP ()"
.br
.ti -1c
.RI "\fBTRACY_API\fP uint32_t \fBtracy::GetThreadHandle\fP ()"
.br
.ti -1c
.RI "\fBTRACY_API\fP \fBvoid\fP \fBtracy::SetThreadName\fP (const char *\fBname\fP)"
.br
.ti -1c
.RI "\fBTRACY_API\fP const char * \fBtracy::GetThreadName\fP (uint32_t \fBid\fP)"
.br
.ti -1c
.RI "\fBTRACY_API\fP const char * \fBtracy::GetEnvVar\fP (const char *\fBname\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
