.TH "adhed/common/TracyStackFrames.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/common/TracyStackFrames.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'TracyStackFrames\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBtracy::s_tracyStackFrames_\fP []"
.br
.ti -1c
.RI "const char ** \fBtracy::s_tracyStackFrames\fP = \fBs_tracyStackFrames_\fP"
.br
.ti -1c
.RI "const \fBStringMatch\fP \fBtracy::s_tracySkipSubframes_\fP []"
.br
.ti -1c
.RI "const \fBStringMatch\fP * \fBtracy::s_tracySkipSubframes\fP = \fBs_tracySkipSubframes_\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
