.TH "adhed/client/tracy_rpmalloc.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/client/tracy_rpmalloc.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br
\fR#include '\&.\&./common/TracyApi\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtracy::rpmalloc_global_statistics_t\fP"
.br
.ti -1c
.RI "struct \fBtracy::rpmalloc_thread_statistics_t\fP"
.br
.ti -1c
.RI "struct \fBtracy::rpmalloc_config_t\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRPMALLOC_EXPORT\fP"
.br
.ti -1c
.RI "#define \fBRPMALLOC_ALLOCATOR\fP"
.br
.ti -1c
.RI "#define \fBRPMALLOC_ATTRIB_MALLOC\fP"
.br
.ti -1c
.RI "#define \fBRPMALLOC_ATTRIB_ALLOC_SIZE\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fBRPMALLOC_ATTRIB_ALLOC_SIZE2\fP(\fBcount\fP,  \fBsize\fP)"
.br
.ti -1c
.RI "#define \fBRPMALLOC_CDECL\fP"
.br
.ti -1c
.RI "#define \fBRPMALLOC_CONFIGURABLE\fP   0"
.br
.RI "Define RPMALLOC_CONFIGURABLE to enable configuring sizes\&. Will introduce\&. "
.ti -1c
.RI "#define \fBRPMALLOC_FIRST_CLASS_HEAPS\fP   0"
.br
.RI "Define RPMALLOC_FIRST_CLASS_HEAPS to enable heap based API (rpmalloc_heap_* functions)\&. "
.ti -1c
.RI "#define \fBRPMALLOC_NO_PRESERVE\fP   1"
.br
.RI "Flag to rpaligned_realloc to not preserve content in reallocation\&. "
.ti -1c
.RI "#define \fBRPMALLOC_GROW_OR_FAIL\fP   2"
.br
.RI "Flag to rpaligned_realloc to fail and return null pointer if grow cannot be done in-place,\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBstruct\fP tracy::rpmalloc_global_statistics_t \fBtracy::rpmalloc_global_statistics_t\fP"
.br
.ti -1c
.RI "typedef \fBstruct\fP tracy::rpmalloc_thread_statistics_t \fBtracy::rpmalloc_thread_statistics_t\fP"
.br
.ti -1c
.RI "typedef \fBstruct\fP tracy::rpmalloc_config_t \fBtracy::rpmalloc_config_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTRACY_API\fP int \fBtracy::rpmalloc_initialize\fP (\fBvoid\fP)"
.br
.RI "Initialize allocator with default configuration\&. "
.ti -1c
.RI "\fBRPMALLOC_EXPORT\fP int \fBtracy::rpmalloc_initialize_config\fP (const \fBrpmalloc_config_t\fP *config)"
.br
.RI "Initialize allocator with given configuration\&. "
.ti -1c
.RI "\fBRPMALLOC_EXPORT\fP const \fBrpmalloc_config_t\fP * \fBtracy::rpmalloc_config\fP (\fBvoid\fP)"
.br
.RI "Get allocator configuration\&. "
.ti -1c
.RI "\fBTRACY_API\fP \fBvoid\fP \fBtracy::rpmalloc_finalize\fP (\fBvoid\fP)"
.br
.RI "Finalize allocator\&. "
.ti -1c
.RI "\fBTRACY_API\fP \fBvoid\fP \fBtracy::rpmalloc_thread_initialize\fP (\fBvoid\fP)"
.br
.RI "Initialize allocator for calling thread\&. "
.ti -1c
.RI "\fBTRACY_API\fP \fBvoid\fP \fBtracy::rpmalloc_thread_finalize\fP (int release_caches)"
.br
.RI "Finalize allocator for calling thread\&. "
.ti -1c
.RI "\fBRPMALLOC_EXPORT\fP \fBvoid\fP \fBtracy::rpmalloc_thread_collect\fP (\fBvoid\fP)"
.br
.RI "Perform deferred deallocations pending for the calling thread heap\&. "
.ti -1c
.RI "\fBRPMALLOC_EXPORT\fP int \fBtracy::rpmalloc_is_thread_initialized\fP (\fBvoid\fP)"
.br
.RI "Query if allocator is initialized for calling thread\&. "
.ti -1c
.RI "\fBRPMALLOC_EXPORT\fP \fBvoid\fP \fBtracy::rpmalloc_thread_statistics\fP (\fBrpmalloc_thread_statistics_t\fP *stats)"
.br
.RI "Get per-thread statistics\&. "
.ti -1c
.RI "\fBRPMALLOC_EXPORT\fP \fBvoid\fP \fBtracy::rpmalloc_global_statistics\fP (\fBrpmalloc_global_statistics_t\fP *stats)"
.br
.RI "Get global statistics\&. "
.ti -1c
.RI "\fBRPMALLOC_EXPORT\fP \fBvoid\fP \fBtracy::rpmalloc_dump_statistics\fP (\fBvoid\fP *file)"
.br
.RI "Dump all statistics in human readable format to file (should be a FILE*) "
.ti -1c
.RI "\fBTRACY_API\fP \fBRPMALLOC_ALLOCATOR\fP \fBvoid\fP * \fBtracy::rpmalloc\fP (size_t \fBsize\fP) \fBRPMALLOC_ATTRIB_MALLOC\fP \fBRPMALLOC_ATTRIB_ALLOC_SIZE\fP(1)"
.br
.RI "Allocate a memory block of at least the given size\&. "
.ti -1c
.RI "\fBTRACY_API\fP \fBvoid\fP \fBtracy::rpfree\fP (\fBvoid\fP *ptr)"
.br
.RI "Free the given memory block\&. "
.ti -1c
.RI "\fBRPMALLOC_EXPORT\fP \fBRPMALLOC_ALLOCATOR\fP \fBvoid\fP * \fBtracy::rpcalloc\fP (size_t num, size_t \fBsize\fP) \fBRPMALLOC_ATTRIB_MALLOC\fP \fBRPMALLOC_ATTRIB_ALLOC_SIZE2\fP(1"
.br
.RI "Allocate a memory block of at least the given size and zero initialize it\&. "
.ti -1c
.RI "\fBRPMALLOC_EXPORT\fP \fBRPMALLOC_ALLOCATOR\fP \fBvoid\fP \fBTRACY_API\fP \fBRPMALLOC_ALLOCATOR\fP \fBvoid\fP * \fBtracy::rprealloc\fP (\fBvoid\fP *ptr, size_t \fBsize\fP) \fBRPMALLOC_ATTRIB_MALLOC\fP \fBRPMALLOC_ATTRIB_ALLOC_SIZE\fP(2)"
.br
.RI "Reallocate the given block to at least the given size\&. "
.ti -1c
.RI "\fBRPMALLOC_EXPORT\fP \fBRPMALLOC_ALLOCATOR\fP \fBvoid\fP * \fBtracy::rpaligned_realloc\fP (\fBvoid\fP *ptr, size_t alignment, size_t \fBsize\fP, size_t oldsize, unsigned int \fBflags\fP) \fBRPMALLOC_ATTRIB_MALLOC\fP \fBRPMALLOC_ATTRIB_ALLOC_SIZE\fP(3)"
.br
.RI "Reallocate the given block to at least the given size and alignment,\&. "
.ti -1c
.RI "\fBRPMALLOC_EXPORT\fP \fBRPMALLOC_ALLOCATOR\fP \fBvoid\fP * \fBtracy::rpaligned_alloc\fP (size_t alignment, size_t \fBsize\fP) \fBRPMALLOC_ATTRIB_MALLOC\fP \fBRPMALLOC_ATTRIB_ALLOC_SIZE\fP(2)"
.br
.RI "Allocate a memory block of at least the given size and alignment\&. "
.ti -1c
.RI "\fBRPMALLOC_EXPORT\fP \fBRPMALLOC_ALLOCATOR\fP \fBvoid\fP * \fBtracy::rpaligned_calloc\fP (size_t alignment, size_t num, size_t \fBsize\fP) \fBRPMALLOC_ATTRIB_MALLOC\fP \fBRPMALLOC_ATTRIB_ALLOC_SIZE2\fP(2"
.br
.RI "Allocate a memory block of at least the given size and alignment, and zero initialize it\&. "
.ti -1c
.RI "\fBRPMALLOC_EXPORT\fP \fBRPMALLOC_ALLOCATOR\fP \fBvoid\fP \fBRPMALLOC_EXPORT\fP \fBRPMALLOC_ALLOCATOR\fP \fBvoid\fP * \fBtracy::rpmemalign\fP (size_t alignment, size_t \fBsize\fP) \fBRPMALLOC_ATTRIB_MALLOC\fP \fBRPMALLOC_ATTRIB_ALLOC_SIZE\fP(2)"
.br
.RI "Allocate a memory block of at least the given size and alignment\&. "
.ti -1c
.RI "\fBRPMALLOC_EXPORT\fP int \fBtracy::rpposix_memalign\fP (\fBvoid\fP **memptr, size_t alignment, size_t \fBsize\fP)"
.br
.RI "Allocate a memory block of at least the given size and alignment\&. "
.ti -1c
.RI "\fBRPMALLOC_EXPORT\fP size_t \fBtracy::rpmalloc_usable_size\fP (\fBvoid\fP *ptr)"
.br
.RI "Query the usable size of the given memory block (from given pointer to the end of block) "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RPMALLOC_ALLOCATOR"

.SS "#define RPMALLOC_ATTRIB_ALLOC_SIZE( \fBsize\fP)"

.SS "#define RPMALLOC_ATTRIB_ALLOC_SIZE2( \fBcount\fP,  \fBsize\fP)"

.SS "#define RPMALLOC_ATTRIB_MALLOC"

.SS "#define RPMALLOC_CDECL"

.SS "#define RPMALLOC_CONFIGURABLE   0"

.PP
Define RPMALLOC_CONFIGURABLE to enable configuring sizes\&. Will introduce\&. 
.SS "#define RPMALLOC_EXPORT"

.SS "#define RPMALLOC_FIRST_CLASS_HEAPS   0"

.PP
Define RPMALLOC_FIRST_CLASS_HEAPS to enable heap based API (rpmalloc_heap_* functions)\&. 
.SS "#define RPMALLOC_GROW_OR_FAIL   2"

.PP
Flag to rpaligned_realloc to fail and return null pointer if grow cannot be done in-place,\&. 
.SS "#define RPMALLOC_NO_PRESERVE   1"

.PP
Flag to rpaligned_realloc to not preserve content in reallocation\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
