.TH "adhed/common/TracySocket.cpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/common/TracySocket.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <assert\&.h>\fP
.br
\fR#include <inttypes\&.h>\fP
.br
\fR#include <new>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <sys/types\&.h>\fP
.br
\fR#include 'TracyAlloc\&.hpp'\fP
.br
\fR#include 'TracySocket\&.hpp'\fP
.br
\fR#include 'TracySystem\&.hpp'\fP
.br
\fR#include <arpa/inet\&.h>\fP
.br
\fR#include <sys/socket\&.h>\fP
.br
\fR#include <sys/param\&.h>\fP
.br
\fR#include <errno\&.h>\fP
.br
\fR#include <fcntl\&.h>\fP
.br
\fR#include <netinet/in\&.h>\fP
.br
\fR#include <netdb\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include <poll\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMSG_NOSIGNAL\fP   0"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBtracy::socket_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBtracy::BufSize\fP = 128 * 1024 }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MSG_NOSIGNAL   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
