.TH "adhed/client/tracy_concurrentqueue.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/client/tracy_concurrentqueue.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./common/TracyAlloc\&.hpp'\fP
.br
\fR#include '\&.\&./common/TracyForceInline\&.hpp'\fP
.br
\fR#include '\&.\&./common/TracySystem\&.hpp'\fP
.br
\fR#include <atomic>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include <type_traits>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <limits>\fP
.br
\fR#include <climits>\fP
.br
\fR#include <array>\fP
.br
\fR#include <thread>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtracy::moodycamel::details::const_numeric_max< T >\fP"
.br
.ti -1c
.RI "union \fBtracy::moodycamel::details::max_align_t\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::ConcurrentQueueDefaultTraits\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::details::ConcurrentQueueProducerTypelessBase\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::details::nomove_if< Enable >\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::details::nomove_if< false >\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::details::is_trivially_destructible< T >\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::details::static_is_lock_free_num< T >\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::details::static_is_lock_free_num< signed char >\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::details::static_is_lock_free_num< short >\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::details::static_is_lock_free_num< int >\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::details::static_is_lock_free_num< long >\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::details::static_is_lock_free_num< long long >\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::details::static_is_lock_free< T >\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::details::static_is_lock_free< bool >\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::details::static_is_lock_free< U * >\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::ProducerToken\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::ConsumerToken\fP"
.br
.ti -1c
.RI "class \fBtracy::moodycamel::ConcurrentQueue< T, Traits >\fP"
.br
.ti -1c
.RI "struct \fBtracy::moodycamel::ConcurrentQueue< T, Traits >::ExplicitProducer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.ti -1c
.RI "namespace \fBtracy::moodycamel\fP"
.br
.ti -1c
.RI "namespace \fBtracy::moodycamel::details\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::max_align_t \fBtracy::moodycamel::details::std_max_align_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBtracy::moodycamel::details::cqLikely\fP (bool \fBx\fP)"
.br
.ti -1c
.RI "bool \fBtracy::moodycamel::details::cqUnlikely\fP (bool \fBx\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , typename Traits > \fBvoid\fP \fBtracy::moodycamel::swap\fP (\fBConcurrentQueue\fP< \fBT\fP, Traits > &\fBa\fP, \fBConcurrentQueue\fP< \fBT\fP, Traits > &\fBb\fP) noexcept"
.br
.ti -1c
.RI "\fBvoid\fP \fBtracy::moodycamel::swap\fP (\fBProducerToken\fP &\fBa\fP, \fBProducerToken\fP &\fBb\fP) noexcept"
.br
.ti -1c
.RI "\fBvoid\fP \fBtracy::moodycamel::swap\fP (\fBConsumerToken\fP &\fBa\fP, \fBConsumerToken\fP &\fBb\fP) noexcept"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
