.TH "adhed/client/TracyThread.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/client/TracyThread.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <pthread\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtracy::ThreadExitHandler\fP"
.br
.ti -1c
.RI "class \fBtracy::Thread\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
