.TH "adhed/tracy/TracyD3D11.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/tracy/TracyD3D11.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtracy::D3D11ZoneScope\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtracy\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTracyD3D11Context\fP(device,  queue)   nullptr"
.br
.ti -1c
.RI "#define \fBTracyD3D11Destroy\fP(ctx)"
.br
.ti -1c
.RI "#define \fBTracyD3D11ContextName\fP(ctx,  \fBname\fP,  \fBsize\fP)"
.br
.ti -1c
.RI "#define \fBTracyD3D11NewFrame\fP(ctx)"
.br
.ti -1c
.RI "#define \fBTracyD3D11Zone\fP(ctx,  \fBname\fP)"
.br
.ti -1c
.RI "#define \fBTracyD3D11ZoneC\fP(ctx,  \fBname\fP,  \fBcolor\fP)"
.br
.ti -1c
.RI "#define \fBTracyD3D11NamedZone\fP(ctx,  varname,  \fBname\fP,  active)"
.br
.ti -1c
.RI "#define \fBTracyD3D11NamedZoneC\fP(ctx,  varname,  \fBname\fP,  \fBcolor\fP,  active)"
.br
.ti -1c
.RI "#define \fBTracyD3D11ZoneTransient\fP(ctx,  varname,  \fBname\fP,  active)"
.br
.ti -1c
.RI "#define \fBTracyD3D11ZoneS\fP(ctx,  \fBname\fP,  \fBdepth\fP)"
.br
.ti -1c
.RI "#define \fBTracyD3D11ZoneCS\fP(ctx,  \fBname\fP,  \fBcolor\fP,  \fBdepth\fP)"
.br
.ti -1c
.RI "#define \fBTracyD3D11NamedZoneS\fP(ctx,  varname,  \fBname\fP,  \fBdepth\fP,  active)"
.br
.ti -1c
.RI "#define \fBTracyD3D11NamedZoneCS\fP(ctx,  varname,  \fBname\fP,  \fBcolor\fP,  \fBdepth\fP,  active)"
.br
.ti -1c
.RI "#define \fBTracyD3D11ZoneTransientS\fP(ctx,  varname,  \fBname\fP,  \fBdepth\fP,  active)"
.br
.ti -1c
.RI "#define \fBTracyD3D11Collect\fP(ctx)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBTracyD3D11Ctx\fP = \fBvoid\fP*"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TracyD3D11Collect( ctx)"

.SS "#define TracyD3D11Context( device,  queue)   nullptr"

.SS "#define TracyD3D11ContextName( ctx,  \fBname\fP,  \fBsize\fP)"

.SS "#define TracyD3D11Destroy( ctx)"

.SS "#define TracyD3D11NamedZone( ctx,  varname,  \fBname\fP,  active)"

.SS "#define TracyD3D11NamedZoneC( ctx,  varname,  \fBname\fP,  \fBcolor\fP,  active)"

.SS "#define TracyD3D11NamedZoneCS( ctx,  varname,  \fBname\fP,  \fBcolor\fP,  \fBdepth\fP,  active)"

.SS "#define TracyD3D11NamedZoneS( ctx,  varname,  \fBname\fP,  \fBdepth\fP,  active)"

.SS "#define TracyD3D11NewFrame( ctx)"

.SS "#define TracyD3D11Zone( ctx,  \fBname\fP)"

.SS "#define TracyD3D11ZoneC( ctx,  \fBname\fP,  \fBcolor\fP)"

.SS "#define TracyD3D11ZoneCS( ctx,  \fBname\fP,  \fBcolor\fP,  \fBdepth\fP)"

.SS "#define TracyD3D11ZoneS( ctx,  \fBname\fP,  \fBdepth\fP)"

.SS "#define TracyD3D11ZoneTransient( ctx,  varname,  \fBname\fP,  active)"

.SS "#define TracyD3D11ZoneTransientS( ctx,  varname,  \fBname\fP,  \fBdepth\fP,  active)"

.SH "Typedef Documentation"
.PP 
.SS "using \fBTracyD3D11Ctx\fP = \fBvoid\fP*"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
