.TH "adhed/glm/gtx/transform.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/transform.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./glm\&.hpp'\fP
.br
\fR#include '\&.\&./gtc/matrix_transform\&.hpp'\fP
.br
\fR#include 'transform\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::translate\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::rotate\fP (\fBT\fP \fBangle\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::scale\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_transform\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTC_matrix_transform\fP (dependence) 
.PP
\fBGLM_GTX_transform\fP 
.PP
\fBGLM_GTX_transform2\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
