.TH "UPRISE_ENGINE/TRANSFORM.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UPRISE_ENGINE/TRANSFORM.h
.SH SYNOPSIS
.br
.PP
\fR#include 'HeaderE/CORE/CORE\&.h'\fP
.br
\fR#include 'HeaderE/DATATYPES/D_DATATYPES\&.h'\fP
.br
\fR#include 'DEBUG_LOGGER\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTransform\fP"
.br
.RI "#include 'HeaderE/DATATYPES/D_TS_P_VECTOR3\&.h' "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_TRANSFORM_\fP"
.br
.ti -1c
.RI "#define \fBADDROTATION\fP(\fBX\fP,  \fBY\fP,  \fBZ\fP)   TRANSFORM\->SetRotation(\fBDATATYPES::TS_P_Vector3\fP(pos\->Vec3Rotation\&.x+(\fBX\fP), pos\->Vec3Rotation\&.y+(\fBY\fP), pos\->Vec3Rotation\&.z +(\fBZ\fP)));"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _TRANSFORM_"

.PP
Definition at line \fB3\fP of file \fBTRANSFORM\&.h\fP\&.
.SS "#define ADDROTATION( \fBX\fP,  \fBY\fP,  \fBZ\fP)   TRANSFORM\->SetRotation(\fBDATATYPES::TS_P_Vector3\fP(pos\->Vec3Rotation\&.x+(\fBX\fP), pos\->Vec3Rotation\&.y+(\fBY\fP), pos\->Vec3Rotation\&.z +(\fBZ\fP)));"

.PP
Definition at line \fB47\fP of file \fBTRANSFORM\&.h\fP\&.
.PP
Referenced by \fBTest::Update()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
