.TH "adhed/glm/gtx/transform2.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/transform2.inl
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > \fBglm::shearX2D\fP (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const &m, \fBT\fP s)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > \fBglm::shearY2D\fP (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const &m, \fBT\fP s)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::shearX3D\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBT\fP s, \fBT\fP \fBt\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::shearY3D\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBT\fP s, \fBT\fP \fBt\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::shearZ3D\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBT\fP s, \fBT\fP \fBt\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > \fBglm::reflect2D\fP (\fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > const &m, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &normal)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::reflect3D\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &normal)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > \fBglm::proj2D\fP (const \fBmat\fP< 3, 3, \fBT\fP, \fBQ\fP > &m, const \fBvec\fP< 3, \fBT\fP, \fBQ\fP > &normal)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::proj3D\fP (const \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > &m, const \fBvec\fP< 3, \fBT\fP, \fBQ\fP > &normal)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::scaleBias\fP (\fBT\fP \fBscale\fP, \fBT\fP bias)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::scaleBias\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBT\fP \fBscale\fP, \fBT\fP bias)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
