.TH "TS_P_Collider_box" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TS_P_Collider_box
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <PHYSICS_OBJECT\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBTS_P_Vector3\fP = \fBDATATYPES::TS_P_Vector3\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisTrigger\fP"
.br
.ti -1c
.RI "\fBDATATYPES::TS_P_Vector3\fP \fBOrigin\fP"
.br
.ti -1c
.RI "\fBTS_P_Vector3\fP \fBbounds\fP"
.br
.ti -1c
.RI "\fBTS_P_Vector3\fP \fBa\fP"
.br
.ti -1c
.RI "\fBTS_P_Vector3\fP \fBb\fP"
.br
.ti -1c
.RI "\fBTS_P_Vector3\fP \fBc\fP"
.br
.ti -1c
.RI "\fBTS_P_Vector3\fP \fBd\fP"
.br
.ti -1c
.RI "\fBTS_P_Vector3\fP \fBe\fP"
.br
.ti -1c
.RI "\fBTS_P_Vector3\fP \fBf\fP"
.br
.ti -1c
.RI "\fBTS_P_Vector3\fP \fBg\fP"
.br
.ti -1c
.RI "\fBTS_P_Vector3\fP \fBh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBPHYSICS_OBJECT\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBTS_P_Collider_box::TS_P_Vector3\fP = \fBDATATYPES::TS_P_Vector3\fP"

.PP
Definition at line \fB17\fP of file \fBPHYSICS_OBJECT\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTS_P_Vector3\fP TS_P_Collider_box::a"

.PP
Definition at line \fB21\fP of file \fBPHYSICS_OBJECT\&.h\fP\&.
.PP
Referenced by \fBPHYSICS::Physics::updateBox()\fP\&.
.SS "\fBTS_P_Vector3\fP TS_P_Collider_box::b"

.PP
Definition at line \fB22\fP of file \fBPHYSICS_OBJECT\&.h\fP\&.
.PP
Referenced by \fBPHYSICS::Physics::updateBox()\fP\&.
.SS "\fBTS_P_Vector3\fP TS_P_Collider_box::bounds"

.PP
Definition at line \fB20\fP of file \fBPHYSICS_OBJECT\&.h\fP\&.
.PP
Referenced by \fBPHYSICS::Physics::updateBox()\fP\&.
.SS "\fBTS_P_Vector3\fP TS_P_Collider_box::c"

.PP
Definition at line \fB23\fP of file \fBPHYSICS_OBJECT\&.h\fP\&.
.PP
Referenced by \fBPHYSICS::Physics::updateBox()\fP\&.
.SS "\fBTS_P_Vector3\fP TS_P_Collider_box::d"

.PP
Definition at line \fB24\fP of file \fBPHYSICS_OBJECT\&.h\fP\&.
.PP
Referenced by \fBPHYSICS::Physics::updateBox()\fP\&.
.SS "\fBTS_P_Vector3\fP TS_P_Collider_box::e"

.PP
Definition at line \fB25\fP of file \fBPHYSICS_OBJECT\&.h\fP\&.
.PP
Referenced by \fBPHYSICS::Physics::updateBox()\fP\&.
.SS "\fBTS_P_Vector3\fP TS_P_Collider_box::f"

.PP
Definition at line \fB26\fP of file \fBPHYSICS_OBJECT\&.h\fP\&.
.PP
Referenced by \fBPHYSICS::Physics::updateBox()\fP\&.
.SS "\fBTS_P_Vector3\fP TS_P_Collider_box::g"

.PP
Definition at line \fB27\fP of file \fBPHYSICS_OBJECT\&.h\fP\&.
.PP
Referenced by \fBPHYSICS::Physics::updateBox()\fP\&.
.SS "\fBTS_P_Vector3\fP TS_P_Collider_box::h"

.PP
Definition at line \fB28\fP of file \fBPHYSICS_OBJECT\&.h\fP\&.
.PP
Referenced by \fBPHYSICS::Physics::updateBox()\fP\&.
.SS "bool TS_P_Collider_box::isTrigger"

.PP
Definition at line \fB18\fP of file \fBPHYSICS_OBJECT\&.h\fP\&.
.SS "\fBDATATYPES::TS_P_Vector3\fP TS_P_Collider_box::Origin"

.PP
Definition at line \fB19\fP of file \fBPHYSICS_OBJECT\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
