.TH "TS_P_Vector2" 3 "Version 0.0.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TS_P_Vector2
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <TS_P_VECOTR2\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTS_P_Vector2\fP ()"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP (float \fBx\fP, float \fBy\fP)"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP (const \fBTS_P_Vector2\fP &other)=default"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP & \fBoperator=\fP (const \fBTS_P_Vector2\fP &other)=default"
.br
.ti -1c
.RI "\fBoperator __m128\fP () const"
.br
.ti -1c
.RI "float \fBmagnitude\fP ()"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP \fBNormalized\fP ()"
.br
.ti -1c
.RI "float \fBpoint\fP (\fBTS_P_Vector2\fP a)"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP \fBoperator/\fP (const float b)"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP \fBoperator/\fP (const \fBTS_P_Vector2\fP b)"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP \fBoperator*\fP (const float b)"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP \fBoperator*\fP (const \fBTS_P_Vector2\fP b)"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP \fBoperator\-\fP (const \fBTS_P_Vector2\fP b)"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP \fBoperator+\fP (const \fBTS_P_Vector2\fP b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBpad1\fP"
.br
.ti -1c
.RI "float \fBpad2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBTS_P_VECOTR2\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TS_P_Vector2::TS_P_Vector2 ()"

.PP
Definition at line \fB3\fP of file \fBTS_P_VECOTR2\&.cpp\fP\&.
.SS "TS_P_Vector2::TS_P_Vector2 (float x, float y)"

.PP
Definition at line \fB7\fP of file \fBTS_P_VECOTR2\&.cpp\fP\&.
.SS "TS_P_Vector2::TS_P_Vector2 (const \fBTS_P_Vector2\fP & other)\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "float TS_P_Vector2::magnitude ()"

.PP
Definition at line \fB18\fP of file \fBTS_P_VECOTR2\&.cpp\fP\&.
.SS "\fBTS_P_Vector2\fP TS_P_Vector2::Normalized ()"

.PP
Definition at line \fB24\fP of file \fBTS_P_VECOTR2\&.cpp\fP\&.
.SS "TS_P_Vector2::operator __m128 () const"

.PP
Definition at line \fB13\fP of file \fBTS_P_VECOTR2\&.cpp\fP\&.
.SS "\fBTS_P_Vector2\fP TS_P_Vector2::operator* (const float b)"

.PP
Definition at line \fB53\fP of file \fBTS_P_VECOTR2\&.cpp\fP\&.
.SS "\fBTS_P_Vector2\fP TS_P_Vector2::operator* (const \fBTS_P_Vector2\fP b)"

.PP
Definition at line \fB63\fP of file \fBTS_P_VECOTR2\&.cpp\fP\&.
.SS "\fBTS_P_Vector2\fP TS_P_Vector2::operator+ (const \fBTS_P_Vector2\fP b)"

.PP
Definition at line \fB83\fP of file \fBTS_P_VECOTR2\&.cpp\fP\&.
.SS "\fBTS_P_Vector2\fP TS_P_Vector2::operator\- (const \fBTS_P_Vector2\fP b)"

.PP
Definition at line \fB73\fP of file \fBTS_P_VECOTR2\&.cpp\fP\&.
.SS "\fBTS_P_Vector2\fP TS_P_Vector2::operator/ (const float b)"

.PP
Definition at line \fB34\fP of file \fBTS_P_VECOTR2\&.cpp\fP\&.
.SS "\fBTS_P_Vector2\fP TS_P_Vector2::operator/ (const \fBTS_P_Vector2\fP b)"

.PP
Definition at line \fB43\fP of file \fBTS_P_VECOTR2\&.cpp\fP\&.
.SS "\fBTS_P_Vector2\fP & TS_P_Vector2::operator= (const \fBTS_P_Vector2\fP & other)\fR [default]\fP"

.SS "float TS_P_Vector2::point (\fBTS_P_Vector2\fP a)"

.PP
Definition at line \fB29\fP of file \fBTS_P_VECOTR2\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float TS_P_Vector2::pad1"

.PP
Definition at line \fB10\fP of file \fBTS_P_VECOTR2\&.h\fP\&.
.SS "float TS_P_Vector2::pad2"

.PP
Definition at line \fB10\fP of file \fBTS_P_VECOTR2\&.h\fP\&.
.SS "float TS_P_Vector2::x"

.PP
Definition at line \fB8\fP of file \fBTS_P_VECOTR2\&.h\fP\&.
.SS "float TS_P_Vector2::y"

.PP
Definition at line \fB9\fP of file \fBTS_P_VECOTR2\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
