.TH "TS_P_Vector2" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TS_P_Vector2
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <D_TS_P_VECOTR2\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTS_P_Vector2\fP ()"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP (float \fBx\fP, float \fBy\fP)"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP (const \fBTS_P_Vector2\fP &other)=default"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP & \fBoperator=\fP (const \fBTS_P_Vector2\fP &other)=default"
.br
.ti -1c
.RI "\fBoperator __m128\fP () const"
.br
.ti -1c
.RI "float \fBmagnitude\fP ()"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP \fBNormalized\fP ()"
.br
.ti -1c
.RI "float \fBpoint\fP (\fBTS_P_Vector2\fP a)"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP \fBoperator/\fP (const float b)"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP \fBoperator/\fP (const \fBTS_P_Vector2\fP b)"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP \fBoperator*\fP (const float b)"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP \fBoperator*\fP (const \fBTS_P_Vector2\fP b)"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP \fBoperator\-\fP (const \fBTS_P_Vector2\fP b)"
.br
.ti -1c
.RI "\fBTS_P_Vector2\fP \fBoperator+\fP (const \fBTS_P_Vector2\fP b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBpad1\fP"
.br
.ti -1c
.RI "float \fBpad2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBD_TS_P_VECOTR2\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TS_P_Vector2::TS_P_Vector2 ()"

.PP
Definition at line \fB4\fP of file \fBD_TS_P_VECOTR2\&.cpp\fP\&.
.nf
4                            :x(0), y(0), pad1(0), pad2(0)
5 {
6 }
.PP
.fi

.PP
Referenced by \fBNormalized()\fP\&.
.SS "TS_P_Vector2::TS_P_Vector2 (float x, float y)"

.PP
Definition at line \fB8\fP of file \fBD_TS_P_VECOTR2\&.cpp\fP\&.
.nf
8                                           :x(x),y(y),pad1(0),pad2(0)
9 {
10 }
.PP
.fi

.SS "TS_P_Vector2::TS_P_Vector2 (const \fBTS_P_Vector2\fP & other)\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "float TS_P_Vector2::magnitude ()"

.PP
Definition at line \fB20\fP of file \fBD_TS_P_VECOTR2\&.cpp\fP\&.
.nf
21 {
22     __m128 val = _mm_setr_ps(x, y, pad1, pad2);
23     return _mm_cvtss_f32(_mm_sqrt_ps(_mm_hadd_ps(_mm_mul_ps(val, val), _mm_setzero_ps())));
24 }
.PP
.fi

.PP
References \fBpad1\fP, \fBpad2\fP, \fBx\fP, and \fBy\fP\&.
.SS "\fBTS_P_Vector2\fP TS_P_Vector2::Normalized ()"

.PP
Definition at line \fB26\fP of file \fBD_TS_P_VECOTR2\&.cpp\fP\&.
.nf
27 {
28     return TS_P_Vector2();
29 }
.PP
.fi

.PP
References \fBTS_P_Vector2()\fP\&.
.SS "TS_P_Vector2::operator __m128 () const"

.PP
Definition at line \fB14\fP of file \fBD_TS_P_VECOTR2\&.cpp\fP\&.
.nf
15 {
16   //TrPr(ctx, __func__)(TracyCZoneCtx ctx)
17     return _mm_setr_ps(x, y, pad1, pad2);
18 }
.PP
.fi

.SS "\fBTS_P_Vector2\fP TS_P_Vector2::operator* (const float b)"

.PP
Definition at line \fB61\fP of file \fBD_TS_P_VECOTR2\&.cpp\fP\&.
.nf
62 {
63 
64     TrPr(ctx, __func__)
65         TS_P_Vector2 _tmp;
66     __m128 val = _mm_setr_ps(x, y, pad1, pad2);
67 
68     _mm_store_ps(&_tmp\&.x, _mm_mul_ps(val, _mm_set_ps1(b)));
69 
70     TrPrE(ctx)
71         return _tmp;
72 }
.PP
.fi

.PP
References \fBpad1\fP, \fBpad2\fP, \fBTrPr\fP, \fBTrPrE\fP, \fBx\fP, and \fBy\fP\&.
.SS "\fBTS_P_Vector2\fP TS_P_Vector2::operator* (const \fBTS_P_Vector2\fP b)"

.PP
Definition at line \fB74\fP of file \fBD_TS_P_VECOTR2\&.cpp\fP\&.
.nf
75 {
76 
77     TrPr(ctx, __func__)
78         TS_P_Vector2 _tmp;
79     __m128 val = _mm_setr_ps(x, y, pad1, pad2);
80     __m128 val1 = _mm_setr_ps(b\&.x, b\&.y, b\&.pad1, b\&.pad2);
81 
82     _mm_store_ps(&_tmp\&.x, _mm_mul_ps(val, val1));
83 
84     TrPrE(ctx)
85         return _tmp;
86 }
.PP
.fi

.PP
References \fBpad1\fP, \fBpad2\fP, \fBTrPr\fP, \fBTrPrE\fP, \fBx\fP, and \fBy\fP\&.
.SS "\fBTS_P_Vector2\fP TS_P_Vector2::operator+ (const \fBTS_P_Vector2\fP b)"

.PP
Definition at line \fB101\fP of file \fBD_TS_P_VECOTR2\&.cpp\fP\&.
.nf
102 {
103     TrPr(ctx, __func__)
104         TS_P_Vector2 tmp;
105     __m128 this3 = _mm_setr_ps(x, y, pad1, pad2);
106     __m128 be = _mm_setr_ps(b\&.x, b\&.y, b\&.pad1, b\&.pad2);
107     _mm_store_ps(&tmp\&.x, _mm_add_ps(this3, be));
108 
109     TrPrE(ctx)
110         return tmp;
111 }
.PP
.fi

.PP
References \fBpad1\fP, \fBpad2\fP, \fBTrPr\fP, \fBTrPrE\fP, \fBx\fP, and \fBy\fP\&.
.SS "\fBTS_P_Vector2\fP TS_P_Vector2::operator\- (const \fBTS_P_Vector2\fP b)"

.PP
Definition at line \fB88\fP of file \fBD_TS_P_VECOTR2\&.cpp\fP\&.
.nf
89 {
90     TrPr(ctx, __func__)
91         __m128 val = _mm_setr_ps(x, y, pad1, pad2);
92 
93     __m128 val1 = _mm_setr_ps(b\&.x, b\&.y, b\&.pad1, b\&.pad2);
94     TS_P_Vector2 _tmp;
95     _mm_store_ps(&_tmp\&.x, _mm_sub_ps(val, val1));
96 
97     TrPrE(ctx)
98         return _tmp;
99 }
.PP
.fi

.PP
References \fBpad1\fP, \fBpad2\fP, \fBTrPr\fP, \fBTrPrE\fP, \fBx\fP, and \fBy\fP\&.
.SS "\fBTS_P_Vector2\fP TS_P_Vector2::operator/ (const float b)"

.PP
Definition at line \fB36\fP of file \fBD_TS_P_VECOTR2\&.cpp\fP\&.
.nf
37 {
38     TrPr(ctx,__func__)
39     TS_P_Vector2 _tmp;
40     __m128 val = _mm_setr_ps(x, y, pad1, pad2);
41 
42     _mm_store_ps(&_tmp\&.x, _mm_div_ps(val, _mm_set_ps1(b)));
43     TrPrE(ctx)
44     return _tmp;;
45 }
.PP
.fi

.PP
References \fBpad1\fP, \fBpad2\fP, \fBTrPr\fP, \fBTrPrE\fP, \fBx\fP, and \fBy\fP\&.
.SS "\fBTS_P_Vector2\fP TS_P_Vector2::operator/ (const \fBTS_P_Vector2\fP b)"

.PP
Definition at line \fB47\fP of file \fBD_TS_P_VECOTR2\&.cpp\fP\&.
.nf
48 {
49     TrPr(ctx, __func__)
50 
51     TS_P_Vector2 _tmp;
52     __m128 val = _mm_setr_ps(x, y, pad1, pad2);
53     __m128 val1 = _mm_setr_ps(b\&.x, b\&.y, b\&.pad1, b\&.pad2);
54 
55     _mm_store_ps(&_tmp\&.x, _mm_div_ps(val, val1));
56 
57     TrPrE(ctx)
58         return _tmp;
59 }
.PP
.fi

.PP
References \fBpad1\fP, \fBpad2\fP, \fBTrPr\fP, \fBTrPrE\fP, \fBx\fP, and \fBy\fP\&.
.SS "\fBTS_P_Vector2\fP & TS_P_Vector2::operator= (const \fBTS_P_Vector2\fP & other)\fR [default]\fP"

.SS "float TS_P_Vector2::point (\fBTS_P_Vector2\fP a)"

.PP
Definition at line \fB31\fP of file \fBD_TS_P_VECOTR2\&.cpp\fP\&.
.nf
32 {
33     return 0\&.0f;
34 }
.PP
.fi

.SH "Member Data Documentation"
.PP 
.SS "float TS_P_Vector2::pad1"

.PP
Definition at line \fB10\fP of file \fBD_TS_P_VECOTR2\&.h\fP\&.
.PP
Referenced by \fBmagnitude()\fP, \fBoperator*()\fP, \fBoperator*()\fP, \fBoperator+()\fP, \fBoperator\-()\fP, \fBoperator/()\fP, and \fBoperator/()\fP\&.
.SS "float TS_P_Vector2::pad2"

.PP
Definition at line \fB10\fP of file \fBD_TS_P_VECOTR2\&.h\fP\&.
.PP
Referenced by \fBmagnitude()\fP, \fBoperator*()\fP, \fBoperator*()\fP, \fBoperator+()\fP, \fBoperator\-()\fP, \fBoperator/()\fP, and \fBoperator/()\fP\&.
.SS "float TS_P_Vector2::x"

.PP
Definition at line \fB8\fP of file \fBD_TS_P_VECOTR2\&.h\fP\&.
.PP
Referenced by \fBmagnitude()\fP, \fBoperator*()\fP, \fBoperator*()\fP, \fBoperator+()\fP, \fBoperator\-()\fP, \fBoperator/()\fP, and \fBoperator/()\fP\&.
.SS "float TS_P_Vector2::y"

.PP
Definition at line \fB9\fP of file \fBD_TS_P_VECOTR2\&.h\fP\&.
.PP
Referenced by \fBmagnitude()\fP, \fBoperator*()\fP, \fBoperator*()\fP, \fBoperator+()\fP, \fBoperator\-()\fP, \fBoperator/()\fP, and \fBoperator/()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
