.TH "tst" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tst
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <test\&.h>\fP
.PP
Inherits \fBCORE::Behaviour\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBCORE::Behaviour\fP
.in +1c
.ti -1c
.RI "\fBBehaviour\fP ()"
.br
.ti -1c
.RI "\fBBehaviour\fP (\fBGameObject\fP *oobj, std::shared_ptr< \fBCORE::Behaviour\fP > trans)"
.br
.ti -1c
.RI "virtual std::shared_ptr< \fBCORE::Behaviour\fP > \fBCopy\fP ()=0"
.br
.ti -1c
.RI "virtual std::shared_ptr< \fBCORE::Behaviour\fP > \fBDeepCopy\fP ()=0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBEditorWindow\fP ()=0"
.br
.ti -1c
.RI "\fBBehaviour\fP ()"
.br
.ti -1c
.RI "\fBBehaviour\fP (int remove)"
.br
.ti -1c
.RI "\fBBehaviour\fP (\fBGameObject\fP *oobj, std::shared_ptr< \fBCORE::Behaviour\fP > trans)"
.br
.ti -1c
.RI "virtual std::shared_ptr< \fBCORE::Behaviour\fP > \fBCopy\fP ()=0"
.br
.ti -1c
.RI "virtual std::shared_ptr< \fBCORE::Behaviour\fP > \fBDeepCopy\fP ()=0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBEditorWindow\fP ()=0"
.br
.in -1c

Static Public Member Functions inherited from \fBCORE::Behaviour\fP
.in +1c
.ti -1c
.RI "static \fBvoid\fP \fBupdateAll\fP ()"
.br
.ti -1c
.RI "static \fBvoid\fP \fBupdateAllAWAKE\fP ()"
.br
.ti -1c
.RI "static \fBvoid\fP \fBupdateAllSTART\fP ()"
.br
.ti -1c
.RI "static \fBvoid\fP \fBupdateallParallel\fP ()"
.br
.ti -1c
.RI "static \fBvoid\fP \fBupdateAll\fP ()"
.br
.ti -1c
.RI "static \fBvoid\fP \fBupdateAllAWAKE\fP ()"
.br
.ti -1c
.RI "static \fBvoid\fP \fBupdateAllSTART\fP ()"
.br
.ti -1c
.RI "static \fBvoid\fP \fBupdateallParallel\fP ()"
.br
.in -1c

Public Attributes inherited from \fBCORE::Behaviour\fP
.in +1c
.ti -1c
.RI "\fBGameObject\fP * \fBgameobject\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBTransform\fP > \fBTRANSFORM\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBCORE::Behaviour\fP > \fBtransf\fP"
.br
.ti -1c
.RI "std::string \fBcompname\fP"
.br
.ti -1c
.RI "UUID \fBuuID\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "bool \fBToBeRemoved\fP"
.br
.ti -1c
.RI "bool \fBenabled\fP"
.br
.in -1c

Static Public Attributes inherited from \fBCORE::Behaviour\fP
.in +1c
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBCORE::Behaviour\fP > > \fBobjectss\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBBehaviour\fP > > \fBbehaviours\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBBehaviour\fP > > \fBAWAKES\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBBehaviour\fP > > \fBStarts\fP"
.br
.ti -1c
.RI "static std::vector< std::shared_ptr< \fBBehaviour\fP > > \fBParallel_Updates\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
