.TH "adhed/glm/detail/type_vec1.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/detail/type_vec1.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'qualifier\&.hpp'\fP
.br
\fR#include <cstddef>\fP
.br
\fR#include 'type_vec1\&.inl'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBglm::vec< 1, T, Q >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator+\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator\-\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator+\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator+\fP (\fBT\fP scalar, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator+\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator\-\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator\-\fP (\fBT\fP scalar, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator\-\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBT\fP scalar, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator/\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator/\fP (\fBT\fP scalar, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator/\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator%\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator%\fP (\fBT\fP scalar, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator%\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator&\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator&\fP (\fBT\fP scalar, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator&\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator|\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator|\fP (\fBT\fP scalar, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator|\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator^\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator^\fP (\fBT\fP scalar, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator^\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator<<\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator<<\fP (\fBT\fP scalar, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator<<\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator>>\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator>>\fP (\fBT\fP scalar, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator>>\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, \fBT\fP, \fBQ\fP > \fBglm::operator~\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP bool \fBglm::operator==\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP bool \fBglm::operator!=\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<\fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, bool, \fBQ\fP > \fBglm::operator&&\fP (\fBvec\fP< 1, bool, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, bool, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<\fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 1, bool, \fBQ\fP > \fBglm::operator||\fP (\fBvec\fP< 1, bool, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, bool, \fBQ\fP > const &\fBv2\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCore features\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
