.TH "adhed/glm/detail/type_mat4x4.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/detail/type_mat4x4.inl
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./matrix\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::operator+\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::operator\-\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::operator+\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::operator+\fP (\fBT\fP scalar, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::operator+\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m1, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m2)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::operator\-\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::operator\-\fP (\fBT\fP scalar, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::operator\-\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m1, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m2)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBT\fP scalar, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP >::col_type \fBglm::operator*\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, typename \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP >::row_type const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP >::row_type \fBglm::operator*\fP (typename \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP >::col_type const &\fBv\fP, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 2, 4, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m1, \fBmat\fP< 2, 4, \fBT\fP, \fBQ\fP > const &m2)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 3, 4, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m1, \fBmat\fP< 3, 4, \fBT\fP, \fBQ\fP > const &m2)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m1, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m2)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::operator/\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::operator/\fP (\fBT\fP scalar, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP >::col_type \fBglm::operator/\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m, typename \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP >::row_type const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP >::row_type \fBglm::operator/\fP (typename \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP >::col_type const &\fBv\fP, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > \fBglm::operator/\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m1, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m2)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP bool \fBglm::operator==\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m1, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m2)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP bool \fBglm::operator!=\fP (\fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m1, \fBmat\fP< 4, 4, \fBT\fP, \fBQ\fP > const &m2)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
