.TH "adhed/glm/detail/type_vec4.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/detail/type_vec4.inl
.SH SYNOPSIS
.br
.PP
\fR#include 'compute_vector_relational\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBglm::detail::compute_vec4_add< T, Q, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec4_sub< T, Q, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec4_mul< T, Q, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec4_div< T, Q, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec4_mod< T, Q, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec4_and< T, Q, IsInt, Size, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec4_or< T, Q, IsInt, Size, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec4_xor< T, Q, IsInt, Size, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec4_shift_left< T, Q, IsInt, Size, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec4_shift_right< T, Q, IsInt, Size, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec4_equal< T, Q, IsInt, Size, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec4_nequal< T, Q, IsInt, Size, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_vec4_bitwise_not< T, Q, IsInt, Size, Aligned >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.ti -1c
.RI "namespace \fBglm::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator+\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator\-\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator+\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator+\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator+\fP (\fBT\fP scalar, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator+\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator+\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator\-\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator\-\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator\-\fP (\fBT\fP scalar, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator\-\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator\-\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBT\fP scalar, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator*\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator/\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator/\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator/\fP (\fBT\fP scalar, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator/\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator/\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator%\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator%\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator%\fP (\fBT\fP scalar, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator%\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &scalar, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator%\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator&\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator&\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator&\fP (\fBT\fP scalar, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator&\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator&\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator|\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator|\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator|\fP (\fBT\fP scalar, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator|\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator|\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator^\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator^\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator^\fP (\fBT\fP scalar, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator^\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator^\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator<<\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator<<\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator<<\fP (\fBT\fP scalar, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator<<\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator<<\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator>>\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP, \fBT\fP scalar)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator>>\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator>>\fP (\fBT\fP scalar, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator>>\fP (\fBvec\fP< 1, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator>>\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::operator~\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP bool \fBglm::operator==\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP bool \fBglm::operator!=\fP (\fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, \fBT\fP, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<\fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, bool, \fBQ\fP > \fBglm::operator&&\fP (\fBvec\fP< 4, bool, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, bool, \fBQ\fP > const &\fBv2\fP)"
.br
.ti -1c
.RI "template<\fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< 4, bool, \fBQ\fP > \fBglm::operator||\fP (\fBvec\fP< 4, bool, \fBQ\fP > const &\fBv1\fP, \fBvec\fP< 4, bool, \fBQ\fP > const &\fBv2\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
