.TH "adhed/glm/detail/type_half.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/detail/type_half.inl
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "union \fBglm::detail::uif32\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.ti -1c
.RI "namespace \fBglm::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGLM_FUNC_QUALIFIER\fP float \fBglm::detail::overflow\fP ()"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP float \fBglm::detail::toFloat32\fP (\fBhdata\fP \fBvalue\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBhdata\fP \fBglm::detail::toFloat16\fP (float const &\fBvalue\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
