.TH "adhed/glm/gtc/ulp.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtc/ulp.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./detail/setup\&.hpp'\fP
.br
\fR#include '\&.\&./detail/qualifier\&.hpp'\fP
.br
\fR#include '\&.\&./detail/_vectorize\&.hpp'\fP
.br
\fR#include '\&.\&./ext/scalar_int_sized\&.hpp'\fP
.br
\fR#include 'ulp\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::next_float\fP (genType \fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::prev_float\fP (genType \fBx\fP)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::next_float\fP (genType \fBx\fP, int ULPs)"
.br
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_DECL\fP genType \fBglm::prev_float\fP (genType \fBx\fP, int ULPs)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP int \fBglm::float_distance\fP (float \fBx\fP, float \fBy\fP)"
.br
.ti -1c
.RI "\fBGLM_FUNC_DECL\fP \fBint64\fP \fBglm::float_distance\fP (double \fBx\fP, double \fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::next_float\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::next_float\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, int ULPs)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::next_float\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, int, \fBQ\fP > const &ULPs)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::prev_float\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::prev_float\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, int ULPs)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > \fBglm::prev_float\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, int, \fBQ\fP > const &ULPs)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, int, \fBQ\fP > \fBglm::float_distance\fP (\fBvec\fP< \fBL\fP, float, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, float, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_DECL\fP \fBvec\fP< \fBL\fP, \fBint64\fP, \fBQ\fP > \fBglm::float_distance\fP (\fBvec\fP< \fBL\fP, double, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, double, \fBQ\fP > const &\fBy\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTC_ulp\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
