.TH "UTILLS::Shared_ptr< _Ty >" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UTILLS::Shared_ptr< _Ty >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <C_SMART_POINTER\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBTYPE\fP = _Ty"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTYPE\fP * \fBGT\fP ()"
.br
.ti -1c
.RI "\fBShared_ptr\fP ()"
.br
.ti -1c
.RI "\fBShared_ptr\fP (_Ty *ptr)"
.br
.ti -1c
.RI "\fBShared_ptr\fP (const \fBShared_ptr\fP &other)"
.br
.ti -1c
.RI "template<class _Ty2 > \fBShared_ptr\fP (\fBShared_ptr\fP< _Ty2 > &&other)"
.br
.ti -1c
.RI "\fB~Shared_ptr\fP ()"
.br
.ti -1c
.RI "template<class _Ty2 > \fBShared_ptr\fP & \fBoperator=\fP (const \fBShared_ptr\fP< _Ty2 > &&other)"
.br
.ti -1c
.RI "template<class _Ty2 > \fBShared_ptr\fP (const \fBShared_ptr\fP< _Ty2 > &other, typename std::enable_if< std::is_convertible< _Ty2 *, _Ty * >::value >::type *=nullptr)"
.br
.ti -1c
.RI "template<class _Ty2 > \fBShared_ptr\fP & \fBoperator=\fP (const \fBShared_ptr\fP< _Ty2 > &other)"
.br
.ti -1c
.RI "_Ty * \fBoperator\->\fP ()"
.br
.ti -1c
.RI "void \fBrelease\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBIptr\fP"
.br
.ti -1c
.RI "long * \fBpointer\fP"
.br
.ti -1c
.RI "_Ty ** \fBPointer\fP"
.br
.ti -1c
.RI "\fBREF_block\fP * \fBref_block\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class _Ty>
.br
class UTILLS::Shared_ptr< _Ty >"
.PP
Definition at line \fB25\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class _Ty > using \fBUTILLS::Shared_ptr\fP< _Ty >::TYPE = _Ty"

.PP
Definition at line \fB27\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class _Ty > \fBUTILLS::Shared_ptr\fP< _Ty >::Shared_ptr ()\fR [inline]\fP"

.PP
Definition at line \fB35\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
35                      :Pointer(nullptr),ref_block(nullptr) {
36 
37         }
.PP
.fi

.SS "template<class _Ty > \fBUTILLS::Shared_ptr\fP< _Ty >::Shared_ptr (_Ty * ptr)\fR [inline]\fP"

.PP
Definition at line \fB38\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
38                              :  ref_block(new REF_block()) {
39             //Iptr = (long)ptr;
40             //pointer = &Iptr;
41             Pointer = &ptr;
42 
43         }
.PP
.fi

.PP
References \fBUTILLS::Shared_ptr< _Ty >::Pointer\fP\&.
.SS "template<class _Ty > \fBUTILLS::Shared_ptr\fP< _Ty >::Shared_ptr (const \fBShared_ptr\fP< _Ty > & other)\fR [inline]\fP"

.PP
Definition at line \fB45\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
45                                             : ref_block(other\&.ref_block) {
46             this\->Pointer = (TYPE**)(other\&.Pointer);
47             *this\->Pointer = *other\&.Pointer;
48             if (ref_block) {
49                 ref_block\->increment();
50             }
51         }
.PP
.fi

.PP
References \fBUTILLS::REF_block::increment()\fP, \fBUTILLS::Shared_ptr< _Ty >::Pointer\fP, and \fBUTILLS::Shared_ptr< _Ty >::ref_block\fP\&.
.SS "template<class _Ty > template<class _Ty2 > \fBUTILLS::Shared_ptr\fP< _Ty >::Shared_ptr (\fBShared_ptr\fP< _Ty2 > && other)\fR [inline]\fP"

.PP
Definition at line \fB54\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
54                                               {
55             this\->Pointer = (TYPE**)(other\&.Pointer);
56             *this\->Pointer = *other\&.Pointer;
57 
58         }
.PP
.fi

.SS "template<class _Ty > \fBUTILLS::Shared_ptr\fP< _Ty >::~\fBShared_ptr\fP ()\fR [inline]\fP"

.PP
Definition at line \fB60\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
60                      {
61             release();
62         }
.PP
.fi

.PP
References \fBUTILLS::Shared_ptr< _Ty >::release()\fP\&.
.SS "template<class _Ty > template<class _Ty2 > \fBUTILLS::Shared_ptr\fP< _Ty >::Shared_ptr (const \fBShared_ptr\fP< _Ty2 > & other, typename std::enable_if< std::is_convertible< _Ty2 *, _Ty * >::value >::type *  = \fRnullptr\fP)\fR [inline]\fP"

.PP
Definition at line \fB71\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
72             :  ref_block(other\&.ref_block) {
73             this\->Pointer = (TYPE**) (other\&.Pointer);
74             *this\->Pointer = *other\&.Pointer;
75             if (ref_block) {
76                 ref_block\->increment();
77             }
78         }
.PP
.fi

.PP
References \fBUTILLS::REF_block::increment()\fP, \fBUTILLS::Shared_ptr< _Ty >::Pointer\fP, and \fBUTILLS::Shared_ptr< _Ty >::ref_block\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class _Ty > \fBTYPE\fP * \fBUTILLS::Shared_ptr\fP< _Ty >::GT ()\fR [inline]\fP"

.PP
Definition at line \fB32\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
32                    {
33             return (TYPE*)(*pointer);
34         }
.PP
.fi

.SS "template<class _Ty > _Ty * \fBUTILLS::Shared_ptr\fP< _Ty >::operator\-> ()\fR [inline]\fP"

.PP
Definition at line \fB92\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
92                           {
93             return *Pointer;
94         }
.PP
.fi

.PP
References \fBUTILLS::Shared_ptr< _Ty >::Pointer\fP\&.
.SS "template<class _Ty > template<class _Ty2 > \fBShared_ptr\fP & \fBUTILLS::Shared_ptr\fP< _Ty >::operator= (const \fBShared_ptr\fP< _Ty2 > && other)\fR [inline]\fP"

.PP
Definition at line \fB64\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
64                                                               {
65             this\->Pointer = (TYPE**)(other\&.Pointer);
66             *this\->Pointer = *other\&.Pointer;
67             this\->ref_block = other\&.ref_block;
68 
69         }
.PP
.fi

.PP
References \fBUTILLS::Shared_ptr< _Ty >::Pointer\fP\&.
.SS "template<class _Ty > template<class _Ty2 > \fBShared_ptr\fP & \fBUTILLS::Shared_ptr\fP< _Ty >::operator= (const \fBShared_ptr\fP< _Ty2 > & other)\fR [inline]\fP"

.PP
Definition at line \fB80\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
80                                                              {
81             if (this != reinterpret_cast<const void*>(&other)) {
82                 release();
83                 this\->Pointer = (TYPE**)(other\&.Pointer);
84                 *this\->Pointer = *other\&.Pointer;
85                 ref_block = other\&.ref_block;
86                 if (ref_block) {
87                     ref_block\->increment();
88                 }
89             }
90             return *this;
91         }
.PP
.fi

.PP
References \fBUTILLS::REF_block::increment()\fP, \fBUTILLS::Shared_ptr< _Ty >::Pointer\fP, \fBUTILLS::Shared_ptr< _Ty >::ref_block\fP, and \fBUTILLS::Shared_ptr< _Ty >::release()\fP\&.
.SS "template<class _Ty > void \fBUTILLS::Shared_ptr\fP< _Ty >::release ()\fR [inline]\fP"

.PP
Definition at line \fB96\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
96                        {
97             if (ref_block) {
98                 ref_block\->decrement();
99                 if (ref_block\->getCount() == 0) {
100                     delete *Pointer;
101                     delete ref_block;
102                 }
103             }
104             Pointer = nullptr;
105             ref_block = nullptr;
106         }
.PP
.fi

.PP
References \fBUTILLS::REF_block::decrement()\fP, \fBUTILLS::REF_block::getCount()\fP, \fBUTILLS::Shared_ptr< _Ty >::Pointer\fP, and \fBUTILLS::Shared_ptr< _Ty >::ref_block\fP\&.
.PP
Referenced by \fBUTILLS::Shared_ptr< _Ty >::operator=()\fP, and \fBUTILLS::Shared_ptr< _Ty >::~Shared_ptr()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class _Ty > long \fBUTILLS::Shared_ptr\fP< _Ty >::Iptr"

.PP
Definition at line \fB28\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.SS "template<class _Ty > _Ty** \fBUTILLS::Shared_ptr\fP< _Ty >::Pointer"

.PP
Definition at line \fB30\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.PP
Referenced by \fBUTILLS::Shared_ptr< _Ty >::operator\->()\fP, \fBUTILLS::Shared_ptr< _Ty >::operator=()\fP, \fBUTILLS::Shared_ptr< _Ty >::operator=()\fP, \fBUTILLS::Shared_ptr< _Ty >::release()\fP, \fBUTILLS::Shared_ptr< _Ty >::Shared_ptr()\fP, \fBUTILLS::Shared_ptr< _Ty >::Shared_ptr()\fP, and \fBUTILLS::Shared_ptr< _Ty >::Shared_ptr()\fP\&.
.SS "template<class _Ty > long* \fBUTILLS::Shared_ptr\fP< _Ty >::pointer"

.PP
Definition at line \fB29\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.SS "template<class _Ty > \fBREF_block\fP* \fBUTILLS::Shared_ptr\fP< _Ty >::ref_block"

.PP
Definition at line \fB31\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.PP
Referenced by \fBUTILLS::Shared_ptr< _Ty >::operator=()\fP, \fBUTILLS::Shared_ptr< _Ty >::release()\fP, \fBUTILLS::Shared_ptr< _Ty >::Shared_ptr()\fP, and \fBUTILLS::Shared_ptr< _Ty >::Shared_ptr()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
