.TH "UTILLS::REF_block" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UTILLS::REF_block
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <C_SMART_POINTER\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBREF_block\fP ()"
.br
.ti -1c
.RI "void \fBincrement\fP ()"
.br
.ti -1c
.RI "void \fBdecrement\fP ()"
.br
.ti -1c
.RI "int \fBgetCount\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBref_cout\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UTILLS::REF_block::REF_block ()\fR [inline]\fP"

.PP
Definition at line \fB19\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
19 :ref_cout(1){}
.PP
.fi

.SH "Member Function Documentation"
.PP 
.SS "void UTILLS::REF_block::decrement ()\fR [inline]\fP"

.PP
Definition at line \fB21\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
21 { \-\-ref_cout; }
.PP
.fi

.PP
References \fBref_cout\fP\&.
.PP
Referenced by \fBUTILLS::Shared_ptr< _Ty >::release()\fP\&.
.SS "int UTILLS::REF_block::getCount () const\fR [inline]\fP"

.PP
Definition at line \fB22\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
22 { return ref_cout; }
.PP
.fi

.PP
References \fBref_cout\fP\&.
.PP
Referenced by \fBUTILLS::Shared_ptr< _Ty >::release()\fP\&.
.SS "void UTILLS::REF_block::increment ()\fR [inline]\fP"

.PP
Definition at line \fB20\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
20 { ++ref_cout; }
.PP
.fi

.PP
References \fBref_cout\fP\&.
.PP
Referenced by \fBUTILLS::Shared_ptr< _Ty >::operator=()\fP, \fBUTILLS::Shared_ptr< _Ty >::Shared_ptr()\fP, and \fBUTILLS::Shared_ptr< _Ty >::Shared_ptr()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int UTILLS::REF_block::ref_cout"

.PP
Definition at line \fB18\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.PP
Referenced by \fBdecrement()\fP, \fBgetCount()\fP, and \fBincrement()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
