.TH "UTILLS" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UTILLS
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPTR_base\fP"
.br
.ti -1c
.RI "class \fBREF_block\fP"
.br
.ti -1c
.RI "class \fBShared_ptr\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class _Ty , class\&.\&.\&. Args> \fBShared_ptr\fP< _Ty > \fBMake_Shared\fP (Args &&\&.\&.\&. args)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<class _Ty , class\&.\&.\&. Args> \fBShared_ptr\fP< _Ty > UTILLS::Make_Shared (Args &&\&.\&.\&. args)"

.PP
Definition at line \fB110\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
110                                                 {
111         return Shared_ptr<_Ty>(new _Ty(std::forward<Args>(args)\&.\&.\&.));
112     }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
