.TH "UTILLS::PTR_base< _Ty >" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UTILLS::PTR_base< _Ty >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <C_SMART_POINTER\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPTR_base\fP ()"
.br
.ti -1c
.RI "virtual \fB~PTR_base\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class _Ty>
.br
class UTILLS::PTR_base< _Ty >"
.PP
Definition at line \fB9\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class _Ty > \fBUTILLS::PTR_base\fP< _Ty >::PTR_base ()\fR [inline]\fP"

.PP
Definition at line \fB11\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
11                    {
12 
13         }
.PP
.fi

.SS "template<class _Ty > virtual \fBUTILLS::PTR_base\fP< _Ty >::~\fBPTR_base\fP ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Definition at line \fB14\fP of file \fBC_SMART_POINTER\&.h\fP\&.
.nf
14 {}
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
