.TH "adhed/glm/vec4.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/vec4.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&./ext/vector_bool4\&.hpp'\fP
.br
\fR#include '\&./ext/vector_bool4_precision\&.hpp'\fP
.br
\fR#include '\&./ext/vector_float4\&.hpp'\fP
.br
\fR#include '\&./ext/vector_float4_precision\&.hpp'\fP
.br
\fR#include '\&./ext/vector_double4\&.hpp'\fP
.br
\fR#include '\&./ext/vector_double4_precision\&.hpp'\fP
.br
\fR#include '\&./ext/vector_int4\&.hpp'\fP
.br
\fR#include '\&./ext/vector_int4_sized\&.hpp'\fP
.br
\fR#include '\&./ext/vector_uint4\&.hpp'\fP
.br
\fR#include '\&./ext/vector_uint4_sized\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
\fBCore features\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
