.TH "adhed/glm/gtx/vec_swizzle.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/vec_swizzle.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./glm\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::xx\fP (const \fBglm::vec\fP< 1, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::xx\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::xx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::xx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::xy\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::xy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::xy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::xz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::xz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::xw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::yx\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::yx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::yx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::yy\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::yy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::yy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::yz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::yz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::yw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::zx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::zx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::zy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::zy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::zz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::zz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::zw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::wx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::wy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::wz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > \fBglm::ww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xxx\fP (const \fBglm::vec\fP< 1, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xxx\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xxx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xxy\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xxy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xxz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xyx\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xyx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xyy\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xyy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xyz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xzx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xzy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xzz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xwx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xwy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xwz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::xww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yxx\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yxx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yxy\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yxy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yxz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yyx\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yyx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yyy\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yyy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yyz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yzx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yzy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yzz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::ywx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::ywy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::ywz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::yww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zxx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zxy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zxz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zyx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zyy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zyz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zzx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zzy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zzz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zwx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zwy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zwz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::zww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::wxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::wxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::wxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::wxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::wyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::wyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::wyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::wyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::wzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::wzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::wzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::wzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::wwx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::wwy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::wwz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > \fBglm::www\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxxx\fP (const \fBglm::vec\fP< 1, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxxx\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxxx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxxy\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxxy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxxz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxyx\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxyx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxyy\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxyy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxyz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxzx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxzy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxzz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxwx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxwy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxwz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xxww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyxx\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyxx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyxy\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyxy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyxz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyyx\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyyx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyyy\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyyy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyyz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyzx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyzy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyzz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xywx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xywy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xywz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xyww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzxx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzxy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzxz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzyx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzyy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzyz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzzx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzzy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzzz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzwx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzwy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzwz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xzww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xwxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xwxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xwxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xwxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xwyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xwyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xwyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xwyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xwzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xwzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xwzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xwzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xwwx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xwwy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xwwz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::xwww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxxx\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxxx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxxy\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxxy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxxz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxyx\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxyx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxyy\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxyy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxyz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxzx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxzy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxzz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxwx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxwy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxwz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yxww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyxx\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyxx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyxy\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyxy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyxz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyyx\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyyx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyyy\fP (const \fBglm::vec\fP< 2, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyyy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyyz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyzx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyzy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyzz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yywx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yywy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yywz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yyww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzxx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzxy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzxz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzyx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzyy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzyz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzzx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzzy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzzz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzwx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzwy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzwz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::yzww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::ywxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::ywxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::ywxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::ywxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::ywyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::ywyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::ywyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::ywyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::ywzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::ywzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::ywzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::ywzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::ywwx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::ywwy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::ywwz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::ywww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxxx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxxy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxxz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxyx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxyy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxyz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxzx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxzy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxzz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxwx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxwy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxwz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zxww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyxx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyxy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyxz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyyx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyyy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyyz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyzx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyzy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyzz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zywx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zywy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zywz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zyww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzxx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzxy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzxz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzyx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzyy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzyz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzzx\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzzy\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzzz\fP (const \fBglm::vec\fP< 3, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzwx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzwy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzwz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zzww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zwxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zwxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zwxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zwxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zwyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zwyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zwyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zwyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zwzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zwzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zwzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zwzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zwwx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zwwy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zwwz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::zwww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wxxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wxxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wxxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wxxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wxyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wxyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wxyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wxyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wxzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wxzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wxzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wxzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wxwx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wxwy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wxwz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wxww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wyxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wyxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wyxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wyxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wyyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wyyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wyyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wyyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wyzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wyzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wyzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wyzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wywx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wywy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wywz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wyww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wzxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wzxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wzxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wzxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wzyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wzyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wzyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wzyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wzzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wzzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wzzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wzzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wzwx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wzwy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wzwz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wzww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wwxx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wwxy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wwxz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wwxw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wwyx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wwyy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wwyz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wwyw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wwzx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wwzy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wwzz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wwzw\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wwwx\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wwwy\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wwwz\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > \fBglm::wwww\fP (const \fBglm::vec\fP< 4, \fBT\fP, \fBQ\fP > &\fBv\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_vec_swizzle\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
