.TH "adhed/glm/ext/vector_double4.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/ext/vector_double4.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./detail/type_vec4\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBvec\fP< 4, double, \fBdefaultp\fP > \fBglm::dvec4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCore features\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
