.TH "adhed/glm/ext/vector_double3_precision.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/ext/vector_double3_precision.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./detail/type_vec3\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBvec\fP< 3, double, \fBhighp\fP > \fBglm::highp_dvec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, double, \fBmediump\fP > \fBglm::mediump_dvec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, double, \fBlowp\fP > \fBglm::lowp_dvec3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCore features\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
