.TH "adhed/glm/ext/vector_relational.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/ext/vector_relational.inl
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./vector_relational\&.hpp'\fP
.br
\fR#include '\&.\&./common\&.hpp'\fP
.br
\fR#include '\&.\&./detail/qualifier\&.hpp'\fP
.br
\fR#include '\&.\&./detail/type_float\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, bool, \fBQ\fP > \fBglm::equal\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBT\fP Epsilon)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, bool, \fBQ\fP > \fBglm::equal\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &Epsilon)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, bool, \fBQ\fP > \fBglm::notEqual\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBT\fP Epsilon)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, bool, \fBQ\fP > \fBglm::notEqual\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &Epsilon)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, bool, \fBQ\fP > \fBglm::equal\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, int MaxULPs)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, bool, \fBQ\fP > \fBglm::equal\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, int, \fBQ\fP > const &MaxULPs)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, bool, \fBQ\fP > \fBglm::notEqual\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, int MaxULPs)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBGLM_CONSTEXPR\fP \fBvec\fP< \fBL\fP, bool, \fBQ\fP > \fBglm::notEqual\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< \fBL\fP, int, \fBQ\fP > const &MaxULPs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_vector_relational\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
