.TH "adhed/glm/gtx/vector_angle.inl" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/vector_angle.inl
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > \fBGLM_FUNC_QUALIFIER\fP genType \fBglm::angle\fP (genType const &\fBx\fP, genType const &\fBy\fP)"
.br
.ti -1c
.RI "template<\fBlength_t\fP L, typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::angle\fP (\fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< \fBL\fP, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::orientedAngle\fP (\fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< 2, \fBT\fP, \fBQ\fP > const &\fBy\fP)"
.br
.ti -1c
.RI "template<typename \fBT\fP , \fBqualifier\fP Q> \fBGLM_FUNC_QUALIFIER\fP \fBT\fP \fBglm::orientedAngle\fP (\fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBx\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBy\fP, \fBvec\fP< 3, \fBT\fP, \fBQ\fP > const &\fBref\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
