.TH "adhed/assimp/version.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/assimp/version.h \- Functions to query the version of the \fBAssimp\fP runtime, check compile flags, \&.\&.\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <assimp/defs\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAI_VERSION_H_INC\fP"
.br
.ti -1c
.RI "#define \fBASSIMP_CFLAGS_SHARED\fP   0x1"
.br
.RI "\fBAssimp\fP was compiled as a shared object (Windows: DLL) "
.ti -1c
.RI "#define \fBASSIMP_CFLAGS_STLPORT\fP   0x2"
.br
.RI "\fBAssimp\fP was compiled against STLport\&. "
.ti -1c
.RI "#define \fBASSIMP_CFLAGS_DEBUG\fP   0x4"
.br
.RI "\fBAssimp\fP was compiled as a debug build\&. "
.ti -1c
.RI "#define \fBASSIMP_CFLAGS_NOBOOST\fP   0x8"
.br
.RI "\fBAssimp\fP was compiled with ASSIMP_BUILD_BOOST_WORKAROUND defined\&. "
.ti -1c
.RI "#define \fBASSIMP_CFLAGS_SINGLETHREADED\fP   0x10"
.br
.RI "\fBAssimp\fP was compiled with ASSIMP_BUILD_SINGLETHREADED defined\&. "
.ti -1c
.RI "#define \fBASSIMP_CFLAGS_DOUBLE_SUPPORT\fP   0x20"
.br
.RI "\fBAssimp\fP was compiled with ASSIMP_BUILD_SINGLETHREADED defined\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBASSIMP_API\fP const char * \fBaiGetLegalString\fP (\fBvoid\fP)"
.br
.RI "Returns a string with legal copyright and licensing information about \fBAssimp\fP\&. The string may include multiple lines\&. "
.ti -1c
.RI "\fBASSIMP_API\fP unsigned int \fBaiGetVersionPatch\fP (\fBvoid\fP)"
.br
.RI "Returns the current patch version number of \fBAssimp\fP\&. "
.ti -1c
.RI "\fBASSIMP_API\fP unsigned int \fBaiGetVersionMinor\fP (\fBvoid\fP)"
.br
.RI "Returns the current minor version number of \fBAssimp\fP\&. "
.ti -1c
.RI "\fBASSIMP_API\fP unsigned int \fBaiGetVersionMajor\fP (\fBvoid\fP)"
.br
.RI "Returns the current major version number of \fBAssimp\fP\&. "
.ti -1c
.RI "\fBASSIMP_API\fP unsigned int \fBaiGetVersionRevision\fP (\fBvoid\fP)"
.br
.RI "Returns the repository revision of the \fBAssimp\fP runtime\&. "
.ti -1c
.RI "\fBASSIMP_API\fP const char * \fBaiGetBranchName\fP ()"
.br
.RI "Returns the branch-name of the \fBAssimp\fP runtime\&. "
.ti -1c
.RI "\fBASSIMP_API\fP unsigned int \fBaiGetCompileFlags\fP (\fBvoid\fP)"
.br
.RI "Returns assimp's compile flags\&. "
.in -1c
.SH "Detailed Description"
.PP 
Functions to query the version of the \fBAssimp\fP runtime, check compile flags, \&.\&.\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define AI_VERSION_H_INC"

.SS "#define ASSIMP_CFLAGS_DEBUG   0x4"

.PP
\fBAssimp\fP was compiled as a debug build\&. 
.SS "#define ASSIMP_CFLAGS_DOUBLE_SUPPORT   0x20"

.PP
\fBAssimp\fP was compiled with ASSIMP_BUILD_SINGLETHREADED defined\&. 
.SS "#define ASSIMP_CFLAGS_NOBOOST   0x8"

.PP
\fBAssimp\fP was compiled with ASSIMP_BUILD_BOOST_WORKAROUND defined\&. 
.SS "#define ASSIMP_CFLAGS_SHARED   0x1"

.PP
\fBAssimp\fP was compiled as a shared object (Windows: DLL) 
.SS "#define ASSIMP_CFLAGS_SINGLETHREADED   0x10"

.PP
\fBAssimp\fP was compiled with ASSIMP_BUILD_SINGLETHREADED defined\&. 
.SS "#define ASSIMP_CFLAGS_STLPORT   0x2"

.PP
\fBAssimp\fP was compiled against STLport\&. 
.SH "Function Documentation"
.PP 
.SS "\fBASSIMP_API\fP const char * aiGetBranchName ()"

.PP
Returns the branch-name of the \fBAssimp\fP runtime\&. 
.PP
\fBReturns\fP
.RS 4
The current branch name\&. 
.RE
.PP

.SS "\fBASSIMP_API\fP unsigned int aiGetCompileFlags (\fBvoid\fP )"

.PP
Returns assimp's compile flags\&. 
.PP
\fBReturns\fP
.RS 4
Any bitwise combination of the ASSIMP_CFLAGS_xxx constants\&. 
.RE
.PP

.SS "\fBASSIMP_API\fP const char * aiGetLegalString (\fBvoid\fP )"

.PP
Returns a string with legal copyright and licensing information about \fBAssimp\fP\&. The string may include multiple lines\&. 
.PP
\fBReturns\fP
.RS 4
Pointer to static string\&. 
.RE
.PP

.SS "\fBASSIMP_API\fP unsigned int aiGetVersionMajor (\fBvoid\fP )"

.PP
Returns the current major version number of \fBAssimp\fP\&. 
.PP
\fBReturns\fP
.RS 4
Major version of the \fBAssimp\fP runtime the application was linked/built against 
.RE
.PP

.SS "\fBASSIMP_API\fP unsigned int aiGetVersionMinor (\fBvoid\fP )"

.PP
Returns the current minor version number of \fBAssimp\fP\&. 
.PP
\fBReturns\fP
.RS 4
Minor version of the \fBAssimp\fP runtime the application was linked/built against 
.RE
.PP

.SS "\fBASSIMP_API\fP unsigned int aiGetVersionPatch (\fBvoid\fP )"

.PP
Returns the current patch version number of \fBAssimp\fP\&. 
.PP
\fBReturns\fP
.RS 4
Patch version of the \fBAssimp\fP runtime the application was linked/built against 
.RE
.PP

.SS "\fBASSIMP_API\fP unsigned int aiGetVersionRevision (\fBvoid\fP )"

.PP
Returns the repository revision of the \fBAssimp\fP runtime\&. 
.PP
\fBReturns\fP
.RS 4
SVN Repository revision number of the \fBAssimp\fP runtime the application was linked/built against\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
