.TH "packages/directxtk12_uwp.2024.6.5.1/include/VertexTypes.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/directxtk12_uwp.2024.6.5.1/include/VertexTypes.h
.SH SYNOPSIS
.br
.PP
\fR#include <d3d12\&.h>\fP
.br
\fR#include <DirectXMath\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDirectX::DX12::VertexPosition\fP"
.br
.ti -1c
.RI "struct \fBDirectX::DX12::VertexPositionColor\fP"
.br
.ti -1c
.RI "struct \fBDirectX::DX12::VertexPositionTexture\fP"
.br
.ti -1c
.RI "struct \fBDirectX::DX12::VertexPositionDualTexture\fP"
.br
.ti -1c
.RI "struct \fBDirectX::DX12::VertexPositionNormal\fP"
.br
.ti -1c
.RI "struct \fBDirectX::DX12::VertexPositionColorTexture\fP"
.br
.ti -1c
.RI "struct \fBDirectX::DX12::VertexPositionNormalColor\fP"
.br
.ti -1c
.RI "struct \fBDirectX::DX12::VertexPositionNormalTexture\fP"
.br
.ti -1c
.RI "struct \fBDirectX::DX12::VertexPositionNormalColorTexture\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDirectX\fP"
.br
.ti -1c
.RI "namespace \fBDirectX::DX12\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
