.TH "adhed/assimp/Vertex.h" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/assimp/Vertex.h
.SH SYNOPSIS
.br
.PP
\fR#include <assimp/vector3\&.h>\fP
.br
\fR#include <assimp/mesh\&.h>\fP
.br
\fR#include <assimp/ai_assert\&.h>\fP
.br
\fR#include <functional>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAssimp::Intern::plus< T0, T1, TRES >\fP"
.br
.ti -1c
.RI "struct \fBAssimp::Intern::minus< T0, T1, TRES >\fP"
.br
.ti -1c
.RI "struct \fBAssimp::Intern::multiplies< T0, T1, TRES >\fP"
.br
.ti -1c
.RI "struct \fBAssimp::Intern::divides< T0, T1, TRES >\fP"
.br
.ti -1c
.RI "class \fBAssimp::Vertex\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAssimp\fP"
.br
.RI "Some C++ utilities for inter- and extrapolation\&. "
.ti -1c
.RI "namespace \fBAssimp::Intern\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAI_VERTEX_H_INC\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP \fBVertex\fP \fBAssimp::operator+\fP (const \fBVertex\fP &\fBv0\fP, const \fBVertex\fP &\fBv1\fP)"
.br
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP \fBVertex\fP \fBAssimp::operator\-\fP (const \fBVertex\fP &\fBv0\fP, const \fBVertex\fP &\fBv1\fP)"
.br
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP \fBVertex\fP \fBAssimp::operator*\fP (const \fBVertex\fP &\fBv0\fP, \fBai_real\fP \fBf\fP)"
.br
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP \fBVertex\fP \fBAssimp::operator/\fP (const \fBVertex\fP &\fBv0\fP, \fBai_real\fP \fBf\fP)"
.br
.ti -1c
.RI "\fBAI_FORCE_INLINE\fP \fBVertex\fP \fBAssimp::operator*\fP (\fBai_real\fP \fBf\fP, const \fBVertex\fP &\fBv0\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AI_VERTEX_H_INC"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
