.TH "adhed/glm/gtx/wrap.hpp" 3 "Version 0.0.0.2" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adhed/glm/gtx/wrap.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./glm\&.hpp'\fP
.br
\fR#include '\&.\&./ext/scalar_common\&.hpp'\fP
.br
\fR#include '\&.\&./ext/vector_common\&.hpp'\fP
.br
\fR#include '\&.\&./gtc/vec1\&.hpp'\fP
.br
\fR#include 'wrap\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_wrap\fP
.PP
\fBSee also\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
