export module UPRISE_ENGINE_META:X86_64_OPCODES;

export {
#define UE_META_BUILD_
#include "AVX/X86_64_AVX_OPCODES_INTERNAL.h"
#include "AVX2/X86_64_AVX2_OPCODES_INTERNAL.h"
#include "GENERAL_PURPOSE/X86_64_GP_OPCODES_INTERNAL.h"
#include "SSE/X86_64_SSE_OPCODES_INTERNAL.h"
#include "X87/X87_OPCODES_INTERNAL.h"
}