#pragma once
#ifndef UE_OPENGL_RENDER_INTELLISENSE_FIX
#define UE_OPENGL_RENDER_INTELLISENSE_FIX
#define DONT_INCLUDE_GLAD

#include"OPENGL/GLAD/GLAD_CONSTANTS/CONSTANTS_PART_1/GLAD_CONSTANTS_PART_1_INTERNAL.h";
#include"OPENGL/GLAD/GLAD_CONSTANTS/CONSTANTS_PART_2/CONSTANTS_PART_2_INTERNAL.h";
#include"OPENGL/GLAD/GLAD_CONSTANTS/CONSTANTS_PART_3/GLAD_CONSTANTS_PART3_INTERNAL.h";
#include"OPENGL/GLAD/GLAD_CONSTANTS/CONSTANTS_PART_4/GLAD_CONSTANTS_PART_4_INTERNAL.h";
#include"OPENGL/GLAD/GLAD_CONSTANTS/CONSTANTS_PART_5/GLAD_CONSTANTS_PART_5_INTERNAL.h";
#include"OPENGL/GLAD/GLAD_CONSTANTS/CONSTANTS_PART_6/GLAD_CONSTANTS_PART_6_INTERNAL.h";
#include"OPENGL/GLAD/GLAD_CONSTANTS/CONSTANTS_PART_7/GLAD_CONSTANTS_PART_7.h";
#include"OPENGL/GLAD/GLAD_GLOBALS/GLAD_GLOBALS_INTERNAL.h";
#include"OPENGL/GLAD/OPENGL_VERSIONS/VERSION_ALL/OPENGL_VERSION_ALL_INTERNAL.h";
#include"OPENGL/GLAD/STUPIDMACROS/GLAD_MACROS.h";
#include"OPENGL/OPENGL_BACKEND/OPENGL_BACKEND_INTERNAL.h";
#include"OPENGL/OPENGL_CONTEXT/OPENGL_CONTEXT_INTERNAL.h";
#include"OPENGL/OPENGL_SHADER/OPENGL_SHADER_INTERNAL.h";
#include"OPENGL/OPENGL_WINDOW/OPENGL_WINDOW_INTERNAL.h";
#endif // !UE_OPENGL_RENDER_INTELLISENSE_FIX
