#pragma once
#ifndef UE_RENDER_INTELLISENSE_FIX
#define UE_RENDER_INTELLISENSE_FIX
#include "DATATYPES/MESH/MESH_INTERNAL.h"
#include "DATATYPES/MODEL/MODEL_INTERNAL.h"
#include "DATATYPES/TEXTURE/TEXTURE_INTERNAL.h"
#include "DATATYPES/VERTEX/VERTEX_INTERNAL.h"
#include "RENDER/CONTEXT/CONTEXT_INTERNAL.h"
#include "RENDER/MAINRENDER/MAINRENDER_INTERNAL.h"
#include "RENDER/MATERIAL/MATERIAL_INTERNAL.h"
#include "RENDER/RENDER_CAMERA/RENDER_CAMERA_INTERNAL.h"
#include "RENDER/SHADER/SHADER_INTERNAL.h"
#include "RENDER/WINDOW/WINDOW_INTERNAL.h"
#endif // !UE_RENDER_INTELLISENSE_FIX
