export module UPRISE_ENGINE_COMMON_RENDER_COMPONETS:WINDOW_BASE;
import UPRISE_ENGINE_CORE;
import :CALLBACK_TYPEDEFS;
import <string>;
export {
#define UE_COMMON_COMPS_BUILD_
#include "WINDOW_BASE_INTERNAL.h"
}