#pragma once
#ifndef UE_GLAD_CONSTANTS_PART_7_INTERNAL_
#define UE_GLAD_CONSTANTS_PART_7_INTERNAL_
#ifndef __INTELLISENSE__
#ifndef UE_OPENGL_BUILD_
#error "this file should not be directly included in user code. use import UPRISE_ENGINE_CORE instead"
#endif
#endif
#include "OPENGL/GLAD/STUPIDMACROS/GLAD_MACROS.h"
#ifdef __INTELLISENSE__
#ifndef DONT_INCLUDE_GLAD
#include <glad/glad.h>
#endif
#endif // __INTELLISENSE__
namespace UPRISE_ENGINE {
    namespace RENDER {
        namespace OPENGL {
            namespace GLAD {
                namespace CONSTANTS {

                    constexpr int _GL_SIGNED_NORMALIZED = 0x8F9C;
                    constexpr int _GL_PRIMITIVE_RESTART = 0x8F9D;
                    constexpr int _GL_PRIMITIVE_RESTART_INDEX = 0x8F9E;
                    constexpr int _GL_COPY_READ_BUFFER = 0x8F36;
                    constexpr int _GL_COPY_WRITE_BUFFER = 0x8F37;
                    constexpr int _GL_UNIFORM_BUFFER = 0x8A11;
                    constexpr int _GL_UNIFORM_BUFFER_BINDING = 0x8A28;
                    constexpr int _GL_UNIFORM_BUFFER_START = 0x8A29;
                    constexpr int _GL_UNIFORM_BUFFER_SIZE = 0x8A2A;
                    constexpr int _GL_MAX_VERTEX_UNIFORM_BLOCKS = 0x8A2B;
                    constexpr int _GL_MAX_GEOMETRY_UNIFORM_BLOCKS = 0x8A2C;
                    constexpr int _GL_MAX_FRAGMENT_UNIFORM_BLOCKS = 0x8A2D;
                    constexpr int _GL_MAX_COMBINED_UNIFORM_BLOCKS = 0x8A2E;
                    constexpr int _GL_MAX_UNIFORM_BUFFER_BINDINGS = 0x8A2F;
                    constexpr int _GL_MAX_UNIFORM_BLOCK_SIZE = 0x8A30;
                    constexpr int _GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS = 0x8A31;
                    constexpr int _GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS = 0x8A32;
                    constexpr int _GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS = 0x8A33;
                    constexpr int _GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = 0x8A34;
                    constexpr int _GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH = 0x8A35;
                    constexpr int _GL_ACTIVE_UNIFORM_BLOCKS = 0x8A36;
                    constexpr int _GL_UNIFORM_TYPE = 0x8A37;
                    constexpr int _GL_UNIFORM_SIZE = 0x8A38;
                    constexpr int _GL_UNIFORM_NAME_LENGTH = 0x8A39;
                    constexpr int _GL_UNIFORM_BLOCK_INDEX = 0x8A3A;
                    constexpr int _GL_UNIFORM_OFFSET = 0x8A3B;
                    constexpr int _GL_UNIFORM_ARRAY_STRIDE = 0x8A3C;
                    constexpr int _GL_UNIFORM_MATRIX_STRIDE = 0x8A3D;
                    constexpr int _GL_UNIFORM_IS_ROW_MAJOR = 0x8A3E;
                    constexpr int _GL_UNIFORM_BLOCK_BINDING = 0x8A3F;
                    constexpr int _GL_UNIFORM_BLOCK_DATA_SIZE = 0x8A40;
                    constexpr int _GL_UNIFORM_BLOCK_NAME_LENGTH = 0x8A41;
                    constexpr int _GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS = 0x8A42;
                    constexpr int _GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES = 0x8A43;
                    constexpr int _GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER = 0x8A44;
                    constexpr int _GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER = 0x8A45;
                    constexpr int _GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER = 0x8A46;
                    constexpr int _GL_INVALID_INDEX = 0xFFFFFFFF; //-V112 false positive as this is part of glad and needed
                    constexpr int _GL_CONTEXT_CORE_PROFILE_BIT = 0x00000001;
                    constexpr int _GL_CONTEXT_COMPATIBILITY_PROFILE_BIT = 0x00000002;
                    constexpr int _GL_LINES_ADJACENCY = 0x000A;
                    constexpr int _GL_LINE_STRIP_ADJACENCY = 0x000B;
                    constexpr int _GL_TRIANGLES_ADJACENCY = 0x000C;
                    constexpr int _GL_TRIANGLE_STRIP_ADJACENCY = 0x000D;
                    constexpr int _GL_PROGRAM_POINT_SIZE = 0x8642;
                    constexpr int _GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS = 0x8C29;
                    constexpr int _GL_FRAMEBUFFER_ATTACHMENT_LAYERED = 0x8DA7;
                    constexpr int _GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS = 0x8DA8;
                    constexpr int _GL_GEOMETRY_SHADER = 0x8DD9;
                    constexpr int _GL_GEOMETRY_VERTICES_OUT = 0x8916;
                    constexpr int _GL_GEOMETRY_INPUT_TYPE = 0x8917;
                    constexpr int _GL_GEOMETRY_OUTPUT_TYPE = 0x8918;
                    constexpr int _GL_MAX_GEOMETRY_UNIFORM_COMPONENTS = 0x8DDF;
                    constexpr int _GL_MAX_GEOMETRY_OUTPUT_VERTICES = 0x8DE0;
                    constexpr int _GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS = 0x8DE1;
                    constexpr int _GL_MAX_VERTEX_OUTPUT_COMPONENTS = 0x9122;
                    constexpr int _GL_MAX_GEOMETRY_INPUT_COMPONENTS = 0x9123;
                    constexpr int _GL_MAX_GEOMETRY_OUTPUT_COMPONENTS = 0x9124;
                    constexpr int _GL_MAX_FRAGMENT_INPUT_COMPONENTS = 0x9125;
                    constexpr int _GL_CONTEXT_PROFILE_MASK = 0x9126;
                    constexpr int _GL_DEPTH_CLAMP = 0x864F;
                    constexpr int _GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION = 0x8E4C;
                    constexpr int _GL_FIRST_VERTEX_CONVENTION = 0x8E4D;
                    constexpr int _GL_LAST_VERTEX_CONVENTION = 0x8E4E;
                    constexpr int _GL_PROVOKING_VERTEX = 0x8E4F;
                    constexpr int _GL_TEXTURE_CUBE_MAP_SEAMLESS = 0x884F;
                    constexpr int _GL_MAX_SERVER_WAIT_TIMEOUT = 0x9111;
                    constexpr int _GL_OBJECT_TYPE = 0x9112;
                    constexpr int _GL_SYNC_CONDITION = 0x9113;
                    constexpr int _GL_SYNC_STATUS = 0x9114;
                    constexpr int _GL_SYNC_FLAGS = 0x9115;
                    constexpr int _GL_SYNC_FENCE = 0x9116;
                    constexpr int _GL_SYNC_GPU_COMMANDS_COMPLETE = 0x9117;
                    constexpr int _GL_UNSIGNALED = 0x9118;
                    constexpr int _GL_SIGNALED = 0x9119;
                    constexpr int _GL_ALREADY_SIGNALED = 0x911A;
                    constexpr int _GL_TIMEOUT_EXPIRED = 0x911B;
                    constexpr int _GL_CONDITION_SATISFIED = 0x911C;
                    constexpr int _GL_WAIT_FAILED = 0x911D;
                    constexpr unsigned long long _GL_TIMEOUT_IGNORED = 0xFFFFFFFFFFFFFFFF;
                    constexpr int _GL_SYNC_FLUSH_COMMANDS_BIT = 0x00000001;
                    constexpr int _GL_SAMPLE_POSITION = 0x8E50;
                    constexpr int _GL_SAMPLE_MASK = 0x8E51;
                    constexpr int _GL_SAMPLE_MASK_VALUE = 0x8E52;
                    constexpr int _GL_MAX_SAMPLE_MASK_WORDS = 0x8E59;
                    constexpr int _GL_TEXTURE_2D_MULTISAMPLE = 0x9100;
                    constexpr int _GL_PROXY_TEXTURE_2D_MULTISAMPLE = 0x9101;
                    constexpr int _GL_TEXTURE_2D_MULTISAMPLE_ARRAY = 0x9102;
                    constexpr int _GL_PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY = 0x9103;
                    constexpr int _GL_TEXTURE_BINDING_2D_MULTISAMPLE = 0x9104;
                    constexpr int _GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY = 0x9105;
                    constexpr int _GL_TEXTURE_SAMPLES = 0x9106;
                    constexpr int _GL_TEXTURE_FIXED_SAMPLE_LOCATIONS = 0x9107;
                    constexpr int _GL_SAMPLER_2D_MULTISAMPLE = 0x9108;
                    constexpr int _GL_INT_SAMPLER_2D_MULTISAMPLE = 0x9109;
                    constexpr int _GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE = 0x910A;
                    constexpr int _GL_SAMPLER_2D_MULTISAMPLE_ARRAY = 0x910B;
                    constexpr int _GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY = 0x910C;
                    constexpr int _GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY = 0x910D;
                    constexpr int _GL_MAX_COLOR_TEXTURE_SAMPLES = 0x910E;
                    constexpr int _GL_MAX_DEPTH_TEXTURE_SAMPLES = 0x910F;
                    constexpr int _GL_MAX_INTEGER_SAMPLES = 0x9110;
                    constexpr int _GL_VERTEX_ATTRIB_ARRAY_DIVISOR = 0x88FE;
                    constexpr int _GL_SRC1_COLOR = 0x88F9;
                    constexpr int _GL_ONE_MINUS_SRC1_COLOR = 0x88FA;
                    constexpr int _GL_ONE_MINUS_SRC1_ALPHA = 0x88FB;
                    constexpr int _GL_MAX_DUAL_SOURCE_DRAW_BUFFERS = 0x88FC;
                    constexpr int _GL_ANY_SAMPLES_PASSED = 0x8C2F;
                    constexpr int _GL_SAMPLER_BINDING = 0x8919;
                    constexpr int _GL_RGB10_A2UI = 0x906F;
                    constexpr int _GL_TEXTURE_SWIZZLE_R = 0x8E42;
                    constexpr int _GL_TEXTURE_SWIZZLE_G = 0x8E43;
                    constexpr int _GL_TEXTURE_SWIZZLE_B = 0x8E44;
                    constexpr int _GL_TEXTURE_SWIZZLE_A = 0x8E45;
                    constexpr int _GL_TEXTURE_SWIZZLE_RGBA = 0x8E46;
                    constexpr int _GL_TIME_ELAPSED = 0x88BF;
                    constexpr int _GL_TIMESTAMP = 0x8E28;
                    constexpr int _GL_INT_2_10_10_10_REV = 0x8D9F;
                    constexpr int _GL_SAMPLE_SHADING = 0x8C36;
                    constexpr int _GL_MIN_SAMPLE_SHADING_VALUE = 0x8C37;
                    constexpr int _GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET = 0x8E5E;
                    constexpr int _GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET = 0x8E5F;
                    constexpr int _GL_TEXTURE_CUBE_MAP_ARRAY = 0x9009;
                    constexpr int _GL_TEXTURE_BINDING_CUBE_MAP_ARRAY = 0x900A;
                    constexpr int _GL_PROXY_TEXTURE_CUBE_MAP_ARRAY = 0x900B;
                    constexpr int _GL_SAMPLER_CUBE_MAP_ARRAY = 0x900C;
                    constexpr int _GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW = 0x900D;
                    constexpr int _GL_INT_SAMPLER_CUBE_MAP_ARRAY = 0x900E;
                    constexpr int _GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY = 0x900F;
                    constexpr int _GL_DRAW_INDIRECT_BUFFER = 0x8F3F;
                    constexpr int _GL_DRAW_INDIRECT_BUFFER_BINDING = 0x8F43;
                    constexpr int _GL_GEOMETRY_SHADER_INVOCATIONS = 0x887F;
                    constexpr int _GL_MAX_GEOMETRY_SHADER_INVOCATIONS = 0x8E5A;
                    constexpr int _GL_MIN_FRAGMENT_INTERPOLATION_OFFSET = 0x8E5B;
                    constexpr int _GL_MAX_FRAGMENT_INTERPOLATION_OFFSET = 0x8E5C;
                    constexpr int _GL_FRAGMENT_INTERPOLATION_OFFSET_BITS = 0x8E5D;
                    constexpr int _GL_MAX_VERTEX_STREAMS = 0x8E71;
                    constexpr int _GL_DOUBLE_VEC2 = 0x8FFC;
                    constexpr int _GL_DOUBLE_VEC3 = 0x8FFD;
                    constexpr int _GL_DOUBLE_VEC4 = 0x8FFE;
                    constexpr int _GL_DOUBLE_MAT2 = 0x8F46;
                    constexpr int _GL_DOUBLE_MAT3 = 0x8F47;
                    constexpr int _GL_DOUBLE_MAT4 = 0x8F48;
                    constexpr int _GL_DOUBLE_MAT2x3 = 0x8F49;
                    constexpr int _GL_DOUBLE_MAT2x4 = 0x8F4A;
                    constexpr int _GL_DOUBLE_MAT3x2 = 0x8F4B;
                    constexpr int _GL_DOUBLE_MAT3x4 = 0x8F4C;
                    constexpr int _GL_DOUBLE_MAT4x2 = 0x8F4D;
                    constexpr int _GL_DOUBLE_MAT4x3 = 0x8F4E;
                    constexpr int _GL_ACTIVE_SUBROUTINES = 0x8DE5;
                    constexpr int _GL_ACTIVE_SUBROUTINE_UNIFORMS = 0x8DE6;
                    constexpr int _GL_ACTIVE_SUBROUTINE_UNIFORM_LOCATIONS = 0x8E47;
                    constexpr int _GL_ACTIVE_SUBROUTINE_MAX_LENGTH = 0x8E48;
                    constexpr int _GL_ACTIVE_SUBROUTINE_UNIFORM_MAX_LENGTH = 0x8E49;
                    constexpr int _GL_MAX_SUBROUTINES = 0x8DE7;
                    constexpr int _GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS = 0x8DE8;
                    constexpr int _GL_NUM_COMPATIBLE_SUBROUTINES = 0x8E4A;
                    constexpr int _GL_COMPATIBLE_SUBROUTINES = 0x8E4B;
                    constexpr int _GL_PATCHES = 0x000E;
                    constexpr int _GL_PATCH_VERTICES = 0x8E72;
                    constexpr int _GL_PATCH_DEFAULT_INNER_LEVEL = 0x8E73;
                    constexpr int _GL_PATCH_DEFAULT_OUTER_LEVEL = 0x8E74;
                    constexpr int _GL_TESS_CONTROL_OUTPUT_VERTICES = 0x8E75;
                    constexpr int _GL_TESS_GEN_MODE = 0x8E76;
                    constexpr int _GL_TESS_GEN_SPACING = 0x8E77;
                    constexpr int _GL_TESS_GEN_VERTEX_ORDER = 0x8E78;
                    constexpr int _GL_TESS_GEN_POINT_MODE = 0x8E79;
                    constexpr int _GL_ISOLINES = 0x8E7A;
                    constexpr int _GL_QUADS = 0x0007;
                    constexpr int _GL_FRACTIONAL_ODD = 0x8E7B;
                    constexpr int _GL_FRACTIONAL_EVEN = 0x8E7C;
                    constexpr int _GL_MAX_PATCH_VERTICES = 0x8E7D;
                    constexpr int _GL_MAX_TESS_GEN_LEVEL = 0x8E7E;
                    constexpr int _GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS = 0x8E7F;
                    constexpr int _GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS = 0x8E80;
                    constexpr int _GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS = 0x8E81;
                    constexpr int _GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS = 0x8E82;
                    constexpr int _GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS = 0x8E83;
                    constexpr int _GL_MAX_TESS_PATCH_COMPONENTS = 0x8E84;
                    constexpr int _GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS = 0x8E85;
                    constexpr int _GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS = 0x8E86;
                    constexpr int _GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS = 0x8E89;
                    constexpr int _GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS = 0x8E8A;
                    constexpr int _GL_MAX_TESS_CONTROL_INPUT_COMPONENTS = 0x886C;
                    constexpr int _GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS = 0x886D;
                    constexpr int _GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS = 0x8E1E;
                    constexpr int _GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS = 0x8E1F;
                    constexpr int _GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER = 0x84F0;
                    constexpr int _GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x84F1;
                    constexpr int _GL_TESS_EVALUATION_SHADER = 0x8E87;
                    constexpr int _GL_TESS_CONTROL_SHADER = 0x8E88;
                    constexpr int _GL_TRANSFORM_FEEDBACK = 0x8E22;
                    constexpr int _GL_TRANSFORM_FEEDBACK_BUFFER_PAUSED = 0x8E23;
                    constexpr int _GL_TRANSFORM_FEEDBACK_BUFFER_ACTIVE = 0x8E24;
                    constexpr int _GL_TRANSFORM_FEEDBACK_BINDING = 0x8E25;
                    constexpr int _GL_MAX_TRANSFORM_FEEDBACK_BUFFERS = 0x8E70;
#ifndef DONT_INCLUDE_GLAD
                    consteval void CheckConstantsPart7() {
                        static_assert(_GL_SIGNED_NORMALIZED == GL_SIGNED_NORMALIZED, "_GL_SIGNED_NORMALIZED is not equal to GL_SIGNED_NORMALIZED");
                        static_assert(_GL_PRIMITIVE_RESTART == GL_PRIMITIVE_RESTART, "_GL_PRIMITIVE_RESTART is not equal to GL_PRIMITIVE_RESTART");
                        static_assert(_GL_PRIMITIVE_RESTART_INDEX == GL_PRIMITIVE_RESTART_INDEX, "_GL_PRIMITIVE_RESTART_INDEX is not equal to GL_PRIMITIVE_RESTART_INDEX");
                        static_assert(_GL_COPY_READ_BUFFER == GL_COPY_READ_BUFFER, "_GL_COPY_READ_BUFFER is not equal to GL_COPY_READ_BUFFER");
                        static_assert(_GL_COPY_WRITE_BUFFER == GL_COPY_WRITE_BUFFER, "_GL_COPY_WRITE_BUFFER is not equal to GL_COPY_WRITE_BUFFER");
                        static_assert(_GL_UNIFORM_BUFFER == GL_UNIFORM_BUFFER, "_GL_UNIFORM_BUFFER is not equal to GL_UNIFORM_BUFFER");
                        static_assert(_GL_UNIFORM_BUFFER_BINDING == GL_UNIFORM_BUFFER_BINDING, "_GL_UNIFORM_BUFFER_BINDING is not equal to GL_UNIFORM_BUFFER_BINDING");
                        static_assert(_GL_UNIFORM_BUFFER_START == GL_UNIFORM_BUFFER_START, "_GL_UNIFORM_BUFFER_START is not equal to GL_UNIFORM_BUFFER_START");
                        static_assert(_GL_UNIFORM_BUFFER_SIZE == GL_UNIFORM_BUFFER_SIZE, "_GL_UNIFORM_BUFFER_SIZE is not equal to GL_UNIFORM_BUFFER_SIZE");
                        static_assert(_GL_MAX_VERTEX_UNIFORM_BLOCKS == GL_MAX_VERTEX_UNIFORM_BLOCKS, "_GL_MAX_VERTEX_UNIFORM_BLOCKS is not equal to GL_MAX_VERTEX_UNIFORM_BLOCKS");
                        static_assert(_GL_MAX_GEOMETRY_UNIFORM_BLOCKS == GL_MAX_GEOMETRY_UNIFORM_BLOCKS, "_GL_MAX_GEOMETRY_UNIFORM_BLOCKS is not equal to GL_MAX_GEOMETRY_UNIFORM_BLOCKS");
                        static_assert(_GL_MAX_FRAGMENT_UNIFORM_BLOCKS == GL_MAX_FRAGMENT_UNIFORM_BLOCKS, "_GL_MAX_FRAGMENT_UNIFORM_BLOCKS is not equal to GL_MAX_FRAGMENT_UNIFORM_BLOCKS");
                        static_assert(_GL_MAX_COMBINED_UNIFORM_BLOCKS == GL_MAX_COMBINED_UNIFORM_BLOCKS, "_GL_MAX_COMBINED_UNIFORM_BLOCKS is not equal to GL_MAX_COMBINED_UNIFORM_BLOCKS");
                        static_assert(_GL_MAX_UNIFORM_BUFFER_BINDINGS == GL_MAX_UNIFORM_BUFFER_BINDINGS, "_GL_MAX_UNIFORM_BUFFER_BINDINGS is not equal to GL_MAX_UNIFORM_BUFFER_BINDINGS");
                        static_assert(_GL_MAX_UNIFORM_BLOCK_SIZE == GL_MAX_UNIFORM_BLOCK_SIZE, "_GL_MAX_UNIFORM_BLOCK_SIZE is not equal to GL_MAX_UNIFORM_BLOCK_SIZE");
                        static_assert(_GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS == GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS, "_GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS is not equal to GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS");
                        static_assert(_GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS == GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS, "_GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS is not equal to GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS");
                        static_assert(_GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS == GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS, "_GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS is not equal to GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS");
                        static_assert(_GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT == GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT, "_GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT is not equal to GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT");
                        static_assert(_GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH == GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH, "_GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH is not equal to GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH");
                        static_assert(_GL_ACTIVE_UNIFORM_BLOCKS == GL_ACTIVE_UNIFORM_BLOCKS, "_GL_ACTIVE_UNIFORM_BLOCKS is not equal to GL_ACTIVE_UNIFORM_BLOCKS");
                        static_assert(_GL_UNIFORM_TYPE == GL_UNIFORM_TYPE, "_GL_UNIFORM_TYPE is not equal to GL_UNIFORM_TYPE");
                        static_assert(_GL_UNIFORM_SIZE == GL_UNIFORM_SIZE, "_GL_UNIFORM_SIZE is not equal to GL_UNIFORM_SIZE");
                        static_assert(_GL_UNIFORM_NAME_LENGTH == GL_UNIFORM_NAME_LENGTH, "_GL_UNIFORM_NAME_LENGTH is not equal to GL_UNIFORM_NAME_LENGTH");
                        static_assert(_GL_UNIFORM_BLOCK_INDEX == GL_UNIFORM_BLOCK_INDEX, "_GL_UNIFORM_BLOCK_INDEX is not equal to GL_UNIFORM_BLOCK_INDEX");
                        static_assert(_GL_UNIFORM_OFFSET == GL_UNIFORM_OFFSET, "_GL_UNIFORM_OFFSET is not equal to GL_UNIFORM_OFFSET");
                        static_assert(_GL_UNIFORM_ARRAY_STRIDE == GL_UNIFORM_ARRAY_STRIDE, "_GL_UNIFORM_ARRAY_STRIDE is not equal to GL_UNIFORM_ARRAY_STRIDE");
                        static_assert(_GL_UNIFORM_MATRIX_STRIDE == GL_UNIFORM_MATRIX_STRIDE, "_GL_UNIFORM_MATRIX_STRIDE is not equal to GL_UNIFORM_MATRIX_STRIDE");
                        static_assert(_GL_UNIFORM_IS_ROW_MAJOR == GL_UNIFORM_IS_ROW_MAJOR, "_GL_UNIFORM_IS_ROW_MAJOR is not equal to GL_UNIFORM_IS_ROW_MAJOR");
                        static_assert(_GL_UNIFORM_BLOCK_BINDING == GL_UNIFORM_BLOCK_BINDING, "_GL_UNIFORM_BLOCK_BINDING is not equal to GL_UNIFORM_BLOCK_BINDING");
                        static_assert(_GL_UNIFORM_BLOCK_DATA_SIZE == GL_UNIFORM_BLOCK_DATA_SIZE, "_GL_UNIFORM_BLOCK_DATA_SIZE is not equal to GL_UNIFORM_BLOCK_DATA_SIZE");
                        static_assert(_GL_UNIFORM_BLOCK_NAME_LENGTH == GL_UNIFORM_BLOCK_NAME_LENGTH, "_GL_UNIFORM_BLOCK_NAME_LENGTH is not equal to GL_UNIFORM_BLOCK_NAME_LENGTH");
                        static_assert(_GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS == GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS, "_GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS is not equal to GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS");
                        static_assert(_GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES == GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES, "_GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES is not equal to GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES");
                        static_assert(_GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER == GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER, "_GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER is not equal to GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER");
                        static_assert(_GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER == GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER, "_GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER is not equal to GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER");
                        static_assert(_GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER == GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER, "_GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER is not equal to GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER");
                        static_assert(_GL_INVALID_INDEX == GL_INVALID_INDEX, "_GL_INVALID_INDEX is not equal to GL_INVALID_INDEX");
                        static_assert(_GL_CONTEXT_CORE_PROFILE_BIT == GL_CONTEXT_CORE_PROFILE_BIT, "_GL_CONTEXT_CORE_PROFILE_BIT is not equal to GL_CONTEXT_CORE_PROFILE_BIT");
                        static_assert(_GL_CONTEXT_COMPATIBILITY_PROFILE_BIT == GL_CONTEXT_COMPATIBILITY_PROFILE_BIT, "_GL_CONTEXT_COMPATIBILITY_PROFILE_BIT is not equal to GL_CONTEXT_COMPATIBILITY_PROFILE_BIT");
                        static_assert(_GL_LINES_ADJACENCY == GL_LINES_ADJACENCY, "_GL_LINES_ADJACENCY is not equal to GL_LINES_ADJACENCY");
                        static_assert(_GL_LINE_STRIP_ADJACENCY == GL_LINE_STRIP_ADJACENCY, "_GL_LINE_STRIP_ADJACENCY is not equal to GL_LINE_STRIP_ADJACENCY");
                        static_assert(_GL_TRIANGLES_ADJACENCY == GL_TRIANGLES_ADJACENCY, "_GL_TRIANGLES_ADJACENCY is not equal to GL_TRIANGLES_ADJACENCY");
                        static_assert(_GL_TRIANGLE_STRIP_ADJACENCY == GL_TRIANGLE_STRIP_ADJACENCY, "_GL_TRIANGLE_STRIP_ADJACENCY is not equal to GL_TRIANGLE_STRIP_ADJACENCY");
                        static_assert(_GL_PROGRAM_POINT_SIZE == GL_PROGRAM_POINT_SIZE, "_GL_PROGRAM_POINT_SIZE is not equal to GL_PROGRAM_POINT_SIZE");
                        static_assert(_GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS == GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS, "_GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS is not equal to GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS");
                        static_assert(_GL_FRAMEBUFFER_ATTACHMENT_LAYERED == GL_FRAMEBUFFER_ATTACHMENT_LAYERED, "_GL_FRAMEBUFFER_ATTACHMENT_LAYERED is not equal to GL_FRAMEBUFFER_ATTACHMENT_LAYERED");
                        static_assert(_GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS == GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS, "_GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS is not equal to GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS");
                        static_assert(_GL_GEOMETRY_SHADER == GL_GEOMETRY_SHADER, "_GL_GEOMETRY_SHADER is not equal to GL_GEOMETRY_SHADER");
                        static_assert(_GL_GEOMETRY_VERTICES_OUT == GL_GEOMETRY_VERTICES_OUT, "_GL_GEOMETRY_VERTICES_OUT is not equal to GL_GEOMETRY_VERTICES_OUT");
                        static_assert(_GL_GEOMETRY_INPUT_TYPE == GL_GEOMETRY_INPUT_TYPE, "_GL_GEOMETRY_INPUT_TYPE is not equal to GL_GEOMETRY_INPUT_TYPE");
                        static_assert(_GL_GEOMETRY_OUTPUT_TYPE == GL_GEOMETRY_OUTPUT_TYPE, "_GL_GEOMETRY_OUTPUT_TYPE is not equal to GL_GEOMETRY_OUTPUT_TYPE");
                        static_assert(_GL_MAX_GEOMETRY_UNIFORM_COMPONENTS == GL_MAX_GEOMETRY_UNIFORM_COMPONENTS, "_GL_MAX_GEOMETRY_UNIFORM_COMPONENTS is not equal to GL_MAX_GEOMETRY_UNIFORM_COMPONENTS");
                        static_assert(_GL_MAX_GEOMETRY_OUTPUT_VERTICES == GL_MAX_GEOMETRY_OUTPUT_VERTICES, "_GL_MAX_GEOMETRY_OUTPUT_VERTICES is not equal to GL_MAX_GEOMETRY_OUTPUT_VERTICES");
                        static_assert(_GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS == GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS, "_GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS is not equal to GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS");
                        static_assert(_GL_MAX_VERTEX_OUTPUT_COMPONENTS == GL_MAX_VERTEX_OUTPUT_COMPONENTS, "_GL_MAX_VERTEX_OUTPUT_COMPONENTS is not equal to GL_MAX_VERTEX_OUTPUT_COMPONENTS");
                        static_assert(_GL_MAX_GEOMETRY_INPUT_COMPONENTS == GL_MAX_GEOMETRY_INPUT_COMPONENTS, "_GL_MAX_GEOMETRY_INPUT_COMPONENTS is not equal to GL_MAX_GEOMETRY_INPUT_COMPONENTS");
                        static_assert(_GL_MAX_GEOMETRY_OUTPUT_COMPONENTS == GL_MAX_GEOMETRY_OUTPUT_COMPONENTS, "_GL_MAX_GEOMETRY_OUTPUT_COMPONENTS is not equal to GL_MAX_GEOMETRY_OUTPUT_COMPONENTS");
                        static_assert(_GL_MAX_FRAGMENT_INPUT_COMPONENTS == GL_MAX_FRAGMENT_INPUT_COMPONENTS, "_GL_MAX_FRAGMENT_INPUT_COMPONENTS is not equal to GL_MAX_FRAGMENT_INPUT_COMPONENTS");
                        static_assert(_GL_CONTEXT_PROFILE_MASK == GL_CONTEXT_PROFILE_MASK, "_GL_CONTEXT_PROFILE_MASK is not equal to GL_CONTEXT_PROFILE_MASK");
                        static_assert(_GL_DEPTH_CLAMP == GL_DEPTH_CLAMP, "_GL_DEPTH_CLAMP is not equal to GL_DEPTH_CLAMP");
                        static_assert(_GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION == GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION, "_GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION is not equal to GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION");
                        static_assert(_GL_FIRST_VERTEX_CONVENTION == GL_FIRST_VERTEX_CONVENTION, "_GL_FIRST_VERTEX_CONVENTION is not equal to GL_FIRST_VERTEX_CONVENTION");
                        static_assert(_GL_LAST_VERTEX_CONVENTION == GL_LAST_VERTEX_CONVENTION, "_GL_LAST_VERTEX_CONVENTION is not equal to GL_LAST_VERTEX_CONVENTION");
                        static_assert(_GL_PROVOKING_VERTEX == GL_PROVOKING_VERTEX, "_GL_PROVOKING_VERTEX is not equal to GL_PROVOKING_VERTEX");
                        static_assert(_GL_TEXTURE_CUBE_MAP_SEAMLESS == GL_TEXTURE_CUBE_MAP_SEAMLESS, "_GL_TEXTURE_CUBE_MAP_SEAMLESS is not equal to GL_TEXTURE_CUBE_MAP_SEAMLESS");
                        static_assert(_GL_MAX_SERVER_WAIT_TIMEOUT == GL_MAX_SERVER_WAIT_TIMEOUT, "_GL_MAX_SERVER_WAIT_TIMEOUT is not equal to GL_MAX_SERVER_WAIT_TIMEOUT");
                        static_assert(_GL_OBJECT_TYPE == GL_OBJECT_TYPE, "_GL_OBJECT_TYPE is not equal to GL_OBJECT_TYPE");
                        static_assert(_GL_SYNC_CONDITION == GL_SYNC_CONDITION, "_GL_SYNC_CONDITION is not equal to GL_SYNC_CONDITION");
                        static_assert(_GL_SYNC_STATUS == GL_SYNC_STATUS, "_GL_SYNC_STATUS is not equal to GL_SYNC_STATUS");
                        static_assert(_GL_SYNC_FLAGS == GL_SYNC_FLAGS, "_GL_SYNC_FLAGS is not equal to GL_SYNC_FLAGS");
                        static_assert(_GL_SYNC_FENCE == GL_SYNC_FENCE, "_GL_SYNC_FENCE is not equal to GL_SYNC_FENCE");
                        static_assert(_GL_SYNC_GPU_COMMANDS_COMPLETE == GL_SYNC_GPU_COMMANDS_COMPLETE, "_GL_SYNC_GPU_COMMANDS_COMPLETE is not equal to GL_SYNC_GPU_COMMANDS_COMPLETE");
                        static_assert(_GL_UNSIGNALED == GL_UNSIGNALED, "_GL_UNSIGNALED is not equal to GL_UNSIGNALED");
                        static_assert(_GL_SIGNALED == GL_SIGNALED, "_GL_SIGNALED is not equal to GL_SIGNALED");
                        static_assert(_GL_ALREADY_SIGNALED == GL_ALREADY_SIGNALED, "_GL_ALREADY_SIGNALED is not equal to GL_ALREADY_SIGNALED");
                        static_assert(_GL_TIMEOUT_EXPIRED == GL_TIMEOUT_EXPIRED, "_GL_TIMEOUT_EXPIRED is not equal to GL_TIMEOUT_EXPIRED");
                        static_assert(_GL_CONDITION_SATISFIED == GL_CONDITION_SATISFIED, "_GL_CONDITION_SATISFIED is not equal to GL_CONDITION_SATISFIED");
                        static_assert(_GL_WAIT_FAILED == GL_WAIT_FAILED, "_GL_WAIT_FAILED is not equal to GL_WAIT_FAILED");
                        static_assert(_GL_TIMEOUT_IGNORED == GL_TIMEOUT_IGNORED, "_GL_TIMEOUT_IGNORED is not equal to GL_TIMEOUT_IGNORED");
                        static_assert(_GL_SYNC_FLUSH_COMMANDS_BIT == GL_SYNC_FLUSH_COMMANDS_BIT, "_GL_SYNC_FLUSH_COMMANDS_BIT is not equal to GL_SYNC_FLUSH_COMMANDS_BIT");
                        static_assert(_GL_SAMPLE_POSITION == GL_SAMPLE_POSITION, "_GL_SAMPLE_POSITION is not equal to GL_SAMPLE_POSITION");
                        static_assert(_GL_SAMPLE_MASK == GL_SAMPLE_MASK, "_GL_SAMPLE_MASK is not equal to GL_SAMPLE_MASK");
                        static_assert(_GL_SAMPLE_MASK_VALUE == GL_SAMPLE_MASK_VALUE, "_GL_SAMPLE_MASK_VALUE is not equal to GL_SAMPLE_MASK_VALUE");
                        static_assert(_GL_MAX_SAMPLE_MASK_WORDS == GL_MAX_SAMPLE_MASK_WORDS, "_GL_MAX_SAMPLE_MASK_WORDS is not equal to GL_MAX_SAMPLE_MASK_WORDS");
                        static_assert(_GL_TEXTURE_2D_MULTISAMPLE == GL_TEXTURE_2D_MULTISAMPLE, "_GL_TEXTURE_2D_MULTISAMPLE is not equal to GL_TEXTURE_2D_MULTISAMPLE");
                        static_assert(_GL_PROXY_TEXTURE_2D_MULTISAMPLE == GL_PROXY_TEXTURE_2D_MULTISAMPLE, "_GL_PROXY_TEXTURE_2D_MULTISAMPLE is not equal to GL_PROXY_TEXTURE_2D_MULTISAMPLE");
                        static_assert(_GL_TEXTURE_2D_MULTISAMPLE_ARRAY == GL_TEXTURE_2D_MULTISAMPLE_ARRAY, "_GL_TEXTURE_2D_MULTISAMPLE_ARRAY is not equal to GL_TEXTURE_2D_MULTISAMPLE_ARRAY");
                        static_assert(_GL_PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY == GL_PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY, "_GL_PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY is not equal to GL_PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY");
                        static_assert(_GL_TEXTURE_BINDING_2D_MULTISAMPLE == GL_TEXTURE_BINDING_2D_MULTISAMPLE, "_GL_TEXTURE_BINDING_2D_MULTISAMPLE is not equal to GL_TEXTURE_BINDING_2D_MULTISAMPLE");
                        static_assert(_GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY == GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY, "_GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY is not equal to GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY");
                        static_assert(_GL_TEXTURE_SAMPLES == GL_TEXTURE_SAMPLES, "_GL_TEXTURE_SAMPLES is not equal to GL_TEXTURE_SAMPLES");
                        static_assert(_GL_TEXTURE_FIXED_SAMPLE_LOCATIONS == GL_TEXTURE_FIXED_SAMPLE_LOCATIONS, "_GL_TEXTURE_FIXED_SAMPLE_LOCATIONS is not equal to GL_TEXTURE_FIXED_SAMPLE_LOCATIONS");
                        static_assert(_GL_SAMPLER_2D_MULTISAMPLE == GL_SAMPLER_2D_MULTISAMPLE, "_GL_SAMPLER_2D_MULTISAMPLE is not equal to GL_SAMPLER_2D_MULTISAMPLE");
                        static_assert(_GL_INT_SAMPLER_2D_MULTISAMPLE == GL_INT_SAMPLER_2D_MULTISAMPLE, "_GL_INT_SAMPLER_2D_MULTISAMPLE is not equal to GL_INT_SAMPLER_2D_MULTISAMPLE");
                        static_assert(_GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE == GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE, "_GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE is not equal to GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE");
                        static_assert(_GL_SAMPLER_2D_MULTISAMPLE_ARRAY == GL_SAMPLER_2D_MULTISAMPLE_ARRAY, "_GL_SAMPLER_2D_MULTISAMPLE_ARRAY is not equal to GL_SAMPLER_2D_MULTISAMPLE_ARRAY");
                        static_assert(_GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY == GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY, "_GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY is not equal to GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY");
                        static_assert(_GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY == GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY, "_GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY is not equal to GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY");
                        static_assert(_GL_MAX_COLOR_TEXTURE_SAMPLES == GL_MAX_COLOR_TEXTURE_SAMPLES, "_GL_MAX_COLOR_TEXTURE_SAMPLES is not equal to GL_MAX_COLOR_TEXTURE_SAMPLES");
                        static_assert(_GL_MAX_DEPTH_TEXTURE_SAMPLES == GL_MAX_DEPTH_TEXTURE_SAMPLES, "_GL_MAX_DEPTH_TEXTURE_SAMPLES is not equal to GL_MAX_DEPTH_TEXTURE_SAMPLES");
                        static_assert(_GL_MAX_INTEGER_SAMPLES == GL_MAX_INTEGER_SAMPLES, "_GL_MAX_INTEGER_SAMPLES is not equal to GL_MAX_INTEGER_SAMPLES");
                        static_assert(_GL_VERTEX_ATTRIB_ARRAY_DIVISOR == GL_VERTEX_ATTRIB_ARRAY_DIVISOR, "_GL_VERTEX_ATTRIB_ARRAY_DIVISOR is not equal to GL_VERTEX_ATTRIB_ARRAY_DIVISOR");
                        static_assert(_GL_SRC1_COLOR == GL_SRC1_COLOR, "_GL_SRC1_COLOR is not equal to GL_SRC1_COLOR");
                        static_assert(_GL_ONE_MINUS_SRC1_COLOR == GL_ONE_MINUS_SRC1_COLOR, "_GL_ONE_MINUS_SRC1_COLOR is not equal to GL_ONE_MINUS_SRC1_COLOR");
                        static_assert(_GL_ONE_MINUS_SRC1_ALPHA == GL_ONE_MINUS_SRC1_ALPHA, "_GL_ONE_MINUS_SRC1_ALPHA is not equal to GL_ONE_MINUS_SRC1_ALPHA");
                        static_assert(_GL_MAX_DUAL_SOURCE_DRAW_BUFFERS == GL_MAX_DUAL_SOURCE_DRAW_BUFFERS, "_GL_MAX_DUAL_SOURCE_DRAW_BUFFERS is not equal to GL_MAX_DUAL_SOURCE_DRAW_BUFFERS");
                        static_assert(_GL_ANY_SAMPLES_PASSED == GL_ANY_SAMPLES_PASSED, "_GL_ANY_SAMPLES_PASSED is not equal to GL_ANY_SAMPLES_PASSED");
                        static_assert(_GL_SAMPLER_BINDING == GL_SAMPLER_BINDING, "_GL_SAMPLER_BINDING is not equal to GL_SAMPLER_BINDING");
                        static_assert(_GL_RGB10_A2UI == GL_RGB10_A2UI, "_GL_RGB10_A2UI is not equal to GL_RGB10_A2UI");
                        static_assert(_GL_TEXTURE_SWIZZLE_R == GL_TEXTURE_SWIZZLE_R, "_GL_TEXTURE_SWIZZLE_R is not equal to GL_TEXTURE_SWIZZLE_R");
                        static_assert(_GL_TEXTURE_SWIZZLE_G == GL_TEXTURE_SWIZZLE_G, "_GL_TEXTURE_SWIZZLE_G is not equal to GL_TEXTURE_SWIZZLE_G");
                        static_assert(_GL_TEXTURE_SWIZZLE_B == GL_TEXTURE_SWIZZLE_B, "_GL_TEXTURE_SWIZZLE_B is not equal to GL_TEXTURE_SWIZZLE_B");
                        static_assert(_GL_TEXTURE_SWIZZLE_A == GL_TEXTURE_SWIZZLE_A, "_GL_TEXTURE_SWIZZLE_A is not equal to GL_TEXTURE_SWIZZLE_A");
                        static_assert(_GL_TEXTURE_SWIZZLE_RGBA == GL_TEXTURE_SWIZZLE_RGBA, "_GL_TEXTURE_SWIZZLE_RGBA is not equal to GL_TEXTURE_SWIZZLE_RGBA");
                        static_assert(_GL_TIME_ELAPSED == GL_TIME_ELAPSED, "_GL_TIME_ELAPSED is not equal to GL_TIME_ELAPSED");
                        static_assert(_GL_TIMESTAMP == GL_TIMESTAMP, "_GL_TIMESTAMP is not equal to GL_TIMESTAMP");
                        static_assert(_GL_INT_2_10_10_10_REV == GL_INT_2_10_10_10_REV, "_GL_INT_2_10_10_10_REV is not equal to GL_INT_2_10_10_10_REV");
                        static_assert(_GL_SAMPLE_SHADING == GL_SAMPLE_SHADING, "_GL_SAMPLE_SHADING is not equal to GL_SAMPLE_SHADING");
                        static_assert(_GL_MIN_SAMPLE_SHADING_VALUE == GL_MIN_SAMPLE_SHADING_VALUE, "_GL_MIN_SAMPLE_SHADING_VALUE is not equal to GL_MIN_SAMPLE_SHADING_VALUE");
                        static_assert(_GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET == GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET, "_GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET is not equal to GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET");
                        static_assert(_GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET == GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET, "_GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET is not equal to GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET");
                        static_assert(_GL_TEXTURE_CUBE_MAP_ARRAY == GL_TEXTURE_CUBE_MAP_ARRAY, "_GL_TEXTURE_CUBE_MAP_ARRAY is not equal to GL_TEXTURE_CUBE_MAP_ARRAY");
                        static_assert(_GL_TEXTURE_BINDING_CUBE_MAP_ARRAY == GL_TEXTURE_BINDING_CUBE_MAP_ARRAY, "_GL_TEXTURE_BINDING_CUBE_MAP_ARRAY is not equal to GL_TEXTURE_BINDING_CUBE_MAP_ARRAY");
                        static_assert(_GL_PROXY_TEXTURE_CUBE_MAP_ARRAY == GL_PROXY_TEXTURE_CUBE_MAP_ARRAY, "_GL_PROXY_TEXTURE_CUBE_MAP_ARRAY is not equal to GL_PROXY_TEXTURE_CUBE_MAP_ARRAY");
                        static_assert(_GL_SAMPLER_CUBE_MAP_ARRAY == GL_SAMPLER_CUBE_MAP_ARRAY, "_GL_SAMPLER_CUBE_MAP_ARRAY is not equal to GL_SAMPLER_CUBE_MAP_ARRAY");
                        static_assert(_GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW == GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW, "_GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW is not equal to GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW");
                        static_assert(_GL_INT_SAMPLER_CUBE_MAP_ARRAY == GL_INT_SAMPLER_CUBE_MAP_ARRAY, "_GL_INT_SAMPLER_CUBE_MAP_ARRAY is not equal to GL_INT_SAMPLER_CUBE_MAP_ARRAY");
                        static_assert(_GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY == GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY, "_GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY is not equal to GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY");
                        static_assert(_GL_DRAW_INDIRECT_BUFFER == GL_DRAW_INDIRECT_BUFFER, "_GL_DRAW_INDIRECT_BUFFER is not equal to GL_DRAW_INDIRECT_BUFFER");
                        static_assert(_GL_DRAW_INDIRECT_BUFFER_BINDING == GL_DRAW_INDIRECT_BUFFER_BINDING, "_GL_DRAW_INDIRECT_BUFFER_BINDING is not equal to GL_DRAW_INDIRECT_BUFFER_BINDING");
                        static_assert(_GL_GEOMETRY_SHADER_INVOCATIONS == GL_GEOMETRY_SHADER_INVOCATIONS, "_GL_GEOMETRY_SHADER_INVOCATIONS is not equal to GL_GEOMETRY_SHADER_INVOCATIONS");
                        static_assert(_GL_MAX_GEOMETRY_SHADER_INVOCATIONS == GL_MAX_GEOMETRY_SHADER_INVOCATIONS, "_GL_MAX_GEOMETRY_SHADER_INVOCATIONS is not equal to GL_MAX_GEOMETRY_SHADER_INVOCATIONS");
                        static_assert(_GL_MIN_FRAGMENT_INTERPOLATION_OFFSET == GL_MIN_FRAGMENT_INTERPOLATION_OFFSET, "_GL_MIN_FRAGMENT_INTERPOLATION_OFFSET is not equal to GL_MIN_FRAGMENT_INTERPOLATION_OFFSET");
                        static_assert(_GL_MAX_FRAGMENT_INTERPOLATION_OFFSET == GL_MAX_FRAGMENT_INTERPOLATION_OFFSET, "_GL_MAX_FRAGMENT_INTERPOLATION_OFFSET is not equal to GL_MAX_FRAGMENT_INTERPOLATION_OFFSET");
                        static_assert(_GL_FRAGMENT_INTERPOLATION_OFFSET_BITS == GL_FRAGMENT_INTERPOLATION_OFFSET_BITS, "_GL_FRAGMENT_INTERPOLATION_OFFSET_BITS is not equal to GL_FRAGMENT_INTERPOLATION_OFFSET_BITS");
                        static_assert(_GL_MAX_VERTEX_STREAMS == GL_MAX_VERTEX_STREAMS, "_GL_MAX_VERTEX_STREAMS is not equal to GL_MAX_VERTEX_STREAMS");
                        static_assert(_GL_DOUBLE_VEC2 == GL_DOUBLE_VEC2, "_GL_DOUBLE_VEC2 is not equal to GL_DOUBLE_VEC2");
                        static_assert(_GL_DOUBLE_VEC3 == GL_DOUBLE_VEC3, "_GL_DOUBLE_VEC3 is not equal to GL_DOUBLE_VEC3");
                        static_assert(_GL_DOUBLE_VEC4 == GL_DOUBLE_VEC4, "_GL_DOUBLE_VEC4 is not equal to GL_DOUBLE_VEC4");
                        static_assert(_GL_DOUBLE_MAT2 == GL_DOUBLE_MAT2, "_GL_DOUBLE_MAT2 is not equal to GL_DOUBLE_MAT2");
                        static_assert(_GL_DOUBLE_MAT3 == GL_DOUBLE_MAT3, "_GL_DOUBLE_MAT3 is not equal to GL_DOUBLE_MAT3");
                        static_assert(_GL_DOUBLE_MAT4 == GL_DOUBLE_MAT4, "_GL_DOUBLE_MAT4 is not equal to GL_DOUBLE_MAT4");
                        static_assert(_GL_DOUBLE_MAT2x3 == GL_DOUBLE_MAT2x3, "_GL_DOUBLE_MAT2x3 is not equal to GL_DOUBLE_MAT2x3");
                        static_assert(_GL_DOUBLE_MAT2x4 == GL_DOUBLE_MAT2x4, "_GL_DOUBLE_MAT2x4 is not equal to GL_DOUBLE_MAT2x4");
                        static_assert(_GL_DOUBLE_MAT3x2 == GL_DOUBLE_MAT3x2, "_GL_DOUBLE_MAT3x2 is not equal to GL_DOUBLE_MAT3x2");
                        static_assert(_GL_DOUBLE_MAT3x4 == GL_DOUBLE_MAT3x4, "_GL_DOUBLE_MAT3x4 is not equal to GL_DOUBLE_MAT3x4");
                        static_assert(_GL_DOUBLE_MAT4x2 == GL_DOUBLE_MAT4x2, "_GL_DOUBLE_MAT4x2 is not equal to GL_DOUBLE_MAT4x2");
                        static_assert(_GL_DOUBLE_MAT4x3 == GL_DOUBLE_MAT4x3, "_GL_DOUBLE_MAT4x3 is not equal to GL_DOUBLE_MAT4x3");
                        static_assert(_GL_ACTIVE_SUBROUTINES == GL_ACTIVE_SUBROUTINES, "_GL_ACTIVE_SUBROUTINES is not equal to GL_ACTIVE_SUBROUTINES");
                        static_assert(_GL_ACTIVE_SUBROUTINE_UNIFORMS == GL_ACTIVE_SUBROUTINE_UNIFORMS, "_GL_ACTIVE_SUBROUTINE_UNIFORMS is not equal to GL_ACTIVE_SUBROUTINE_UNIFORMS");
                        static_assert(_GL_ACTIVE_SUBROUTINE_UNIFORM_LOCATIONS == GL_ACTIVE_SUBROUTINE_UNIFORM_LOCATIONS, "_GL_ACTIVE_SUBROUTINE_UNIFORM_LOCATIONS is not equal to GL_ACTIVE_SUBROUTINE_UNIFORM_LOCATIONS");
                        static_assert(_GL_ACTIVE_SUBROUTINE_MAX_LENGTH == GL_ACTIVE_SUBROUTINE_MAX_LENGTH, "_GL_ACTIVE_SUBROUTINE_MAX_LENGTH is not equal to GL_ACTIVE_SUBROUTINE_MAX_LENGTH");
                        static_assert(_GL_ACTIVE_SUBROUTINE_UNIFORM_MAX_LENGTH == GL_ACTIVE_SUBROUTINE_UNIFORM_MAX_LENGTH, "_GL_ACTIVE_SUBROUTINE_UNIFORM_MAX_LENGTH is not equal to GL_ACTIVE_SUBROUTINE_UNIFORM_MAX_LENGTH");
                        static_assert(_GL_MAX_SUBROUTINES == GL_MAX_SUBROUTINES, "_GL_MAX_SUBROUTINES is not equal to GL_MAX_SUBROUTINES");
                        static_assert(_GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS == GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS, "_GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS is not equal to GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS");
                        static_assert(_GL_NUM_COMPATIBLE_SUBROUTINES == GL_NUM_COMPATIBLE_SUBROUTINES, "_GL_NUM_COMPATIBLE_SUBROUTINES is not equal to GL_NUM_COMPATIBLE_SUBROUTINES");
                        static_assert(_GL_COMPATIBLE_SUBROUTINES == GL_COMPATIBLE_SUBROUTINES, "_GL_COMPATIBLE_SUBROUTINES is not equal to GL_COMPATIBLE_SUBROUTINES");
                        static_assert(_GL_PATCHES == GL_PATCHES, "_GL_PATCHES is not equal to GL_PATCHES");
                        static_assert(_GL_PATCH_VERTICES == GL_PATCH_VERTICES, "_GL_PATCH_VERTICES is not equal to GL_PATCH_VERTICES");
                        static_assert(_GL_PATCH_DEFAULT_INNER_LEVEL == GL_PATCH_DEFAULT_INNER_LEVEL, "_GL_PATCH_DEFAULT_INNER_LEVEL is not equal to GL_PATCH_DEFAULT_INNER_LEVEL");
                        static_assert(_GL_PATCH_DEFAULT_OUTER_LEVEL == GL_PATCH_DEFAULT_OUTER_LEVEL, "_GL_PATCH_DEFAULT_OUTER_LEVEL is not equal to GL_PATCH_DEFAULT_OUTER_LEVEL");
                        static_assert(_GL_TESS_CONTROL_OUTPUT_VERTICES == GL_TESS_CONTROL_OUTPUT_VERTICES, "_GL_TESS_CONTROL_OUTPUT_VERTICES is not equal to GL_TESS_CONTROL_OUTPUT_VERTICES");
                        static_assert(_GL_TESS_GEN_MODE == GL_TESS_GEN_MODE, "_GL_TESS_GEN_MODE is not equal to GL_TESS_GEN_MODE");
                        static_assert(_GL_TESS_GEN_SPACING == GL_TESS_GEN_SPACING, "_GL_TESS_GEN_SPACING is not equal to GL_TESS_GEN_SPACING");
                        static_assert(_GL_TESS_GEN_VERTEX_ORDER == GL_TESS_GEN_VERTEX_ORDER, "_GL_TESS_GEN_VERTEX_ORDER is not equal to GL_TESS_GEN_VERTEX_ORDER");
                        static_assert(_GL_TESS_GEN_POINT_MODE == GL_TESS_GEN_POINT_MODE, "_GL_TESS_GEN_POINT_MODE is not equal to GL_TESS_GEN_POINT_MODE");
                        static_assert(_GL_ISOLINES == GL_ISOLINES, "_GL_ISOLINES is not equal to GL_ISOLINES");
                        static_assert(_GL_QUADS == GL_QUADS, "_GL_QUADS is not equal to GL_QUADS");
                        static_assert(_GL_FRACTIONAL_ODD == GL_FRACTIONAL_ODD, "_GL_FRACTIONAL_ODD is not equal to GL_FRACTIONAL_ODD");
                        static_assert(_GL_FRACTIONAL_EVEN == GL_FRACTIONAL_EVEN, "_GL_FRACTIONAL_EVEN is not equal to GL_FRACTIONAL_EVEN");
                        static_assert(_GL_MAX_PATCH_VERTICES == GL_MAX_PATCH_VERTICES, "_GL_MAX_PATCH_VERTICES is not equal to GL_MAX_PATCH_VERTICES");
                        static_assert(_GL_MAX_TESS_GEN_LEVEL == GL_MAX_TESS_GEN_LEVEL, "_GL_MAX_TESS_GEN_LEVEL is not equal to GL_MAX_TESS_GEN_LEVEL");
                        static_assert(_GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS == GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS, "_GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS is not equal to GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS");
                        static_assert(_GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS == GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS, "_GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS is not equal to GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS");
                        static_assert(_GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS == GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS, "_GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS is not equal to GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS");
                        static_assert(_GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS == GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS, "_GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS is not equal to GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS");
                        static_assert(_GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS == GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS, "_GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS is not equal to GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS");
                        static_assert(_GL_MAX_TESS_PATCH_COMPONENTS == GL_MAX_TESS_PATCH_COMPONENTS, "_GL_MAX_TESS_PATCH_COMPONENTS is not equal to GL_MAX_TESS_PATCH_COMPONENTS");
                        static_assert(_GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS == GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS, "_GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS is not equal to GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS");
                        static_assert(_GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS == GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS, "_GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS is not equal to GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS");
                        static_assert(_GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS == GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS, "_GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS is not equal to GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS");
                        static_assert(_GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS == GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS, "_GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS is not equal to GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS");
                        static_assert(_GL_MAX_TESS_CONTROL_INPUT_COMPONENTS == GL_MAX_TESS_CONTROL_INPUT_COMPONENTS, "_GL_MAX_TESS_CONTROL_INPUT_COMPONENTS is not equal to GL_MAX_TESS_CONTROL_INPUT_COMPONENTS");
                        static_assert(_GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS == GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS, "_GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS is not equal to GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS");
                        static_assert(_GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS == GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS, "_GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS is not equal to GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS");
                        static_assert(_GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS == GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS, "_GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS is not equal to GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS");
                        static_assert(_GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER == GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER, "_GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER is not equal to GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER");
                        static_assert(_GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER == GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER, "_GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER is not equal to GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER");
                        static_assert(_GL_TESS_EVALUATION_SHADER == GL_TESS_EVALUATION_SHADER, "_GL_TESS_EVALUATION_SHADER is not equal to GL_TESS_EVALUATION_SHADER");
                        static_assert(_GL_TESS_CONTROL_SHADER == GL_TESS_CONTROL_SHADER, "_GL_TESS_CONTROL_SHADER is not equal to GL_TESS_CONTROL_SHADER");
                        static_assert(_GL_TRANSFORM_FEEDBACK == GL_TRANSFORM_FEEDBACK, "_GL_TRANSFORM_FEEDBACK is not equal to GL_TRANSFORM_FEEDBACK");
                        static_assert(_GL_TRANSFORM_FEEDBACK_BUFFER_PAUSED == GL_TRANSFORM_FEEDBACK_BUFFER_PAUSED, "_GL_TRANSFORM_FEEDBACK_BUFFER_PAUSED is not equal to GL_TRANSFORM_FEEDBACK_BUFFER_PAUSED");
                        static_assert(_GL_TRANSFORM_FEEDBACK_BUFFER_ACTIVE == GL_TRANSFORM_FEEDBACK_BUFFER_ACTIVE, "_GL_TRANSFORM_FEEDBACK_BUFFER_ACTIVE is not equal to GL_TRANSFORM_FEEDBACK_BUFFER_ACTIVE");
                        static_assert(_GL_TRANSFORM_FEEDBACK_BINDING == GL_TRANSFORM_FEEDBACK_BINDING, "_GL_TRANSFORM_FEEDBACK_BINDING is not equal to GL_TRANSFORM_FEEDBACK_BINDING");
                        static_assert(_GL_MAX_TRANSFORM_FEEDBACK_BUFFERS == GL_MAX_TRANSFORM_FEEDBACK_BUFFERS, "_GL_MAX_TRANSFORM_FEEDBACK_BUFFERS is not equal to GL_MAX_TRANSFORM_FEEDBACK_BUFFERS");
                    }
#endif
                }
            }
        }
    }
}

#endif
