#pragma once
#ifndef UE_GLAD_CONSTANTS_PART_5_INTERNAL_
#define UE_GLAD_CONSTANTS_PART_5_INTERNAL_
#ifndef __INTELLISENSE__
#ifndef UE_OPENGL_BUILD_
#error "this file should not be directly included in user code. use import UPRISE_ENGINE_CORE instead"
#endif
#endif
#include "OPENGL/GLAD/STUPIDMACROS/GLAD_MACROS.h"
#ifdef __INTELLISENSE__
#ifndef DONT_INCLUDE_GLAD
#include <glad.h>
#endif
#endif // __INTELLISENSE__
namespace UPRISE_ENGINE {
    namespace RENDER {
        namespace GLAD {
            namespace CONSTANTS {
                constexpr int _GL_FLOAT_VEC2 = 0x8B50;
                constexpr int _GL_FLOAT_VEC3 = 0x8B51;
                constexpr int _GL_FLOAT_VEC4 = 0x8B52;
                constexpr int _GL_INT_VEC2 = 0x8B53;
                constexpr int _GL_INT_VEC3 = 0x8B54;
                constexpr int _GL_INT_VEC4 = 0x8B55;
                constexpr int _GL_BOOL = 0x8B56;
                constexpr int _GL_BOOL_VEC2 = 0x8B57;
                constexpr int _GL_BOOL_VEC3 = 0x8B58;
                constexpr int _GL_BOOL_VEC4 = 0x8B59;
                constexpr int _GL_FLOAT_MAT2 = 0x8B5A;
                constexpr int _GL_FLOAT_MAT3 = 0x8B5B;
                constexpr int _GL_FLOAT_MAT4 = 0x8B5C;
                constexpr int _GL_SAMPLER_1D = 0x8B5D;
                constexpr int _GL_SAMPLER_2D = 0x8B5E;
                constexpr int _GL_SAMPLER_3D = 0x8B5F;
                constexpr int _GL_SAMPLER_CUBE = 0x8B60;
                constexpr int _GL_SAMPLER_1D_SHADOW = 0x8B61;
                constexpr int _GL_SAMPLER_2D_SHADOW = 0x8B62;
                constexpr int _GL_DELETE_STATUS = 0x8B80;
                constexpr int _GL_COMPILE_STATUS = 0x8B81;
                constexpr int _GL_LINK_STATUS = 0x8B82;
                constexpr int _GL_VALIDATE_STATUS = 0x8B83;
                constexpr int _GL_INFO_LOG_LENGTH = 0x8B84;
                constexpr int _GL_ATTACHED_SHADERS = 0x8B85;
                constexpr int _GL_ACTIVE_UNIFORMS = 0x8B86;
                constexpr int _GL_ACTIVE_UNIFORM_MAX_LENGTH = 0x8B87;
                constexpr int _GL_SHADER_SOURCE_LENGTH = 0x8B88;
                constexpr int _GL_ACTIVE_ATTRIBUTES = 0x8B89;
                constexpr int _GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = 0x8B8A;
                constexpr int _GL_FRAGMENT_SHADER_DERIVATIVE_HINT = 0x8B8B;
                constexpr int _GL_SHADING_LANGUAGE_VERSION = 0x8B8C;
                constexpr int _GL_CURRENT_PROGRAM = 0x8B8D;
                constexpr int _GL_POINT_SPRITE_COORD_ORIGIN = 0x8CA0;
                constexpr int _GL_LOWER_LEFT = 0x8CA1;
                constexpr int _GL_UPPER_LEFT = 0x8CA2;
                constexpr int _GL_STENCIL_BACK_REF = 0x8CA3;
                constexpr int _GL_STENCIL_BACK_VALUE_MASK = 0x8CA4;
                constexpr int _GL_STENCIL_BACK_WRITEMASK = 0x8CA5;
                constexpr int _GL_PIXEL_PACK_BUFFER = 0x88EB;
                constexpr int _GL_PIXEL_UNPACK_BUFFER = 0x88EC;
                constexpr int _GL_PIXEL_PACK_BUFFER_BINDING = 0x88ED;
                constexpr int _GL_PIXEL_UNPACK_BUFFER_BINDING = 0x88EF;
                constexpr int _GL_FLOAT_MAT2x3 = 0x8B65;
                constexpr int _GL_FLOAT_MAT2x4 = 0x8B66;
                constexpr int _GL_FLOAT_MAT3x2 = 0x8B67;
                constexpr int _GL_FLOAT_MAT3x4 = 0x8B68;
                constexpr int _GL_FLOAT_MAT4x2 = 0x8B69;
                constexpr int _GL_FLOAT_MAT4x3 = 0x8B6A;
                constexpr int _GL_SRGB = 0x8C40;
                constexpr int _GL_SRGB8 = 0x8C41;
                constexpr int _GL_SRGB_ALPHA = 0x8C42;
                constexpr int _GL_SRGB8_ALPHA8 = 0x8C43;
                constexpr int _GL_COMPRESSED_SRGB = 0x8C48;
                constexpr int _GL_COMPRESSED_SRGB_ALPHA = 0x8C49;
                constexpr int _GL_COMPARE_REF_TO_TEXTURE = 0x884E;
                constexpr int _GL_CLIP_DISTANCE0 = 0x3000;
                constexpr int _GL_CLIP_DISTANCE1 = 0x3001;
                constexpr int _GL_CLIP_DISTANCE2 = 0x3002;
                constexpr int _GL_CLIP_DISTANCE3 = 0x3003;
                constexpr int _GL_CLIP_DISTANCE4 = 0x3004;
                constexpr int _GL_CLIP_DISTANCE5 = 0x3005;
                constexpr int _GL_CLIP_DISTANCE6 = 0x3006;
                constexpr int _GL_CLIP_DISTANCE7 = 0x3007;
                constexpr int _GL_MAX_CLIP_DISTANCES = 0x0D32;
                constexpr int _GL_MAJOR_VERSION = 0x821B;
                constexpr int _GL_MINOR_VERSION = 0x821C;
                constexpr int _GL_NUM_EXTENSIONS = 0x821D;
                constexpr int _GL_CONTEXT_FLAGS = 0x821E;
                constexpr int _GL_COMPRESSED_RED = 0x8225;
                constexpr int _GL_COMPRESSED_RG = 0x8226;
                constexpr int _GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT = 0x00000001;
                constexpr int _GL_RGBA32F = 0x8814;
                constexpr int _GL_RGB32F = 0x8815;
                constexpr int _GL_RGBA16F = 0x881A;
                constexpr int _GL_RGB16F = 0x881B;
                constexpr int _GL_VERTEX_ATTRIB_ARRAY_INTEGER = 0x88FD;
                constexpr int _GL_MAX_ARRAY_TEXTURE_LAYERS = 0x88FF;
                constexpr int _GL_MIN_PROGRAM_TEXEL_OFFSET = 0x8904;
                constexpr int _GL_MAX_PROGRAM_TEXEL_OFFSET = 0x8905;
                constexpr int _GL_CLAMP_READ_COLOR = 0x891C;
                constexpr int _GL_FIXED_ONLY = 0x891D;
                constexpr int _GL_MAX_VARYING_COMPONENTS = 0x8B4B;
                constexpr int _GL_TEXTURE_1D_ARRAY = 0x8C18;
                constexpr int _GL_PROXY_TEXTURE_1D_ARRAY = 0x8C19;
                constexpr int _GL_TEXTURE_2D_ARRAY = 0x8C1A;
                constexpr int _GL_PROXY_TEXTURE_2D_ARRAY = 0x8C1B;
                constexpr int _GL_TEXTURE_BINDING_1D_ARRAY = 0x8C1C;
                constexpr int _GL_TEXTURE_BINDING_2D_ARRAY = 0x8C1D;
                constexpr int _GL_R11F_G11F_B10F = 0x8C3A;
                constexpr int _GL_UNSIGNED_INT_10F_11F_11F_REV = 0x8C3B;
                constexpr int _GL_RGB9_E5 = 0x8C3D;
                constexpr int _GL_UNSIGNED_INT_5_9_9_9_REV = 0x8C3E;
                constexpr int _GL_TEXTURE_SHARED_SIZE = 0x8C3F;
                constexpr int _GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = 0x8C76;
                constexpr int _GL_TRANSFORM_FEEDBACK_BUFFER_MODE = 0x8C7F;
                constexpr int _GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = 0x8C80;
                constexpr int _GL_TRANSFORM_FEEDBACK_VARYINGS = 0x8C83;
                constexpr int _GL_TRANSFORM_FEEDBACK_BUFFER_START = 0x8C84;
                constexpr int _GL_TRANSFORM_FEEDBACK_BUFFER_SIZE = 0x8C85;
                constexpr int _GL_PRIMITIVES_GENERATED = 0x8C87;
                constexpr int _GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = 0x8C88;
                constexpr int _GL_RASTERIZER_DISCARD = 0x8C89;
                constexpr int _GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = 0x8C8A;
                constexpr int _GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = 0x8C8B;
                constexpr int _GL_INTERLEAVED_ATTRIBS = 0x8C8C;
                constexpr int _GL_SEPARATE_ATTRIBS = 0x8C8D;
                constexpr int _GL_TRANSFORM_FEEDBACK_BUFFER = 0x8C8E;
                constexpr int _GL_TRANSFORM_FEEDBACK_BUFFER_BINDING = 0x8C8F;
                constexpr int _GL_RGBA32UI = 0x8D70;
                constexpr int _GL_RGB32UI = 0x8D71;
                constexpr int _GL_RGBA16UI = 0x8D76;
                constexpr int _GL_RGB16UI = 0x8D77;
                constexpr int _GL_RGBA8UI = 0x8D7C;
                constexpr int _GL_RGB8UI = 0x8D7D;
                constexpr int _GL_RGBA32I = 0x8D82;
                constexpr int _GL_RGB32I = 0x8D83;
                constexpr int _GL_RGBA16I = 0x8D88;
                constexpr int _GL_RGB16I = 0x8D89;
                constexpr int _GL_RGBA8I = 0x8D8E;
                constexpr int _GL_RGB8I = 0x8D8F;
                constexpr int _GL_RED_INTEGER = 0x8D94;
                constexpr int _GL_GREEN_INTEGER = 0x8D95;
                constexpr int _GL_BLUE_INTEGER = 0x8D96;
                constexpr int _GL_RGB_INTEGER = 0x8D98;
                constexpr int _GL_RGBA_INTEGER = 0x8D99;
                constexpr int _GL_BGR_INTEGER = 0x8D9A;
                constexpr int _GL_BGRA_INTEGER = 0x8D9B;
                constexpr int _GL_SAMPLER_1D_ARRAY = 0x8DC0;
                constexpr int _GL_SAMPLER_2D_ARRAY = 0x8DC1;
                constexpr int _GL_SAMPLER_1D_ARRAY_SHADOW = 0x8DC3;
                constexpr int _GL_SAMPLER_2D_ARRAY_SHADOW = 0x8DC4;
                constexpr int _GL_SAMPLER_CUBE_SHADOW = 0x8DC5;
                constexpr int _GL_UNSIGNED_INT_VEC2 = 0x8DC6;
                constexpr int _GL_UNSIGNED_INT_VEC3 = 0x8DC7;
                constexpr int _GL_UNSIGNED_INT_VEC4 = 0x8DC8;
                constexpr int _GL_INT_SAMPLER_1D = 0x8DC9;
                constexpr int _GL_INT_SAMPLER_2D = 0x8DCA;
                constexpr int _GL_INT_SAMPLER_3D = 0x8DCB;
                constexpr int _GL_INT_SAMPLER_CUBE = 0x8DCC;
                constexpr int _GL_INT_SAMPLER_1D_ARRAY = 0x8DCE;
                constexpr int _GL_INT_SAMPLER_2D_ARRAY = 0x8DCF;
                constexpr int _GL_UNSIGNED_INT_SAMPLER_1D = 0x8DD1;
                constexpr int _GL_UNSIGNED_INT_SAMPLER_2D = 0x8DD2;
                constexpr int _GL_UNSIGNED_INT_SAMPLER_3D = 0x8DD3;
                constexpr int _GL_UNSIGNED_INT_SAMPLER_CUBE = 0x8DD4;
                constexpr int _GL_UNSIGNED_INT_SAMPLER_1D_ARRAY = 0x8DD6;
                constexpr int _GL_UNSIGNED_INT_SAMPLER_2D_ARRAY = 0x8DD7;
                constexpr int _GL_QUERY_WAIT = 0x8E13;
                constexpr int _GL_QUERY_NO_WAIT = 0x8E14;
                constexpr int _GL_QUERY_BY_REGION_WAIT = 0x8E15;
                constexpr int _GL_QUERY_BY_REGION_NO_WAIT = 0x8E16;
                constexpr int _GL_BUFFER_ACCESS_FLAGS = 0x911F;
                constexpr int _GL_BUFFER_MAP_LENGTH = 0x9120;
                constexpr int _GL_BUFFER_MAP_OFFSET = 0x9121;
                constexpr int _GL_DEPTH_COMPONENT32F = 0x8CAC;
                constexpr int _GL_DEPTH32F_STENCIL8 = 0x8CAD;
                constexpr int _GL_FLOAT_32_UNSIGNED_INT_24_8_REV = 0x8DAD;
                constexpr int _GL_INVALID_FRAMEBUFFER_OPERATION = 0x0506;
#ifndef DONT_INCLUDE_GLAD
                consteval void CheckConstantsPart5() {
                    static_assert(_GL_FLOAT_VEC2 == GL_FLOAT_VEC2, "_GL_FLOAT_VEC2 is not equal to GL_FLOAT_VEC2");
                    static_assert(_GL_FLOAT_VEC3 == GL_FLOAT_VEC3, "_GL_FLOAT_VEC3 is not equal to GL_FLOAT_VEC3");
                    static_assert(_GL_FLOAT_VEC4 == GL_FLOAT_VEC4, "_GL_FLOAT_VEC4 is not equal to GL_FLOAT_VEC4");
                    static_assert(_GL_INT_VEC2 == GL_INT_VEC2, "_GL_INT_VEC2 is not equal to GL_INT_VEC2");
                    static_assert(_GL_INT_VEC3 == GL_INT_VEC3, "_GL_INT_VEC3 is not equal to GL_INT_VEC3");
                    static_assert(_GL_INT_VEC4 == GL_INT_VEC4, "_GL_INT_VEC4 is not equal to GL_INT_VEC4");
                    static_assert(_GL_BOOL == GL_BOOL, "_GL_BOOL is not equal to GL_BOOL");
                    static_assert(_GL_BOOL_VEC2 == GL_BOOL_VEC2, "_GL_BOOL_VEC2 is not equal to GL_BOOL_VEC2");
                    static_assert(_GL_BOOL_VEC3 == GL_BOOL_VEC3, "_GL_BOOL_VEC3 is not equal to GL_BOOL_VEC3");
                    static_assert(_GL_BOOL_VEC4 == GL_BOOL_VEC4, "_GL_BOOL_VEC4 is not equal to GL_BOOL_VEC4");
                    static_assert(_GL_FLOAT_MAT2 == GL_FLOAT_MAT2, "_GL_FLOAT_MAT2 is not equal to GL_FLOAT_MAT2");
                    static_assert(_GL_FLOAT_MAT3 == GL_FLOAT_MAT3, "_GL_FLOAT_MAT3 is not equal to GL_FLOAT_MAT3");
                    static_assert(_GL_FLOAT_MAT4 == GL_FLOAT_MAT4, "_GL_FLOAT_MAT4 is not equal to GL_FLOAT_MAT4");
                    static_assert(_GL_SAMPLER_1D == GL_SAMPLER_1D, "_GL_SAMPLER_1D is not equal to GL_SAMPLER_1D");
                    static_assert(_GL_SAMPLER_2D == GL_SAMPLER_2D, "_GL_SAMPLER_2D is not equal to GL_SAMPLER_2D");
                    static_assert(_GL_SAMPLER_3D == GL_SAMPLER_3D, "_GL_SAMPLER_3D is not equal to GL_SAMPLER_3D");
                    static_assert(_GL_SAMPLER_CUBE == GL_SAMPLER_CUBE, "_GL_SAMPLER_CUBE is not equal to GL_SAMPLER_CUBE");
                    static_assert(_GL_SAMPLER_1D_SHADOW == GL_SAMPLER_1D_SHADOW, "_GL_SAMPLER_1D_SHADOW is not equal to GL_SAMPLER_1D_SHADOW");
                    static_assert(_GL_SAMPLER_2D_SHADOW == GL_SAMPLER_2D_SHADOW, "_GL_SAMPLER_2D_SHADOW is not equal to GL_SAMPLER_2D_SHADOW");
                    static_assert(_GL_DELETE_STATUS == GL_DELETE_STATUS, "_GL_DELETE_STATUS is not equal to GL_DELETE_STATUS");
                    static_assert(_GL_COMPILE_STATUS == GL_COMPILE_STATUS, "_GL_COMPILE_STATUS is not equal to GL_COMPILE_STATUS");
                    static_assert(_GL_LINK_STATUS == GL_LINK_STATUS, "_GL_LINK_STATUS is not equal to GL_LINK_STATUS");
                    static_assert(_GL_VALIDATE_STATUS == GL_VALIDATE_STATUS, "_GL_VALIDATE_STATUS is not equal to GL_VALIDATE_STATUS");
                    static_assert(_GL_INFO_LOG_LENGTH == GL_INFO_LOG_LENGTH, "_GL_INFO_LOG_LENGTH is not equal to GL_INFO_LOG_LENGTH");
                    static_assert(_GL_ATTACHED_SHADERS == GL_ATTACHED_SHADERS, "_GL_ATTACHED_SHADERS is not equal to GL_ATTACHED_SHADERS");
                    static_assert(_GL_ACTIVE_UNIFORMS == GL_ACTIVE_UNIFORMS, "_GL_ACTIVE_UNIFORMS is not equal to GL_ACTIVE_UNIFORMS");
                    static_assert(_GL_ACTIVE_UNIFORM_MAX_LENGTH == GL_ACTIVE_UNIFORM_MAX_LENGTH, "_GL_ACTIVE_UNIFORM_MAX_LENGTH is not equal to GL_ACTIVE_UNIFORM_MAX_LENGTH");
                    static_assert(_GL_SHADER_SOURCE_LENGTH == GL_SHADER_SOURCE_LENGTH, "_GL_SHADER_SOURCE_LENGTH is not equal to GL_SHADER_SOURCE_LENGTH");
                    static_assert(_GL_ACTIVE_ATTRIBUTES == GL_ACTIVE_ATTRIBUTES, "_GL_ACTIVE_ATTRIBUTES is not equal to GL_ACTIVE_ATTRIBUTES");
                    static_assert(_GL_ACTIVE_ATTRIBUTE_MAX_LENGTH == GL_ACTIVE_ATTRIBUTE_MAX_LENGTH, "_GL_ACTIVE_ATTRIBUTE_MAX_LENGTH is not equal to GL_ACTIVE_ATTRIBUTE_MAX_LENGTH");
                    static_assert(_GL_FRAGMENT_SHADER_DERIVATIVE_HINT == GL_FRAGMENT_SHADER_DERIVATIVE_HINT, "_GL_FRAGMENT_SHADER_DERIVATIVE_HINT is not equal to GL_FRAGMENT_SHADER_DERIVATIVE_HINT");
                    static_assert(_GL_SHADING_LANGUAGE_VERSION == GL_SHADING_LANGUAGE_VERSION, "_GL_SHADING_LANGUAGE_VERSION is not equal to GL_SHADING_LANGUAGE_VERSION");
                    static_assert(_GL_CURRENT_PROGRAM == GL_CURRENT_PROGRAM, "_GL_CURRENT_PROGRAM is not equal to GL_CURRENT_PROGRAM");
                    static_assert(_GL_POINT_SPRITE_COORD_ORIGIN == GL_POINT_SPRITE_COORD_ORIGIN, "_GL_POINT_SPRITE_COORD_ORIGIN is not equal to GL_POINT_SPRITE_COORD_ORIGIN");
                    static_assert(_GL_LOWER_LEFT == GL_LOWER_LEFT, "_GL_LOWER_LEFT is not equal to GL_LOWER_LEFT");
                    static_assert(_GL_UPPER_LEFT == GL_UPPER_LEFT, "_GL_UPPER_LEFT is not equal to GL_UPPER_LEFT");
                    static_assert(_GL_STENCIL_BACK_REF == GL_STENCIL_BACK_REF, "_GL_STENCIL_BACK_REF is not equal to GL_STENCIL_BACK_REF");
                    static_assert(_GL_STENCIL_BACK_VALUE_MASK == GL_STENCIL_BACK_VALUE_MASK, "_GL_STENCIL_BACK_VALUE_MASK is not equal to GL_STENCIL_BACK_VALUE_MASK");
                    static_assert(_GL_STENCIL_BACK_WRITEMASK == GL_STENCIL_BACK_WRITEMASK, "_GL_STENCIL_BACK_WRITEMASK is not equal to GL_STENCIL_BACK_WRITEMASK");
                    static_assert(_GL_PIXEL_PACK_BUFFER == GL_PIXEL_PACK_BUFFER, "_GL_PIXEL_PACK_BUFFER is not equal to GL_PIXEL_PACK_BUFFER");
                    static_assert(_GL_PIXEL_UNPACK_BUFFER == GL_PIXEL_UNPACK_BUFFER, "_GL_PIXEL_UNPACK_BUFFER is not equal to GL_PIXEL_UNPACK_BUFFER");
                    static_assert(_GL_PIXEL_PACK_BUFFER_BINDING == GL_PIXEL_PACK_BUFFER_BINDING, "_GL_PIXEL_PACK_BUFFER_BINDING is not equal to GL_PIXEL_PACK_BUFFER_BINDING");
                    static_assert(_GL_PIXEL_UNPACK_BUFFER_BINDING == GL_PIXEL_UNPACK_BUFFER_BINDING, "_GL_PIXEL_UNPACK_BUFFER_BINDING is not equal to GL_PIXEL_UNPACK_BUFFER_BINDING");
                    static_assert(_GL_FLOAT_MAT2x3 == GL_FLOAT_MAT2x3, "_GL_FLOAT_MAT2x3 is not equal to GL_FLOAT_MAT2x3");
                    static_assert(_GL_FLOAT_MAT2x4 == GL_FLOAT_MAT2x4, "_GL_FLOAT_MAT2x4 is not equal to GL_FLOAT_MAT2x4");
                    static_assert(_GL_FLOAT_MAT3x2 == GL_FLOAT_MAT3x2, "_GL_FLOAT_MAT3x2 is not equal to GL_FLOAT_MAT3x2");
                    static_assert(_GL_FLOAT_MAT3x4 == GL_FLOAT_MAT3x4, "_GL_FLOAT_MAT3x4 is not equal to GL_FLOAT_MAT3x4");
                    static_assert(_GL_FLOAT_MAT4x2 == GL_FLOAT_MAT4x2, "_GL_FLOAT_MAT4x2 is not equal to GL_FLOAT_MAT4x2");
                    static_assert(_GL_FLOAT_MAT4x3 == GL_FLOAT_MAT4x3, "_GL_FLOAT_MAT4x3 is not equal to GL_FLOAT_MAT4x3");
                    static_assert(_GL_SRGB == GL_SRGB, "_GL_SRGB is not equal to GL_SRGB");
                    static_assert(_GL_SRGB8 == GL_SRGB8, "_GL_SRGB8 is not equal to GL_SRGB8");
                    static_assert(_GL_SRGB_ALPHA == GL_SRGB_ALPHA, "_GL_SRGB_ALPHA is not equal to GL_SRGB_ALPHA");
                    static_assert(_GL_SRGB8_ALPHA8 == GL_SRGB8_ALPHA8, "_GL_SRGB8_ALPHA8 is not equal to GL_SRGB8_ALPHA8");
                    static_assert(_GL_COMPRESSED_SRGB == GL_COMPRESSED_SRGB, "_GL_COMPRESSED_SRGB is not equal to GL_COMPRESSED_SRGB");
                    static_assert(_GL_COMPRESSED_SRGB_ALPHA == GL_COMPRESSED_SRGB_ALPHA, "_GL_COMPRESSED_SRGB_ALPHA is not equal to GL_COMPRESSED_SRGB_ALPHA");
                    static_assert(_GL_COMPARE_REF_TO_TEXTURE == GL_COMPARE_REF_TO_TEXTURE, "_GL_COMPARE_REF_TO_TEXTURE is not equal to GL_COMPARE_REF_TO_TEXTURE");
                    static_assert(_GL_CLIP_DISTANCE0 == GL_CLIP_DISTANCE0, "_GL_CLIP_DISTANCE0 is not equal to GL_CLIP_DISTANCE0");
                    static_assert(_GL_CLIP_DISTANCE1 == GL_CLIP_DISTANCE1, "_GL_CLIP_DISTANCE1 is not equal to GL_CLIP_DISTANCE1");
                    static_assert(_GL_CLIP_DISTANCE2 == GL_CLIP_DISTANCE2, "_GL_CLIP_DISTANCE2 is not equal to GL_CLIP_DISTANCE2");
                    static_assert(_GL_CLIP_DISTANCE3 == GL_CLIP_DISTANCE3, "_GL_CLIP_DISTANCE3 is not equal to GL_CLIP_DISTANCE3");
                    static_assert(_GL_CLIP_DISTANCE4 == GL_CLIP_DISTANCE4, "_GL_CLIP_DISTANCE4 is not equal to GL_CLIP_DISTANCE4");
                    static_assert(_GL_CLIP_DISTANCE5 == GL_CLIP_DISTANCE5, "_GL_CLIP_DISTANCE5 is not equal to GL_CLIP_DISTANCE5");
                    static_assert(_GL_CLIP_DISTANCE6 == GL_CLIP_DISTANCE6, "_GL_CLIP_DISTANCE6 is not equal to GL_CLIP_DISTANCE6");
                    static_assert(_GL_CLIP_DISTANCE7 == GL_CLIP_DISTANCE7, "_GL_CLIP_DISTANCE7 is not equal to GL_CLIP_DISTANCE7");
                    static_assert(_GL_MAX_CLIP_DISTANCES == GL_MAX_CLIP_DISTANCES, "_GL_MAX_CLIP_DISTANCES is not equal to GL_MAX_CLIP_DISTANCES");
                    static_assert(_GL_MAJOR_VERSION == GL_MAJOR_VERSION, "_GL_MAJOR_VERSION is not equal to GL_MAJOR_VERSION");
                    static_assert(_GL_MINOR_VERSION == GL_MINOR_VERSION, "_GL_MINOR_VERSION is not equal to GL_MINOR_VERSION");
                    static_assert(_GL_NUM_EXTENSIONS == GL_NUM_EXTENSIONS, "_GL_NUM_EXTENSIONS is not equal to GL_NUM_EXTENSIONS");
                    static_assert(_GL_CONTEXT_FLAGS == GL_CONTEXT_FLAGS, "_GL_CONTEXT_FLAGS is not equal to GL_CONTEXT_FLAGS");
                    static_assert(_GL_COMPRESSED_RED == GL_COMPRESSED_RED, "_GL_COMPRESSED_RED is not equal to GL_COMPRESSED_RED");
                    static_assert(_GL_COMPRESSED_RG == GL_COMPRESSED_RG, "_GL_COMPRESSED_RG is not equal to GL_COMPRESSED_RG");
                    static_assert(_GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT == GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT, "_GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT is not equal to GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT");
                    static_assert(_GL_RGBA32F == GL_RGBA32F, "_GL_RGBA32F is not equal to GL_RGBA32F");
                    static_assert(_GL_RGB32F == GL_RGB32F, "_GL_RGB32F is not equal to GL_RGB32F");
                    static_assert(_GL_RGBA16F == GL_RGBA16F, "_GL_RGBA16F is not equal to GL_RGBA16F");
                    static_assert(_GL_RGB16F == GL_RGB16F, "_GL_RGB16F is not equal to GL_RGB16F");
                    static_assert(_GL_VERTEX_ATTRIB_ARRAY_INTEGER == GL_VERTEX_ATTRIB_ARRAY_INTEGER, "_GL_VERTEX_ATTRIB_ARRAY_INTEGER is not equal to GL_VERTEX_ATTRIB_ARRAY_INTEGER");
                    static_assert(_GL_MAX_ARRAY_TEXTURE_LAYERS == GL_MAX_ARRAY_TEXTURE_LAYERS, "_GL_MAX_ARRAY_TEXTURE_LAYERS is not equal to GL_MAX_ARRAY_TEXTURE_LAYERS");
                    static_assert(_GL_MIN_PROGRAM_TEXEL_OFFSET == GL_MIN_PROGRAM_TEXEL_OFFSET, "_GL_MIN_PROGRAM_TEXEL_OFFSET is not equal to GL_MIN_PROGRAM_TEXEL_OFFSET");
                    static_assert(_GL_MAX_PROGRAM_TEXEL_OFFSET == GL_MAX_PROGRAM_TEXEL_OFFSET, "_GL_MAX_PROGRAM_TEXEL_OFFSET is not equal to GL_MAX_PROGRAM_TEXEL_OFFSET");
                    static_assert(_GL_CLAMP_READ_COLOR == GL_CLAMP_READ_COLOR, "_GL_CLAMP_READ_COLOR is not equal to GL_CLAMP_READ_COLOR");
                    static_assert(_GL_FIXED_ONLY == GL_FIXED_ONLY, "_GL_FIXED_ONLY is not equal to GL_FIXED_ONLY");
                    static_assert(_GL_MAX_VARYING_COMPONENTS == GL_MAX_VARYING_COMPONENTS, "_GL_MAX_VARYING_COMPONENTS is not equal to GL_MAX_VARYING_COMPONENTS");
                    static_assert(_GL_TEXTURE_1D_ARRAY == GL_TEXTURE_1D_ARRAY, "_GL_TEXTURE_1D_ARRAY is not equal to GL_TEXTURE_1D_ARRAY");
                    static_assert(_GL_PROXY_TEXTURE_1D_ARRAY == GL_PROXY_TEXTURE_1D_ARRAY, "_GL_PROXY_TEXTURE_1D_ARRAY is not equal to GL_PROXY_TEXTURE_1D_ARRAY");
                    static_assert(_GL_TEXTURE_2D_ARRAY == GL_TEXTURE_2D_ARRAY, "_GL_TEXTURE_2D_ARRAY is not equal to GL_TEXTURE_2D_ARRAY");
                    static_assert(_GL_PROXY_TEXTURE_2D_ARRAY == GL_PROXY_TEXTURE_2D_ARRAY, "_GL_PROXY_TEXTURE_2D_ARRAY is not equal to GL_PROXY_TEXTURE_2D_ARRAY");
                    static_assert(_GL_TEXTURE_BINDING_1D_ARRAY == GL_TEXTURE_BINDING_1D_ARRAY, "_GL_TEXTURE_BINDING_1D_ARRAY is not equal to GL_TEXTURE_BINDING_1D_ARRAY");
                    static_assert(_GL_TEXTURE_BINDING_2D_ARRAY == GL_TEXTURE_BINDING_2D_ARRAY, "_GL_TEXTURE_BINDING_2D_ARRAY is not equal to GL_TEXTURE_BINDING_2D_ARRAY");
                    static_assert(_GL_R11F_G11F_B10F == GL_R11F_G11F_B10F, "_GL_R11F_G11F_B10F is not equal to GL_R11F_G11F_B10F");
                    static_assert(_GL_UNSIGNED_INT_10F_11F_11F_REV == GL_UNSIGNED_INT_10F_11F_11F_REV, "_GL_UNSIGNED_INT_10F_11F_11F_REV is not equal to GL_UNSIGNED_INT_10F_11F_11F_REV");
                    static_assert(_GL_RGB9_E5 == GL_RGB9_E5, "_GL_RGB9_E5 is not equal to GL_RGB9_E5");
                    static_assert(_GL_UNSIGNED_INT_5_9_9_9_REV == GL_UNSIGNED_INT_5_9_9_9_REV, "_GL_UNSIGNED_INT_5_9_9_9_REV is not equal to GL_UNSIGNED_INT_5_9_9_9_REV");
                    static_assert(_GL_TEXTURE_SHARED_SIZE == GL_TEXTURE_SHARED_SIZE, "_GL_TEXTURE_SHARED_SIZE is not equal to GL_TEXTURE_SHARED_SIZE");
                    static_assert(_GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH == GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH, "_GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH is not equal to GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH");
                    static_assert(_GL_TRANSFORM_FEEDBACK_BUFFER_MODE == GL_TRANSFORM_FEEDBACK_BUFFER_MODE, "_GL_TRANSFORM_FEEDBACK_BUFFER_MODE is not equal to GL_TRANSFORM_FEEDBACK_BUFFER_MODE");
                    static_assert(_GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS == GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS, "_GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS is not equal to GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS");
                    static_assert(_GL_TRANSFORM_FEEDBACK_VARYINGS == GL_TRANSFORM_FEEDBACK_VARYINGS, "_GL_TRANSFORM_FEEDBACK_VARYINGS is not equal to GL_TRANSFORM_FEEDBACK_VARYINGS");
                    static_assert(_GL_TRANSFORM_FEEDBACK_BUFFER_START == GL_TRANSFORM_FEEDBACK_BUFFER_START, "_GL_TRANSFORM_FEEDBACK_BUFFER_START is not equal to GL_TRANSFORM_FEEDBACK_BUFFER_START");
                    static_assert(_GL_TRANSFORM_FEEDBACK_BUFFER_SIZE == GL_TRANSFORM_FEEDBACK_BUFFER_SIZE, "_GL_TRANSFORM_FEEDBACK_BUFFER_SIZE is not equal to GL_TRANSFORM_FEEDBACK_BUFFER_SIZE");
                    static_assert(_GL_PRIMITIVES_GENERATED == GL_PRIMITIVES_GENERATED, "_GL_PRIMITIVES_GENERATED is not equal to GL_PRIMITIVES_GENERATED");
                    static_assert(_GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN == GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN, "_GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN is not equal to GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN");
                    static_assert(_GL_RASTERIZER_DISCARD == GL_RASTERIZER_DISCARD, "_GL_RASTERIZER_DISCARD is not equal to GL_RASTERIZER_DISCARD");
                    static_assert(_GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS == GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS, "_GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS is not equal to GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS");
                    static_assert(_GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS == GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS, "_GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS is not equal to GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS");
                    static_assert(_GL_INTERLEAVED_ATTRIBS == GL_INTERLEAVED_ATTRIBS, "_GL_INTERLEAVED_ATTRIBS is not equal to GL_INTERLEAVED_ATTRIBS");
                    static_assert(_GL_SEPARATE_ATTRIBS == GL_SEPARATE_ATTRIBS, "_GL_SEPARATE_ATTRIBS is not equal to GL_SEPARATE_ATTRIBS");
                    static_assert(_GL_TRANSFORM_FEEDBACK_BUFFER == GL_TRANSFORM_FEEDBACK_BUFFER, "_GL_TRANSFORM_FEEDBACK_BUFFER is not equal to GL_TRANSFORM_FEEDBACK_BUFFER");
                    static_assert(_GL_TRANSFORM_FEEDBACK_BUFFER_BINDING == GL_TRANSFORM_FEEDBACK_BUFFER_BINDING, "_GL_TRANSFORM_FEEDBACK_BUFFER_BINDING is not equal to GL_TRANSFORM_FEEDBACK_BUFFER_BINDING");
                    static_assert(_GL_RGBA32UI == GL_RGBA32UI, "_GL_RGBA32UI is not equal to GL_RGBA32UI");
                    static_assert(_GL_RGB32UI == GL_RGB32UI, "_GL_RGB32UI is not equal to GL_RGB32UI");
                    static_assert(_GL_RGBA16UI == GL_RGBA16UI, "_GL_RGBA16UI is not equal to GL_RGBA16UI");
                    static_assert(_GL_RGB16UI == GL_RGB16UI, "_GL_RGB16UI is not equal to GL_RGB16UI");
                    static_assert(_GL_RGBA8UI == GL_RGBA8UI, "_GL_RGBA8UI is not equal to GL_RGBA8UI");
                    static_assert(_GL_RGB8UI == GL_RGB8UI, "_GL_RGB8UI is not equal to GL_RGB8UI");
                    static_assert(_GL_RGBA32I == GL_RGBA32I, "_GL_RGBA32I is not equal to GL_RGBA32I");
                    static_assert(_GL_RGB32I == GL_RGB32I, "_GL_RGB32I is not equal to GL_RGB32I");
                    static_assert(_GL_RGBA16I == GL_RGBA16I, "_GL_RGBA16I is not equal to GL_RGBA16I");
                    static_assert(_GL_RGB16I == GL_RGB16I, "_GL_RGB16I is not equal to GL_RGB16I");
                    static_assert(_GL_RGBA8I == GL_RGBA8I, "_GL_RGBA8I is not equal to GL_RGBA8I");
                    static_assert(_GL_RGB8I == GL_RGB8I, "_GL_RGB8I is not equal to GL_RGB8I");
                    static_assert(_GL_RED_INTEGER == GL_RED_INTEGER, "_GL_RED_INTEGER is not equal to GL_RED_INTEGER");
                    static_assert(_GL_GREEN_INTEGER == GL_GREEN_INTEGER, "_GL_GREEN_INTEGER is not equal to GL_GREEN_INTEGER");
                    static_assert(_GL_BLUE_INTEGER == GL_BLUE_INTEGER, "_GL_BLUE_INTEGER is not equal to GL_BLUE_INTEGER");
                    static_assert(_GL_RGB_INTEGER == GL_RGB_INTEGER, "_GL_RGB_INTEGER is not equal to GL_RGB_INTEGER");
                    static_assert(_GL_RGBA_INTEGER == GL_RGBA_INTEGER, "_GL_RGBA_INTEGER is not equal to GL_RGBA_INTEGER");
                    static_assert(_GL_BGR_INTEGER == GL_BGR_INTEGER, "_GL_BGR_INTEGER is not equal to GL_BGR_INTEGER");
                    static_assert(_GL_BGRA_INTEGER == GL_BGRA_INTEGER, "_GL_BGRA_INTEGER is not equal to GL_BGRA_INTEGER");
                    static_assert(_GL_SAMPLER_1D_ARRAY == GL_SAMPLER_1D_ARRAY, "_GL_SAMPLER_1D_ARRAY is not equal to GL_SAMPLER_1D_ARRAY");
                    static_assert(_GL_SAMPLER_2D_ARRAY == GL_SAMPLER_2D_ARRAY, "_GL_SAMPLER_2D_ARRAY is not equal to GL_SAMPLER_2D_ARRAY");
                    static_assert(_GL_SAMPLER_1D_ARRAY_SHADOW == GL_SAMPLER_1D_ARRAY_SHADOW, "_GL_SAMPLER_1D_ARRAY_SHADOW is not equal to GL_SAMPLER_1D_ARRAY_SHADOW");
                    static_assert(_GL_SAMPLER_2D_ARRAY_SHADOW == GL_SAMPLER_2D_ARRAY_SHADOW, "_GL_SAMPLER_2D_ARRAY_SHADOW is not equal to GL_SAMPLER_2D_ARRAY_SHADOW");
                    static_assert(_GL_SAMPLER_CUBE_SHADOW == GL_SAMPLER_CUBE_SHADOW, "_GL_SAMPLER_CUBE_SHADOW is not equal to GL_SAMPLER_CUBE_SHADOW");
                    static_assert(_GL_UNSIGNED_INT_VEC2 == GL_UNSIGNED_INT_VEC2, "_GL_UNSIGNED_INT_VEC2 is not equal to GL_UNSIGNED_INT_VEC2");
                    static_assert(_GL_UNSIGNED_INT_VEC3 == GL_UNSIGNED_INT_VEC3, "_GL_UNSIGNED_INT_VEC3 is not equal to GL_UNSIGNED_INT_VEC3");
                    static_assert(_GL_UNSIGNED_INT_VEC4 == GL_UNSIGNED_INT_VEC4, "_GL_UNSIGNED_INT_VEC4 is not equal to GL_UNSIGNED_INT_VEC4");
                    static_assert(_GL_INT_SAMPLER_1D == GL_INT_SAMPLER_1D, "_GL_INT_SAMPLER_1D is not equal to GL_INT_SAMPLER_1D");
                    static_assert(_GL_INT_SAMPLER_2D == GL_INT_SAMPLER_2D, "_GL_INT_SAMPLER_2D is not equal to GL_INT_SAMPLER_2D");
                    static_assert(_GL_INT_SAMPLER_3D == GL_INT_SAMPLER_3D, "_GL_INT_SAMPLER_3D is not equal to GL_INT_SAMPLER_3D");
                    static_assert(_GL_INT_SAMPLER_CUBE == GL_INT_SAMPLER_CUBE, "_GL_INT_SAMPLER_CUBE is not equal to GL_INT_SAMPLER_CUBE");
                    static_assert(_GL_INT_SAMPLER_1D_ARRAY == GL_INT_SAMPLER_1D_ARRAY, "_GL_INT_SAMPLER_1D_ARRAY is not equal to GL_INT_SAMPLER_1D_ARRAY");
                    static_assert(_GL_INT_SAMPLER_2D_ARRAY == GL_INT_SAMPLER_2D_ARRAY, "_GL_INT_SAMPLER_2D_ARRAY is not equal to GL_INT_SAMPLER_2D_ARRAY");
                    static_assert(_GL_UNSIGNED_INT_SAMPLER_1D == GL_UNSIGNED_INT_SAMPLER_1D, "_GL_UNSIGNED_INT_SAMPLER_1D is not equal to GL_UNSIGNED_INT_SAMPLER_1D");
                    static_assert(_GL_UNSIGNED_INT_SAMPLER_2D == GL_UNSIGNED_INT_SAMPLER_2D, "_GL_UNSIGNED_INT_SAMPLER_2D is not equal to GL_UNSIGNED_INT_SAMPLER_2D");
                    static_assert(_GL_UNSIGNED_INT_SAMPLER_3D == GL_UNSIGNED_INT_SAMPLER_3D, "_GL_UNSIGNED_INT_SAMPLER_3D is not equal to GL_UNSIGNED_INT_SAMPLER_3D");
                    static_assert(_GL_UNSIGNED_INT_SAMPLER_CUBE == GL_UNSIGNED_INT_SAMPLER_CUBE, "_GL_UNSIGNED_INT_SAMPLER_CUBE is not equal to GL_UNSIGNED_INT_SAMPLER_CUBE");
                    static_assert(_GL_UNSIGNED_INT_SAMPLER_1D_ARRAY == GL_UNSIGNED_INT_SAMPLER_1D_ARRAY, "_GL_UNSIGNED_INT_SAMPLER_1D_ARRAY is not equal to GL_UNSIGNED_INT_SAMPLER_1D_ARRAY");
                    static_assert(_GL_UNSIGNED_INT_SAMPLER_2D_ARRAY == GL_UNSIGNED_INT_SAMPLER_2D_ARRAY, "_GL_UNSIGNED_INT_SAMPLER_2D_ARRAY is not equal to GL_UNSIGNED_INT_SAMPLER_2D_ARRAY");
                    static_assert(_GL_QUERY_WAIT == GL_QUERY_WAIT, "_GL_QUERY_WAIT is not equal to GL_QUERY_WAIT");
                    static_assert(_GL_QUERY_NO_WAIT == GL_QUERY_NO_WAIT, "_GL_QUERY_NO_WAIT is not equal to GL_QUERY_NO_WAIT");
                    static_assert(_GL_QUERY_BY_REGION_WAIT == GL_QUERY_BY_REGION_WAIT, "_GL_QUERY_BY_REGION_WAIT is not equal to GL_QUERY_BY_REGION_WAIT");
                    static_assert(_GL_QUERY_BY_REGION_NO_WAIT == GL_QUERY_BY_REGION_NO_WAIT, "_GL_QUERY_BY_REGION_NO_WAIT is not equal to GL_QUERY_BY_REGION_NO_WAIT");
                    static_assert(_GL_BUFFER_ACCESS_FLAGS == GL_BUFFER_ACCESS_FLAGS, "_GL_BUFFER_ACCESS_FLAGS is not equal to GL_BUFFER_ACCESS_FLAGS");
                    static_assert(_GL_BUFFER_MAP_LENGTH == GL_BUFFER_MAP_LENGTH, "_GL_BUFFER_MAP_LENGTH is not equal to GL_BUFFER_MAP_LENGTH");
                    static_assert(_GL_BUFFER_MAP_OFFSET == GL_BUFFER_MAP_OFFSET, "_GL_BUFFER_MAP_OFFSET is not equal to GL_BUFFER_MAP_OFFSET");
                    static_assert(_GL_DEPTH_COMPONENT32F == GL_DEPTH_COMPONENT32F, "_GL_DEPTH_COMPONENT32F is not equal to GL_DEPTH_COMPONENT32F");
                    static_assert(_GL_DEPTH32F_STENCIL8 == GL_DEPTH32F_STENCIL8, "_GL_DEPTH32F_STENCIL8 is not equal to GL_DEPTH32F_STENCIL8");
                    static_assert(_GL_FLOAT_32_UNSIGNED_INT_24_8_REV == GL_FLOAT_32_UNSIGNED_INT_24_8_REV, "_GL_FLOAT_32_UNSIGNED_INT_24_8_REV is not equal to GL_FLOAT_32_UNSIGNED_INT_24_8_REV");
                    static_assert(_GL_INVALID_FRAMEBUFFER_OPERATION == GL_INVALID_FRAMEBUFFER_OPERATION, "_GL_INVALID_FRAMEBUFFER_OPERATION is not equal to GL_INVALID_FRAMEBUFFER_OPERATION");
                }
#endif
            }
        }
    }
}
#endif