#pragma once
#ifndef UE_GLAD_CONSTANTS_PART_6_INTERNAL_
#define UE_GLAD_CONSTANTS_PART_6_INTERNAL_
#ifndef __INTELLISENSE__
#ifndef UE_OPENGL_BUILD_
#error "this file should not be directly included in user code. use import UPRISE_ENGINE_CORE instead"
#endif
#endif
#include "OPENGL/GLAD/STUPIDMACROS/GLAD_MACROS.h"
#ifdef __INTELLISENSE__
#include <glad.h>
#endif // __INTELLISENSE__
namespace UPRISE_ENGINE {
    namespace RENDER {
        namespace GLAD {
            namespace CONSTANTS {
                constexpr int _GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = 0x8210;
                constexpr int _GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = 0x8211;
                constexpr int _GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = 0x8212;
                constexpr int _GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = 0x8213;
                constexpr int _GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = 0x8214;
                constexpr int _GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = 0x8215;
                constexpr int _GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = 0x8216;
                constexpr int _GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = 0x8217;
                constexpr int _GL_FRAMEBUFFER_DEFAULT = 0x8218;
                constexpr int _GL_FRAMEBUFFER_UNDEFINED = 0x8219;
                constexpr int _GL_DEPTH_STENCIL_ATTACHMENT = 0x821A;
                constexpr int _GL_MAX_RENDERBUFFER_SIZE = 0x84E8;
                constexpr int _GL_DEPTH_STENCIL = 0x84F9;
                constexpr int _GL_UNSIGNED_INT_24_8 = 0x84FA;
                constexpr int _GL_DEPTH24_STENCIL8 = 0x88F0;
                constexpr int _GL_TEXTURE_STENCIL_SIZE = 0x88F1;
                constexpr int _GL_TEXTURE_RED_TYPE = 0x8C10;
                constexpr int _GL_TEXTURE_GREEN_TYPE = 0x8C11;
                constexpr int _GL_TEXTURE_BLUE_TYPE = 0x8C12;
                constexpr int _GL_TEXTURE_ALPHA_TYPE = 0x8C13;
                constexpr int _GL_TEXTURE_DEPTH_TYPE = 0x8C16;
                constexpr int _GL_UNSIGNED_NORMALIZED = 0x8C17;
                constexpr int _GL_FRAMEBUFFER_BINDING = 0x8CA6;
                constexpr int _GL_DRAW_FRAMEBUFFER_BINDING = 0x8CA6;
                constexpr int _GL_RENDERBUFFER_BINDING = 0x8CA7;
                constexpr int _GL_READ_FRAMEBUFFER = 0x8CA8;
                constexpr int _GL_DRAW_FRAMEBUFFER = 0x8CA9;
                constexpr int _GL_READ_FRAMEBUFFER_BINDING = 0x8CAA;
                constexpr int _GL_RENDERBUFFER_SAMPLES = 0x8CAB;
                constexpr int _GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 0x8CD0;
                constexpr int _GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 0x8CD1;
                constexpr int _GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 0x8CD2;
                constexpr int _GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 0x8CD3;
                constexpr int _GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = 0x8CD4;
                constexpr int _GL_FRAMEBUFFER_COMPLETE = 0x8CD5;
                constexpr int _GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 0x8CD6;
                constexpr int _GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 0x8CD7;
                constexpr int _GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = 0x8CDB;
                constexpr int _GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER = 0x8CDC;
                constexpr int _GL_FRAMEBUFFER_UNSUPPORTED = 0x8CDD;
                constexpr int _GL_MAX_COLOR_ATTACHMENTS = 0x8CDF;
                constexpr int _GL_COLOR_ATTACHMENT0 = 0x8CE0;
                constexpr int _GL_COLOR_ATTACHMENT1 = 0x8CE1;
                constexpr int _GL_COLOR_ATTACHMENT2 = 0x8CE2;
                constexpr int _GL_COLOR_ATTACHMENT3 = 0x8CE3;
                constexpr int _GL_COLOR_ATTACHMENT4 = 0x8CE4;
                constexpr int _GL_COLOR_ATTACHMENT5 = 0x8CE5;
                constexpr int _GL_COLOR_ATTACHMENT6 = 0x8CE6;
                constexpr int _GL_COLOR_ATTACHMENT7 = 0x8CE7;
                constexpr int _GL_COLOR_ATTACHMENT8 = 0x8CE8;
                constexpr int _GL_COLOR_ATTACHMENT9 = 0x8CE9;
                constexpr int _GL_COLOR_ATTACHMENT10 = 0x8CEA;
                constexpr int _GL_COLOR_ATTACHMENT11 = 0x8CEB;
                constexpr int _GL_COLOR_ATTACHMENT12 = 0x8CEC;
                constexpr int _GL_COLOR_ATTACHMENT13 = 0x8CED;
                constexpr int _GL_COLOR_ATTACHMENT14 = 0x8CEE;
                constexpr int _GL_COLOR_ATTACHMENT15 = 0x8CEF;
                constexpr int _GL_COLOR_ATTACHMENT16 = 0x8CF0;
                constexpr int _GL_COLOR_ATTACHMENT17 = 0x8CF1;
                constexpr int _GL_COLOR_ATTACHMENT18 = 0x8CF2;
                constexpr int _GL_COLOR_ATTACHMENT19 = 0x8CF3;
                constexpr int _GL_COLOR_ATTACHMENT20 = 0x8CF4;
                constexpr int _GL_COLOR_ATTACHMENT21 = 0x8CF5;
                constexpr int _GL_COLOR_ATTACHMENT22 = 0x8CF6;
                constexpr int _GL_COLOR_ATTACHMENT23 = 0x8CF7;
                constexpr int _GL_COLOR_ATTACHMENT24 = 0x8CF8;
                constexpr int _GL_COLOR_ATTACHMENT25 = 0x8CF9;
                constexpr int _GL_COLOR_ATTACHMENT26 = 0x8CFA;
                constexpr int _GL_COLOR_ATTACHMENT27 = 0x8CFB;
                constexpr int _GL_COLOR_ATTACHMENT28 = 0x8CFC;
                constexpr int _GL_COLOR_ATTACHMENT29 = 0x8CFD;
                constexpr int _GL_COLOR_ATTACHMENT30 = 0x8CFE;
                constexpr int _GL_COLOR_ATTACHMENT31 = 0x8CFF;
                constexpr int _GL_DEPTH_ATTACHMENT = 0x8D00;
                constexpr int _GL_STENCIL_ATTACHMENT = 0x8D20;
                constexpr int _GL_FRAMEBUFFER = 0x8D40;
                constexpr int _GL_RENDERBUFFER = 0x8D41;
                constexpr int _GL_RENDERBUFFER_WIDTH = 0x8D42;
                constexpr int _GL_RENDERBUFFER_HEIGHT = 0x8D43;
                constexpr int _GL_RENDERBUFFER_INTERNAL_FORMAT = 0x8D44;
                constexpr int _GL_STENCIL_INDEX1 = 0x8D46;
                constexpr int _GL_STENCIL_INDEX4 = 0x8D47;
                constexpr int _GL_STENCIL_INDEX8 = 0x8D48;
                constexpr int _GL_STENCIL_INDEX16 = 0x8D49;
                constexpr int _GL_RENDERBUFFER_RED_SIZE = 0x8D50;
                constexpr int _GL_RENDERBUFFER_GREEN_SIZE = 0x8D51;
                constexpr int _GL_RENDERBUFFER_BLUE_SIZE = 0x8D52;
                constexpr int _GL_RENDERBUFFER_ALPHA_SIZE = 0x8D53;
                constexpr int _GL_RENDERBUFFER_DEPTH_SIZE = 0x8D54;
                constexpr int _GL_RENDERBUFFER_STENCIL_SIZE = 0x8D55;
                constexpr int _GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = 0x8D56;
                constexpr int _GL_MAX_SAMPLES = 0x8D57;
                constexpr int _GL_FRAMEBUFFER_SRGB = 0x8DB9;
                constexpr int _GL_HALF_FLOAT = 0x140B;
                constexpr int _GL_MAP_READ_BIT = 0x0001;
                constexpr int _GL_MAP_WRITE_BIT = 0x0002;
                constexpr int _GL_MAP_INVALIDATE_RANGE_BIT = 0x0004;
                constexpr int _GL_MAP_INVALIDATE_BUFFER_BIT = 0x0008;
                constexpr int _GL_MAP_FLUSH_EXPLICIT_BIT = 0x0010;
                constexpr int _GL_MAP_UNSYNCHRONIZED_BIT = 0x0020;
                constexpr int _GL_COMPRESSED_RED_RGTC1 = 0x8DBB;
                constexpr int _GL_COMPRESSED_SIGNED_RED_RGTC1 = 0x8DBC;
                constexpr int _GL_COMPRESSED_RG_RGTC2 = 0x8DBD;
                constexpr int _GL_COMPRESSED_SIGNED_RG_RGTC2 = 0x8DBE;
                constexpr int _GL_RG = 0x8227;
                constexpr int _GL_RG_INTEGER = 0x8228;
                constexpr int _GL_R8 = 0x8229;
                constexpr int _GL_R16 = 0x822A;
                constexpr int _GL_RG8 = 0x822B;
                constexpr int _GL_RG16 = 0x822C;
                constexpr int _GL_R16F = 0x822D;
                constexpr int _GL_R32F = 0x822E;
                constexpr int _GL_RG16F = 0x822F;
                constexpr int _GL_RG32F = 0x8230;
                constexpr int _GL_R8I = 0x8231;
                constexpr int _GL_R8UI = 0x8232;
                constexpr int _GL_R16I = 0x8233;
                constexpr int _GL_R16UI = 0x8234;
                constexpr int _GL_R32I = 0x8235;
                constexpr int _GL_R32UI = 0x8236;
                constexpr int _GL_RG8I = 0x8237;
                constexpr int _GL_RG8UI = 0x8238;
                constexpr int _GL_RG16I = 0x8239;
                constexpr int _GL_RG16UI = 0x823A;
                constexpr int _GL_RG32I = 0x823B;
                constexpr int _GL_RG32UI = 0x823C;
                constexpr int _GL_VERTEX_ARRAY_BINDING = 0x85B5;
                constexpr int _GL_SAMPLER_2D_RECT = 0x8B63;
                constexpr int _GL_SAMPLER_2D_RECT_SHADOW = 0x8B64;
                constexpr int _GL_SAMPLER_BUFFER = 0x8DC2;
                constexpr int _GL_INT_SAMPLER_2D_RECT = 0x8DCD;
                constexpr int _GL_INT_SAMPLER_BUFFER = 0x8DD0;
                constexpr int _GL_UNSIGNED_INT_SAMPLER_2D_RECT = 0x8DD5;
                constexpr int _GL_UNSIGNED_INT_SAMPLER_BUFFER = 0x8DD8;
                constexpr int _GL_TEXTURE_BUFFER = 0x8C2A;
                constexpr int _GL_MAX_TEXTURE_BUFFER_SIZE = 0x8C2B;
                constexpr int _GL_TEXTURE_BINDING_BUFFER = 0x8C2C;
                constexpr int _GL_TEXTURE_BUFFER_DATA_STORE_BINDING = 0x8C2D;
                constexpr int _GL_TEXTURE_RECTANGLE = 0x84F5;
                constexpr int _GL_TEXTURE_BINDING_RECTANGLE = 0x84F6;
                constexpr int _GL_PROXY_TEXTURE_RECTANGLE = 0x84F7;
                constexpr int _GL_MAX_RECTANGLE_TEXTURE_SIZE = 0x84F8;
                constexpr int _GL_R8_SNORM = 0x8F94;
                constexpr int _GL_RG8_SNORM = 0x8F95;
                constexpr int _GL_RGB8_SNORM = 0x8F96;
                constexpr int _GL_RGBA8_SNORM = 0x8F97;
                constexpr int _GL_R16_SNORM = 0x8F98;
                constexpr int _GL_RG16_SNORM = 0x8F99;
                constexpr int _GL_RGB16_SNORM = 0x8F9A;
                constexpr int _GL_RGBA16_SNORM = 0x8F9B;
                consteval void CheckConstantsPart6() {
                    static_assert(_GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING == GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING, "_GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING is not equal to GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING");
                    static_assert(_GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE == GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE, "_GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE is not equal to GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE");
                    static_assert(_GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE == GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE, "_GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE is not equal to GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE");
                    static_assert(_GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE == GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE, "_GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE is not equal to GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE");
                    static_assert(_GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE == GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE, "_GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE is not equal to GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE");
                    static_assert(_GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE == GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE, "_GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE is not equal to GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE");
                    static_assert(_GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE == GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE, "_GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE is not equal to GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE");
                    static_assert(_GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE == GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE, "_GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE is not equal to GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE");
                    static_assert(_GL_FRAMEBUFFER_DEFAULT == GL_FRAMEBUFFER_DEFAULT, "_GL_FRAMEBUFFER_DEFAULT is not equal to GL_FRAMEBUFFER_DEFAULT");
                    static_assert(_GL_FRAMEBUFFER_UNDEFINED == GL_FRAMEBUFFER_UNDEFINED, "_GL_FRAMEBUFFER_UNDEFINED is not equal to GL_FRAMEBUFFER_UNDEFINED");
                    static_assert(_GL_DEPTH_STENCIL_ATTACHMENT == GL_DEPTH_STENCIL_ATTACHMENT, "_GL_DEPTH_STENCIL_ATTACHMENT is not equal to GL_DEPTH_STENCIL_ATTACHMENT");
                    static_assert(_GL_MAX_RENDERBUFFER_SIZE == GL_MAX_RENDERBUFFER_SIZE, "_GL_MAX_RENDERBUFFER_SIZE is not equal to GL_MAX_RENDERBUFFER_SIZE");
                    static_assert(_GL_DEPTH_STENCIL == GL_DEPTH_STENCIL, "_GL_DEPTH_STENCIL is not equal to GL_DEPTH_STENCIL");
                    static_assert(_GL_UNSIGNED_INT_24_8 == GL_UNSIGNED_INT_24_8, "_GL_UNSIGNED_INT_24_8 is not equal to GL_UNSIGNED_INT_24_8");
                    static_assert(_GL_DEPTH24_STENCIL8 == GL_DEPTH24_STENCIL8, "_GL_DEPTH24_STENCIL8 is not equal to GL_DEPTH24_STENCIL8");
                    static_assert(_GL_TEXTURE_STENCIL_SIZE == GL_TEXTURE_STENCIL_SIZE, "_GL_TEXTURE_STENCIL_SIZE is not equal to GL_TEXTURE_STENCIL_SIZE");
                    static_assert(_GL_TEXTURE_RED_TYPE == GL_TEXTURE_RED_TYPE, "_GL_TEXTURE_RED_TYPE is not equal to GL_TEXTURE_RED_TYPE");
                    static_assert(_GL_TEXTURE_GREEN_TYPE == GL_TEXTURE_GREEN_TYPE, "_GL_TEXTURE_GREEN_TYPE is not equal to GL_TEXTURE_GREEN_TYPE");
                    static_assert(_GL_TEXTURE_BLUE_TYPE == GL_TEXTURE_BLUE_TYPE, "_GL_TEXTURE_BLUE_TYPE is not equal to GL_TEXTURE_BLUE_TYPE");
                    static_assert(_GL_TEXTURE_ALPHA_TYPE == GL_TEXTURE_ALPHA_TYPE, "_GL_TEXTURE_ALPHA_TYPE is not equal to GL_TEXTURE_ALPHA_TYPE");
                    static_assert(_GL_TEXTURE_DEPTH_TYPE == GL_TEXTURE_DEPTH_TYPE, "_GL_TEXTURE_DEPTH_TYPE is not equal to GL_TEXTURE_DEPTH_TYPE");
                    static_assert(_GL_UNSIGNED_NORMALIZED == GL_UNSIGNED_NORMALIZED, "_GL_UNSIGNED_NORMALIZED is not equal to GL_UNSIGNED_NORMALIZED");
                    static_assert(_GL_FRAMEBUFFER_BINDING == GL_FRAMEBUFFER_BINDING, "_GL_FRAMEBUFFER_BINDING is not equal to GL_FRAMEBUFFER_BINDING");
                    static_assert(_GL_DRAW_FRAMEBUFFER_BINDING == GL_DRAW_FRAMEBUFFER_BINDING, "_GL_DRAW_FRAMEBUFFER_BINDING is not equal to GL_DRAW_FRAMEBUFFER_BINDING");
                    static_assert(_GL_RENDERBUFFER_BINDING == GL_RENDERBUFFER_BINDING, "_GL_RENDERBUFFER_BINDING is not equal to GL_RENDERBUFFER_BINDING");
                    static_assert(_GL_READ_FRAMEBUFFER == GL_READ_FRAMEBUFFER, "_GL_READ_FRAMEBUFFER is not equal to GL_READ_FRAMEBUFFER");
                    static_assert(_GL_DRAW_FRAMEBUFFER == GL_DRAW_FRAMEBUFFER, "_GL_DRAW_FRAMEBUFFER is not equal to GL_DRAW_FRAMEBUFFER");
                    static_assert(_GL_READ_FRAMEBUFFER_BINDING == GL_READ_FRAMEBUFFER_BINDING, "_GL_READ_FRAMEBUFFER_BINDING is not equal to GL_READ_FRAMEBUFFER_BINDING");
                    static_assert(_GL_RENDERBUFFER_SAMPLES == GL_RENDERBUFFER_SAMPLES, "_GL_RENDERBUFFER_SAMPLES is not equal to GL_RENDERBUFFER_SAMPLES");
                    static_assert(_GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE == GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE, "_GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE is not equal to GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE");
                    static_assert(_GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME == GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME, "_GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME is not equal to GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME");
                    static_assert(_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL == GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL, "_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL is not equal to GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL");
                    static_assert(_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE == GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE, "_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE is not equal to GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE");
                    static_assert(_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER == GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER, "_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER is not equal to GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER");
                    static_assert(_GL_FRAMEBUFFER_COMPLETE == GL_FRAMEBUFFER_COMPLETE, "_GL_FRAMEBUFFER_COMPLETE is not equal to GL_FRAMEBUFFER_COMPLETE");
                    static_assert(_GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT == GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT, "_GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT is not equal to GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT");
                    static_assert(_GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT == GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT, "_GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT is not equal to GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT");
                    static_assert(_GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER == GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER, "_GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER is not equal to GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER");
                    static_assert(_GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER == GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER, "_GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER is not equal to GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER");
                    static_assert(_GL_FRAMEBUFFER_UNSUPPORTED == GL_FRAMEBUFFER_UNSUPPORTED, "_GL_FRAMEBUFFER_UNSUPPORTED is not equal to GL_FRAMEBUFFER_UNSUPPORTED");
                    static_assert(_GL_MAX_COLOR_ATTACHMENTS == GL_MAX_COLOR_ATTACHMENTS, "_GL_MAX_COLOR_ATTACHMENTS is not equal to GL_MAX_COLOR_ATTACHMENTS");
                    static_assert(_GL_COLOR_ATTACHMENT0 == GL_COLOR_ATTACHMENT0, "_GL_COLOR_ATTACHMENT0 is not equal to GL_COLOR_ATTACHMENT0");
                    static_assert(_GL_COLOR_ATTACHMENT1 == GL_COLOR_ATTACHMENT1, "_GL_COLOR_ATTACHMENT1 is not equal to GL_COLOR_ATTACHMENT1");
                    static_assert(_GL_COLOR_ATTACHMENT2 == GL_COLOR_ATTACHMENT2, "_GL_COLOR_ATTACHMENT2 is not equal to GL_COLOR_ATTACHMENT2");
                    static_assert(_GL_COLOR_ATTACHMENT3 == GL_COLOR_ATTACHMENT3, "_GL_COLOR_ATTACHMENT3 is not equal to GL_COLOR_ATTACHMENT3");
                    static_assert(_GL_COLOR_ATTACHMENT4 == GL_COLOR_ATTACHMENT4, "_GL_COLOR_ATTACHMENT4 is not equal to GL_COLOR_ATTACHMENT4");
                    static_assert(_GL_COLOR_ATTACHMENT5 == GL_COLOR_ATTACHMENT5, "_GL_COLOR_ATTACHMENT5 is not equal to GL_COLOR_ATTACHMENT5");
                    static_assert(_GL_COLOR_ATTACHMENT6 == GL_COLOR_ATTACHMENT6, "_GL_COLOR_ATTACHMENT6 is not equal to GL_COLOR_ATTACHMENT6");
                    static_assert(_GL_COLOR_ATTACHMENT7 == GL_COLOR_ATTACHMENT7, "_GL_COLOR_ATTACHMENT7 is not equal to GL_COLOR_ATTACHMENT7");
                    static_assert(_GL_COLOR_ATTACHMENT8 == GL_COLOR_ATTACHMENT8, "_GL_COLOR_ATTACHMENT8 is not equal to GL_COLOR_ATTACHMENT8");
                    static_assert(_GL_COLOR_ATTACHMENT9 == GL_COLOR_ATTACHMENT9, "_GL_COLOR_ATTACHMENT9 is not equal to GL_COLOR_ATTACHMENT9");
                    static_assert(_GL_COLOR_ATTACHMENT10 == GL_COLOR_ATTACHMENT10, "_GL_COLOR_ATTACHMENT10 is not equal to GL_COLOR_ATTACHMENT10");
                    static_assert(_GL_COLOR_ATTACHMENT11 == GL_COLOR_ATTACHMENT11, "_GL_COLOR_ATTACHMENT11 is not equal to GL_COLOR_ATTACHMENT11");
                    static_assert(_GL_COLOR_ATTACHMENT12 == GL_COLOR_ATTACHMENT12, "_GL_COLOR_ATTACHMENT12 is not equal to GL_COLOR_ATTACHMENT12");
                    static_assert(_GL_COLOR_ATTACHMENT13 == GL_COLOR_ATTACHMENT13, "_GL_COLOR_ATTACHMENT13 is not equal to GL_COLOR_ATTACHMENT13");
                    static_assert(_GL_COLOR_ATTACHMENT14 == GL_COLOR_ATTACHMENT14, "_GL_COLOR_ATTACHMENT14 is not equal to GL_COLOR_ATTACHMENT14");
                    static_assert(_GL_COLOR_ATTACHMENT15 == GL_COLOR_ATTACHMENT15, "_GL_COLOR_ATTACHMENT15 is not equal to GL_COLOR_ATTACHMENT15");
                    static_assert(_GL_COLOR_ATTACHMENT16 == GL_COLOR_ATTACHMENT16, "_GL_COLOR_ATTACHMENT16 is not equal to GL_COLOR_ATTACHMENT16");
                    static_assert(_GL_COLOR_ATTACHMENT17 == GL_COLOR_ATTACHMENT17, "_GL_COLOR_ATTACHMENT17 is not equal to GL_COLOR_ATTACHMENT17");
                    static_assert(_GL_COLOR_ATTACHMENT18 == GL_COLOR_ATTACHMENT18, "_GL_COLOR_ATTACHMENT18 is not equal to GL_COLOR_ATTACHMENT18");
                    static_assert(_GL_COLOR_ATTACHMENT19 == GL_COLOR_ATTACHMENT19, "_GL_COLOR_ATTACHMENT19 is not equal to GL_COLOR_ATTACHMENT19");
                    static_assert(_GL_COLOR_ATTACHMENT20 == GL_COLOR_ATTACHMENT20, "_GL_COLOR_ATTACHMENT20 is not equal to GL_COLOR_ATTACHMENT20");
                    static_assert(_GL_COLOR_ATTACHMENT21 == GL_COLOR_ATTACHMENT21, "_GL_COLOR_ATTACHMENT21 is not equal to GL_COLOR_ATTACHMENT21");
                    static_assert(_GL_COLOR_ATTACHMENT22 == GL_COLOR_ATTACHMENT22, "_GL_COLOR_ATTACHMENT22 is not equal to GL_COLOR_ATTACHMENT22");
                    static_assert(_GL_COLOR_ATTACHMENT23 == GL_COLOR_ATTACHMENT23, "_GL_COLOR_ATTACHMENT23 is not equal to GL_COLOR_ATTACHMENT23");
                    static_assert(_GL_COLOR_ATTACHMENT24 == GL_COLOR_ATTACHMENT24, "_GL_COLOR_ATTACHMENT24 is not equal to GL_COLOR_ATTACHMENT24");
                    static_assert(_GL_COLOR_ATTACHMENT25 == GL_COLOR_ATTACHMENT25, "_GL_COLOR_ATTACHMENT25 is not equal to GL_COLOR_ATTACHMENT25");
                    static_assert(_GL_COLOR_ATTACHMENT26 == GL_COLOR_ATTACHMENT26, "_GL_COLOR_ATTACHMENT26 is not equal to GL_COLOR_ATTACHMENT26");
                    static_assert(_GL_COLOR_ATTACHMENT27 == GL_COLOR_ATTACHMENT27, "_GL_COLOR_ATTACHMENT27 is not equal to GL_COLOR_ATTACHMENT27");
                    static_assert(_GL_COLOR_ATTACHMENT28 == GL_COLOR_ATTACHMENT28, "_GL_COLOR_ATTACHMENT28 is not equal to GL_COLOR_ATTACHMENT28");
                    static_assert(_GL_COLOR_ATTACHMENT29 == GL_COLOR_ATTACHMENT29, "_GL_COLOR_ATTACHMENT29 is not equal to GL_COLOR_ATTACHMENT29");
                    static_assert(_GL_COLOR_ATTACHMENT30 == GL_COLOR_ATTACHMENT30, "_GL_COLOR_ATTACHMENT30 is not equal to GL_COLOR_ATTACHMENT30");
                    static_assert(_GL_COLOR_ATTACHMENT31 == GL_COLOR_ATTACHMENT31, "_GL_COLOR_ATTACHMENT31 is not equal to GL_COLOR_ATTACHMENT31");
                    static_assert(_GL_DEPTH_ATTACHMENT == GL_DEPTH_ATTACHMENT, "_GL_DEPTH_ATTACHMENT is not equal to GL_DEPTH_ATTACHMENT");
                    static_assert(_GL_STENCIL_ATTACHMENT == GL_STENCIL_ATTACHMENT, "_GL_STENCIL_ATTACHMENT is not equal to GL_STENCIL_ATTACHMENT");
                    static_assert(_GL_FRAMEBUFFER == GL_FRAMEBUFFER, "_GL_FRAMEBUFFER is not equal to GL_FRAMEBUFFER");
                    static_assert(_GL_RENDERBUFFER == GL_RENDERBUFFER, "_GL_RENDERBUFFER is not equal to GL_RENDERBUFFER");
                    static_assert(_GL_RENDERBUFFER_WIDTH == GL_RENDERBUFFER_WIDTH, "_GL_RENDERBUFFER_WIDTH is not equal to GL_RENDERBUFFER_WIDTH");
                    static_assert(_GL_RENDERBUFFER_HEIGHT == GL_RENDERBUFFER_HEIGHT, "_GL_RENDERBUFFER_HEIGHT is not equal to GL_RENDERBUFFER_HEIGHT");
                    static_assert(_GL_RENDERBUFFER_INTERNAL_FORMAT == GL_RENDERBUFFER_INTERNAL_FORMAT, "_GL_RENDERBUFFER_INTERNAL_FORMAT is not equal to GL_RENDERBUFFER_INTERNAL_FORMAT");
                    static_assert(_GL_STENCIL_INDEX1 == GL_STENCIL_INDEX1, "_GL_STENCIL_INDEX1 is not equal to GL_STENCIL_INDEX1");
                    static_assert(_GL_STENCIL_INDEX4 == GL_STENCIL_INDEX4, "_GL_STENCIL_INDEX4 is not equal to GL_STENCIL_INDEX4");
                    static_assert(_GL_STENCIL_INDEX8 == GL_STENCIL_INDEX8, "_GL_STENCIL_INDEX8 is not equal to GL_STENCIL_INDEX8");
                    static_assert(_GL_STENCIL_INDEX16 == GL_STENCIL_INDEX16, "_GL_STENCIL_INDEX16 is not equal to GL_STENCIL_INDEX16");
                    static_assert(_GL_RENDERBUFFER_RED_SIZE == GL_RENDERBUFFER_RED_SIZE, "_GL_RENDERBUFFER_RED_SIZE is not equal to GL_RENDERBUFFER_RED_SIZE");
                    static_assert(_GL_RENDERBUFFER_GREEN_SIZE == GL_RENDERBUFFER_GREEN_SIZE, "_GL_RENDERBUFFER_GREEN_SIZE is not equal to GL_RENDERBUFFER_GREEN_SIZE");
                    static_assert(_GL_RENDERBUFFER_BLUE_SIZE == GL_RENDERBUFFER_BLUE_SIZE, "_GL_RENDERBUFFER_BLUE_SIZE is not equal to GL_RENDERBUFFER_BLUE_SIZE");
                    static_assert(_GL_RENDERBUFFER_ALPHA_SIZE == GL_RENDERBUFFER_ALPHA_SIZE, "_GL_RENDERBUFFER_ALPHA_SIZE is not equal to GL_RENDERBUFFER_ALPHA_SIZE");
                    static_assert(_GL_RENDERBUFFER_DEPTH_SIZE == GL_RENDERBUFFER_DEPTH_SIZE, "_GL_RENDERBUFFER_DEPTH_SIZE is not equal to GL_RENDERBUFFER_DEPTH_SIZE");
                    static_assert(_GL_RENDERBUFFER_STENCIL_SIZE == GL_RENDERBUFFER_STENCIL_SIZE, "_GL_RENDERBUFFER_STENCIL_SIZE is not equal to GL_RENDERBUFFER_STENCIL_SIZE");
                    static_assert(_GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE == GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE, "_GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE is not equal to GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE");
                    static_assert(_GL_MAX_SAMPLES == GL_MAX_SAMPLES, "_GL_MAX_SAMPLES is not equal to GL_MAX_SAMPLES");
                    static_assert(_GL_FRAMEBUFFER_SRGB == GL_FRAMEBUFFER_SRGB, "_GL_FRAMEBUFFER_SRGB is not equal to GL_FRAMEBUFFER_SRGB");
                    static_assert(_GL_HALF_FLOAT == GL_HALF_FLOAT, "_GL_HALF_FLOAT is not equal to GL_HALF_FLOAT");
                    static_assert(_GL_MAP_READ_BIT == GL_MAP_READ_BIT, "_GL_MAP_READ_BIT is not equal to GL_MAP_READ_BIT");
                    static_assert(_GL_MAP_WRITE_BIT == GL_MAP_WRITE_BIT, "_GL_MAP_WRITE_BIT is not equal to GL_MAP_WRITE_BIT");
                    static_assert(_GL_MAP_INVALIDATE_RANGE_BIT == GL_MAP_INVALIDATE_RANGE_BIT, "_GL_MAP_INVALIDATE_RANGE_BIT is not equal to GL_MAP_INVALIDATE_RANGE_BIT");
                    static_assert(_GL_MAP_INVALIDATE_BUFFER_BIT == GL_MAP_INVALIDATE_BUFFER_BIT, "_GL_MAP_INVALIDATE_BUFFER_BIT is not equal to GL_MAP_INVALIDATE_BUFFER_BIT");
                    static_assert(_GL_MAP_FLUSH_EXPLICIT_BIT == GL_MAP_FLUSH_EXPLICIT_BIT, "_GL_MAP_FLUSH_EXPLICIT_BIT is not equal to GL_MAP_FLUSH_EXPLICIT_BIT");
                    static_assert(_GL_MAP_UNSYNCHRONIZED_BIT == GL_MAP_UNSYNCHRONIZED_BIT, "_GL_MAP_UNSYNCHRONIZED_BIT is not equal to GL_MAP_UNSYNCHRONIZED_BIT");
                    static_assert(_GL_COMPRESSED_RED_RGTC1 == GL_COMPRESSED_RED_RGTC1, "_GL_COMPRESSED_RED_RGTC1 is not equal to GL_COMPRESSED_RED_RGTC1");
                    static_assert(_GL_COMPRESSED_SIGNED_RED_RGTC1 == GL_COMPRESSED_SIGNED_RED_RGTC1, "_GL_COMPRESSED_SIGNED_RED_RGTC1 is not equal to GL_COMPRESSED_SIGNED_RED_RGTC1");
                    static_assert(_GL_COMPRESSED_RG_RGTC2 == GL_COMPRESSED_RG_RGTC2, "_GL_COMPRESSED_RG_RGTC2 is not equal to GL_COMPRESSED_RG_RGTC2");
                    static_assert(_GL_COMPRESSED_SIGNED_RG_RGTC2 == GL_COMPRESSED_SIGNED_RG_RGTC2, "_GL_COMPRESSED_SIGNED_RG_RGTC2 is not equal to GL_COMPRESSED_SIGNED_RG_RGTC2");
                    static_assert(_GL_RG == GL_RG, "_GL_RG is not equal to GL_RG");
                    static_assert(_GL_RG_INTEGER == GL_RG_INTEGER, "_GL_RG_INTEGER is not equal to GL_RG_INTEGER");
                    static_assert(_GL_R8 == GL_R8, "_GL_R8 is not equal to GL_R8");
                    static_assert(_GL_R16 == GL_R16, "_GL_R16 is not equal to GL_R16");
                    static_assert(_GL_RG8 == GL_RG8, "_GL_RG8 is not equal to GL_RG8");
                    static_assert(_GL_RG16 == GL_RG16, "_GL_RG16 is not equal to GL_RG16");
                    static_assert(_GL_R16F == GL_R16F, "_GL_R16F is not equal to GL_R16F");
                    static_assert(_GL_R32F == GL_R32F, "_GL_R32F is not equal to GL_R32F");
                    static_assert(_GL_RG16F == GL_RG16F, "_GL_RG16F is not equal to GL_RG16F");
                    static_assert(_GL_RG32F == GL_RG32F, "_GL_RG32F is not equal to GL_RG32F");
                    static_assert(_GL_R8I == GL_R8I, "_GL_R8I is not equal to GL_R8I");
                    static_assert(_GL_R8UI == GL_R8UI, "_GL_R8UI is not equal to GL_R8UI");
                    static_assert(_GL_R16I == GL_R16I, "_GL_R16I is not equal to GL_R16I");
                    static_assert(_GL_R16UI == GL_R16UI, "_GL_R16UI is not equal to GL_R16UI");
                    static_assert(_GL_R32I == GL_R32I, "_GL_R32I is not equal to GL_R32I");
                    static_assert(_GL_R32UI == GL_R32UI, "_GL_R32UI is not equal to GL_R32UI");
                    static_assert(_GL_RG8I == GL_RG8I, "_GL_RG8I is not equal to GL_RG8I");
                    static_assert(_GL_RG8UI == GL_RG8UI, "_GL_RG8UI is not equal to GL_RG8UI");
                    static_assert(_GL_RG16I == GL_RG16I, "_GL_RG16I is not equal to GL_RG16I");
                    static_assert(_GL_RG16UI == GL_RG16UI, "_GL_RG16UI is not equal to GL_RG16UI");
                    static_assert(_GL_RG32I == GL_RG32I, "_GL_RG32I is not equal to GL_RG32I");
                    static_assert(_GL_RG32UI == GL_RG32UI, "_GL_RG32UI is not equal to GL_RG32UI");
                    static_assert(_GL_VERTEX_ARRAY_BINDING == GL_VERTEX_ARRAY_BINDING, "_GL_VERTEX_ARRAY_BINDING is not equal to GL_VERTEX_ARRAY_BINDING");
                    static_assert(_GL_SAMPLER_2D_RECT == GL_SAMPLER_2D_RECT, "_GL_SAMPLER_2D_RECT is not equal to GL_SAMPLER_2D_RECT");
                    static_assert(_GL_SAMPLER_2D_RECT_SHADOW == GL_SAMPLER_2D_RECT_SHADOW, "_GL_SAMPLER_2D_RECT_SHADOW is not equal to GL_SAMPLER_2D_RECT_SHADOW");
                    static_assert(_GL_SAMPLER_BUFFER == GL_SAMPLER_BUFFER, "_GL_SAMPLER_BUFFER is not equal to GL_SAMPLER_BUFFER");
                    static_assert(_GL_INT_SAMPLER_2D_RECT == GL_INT_SAMPLER_2D_RECT, "_GL_INT_SAMPLER_2D_RECT is not equal to GL_INT_SAMPLER_2D_RECT");
                    static_assert(_GL_INT_SAMPLER_BUFFER == GL_INT_SAMPLER_BUFFER, "_GL_INT_SAMPLER_BUFFER is not equal to GL_INT_SAMPLER_BUFFER");
                    static_assert(_GL_UNSIGNED_INT_SAMPLER_2D_RECT == GL_UNSIGNED_INT_SAMPLER_2D_RECT, "_GL_UNSIGNED_INT_SAMPLER_2D_RECT is not equal to GL_UNSIGNED_INT_SAMPLER_2D_RECT");
                    static_assert(_GL_UNSIGNED_INT_SAMPLER_BUFFER == GL_UNSIGNED_INT_SAMPLER_BUFFER, "_GL_UNSIGNED_INT_SAMPLER_BUFFER is not equal to GL_UNSIGNED_INT_SAMPLER_BUFFER");
                    static_assert(_GL_TEXTURE_BUFFER == GL_TEXTURE_BUFFER, "_GL_TEXTURE_BUFFER is not equal to GL_TEXTURE_BUFFER");
                    static_assert(_GL_MAX_TEXTURE_BUFFER_SIZE == GL_MAX_TEXTURE_BUFFER_SIZE, "_GL_MAX_TEXTURE_BUFFER_SIZE is not equal to GL_MAX_TEXTURE_BUFFER_SIZE");
                    static_assert(_GL_TEXTURE_BINDING_BUFFER == GL_TEXTURE_BINDING_BUFFER, "_GL_TEXTURE_BINDING_BUFFER is not equal to GL_TEXTURE_BINDING_BUFFER");
                    static_assert(_GL_TEXTURE_BUFFER_DATA_STORE_BINDING == GL_TEXTURE_BUFFER_DATA_STORE_BINDING, "_GL_TEXTURE_BUFFER_DATA_STORE_BINDING is not equal to GL_TEXTURE_BUFFER_DATA_STORE_BINDING");
                    static_assert(_GL_TEXTURE_RECTANGLE == GL_TEXTURE_RECTANGLE, "_GL_TEXTURE_RECTANGLE is not equal to GL_TEXTURE_RECTANGLE");
                    static_assert(_GL_TEXTURE_BINDING_RECTANGLE == GL_TEXTURE_BINDING_RECTANGLE, "_GL_TEXTURE_BINDING_RECTANGLE is not equal to GL_TEXTURE_BINDING_RECTANGLE");
                    static_assert(_GL_PROXY_TEXTURE_RECTANGLE == GL_PROXY_TEXTURE_RECTANGLE, "_GL_PROXY_TEXTURE_RECTANGLE is not equal to GL_PROXY_TEXTURE_RECTANGLE");
                    static_assert(_GL_MAX_RECTANGLE_TEXTURE_SIZE == GL_MAX_RECTANGLE_TEXTURE_SIZE, "_GL_MAX_RECTANGLE_TEXTURE_SIZE is not equal to GL_MAX_RECTANGLE_TEXTURE_SIZE");
                    static_assert(_GL_R8_SNORM == GL_R8_SNORM, "_GL_R8_SNORM is not equal to GL_R8_SNORM");
                    static_assert(_GL_RG8_SNORM == GL_RG8_SNORM, "_GL_RG8_SNORM is not equal to GL_RG8_SNORM");
                    static_assert(_GL_RGB8_SNORM == GL_RGB8_SNORM, "_GL_RGB8_SNORM is not equal to GL_RGB8_SNORM");
                    static_assert(_GL_RGBA8_SNORM == GL_RGBA8_SNORM, "_GL_RGBA8_SNORM is not equal to GL_RGBA8_SNORM");
                    static_assert(_GL_R16_SNORM == GL_R16_SNORM, "_GL_R16_SNORM is not equal to GL_R16_SNORM");
                    static_assert(_GL_RG16_SNORM == GL_RG16_SNORM, "_GL_RG16_SNORM is not equal to GL_RG16_SNORM");
                    static_assert(_GL_RGB16_SNORM == GL_RGB16_SNORM, "_GL_RGB16_SNORM is not equal to GL_RGB16_SNORM");
                    static_assert(_GL_RGBA16_SNORM == GL_RGBA16_SNORM, "_GL_RGBA16_SNORM is not equal to GL_RGBA16_SNORM");
                }
            }
        }
    }
}
#endif